### ISSUE TITLE
`NuGetCommand@2` `push` commands are timing out occasionally

### ISSUE THREAD

**Issue by dougbu** [microsoft/azure-pipelines-tasks#10068]
### Question, Bug, or Feature?
*Type*: Bug
**Enter Task Name**: `NuGetCommand@2`

## Environment
- Server - Azure Pipelines
  - account: I'm not sure. **Where is this information visible in our pipeline?**
  - team project: I'm not sure. **Where is this information visible in our pipeline?**
  - owners are either .NET Core Engineering or Project K Runtime Engineering team
  - build definition names & numbers:
    - aspnet-Extensions release pipeline: Release master 20190408.2 - 1
      - https://dev.azure.com/dnceng/internal/_releaseProgress?_a=release-environment-logs&releaseId=4340&environmentId=9673
    - AspNetCore-Tooling-packages release pipeline: Release-241
      - https://dev.azure.com/dnceng/internal/_releaseProgress?_a=release-environment-logs&releaseId=4345&environmentId=9685
    - aspnet-AspNetCore release pipeline: 20190401.3 - master - rev 1
      - https://dev.azure.com/dnceng/internal/_releaseProgress?_a=release-environment-logs&releaseId=4071&environmentId=8915

- Agent - Hosted or Private:
    - If using Hosted agent, provide agent queue name: Hosted VS2017

## Issue Description
The `NuGetCommand@2` task used in our "NuGet push packages (Shipping and NonShipping only)" (AspNetCore-Tooling) or "Push symbols to aspnetcore-dev" (Extensions and AspNetCore) build steps in the "dotnet.myget.org (aspnetcore-dev)" jobs is executing NuGet commands that time out on an irregular basis. I didn't search around but believe we've also seen the "Push packages to aspnetcore-dev" task fail in the aspnet-AspNetCore pipeline with the same errors.

Note the command is timing out, not the overall task.

### Attempts to resolve
In reaction to the `You can change the default timeout of 300 seconds by using the -Timeout <seconds> option with the push command.` advice in the NuGet error, we tried to use a "custom" command for the `NuGetCommand@2` task. This attempt was entirely unsuccessful because we do not know the variable or parameter names for the API-Key or the current package. The command ended up failing silently (a NuGet bug I'll file shortly):
```
2019-04-08T15:29:38.9877533Z [command]C:\hostedtoolcache\windows\NuGet\5.0.0\x64\nuget.exe push -timeout 1000 -NonInteractive
2019-04-08T15:29:39.4574752Z push: invalid arguments.
2019-04-08T15:29:39.4575463Z usage: NuGet push <package path> [API key] [options]
2019-04-08T15:29:39.4575826Z 
2019-04-08T15:29:39.4576206Z Pushes a package to the server and publishes it.
2019-04-08T15:29:39.4576636Z NuGet's default configuration is obtained by loading %AppData%\NuGet\NuGet.config, then loading any nuget.config or .nuget\nuget.config starting from root of drive and ending in current directory.
2019-04-08T15:29:39.4577317Z 
2019-04-08T15:29:39.4577725Z      Specify the path to the package and your API key to push the package to the server.
2019-04-08T15:29:39.4578127Z 
2019-04-08T15:29:39.4578481Z options:
2019-04-08T15:29:39.4607430Z 
2019-04-08T15:29:39.4607686Z  -Source                  (src)                                  Specifies the server URL. If not specified, nuget.org is used unless DefaultPushSource config value is set in the NuGet config file.
2019-04-08T15:29:39.4607814Z  -ApiKey                                                         The API key for the server.
2019-04-08T15:29:39.4607949Z  -SymbolSource                                                   Specifies the symbol server URL. If not specified, nuget.smbsrc.net is used when pushing to nuget.org.
2019-04-08T15:29:39.4608063Z  -SymbolApiKey                                                   The API key for the symbol server.
2019-04-08T15:29:39.4608190Z  -Timeout                                                        Specifies the timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
2019-04-08T15:29:39.4608332Z  -DisableBuffering                                               Disable buffering when pushing to an HTTP(S) server to decrease memory usage. Note that when this option is enabled, integrated windows authentication might not work.
2019-04-08T15:29:39.4608511Z  -NoSymbols                                                      If a symbols package exists, it will not be pushed to a symbol server.
2019-04-08T15:29:39.4608618Z  -NoServiceEndpoint                                              Does not append "api/v2/packages" to the source URL.
2019-04-08T15:29:39.4608728Z  -Help                    (?)                                    help
2019-04-08T15:29:39.4608829Z  -Verbosity                                                      Display this amount of details in the output: normal, quiet, detailed.
2019-04-08T15:29:39.4608950Z  -NonInteractive                                                 Do not prompt for user input or confirmations.
2019-04-08T15:29:39.4609117Z  -ConfigFile                                                     The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. To learn more about NuGet configuration go to https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior.
2019-04-08T15:29:39.4610880Z  -ForceEnglishOutput                                             Forces the application to run using an invariant, English-based culture.
2019-04-08T15:29:39.4610950Z 
2019-04-08T15:29:39.4611027Z examples:
2019-04-08T15:29:39.4611066Z 
2019-04-08T15:29:39.4611130Z nuget push foo.nupkg 4003d786-cc37-4004-bfdf-c4f3e8ef9b3a
2019-04-08T15:29:39.4611198Z 
2019-04-08T15:29:39.4611270Z nuget push foo.nupkg 4003d786-cc37-4004-bfdf-c4f3e8ef9b3a -src http://customsource/
2019-04-08T15:29:39.4611323Z 
2019-04-08T15:29:39.4611394Z nuget push foo.nupkg
2019-04-08T15:29:39.4611435Z 
2019-04-08T15:29:39.4611491Z nuget push foo.nupkg.symbols
2019-04-08T15:29:39.4615257Z 
2019-04-08T15:29:39.4615354Z nuget push foo.nupkg -Timeout 360
2019-04-08T15:29:39.4615399Z 
2019-04-08T15:29:39.4615479Z For more information, visit http://docs.nuget.org/docs/reference/command-line-reference
```
(That was from https://dev.azure.com/dnceng/internal/_releaseProgress?_a=release-environment-logs&releaseId=4309&environmentId=9523)

### Request
Please add `-Timeout 1000` (or similar) to the NuGet commands this task executes. If that cannot be done, please make it possible to add command-line parameters to the NuGet commands via a new (optional) parameter to the task. If that also cannot be done, please provide the variable names needed to compose a custom command with the correct parameters.

### Task logs
```
2019-04-08T20:09:44.1396519Z [command]C:\hostedtoolcache\windows\NuGet\5.0.0\x64\nuget.exe push D:\a\r1\a\ci\artifacts\Release\Shipping\Microsoft.Extensions.Localization.Abstractions.3.0.0-preview5.19208.2.symbols.nupkg -NonInteractive -Source https://dotnet.myget.org/F/aspnetcore-dev/symbols/api/v2/package -ApiKey *** -ConfigFile D:\a\_temp\Nuget\tempNuGet_147347.config -Verbosity Detailed
2019-04-08T20:14:45.1680500Z NuGet Version: 5.0.0.5923
2019-04-08T20:14:45.1681531Z Pushing Microsoft.Extensions.Localization.Abstractions.3.0.0-preview5.19208.2.symbols.nupkg to 'https://dotnet.myget.org/F/aspnetcore-dev/symbols/api/v2/package'...
2019-04-08T20:14:45.1681754Z   PUT https://dotnet.myget.org/F/aspnetcore-dev/symbols/api/v2/package/
2019-04-08T20:14:45.1681904Z System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
2019-04-08T20:14:45.1682242Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1682551Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1682753Z    at NuGet.Protocol.TimeoutUtility.<StartWithTimeout>d__0`1.MoveNext()
2019-04-08T20:14:45.1682873Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1683278Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1683449Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1683590Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1683762Z    at NuGet.Protocol.HttpRetryHandler.<SendAsync>d__0.MoveNext()
2019-04-08T20:14:45.1683880Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1684042Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1684207Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1684334Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1684506Z    at NuGet.Protocol.HttpSource.<GetThrottledResponse>d__20.MoveNext()
2019-04-08T20:14:45.1684634Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1684799Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1684964Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1685115Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1685283Z    at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
2019-04-08T20:14:45.1685402Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1685563Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1686002Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1686248Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1686412Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__23.MoveNext()
2019-04-08T20:14:45.1686511Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1686642Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1687032Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1687618Z A task was canceled.
2019-04-08T20:14:45.1687769Z   Pushing took too long. You can change the default timeout of 300 seconds by using the -Timeout <seconds> option with the push command.
2019-04-08T20:14:45.1687886Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1688030Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext()
2019-04-08T20:14:45.1688170Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1688271Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1688403Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1688503Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1688654Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__19.MoveNext()
2019-04-08T20:14:45.1688952Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1689047Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1689178Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1689278Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1689419Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
2019-04-08T20:14:45.1689551Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1689720Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1689852Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1689962Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1690094Z    at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
2019-04-08T20:14:45.1690184Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1690315Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1690446Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1690547Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1690853Z    at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__32.MoveNext()
2019-04-08T20:14:45.1690942Z    --- End of inner exception stack trace ---
2019-04-08T20:14:45.1691066Z    at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__32.MoveNext()
2019-04-08T20:14:45.1691199Z ---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.
2019-04-08T20:14:45.1691302Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1691432Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1691528Z    at NuGet.Protocol.TimeoutUtility.<StartWithTimeout>d__0`1.MoveNext()
2019-04-08T20:14:45.1691657Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1691785Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1691875Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1692009Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1692427Z    at NuGet.Protocol.HttpRetryHandler.<SendAsync>d__0.MoveNext()
2019-04-08T20:14:45.1692598Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1692800Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1692965Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1693143Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1693268Z    at NuGet.Protocol.HttpSource.<GetThrottledResponse>d__20.MoveNext()
2019-04-08T20:14:45.1693435Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1693552Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1693712Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1693889Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1694016Z    at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
2019-04-08T20:14:45.1694178Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1694293Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1694441Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1694567Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1694742Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__23.MoveNext()
2019-04-08T20:14:45.1694905Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1695023Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1695259Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1695384Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1695566Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext()
2019-04-08T20:14:45.1695889Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1695985Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1696120Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1696222Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1696373Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__19.MoveNext()
2019-04-08T20:14:45.1696514Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1696615Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1696910Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1697184Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1697327Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
2019-04-08T20:14:45.1697419Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1697549Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1697675Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1697773Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1697898Z    at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
2019-04-08T20:14:45.1698162Z --- End of stack trace from previous location where exception was thrown ---
2019-04-08T20:14:45.1698301Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-08T20:14:45.1698431Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-04-08T20:14:45.1698599Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-08T20:14:45.1698736Z    at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__32.MoveNext()<---
2019-04-08T20:14:45.1698792Z 
2019-04-08T20:14:45.1698935Z ---> (Inner Exception #1) System.Exception: Pushing took too long. You can change the default timeout of 300 seconds by using the -Timeout <seconds> option with the push command.<---
2019-04-08T20:14:45.1699019Z 
2019-04-08T20:14:45.1930227Z ##[error]The nuget command failed with exit code(1) and error(A task was canceled.
  Pushing took too long. You can change the default timeout of 300 seconds by using the -Timeout <seconds> option with the push command.)
2019-04-08T20:14:45.1943880Z ##[error]Packages failed to publish
```

## See also
https://github.com/aspnet/AspNetCore-Internal/issues/2191

**Comment by salvmd** [comment]
Apologies for the slow response. Unfortunately, it's unlikely we will be adding other parameters to the task. We're looking to do an overhaul of our pipelines tasks in the near future, so we won't be making any improvements to the current tasks (@elbatk to confirm on this).
The only option left is, as you mentioned, to try with the custom command. As to what to pass in the API-Key parameter: that value is specific to myget and your configured access to their service, so we can't offer much guidance on that. Having said that, you probably have this value configured in a service connection already since the NuGet push works (when it doesn't time out).
From your task configuration (when the selected Command is "push"), see below under "NuGet server" the service connection you have selected. Click on "Manage" to go to the list of service connections. If you can't find it there, it might be that you don't have permissions to manage them and would need to find a user who does. Once you are able to see the service connection, the API-Key should be there.

**Comment by elbatk** [comment]
@dougbu hey there - we're taking a look at all of our "Artifacts" pipelines tasks in the coming quarter, and instead of trying to patch and fix the current ones, we're looking to change how our tasks are used in Azure Pipelines (mostly around auth & setup). Hopefully Salvador's response is helpful in the meantime!
