### ISSUE TITLE
Command Line Task v2: Cannot bind argument to parameter 'LiteralPath' because it is an empty string.

### ISSUE THREAD

**Issue by pgraham-acn** [microsoft/azure-pipelines-tasks#10156]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Command Line

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: pressganeyei, PGO-AUDIT-API, PGO-AUDIT-API-RELEASE-PATCH

- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Unknown

## Issue Description

script content:

```
git config user.email "*****************"
git config user.name "*****************"
```

### Task logs

```
##[debug]Evaluating condition for step: 'git config'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: git config
==============================================================================
Task         : Command Line
Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
Version      : 2.148.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
##[debug]VstsTaskSdk 0.9.0 commit 6c48b16164b9a1c9548776ad2062dad5cd543352
##[debug]Entering E:\preusprdaidvp02-agent02\_work\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.148.0\cmdline.ps1.
##[debug]Loading resource strings from: E:\preusprdaidvp02-agent02\_work\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.148.0\task.json
##[debug]Loaded 6 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: E:\preusprdaidvp02-agent02\_work\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.148.0\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 6 strings.
##[debug]INPUT_FAILONSTDERR: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_SCRIPT: 'git config user.email "buildmaster@pressganey.com"
##[debug]git config user.name "nPGO Release Build"'
##[debug]INPUT_WORKINGDIRECTORY: 'E:\preusprdaidvp02-agent02\_work\110\s'
##[debug]Asserting container path exists: 'E:\preusprdaidvp02-agent02\_work\110\s'
Generating script.
##[debug]AGENT_VERSION: '2.134.0'
##[debug]AGENT_TEMPDIRECTORY: 'E:\preusprdaidvp02-agent02\_work\_temp'
##[debug]Asserting container path exists: 'E:\preusprdaidvp02-agent02\_work\_temp'
##[debug]Leaving E:\preusprdaidvp02-agent02\_work\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.148.0\cmdline.ps1.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]E:\preusprdaidvp02-agent02\_work\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.148.0\cmdline.ps1 : Cannot bind argument to parameter 'LiteralPath' because it is an empty string.
##[debug]At line:1 char:1
##[debug]+ . 'E:\preusprdaidvp02-agent02\_work\_tasks\CmdLine_d9bafed4-0b18-4f58 ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidData: (:) [cmdline.ps1], ParameterBindingValidationException
##[debug]    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,cmdline.ps1
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, E:\preusprdaidvp02-agent02\_work\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.148.0\cmdline.ps1: line 42
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'LiteralPath' because it is an empty string.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
##[error]Cannot bind argument to parameter 'LiteralPath' because it is an empty string.
##[debug]Processed: ##vso[task.logissue type=error]Cannot bind argument to parameter 'LiteralPath' because it is an empty string.
##[debug]Processed: ##vso[task.complete result=Failed]
##[section]Finishing: git config
```

**Comment by pgraham-acn** [comment]
Just tried with a Hosted agent from VS2017 and the build succeeded. Does this mean that I need to get the agent in the Private queue updated?

**Comment by sebdau** [comment]
I'm experiencing a similiar error on a most recent self-hosted agent 2.153.2.

this is the cmd tasks yaml:

```
steps:
- script: 'echo test'
  workingDirectory: 'C:\Testing\'
  displayName: 'Command Line Script'
```

**Comment by damccorm** [comment]
Hey, it sounds like this is an agent issue - could you please log it at https://github.com/microsoft/azure-pipelines-agent? That way it gets routed correctly.

I'm going to close here since this isn't a tasks issue, if you think it should be reopened feel free to comment and we can reopen.

**Comment by damccorm** [comment]
Hey, it sounds like this is an agent issue - could you please log it at https://github.com/microsoft/azure-pipelines-agent? That way it gets routed correctly.

I'm going to close here since this isn't a tasks issue, if you think it should be reopened feel free to comment and we can reopen.
