### ISSUE TITLE
Cannot bind argument to parameter 'inputString' because it is an empty string.

### ISSUE THREAD

**Issue by Gordon-Beeming** [microsoft/azure-pipelines-tasks#10201]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SQL Server Database Deploy

## Environment
- Server - Azure Pipelines?
    
- Agent - Private

### Task logs

```
2019-04-24T14:05:11.1613025Z ##[debug]Evaluating condition for step: 'SQL DB Deploy'
2019-04-24T14:05:11.1613873Z ##[debug]Evaluating: succeeded()
2019-04-24T14:05:11.1614179Z ##[debug]Evaluating succeeded:
2019-04-24T14:05:11.1614581Z ##[debug]=> True
2019-04-24T14:05:11.1614969Z ##[debug]Result: True
2019-04-24T14:05:11.1615352Z ##[section]Starting: SQL DB Deploy
2019-04-24T14:05:11.1622129Z ==============================================================================
2019-04-24T14:05:11.1622363Z Task         : SQL Server Database Deploy
2019-04-24T14:05:11.1622563Z Description  : Deploy to SQL Server Database using DACPAC or SQL scripts
2019-04-24T14:05:11.1622755Z Version      : 0.3.16
2019-04-24T14:05:11.1622906Z Author       : Microsoft Corporation
2019-04-24T14:05:11.1623082Z Help         : [More Information](https://aka.ms/sqldacpacmachinegroupreadme)
2019-04-24T14:05:11.1623294Z ==============================================================================
2019-04-24T14:05:12.9010360Z ##[debug]VstsTaskSdk 0.8.2 commit 
2019-04-24T14:05:13.1039054Z ##[debug]Entering C:\vstsagent\A2\_work\_tasks\SqlDacpacDeploymentOnMachineGroup_4b506f7f-720f-47bb-bf21-029bac6a690d\0.3.16\Main.ps1.
2019-04-24T14:05:13.1039453Z ##[debug]Loading resource strings from: C:\vstsagent\A2\_work\_tasks\SqlDacpacDeploymentOnMachineGroup_4b506f7f-720f-47bb-bf21-029bac6a690d\0.3.16\Task.json
2019-04-24T14:05:13.1137150Z ##[debug]Loaded 6 strings.
2019-04-24T14:05:13.1688700Z ##[debug]SYSTEM_CULTURE: 'en-US'
2019-04-24T14:05:13.1700802Z ##[debug]Loading resource strings from: C:\vstsagent\A2\_work\_tasks\SqlDacpacDeploymentOnMachineGroup_4b506f7f-720f-47bb-bf21-029bac6a690d\0.3.16\Strings\resources.resjson\en-US\resources.resjson
2019-04-24T14:05:13.2435578Z ##[debug]Loaded 6 strings.
2019-04-24T14:05:13.2519034Z ##[debug]INPUT_TASKTYPE: 'dacpac'
2019-04-24T14:05:13.2542970Z ##[debug]INPUT_DACPACFILE: 'C:\vstsagent\A2\_work\r1\a\_<CLIENT PROJECT> - Database - CI\drop\src\<CLIENT PROJECT>.Database\bin\Release\<CLIENT PROJECT>.Database.dacpac'
2019-04-24T14:05:13.2595757Z ##[debug]INPUT_SQLFILE (empty)
2019-04-24T14:05:13.2624797Z ##[debug]INPUT_EXECUTEINTRANSACTION: 'false'
2019-04-24T14:05:13.2704636Z ##[debug] Converted to bool: False
2019-04-24T14:05:13.2704888Z ##[debug]INPUT_EXCLUSIVELOCK: 'false'
2019-04-24T14:05:13.2705218Z ##[debug] Converted to bool: False
2019-04-24T14:05:13.2705441Z ##[debug]INPUT_APPLOCKNAME (empty)
2019-04-24T14:05:13.2729600Z ##[debug]INPUT_INLINESQL (empty)
2019-04-24T14:05:13.2751889Z ##[debug]INPUT_TARGETMETHOD: 'connectionString'
2019-04-24T14:05:13.2774426Z ##[debug]INPUT_SERVERNAME: 'localhost'
2019-04-24T14:05:13.2799355Z ##[debug]INPUT_DATABASENAME (empty)
2019-04-24T14:05:13.2851058Z ##[debug]INPUT_AUTHSCHEME: 'windowsAuthentication'
2019-04-24T14:05:13.2851321Z ##[debug]INPUT_SQLUSERNAME (empty)
2019-04-24T14:05:13.2875998Z ##[debug]INPUT_SQLPASSWORD (empty)
2019-04-24T14:05:13.2900167Z ##[debug]INPUT_CONNECTIONSTRING: '***'
2019-04-24T14:05:13.2922630Z ##[debug]INPUT_PUBLISHPROFILE: 'C:\vstsagent\A2\_work\r1\a/_IaC/<CLIENT PROJECT>/<CLIENT PROJECT>.Database.publish.xml'
2019-04-24T14:05:13.2950246Z ##[debug]INPUT_ADDITIONALARGUMENTS (empty)
2019-04-24T14:05:13.2984062Z ##[debug]INPUT_ADDITIONALARGUMENTSSQL (empty)
2019-04-24T14:05:13.3042195Z ##[debug]Loading module from path 'C:\vstsagent\A2\_work\_tasks\SqlDacpacDeploymentOnMachineGroup_4b506f7f-720f-47bb-bf21-029bac6a690d\0.3.16\ps_modules\TaskModuleSqlUtility\TaskModuleSqlUtility.psd1'.
2019-04-24T14:05:13.3154969Z ##[debug]Loading module from path 'C:\vstsagent\A2\_work\_tasks\SqlDacpacDeploymentOnMachineGroup_4b506f7f-720f-47bb-bf21-029bac6a690d\0.3.16\ps_modules\TaskModuleSqlUtility\TaskModuleSqlUtility.psm1'.
2019-04-24T14:05:13.3485209Z ##[debug]NonInteractive: False
2019-04-24T14:05:13.4396740Z ##[debug]Exporting function 'Invoke-DacpacDeployment'.
2019-04-24T14:05:13.4448631Z ##[debug]Exporting function 'Invoke-SqlQueryDeployment'.
2019-04-24T14:05:13.4448922Z ##[debug]Adding exceptions types.
2019-04-24T14:05:13.8501940Z ##[debug]Importing function 'Invoke-DacpacDeployment'.
2019-04-24T14:05:13.8519558Z ##[debug]Importing function 'Invoke-SqlQueryDeployment'.
2019-04-24T14:05:13.9162951Z ##[debug]Caught exception from task script.
2019-04-24T14:05:13.9163252Z ##[debug]Error record:
2019-04-24T14:05:14.0109210Z ##[debug]ForEach-Object : Cannot bind argument to parameter 'inputString' because it is an empty string.
2019-04-24T14:05:14.0141309Z ##[debug]At line:19 char:13
2019-04-24T14:05:14.0141635Z ##[debug]+             ForEach-Object {
2019-04-24T14:05:14.0152891Z ##[debug]+             ~~~~~~~~~~~~~~~~
2019-04-24T14:05:14.0163761Z ##[debug]    + CategoryInfo          : InvalidData: (:) [ForEach-Object], ParameterBind    ingValidationException
2019-04-24T14:05:14.0174556Z ##[debug]    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl    lowed,Microsoft.PowerShell.Commands.ForEachObjectCommand
2019-04-24T14:05:14.0193145Z ##[debug] 
2019-04-24T14:05:14.0228101Z ##[debug]Script stack trace:
2019-04-24T14:05:14.0238615Z ##[debug]at <ScriptBlock>, C:\vstsagent\A2\_work\_tasks\SqlDacpacDeploymentOnMachineGroup_4b506f7f-720f-47bb-bf21-029bac6a690d\0.3.16\Main.ps1: line 89
```
2019-04-24T14:05:14.0249443Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-04-24T14:05:14.0260137Z ##[debug]at <ScriptBlock>, <No file>: line 22
2019-04-24T14:05:14.0270758Z ##[debug]at <ScriptBlock>, <No file>: line 18
2019-04-24T14:05:14.0291674Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-04-24T14:05:14.0361907Z ##[debug]Exception:
2019-04-24T14:05:14.0362224Z ##[debug]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'inputString' because it is an empty string.
2019-04-24T14:05:14.0374071Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-04-24T14:05:14.0386395Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-04-24T14:05:14.0398210Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-04-24T14:05:14.0501949Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-04-24T14:05:14.0502314Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2019-04-24T14:05:14.0502559Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2019-04-24T14:05:14.0502954Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
2019-04-24T14:05:14.0503401Z ##[debug]   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
2019-04-24T14:05:14.0518356Z ##[debug]   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
2019-04-24T14:05:14.0529880Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
2019-04-24T14:05:14.0541744Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
2019-04-24T14:05:14.0553154Z ##[debug]   at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
2019-04-24T14:05:14.0747571Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2019-04-24T14:05:14.0865277Z ##[error]Cannot bind argument to parameter 'inputString' because it is an empty string.
2019-04-24T14:05:14.0873763Z ##[debug]Processed: ##vso[task.logissue type=error]Cannot bind argument to parameter 'inputString' because it is an empty string.
2019-04-24T14:05:14.0879787Z ##[debug]Processed: ##vso[task.complete result=Failed]
2019-04-24T14:05:14.1260889Z ##[section]Finishing: SQL DB Deploy

**Comment by mereth** [comment]
This bug is related to this feature : #9949

**Comment by bajmming** [comment]
Related to and workaround here  https://developercommunity.visualstudio.com/comments/542128/view.html
