### ISSUE TITLE
SetVariable with variable names containing '=' failed the task

### ISSUE THREAD

**Issue by Yiming-Jia** [microsoft/azure-pipelines-tasks#10329]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Bug*

**Not to specific task**

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azur Pipelines
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Build link: https://dev.azure.com/yijia/AppConfig-Test/_build/results?buildId=100
account: yijia; Project: AppConfig-Test; 
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
      Hosted VS2017
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
The task is developed by us (Azure App Configuration team), the task run the tl.setVariables() to set variables to environment variables.
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
Logs as below:
```
##[debug]Set variables: =; v: "="
##[debug]set ===
##[error]Unable to process command '##vso[task.setvariable variable==;issecret=false;]=' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Required field 'variable' is missing in ##vso[task.setvariable] command.
##[debug]System.Exception: Required field 'variable' is missing in ##vso[task.setvariable] command.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension.ProcessTaskSetVariableCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
##[debug]Processed: ##vso[task.setvariable variable==;issecret=false;]=
##[debug]Set variables: ==; v: "haha"
##[debug]set ===haha
##[error]Unable to process command '##vso[task.setvariable variable===;issecret=false;]haha' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Required field 'variable' is missing in ##vso[task.setvariable] command.
##[debug]System.Exception: Required field 'variable' is missing in ##vso[task.setvariable] command.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension.ProcessTaskSetVariableCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
```

**Comment by Yiming-Jia** [comment]
Close this issue, as we're using new library azure-pipelines-task-lib. And already filed a [issue](https://github.com/microsoft/azure-pipelines-task-lib/issues/535) in that repo.
