### ISSUE TITLE
we have a issue in azure devops release pipeline for bigcommerce cli application(java)

### ISSUE THREAD

**Issue by mahammad13** [microsoft/azure-pipelines-tasks#10418]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by mahammad13** [comment]
getting below error while release pipline(upload the theme to big commerce site)

2019-05-20T10:51:21.7604467Z SCSS Parsing Started...
2019-05-20T10:51:21.7742756Z Template Parsing Started...
2019-05-20T10:51:21.7743791Z Language Files Parsing Started...
2019-05-20T10:51:21.7744448Z Building Theme Schema File...
2019-05-20T10:51:21.9155495Z Theme task Started...
2019-05-20T10:51:21.9545215Z /home/testadmin/vstsagent/_work_mount/_tool/node/8.16.0/x64/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-bundle.js:113
2019-05-20T10:51:21.9566881Z             const filterFiles = files.filter((file) => {
2019-05-20T10:51:21.9567912Z                                       ^
2019-05-20T10:51:21.9568394Z 
2019-05-20T10:51:21.9569371Z TypeError: Cannot read property 'filter' of undefined
2019-05-20T10:51:21.9571253Z     at Fs.readdir (/home/testadmin/vstsagent/_work_mount/_tool/node/8.16.0/x64/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-bundle.js:113:39)
2019-05-20T10:51:21.9572018Z     at FSReqWrap.oncomplete (fs.js:135:15)
2019-05-20T10:51:23.6202082Z ##[error]Bash exited with code '1'.

please help me on this issuse

**Comment by bryanmacfarlane** [comment]
The issue template wasn't filled out with any details and the small snippet is not enough to go on.  It also appears to be a custom bash script.   If the bug is in a task in this repo, log an issue with the template filled out and we will route.
