### ISSUE TITLE
vsts login -token fails with error output

### ISSUE THREAD

**Issue by Cloudmersive** [microsoft/azure-pipelines-tasks#10461]
[Errno 13] Permission denied: '/home/username/.local/share/python_keyring'
Traceback (most recent call last):
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/knack/invocation.py", line 172, in execute
    cmd_result = parsed_args.func(params)
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/knack/commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/knack/commands.py", line 203, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/vsts/cli/team/common/credentials.py", line 46, in credential_set
    set_credential(team_instance=team_instance, token=token)
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/vsts/cli/common/_credentials.py", line 46, in set_credential
    keyring.set_password(key, _USERNAME, token)
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/keyring/core.py", line 47, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/keyrings/alt/file_base.py", line 139, in set_password
    self._write_config_value(service, username, password_base64)
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/keyrings/alt/file_base.py", line 149, in _write_config_value
    self._ensure_file_path()
  File "/home/username/lib/vsts-cli/local/lib/python2.7/site-packages/keyrings/alt/file_base.py", line 175, in _ensure_file_path
    os.makedirs(storage_root)
  File "/home/username/lib/vsts-cli/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/username/.local/share/python_keyring'

**Comment by bryanmacfarlane** [comment]
Not a task issue.  Can you create an issue in the vsts-cli?
