### ISSUE TITLE
Empty password when extracting Azure Container Registry credentials from Service Connection

### ISSUE THREAD

**Issue by lgoncalv** [microsoft/azure-pipelines-tasks#10605]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ServiceFabricDeployV1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/ServiceFabricDeployV1

## Environment
- Azure Pipelines
- Agent: Hosted VS2017

## Issue Description

Using below build file

``` YAML
variables:
  major_version: 1
  minor_version: 0

name: $(major_version).$(minor_version).$(date:yyyyMMdd)$(rev:.r)-rc

trigger:
- master

stages:
- stage: Build_and_push_docker_image
  jobs:
  - job: BuildJob
    pool:
     vmImage: 'win1803'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
       command: login
       containerRegistry: acrConnection
    - task: Docker@2
      displayName: Build and Push
      inputs:
       command: buildAndPush
       Dockerfile: discounting-app/Dockerfile
       repository: discounting.frontend
       tags: |
         latest
         v$(Build.BuildNumber)
- stage: Deploy_to_azure_service_fabric_cluster
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: PowerShell@2
      displayName: Update image tag
      inputs:
        targetType: 'filePath'
        filePath: discounting-deployment/UpdateImageTag.ps1
        arguments: discounting-deployment/AzureServiceFabric/ApplicationPackageRoot/Discounting.FrontEndPkg/ServiceManifest.xml discounting.frontend v$(Build.BuildNumber)
    - task: ServiceFabricUpdateManifests@2
      displayName: Update manifest versions
      inputs:
        updateType: 'manifest versions'
        applicationPackagePath: discounting-deployment/AzureServiceFabric/ApplicationPackageRoot
        versionSuffix: '.$(Build.BuildNumber)'
        updateOnlyChanged: false
        compareType: 'LastSuccessful'
    - task: ServiceFabricDeploy@1
      inputs:
        applicationPackagePath: discounting-deployment/AzureServiceFabric/ApplicationPackageRoot
        serviceConnectionName: asfConnection
        publishProfilePath: discounting-deployment/AzureServiceFabric/PublishProfiles/Cloud.xml
        applicationParameterPath: discounting-deployment/AzureServiceFabric/ApplicationParameters/Cloud.xml
        overwriteBehavior: 'SameAppTypeAndVersion'
        configureDockerSettings: true
        registryCredentials: ContainerRegistryEndpoint
        dockerRegistryConnection: acrConnection
```

It fails on the the task ServiceFabricDeploy@1 with following error: `##[error]Cannot bind argument to parameter 'Text' because it is an empty string.`

The problem seems to be extracting the credentials of the *Azure Container Registry* service connection, [line 36](https://github.com/microsoft/azure-pipelines-tasks/blob/b08a623f1409b9247362d16a8a1d71c29de1d402/Tasks/ServiceFabricDeployV1/Update-DockerSettings.psm1#L36 ) on file `Update-DockerSettings.psm1` is returning an empty password.

I spotted on the logs the below lines that seem to be trying to use hub.docker.com as endpoint URL instead of the Azure Container Registry.

```
##[debug]INPUT_REGISTRYCREDENTIALS: 'ContainerRegistryEndpoint'
##[debug]INPUT_DOCKERREGISTRYENDPOINT: '40f368f7-2ea8-45bd-b0dd-40d217abfdd0'
##[debug]ENDPOINT_URL_40f368f7-2ea8-45bd-b0dd-40d217abfdd0: 'https://hub.docker.com/'
##[debug]ENDPOINT_AUTH_40f368f7-2ea8-45bd-b0dd-40d217abfdd0: '********'
```

### Task logs

```
##[debug]Evaluating condition for step: 'ServiceFabricDeploy'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: ServiceFabricDeploy
==============================================================================
Task         : Service Fabric Application Deployment
Description  : Deploy a Service Fabric application to a cluster.
Version      : 1.7.31
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820528)
==============================================================================
##[debug]VstsTaskSdk 0.8.2 commit 
##[debug]Entering D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\deploy.ps1.
##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\task.json
##[debug]Loaded 82 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 82 strings.
##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\ServiceFabricHelpers\ServiceFabricHelpers.psm1'.
##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\ServiceFabricHelpers\module.json
##[debug]Loaded 17 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\ServiceFabricHelpers\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 17 strings.
##[debug]Entering Find-VstsFiles.
##[debug] LiteralDirectory: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\ServiceFabricHelpers'
##[debug] LegacyPattern: '*.ps1'
##[debug]Entering Get-MatchingItems.
##[debug] IncludePatterns: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\ServiceFabricHelpers\*.ps1'
##[debug] ExcludePatterns: ''
##[debug] IncludeFiles: 'True'
##[debug] IncludeDirectories: 'False'
##[debug] Force: 'False'
##[debug]Paths: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\ServiceFabricHelpers\
##[debug] CommonHelpers.ps1
##[debug] Connect-ServiceFabricClusterFromServiceEndpoint.ps1
##[debug] Get-ServiceFabricEncryptedText.ps1
##[debug] SFOperations.ps1
##[debug]Leaving Get-MatchingItems.
##[debug]Total found: 4
##[debug]Leaving Find-VstsFiles.
##[debug]Exporting function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
##[debug]Exporting function 'Remove-ClientCertificate'.
##[debug]Exporting function 'Get-ServiceFabricEncryptedText'.
##[debug]Exporting variable 'SF_Operations'.
##[debug]Exporting function 'Publish-Telemetry'.
##[debug]Exporting function 'Get-SfSdkVersion'.
##[debug]Exporting function 'Trace-WarningIfCertificateNotPresentInLocalCertStore'.
##[debug]Importing function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
##[debug]Importing function 'Get-ServiceFabricEncryptedText'.
##[debug]Importing function 'Get-SfSdkVersion'.
##[debug]Importing function 'Publish-Telemetry'.
##[debug]Importing function 'Remove-ClientCertificate'.
##[debug]Importing function 'Trace-WarningIfCertificateNotPresentInLocalCertStore'.
##[debug]Importing variable 'SF_Operations'.
##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\PowershellHelpers\PowershellHelpers.psm1'.
##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\PowershellHelpers\module.json
##[debug]Loaded 3 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\PowershellHelpers\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 3 strings.
##[debug]Exporting function 'Invoke-ActionWithRetries'.
##[debug]Exporting function 'Get-TempDirectoryPath'.
##[debug]Importing function 'Get-TempDirectoryPath'.
##[debug]Importing function 'Invoke-ActionWithRetries'.
##[debug]INPUT_PUBLISHPROFILEPATH: 'd:\a\1\s\discounting-deployment\AzureServiceFabric\PublishProfiles\Cloud.xml'
Searching for path: d:\a\1\s\discounting-deployment\AzureServiceFabric\PublishProfiles\Cloud.xml
##[debug]Entering Find-VstsFiles.
##[debug] LegacyPattern: 'd:\a\1\s\discounting-deployment\AzureServiceFabric\PublishProfiles\Cloud.xml'
##[debug]Entering Get-MatchingItems.
##[debug] IncludePatterns: 'd:\a\1\s\discounting-deployment\AzureServiceFabric\PublishProfiles\Cloud.xml'
##[debug] ExcludePatterns: ''
##[debug] IncludeFiles: 'True'
##[debug] IncludeDirectories: 'False'
##[debug] Force: 'False'
##[debug]Path: d:\a\1\s\discounting-deployment\AzureServiceFabric\PublishProfiles\Cloud.xml
##[debug]Leaving Get-MatchingItems.
##[debug]Total found: 1
##[debug]Leaving Find-VstsFiles.
##[debug]Asserting leaf path exists: 'd:\a\1\s\discounting-deployment\AzureServiceFabric\PublishProfiles\Cloud.xml'
Found path: d:\a\1\s\discounting-deployment\AzureServiceFabric\PublishProfiles\Cloud.xml
##[debug]INPUT_APPLICATIONPACKAGEPATH: 'd:\a\1\s\discounting-deployment\AzureServiceFabric\ApplicationPackageRoot'
Searching for path: d:\a\1\s\discounting-deployment\AzureServiceFabric\ApplicationPackageRoot
##[debug]Entering Find-VstsFiles.
##[debug] LegacyPattern: 'd:\a\1\s\discounting-deployment\AzureServiceFabric\ApplicationPackageRoot'
##[debug] IncludeDirectories: 'True'
##[debug]Entering Get-MatchingItems.
##[debug] IncludePatterns: 'd:\a\1\s\discounting-deployment\AzureServiceFabric\ApplicationPackageRoot'
##[debug] ExcludePatterns: ''
##[debug] IncludeFiles: 'False'
##[debug] IncludeDirectories: 'True'
##[debug] Force: 'False'
##[debug]Path: d:\a\1\s\discounting-deployment\AzureServiceFabric\ApplicationPackageRoot
##[debug]Leaving Get-MatchingItems.
##[debug]Total found: 1
##[debug]Leaving Find-VstsFiles.
##[debug]Asserting container path exists: 'd:\a\1\s\discounting-deployment\AzureServiceFabric\ApplicationPackageRoot'
Found path: d:\a\1\s\discounting-deployment\AzureServiceFabric\ApplicationPackageRoot
##[debug]INPUT_SERVICECONNECTIONNAME: 'f4640915-e364-4301-934d-c8d3c03e6731'
##[debug]ENDPOINT_URL_f4640915-e364-4301-934d-c8d3c03e6731: 'tcp://the-cluster.northeurope.cloudapp.azure.com:19000/'
##[debug]ENDPOINT_AUTH_f4640915-e364-4301-934d-c8d3c03e6731: '********'
##[debug]ENDPOINT_DATA_f4640915-e364-4301-934d-c8d3c03e6731: '{}'
##[debug]INPUT_COPYPACKAGETIMEOUTSEC (empty)
##[debug]INPUT_REGISTERPACKAGETIMEOUTSEC (empty)
##[debug]INPUT_COMPRESSPACKAGE: 'false'
##[debug]INPUT_SKIPUPGRADESAMETYPEANDVERSION: 'false'
##[debug]INPUT_SKIPPACKAGEVALIDATION: 'false'
##[debug]INPUT_UNREGISTERUNUSEDVERSIONS: 'true'
##[debug]INPUT_CONFIGUREDOCKERSETTINGS: 'true'
##[debug]INPUT_OVERRIDEAPPLICATIONPARAMETER: 'false'
##[debug]Entering Connect-ServiceFabricClusterFromServiceEndpoint.
##[debug] ClusterConnectionParameters: 'System.Collections.Hashtable'
##[debug] ConnectedServiceEndpoint: '@{Url=tcp://the-cluster.northeurope.cloudapp.azure.com:19000/; Data=; Auth=}'
##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\TlsHelper_\TlsHelper_.psm1'.
##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\TlsHelper_/module.json
##[debug]Loaded 3 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\TlsHelper_\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 3 strings.
##[debug]Exporting function 'Add-Tls12InSession'.
##[debug]Exporting function 'Assert-TlsError'.
##[debug]Importing function 'Add-Tls12InSession'.
##[debug]Importing function 'Assert-TlsError'.
##[debug]Importing function 'Get-TempDirectoryPath'.
##[debug]Importing function 'Invoke-ActionWithRetries'.
##[debug]TLS 1.2 already present in session.
Imported cluster client certificate with thumbprint '***'.
Successfully connected to cluster.
##[debug]Leaving Connect-ServiceFabricClusterFromServiceEndpoint.
##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\Update-DockerSettings.psm1'.
##[debug]Exporting function 'Update-DockerSettings'.
##[debug]Importing function 'Update-DockerSettings'.
##[debug]Entering Update-DockerSettings.
##[debug] ApplicationPackagePath: 'd:\a\1\s\discounting-deployment\AzureServiceFabric\ApplicationPackageRoot'
##[debug] ClusterConnectionParameters: 'System.Collections.Hashtable'
##[debug]INPUT_REGISTRYCREDENTIALS: 'ContainerRegistryEndpoint'
##[debug]INPUT_DOCKERREGISTRYENDPOINT: '40f368f7-2ea8-45bd-b0dd-40d217abfdd0'
##[debug]ENDPOINT_URL_40f368f7-2ea8-45bd-b0dd-40d217abfdd0: 'https://hub.docker.com/'
##[debug]ENDPOINT_AUTH_40f368f7-2ea8-45bd-b0dd-40d217abfdd0: '********'
##[debug]ENDPOINT_DATA_40f368f7-2ea8-45bd-b0dd-40d217abfdd0: '{"registrytype":"ACR","subscriptionId":"487a714d-a620-4375-962b-76583bab423c","subscriptionName":"SBUKNETWORKSTEAM","azureSpnRoleAssignmentId":"b8d1e7d9-051e-4fda-a730-b534ccef1fc0","azureSpnPermissions":"[{\"roleAssignmentId\":\"b8d1e7d9-051e-4fda-a730-b534ccef1fc0\",\"resourceProvider\":\"Microsoft.RoleAssignment\",\"provisioned\":true}]","spnObjectId":"5ff1260d-cb1f-4507-9a62-0466b9c857e7","appObjectId":"6a5eb81f-8bdb-4caf-886d-6da103552d2c","registryId":"***"}'
##[debug]Leaving Update-DockerSettings.
##[debug]SYSTEM_JOBID: '2581281a-c3e8-561a-9606-d2f6e9c3b159'
Service fabric SDK version: 3.3.617.9590.
##[debug]Processed: ##vso[telemetry.publish area=TaskHub;feature=ServiceFabricDeploy]{"OperationId":"EncryptServiceFabricText","ExceptionData":"System.Management.Automation.ParameterBindingValidationException;|D:\\a\\_tasks\\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\\1.7.31\\deploy.ps1|64","JobId":"2581281a-c3e8-561a-9606-d2f6e9c3b159","SDKVersion":"3.3.617.9590"}
##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\deploy.ps1.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Update-DockerSettings : Cannot bind argument to parameter 'Text' because it is an empty string.
##[debug]At D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\deploy.ps1:64 char:9
##[debug]+         Update-DockerSettings -ApplicationPackagePath $applicationPac ...
##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidData: (:) [Update-DockerSettings], ParameterBindingValidationException
##[debug]    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Update-DockerSettings
##[debug] 
##[debug]Script stack trace:
##[debug]at Get-ServiceFabricEncryptedText, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\ServiceFabricHelpers\Get-ServiceFabricEncryptedText.ps1: line 41
##[debug]at Update-DockerSettings, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\Update-DockerSettings.psm1: line 49
##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\deploy.ps1: line 64
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Text' because it is an empty string.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
##[error]Cannot bind argument to parameter 'Text' because it is an empty string.
##[debug]Processed: ##vso[task.logissue type=error]Cannot bind argument to parameter 'Text' because it is an empty string.
##[debug]Processed: ##vso[task.complete result=Failed]
##[section]Finishing: ServiceFabricDeploy
```

### Error logs

```
##[debug]Processed: ##vso[telemetry.publish area=TaskHub;feature=ServiceFabricDeploy]{"OperationId":"EncryptServiceFabricText","ExceptionData":"System.Management.Automation.ParameterBindingValidationException;|D:\\a\\_tasks\\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\\1.7.31\\deploy.ps1|64","JobId":"2581281a-c3e8-561a-9606-d2f6e9c3b159","SDKVersion":"3.3.617.9590"}
##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\deploy.ps1.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Update-DockerSettings : Cannot bind argument to parameter 'Text' because it is an empty string.
##[debug]At D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\deploy.ps1:64 char:9
##[debug]+         Update-DockerSettings -ApplicationPackagePath $applicationPac ...
##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidData: (:) [Update-DockerSettings], ParameterBindingValidationException
##[debug]    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Update-DockerSettings
##[debug] 
##[debug]Script stack trace:
##[debug]at Get-ServiceFabricEncryptedText, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\ps_modules\ServiceFabricHelpers\Get-ServiceFabricEncryptedText.ps1: line 41
##[debug]at Update-DockerSettings, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\Update-DockerSettings.psm1: line 49
##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.31\deploy.ps1: line 64
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Text' because it is an empty string.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
##[error]Cannot bind argument to parameter 'Text' because it is an empty string.
##[debug]Processed: ##vso[task.logissue type=error]Cannot bind argument to parameter 'Text' because it is an empty string.
##[debug]Processed: ##vso[task.complete result=Failed]
##[section]Finishing: ServiceFabricDeploy
```

**Comment by vinodkumar3** [comment]
Currently ServiceFabricDeploy task is supporting only DockerHub Container Registry Service connection endpoint but not ACR. We are taking this up and will update once we roll out the support.

**Comment by lgoncalv** [comment]
Thanks @vinodkumar3, is not clear from the documentation that ACR is not supported. Will keep an eye on any updates! 👍

**Comment by vinodkumar3** [comment]
@lgoncalv 
Required support has been added as part of ServiceFabricDeploy task version 1.7.34. It should be released for all the customers in around 2 weeks of time.
