### ISSUE TITLE
Deploying azure cloud service fails with an internal error

### ISSUE THREAD

**Issue by mrudalal** [microsoft/azure-pipelines-tasks#10964]
While deploying the build, it throws and error as follows. 

2019-07-19T15:33:46.5037502Z ##[error]InternalError : The server encountered an internal error. Please retry the request.
Attached is the detailed log

[tasklog_6 (1).log](https://github.com/microsoft/azure-pipelines-tasks/files/3416748/tasklog_6.1.log)

**Comment by Ajay-MS** [comment]
@mrudalal 

Is this error consistent ? 

I doubt that it's an intermittent issue because of some issue with cloud service as exception is internal server error 
```
InternalError : The server encountered an internal error. Please retry the request. ---> Hyak.Common.CloudException: InternalError : The server encountered an internal error. Please retry the request.
2019-07-22T09:41:24.0412576Z ##[debug]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-07-22T09:41:24.0412576Z ##[debug]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
```

**Comment by RoshanKumarMicrosoft** [comment]
@mrudalal  Are you still unblocked ? If yes please your skype id on RM_Customer_Queries@microsoft.com.

**Comment by SumiranAgg** [comment]
Closing issue due to no customer activity.
