### ISSUE TITLE
False positive on step failure:  ##[error]SettingsUpdation.Run : Exception occurred during the updation of run settings

### ISSUE THREAD

**Issue by splateaux** [microsoft/azure-pipelines-tasks#10982]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest@2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name

, build definition name/build number: 
[Pipeline](https://softprocorp.visualstudio.com/RandD/_release?view=mine&definitionId=60)
Release Pipeline: Select-Gauntlet

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The VSTest step had the error shown below, which is fine, but the step showed a "Succeeded", which made the overall pipeline show as successful.  This is obviously not good since none of our tests ran.

### Task logs

A complete debug log can be provided privately.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

2019-07-23T14:50:59.2572189Z ##[warning]Unable to parse the override run parameters string: <Removed>
2019-07-23T14:50:59.2572527Z ##[debug]Processed: ##vso[task.logissue type=warning;]Unable to parse the override run parameters string:<Removed>
2019-07-23T14:50:59.2573444Z ##[error]SettingsUpdation.Run : Exception occurred during the updation of run settings: System.FormatException: Error encountered while overriding test run parameters. Please check the test run parameteres provided.

**Comment by singhsarab** [comment]
@splateaux Can you please share the test run parameters you are giving ?

**Comment by splateaux** [comment]
The test run parameters were absolutely not properly formed.  They were effectively something like `-parameterOne steve -parameterTwo some value with spaces but no quotes`

It's not that my parameters were wrong and that the test step gave an error... it should have, it's that the step showed as "Succeeded" when it went failed so badly.

**Comment by ShreyasRmsft** [comment]
@splateaux we have fixed this and this should get rolled out in around 2 weeks

**Comment by ShreyasRmsft** [comment]
@splateaux this is fixed in task version 2.159.x
this version has been rolled out to around half the accounts and the other half should get it in a week.

If you have version 2.159.x or higher and are still facing the issue please re-open this ticket.

**Comment by nipuns11** [comment]
I have the same error , one of my variables has a space in it and the total length is 586 for the variable 2020-02-10T21:30:42.6519039Z ##[error]SetupPhase.Run : Exception occurred during the updation of run settings: System.FormatException: Error encountered while overriding test run parameters. Please check the test run parameteres provided.
2020-02-10T21:30:42.6519586Z    at Microsoft.VisualStudio.TestService.SettingsManager.OverrideParamsSettingsProcessor.GetOverrideParameters(String overrdeParametersString)
2020-02-10T21:30:42.6519842Z    at Microsoft.VisualStudio.TestService.SettingsManager.OverrideParamsSettingsProcessor.UpdateSettingsWithParameters(XDocument settings)
2020-02-10T21:30:42.6520043Z    at Microsoft.VisualStudio.TestService.SettingsManager.CommonSettingsManager.UpdateCommonSettings(InputDataContract inputDataContract, SettingsModifier settingsModifier)
2020-02-10T21:30:42.6520214Z    at Microsoft.VisualStudio.TestService.SettingsManager.SettingsManager.UpdateSettingsAsRequired(InputDataContract inputDataContract)
2020-02-10T21:30:42.6520401Z    at MS.VS.TestService.VstestConsoleAdapter.SetupPhase.Run(VstestConsoleRunContext testRunContext, CancellationToken cancellationToken)
