### ISSUE TITLE
Caching react scripts test fails after using caching in pipeline

### ISSUE THREAD

**Issue by baywet** [microsoft/azure-pipelines-tasks#11011]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheBeta  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 2toLead/VOR/ECSPilotFrontEnd/6858

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

```YAML
# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
      - develop
      - support/production

stages:
- stage: build
  displayName: build
  variables:
    CI: true
  jobs:
    - job: mainbuild
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - task: CacheBeta@0
        inputs:
          key: |
            $(Agent.OS)
            $(Build.SourcesDirectory)/package-lock.json
          path: $(Build.SourcesDirectory)/node_modules
          cacheHitVar: CACHE_RESTORED
        displayName: 'Cache Npm'
      #install nodejs modules with npm
      - task: Npm@1
        displayName: 'npm install'
        inputs:
          workingDir: '$(Build.SourcesDirectory)'
          verbose: false
        condition: ne(variables.CACHE_RESTORED, 'true')
      #workaround for office ui fabric and unit tests
      - task: PowerShell@2
        inputs:
          filePath: './scripts/pretest.ps1'
          workingDirectory: '$(Build.SourcesDirectory)'
      #start unit tests
      - task: Npm@1
        displayName: 'npm test'
        inputs:
          command: custom
          customCommand: 'test'
          workingDir: '$(Build.SourcesDirectory)'
          verbose: false
      #workaround for office ui fabric and unit tests
      - task: PowerShell@2
        inputs:
          filePath: './scripts/posttest.ps1'
          workingDirectory: '$(Build.SourcesDirectory)'
      #build the solution
      - task: Npm@1
        displayName: 'npm run build'
        inputs:
          command: custom
          customCommand: 'run build'
          workingDir: '$(Build.SourcesDirectory)'
          verbose: false
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.SourcesDirectory)/build'
          ArtifactName: drop
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.SourcesDirectory)/scripts'
          ArtifactName: scripts
```
This is my pipeline definition (truncated the deploy stage for brevity), as I was testing the new CacheBeta task, I added this task as well as the condition on the npm install task.
On cache miss, build succeeds.
On cache hit, build fails on the npm test task with the log below.
Project was created using the create react app a few months ago and is up to date in terms of dependencies.
I suspect the test script wants to log somewhere in the node_modules folder, which is set to read-only by the cache restore.
**It'd be nice if we could still write to the folders restored by the cache, but get a warning in the post op (or even better, an option to get a warning or an error)**

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
```

Starting: npm test |  
-- | --
  | ============================================================================== |  
  | Task         : npm |  
  | Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts. |  
  | Version      : 1.155.2 |  
  | Author       : Microsoft Corporation |  
  | Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm |  
  | ============================================================================== |  
  | SYSTEMVSSCONNECTION exists true |  
  | SYSTEMVSSCONNECTION exists true |  
  | pt/hostedtoolcache/node/10.16.0/x64/bin/npm --version |  
  | 6.9.0 |  
  | pt/hostedtoolcache/node/10.16.0/x64/bin/npm config list |  
  | ; cli configs |  
  | metrics-registry = "https://registry.npmjs.org/" |  
  | scope = "" |  
  | user-agent = "npm/6.9.0 node/v10.16.0 linux x64" |  
  |   |  
  | ; environment configs |  
  | userconfig = "/home/vsts/work/1/npm/6858.npmrc" |  
  |   |  
  | ; node bin location = /opt/hostedtoolcache/node/10.16.0/x64/bin/node |  
  | ; cwd = /home/vsts/work/1/s |  
  | ; HOME = /home/vsts |  
  | ; "npm config ls -l" to show all defaults. |  
  |   |  
  | pt/hostedtoolcache/node/10.16.0/x64/bin/npm test |  
  |   |  
  | sh: 1: react-scripts: Permission denied |  
  | npm ERR! Test failed.  See above for more details. |  
  | > ecs@0.1.0 test /home/vsts/work/1/s |  
  | > react-scripts test |  
  |   |  
  | ##[warning]Couldn't find a debug log in the cache or working directory |  
  | ##[error]Error: Npm failed with return code: 1 |  
  | Finishing: npm test

```

**Comment by baywet** [comment]
If I chmod -R 777 on the restored node_modules folder then I get the following error:
```
##[debug]AGENT_OS=Linux
Error: Cannot find module '../scripts/test'
##[debug]AGENT_VERSION=2.155.1
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
##[debug]BUILD_BUILDID=7176
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
##[debug]BUILD_BUILDNUMBER=VOR_ECSPilotFrontend_PipelineCaching_20190821.3
    at Object.<anonymous> (/home/vsts/work/1/s/node_modules/.bin/react-scripts:35:25)
##[debug]BUILD_BUILDURI=vstfs:///Build/Build/7176
    at Module._compile (internal/modules/cjs/loader.js:778:30)
##[debug]BUILD_CONTAINERID=2291862
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
##[debug]BUILD_DEFINITIONNAME=ECSPilotFrontend
    at Module.load (internal/modules/cjs/loader.js:653:32)
##[debug]BUILD_DEFINITIONVERSION=1
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
##[debug]BUILD_REASON=Manual
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
##[debug]BUILD_REPOSITORY_CLEAN=False
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
##[debug]BUILD_REPOSITORY_GIT_SUBMODULECHECKOUT=False
    at startup (internal/bootstrap/node.js:283:19)
##[debug]BUILD_REPOSITORY_NAME=ECSPilotFrontend
npm verb lifecycle ecs@0.1.0~test: unsafe-perm in lifecycle true
##[debug]BUILD_REPOSITORY_PROVIDER=TfsGit
npm verb lifecycle ecs@0.1.0~test: PATH: /opt/hostedtoolcache/node/10.16.3/x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vsts/work/1/s/node_modules/.bin:/opt/hostedtoolcache/node/10.16.3/x64/bin:/usr/share/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
##[debug]BUILD_SOURCEVERSION=c050ba002bd03e19e70c67dac9910324d2450d04
npm verb lifecycle ecs@0.1.0~test: CWD: /home/vsts/work/1/s
##[debug]Processed: ##vso[telemetry.publish area=Packaging;feature=npm]{"SYSTEM_TASKINSTANCEID":"acadaafa-0ffc-5b5e-77bc-2ad49056bd86","SYSTEM_JOBID":"7ed36a57-97e1-52ba-f2f6-edef580a5859","SYSTEM_PLANID":"f15129e4-9b21-4d38-bbb6-ba4ca18a63b2","SYSTEM_COLLECTIONID":"316c93ea-a424-4907-8926-f0f22f909c6f","AGENT_ID":"21","AGENT_MACHINENAME":"fv-az456","AGENT_NAME":"Hosted Agent","AGENT_JOBSTATUS":"Succeeded","AGENT_OS":"Linux","AGENT_VERSION":"2.155.1","BUILD_BUILDID":"7176","BUILD_BUILDNUMBER":"VOR_ECSPilotFrontend_PipelineCaching_20190821.3","BUILD_BUILDURI":"vstfs:///Build/Build/7176","BUILD_CONTAINERID":"2291862","BUILD_DEFINITIONNAME":"ECSPilotFrontend","BUILD_DEFINITIONVERSION":"1","BUILD_REASON":"Manual","BUILD_REPOSITORY_CLEAN":"False","BUILD_REPOSITORY_GIT_SUBMODULECHECKOUT":"False","BUILD_REPOSITORY_NAME":"ECSPilotFrontend","BUILD_REPOSITORY_PROVIDER":"TfsGit","BUILD_SOURCEVERSION":"c050ba002bd03e19e70c67dac9910324d2450d04","exitCode":1}
npm info lifecycle ecs@0.1.0~test: Failed to exec test script
npm ERR! Test failed.  See above for more details.
npm verb exit [ 1, true ]
npm timing npm Completed in 170ms
npm verb code 1
```

**Comment by fadnavistanmay** [comment]
@baywet - Ack.

**Comment by baywet** [comment]
Follow up:
reverting the scripts in pacakage.json to the original setup of create react app and using the following pipeline works much better (and faster).
Note: upgraded cache beta task to version 1, used npm ci instead of npm install, 
```YAML
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
      - develop
      - support/production

stages:
- stage: build
  displayName: build
  variables:
    CI: true
    npm_config_cache: $(Pipeline.Workspace)/.npm
  jobs:
    - job: mainbuild
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - task: CacheBeta@1
        inputs:
          key: npm | $(Agent.OS) | package-lock.json
          path: $(npm_config_cache)
        displayName: 'Cache Npm'
      #install nodejs modules with npm
      - script: 'npm ci'
        workingDirectory: '$(Build.SourcesDirectory)'
        displayName: 'npm ci'
      #workaround for office ui fabric and unit tests
      - task: PowerShell@2
        inputs:
          filePath: './scripts/pretest.ps1'
          workingDirectory: '$(Build.SourcesDirectory)'
      #start unit tests
      - script: 'node node_modules/react-scripts/scripts/test.js'
        displayName: 'npm test'
        workingDirectory: '$(Build.SourcesDirectory)'
      #workaround for office ui fabric and unit tests
      - task: PowerShell@2
        inputs:
          filePath: './scripts/posttest.ps1'
          workingDirectory: '$(Build.SourcesDirectory)'
      #build the solution
      - script: 'node node_modules/react-scripts/scripts/build.js'
        displayName: 'npm run build'
        workingDirectory: '$(Build.SourcesDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.SourcesDirectory)/build'
          ArtifactName: drop
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.SourcesDirectory)/scripts'
          ArtifactName: scripts
```
