### ISSUE TITLE
PublishTestResults Fails with NullReferenceException when an VSTest results file has zero tests

### ISSUE THREAD

**Issue by sonofhammer** [microsoft/azure-pipelines-tasks#11054]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults@2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
        - Azure Pipelines, Project name build definition etc, doesn't matter: Repro YAML below.

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017
  

## Issue Description

PublishTestResults errors with  NullReferenceException when a test results file has zero test results.

### Error logs

```
2019-08-01T18:35:19.2787718Z ##[warning]Failed to parse result files:  Object reference not set to an instance of an object.
2019-08-01T18:35:19.2797533Z ##[debug]Processed: ##vso[task.logissue type=warning;]Failed to parse result files:  Object reference not set to an instance of an object.
2019-08-01T18:35:19.3724799Z 
2019-08-01T18:35:19.8335171Z Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
2019-08-01T18:35:19.8335578Z    at MS.TF.PublishTestResultsTask.TestResultsPublisher.Program.executeTestResultsPublisher(String[] args) in D:\V2.0\A1\_work\80\s\Ta\Tasks\TestResultsPublisher\TestResultsPublisher\Program.cs:line 78
2019-08-01T18:35:19.8335955Z    at MS.TF.PublishTestResultsTask.TestResultsPublisher.Program.Main(String[] args) in D:\V2.0\A1\_work\80\s\Ta\Tasks\TestResultsPublisher\TestResultsPublisher\Program.cs:line 22
2019-08-01T18:35:19.8806683Z ##[debug]Exit code 3221225477 received from tool 'D:\a\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.155.0\modules\TestResultsPublisher.exe'
2019-08-01T18:35:19.8811270Z ##[debug]STDIO streams have closed for tool 'D:\a\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.155.0\modules\TestResultsPublisher.exe'
2019-08-01T18:35:19.8829272Z ##[debug]Exit code of TestResultsPublisher: 3221225477
```

YAML that reproduces the issue

``` yaml
pool:
  name: Hosted VS2017
steps:
- powershell: |
   $foo = '<?xml version="1.0" encoding="UTF-8"?>
      <TestRun id="6c5ca475-86d1-48d7-b0fa-8cfe3e37e0b6" name="testResults\testResults_2019-08-01T153300.338Z.xml" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
      <Times creation="2019-08-01T15:33:15+0000" start="2019-08-01T15:33:15+0000" finish="2019-08-01T15:33:15+0000"/>
      <TestLists>
        <TestList/>
      </TestLists>
      <TestDefinitions>
        <UnitTest/>
      </TestDefinitions>
      <TestEntries>
        <TestEntry/>
      </TestEntries>
      <Results>
        <UnitTestResult/>
      </Results>
      <ResultSummary outcome="Completed">
        <Counters total="0" executed="0" passed="0" failed="0"/>
        <Output>
          <StdOut/>
        </Output>
      </ResultSummary>
      </TestRun>'
   out-file -FilePath ".\testresults.xml" -InputObject $foo
  displayName: 'PowerShell Script'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/testresults.xml'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/testresults.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: foo
```

**Comment by sonofhammer** [comment]
The results file was created by Karma test runner running Jasmine tests. I'm working on making Karma not publish an empty test result file, which should work as a workaround for me.

**Comment by suyash691** [comment]
Fixed the issue. Closing this
