### ISSUE TITLE
npm version 6.11.0 - 'find_dp0' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by penihel** [microsoft/azure-pipelines-tasks#11199]
*Type*: Bug
**Enter Task Name**: 
Task         : npm
Task Version      : 1.156.1

## Environment
- Server - Azure Pipelines
 
## Issue Description

![image](https://user-images.githubusercontent.com/1167747/63612508-c74ce000-c5b4-11e9-81ac-841840b4db42.png)

I had a task that runs a custom npm commands. And worked perfect until the Hosted Agent (Hosted Windows 2019 with VS2019) upgrade the npm version from **"6.10.3"** to **"6.11.0"**

### Task logs with error (**"6.11.0"**)

```
##[section]Starting: ProgramasProjetosWebApp - npm build
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.156.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
==============================================================================
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
[command]C:\windows\system32\cmd.exe /D /S /C "C:\npm\prefix\npm.cmd --version"
6.11.0
[command]C:\windows\system32\cmd.exe /D /S /C "C:\npm\prefix\npm.cmd config list"
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.11.0 node/v10.16.3 win32 x64"

; environment configs
cache = "C:\\npm\\cache"
prefix = "C:\\npm\\prefix"
userconfig = "d:\\a\\1\\npm\\31417.npmrc"

; builtin config undefined

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = d:\a\1\s\src\ProgramasProjetos\ProgramasProjetosWebApp
; HOME = C:\Users\VssAdministrator
; "npm config ls -l" to show all defaults.

[command]C:\windows\system32\cmd.exe /D /S /C "C:\npm\prefix\npm.cmd run build-prod"
'find_dp0' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'd:\@angular\cli\bin\ng'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

> programas-projetos-web-app@0.0.0 build-prod d:\a\1\s\src\ProgramasProjetos\ProgramasProjetosWebApp
> ng build --prod --base-href=/programasprojetos/ --deploy-url=/programasprojetos/

##[section]Finishing: ProgramasProjetosWebApp - npm build

```
again, yesterday worked perfect, i did not change nothing, and today i got this problem.

Comparing both logs, i saw the diference, the npm version.

**Comment by apluche** [comment]
Hi,

Thanks for reaching out to us. It appears that the issue is with npm v6.11.0, there is a similar issue report here: https://npm.community/t/6-11-0-npm-looking-for-executable-packages-in-root-c/9574 . Additionally, it looks like npm has already released the fix for this in npm v6.11.1 based on the solution to the issue report. 

Since this is not an issue with the task, i would suggest updating your npm version or downgrading it and trying again. 

Please let me know if this fixes your issue.

**Comment by penihel** [comment]
I'm using the Hosted Agent (Hosted Windows 2019 with VS2019). 
I added a task "Use Node 12.6" that user npm "6.9.0". This task runs, but the next one, continue using npm "6.11.0"

How i change de npm version on Hosted Agent (Hosted Windows 2019 with VS2019)?

**Comment by shubham90** [comment]
@penihel while we make the fix to the hosted agents, can you please add a command line task before the npm task and run:

npm install -g npm@6.11.1
npm run prepare - successful

This should update your npm globally and npm task should use 6.11.1. We have forwarded this issue to the team which manages hosted agents.

**Comment by gabrielcalegari** [comment]
@shubham90 I tried to run these commands, but I get this:

```
##[section]Starting: Install NPM (temporary)
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\60c407c4-8434-461a-9633-f1bdf971a3a8.cmd""
C:\npm\prefix\npm -> C:\npm\prefix\node_modules\npm\bin\npm-cli.js
C:\npm\prefix\npx -> C:\npm\prefix\node_modules\npm\bin\npx-cli.js
+ npm@6.11.1
updated 2 packages in 29.556s
'npm-cli.js" install -g npm@6.11.1' is not recognized as an internal or external command,
operable program or batch file.
##[error]Cmd.exe exited with code '9009'.
##[section]Finishing: Install NPM (temporary)
```
