### ISSUE TITLE
IoT Edge deployment creation failure with 'jsonschema' distribution not found

### ISSUE THREAD

**Issue by shantanu1singh** [microsoft/azure-pipelines-tasks#11376]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureIoTEdge@2  

## Environment
- Server - Azure Pipelines
   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account->MsAzure
Project->One
Build Definition Name->azure-iot-mcvp - Build and Run Auto Edge
Build Number->25155063
https://msazure.visualstudio.com/One/_build/results?buildId=25155063

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: "ubuntu-16.04"

## Issue Description

[Include task name(s), screenshots and any other relevant details]
We are using the Azure IoT Edge task to create a deployment for an Azure IoT Edge device. The task, in turn, uses the az module to create a deployment and fails with the following error:
![image](https://user-images.githubusercontent.com/2570312/65268091-41488a00-dacb-11e9-8ac9-c9d8e5475d7b.png)

### Task logs

[log_36_25155063.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3632569/log_36_25155063.zip)

Diagnostic logs:
[log_38_25156253.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3632696/log_38_25156253.zip)

### Error logs

[command]/usr/bin/az iot edge deployment create --config-id one-devops-deployment --hub-name <X> --content /tmp/deployment_1568914571694.json --target-condition deviceId='33b5691610884b27a952726352904b5c' --priority 0 --output none
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: The 'jsonschema' distribution was not found and is required by the application
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 524, in iot_edge_deployment_create
    login=login, edge=True)
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 558, in _iot_hub_configuration_create
    content = _process_config_content(content, 'module' if edge else 'device')
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 613, in _process_config_content
    _validate_payload_schema(content)
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 626, in _validate_payload_schema
    from jsonschema import validate
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/jsonschema/__init__.py", line 33, in <module>
    __version__ = get_distribution(__name__).version
  File "/opt/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 472, in get_distribution
    dist = get_provider(dist)
  File "/opt/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jsonschema' distribution was not found and is required by the application
WARNING: 
To open an issue, please run: 'az feedback'

**Comment by blackchoey** [comment]
This issue is caused by Azure CLI IoT extension issue: https://github.com/Azure/azure-iot-cli-extension/issues/98. Azure CLI IoT extension has released a new version 0.8.2 to resolve this issue a few days ago.
