### ISSUE TITLE
Error: spawn E2BIG after Kubernetes apply

### ISSUE THREAD

**Issue by piotrgwiazda** [microsoft/azure-pipelines-tasks#11447]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Kubernetes@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/KubernetesV1

## Environment
- Server - Azure Pipelines
    
- Agent - Hosted or Private: 
   
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Task configuration
```
      - task: Kubernetes@1
        displayName: Deploy application
        inputs:
          connectionType: Azure Resource Manager
          azureSubscriptionEndpoint: ***
          azureResourceGroup: ****
          kubernetesCluster: ****
          command: apply
```

When running kubernetes apply on a relatively large Kubernetes deployment the **next** task of any type fails with 
```
internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Socket.<anonymous> (/__w/_temp/containerHandlerInvoker.js:56:18)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
##[debug]Set env: KUBERNETES1_KUBECTLOUTPUT={
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "v1",
            "kind": "Namespace",
.....A LOT BELOW....
```
The problem is that the kubernetes apply task puts the whole kubernetes output into a variable KUBERNETES1_KUBECTLOUTPUT and passes. Then the next task of any type fails on preparing the environment. Troubleshooting is very hard and misleading.

The Kubernetes apply tasks could fail with a descriptive error like "Output too long use different output format" rather than pass and break the next task.

### Task logs

---

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Socket.<anonymous> (/__w/_temp/containerHandlerInvoker.js:56:18)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
##[debug]Set env: KUBERNETES1_KUBECTLOUTPUT={
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "v1",
            "kind": "Namespace",
.....A LOT BELOW....
```

### Workaround

Use `outputFormat: name` task configuration

**Comment by vithati** [comment]
@piotrgwiazda , we have fixed the issue.
