### ISSUE TITLE
Modules\DTAExecutionHost.exe' failed with exit code 1  please help me to solve this isssue

### ISSUE THREAD

**Issue by Tuely** [microsoft/azure-pipelines-tasks#11526]
019-10-08T16:06:57.6913114Z       Example  /ResultsDirectory:<pathToResultsDirectory>
2019-10-08T16:06:57.6913425Z --ParentProcessId|/ParentProcessId:<ParentProcessId>
2019-10-08T16:06:57.6914147Z       Process Id of the Parent Process responsible for launching current process.
2019-10-08T16:06:57.6914547Z --Port|/Port:<Port>
2019-10-08T16:06:57.6915049Z       The Port for socket connection and receiving the event messages.
2019-10-08T16:06:57.6915373Z -?|--Help|/?|/Help
2019-10-08T16:06:57.6915621Z       Display this usage message.
2019-10-08T16:06:57.6916453Z --Collect|/Collect:<DataCollector FriendlyName>
2019-10-08T16:06:57.6916769Z       Enables data collector for the test run. More info here : https://aka.ms/vstest-collect
2019-10-08T16:06:57.6917124Z --InIsolation|/InIsolation
2019-10-08T16:06:57.6917419Z       Runs the tests in an isolated process. This makes vstest.console.exe 
2019-10-08T16:06:57.6917729Z       process less likely to be stopped on an error in the tests, but tests 
2019-10-08T16:06:57.6918452Z       may run slower.
2019-10-08T16:06:57.6918783Z @<file>
2019-10-08T16:06:57.6919201Z       Read response file for more options.
2019-10-08T16:06:57.6920214Z   To run tests:
2019-10-08T16:06:57.6920487Z     >vstest.console.exe tests.dll 
2019-10-08T16:06:57.6920770Z   To run tests with additional settings such as  data collectors:
2019-10-08T16:06:57.6921079Z     >vstest.console.exe  tests.dll /Settings:Local.RunSettings
2019-10-08T16:06:57.7072746Z Vstest.console.exe exited with code 1.
2019-10-08T16:06:57.7073215Z **************** Completed test execution *********************
2019-10-08T16:06:57.7103875Z Test results files: C:\Agent1\_work\_temp\TestResults\TestVM_TestRun_2019-10-08_16_43_58.trx
2019-10-08T16:06:57.7373846Z Updating test results: 152
2019-10-08T16:06:57.7651211Z Publishing test results to test run '1005764'.
2019-10-08T16:06:57.9053721Z TestResults To Publish 152, Test run id:1005764
2019-10-08T16:06:57.9059025Z Test results publishing 152, remaining: 0. Test run id: 1005764
2019-10-08T16:07:01.5103803Z Updated test results: 152
2019-10-08T16:07:01.5104334Z Publishing Attachments: 1
2019-10-08T16:07:01.5634401Z ##[warning]This TestVM_TestRun_2019-10-08_16_43_58.trx already exists
2019-10-08T16:07:01.7747992Z ##[warning]Maximum number of attempts running the failed tests reached: 3
2019-10-08T16:07:02.2329485Z Execution Result Code 1 is non zero, checking for failed results
2019-10-08T16:07:02.2838568Z Completed TestExecution Model...
2019-10-08T16:07:02.3112470Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2019-10-08T16:07:02.3113545Z ##[error]Error: The process 'C:\Agent1\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.157.5\Modules\DTAExecutionHost.exe' failed with exit code 1
2019-10-08T16:07:02.3116490Z ##[error]Vstest failed with error. Check logs for failures. There might be failed tests.
2019-10-08T16:07:02.3209473Z ##[section]Finishing: VsTest - testAssemblies
2019-10-08T16:07:02.3361941Z ##[section]Starting: Publish Test Results **/TEST-*.xml
2019-10-08T16:07:02.3366679Z ==============================================================================
2019-10-08T16:07:02.3366801Z Task         : Publish Test Results
2019-10-08T16:07:02.3367198Z Description  : Publish test results to Azure Pipelines
2019-10-08T16:07:02.3367318Z Version      : 2.158.0
2019-10-08T16:07:02.3367410Z Author       : Microsoft Corporation
2019-10-08T16:07:02.3367702Z Help         : [Learn more about this task](https://go.microsoft.com/fwlink/?LinkID=613742)
2019-10-08T16:07:02.3367841Z ==============================================================================
2019-10-08T16:07:04.2925991Z [command]"C:\Program Files\dotnet\dotnet.exe" --version
2019-10-08T16:07:07.2533044Z 2.1.509
2019-10-08T16:07:07.2536039Z ##[warning]No test result files matching **/TEST-*.xml were found.
2019-10-08T16:07:07.4190992Z ##[section]Finishing: Publish Test Results **/TEST-*.xml
2019-10-08T16:07:07.4282994Z ##[section]Starting: Generate SpecFlow Report
2019-10-08T16:07:07.4286104Z ==============================================================================
2019-10-08T16:07:07.4286235Z Task         : Report Generator for SpecFlow
2019-10-08T16:07:07.4286353Z Description  : SpecFlow Test Execution Report Generator
2019-10-08T16:07:07.4286461Z Version      : 1.0.2
2019-10-08T16:07:07.4286578Z Author       : Mario Majcica
2019-10-08T16:07:07.4286920Z Help         : Generates SpecFlow test execution reports in HTML format.
2019-10-08T16:07:07.4287033Z ==============================================================================
2019-10-08T16:07:11.5295985Z ##[error]No trx files was found using search pattern 'C:\Agent1\_work\12\s\TestResults'.
2019-10-08T16:07:11.5648016Z ##[section]Finishing: Generate SpecFlow Report
2019-10-08T16:07:11.5747596Z ##[section]Starting: Post Job Cleanup
2019-10-08T16:07:11.5819760Z Cleaning any cached credential from repository: Testing (Git)
2019-10-08T16:07:11.5876702Z ##[command]git config --unset-all http.https://hughub.visualstudio.com/HugHub/_git/Testing.extraheader
2019-10-08T16:07:11.6774195Z ##[command]git remote set-url origin https://hughub.visualstudio.com/HugHub/_git/Testing
2019-10-08T16:07:11.7546057Z ##[command]git remote set-url --push origin https://hughub.visualstudio.com/HugHub/_git/Testing
2019-10-08T16:07:11.8247174Z ##[section]Finishing: Post Job Cleanup
2019-10-08T16:07:11.8626421Z ##[section]Finishing: Phase 1

**Comment by mayankbansal018** [comment]
Can you please check if there were test failures in your build? If yes, then DATExecutionHost process fails  with exit code "1" if there are tests failures, which is by design.

**Comment by mayankbansal018** [comment]
@Tuely can you please confirm if tests are failing when you see DTAExecutionHost process exiting with code `1`

**Comment by Tuely** [comment]
@mayankbansal018 tests are not failing. I am getting test report. i think it's failing to write the report in vm. please find attached

![log](https://user-images.githubusercontent.com/29451624/66563510-d03e4480-eb55-11e9-9e2f-e9705529b78b.PNG)
![result](https://user-images.githubusercontent.com/29451624/66563511-d03e4480-eb55-11e9-860b-93dcd2f4fc74.PNG)

**Comment by mayankbansal018** [comment]
@Tuely I can see one of the test as failed in the report, in such case vstest.console, & dtaexecutionhost both fail with exit code 1

![image](https://user-images.githubusercontent.com/24792973/66564118-ddbaf500-eb7c-11e9-9580-1f57b9fa786c.png)

**Comment by Tuely** [comment]
Thanks @mayankbansal018  that makes sense:). Can you please help me out for this specflow report error as well 

![image](https://user-images.githubusercontent.com/29451624/66564662-74c18600-eb58-11e9-9aac-cd09ee1bd216.png)


##[error]No trx files was found using search pattern 'C:\Agent1\_work\12\s\TestResults

**Comment by mayankbansal018** [comment]
To mitigate this please change the input for specflow task to $Agent.TempDirectory.

please read solution section of https://developercommunity.visualstudio.com/content/problem/756960/21574modulesdtaexecutionhostexe-failed-with-exit-c.html for detailed explanation

**Comment by Tuely** [comment]
Thanks. Do i need to change in publish test reults and specflow report ?

![image](https://user-images.githubusercontent.com/29451624/66567014-3f1f9b80-eb5e-11e9-9005-d99a987c7883.png)

**Comment by Tuely** [comment]
![image](https://user-images.githubusercontent.com/29451624/66567048-4e9ee480-eb5e-11e9-94d8-45ef70468eb9.png)

**Comment by mayankbansal018** [comment]
yes, although in your publish test results task you are giving filters as **/Test-*.xml, you might want to change it to .trx

**Comment by Tuely** [comment]
@mayankbansal018 i have changed to nunit now getting error as

![image](https://user-images.githubusercontent.com/29451624/66573459-9c214e80-eb6a-11e9-80ef-3a2eef4907d0.png)


##[section]Starting: Generate SpecFlow Report
==============================================================================
Task         : Report Generator for SpecFlow
Description  : SpecFlow Test Execution Report Generator
Version      : 1.0.2
Author       : Mario Majcica
Help         : Generates SpecFlow test execution reports in HTML format.
==============================================================================
##[command]"C:\Agent1\_work\_tasks\SpecFlowReportGenerator_064be1b0-3bf6-11e8-a3b0-9b14c8b87afb\1.0.2\ps_modules\2.3.1\specflow.exe" nunitexecutionreport "C:\Agent1\_work\12\s\AutomationPlatform\BrightSideTest\BrightSideTest.csproj" /xmlTestResult:"C:\Agent1\_work\_temp" /testOutput:"C:\Agent1\_work\12\a\Resultsfiles.html" /out:"C:\Agent1\_work\12\a\Resultsfile.html"
NConsoler.NConsolerException: Access to the path 'C:\Agent1\_work\_temp' is denied. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path 'C:\Agent1\_work\_temp' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at TechTalk.SpecFlow.Reporting.NUnitExecutionReport.NUnitExecutionReportGenerator.LoadXmlTestResult()
   at TechTalk.SpecFlow.Reporting.NUnitExecutionReport.NUnitBasedExecutionReportGenerator.GenerateReport(SpecFlowProject specFlowProject)
   at TechTalk.SpecFlow.Reporting.NUnitExecutionReport.NUnitBasedExecutionReportGenerator.GenerateAndTransformReport()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NConsoler.Consolery.InvokeMethod(MethodInfo method)
   --- End of inner exception stack trace ---
   at NConsoler.Consolery.InvokeMethod(MethodInfo method)
   at NConsoler.Consolery.Run(Type targetType, String[] args, IMessenger messenger)

**Comment by Tuely** [comment]
still i couldn't fetch the trx file in the specflow report

![image](https://user-images.githubusercontent.com/29451624/66585888-91bd7f80-eb7f-11e9-9d68-263dfbafaf21.png)

**Comment by Tuely** [comment]
publish trx file seems to be like this. I think the path which i ma giving is still wrong. tried with  $Agent.TempDirectory even that's not working

![image](https://user-images.githubusercontent.com/29451624/66586012-d1846700-eb7f-11e9-8444-3e3c27f6bef1.png)
