### ISSUE TITLE
Agent Cannot Authenticate

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-tasks#11559]
Using the latest Azure Agent (on-prem) on a Windows Server we have had success with all but one server. On one server the agent appears online and idle but will not accept any jobs. When we target it for a pipeline run the job just remains queued forever.

With Fiddler we see a 401 with the following response:
```
{"$id":"1","innerException":null,"message":"TF400813: The user '' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

We thought authentication runs via the PAT - why is it asking for a user?
Disclaimer: we used the same PAT for 2 instances of the agent on the same server.

Some other stuff:
```
[2019-10-14 09:41:36Z WARN VisualStudioServices] GET request to https://buhlergroup.visualstudio.com/_apis/distributedtask/pools/41/messages?sessionId=2233aa55-903c-4ba0-87e8-a6008f30a0f7&lastMessageId=2 has been cancelled.
[2019-10-14 09:41:36Z INFO MessageListener] Get next message has been cancelled.
[2019-10-14 09:41:36Z INFO Agent] Ignore any exception after cancel message loop. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
```

**Comment by cawoodm** [comment]
We're also seeing 403's on this: `https://buhlergroup.visualstudio.com/_apis/distributedtask/pools/41/messages?sessionId=2233aa55-903c-4ba0-87e8-a6008f30a0f7&lastMessageId=2`

**Comment by damccorm** [comment]
Hi, this looks like an issue with the agent - would you mind logging this issue there? https://github.com/microsoft/azure-pipelines-agent
