### ISSUE TITLE
Test step hanging in Azure Devops build pipeline 

### ISSUE THREAD

**Issue by patricknolan** [microsoft/azure-pipelines-tasks#11857]
Since updating my solution to .NET Core 3.0, EF Core 3.0 and xUnit 2.4.1, the test step is hanging. This step runs tests in about 5 test projects but it seems to hang on the the second project 9 out of 10 times.

How can I work out exactly what is causing this? Even when I run with diagnostics enabled the output doesn't seem to help much. See log below.

Updating my solution also coincided with the outage in Azure Devops last week so I'm not sure if there's still a problem with the environment\service that is causing my problem or if it's related to updating my solution.

Any help would be greatly appreciated!

**STEP**

```
===============================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.158.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
===============================================================

```
**OUTPUT**

```
/usr/bin/dotnet test /home/vsts/work/1/s/Rnh.Domain.Api.Tests/Rnh.Domain.Api.Tests.csproj --logger trx --results-directory /home/vsts/work/_temp --configuration Release
Test run for /home/vsts/work/1/s/Rnh.Domain.Api.Tests/bin/Release/netcoreapp3.0/Rnh.Domain.Api.Tests.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
##[debug]Re-evaluate condition on job cancellation for step: 'Test'.
##[debug]Skip Re-evaluate condition on agent shutdown.
##[error]The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
Finishing: Test

```

**Comment by ShreyasRmsft** [comment]
@patricknolan can you run your tests using the vstest task after build them with the dotnet task? We have a feature in the vstest task (it's still in preview) to detect hangs and collect process dumps.

https://github.com/microsoft/vstest-docs/blob/master/RFCs/0028-BlameCollector-Hang-Detection.md
