### ISSUE TITLE
Different issue points when using FileTransform@2

### ISSUE THREAD

**Issue by AllanMichaelsen** [microsoft/azure-pipelines-tasks#11856]
**Question, Bug, or Feature?**
Type: Bug

Enter Task Name: FileTransform@2

**Environment**
Server - Azure Pipelines

**Issue Description**
When using FileTransform@2 to tranform config files after build we are experiencing some weird behaviour...

If we run the above pipeline with the same two inputfiles, we get different errors on each run. Some runs it finishes an action at a point where it failed in the previous run.

**The pipeline step**
`    steps:
    - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)'
        xmlTransformationRules: '-transform buildFiles\App.Debug.config -xml BuildFiles\App.config -result $(artifactBatchConfig)'`

**Task logs**
Executing SetAttributes (transform line 41, 164)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Web.XmlTransform.XmlTransformationLogger.ConvertUriToFileName(XmlDocument xmlDocument)
   at Microsoft.Web.XmlTransform.XmlTransformationLogger.LogWarning(XmlNode referenceNode, String message, Object[] messageArgs)
   at Microsoft.Web.XmlTransform.Transform.ApplyOnAllTargetNodes()
Exception while transforming: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at OutcoldSolutions.ConfigTransformationTool.TransformationTask.Execute(String destinationFilePath, Boolean forceParametersTask).
on /configuration/securityConfiguration/authorizationProviders/add/rules/add[@name='AnsoegningRKI_Gem']
Applying to 'add' element (no source line info)
Set 'name' attribute
Set 'expression' attribute
Set 2 attributes
Done executing SetAttributes
Executing SetAttributes (transform line 42, 177)
on /configuration/securityConfiguration/authorizationProviders/add/rules/add[@name='AnsoegningRKI_CheckFirmaRKIGem']

-----------------------

Set 'expression' attribute
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Web.XmlTransform.XmlTransformationLogger.ConvertUriToFileName(XmlDocument xmlDocument)
   at Microsoft.Web.XmlTransform.XmlTransformationLogger.LogWarning(XmlNode referenceNode, String message, Object[] messageArgs)
   at Microsoft.Web.XmlTransform.Transform.ApplyOnAllTargetNodes()
Exception while transforming: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at OutcoldSolutions.ConfigTransformationTool.TransformationTask.Execute(String destinationFilePath, Boolean forceParametersTask).
Set 2 attributes
Done executing SetAttributes
Executing SetAttributes (transform line 38, 165)
on /configuration/securityConfiguration/authorizationProviders/add/rules/add[@name='AnsoegningRKI_Hent']

If we run the same two files through this powershell it works as expected (as it does in Visual Studio build as well)

`function applyConfigTransformation($src,$xdt,$dst){
Add-Type -Path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Web\Microsoft.Web.XmlTransform.dll"

  try{
    $doc = New-Object Microsoft.Web.XmlTransform.XmlTransformableDocument
    $doc.PreserveWhiteSpace = $true
    $doc.Load($src)
    
    $trn = New-Object Microsoft.Web.XmlTransform.XmlTransformation($xdt)
    if ($trn.Apply($doc)){
      $doc.Save($dst)
    }
    else{
      throw "Transformation terminated with status False"
    }
  }
  catch{
    Write-Output $Error[0].Exception
  } 
}`

**Comment by eaarora-ms** [comment]
@AllanMichaelsen  Can you please set the variable "System.debug" with value "true". Redeploy and share logs at RM_Customer_Queries at microsoft dot com

**Comment by eaarora-ms** [comment]
@AllanMichaelsen  Can you please confirm if you're still facing the issue? I haven't received any logs from you until now. Thanks!

**Comment by AllanMichaelsen** [comment]
Sorry for the late reply. A decision was made to transform in the project file instead as there was no time to wait for a solution. If no one else is experiencing this issue it could be a problem in the file structure somehow but I can't say for sure.

I can't send further logs as transformation in this manner has been stopped.
________________________________

**Comment by eaarora-ms** [comment]
Closing this in that case. Please comment if you face the issue again in the future.
