### ISSUE TITLE
PublishTestResults is marked as "succeeded" if dotnet app throws exception

### ISSUE THREAD

**Issue by mikeharder** [microsoft/azure-pipelines-tasks#11926]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/azure-sdk/public/_build/results?buildId=203814

- Agent - Hosted or Private: Hosted

## Issue Description

If the dotnet portion of the `PublishTestResults` task throws an exception, the task is marked as `succeeded` when it should be marked as `failed`.  The current behavior masks failures in the dotnet portion of the task.

Related: https://github.com/microsoft/azure-pipelines-tasks/issues/11925

### Task logs

[log_147_203814.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3933748/log_147_203814.zip)

### Error logs

```
2019-12-05T18:20:40.0049465Z ##[debug]Reading test results from file 'sdk/appconfiguration/app-configuration/test-results.xml'.
2019-12-05T18:20:40.0347004Z Failed to parse result files: System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/vsts/agents/2.160.1/bin/sdk/appconfiguration/app-configuration/test-results.xml'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ReadFile(String filePath, XmlDocument doc)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFile(TestRunContext runContext, String filePath)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.<>c__DisplayClass1_0.<ParseTestResultFiles>b__0(String file)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFiles(TestRunContext runContext, IList`1 resultFilePaths)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.Parser.ParseFiles(IExecutionContext executionContext, TestRunContext testRunContext, List`1 testResultsFiles, ITestResultParser testResultParser)
2019-12-05T18:20:40.0393637Z ##[debug]Processed: ##vso[results.publish type=JUnit;mergeResults=false;runTitle=Linux - NodeJS - Unit Tests - [Node 12.x%5D;publishRunAttachments=true;resultFiles=sdk/appconfiguration/app-configuration/test-results.xml,sdk/core/abort-controller/test-results.xml,sdk/core/core-amqp/test-results.xml,sdk/core/core-arm/test-results.xml,sdk/core/core-auth/test-results.xml,sdk/core/core-http/test-results.xml,sdk/core/core-lro/test-results.xml,sdk/core/core-tracing/test-results.xml,sdk/core/logger/test-results.xml,sdk/identity/identity/test-results.xml,sdk/keyvault/keyvault-certificates/test-results.xml,sdk/keyvault/keyvault-keys/test-results.xml,sdk/keyvault/keyvault-secrets/test-results.xml,sdk/storage/storage-blob/test-results.xml,sdk/storage/storage-file-datalake/test-results.xml,sdk/storage/storage-file-share/test-results.xml,sdk/storage/storage-queue/test-results.xml,sdk/template/template/test-results.xml;failTaskOnFailedTests=false;testRunSystem=VSTS - PTR;]
2019-12-05T18:20:40.0394555Z ##[debug]task result: Succeeded
```

**Comment by sahitiyerramilli** [comment]
Hey,

This is how the system is designed. In case there are multiple test files and one of the test files is not found, we publish the other results and display the problem in the logs.

**Comment by mikeharder** [comment]
What do you mean by a test file is "not found"?  In related issue #11925, the issue was that the JS component and .NET component of this task were not in sync, and this should cause `PublishTestResults` to fail.  There may be some cases where it's appropriate to skip missing results files, but I don't think this is one of them.

**Comment by sahitiyerramilli** [comment]
#11925  is a bug and we are working on it. But if a few files among a bunch of files are actually not found, then we don't fail the task by design.

**Comment by richardgavel** [comment]
I would throw another scenario in the mix: "Failed to parse result files. Invalid file format". If I tell it to parse files and it has trouble doing that, this is another scenario the publish should fail. This is very dangerous, because it passed, failures in another file it didn't pick up got thru.
