### ISSUE TITLE
PublishTestResults throws exception if searchFolder is relative path

### ISSUE THREAD

**Issue by mikeharder** [microsoft/azure-pipelines-tasks#11925]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/azure-sdk/public/_build/results?buildId=203814

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: Linux and Mac

## Issue Description

If `PublishTestResults.searchFolder` is set to a relative path, the task fails with an exception.  It fails on Linux and Mac but succeeds on Windows.  The root cause appears to be that the JS portion of the task resolves the relative path correctly (relative to repo root), but the dotnet portion of the task resolves the relative path against a different root, so the resolved path is no longer valid.

A workaround is to use an absolute path (e.g. `$(System.DefaultWorkingDirectory)/sdk` rather than just `sdk`).  However, other settings like `CopyFiles.sourceFolder` support relative paths, so I think `PublishTestResults.searchFolder` should support them as well.

### Task logs

[log_147_203814.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3933726/log_147_203814.zip)

### Error logs

```
##[debug]Reading test results from file 'sdk/appconfiguration/app-configuration/test-results.xml'.
Failed to parse result files: System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/vsts/agents/2.160.1/bin/sdk/appconfiguration/app-configuration/test-results.xml'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ReadFile(String filePath, XmlDocument doc)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFile(TestRunContext runContext, String filePath)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.<>c__DisplayClass1_0.<ParseTestResultFiles>b__0(String file)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFiles(TestRunContext runContext, IList`1 resultFilePaths)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.Parser.ParseFiles(IExecutionContext executionContext, TestRunContext testRunContext, List`1 testResultsFiles, ITestResultParser testResultParser)
##[debug]Processed: ##vso[results.publish type=JUnit;mergeResults=false;runTitle=Linux - NodeJS - Unit Tests - [Node 12.x%5D;publishRunAttachments=true;resultFiles=sdk/appconfiguration/app-configuration/test-results.xml,sdk/core/abort-controller/test-results.xml,sdk/core/core-amqp/test-results.xml,sdk/core/core-arm/test-results.xml,sdk/core/core-auth/test-results.xml,sdk/core/core-http/test-results.xml,sdk/core/core-lro/test-results.xml,sdk/core/core-tracing/test-results.xml,sdk/core/logger/test-results.xml,sdk/identity/identity/test-results.xml,sdk/keyvault/keyvault-certificates/test-results.xml,sdk/keyvault/keyvault-keys/test-results.xml,sdk/keyvault/keyvault-secrets/test-results.xml,sdk/storage/storage-blob/test-results.xml,sdk/storage/storage-file-datalake/test-results.xml,sdk/storage/storage-file-share/test-results.xml,sdk/storage/storage-queue/test-results.xml,sdk/template/template/test-results.xml;failTaskOnFailedTests=false;testRunSystem=VSTS - PTR;]
##[debug]task result: Succeeded
```

**Comment by sahitiyerramilli** [comment]
Hey,

This is a bug on our side. We'll fix this soon. We'll keep you updated.

**Comment by navin22** [comment]
This has been fixed in the latest version of the task.
Please reopen the issue if you are still blocked.
