### ISSUE TITLE
ManagedBatchParser.ParserException

### ISSUE THREAD

**Issue by IndraVisatiya** [microsoft/azure-pipelines-tasks#12020]
Write-Exception : ManagedBatchParser.ParserException
2019-12-22T05:37:43.8797775Z ##[debug]   at ManagedBatchParser.Parser.Parse()
2019-12-22T05:37:43.8825890Z ##[debug]   at Microsoft.SqlServer.Management.PowerShell.ExecutionProcessor.ExecuteTSql(String sqlCommand)
2019-12-22T05:37:43.8849714Z ##[debug]At C:\azagent\A1\_work\_tasks\SqlDacpacDeploymentOnMachineGroup_4b506f7f-720f-47bb-bf21-029bac6a690d\0.3.20\Main.ps1:189 char:5
2019-12-22T05:37:43.8871547Z ##[debug]+     Write-Exception($_.Exception)
2019-12-22T05:37:43.8892174Z ##[debug]+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-12-22T05:37:43.8910992Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep    tion
2019-12-22T05:37:43.8931734Z ##[debug]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio    n,Write-Exception
2019-12-22T05:37:43.8955358Z ##[debug]

**Comment by arjgupta** [comment]
@IndraVisatiya , can you please send the debug logs for the task to RM_Customer_Queries at microsoft dot com
