### ISSUE TITLE
Failed: ETIMEDOUT connect ETIMEDOUT when running tests in VM to Browserstack

### ISSUE THREAD

**Issue by ivan-xue-prospa** [microsoft/azure-pipelines-tasks#12092]
We have some tests designed using Protractor and running in Browserstack.

When running the same tests from local, everything works fine. But when running the tests in the hosted Windows agent through a docker from azure release pipeline, we are getting the following errors:

`2020-01-08T04:37:53.1662840Z [IE]       [31m- [39m[31mFailed: ETIMEDOUT connect ETIMEDOUT 173.234.104.15:80[39m
2020-01-08T04:37:53.1676110Z [IE] 
2020-01-08T04:37:53.1688573Z [IE]   Top level suite
2020-01-08T04:37:53.1700197Z [IE]     [31m✗ Non-spec failure[39m (undefined)
2020-01-08T04:37:53.1713365Z [IE]       [31m- [39m[31mWebDriverError: Session not started or terminated[39m
2020-01-08T04:37:53.1726310Z [IE] 
2020-01-08T04:37:53.1738638Z [IE] Executed 8 of 8 specs[31m (1 ERROR)[39m[31m (1 FAILED)[39m in 5 mins 48 secs.
2020-01-08T04:37:53.1752133Z [IE] 
2020-01-08T04:37:53.1768665Z [IE] /app/node_modules/selenium-webdriver/lib/error.js:546
2020-01-08T04:37:53.1786876Z [IE]         throw new ctor(message);
2020-01-08T04:37:53.1800531Z [IE]               ^
2020-01-08T04:37:53.1813641Z [IE] WebDriverError: Session not started or terminated
2020-01-08T04:37:53.1828039Z [IE]     at Object.checkLegacyResponse (/app/node_modules/selenium-webdriver/lib/error.js:546:15)
2020-01-08T04:37:53.1842539Z [IE]     at parseHttpResponse (/app/node_modules/selenium-webdriver/lib/http.js:509:13)
2020-01-08T04:37:53.1856823Z [IE]     at doSend.then.response (/app/node_modules/selenium-webdriver/lib/http.js:441:30)
2020-01-08T04:37:53.1870837Z [IE]     at processTicksAndRejections (internal/process/task_queues.js:86:5)
2020-01-08T04:37:53.1884922Z [IE] From: Task: WebDriver.quit()
2020-01-08T04:37:53.1897418Z [IE]     at thenableWebDriverProxy.schedule (/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
2020-01-08T04:37:53.1909496Z [IE]     at thenableWebDriverProxy.quit (/app/node_modules/selenium-webdriver/lib/webdriver.js:840:23)
2020-01-08T04:37:53.1921425Z [IE]     at run (/app/node_modules/protractor/built/browser.js:59:33)
2020-01-08T04:37:53.1933884Z [IE]     at ProtractorBrowser.to.(anonymous function) [as quit] (/app/node_modules/protractor/built/browser.js:67:16)
2020-01-08T04:37:53.1945988Z [IE]     at onComplete (/app/e2e/protractorBrowserstackLocal.conf.js:151:13)
2020-01-08T04:37:53.1957246Z [IE]     at /app/node_modules/protractor/built/frameworks/jasmine.js:115:27
2020-01-08T04:37:53.1968975Z [IE]     at module.exports.jasmineDone (/app/node_modules/jasmine/lib/reporters/completion_reporter.js:15:5)
2020-01-08T04:37:53.1979912Z [IE]     at dispatch (/app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4366:28)
2020-01-08T04:37:53.1990703Z [IE]     at ReportDispatcher.jasmineDone (/app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4337:11)
2020-01-08T04:37:53.2002314Z [IE]     at QueueRunner.onComplete (/app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:994:18)
2020-01-08T04:37:53.2013500Z [IE]     at Timeout._onTimeout (/app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4231:12)
2020-01-08T04:37:53.2029630Z [IE]     at listOnTimeout (internal/timers.js:535:17)
2020-01-08T04:37:53.2042016Z [IE]     at processTimers (internal/timers.js:479:7)`

I tried to increase idle timeout for the test agent network, but no luck.

**Comment by ShreyasRmsft** [comment]
Could be an issue with docker on the hosted agents.

**Comment by zachariahcox** [comment]
@prativen , this appears to be a containers ecosystem issue.

**Comment by pingvishal-msft** [comment]
@ivan-xue-prospa Please share a sample pipeline to reproduce and analyze this further.

**Comment by ivan-xue-prospa** [comment]
https://prospadev.visualstudio.com/Prospa%20Development/_releaseProgress?_a=release-environment-logs&releaseId=29492&environmentId=99759
