### ISSUE TITLE
Microsoft.Rest.SerializationException: Unable to deserialize the response.

### ISSUE THREAD

**Issue by flabbergasted** [microsoft/azure-pipelines-tasks#12127]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure file copy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
account (organization?): processunity
team project: trunk
build definition id: 33
release id: 6476 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    Windows Server 2012 R2 Datacenter.
   Agent version: 2.155.1

## Issue Description

[Include task name(s), screenshots and any other relevant details]
Trying to add a file to an azure storage account, and I'm getting a 'Unable to deserialize the response' error.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
Attached full system.debug log.
[tasklog_10.log](https://github.com/microsoft/azure-pipelines-tasks/files/4047844/tasklog_10.log)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
2020-01-10T20:32:56.0394337Z ##[debug]Caught exception from task script.
2020-01-10T20:32:56.0394508Z ##[debug]Error record:
2020-01-10T20:32:56.0394707Z ##[debug]Get-AzureRmStorageAccount : Unable to deserialize the response.
2020-01-10T20:32:56.0394998Z ##[debug]At C:\azagent\A1\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\2.154.16\AzureUtilityGTE1.0.ps1:27 char:47
2020-01-10T20:32:56.0395225Z ##[debug]+ ... ResourceDetails = Get-AzureRmStorageAccount -ErrorAction Stop | Where ...
2020-01-10T20:32:56.0395539Z ##[debug]+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-10T20:32:56.0395756Z ##[debug]    + CategoryInfo          : CloseError: (:) [Get-AzureRmStorageAccount], Ser    ializationException
2020-01-10T20:32:56.0395997Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetA    zureStorageAccountCommand
2020-01-10T20:32:56.0397599Z ##[debug] 
2020-01-10T20:32:56.0397884Z ##[debug]Script stack trace:
2020-01-10T20:32:56.0398135Z ##[debug]at Get-AzureStorageAccountResourceGroupName, C:\azagent\A1\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\2.154.16\AzureUtilityGTE1.0.ps1: line 27
2020-01-10T20:32:56.0398425Z ##[debug]at Get-AzureStorageKeyFromARM, C:\azagent\A1\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\2.154.16\AzureUtilityRest.ps1: line 28
2020-01-10T20:32:56.0398707Z ##[debug]at Get-StorageKey, C:\azagent\A1\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\2.154.16\Utility.ps1: line 149
2020-01-10T20:32:56.0399226Z ##[debug]at <ScriptBlock>, C:\azagent\A1\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\2.154.16\AzureFileCopy.ps1: line 101
2020-01-10T20:32:56.0399474Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-01-10T20:32:56.0420178Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-01-10T20:32:56.0421114Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-01-10T20:32:56.0421330Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-01-10T20:32:56.0421573Z ##[debug]Exception:
2020-01-10T20:32:56.0421859Z ##[debug]Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "FileStorage" to type 'System.Nullable`1[Microsoft.Azure.Management.Storage.Models.Kind]'. Path '', line 1, position 74541. ---> System.ArgumentException: Requested value 'FileStorage' was not found.
2020-01-10T20:32:56.0422352Z ##[debug]   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
2020-01-10T20:32:56.0422566Z ##[debug]   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
2020-01-10T20:32:56.0422777Z ##[debug]   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
2020-01-10T20:32:56.0423010Z ##[debug]   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2020-01-10T20:32:56.0423404Z ##[debug]   --- End of inner exception stack trace ---
2020-01-10T20:32:56.0423626Z ##[debug]   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2020-01-10T20:32:56.0424073Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2020-01-10T20:32:56.0424494Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2020-01-10T20:32:56.0425088Z ##[debug]   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
2020-01-10T20:32:56.0425337Z ##[debug]   at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2020-01-10T20:32:56.0425622Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2020-01-10T20:32:56.0426089Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
2020-01-10T20:32:56.0426581Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
2020-01-10T20:32:56.0427141Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2020-01-10T20:32:56.0427738Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2020-01-10T20:32:56.0428483Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2020-01-10T20:32:56.0433160Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2020-01-10T20:32:56.0433766Z ##[debug]   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2020-01-10T20:32:56.0450920Z ##[debug]   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
2020-01-10T20:32:56.0557263Z ##[debug]   at Microsoft.Azure.Management.Storage.StorageAccountsOperations.<ListWithHttpMessagesAsync>d__10.MoveNext()
2020-01-10T20:32:56.0581700Z ##[debug]   --- End of inner exception stack trace ---
2020-01-10T20:32:56.0620650Z ##[debug]   at Microsoft.Azure.Management.Storage.StorageAccountsOperations.<ListWithHttpMessagesAsync>d__10.MoveNext()
2020-01-10T20:32:56.0627070Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2020-01-10T20:32:56.0627635Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2020-01-10T20:32:56.0628124Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-01-10T20:32:56.0628728Z ##[debug]   at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.<ListAsync>d__11.MoveNext()
2020-01-10T20:32:56.0629503Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2020-01-10T20:32:56.0629895Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2020-01-10T20:32:56.0630220Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-01-10T20:32:56.0638192Z ##[debug]   at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.List(IStorageAccountsOperations operations)
2020-01-10T20:32:56.0654443Z ##[debug]   at Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand.ExecuteCmdlet()
2020-01-10T20:32:56.0693546Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

**Comment by arjgupta** [comment]
@flabbergasted can you try to upgrade the version Azure PowerShell installed on your private agent. This should work.

**Comment by arjgupta** [comment]
Closing this issue. Please reopen if you are still facing this issue.
