### ISSUE TITLE
Test runs intermittently fail with "did not complete yet".

### ISSUE THREAD

**Issue by andersforsgren** [microsoft/azure-pipelines-tasks#12151]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**:  
VsTest

## Environment

DevOps Server 2019.1 / Dev17.M153.3
Agent: Private, v2.153.1 on Windows 10 v1809
    
## Issue Description

Test runs where vstest executes mstest unit tests intermittently fail with error message "Test run NNNN did not complete yet."

(Edit: removed "on multiple agents" because this error reproduces for a run executing a single test)

Before this, the logs say ` IsValidServiceResponse: Received None command..Service Workflow is not active`. Successful runs log "Received the command : Start", while failing runs do not.

### Error logs

Relevant section of a failing run

```
2020-01-15T14:44:12.8228735Z Test run with Id 32871 associated
2020-01-15T14:44:12.9581464Z ##[debug]TestHostStart.Run : Waiting to get a start command or stop/cancel command
2020-01-15T14:44:22.6980998Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:44:42.7125011Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:45:22.7503409Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:46:22.7426443Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:47:22.7365086Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:48:22.8552866Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:49:22.8468945Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:50:22.8552019Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:51:22.8904590Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:52:22.8791732Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:53:22.8891899Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:54:22.8998115Z IsValidServiceResponse: Received None command..Service Workflow is not active
2020-01-15T14:54:22.9050145Z TestExecutionHost.ProcessCommand. Stop Command handled
2020-01-15T14:54:22.9051666Z ##[debug]TestHostStart.Run : TestHost stop/cancel invoked
2020-01-15T14:54:22.9051985Z ##[debug]ExecutionStateResolver.SetNextPhase : Current Phase: TestHostStart
2020-01-15T14:54:22.9052242Z ##[debug]ExecutionStateResolver.SetNextPhase : Next Phase: TestHostEnd
2020-01-15T14:54:22.9052434Z ##[debug]TestExecutionHost.Execute: Current Phase TestHostEnd
2020-01-15T14:54:22.9053775Z ##[debug]VstestAdapter.ExecuteAsync : Starting Execution
2020-01-15T14:54:22.9910946Z ##[debug]ProceedAfterAbortedTestCase : False
2020-01-15T14:54:23.2377448Z ##[debug]SliceDetailsStore.NormalizeSettings : No Slice details or run information
2020-01-15T14:54:23.2377777Z ##[debug]VstestAdapter.ExecuteAsync : Returning
2020-01-15T14:54:23.2406652Z ##[debug]TestHostEnd.Run : CancellatationRequested: True : RunCreated : True : RunCompleted : False
2020-01-15T14:54:23.2505280Z ##[debug]TestHostEnd.Run: Run not completed. Waiting for the stop event
2020-01-15T14:54:23.2505582Z ##[debug]TestHostStop.Run : Logging the test run details
2020-01-15T14:54:23.2623773Z Test run '32871' is in 'InProgress' state.
2020-01-15T14:54:23.2705405Z ##[error]Test run 32871 did not complete yet.
2020-01-15T14:54:23.4977768Z ##[debug]Processed: ##vso[task.logissue type=error;]Test run 32871 did not complete yet.
2020-01-15T14:54:23.5004022Z ##[debug]Processed: ##vso[task.complete result=Failed;]Test run 32871 did not complete yet.
2020-01-15T14:54:23.5895491Z ##[debug]Deleted test settings with id : 9422
```

For comparison, a successful build has "Received the command : Start" and continues to execute tests. 

```
2020-01-15T12:54:09.3060326Z Test run with Id 32829 associated
2020-01-15T12:54:09.4245735Z ##[debug]TestHostStart.Run : Waiting to get a start command or stop/cancel command
2020-01-15T12:54:20.2245116Z Received the command : Start
2020-01-15T12:54:20.2281652Z TestExecutionHost.ProcessCommand. Start Command handled
2020-01-15T12:54:20.2282673Z ##[debug]Notified the command 1 : {"Command":1}
2020-01-15T12:54:20.2283839Z ##[debug]TestHostStart.Run : TestHost start invoked
2020-01-15T12:54:20.2284475Z ##[debug]ExecutionStateResolver.SetNextPhase : Current Phase: TestHostStart
```

### Task logs

Can provide privately if necessary, they are quite large

**Comment by andersforsgren** [comment]
**Update**: found the problem. 

The cause was time drift between the build agents and the DevOps server, causing all auth to fail. 

The issue of clock difference between Agents and DevOps should perhaps be added to this troubleshooting guide:
https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops#common-issues-and-resolutions
, as it may not be immediately obvious that the reason the auth token is expired is because of disagreeing clocks.

This issue can be closed.

The offending line in the agent log:
```
[2020-01-17 15:58:14Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\TfsAgent\1\.credentials_rsaparams
[2020-01-17 15:58:14Z ERR  VisualStudioServices] POST request to http://[server]/tfs/_apis/oauth2/token failed. HTTP Status: BadRequest
[2020-01-17 15:58:14Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2020-01-17 15:58:14Z ERR  MessageListener] Catch exception during get next message.
[2020-01-17 15:58:14Z ERR  MessageListener] Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenRequestException: The bearer <secret removed> expired on 1/17/2020 4:03:15 PM. Current server time is 1/17/2020 5:54:21 PM.
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
```

**Comment by PrashanthSannayalaGit** [comment]
@andersforsgren i am getting the same exception from my On Demand Pipelines. Could you please tell me know did you resolve this issue. 

Here is the log i am getting 

TestExecutionHost.Execute: Registered TestAgent : 265 : LWLT5CD104R5X7-PS-Agent-02-91
Updated Run Settings:
<RunSettings>
  <RunConfiguration>
    <BatchSize>1000</BatchSize>
    <ResultsDirectory>C:\Company\Agents\new-agents\New-Agent-Prash-2\vsts-agent-win-x64-2.204.0\_work\_temp\TestResults</ResultsDirectory>
  </RunConfiguration>
</RunSettings>
IsValidServiceResponse: Received None command..Service Workflow is not active
Creating run for selected test assemblies with following parameters
SourceFilter: *.dll TestCaseFilter: 
Run title: TestRun_RE1 - On Demand Runner - Mobile App - Android_Release-22
Build location: C:\Lowell\Agents\new-agents\New-Agent-Prash-2\vsts-agent-win-x64-2.204.0\_work\r1\a\AutoTests
Build Id: 12077
Test run with Id 42224 associated
IsValidServiceResponse: Received None command..Service Workflow is not active
IsValidServiceResponse: Received None command..Service Workflow is not active
IsValidServiceResponse: Received None command..Service Workflow is not active
IsValidServiceResponse: Received None command..Service Workflow is not active
IsValidServiceResponse: Received None command..Service Workflow is not active
IsValidServiceResponse: Received None command..Service Workflow is not active

**Comment by TimotyTimm** [comment]
We have the same issue starting from 2nd July 2022 until now from any agents (microsoft and self hosted) so i don't think the issue with the time drift now. 
https://developercommunity.visualstudio.com is down so it is not possible to submit (https://status.visualstudio.microsoft.com/status)

@andersforsgren could you pls clarify it is working for you today ? for any visual studio tests in AZDO

**Comment by PrashanthSannayalaGit** [comment]
@TimotyTimm exactly I am facing the issue since 4th July 2022. (As 2nd July was weekend, we have not run the pipeline). This was working fine until Friday 1st July 2022. 

@andersforsgren as you have mentioned, I have verified the time zones from my local system (Running Local Agent) to the DevOps Server however, they are same. Could you also give it a try and see if it is working for you please :)

**Comment by andersforsgren** [comment]
I have no issues with pipelines at the moment. We use only self-hosted agents. The probleem in this issue has not returned since we synchronized the clocks and solved the issue in Jan 2020.

I don't think it was a time *zone* issue, I think it was just a matter of time drift by a few minutes due to missing clock synchronization, but I might be misremembering.

**Comment by TimotyTimm** [comment]
> @andersforsgren apologies, I meant to say the drift time only.
> 
> @andersforsgren @TimotyTimm I am using 2 types of pipelines 1. Scheduled Pipelines 2. On Demand Runners both of these pipelines uses Local Agents only
> 
> The Scheduled pipelines are working fine. There is no issue observed as of now.
> 
> However the On Demand Runners will be initiated from the Test Plan, these On Demand runner pipelines stopped working since 2nd/4th July 2022

For me it is not working for both - scheduled  and on demand as well. Haven't found any solutions for now.

**Comment by vaughanh1** [comment]
I am also seeing this issue today. Will this ticket be reopened or has a new one been created yet?

**Comment by TimotyTimm** [comment]
looks like it was fixed 
https://developercommunity.visualstudio.com/t/Azure-DevOps:-Issue-with-Visual-Studio-T/10089391

**Comment by rhyscooper** [comment]
Same here, all working now as of this morning. Thanks!

**Comment by vaughanh1** [comment]
As per comment from @TimotyTimm I can confirm it now works. Thanks
