### ISSUE TITLE
Reading a json file using PowerShell fails 

### ISSUE THREAD

**Issue by dzhavat** [microsoft/azure-pipelines-tasks#12219]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShell

## Environment
- Server - Azure Pipelines
  
## Issue Description

I'm using the PowerShell@2 task to read the content of a generated json file and pipe it to a command. It's an inline script that looks like this: 

`'Get-Content report.json | ./node_modules/.bin/cucumber-junit > report.xml'`

### Error logs

```text
2020-01-24T13:26:55.0933805Z ##[section]Starting: Generate Cucumber Report
2020-01-24T13:26:55.1136787Z ==============================================================================
2020-01-24T13:26:55.1136863Z Task         : PowerShell
2020-01-24T13:26:55.1136923Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2020-01-24T13:26:55.1136958Z Version      : 2.151.2
2020-01-24T13:26:55.1136990Z Author       : Microsoft Corporation
2020-01-24T13:26:55.1137024Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2020-01-24T13:26:55.1137082Z ==============================================================================
2020-01-24T13:26:56.1053338Z Generating script.
2020-01-24T13:26:56.1507941Z ========================== Starting Command Output ===========================
2020-01-24T13:26:56.1813819Z ##[command]"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'd:\a\_temp\asd21312-1312-456a-aefe-1cc5c91dcf3c.ps1'"
2020-01-24T13:26:56.7657076Z undefined:1
2020-01-24T13:26:56.7657705Z ï»¿[
2020-01-24T13:26:56.7657898Z ^
2020-01-24T13:26:56.7658032Z 
2020-01-24T13:26:56.7659018Z SyntaxError: Unexpected token ï»¿ in JSON at position 0
2020-01-24T13:26:56.7659207Z     at JSON.parse (<anonymous>)
2020-01-24T13:26:56.7659740Z     at cucumberJunit (D:\a\1\s\Source\WebApp\node_modules\cucumber-junit\lib\cucumber_junit.js:204:29)
2020-01-24T13:26:56.7661045Z     at Socket.<anonymous> (D:\a\1\s\Source\WebApp\node_modules\cucumber-junit\bin\cucumber-junit:39:26)
2020-01-24T13:26:56.7661546Z     at Socket.emit (events.js:228:7)
2020-01-24T13:26:56.7662509Z     at endReadableNT (_stream_readable.js:1185:12)
2020-01-24T13:26:56.7665779Z     at processTicksAndRejections (internal/process/task_queues.js:81:21)
2020-01-24T13:26:56.9071388Z ##[error]PowerShell exited with code '1'.
2020-01-24T13:26:56.9434061Z ##[section]Finishing: Generate Cucumber Report
```

The same command runs perfectly fine locally. It only fails when ran on Azure. It seems like reading the file using PowerShell is always with Byte-order-mark and this is where things break.

**Comment by damccorm** [comment]
Hey @dzhavat - could you try running the build with a pipeline variable `agent.retainDefaultEncoding` set to true?

**Comment by damccorm** [comment]
Closing due to inactivity
