### ISSUE TITLE
AzureFileCopy: Input required: ConnectedServiceNameSelector

### ISSUE THREAD

**Issue by M0ns1gn0r** [microsoft/azure-pipelines-tasks#12247]
**Type**: Bug
**Task Name**: AzureFileCopy
**Server**: Azure Pipelines
**Agent**: hosted windows-latest

## Issue Description

When AzureFileCopy is used in the pipeline, it automatically adds and executes the pipeline task `Pre-job: xxxx`. This task gets marked as succeeded but there is an error in its log:

 `Unable to fetch storage account key. Error: '{0}' Error: Input required: ConnectedServiceNameSelector`.

This line seems to cause the error:
https://github.com/microsoft/azure-pipelines-tasks/blob/5f7eb9fd13740244e080d5eac6b0cd638b18d7b9/Tasks/AzureFileCopyV3/PreJobExecutionAzureFileCopy.ts#L30

But *AzureFileCopyV3* does not accept this argument, it accepts only `ConnectedServiceNameARM` with the alias `azureSubscription`. Here is how I call the task:

```yaml
- task: AzureFileCopy@3
  displayName: Deploy to Blob
  inputs:
    azureSubscription: $(pipelineSpn)
    sourcePath: $(extractedArtifactLocation)
    destination: azureBlob
    storage: $(storageName)
    containerName: $web
    cleanTargetBeforeCopy: true
```

### Task logs

	2020-01-28T14:46:34.9790245Z ##[debug]Evaluating condition for step: 'Deploy to Blob'
	2020-01-28T14:46:34.9899679Z ##[debug]Evaluating: SucceededNode()
	2020-01-28T14:46:34.9912255Z ##[debug]Evaluating SucceededNode:
	2020-01-28T14:46:34.9995337Z ##[debug]=> True
	2020-01-28T14:46:35.0024176Z ##[debug]Result: True
	2020-01-28T14:46:35.0081179Z ##[section]Starting: Deploy to Blob
	2020-01-28T14:46:35.1853275Z ==============================================================================
	2020-01-28T14:46:35.1853387Z Task         : Azure file copy
	2020-01-28T14:46:35.1853459Z Description  : Copy files to Azure Blob Storage or virtual machines
	2020-01-28T14:46:35.1853511Z Version      : 3.154.15
	2020-01-28T14:46:35.1853554Z Author       : Microsoft Corporation
	2020-01-28T14:46:35.1853629Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-file-copy
	2020-01-28T14:46:35.1853692Z ==============================================================================
	2020-01-28T14:46:35.5783188Z ##[debug]agent.TempDirectory=d:\a\_temp
	2020-01-28T14:46:35.5783812Z ##[debug]loading inputs and endpoints
	2020-01-28T14:46:35.5783897Z ##[debug]loading ENDPOINT_AUTH_edc991a3-e0ed-4468-8f41-3cbd0af2baa3
	2020-01-28T14:46:35.5957918Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_edc991a3-e0ed-4468-8f41-3cbd0af2baa3_AUTHENTICATIONTYPE
	2020-01-28T14:46:35.5961319Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_edc991a3-e0ed-4468-8f41-3cbd0af2baa3_SERVICEPRINCIPALID
	2020-01-28T14:46:35.5963395Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_edc991a3-e0ed-4468-8f41-3cbd0af2baa3_SERVICEPRINCIPALKEY
	2020-01-28T14:46:35.5965033Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_edc991a3-e0ed-4468-8f41-3cbd0af2baa3_TENANTID
	2020-01-28T14:46:35.5966678Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
	2020-01-28T14:46:35.5968356Z ##[debug]loading ENDPOINT_AUTH_SCHEME_edc991a3-e0ed-4468-8f41-3cbd0af2baa3
	2020-01-28T14:46:35.5970079Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
	2020-01-28T14:46:35.5971494Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
	2020-01-28T14:46:35.5976293Z ##[debug]loading INPUT_CLEANTARGETBEFORECOPY
	2020-01-28T14:46:35.5977966Z ##[debug]loading INPUT_CONNECTEDSERVICENAMEARM
	2020-01-28T14:46:35.5979470Z ##[debug]loading INPUT_CONTAINERNAME
	2020-01-28T14:46:35.5981039Z ##[debug]loading INPUT_COPYFILESINPARALLEL
	2020-01-28T14:46:35.5984599Z ##[debug]loading INPUT_DESTINATION
	2020-01-28T14:46:35.5984966Z ##[debug]loading INPUT_ENABLECOPYPREREQUISITES
	2020-01-28T14:46:35.5985847Z ##[debug]loading INPUT_RESOURCEFILTERINGMETHOD
	2020-01-28T14:46:35.5987686Z ##[debug]loading INPUT_SKIPCACHECK
	2020-01-28T14:46:35.5989220Z ##[debug]loading INPUT_SOURCEPATH
	2020-01-28T14:46:35.5990710Z ##[debug]loading INPUT_STORAGEACCOUNTRM
	2020-01-28T14:46:35.5996316Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
	2020-01-28T14:46:35.6003966Z ##[debug]loaded 20
	2020-01-28T14:46:35.6021159Z ##[debug]Agent.ProxyUrl=undefined
	2020-01-28T14:46:35.6022955Z ##[debug]Agent.CAInfo=undefined
	2020-01-28T14:46:35.6023581Z ##[debug]Agent.ClientCert=undefined
	2020-01-28T14:46:36.6835046Z ##[debug]Agent.SkipCertValidation=undefined
	2020-01-28T14:46:36.6841351Z ##[debug]agent.proxyurl=undefined
	2020-01-28T14:46:36.6844183Z ##[debug]VSTS_ARM_REST_IGNORE_SSL_ERRORS=undefined
	2020-01-28T14:46:36.6847012Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_8efdd2b9-a76d-438f-8d9d-d87ca45b4d74_build_3_0
	2020-01-28T14:46:36.6848510Z ##[debug]Agent.TempDirectory=d:\a\_temp
	2020-01-28T14:46:36.6848889Z ##[debug]Agent.TempDirectory=d:\a\_temp
	2020-01-28T14:46:36.6849256Z ##[debug]Setting resource path to d:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\3.154.15\task.json
	2020-01-28T14:46:36.6849579Z ##[debug]check path : d:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\3.154.15\task.json
	2020-01-28T14:46:36.6850041Z ##[debug]adding resource file: d:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\3.154.15\task.json
	2020-01-28T14:46:36.6850408Z ##[debug]system.culture=en-US
	2020-01-28T14:46:36.6852071Z Unable to fetch storage account key. Error: '{0}' Error: Input required: ConnectedServiceNameSelector
	2020-01-28T14:46:36.6852247Z     at Object.getInput (d:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\3.154.15\node_modules\azure-pipelines-task-lib\task.js:204:15)
	2020-01-28T14:46:36.6852355Z     at d:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\3.154.15\PreJobExecutionAzureFileCopy.js:35:37
	2020-01-28T14:46:36.6852436Z     at next (native)
	2020-01-28T14:46:36.6852612Z     at d:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\3.154.15\PreJobExecutionAzureFileCopy.js:7:71
	2020-01-28T14:46:36.6852699Z     at __awaiter (d:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\3.154.15\PreJobExecutionAzureFileCopy.js:3:12)
	2020-01-28T14:46:36.6852772Z     at run (d:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\3.154.15\PreJobExecutionAzureFileCopy.js:27:12)
	2020-01-28T14:46:36.6852860Z     at Object.<anonymous> (d:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\3.154.15\PreJobExecutionAzureFileCopy.js:60:1)
	2020-01-28T14:46:36.6852926Z     at Module._compile (module.js:577:32)
	2020-01-28T14:46:36.6853278Z     at Object.Module._extensions..js (module.js:586:10)
	2020-01-28T14:46:36.6853353Z     at Module.load (module.js:494:32)
	2020-01-28T14:46:36.6882450Z ##[section]Finishing: Deploy to Blob

**Comment by 20shivangi** [comment]
@M0ns1gn0r I agree some error is coming in Pre Job Execution step of AzureFileCopyV3. But this does not affect your main step of execution, the task is executed successfully.
We have fixed this issue in new version of AzureFileCopy i.e. V4 which will get deployed in 6-8 weeks.

**Comment by 20shivangi** [comment]
Please wait for 6-8 weeks to get new version of task. Closing this issue.

**Comment by ohwellwhatever** [comment]
Please don't close this issue, is blocking us.

**Comment by 20shivangi** [comment]
@ohwellwhatever Please use latest version of AzureFileCopy i.e. V4 version. It is fixed in there

**Comment by ohwellwhatever** [comment]
@20shivangi the problem with V4 is it doesn't support outputStorageUri and outputStorageContainerSasToken, which we are using for linked ARM template deployments.

**Comment by ohwellwhatever** [comment]
@20shivangi  also this https://github.com/Azure/azure-storage-azcopy/issues/474 is happening with v4

**Comment by 20shivangi** [comment]
@ohwellwhatever This V4 issue occurs if you have not provided sufficient permissions on your SPN. You have to provide permission of Storage Blob Owner and Storage Blob Contributor to you SPN. Once it is done, issue won't occur.
