### ISSUE TITLE
tar fails with "could not chdir" when cache isn't created

### ISSUE THREAD

**Issue by IanKemp** [microsoft/azure-pipelines-tasks#12268]
## Required Information

**Question, Bug, or Feature?** bug

**Enter Task Name**: `Cache@2`

## Environment
Azure Pipelines, hosted agent `macOS-latest`

## Issue Description

Task runs but fails to create a cache. As a result `tar` fails post-job because the cache directory doesn't exist.

```yaml
  - task: Cache@2
    inputs:
      key: 'cocoapods | "$(Agent.OS)"'
      restoreKeys: |
        gems | "$(Agent.OS)"
        gems
      path: $(COCOAPODS_PATH)
    displayName: Cache CocoaPods
```

### Error logs

Task:

```
Resolving restore key:
 - gems     [string]
 - "Darwin" [string]
Resolved to: gems|"Darwin"|**
Resolving restore key:
 - gems [string]
Resolved to: gems|**
##[debug]Dedup parallelism: 192
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `cocoapods|"Darwin"`
Information, Fingerprint: `gems|"Darwin"|**`
Information, Fingerprint: `gems|**`
Information, There is a cache miss.
```

Post-job:

```
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `cocoapods|"Darwin"`
Information, There is a cache miss.
##[debug]Starting 'tar' with arguments '-v -cf "9b340c4cd53c442db4bdda5e56da8e3d_archive.tar" -C "/Users/runner/runners/2.164.6/work/1/.cocoapods/repos/cocoapods-" .'...
tar: could not chdir to '/Users/runner/runners/2.164.6/work/1/.cocoapods/repos/cocoapods-'

##[error]Process returned non-zero exit code: 1
##[debug]Processed: ##vso[task.logissue type=error;]Process returned non-zero exit code: 1
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Agent.Plugins.PipelineCache.TarUtils.RunProcessAsync(AgentTaskPluginExecutionContext context, ProcessStartInfo processStartInfo, Func`3 additionalTaskToExecuteWhilstRunningProcess, Action actionOnFailure, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.TarUtils.RunProcessAsync(AgentTaskPluginExecutionContext context, ProcessStartInfo processStartInfo, Func`3 additionalTaskToExecuteWhilstRunningProcess, Action actionOnFailure, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.TarUtils.ArchiveFilesToTarAsync(AgentTaskPluginExecutionContext context, String inputPath, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.PipelineCacheServer.GetUploadPathAsync(ContentFormat contentFormat, AgentTaskPluginExecutionContext context, String path, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.PipelineCacheServer.UploadAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, String path, CancellationToken cancellationToken, ContentFormat contentFormat)
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, Func`1 restoreKeysGenerator, String path, CancellationToken token)
   at Agent.Plugins.PipelineCache.PipelineCacheTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: Cache CocoaPods
```

**Comment by johnterickson** [comment]
@IanKemp What state is the job in when the post-job task runs?  It should only run if the job is in a successful state.

**Comment by dzielin** [comment]
I'm having a similar issue with .npm caching.  I used the documentation provided [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#nodejsnpm), but removed the "package-lock.json" because my solution has multiple package locks (one in each project).  I'm just trying to get it to cache _something_, and to make sure I'm subsequently getting a cache hit.

Everything up to the cache post-job ran successfully.

Task YAML:
```
#Your build pipeline references an undefined variable named ‘Pipeline.Workspace’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: Cache@2
  displayName: 'Cache .npm folder'
  inputs:
    key: 'npm | "$(Agent.OS)"'
    path: '$(Pipeline.Workspace)/.npm'
    restoreKeys: |
     npm | "$(Agent.OS)"
     npm
```

Task Output:
```
2020-02-10T19:48:53.9542773Z ##[debug]Evaluating condition for step: 'Cache .npm folder'
2020-02-10T19:48:53.9543876Z ##[debug]Evaluating: succeeded()
2020-02-10T19:48:53.9544018Z ##[debug]Evaluating succeeded:
2020-02-10T19:48:53.9544387Z ##[debug]=> True
2020-02-10T19:48:53.9544623Z ##[debug]Result: True
2020-02-10T19:48:53.9544880Z ##[section]Starting: Cache .npm folder
2020-02-10T19:48:53.9647535Z ==============================================================================
2020-02-10T19:48:53.9647625Z Task         : Cache
2020-02-10T19:48:53.9647680Z Description  : Cache files between runs
2020-02-10T19:48:53.9647730Z Version      : 2.0.0
2020-02-10T19:48:53.9647792Z Author       : Microsoft Corporation
2020-02-10T19:48:53.9647844Z Help         : https://aka.ms/pipeline-caching-docs
2020-02-10T19:48:53.9647913Z ==============================================================================
2020-02-10T19:48:54.3739962Z Resolving key:
2020-02-10T19:48:54.3948244Z  - npm          [string]
2020-02-10T19:48:54.3957856Z  - "Windows_NT" [string]
2020-02-10T19:48:54.3980952Z Resolved to: npm|"Windows_NT"
2020-02-10T19:48:54.4010201Z ##[debug]Processed: ##vso[task.settaskvariable variable=RESTORE_STEP_RAN;issecret=False;]true
2020-02-10T19:48:54.4010686Z ##[debug]Processed: ##vso[task.settaskvariable variable=RESTORE_STEP_RESOLVED_FINGERPRINT;issecret=False;]npm|"Windows_NT"
2020-02-10T19:48:54.4024284Z Resolving restore key:
2020-02-10T19:48:54.4025044Z  - npm          [string]
2020-02-10T19:48:54.4025273Z  - "Windows_NT" [string]
2020-02-10T19:48:54.4026893Z Resolved to: npm|"Windows_NT"|**
2020-02-10T19:48:54.4027134Z Resolving restore key:
2020-02-10T19:48:54.4027325Z  - npm [string]
2020-02-10T19:48:54.4027495Z Resolved to: npm|**
2020-02-10T19:48:55.3319918Z ##[debug]Dedup parallelism: 192
2020-02-10T19:48:55.5346928Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 66cec078-40fc-40ff-a72e-31ecab6050b0
2020-02-10T19:48:55.8903737Z Information, Getting a pipeline cache artifact with one of the following fingerprints:
2020-02-10T19:48:55.8904269Z Information, Fingerprint: `npm|"Windows_NT"`
2020-02-10T19:48:55.8904689Z Information, Fingerprint: `npm|"Windows_NT"|**`
2020-02-10T19:48:55.8904875Z Information, Fingerprint: `npm|**`
2020-02-10T19:48:56.6127617Z Information, There is a cache miss.
2020-02-10T19:48:56.6829565Z ##[debug]Processed: ##vso[telemetry.publish area=AzurePipelinesAgent;feature=PipelineCache]{"FileCount":"0","PlanId":"689dba42-cc82-4c9c-8f54-4cddc332957d","JobId":"275f1d19-1bd8-5591-b06b-07d489ea915a","TaskInstanceId":"a2501af0-003b-5dc1-c7f3-bb7ddb1593dd","CacheResult":"Miss","ActionDurationMs":"741","ActionName":"PipelineCache.RestoreCache","ActionResult":"Success","AttemptNumber":"1","ItemCount":"0","Level":"ThirdParty","CreatedUtcNow":"2020-02-10T19:48:55.8658952Z","SentUtcNow":"2020-02-10T19:48:56.6186066Z","BaseAddress":"https://vsblobprodeus21.vsblob.visualstudio.com/A6e1e1977-ea21-4f5f-a028-c9c78aa999f3/","X_TFS_Session":"66cec078-40fc-40ff-a72e-31ecab6050b0","DeploymentEnvironment":"PRODUCTION","DeploymentEnvironmentIsProduction":"True","VSOAccount":"vsblobprodeus21","OSName":"Microsoft Windows","OSVersion":"10.0.17763","FrameworkDescription":".NET Core ","ProcessName":"Agent.PluginHost","DotNetReleaseDword":"-1","Version":"18.164.29709.0 built by: master (818ce344aa)","ExceptionCount":"0"}
2020-02-10T19:48:57.1046174Z Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session 66cec078-40fc-40ff-a72e-31ecab6050b0
2020-02-10T19:48:57.1185573Z ##[section]Finishing: Cache .npm folder
```

Post-job output:
```
2020-02-10T19:55:50.8979275Z ##[debug]Evaluating condition for step: 'Cache .npm folder'
2020-02-10T19:55:50.8979925Z ##[debug]Evaluating: AlwaysNode()
2020-02-10T19:55:50.8980028Z ##[debug]Evaluating AlwaysNode:
2020-02-10T19:55:50.8980175Z ##[debug]=> True
2020-02-10T19:55:50.8980371Z ##[debug]Result: True
2020-02-10T19:55:50.8980545Z ##[section]Starting: Cache .npm folder
2020-02-10T19:55:50.9080770Z ==============================================================================
2020-02-10T19:55:50.9080848Z Task         : Cache
2020-02-10T19:55:50.9081025Z Description  : Cache files between runs
2020-02-10T19:55:50.9081093Z Version      : 2.0.0
2020-02-10T19:55:50.9081140Z Author       : Microsoft Corporation
2020-02-10T19:55:50.9081208Z Help         : https://aka.ms/pipeline-caching-docs
2020-02-10T19:55:50.9081265Z ==============================================================================
2020-02-10T19:55:51.3220177Z Resolving key:
2020-02-10T19:55:51.3417400Z  - npm          [string]
2020-02-10T19:55:51.3426013Z  - "Windows_NT" [string]
2020-02-10T19:55:51.3449081Z Resolved to: npm|"Windows_NT"
2020-02-10T19:55:51.6276505Z ##[debug]Dedup parallelism: 192
2020-02-10T19:55:51.8432371Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session e4b8bb5c-dbf3-48b7-91ba-28b098d95689
2020-02-10T19:55:51.8761067Z Information, Getting a pipeline cache artifact with one of the following fingerprints:
2020-02-10T19:55:51.8761634Z Information, Fingerprint: `npm|"Windows_NT"`
2020-02-10T19:55:52.3843888Z Information, There is a cache miss.
2020-02-10T19:55:52.4700807Z ##[debug]Processed: ##vso[telemetry.publish area=AzurePipelinesAgent;feature=PipelineCache]{"FileCount":"0","PlanId":"689dba42-cc82-4c9c-8f54-4cddc332957d","JobId":"275f1d19-1bd8-5591-b06b-07d489ea915a","TaskInstanceId":"a2501af0-003b-5dc1-c7f3-bb7ddb1593dd","CacheResult":"Miss","ActionDurationMs":"527","ActionName":"PipelineCache.RestoreCache","ActionResult":"Success","AttemptNumber":"1","ItemCount":"0","Level":"ThirdParty","CreatedUtcNow":"2020-02-10T19:55:51.8522512Z","SentUtcNow":"2020-02-10T19:55:52.3900786Z","BaseAddress":"https://vsblobprodeus21.vsblob.visualstudio.com/A6e1e1977-ea21-4f5f-a028-c9c78aa999f3/","X_TFS_Session":"e4b8bb5c-dbf3-48b7-91ba-28b098d95689","DeploymentEnvironment":"PRODUCTION","DeploymentEnvironmentIsProduction":"True","VSOAccount":"vsblobprodeus21","OSName":"Microsoft Windows","OSVersion":"10.0.17763","FrameworkDescription":".NET Core ","ProcessName":"Agent.PluginHost","DotNetReleaseDword":"-1","Version":"18.164.29709.0 built by: master (818ce344aa)","ExceptionCount":"0"}
2020-02-10T19:55:52.4701397Z ##[debug]Starting 'tar' with arguments '-h -v -cf "77f198a4e9be488484e7d961b4f28d8a_archive.tar" -C "D:\a\1\.npm" .'...
2020-02-10T19:55:52.5692412Z tar: could not chdir to 'D:\a\1\.npm'
2020-02-10T19:55:52.5692867Z 
2020-02-10T19:55:53.3882316Z Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session e4b8bb5c-dbf3-48b7-91ba-28b098d95689
2020-02-10T19:55:53.3912060Z ##[error]Process returned non-zero exit code: 1
2020-02-10T19:55:53.3912425Z ##[debug]Processed: ##vso[task.logissue type=error;]Process returned non-zero exit code: 1
2020-02-10T19:55:53.3913113Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2020-02-10T19:55:53.4255418Z ##[debug]   at Agent.Plugins.PipelineCache.TarUtils.RunProcessAsync(AgentTaskPluginExecutionContext context, ProcessStartInfo processStartInfo, Func`3 additionalTaskToExecuteWhilstRunningProcess, Action actionOnFailure, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.TarUtils.RunProcessAsync(AgentTaskPluginExecutionContext context, ProcessStartInfo processStartInfo, Func`3 additionalTaskToExecuteWhilstRunningProcess, Action actionOnFailure, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.TarUtils.ArchiveFilesToTarAsync(AgentTaskPluginExecutionContext context, String inputPath, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.PipelineCacheServer.GetUploadPathAsync(ContentFormat contentFormat, AgentTaskPluginExecutionContext context, String path, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.PipelineCacheServer.UploadAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, String path, CancellationToken cancellationToken, ContentFormat contentFormat)
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, Func`1 restoreKeysGenerator, String path, CancellationToken token)
   at Agent.Plugins.PipelineCache.PipelineCacheTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2020-02-10T19:55:53.4387814Z ##[section]Finishing: Cache .npm folder
```

**Comment by johnterickson** [comment]
@dzielin Are you sure you set the variable to tell NPM where to create the folder? Currently you are pointing to a non-existent folder.

```
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
```

**Comment by fadnavistanmay** [comment]
Please make sure that folder exists, before the post-job cache task is run.

**Comment by hoangpham95** [comment]
@fadnavistanmay How can I create the folder? I am having similar problem with Gradle where the message is 
```
tar: could not chdir to '/Users/runner/runners/2.164.6/work/1/.gradle'
```
in post-job.

**Comment by dotnetjunky** [comment]
@hoangpham95 You can create a folder by simply using the `mkdir` script

**Comment by green-munkey** [comment]
We ran into this issue also . We were able to get past the error above after creating the $(Pipeline.Workspace)/.npm folder. Now we are having issue trying to run our lint and build step after the modules get cached . 

Errors:

'tslint' is not recognized as an internal or external command
'ng' is not recognized as an internal or external command


Ymal:

Errors:

'tslint' is not recognized as an internal or external command
'ng' is not recognized as an internal or external command


Ymal:

steps:
- script: |
   mkdir -p .npm   
  workingDirectory: '$(Pipeline.Workspace)'
  displayName: 'Validate cache folder'

- task: Cache@2
  displayName: Cache npm
  inputs:
    key: 'npm-cache-angular | $(Agent.OS) | $(Build.SourcesDirectory)/App/package-lock.json'
    cacheHitVar: CacheRestore
    path: $(Pipeline.Workspace)/.npm

- script: 'npm config set cache $(Pipeline.Workspace)/.npm --global'
  displayName: 'Set Cache Path'


- task: Npm@1
  displayName: NPM CI
  condition: ne(variables.CacheRestore, 'true')
  inputs:
    command: 'ci'
    workingDir: '$(Build.SourcesDirectory)/App'

- task: Npm@1
  displayName: NPM lint
  inputs:
    command: custom
    workingDir: $(Build.SourcesDirectory)/App
    customCommand: run lint

- task: Npm@1
  displayName: NPM build
  inputs:
    command: custom
    workingDir: $(Build.SourcesDirectory)/App
    customCommand: run build

**Comment by jirifranc** [comment]
I had the same problem with npm when using `$(Pipeline.Workspace)/.npm` directly in the task. I solved it by creating a variable `npm_config_cache: $(Pipeline.Workspace)/.npm` and referencing it instead.

**Comment by sergiu-teller** [comment]
For my case I had to look in the `$(Build.SourcesDirectory)`, which is one level deeper than `$(Pipeline.Workspace)`. That's why it wasn't finding the dependencies in my case.
