### ISSUE TITLE
ServiceFabricDeploy fails with ABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched

### ISSUE THREAD

**Issue by zendu** [microsoft/azure-pipelines-tasks#12329]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ServiceFabricDeploy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines (will provide details in separate message)

- Agent - Private: 

Agent.OS | Windows_NT
Agent.OSArchitecture | X64 
Agent.OSVersion | 10.0.14393
Agent.Version | 2.164.7

## Issue Description

Task fails with certificate mismatch error with no additional details to debug. I am able to connect to the cluster using PowerShell.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
2020-02-11T04:46:18.7957440Z ##[debug]Processed: ##vso[task.logissue type=warning]Failed to contact Failover Manager Service, Attempting to contact FMM...
2020-02-11T04:46:18.8137833Z ##[debug]System.Fabric.FabricServerAuthenticationFailedException: FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C44
2020-02-11T04:46:18.8153726Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricQueryClient10.EndGetPartitionList2(IFabricAsyncOperationContext context)
2020-02-11T04:46:18.8170457Z ##[debug]   at System.Fabric.FabricClient.QueryClient.GetPartitionListAsyncEndWrapper(IFabricAsyncOperationContext context)
2020-02-11T04:46:18.8187909Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2020-02-11T04:46:18.8203980Z ##[debug]   --- End of inner exception stack trace ---
2020-02-11T04:46:18.8286137Z ##[debug]System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
2020-02-11T04:46:18.8303861Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2020-02-11T04:46:18.8319836Z ##[debug]   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
2020-02-11T04:46:18.8335462Z ##[debug]   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase.TestClusterConnection(IClusterConnection clusterConnection, Boolean testNetwork)
2020-02-11T04:46:18.8356369Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
2020-02-11T04:46:18.8379514Z ##[debug]System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
2020-02-11T04:46:18.8396142Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2020-02-11T04:46:18.8411990Z ##[debug]   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
2020-02-11T04:46:18.8428779Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
2020-02-11T04:46:18.8783778Z ##[debug]Leaving Connect-ServiceFabricClusterFromServiceEndpoint.
2020-02-11T04:46:18.9080956Z ##[debug]SYSTEM_JOBID: '362f56d3-7574-56f5-727f-3eeb5a81d472'
2020-02-11T04:46:18.9171126Z Service fabric SDK version: 3.3.664.9590.
2020-02-11T04:46:18.9331164Z ##[debug]Processed: ##vso[telemetry.publish area=TaskHub;feature=ServiceFabricDeploy]{"OperationId":"ConnectCluster","ExceptionData":"System.Fabric.FabricServerAuthenticationFailedException;System.Runtime.InteropServices.COMException;|E:\\agent_work\\_tasks\\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\\1.8.0\\ps_modules\\ServiceFabricHelpers\\Connect-ServiceFabricClusterFromServiceEndpoint.ps1|267","JobId":"362f56d3-7574-56f5-727f-3eeb5a81d472","SDKVersion":"3.3.664.9590"}
2020-02-11T04:46:18.9331794Z ##[debug]Leaving E:\agent_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.8.0\deploy.ps1.
2020-02-11T04:46:18.9332426Z ##[debug]Caught exception from task script.
2020-02-11T04:46:18.9332696Z ##[debug]Error record:
2020-02-11T04:46:18.9851317Z ##[debug]Connect-ServiceFabricCluster : FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched
2020-02-11T04:46:18.9866501Z ##[debug]At E:\agent_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.8.0\ps_modules\ServiceFabricHelpers\Connect-ServiceFabricClusterFromServiceEndpoint.ps1:267 char:26
2020-02-11T04:46:18.9882281Z ##[debug]+ ... ectResult = Connect-ServiceFabricCluster @clusterConnectionParameters ...
2020-02-11T04:46:18.9899566Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-02-11T04:46:18.9916773Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [Connect-ServiceFabricCluster], FabricServerAuthenticationFailedEx    ception
2020-02-11T04:46:18.9931797Z ##[debug]    + FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster
2020-02-11T04:46:18.9947272Z ##[debug] 
2020-02-11T04:46:18.9970634Z ##[debug]Script stack trace:
2020-02-11T04:46:19.0014197Z ##[debug]at Connect-ServiceFabricClusterAction, E:\agent_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.8.0\ps_modules\ServiceFabricHelpers\Connect-ServiceFabricClusterFromServiceEndpoint.ps1: line 267
2020-02-11T04:46:19.0029202Z ##[debug]at Connect-ServiceFabricClusterFromServiceEndpoint, E:\agent_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.8.0\ps_modules\ServiceFabricHelpers\Connect-ServiceFabricClusterFromServiceEndpoint.ps1: line 230
2020-02-11T04:46:19.0045939Z ##[debug]at <ScriptBlock>, E:\agent_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.8.0\deploy.ps1: line 59
2020-02-11T04:46:19.0061508Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-11T04:46:19.0079175Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-02-11T04:46:19.0094665Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-02-11T04:46:19.0109010Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-11T04:46:19.0134782Z ##[debug]Exception:
2020-02-11T04:46:19.0179856Z ##[debug]System.Fabric.FabricServerAuthenticationFailedException: FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C44
2020-02-11T04:46:19.0195124Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricQueryClient10.EndGetPartitionList2(IFabricAsyncOperationContext context)
2020-02-11T04:46:19.0210433Z ##[debug]   at System.Fabric.FabricClient.QueryClient.GetPartitionListAsyncEndWrapper(IFabricAsyncOperationContext context)
2020-02-11T04:46:19.0228417Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2020-02-11T04:46:19.0247147Z ##[debug]   --- End of inner exception stack trace ---
2020-02-11T04:46:19.0264753Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2020-02-11T04:46:19.0324309Z ##[error]FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched
2020-02-11T04:46:19.0324711Z ##[debug]Processed: ##vso[task.logissue type=error]FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched
2020-02-11T04:46:19.0334687Z ##[debug]Processed: ##vso[task.complete result=Failed]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

2020-02-11T01:25:39.6636392Z Imported cluster client certificate with thumbprint '***'.
2020-02-11T01:25:40.6960309Z ##[warning]Failed to contact Naming Service. Attempting to contact Failover Manager Service...
2020-02-11T01:25:40.7059872Z ##[warning]Failed to contact Failover Manager Service, Attempting to contact FMM...
2020-02-11T01:25:40.7980114Z Service fabric SDK version: 3.3.664.9590.
2020-02-11T01:25:40.8731329Z ##[error]FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched

**Comment by anuragc617** [comment]
@zendu are you still facing this issue? You said, you are able to connect to Cluster using PowerShell. Did you try connecting to cluster using Connect-ServiceFabricCluster with same thumbprint?

**Comment by anuragc617** [comment]
@zendu  I am closing this issue for now. If you are still facing it, you can re-open this issue.
