### ISSUE TITLE
GradleV2 Task: Jacoco code coverage report broken

### ISSUE THREAD

**Issue by huaxiawang** [microsoft/azure-pipelines-tasks#12365]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines: https://humana.visualstudio.com/Digital%20Health%20and%20Analytics/_build/results?buildId=345967

- Agent - Hosted or Private: 

    - Private agent
        - OS: Linux
        - Agent version: 2.164.8

## Issue Description

Jacoco Code coverage report task fails in GradleV2
Gradle version: 5.6.3
Jacoco version: 0.8.5

### Task logs

```

Execution failed for task ':jacocoRootReport'.
> Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.3/userguide/command_line_interface.html#sec:command_line_warnings
47 actionable tasks: 42 executed, 5 up-to-date

BUILD FAILED in 2m 23s
Error: The process '/home/vsts/_work/12/s/gradlew' failed with exit code 1
    at ExecState._setResult (/home/vsts/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.163.0/node_modules/azure-pipelines-task-lib/toolrunner.js:816:25)
    at ExecState.CheckComplete (/home/vsts/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.163.0/node_modules/azure-pipelines-task-lib/toolrunner.js:799:18)
    at ChildProcess.<anonymous> (/home/vsts/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.163.0/node_modules/azure-pipelines-task-lib/toolrunner.js:721:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
##[warning]No code coverage results found to be published. This could occur if there were no tests executed or there was a build failure. Check the gradle output for details.
##[error]Error: The process '/home/vsts/_work/12/s/gradlew' failed with exit code 1

```

## Troubleshooting

This task fails as the Gradle code is wrong here:
https://github.com/microsoft/azure-pipelines-tasks/blob/ca4f0d5f9e59f52a2896e5956d4f29169d7d0c68/Tasks/Common/codecoverage-tools/codecoverageconstants.ts#L50

There is no property named `classesDir` for Gradle `SourceSetOutput`, the property available is `classesDirs`, detailed documentation can be find [here](https://docs.gradle.org/5.6.3/dsl/org.gradle.api.tasks.SourceSetOutput.html#N1A81F)

**Comment by huaxiawang** [comment]
Is there any progress?

**Comment by anatolybolshakov** [comment]
Hi @huaxiawang, there seems to be an issue with build.gradle file - 'classesDir' property was [renamed ](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSetOutput.html#org.gradle.api.tasks.SourceSetOutput:classesDirs) to 'classesDirs' for Gradle 5 and greater - could you please try to rename it?

**Comment by anatolybolshakov** [comment]
Hi @huaxiawang, I'm closing this issue due to inactivity at the moment, please feel free to reopen it if it is still actual for you
