### ISSUE TITLE
Failed because one or more lines were written to the STDERR stream

### ISSUE THREAD

**Issue by goriunov** [microsoft/azure-pipelines-tasks#12397]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure CLI Inline script   

list here (V# not needed):  v1
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

From about yesterday we are unable to deploy with azure cli script, for some reason we are getting "2020-02-20T21:47:46.4285528Z ##[error]Script failed with error: Error: The process 'D:\a\_temp\azureclitaskscript1582235228379.bat' failed because one or more lines were written to the STDERR stream" even though there is no errors in the logs (even in debug).

Command this Inline is "az storage container create --account-name *** --name ***"

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

2020-02-20T21:47:46.4285528Z ##[error]Script failed with error: Error: The process 'D:\a\_temp\azureclitaskscript1582235228379.bat' failed because one or more lines were written to the STDERR stream

**Comment by goatandsheep** [comment]
I'm also having this error.

**Comment by issacnitin** [comment]
@goriunov @goatandsheep Thanks for reporting the issue. To confirm, you are able to see the errors written to stderr in the logs correct? Could you share them as well?

**Comment by goriunov** [comment]
@issacnitin from the logs which i have (debug enabled) only 3 lines contain `error` and nothing else:

```
2020-02-23T21:49:20.9367440Z ##[error]Script failed with error: Error: The process 'D:\a\_temp\azureclitaskscript1582494522128.bat' failed because one or more lines were written to the STDERR stream
2020-02-23T21:49:20.9375412Z ##[debug]Processed: ##vso[task.issue type=error;]Script failed with error: Error: The process 'D:\a\_temp\azureclitaskscript1582494522128.bat' failed because one or more lines were written to the STDERR stream
2020-02-23T21:49:20.9376402Z ##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with error: Error: The process 'D:\a\_temp\azureclitaskscript1582494522128.bat' failed because one or more lines were written to the STDERR stream
```

**Comment by issacnitin** [comment]
@goriunov I'm able to reproduce the issue. We had a bug in the Azure CLI task, where if you have "Fail on Standard Error" checked, the script will always fail. The issue has been fixed and is in due rollout. For now, as a workaround, please uncheck the option to unblock your pipeline.
Related issue: https://github.com/microsoft/azure-pipelines-tasks/issues/12143
![githubissue](https://user-images.githubusercontent.com/4218887/75143871-e66f2a80-571b-11ea-86f9-30eaa58c5a57.PNG)

**Comment by issacnitin** [comment]
Closing the issue, as issue is already fixed and is in rollout.

**Comment by Astersss** [comment]
I got this issue today. Have you rolled out the fix already?

**Comment by antoniodlp** [comment]
This is happening to me as well

**Comment by kevinwedwards** [comment]
we too are getting this....

**Comment by kevinwedwards** [comment]
> @goriunov I'm able to reproduce the issue. We had a bug in the Azure CLI task, where if you have "Fail on Standard Error" checked, the script will always fail. The issue has been fixed and is in due rollout. For now, as a workaround, please uncheck the option to unblock your pipeline.

Should we still be doing this work around in May?

**Comment by bishal-pdMSFT** [comment]
This issue could still be happening if your script is writing to stderr.

In v2 of Azure CLI task we have made improvements to print the stderr logs. You can upgrade to v2 and see what logs are being written to stderr by your script.

**Comment by Sarah-Aly** [comment]
Azure CLI task v2 causes the pipeline to fail although everything was successfully deployed. Checking the logs written to stderr by my script showed errors that were supposed to be informational logs from running the command `az eventgrid event-subscription create`. When will this be fixed?

**Task**
```
Task: AzureCLI@2
...
scriptType: bash
failOnStandardError: true
```
**Command in script**
`      az eventgrid event-subscription create --name "es-$app_name" \
        --source-resource-id $eventgrid_id \
        --endpoint $app_id/functions/eventGrid_format --endpoint-type azurefunction`
**Logs written to stderr**
>2020-06-09T00:34:02.5424246Z ##[error]The behavior of this command has been altered by the following extension: eventgrid
2020-06-09T00:34:02.5434374Z ##[error]The behavior of this command has been altered by the following extension: eventgrid
2020-06-09T00:34:02.5436270Z ##[error]If the provided endpoint does not support subscription validation handshake, navigate to the validation URL that you receive in the subscription validation event, in order to complete the event subscription creation or update. For more details, please visit http://aka.ms/esvalidation
2020-06-09T00:34:02.5437644Z ##[error]The behavior of this command has been altered by the following extension: eventgrid
2020-06-09T00:34:02.5438645Z ##[error]The behavior of this command has been altered by the following extension: eventgrid
2020-06-09T00:34:02.5441016Z ##[error]If the provided endpoint does not support subscription validation handshake, navigate to the validation URL that you receive in the subscription validation event, in order to complete the event subscription creation or update. For more details, please visit http://aka.ms/esvalidation
2020-06-09T00:34:02.5442431Z ##[error]The behavior of this command has been altered by the following extension: eventgrid
2020-06-09T00:34:02.5443524Z ##[error]The behavior of this command has been altered by the following extension: eventgrid
2020-06-09T00:34:02.5445044Z ##[error]If the provided endpoint does not support subscription validation handshake, navigate to the validation URL that you receive in the subscription validation event, in order to complete the event subscription creation or update. For more details, please visit http://aka.ms/esvalidation
2020-06-09T00:34:02.5446488Z ##[error]The behavior of this command has been altered by the following extension: eventgrid
2020-06-09T00:34:02.5447512Z ##[error]Script has output to stderr. Failing as failOnStdErr is set to true.

**Comment by issacnitin** [comment]
@Sarah-Aly Please take it up with https://github.com/Azure/azure-cli
They'll be able to help you regarding why the informational text is written to stderr

**Comment by abedfarvardin** [comment]
I installed the Web Deploy  3.6 on agent deploy server, and my problem was solved.
![image](https://user-images.githubusercontent.com/46480511/152144820-053794d9-9120-4d31-b233-64442254a454.png)

**Comment by AbdulMehar** [comment]
Getting a similar issue right now as well. Within the pipeline, I am logging into my ACR to push a helm image, then I go on to upload an artifact. I checked my login credentials locally and within Pipeline Variables and they are working, as for the artifact, I am following the guideline that Microsoft provides. I had `failOnStderr` set to true, Disabled it and the pipeline got unblocked, and deployments went through smoothly.

**Comment by nagesheaton** [comment]
We are also getting the same error.

What is the resolution? Does anybody know?

##[error]Bash wrote one or more lines to the standard error stream.
##[error]Traceback (most recent call last):
  File "/o***t/az/lib/***ython3.11/site-***ackages/azure/cli/core/cloud.***y", line 544, in get_active_cloud_name

##[error]    return cli_ctx.config.get('cloud', 'name')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/o***t/az/lib/***ython3.11/site-***ackages/knack/config.***y", line 99, in get
    raise last_ex  # ***ylint:disable=raising-bad-ty***e
    ^^^^^^^^^^^^^
  File "/o***t/az/lib/***ython3.11/site-***ackages/knack/config.***y", line 94, in get
    return config.get(section, o***tion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/o***t/az/lib/***ython3.11/site-***ackages/knack/config.***y", line 208, in get
    return self.config_***arser.get(section, o***tion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/o***t/az/lib/***ython3.11/config***arser.***y", line 797, in get

##[error]    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/o***t/az/lib/***ython3.11/config***arser.***y", line 1168, in _unify_values

##[error]    raise NoSectionError(section) from None
