### ISSUE TITLE
Wrong test results using AppCenterTest task  on AZDO

### ISSUE THREAD

**Issue by rmarinho** [microsoft/azure-pipelines-tasks#12544]
## Required Information

Bug with AppCenterTest  task - Wrong results after test 
(devdiv)

## Environment

Azure Pipelines
Hosted  - VS2017

## Issue Description

When using the AppCenterTest task i m having weird results, we are running tests on AppCenter but the tests reported on AZDO UI show only 47 while there were 688 tests, and 622 passed. If fails some tests also and they are not reported.

Release on AZDO:

https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=615717&environmentId=3331583&_a=release-environment-logs

TestRun results:

https://devdiv.visualstudio.com/DevDiv/_TestManagement/Runs?runId=11701146&_a=runCharts

if you download the attachment  shows 688 test count 
```
<test-run id="0" start-time="2020-03-07 00:42:25Z" result="Passed" end-time="2020-03-07 03:41:13Z" testcasecount="688" total="628" passed="622" failed="1" inconclusive="5" skipped="0" asserts="242" duration="10727.061446">
```

### Task logs

[apcentertask.log](https://github.com/microsoft/azure-pipelines-tasks/files/4345405/apcentertask.log)

**Comment by john7doe** [comment]
@rmarinho if you look at the xml file that produced the report you can see that its from a completely different test run: https://appcenter.ms/orgs/xtc-Xamarin-Forms/apps/AndroidControlGallery-1/test/runs/04350789-227c-49fa-ab47-399173b5a0a5 (not https://appcenter.ms/orgs/xtc-Xamarin-Forms/apps/AndroidControlGallery-1/test/series/master/runs/4632a955-76e2-44f0-a104-3bdf7b96dab7 as found in the release output)

Why and how the publish test task found an old xml file I do not know, perhaps the VSTS team can help you with that.

I also noticed that the CLI is downloading a zip file (Downloaded artifacts to D:\a\r1\a\testresults\nunit_xml_zip.zip) perhaps it needs unzipping for the `Publish Test Results *.xml` task to pick it up?

Br,
/Simon

**Comment by rmarinho** [comment]
How can this be working fine on others stages and not this one? Seems weird. 
Downloading and opening the xml is part of the VSTS task

**Comment by rmarinho** [comment]
I did more digging and seems is wrong for example looking a the test results for this_:

https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=626272&_a=release-environment-logs&environmentId=3399719

if i follow up the TestPlan run here it shows only 47 results

https://tfsprodwus2su6.visualstudio.com/A011b8bdf-6d56-4f87-be0d-0092136884d9/DevDiv/_TestManagement/Runs?runId=12086426&_a=runCharts

![image](https://user-images.githubusercontent.com/1235097/77928983-0a84d500-72a1-11ea-8fcc-ec475203287d.png)

but if i download the xml  i do see, so it seems that the xml shows the total correctly 638 tests. is the issue on the Publish test results task?

[uitest_tests_android29_lr.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4403713/uitest_tests_android29_lr.zip)


```
test-run id="0" start-time="2020-03-27 00:50:13Z" result="Passed" end-time="2020-03-27 03:13:06Z" testcasecount="698" total="638" passed="631" failed="2" inconclusive="5" skipped="0" asserts="258" duration="8572.0832">
```

**Comment by rmarinho** [comment]
Hey @navin22 can you help me with this issue?!

Thanks

**Comment by navin22** [comment]
Hi @rmarinho - Are these tests are xunit data driven tests, recently there is a change in how we show the data driven tests. If that's the case, only one test is counted for all the data driven tests of a test method.

**Comment by rmarinho** [comment]
hI @navin22 these are Nunit, we are from a internal team on Microsoft, and this is really blocking our team. I wonder if you help s debug, also there's a lot of errors when running the task, i wonder if this is a indicator for the failure.

https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=626272&_a=release-environment-logs&environmentId=3399719

```
020-03-27T03:35:13.1509400Z ##[debug]   --version
2020-03-27T03:35:13.1515020Z [command]/usr/local/bin/dotnet --version
2020-03-27T03:35:13.4806410Z 3.1.101
2020-03-27T03:35:13.4808740Z ##[debug]PublishTestResults.OverrideExeFlow=undefined
2020-03-27T03:35:13.4810370Z ##[debug]OS type: Darwin
2020-03-27T03:35:14.5775060Z ##[debug]Failed to get FF TestManagement.Server.EnableHierarchicalResult Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.EnableHierarchicalResult)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.EnableHierarchicalResult
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:14.6528660Z ##[debug]Failed to get FF TestManagement.Server.EnableHierarchicalResultAttachment Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.EnableHierarchicalResultAttachment)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.EnableHierarchicalResultAttachment
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:14.7275150Z ##[debug]Failed to get FF WebAccess.TestManagement.LinkedStackTrace Value, exception message System.AggregateException: One or more errors occurred. (WebAccess.TestManagement.LinkedStackTrace)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: WebAccess.TestManagement.LinkedStackTrace
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:14.8089540Z ##[debug]Object of TestLogStore created.
2020-03-27T03:35:14.8823240Z ##[debug]Failed to get FF TestManagement.Server.TestLogStoreOnTCMService Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.TestLogStoreOnTCMService)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.TestLogStoreOnTCMService
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:14.9578030Z ##[debug]Failed to get FF TestManagement.Server.PublishOnTestLogStoreEnabled Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.PublishOnTestLogStoreEnabled)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.PublishOnTestLogStoreEnabled
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:15.1642620Z ##[debug]Failed to get FF TestManagement.Server.TestLogStoreTelemetryDisabledFF Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.TestLogStoreTelemetryDisabledFF)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.TestLogStoreTelemetryDisabledFF
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:15.1654920Z Result Attachments will be stored in FileService
2020-03-27T03:35:15.1655570Z ##[debug]Object of TestResultsPublisher created.
2020-03-27T03:35:15.2414670Z ##[debug]Failed to get FF TestManagement.Server.ParserAndPublisherTelemetryEnabledFF Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.ParserAndPublisherTelemetryEnabledFF)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.ParserAndPublisherTelemetryEnabledFF
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:15.2419270Z ##[debug]Object of TestLogStore created.
2020-03-27T03:35:15.3149790Z ##[debug]Failed to get FF TestManagement.Server.TestLogStoreOnTCMService Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.TestLogStoreOnTCMService)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.TestLogStoreOnTCMService
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:15.3897490Z ##[debug]Failed to get FF TestManagement.Server.PublishOnTestLogStoreEnabled Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.PublishOnTestLogStoreEnabled)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.PublishOnTestLogStoreEnabled
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:15.3902320Z Run Attachments will be stored in FileService
2020-03-27T03:35:15.4646280Z ##[debug]Failed to get FF TestManagement.Server.ParserAndPublisherTelemetryEnabledFF Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.ParserAndPublisherTelemetryEnabledFF)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.ParserAndPublisherTelemetryEnabledFF
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:15.4654400Z ##[debug]Object of TestRunPublisher created.
2020-03-27T03:35:15.4657350Z ##[debug]Object of TestLogStore created.
2020-03-27T03:35:15.5403620Z ##[debug]Failed to get FF TestManagement.Server.TestLogStoreOnTCMService Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.TestLogStoreOnTCMService)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.TestLogStoreOnTCMService
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
2020-03-27T03:35:15.6141770Z ##[debug]Failed to get FF TestManagement.Server.PublishOnTestLogStoreEnabled Value, exception message System.AggregateException: One or more errors occurred. (TestManagement.Server.PublishOnTestLogStoreEnabled)
 ---> Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.PublishOnTestLogStoreEnabled
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsCacheManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState)
```

**Comment by navin22** [comment]
@rmarinho : I think there's some issue.
Is the issue happening only in release pipeline? or you getting this error in build pipeline as well?

**Comment by cpratap994** [comment]
Hi @rmarinho ,
According to Nunit3.0 standard test result format 
(https://github.com/nunit/docs/wiki/Test-Result-XML-Format), the shared  result xml file has only 47 test-cases, which were read by nunit code-parser and published.
Can you please once check if the code actually contains the number of test cases shown in <test-run> tag.
And also can you please cross verify this file with the files which are working fine with number of <test-case> tag. 
And please share some more files which are failing like this xml file, i will look into it. And also it will be an additional help if you can share working nunit files as well for comparison.
I was just going through the xml file you shared above uitest_tests_android29_lr.xml

**Comment by rmarinho** [comment]
Hi @cpratap994 thankls for trying to help, is hard for me to get the files they are in a hosted machined, can you get them from a test report ? 

Here's a test run that runs fine

https://dev.azure.com/xamarin/public/_releaseProgress?_a=release-environment-extension&releaseId=1595&environmentId=57522

here's one that fails 

https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=1595&environmentId=57534&_a=release-environment-logs

**Comment by rmarinho** [comment]
here are two runs one that works , other than doesn’t. using the same method, appcenter task, then upload the test results

Test run API23 that runs fine
https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=646425&_a=release-environment-extension&environmentId=3523731&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab
https://appcenter.ms/orgs/xtc-Xamarin-Forms/apps/AndroidControlGallery-1/test/series/release-4.5.0-sr5/runs/36df09ad-af5c-4a55-9449-ac964ee968ce

<img width="1226" alt="vs" src="https://user-images.githubusercontent.com/1235097/80383924-224d7a00-889c-11ea-924a-d563a4af80e4.png">

<img width="1389" alt="appcenter" src="https://user-images.githubusercontent.com/1235097/80383973-32655980-889c-11ea-8045-bb0956899ab1.png">


Test run API27 that fails to report correct test number
https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=646425&environmentId=3523733&_a=release-environment-extension&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab
https://appcenter.ms/orgs/xtc-Xamarin-Forms/apps/AndroidControlGallery-1/test/series/release-4.5.0-sr5/runs/5a5e07af-2da5-43c4-8218-a738c5ff0914

<img width="1034" alt="vsfail" src="https://user-images.githubusercontent.com/1235097/80384077-545edc00-889c-11ea-993e-9f587af3cd59.png">
<img width="1389" alt="appcenter" src="https://user-images.githubusercontent.com/1235097/80384083-5759cc80-889c-11ea-93e6-dcbad41ad152.png">

**Comment by cpratap994** [comment]
@rmarinho 
I just downloaded  *.trx files from both runs: 
**Issue Run:-** 
https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=646425&environmentId=3523733&_a=release-environment-extension&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab
![failed](https://user-images.githubusercontent.com/6858862/81171738-8c5fd080-8fba-11ea-9f17-acd7e46b3197.PNG)

**working Run :-**
https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=646425&environmentId=3523731&_a=release-environment-extension&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab
![passed](https://user-images.githubusercontent.com/6858862/81171840-c03af600-8fba-11ea-8439-c016a6df8c28.PNG)

PublishTestResult task reads *.trx file only and follow 
(https://github.com/nunit/docs/wiki/Test-Result-XML-Format ) this formatting schema for parsing and publish it and show it on the screen(pie charts)
And if you see in above .trx files snips i have attached above says that first file has total _<test-case>_ tags 48(96/2) and the other one has 730(1460/2), so PublishTestResult is reading files (*.trx) correctly.
Can you please check **Xamarin UITest** Task , this is the task which generates *.trx file to be processed by PublishTestResult

**Comment by rmarinho** [comment]
Hi @cpratap994  i thanks, i keep having this issue and i found more information about this. 

I have printed the NUnit .xml file as part of the task before passing it to the publish results task.
looking at this test run : 
https://dev.azure.com/xamarin/public/_releaseProgress?_a=release-environment-extension&releaseId=1747&environmentId=63950&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab

![image](https://user-images.githubusercontent.com/1235097/83624821-08820f80-a58b-11ea-8013-711373fd9ad0.png)

It shows that the test name is something like `_IsVisible_apple_iphone_xs-12_1_4`

But the xml file shows something like this  `<test-case id="0-2066" name="_IsVisible_apple_iphone_xs_max_13_5"`

https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=1747&environmentId=63950&_a=release-environment-logs

The correct should be *iphone_xs_max_13_5*. Why would it report a different name. 

At the same time if i look at the failure reported it seems to be correct for example the failed test here:

https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=1747&environmentId=63972&_a=release-environment-extension&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab

The test name shows `MemoryLeakB42329_google_pixel_2-8_1_0`  but if i see the nunit.xml file the failed test name is `MemoryLeakB42329_lg_nexus_5_4_4_4"`

```
  <test-case id="0-1324" name="MemoryLeakB42329_lg_nexus_5_4_4_4" fullname="Xamarin.Forms.Controls.Issues.Bugzilla42329.MemoryLeakB42329" methodname="MemoryLeakB42329" classname="Xamarin.Forms.Controls.Issues.Bugzilla42329" runstate="Runnable" seed="468137713" result="Failed" label="Error" start-time="2020-06-01 19:38:02Z" end-time="2020-06-01 19:39:16Z" duration="73.933608" asserts="0">
2020-06-01T20:31:48.3668260Z                 <failure>
2020-06-01T20:31:48.3668770Z                   <message><![CDATA[System.Exception : Error while performing WaitForElement(Marked("Page1"), "Timed out waiting for element...", null, null, null)
2020-06-01T20:31:48.3669800Z   ----> System.TimeoutException : Timed out waiting for element...]]></message>
2020-06-01T20:31:48.3671050Z                   <stack-trace><![CDATA[  at Xamarin.UITest.Utils.ErrorReporting.With[T] (System.Func`1[TResult] func, System.Object[] args, System.String memberName) [0x0005b] in <1e83ea66795243fe9314c23f4eef1081>:0 
2020-06-01T20:31:48.3672260Z   at Xamarin.UITest.Android.AndroidApp.WaitForElement (System.Func`2[T,TResult] query, System.String timeoutMessage, System.Nullable`1[T] timeout, System.Nullable`1[T] retryFrequency, System.Nullable`1[T] postTimeout) [0x00032] in <1e83ea66795243fe9314c23f4eef1081>:0 
2020-06-01T20:31:48.3673570Z   at Xamarin.UITest.Android.AndroidApp.WaitForElement (System.String marked, System.String timeoutMessage, System.Nullable`1[T] timeout, System.Nullable`1[T] retryFrequency, System.Nullable`1[T] postTimeout) [0x0000d] in <1e83ea66795243fe9314c23f4eef1081>:0 
2020-06-01T20:31:48.3674870Z   at Xamarin.Forms.Controls.ScreenshotConditionalApp.WaitForElement (System.String marked, System.String timeoutMessage, System.Nullable`1[T] timeout, System.Nullable`1[T] retryFrequency, System.Nullable`1[T] postTimeout) [0x00001] in <f8e72e010dd44711adeade70d85a29e4>:0 
2020-06-01T20:31:48.3675870Z   at Xamarin.Forms.Controls.Issues.Bugzilla42329.MemoryLeakB42329 () [0x00049] in <f8e72e010dd44711adeade70d85a29e4>:0 
2020-06-01T20:31:48.3676970Z   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
2020-06-01T20:31:48.3677960Z   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <48b95f3df5804531818f80e28ec60191>:0 
2020-06-01T20:31:48.3678990Z --TimeoutException
2020-06-01T20:31:48.3679760Z   at Xamarin.UITest.Shared.WaitForHelper.WaitForAny[T] (System.Func`1[TResult] query, System.String timeoutMessage, System.Nullable`1[T] timeout, System.Nullable`1[T] retryFrequency, System.Nullable`1[T] postTimeout) [0x0001d] in <1e83ea66795243fe9314c23f4eef1081>:0 
2020-06-01T20:31:48.3680800Z   at Xamarin.UITest.Android.AndroidApp+<>c__DisplayClass80_0.<WaitForElement>b__0 () [0x00054] in <1e83ea66795243fe9314c23f4eef1081>:0 
2020-06-01T20:31:48.3682080Z   at Xamarin.UITest.Utils.ErrorReporting.With[T] (System.Func`1[TResult] func, System.Object[] args, System.String memberName) [0x0000e] in <1e83ea66795243fe9314c23f4eef1081>:0 ]]></stack-trace>
2020-06-01T20:31:48.3682730Z                 </failure>
```

**Comment by rmarinho** [comment]
Btw i tried  version 1 and version 2 of the task and have the same issue.

**Comment by rmarinho** [comment]
I wonder if this is because the *test-case id* i can have the same test id but from different runs on different devices.
