### ISSUE TITLE
Index Sources & Publish Symbols task fails on TLS 1.2 only communication

### ISSUE THREAD

**Issue by shayl** [microsoft/azure-pipelines-tasks#12611]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Index Sources & Publish Symbols (PublishSymbols)

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines   
    - Account name: microsoft
    - team project name: WDATP
    - build definition name/build number: 35451

- Agent - Private
    
    - OS: windows server 2016 Datacenter
    - agent version: 2.165.0

## Issue Description
Since we updated our private build agents servers to work only with TLS 1.2 (and disable older TLS or SSL) this task is failing.
Error:
```
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive.
##[debug]At C:\Agent\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.0.16\PublishSymbols.ps1:20 char:15
##[debug]+ ...    $result = Invoke-WebRequest $serviceDefinitionUri -UseBasicParsing
##[debug]+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt    pWebRequest) [Invoke-WebRequest], WebException
##[debug]    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe    ll.Commands.InvokeWebRequestCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at Get-SymbolServiceUri, C:\Agent\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.0.16\PublishSymbols.ps1: line 20
##[debug]at <ScriptBlock>, C:\Agent\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.0.16\PublishSymbols.ps1: line 202
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
##[debug]   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
##[debug]   at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
##[debug]   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
##[debug]   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
##[debug]   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
##[debug]   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
##[debug]   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
##[debug]   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
##[debug]   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
##[debug]   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
##[debug]   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
##[debug]   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
##[debug]   at System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
##[debug]   at System.Net.ConnectStream.WriteHeaders(Boolean async)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
##[error]The underlying connection was closed: An unexpected error occurred on a receive.
##[debug]Processed: ##vso[task.logissue type=error]The underlying connection was closed: An unexpected error occurred on a receive.
##[debug]Processed: ##vso[task.complete result=Failed]
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by shayl** [comment]
Hi, any workaround for this?

**Comment by shayl** [comment]
Still waiting. Any update on this?

**Comment by shayl** [comment]
still waiting for a response...

**Comment by nuzolx** [comment]
I have the same issue.

**Comment by nuzolx** [comment]
see: https://github.com/microsoft/azure-pipelines-tasks/issues/15139
