### ISSUE TITLE
Bug: Azure CLI task does not censor passwords and prints them as cleartext into output console window

### ISSUE THREAD

**Issue by Tobnac** [microsoft/azure-pipelines-tasks#12689]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: AzureCLIV1

## Environment

(Shouldn't matter for this kind of issue)
Release Pipeline, Hosted VS2017 agent

## Issue Description

In my library, I have a variable group. This group contains a variable that is marked as secret. I can not read this value in the UI.

My release pipeline linked this variable group. On the variables-tab, the variable value is still censored with stars.

The pipeline itself has an Azure CLI Task.
Task Version 1
Azure subscription selected via service connection.
Inline script -> contains several commands, a.o. one that uses my secret pipeline variable, that I refer to using $(variableName).

When I run this pipeline, it prints the script commands into the output window. While doing so, it does not censor or hide the secret password at all. It is clearly visible in cleartext and able to be copied without problems.

Other tasks, like the CmdLineV2 command line task, which is very similar, does censor these secrets with three stars, so that the value is never displayed anywhere.

**Comment by vinodkumar3** [comment]
@Tobnac 
This is really a big concern and we are taking it up on priority. However, I tried many commands and variables and its working fine for me.
It will really be helpful if you can share the precise command and the variable name which is causing the issue.

**Comment by Tobnac** [comment]
@vinodkumar3 
Sure. I also added the pipeline output. Maybe the command printing is handled differently here because the command fails with an error?

Variable group name: BackendSslCertificate
Variable name: SslCertPassword
Its a release pipeline, uses multiple artifacts and stages.
I didnt change/set/add any output or environmental variables, but I did enable the "continue on error" checkbox.
Password (same types of characters, but obviously changed): a=b^(C[3]) 
Inline script (company and product name strings replaced):

```
echo "1/4: Upload SSL-Cert to tenantManagement (expecting conflict error when already uploaded)"
az webapp config ssl upload --certificate-file "$(secFile.secureFilePath)" --certificate-password "$(SslCertPassword)" --name company-name-$(EnvironmentToken)-tenant-management --resource-group company-name-$(EnvironmentToken) --subscription "Service - Company Name"
```

Pipeline output:
```
2020-04-16T01:21:28.9912686Z ##[section]Starting: Upload SSl-cert
2020-04-16T01:21:29.0036079Z ==============================================================================
2020-04-16T01:21:29.0036463Z Task         : Azure CLI
2020-04-16T01:21:29.0036973Z Description  : Run Azure CLI commands against an Azure subscription in a Shell script when running on Linux agent or Batch script when running on Windows agent.
2020-04-16T01:21:29.0037465Z Version      : 1.163.0
2020-04-16T01:21:29.0037845Z Author       : Microsoft Corporation
2020-04-16T01:21:29.0038297Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2020-04-16T01:21:29.0038650Z ==============================================================================
2020-04-16T01:21:29.2457681Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2020-04-16T01:21:31.6083134Z WARNING: You have 2 updates available. Consider updating your CLI installation. Instructions can be found at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
2020-04-16T01:21:31.6084028Z azure-cli                          2.2.0 *
2020-04-16T01:21:31.6084849Z 
2020-04-16T01:21:31.6086529Z command-modules-nspkg              2.0.3
2020-04-16T01:21:31.6087298Z core                               2.2.0 *
2020-04-16T01:21:31.6087891Z nspkg                              3.0.4
2020-04-16T01:21:31.6088478Z telemetry                          1.0.4
2020-04-16T01:21:31.6091690Z 
2020-04-16T01:21:31.6092272Z Extensions:
2020-04-16T01:21:31.6092847Z azure-devops                      0.17.0
2020-04-16T01:21:31.6093786Z 
2020-04-16T01:21:31.6094443Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2020-04-16T01:21:31.6095229Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2020-04-16T01:21:31.6096363Z 
2020-04-16T01:21:31.6097077Z Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
2020-04-16T01:21:31.6097716Z 
2020-04-16T01:21:31.6098296Z Legal docs and information: aka.ms/AzureCliLegal
2020-04-16T01:21:31.6098816Z 
2020-04-16T01:21:31.6099245Z 
2020-04-16T01:21:31.6099651Z 
2020-04-16T01:21:31.6100051Z 
2020-04-16T01:21:31.6100682Z Please let us know how we are doing: https://aka.ms/clihats
2020-04-16T01:21:31.6126276Z Setting AZURE_CONFIG_DIR env variable to: D:\a\_temp\.azclitask
2020-04-16T01:21:31.6130101Z Setting active cloud to: AzureCloud
2020-04-16T01:21:31.6245165Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
2020-04-16T01:21:32.8648745Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** -p *** --tenant ***"
2020-04-16T01:21:34.4683662Z [
2020-04-16T01:21:34.4684254Z   {
2020-04-16T01:21:34.4684720Z     "cloudName": "AzureCloud",
2020-04-16T01:21:34.4685378Z     "homeTenantId": "***",
2020-04-16T01:21:34.4685903Z     "id": "123456789",
2020-04-16T01:21:34.4686441Z     "isDefault": true,
2020-04-16T01:21:34.4687114Z     "managedByTenants": [],
2020-04-16T01:21:34.4687696Z     "name": "Service - Company Name",
2020-04-16T01:21:34.4688270Z     "state": "Enabled",
2020-04-16T01:21:34.4688852Z     "tenantId": "***",
2020-04-16T01:21:34.4689374Z     "user": {
2020-04-16T01:21:34.4689956Z       "name": "***",
2020-04-16T01:21:34.4690515Z       "type": "servicePrincipal"
2020-04-16T01:21:34.4691002Z     }
2020-04-16T01:21:34.4691444Z   }
2020-04-16T01:21:34.4691886Z ]
2020-04-16T01:21:34.4853337Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription 123456789"
2020-04-16T01:21:35.7186146Z [command]C:\windows\system32\cmd.exe /D /S /C "D:\a\_temp\azureclitaskscript1587000089216.bat"
2020-04-16T01:21:35.7313711Z 
2020-04-16T01:21:35.7314539Z D:\a\r1\a>echo "1/4: Upload SSL-Cert to tenantManagement (expecting conflict error when already uploaded)" 
2020-04-16T01:21:35.7316780Z "1/4: Upload SSL-Cert to tenantManagement (expecting conflict error when already uploaded)"
2020-04-16T01:21:35.7317028Z 
2020-04-16T01:21:35.7317831Z D:\a\r1\a>az webapp config ssl upload --certificate-file "D:\a\_temp\companynameSslCertWildcard.pfx" --certificate-password "a=b^(C[3])" --name company-name-preview-tenant-management --resource-group company-name-preview --subscription "Service - Company name" 
2020-04-16T01:21:37.9456536Z ERROR: The command failed with an unexpected error. Here is the traceback:
2020-04-16T01:21:37.9457428Z 
2020-04-16T01:21:37.9465713Z ERROR: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
2020-04-16T01:21:37.9466316Z Traceback (most recent call last):
2020-04-16T01:21:37.9466876Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\knack\knack\cli.py", line 206, in invoke
2020-04-16T01:21:37.9467658Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
2020-04-16T01:21:37.9468525Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
2020-04-16T01:21:37.9469386Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
2020-04-16T01:21:37.9470162Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\six\six.py", line 703, in reraise
2020-04-16T01:21:37.9470916Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
2020-04-16T01:21:37.9471726Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
2020-04-16T01:21:37.9472523Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
2020-04-16T01:21:37.9473393Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2078, in upload_ssl_cert
2020-04-16T01:21:37.9474265Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2092, in _get_cert
2020-04-16T01:21:37.9475264Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\pyOpenSSL\OpenSSL\crypto.py", line 2996, in load_pkcs12
2020-04-16T01:21:37.9476059Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\pyOpenSSL\OpenSSL\_util.py", line 54, in exception_from_error_queue
2020-04-16T01:21:37.9476745Z OpenSSL.crypto.Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
2020-04-16T01:21:37.9477234Z WARNING: 
2020-04-16T01:21:37.9477629Z To open an issue, please run: 'az feedback'
2020-04-16T01:21:38.8580668Z ##[error]Script failed with error: Error: The process 'D:\a\_temp\azureclitaskscript1587000089216.bat' failed with exit code 1
2020-04-16T01:21:38.8597823Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
2020-04-16T01:21:39.3544445Z ##[section]Finishing: Upload SSl-cert
```

I don't know why the command fails and was not able to fix it yet, but that is a separate problem.

**Comment by issacnitin** [comment]
@Tobnac The only case I could repro this scenario is when the variables are locked in the variable group but redefined and open in pipeline variables. Can you confirm that's not the case with you?

**Comment by Tobnac** [comment]
> @Tobnac The only case I could repro this scenario is when the variables are locked in the variable group but redefined and open in pipeline variables. Can you confirm that's not the case with you?

Can confirm. The only one single place where this variable is defined is in one said variable group and not in any pipeline variables, output variables, etc.

**Comment by issacnitin** [comment]
@Tobnac I was able to repro the issue, seems like this is an issue with the specific password you're using 
```
a=b^(C[3])
```
As a workaround, please change the password to alphanumeric while we fix the issue. Thanks a lot for raising this issue!

**Comment by issacnitin** [comment]
This is happening because ```^``` is escape character in command prompt. You can either use ```"$(SslCertPassword)"``` or add an extra ```^``` before ```^```

**Comment by issacnitin** [comment]
@Tobnac Were you able to try out using a different password?

**Comment by Tobnac** [comment]
@issacnitin Yes, it works perfectly as long as I don't use the `^` character, as you said. Thanks for the update.

**Comment by issacnitin** [comment]
Awesome! Thanks @Tobnac . We'll be closing the issue for now. Feel free to re-open for any concerns regarding this
