### ISSUE TITLE
Docker-compose task UnicodeEncodeError

### ISSUE THREAD

**Issue by GrumpyMeow** [microsoft/azure-pipelines-tasks#12711]
I've put a Docker-compose-task in one of my release-pipeline. This will trigger the following error:
```UnicodeEncodeError: 'charmap' codec can't encode character '\u200e' in position 2905: character maps to <undefined>```
I run the Docker-compose-task against a remote Windows 2019 (ltsc2019) Azure hosted machine. 
Apparently before doing the actual Docker-compose command i instructed ("up"), the task does a Docker-compose config. This part of the task triggers the unicode error.

Related issues:
* https://github.com/docker/compose/issues/5826

Running on the docker-compose/agent machine: chcp
Returns: Active code page: 437

I see the following solution here:

> In the 1809 build of Windows 10 I've managed to permanently solve this by going to the system's Language settings, selecting Administrative language settings, clicking Change system locale... and checking the Beta: Use Unicode UTF-8 for worldwide language support box and then restarting my pc.
https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8

Hereunder the debug trace:
```
##[debug]mkdir 'C:\agent\_work\_temp\DockerConfig_1587128814917\trust'
##[debug]mkdir 'C:\agent\_work\_temp\DockerConfig_1587128814917\trust\private'
##[debug]Writing Docker config to temp file. File path: C:\agent\_work\_temp\DockerConfig_1587128814917\config.json, Docker config: {"auths": { "xxxxxx.azurecr.io": {"auth": "***", "email": "xxx@xxx" } }, "HttpHeaders":{"X-Meta-Source-Client":"VSTS"} }
##[debug]Synced the file content to the disk. The content is {"auths": { "xxxx.azurecr.io": {"auth": "***", "email": "xxx@xxx" } }, "HttpHeaders":{"X-Meta-Source-Client":"VSTS"} }.
##[debug]dockerComposeFileArgs=null
#[debug]which 'C:\ProgramData\chocolatey\bin\docker-compose.exe'
##[debug]found: 'C:\ProgramData\chocolatey\bin\docker-compose.exe'
##[debug]which 'C:\ProgramData\chocolatey\bin\docker-compose.exe'
##[debug]found: 'C:\ProgramData\chocolatey\bin\docker-compose.exe'
##[debug]C:\ProgramData\chocolatey\bin\docker-compose.exe arg: ["-f","C:\\agent\\_work\\r1\\a\\Docker\\project\\Docker-compose.yaml"]
##[debug]C:\ProgramData\chocolatey\bin\docker-compose.exe arg: ["-p","project"]
##[debug]C:\ProgramData\chocolatey\bin\docker-compose.exe arg: config
##[debug]exec tool: C:\ProgramData\chocolatey\bin\docker-compose.exe
##[debug]arguments:
##[debug]   -f
##[debug]   C:\agent\_work\r1\a\Docker\project\Docker-compose.yaml
##[debug]   -p
##[debug]   project
##[debug]   config
##[error][9176] Failed to execute script docker-compose
##[debug]Processed: ##vso[task.issue type=error;][9176] Failed to execute script docker-compose
##[error]Traceback (most recent call last):
##[debug]Processed: ##vso[task.issue type=error;]Traceback (most recent call last):
##[error]  File "docker-compose", line 6, in <module>
##[debug]Processed: ##vso[task.issue type=error;]  File "docker-compose", line 6, in <module>
##[error]  File "compose\cli\main.py", line 72, in main
##[debug]Processed: ##vso[task.issue type=error;]  File "compose\cli\main.py", line 72, in main
##[error]  File "compose\cli\main.py", line 122, in perform_command
##[debug]Processed: ##vso[task.issue type=error;]  File "compose\cli\main.py", line 122, in perform_command
##[error]  File "compose\cli\main.py", line 353, in config
##[debug]Processed: ##vso[task.issue type=error;]  File "compose\cli\main.py", line 353, in config
##[error]  File "c:\jenkins\workspace\dsg_compose_1.25.5\venv\lib\encodings\cp1252.py", line 19, in encode
##[debug]Processed: ##vso[task.issue type=error;]  File "c:\jenkins\workspace\dsg_compose_1.25.5\venv\lib\encodings\cp1252.py", line 19, in encode
##[error]UnicodeEncodeError: 'charmap' codec can't encode character '\u200e' in position 2905: character maps to <undefined>
##[debug]Processed: ##vso[task.issue type=error;]UnicodeEncodeError: 'charmap' codec can't encode character '\u200e' in position 2905: character maps to <undefined>
##[debug]Exit code 4294967295 received from tool 'C:\ProgramData\chocolatey\bin\docker-compose.exe'
##[debug]STDIO streams have closed for tool 'C:\ProgramData\chocolatey\bin\docker-compose.exe'
##[debug]task result: Failed
##[error]The process 'C:\ProgramData\chocolatey\bin\docker-compose.exe' failed with exit code 4294967295
##[debug]Processed: ##vso[task.issue type=error;]The process 'C:\ProgramData\chocolatey\bin\docker-compose.exe' failed with exit code 4294967295
##[debug]Processed: ##vso[task.complete result=Failed;]The process 'C:\ProgramData\chocolatey\bin\docker-compose.exe' failed with exit code 4294967295
```

**Comment by sonayak** [comment]
@GrumpyMeow The character that is causing problem is \u200e. This is actually a control character https://en.wikipedia.org/wiki/Left-to-right_mark
https://codepoints.net/U+200E
Do you need this in the docker-compose file or is it introduced by mistake?

**Comment by sonayak** [comment]
@GrumpyMeow Can you respond to the above queries?

**Comment by GrumpyMeow** [comment]
Hi,
I came across this issue a while ago. I’m pretty sure that I didn’t have that control character in my commands. I think I resolved the issue with selecting the “system language settings”.

**Comment by sonayak** [comment]
Thanks @GrumpyMeow  for the update. The specified related issue #5826 with docker compose has already been fixed by the docker compose team. I am closing the issue.
