### ISSUE TITLE
Publish pipeline artifact - failed with error that the artifact already exists

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azure-pipelines-tasks#12718]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?** 
*Type*: Bug

**Enter Task Name**: PublishPipelineArtifact@0  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  61677

## Issue Description
The task failed with error saying the artifact already exists, but I am pretty sure the name is unique and only only used once.

on rerun, the task passed and I don't remember seeing this error before. 

### Task logs

2020-04-17T08:18:09.4008730Z ##[section]Starting: Publish SelfSigned
2020-04-17T08:18:09.4030790Z ==============================================================================
2020-04-17T08:18:09.4031650Z Task         : Publish pipeline artifact
2020-04-17T08:18:09.4032410Z Description  : Publish a local directory or file as a named artifact for the current pipeline
2020-04-17T08:18:09.4033120Z Version      : 0.140.0
2020-04-17T08:18:09.4033680Z Author       : Microsoft Corporation
2020-04-17T08:18:09.4034430Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
2020-04-17T08:18:09.4035240Z ==============================================================================
2020-04-17T08:18:09.8812340Z Uploading pipeline artifact from /Users/runner/runners/2.165.2/work/1/s/.build/darwin/archive/azuredatastudio-darwin.zip for build #61677
2020-04-17T08:18:10.9594780Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 50718340-f273-47a9-a5d0-514f56f3a706
2020-04-17T08:18:10.9917040Z Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session 50718340-f273-47a9-a5d0-514f56f3a706
2020-04-17T08:18:12.8741720Z Information, 1 files processed.
2020-04-17T08:18:12.8753470Z Information, Processed 1 files from /Users/runner/runners/2.165.2/work/1/s/.build/darwin/archive successfully.
2020-04-17T08:18:16.1239420Z Information, Uploading 1 files from directory /Users/runner/runners/2.165.2/work/1/s/.build/darwin/archive to Drop service.
2020-04-17T08:18:16.1245490Z Information, Uploaded 0 out of 140,692,601 bytes
2020-04-17T08:18:16.1286980Z Information, Batcher OutputCount: 0  Uploader queue: 0  Active Upload sessions: 1.
2020-04-17T08:18:21.1337940Z Information, Uploading 1 files from directory /Users/runner/runners/2.165.2/work/1/s/.build/darwin/archive to Drop service.
2020-04-17T08:18:21.1339130Z Information, Uploaded 0 out of 140,692,601 bytes
2020-04-17T08:18:21.1339900Z Information, Batcher OutputCount: 0  Uploader queue: 0  Active Upload sessions: 1.
2020-04-17T08:18:26.2162830Z Information, Uploading 1 files from directory /Users/runner/runners/2.165.2/work/1/s/.build/darwin/archive to Drop service.
2020-04-17T08:18:26.2163950Z Information, Uploaded 20,115,585 out of 140,692,601 bytes
2020-04-17T08:18:26.2164730Z Information, Batcher OutputCount: 0  Uploader queue: 0  Active Upload sessions: 1.
2020-04-17T08:18:28.3882160Z Information, Uploaded 40,972,441 out of 140,692,800 bytes
2020-04-17T08:18:28.3883050Z Information, Content upload is done!
2020-04-17T08:18:28.3892770Z Information, 
2020-04-17T08:18:28.3893360Z Content upload statistics:
2020-04-17T08:18:28.3893860Z Total Content: 281.4 MB
2020-04-17T08:18:28.3894310Z Physical Content Uploaded: 40.4 MB
2020-04-17T08:18:28.3894820Z Logical Content Uploaded: 41.0 MB
2020-04-17T08:18:28.3895360Z Compression Saved: 0.6 MB
2020-04-17T08:18:28.3895810Z Deduplication Saved: 240.4 MB
2020-04-17T08:18:28.3896260Z Number of Chunks Uploaded: 511
2020-04-17T08:18:28.3896630Z 
2020-04-17T08:18:29.8842300Z Warning, [] Try 1/3, non-retryable exception caught. Throwing. Details:
2020-04-17T08:18:29.8844300Z No LastRequestResponse on exception ArtifactExistsException: Artifact darwin-selfsigned already exists for build 61677. Microsoft.TeamFoundation.Build.WebApi.ArtifactExistsException: Artifact darwin-selfsigned already exists for build 61677.
2020-04-17T08:18:29.8846120Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
2020-04-17T08:18:29.8847270Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
2020-04-17T08:18:29.8848460Z    at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
2020-04-17T08:18:29.8849930Z    at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
2020-04-17T08:18:29.8852060Z    at Agent.Plugins.PipelineArtifact.BuildServer.AssociateArtifactAsync(Guid projectId, Int32 pipelineId, String name, String jobId, String type, String data, Dictionary`2 propertiesDictionary, CancellationToken cancellationToken)
2020-04-17T08:18:29.8853190Z    at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.<>c__DisplayClass2_1.<<UploadAsync>b__2>d.MoveNext()
2020-04-17T08:18:29.8854440Z --- End of stack trace from previous location where exception was thrown ---
2020-04-17T08:18:29.8855320Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2020-04-17T08:18:29.8860140Z Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 50718340-f273-47a9-a5d0-514f56f3a706
2020-04-17T08:18:29.8905370Z ##[error]Artifact darwin-selfsigned already exists for build 61677.
2020-04-17T08:18:29.9055000Z ##[section]Finishing: Publish SelfSigned

**Comment by alanrenmsft** [comment]
turns out someone from our team did rerun the job.

**Comment by BoazWarshawsky** [comment]
I am also having that issue, is there any solution for that?
@alanrenmsft

**Comment by alanrenmsft** [comment]
@BoazWarshawsky I don't see a task available to delete pipeline artifact, I guess you shouldn't be rerunning the failed jobs to avoid this problem

**Comment by bnbarak** [comment]
We had the same issue when one pushes twice in small time interval. So the PR triggered the pipeline twice in the same 60 seconds, resulting in the same fail. Is there an option to turn off batch per PR?

**Comment by rwerlang** [comment]
I'm having the same issue.
It makes no sense to have a task that can only run once if the pipeline can run often because of retries or a failure after the artifact was published.
This is a bug and should be fixed. It should allow the publishing of the artifact again in case the build has failed.
So now I have a failing build and can't use the retry feature because of this. Makes no sense.

**Comment by karpikpl** [comment]
was there ever a solution for this, to override existing artifact?

**Comment by Siebjee** [comment]
I do not like commenting on old "closed" issues. But to those who will benefit from this work-around:

In this case it'll use the JobAttempt as a prefix.. I do not like it but it works.
```
      - publish: $(System.DefaultWorkingDirectory)/my-artifact
        artifact: $(System.JobAttempt)-my-artifact
        condition: always()
```

**Comment by Hjaf** [comment]
Assuming that artifacts are the product of a successful run up until the step where the artifact is published, what about checking and using this artifact, then continue from this step in the event a re-run is required?  
I have to re-run the deployment because a connection was not shared with the SPN, so if I'm bound to using ALM Accelerator I would basically need to commit some irrelevant changes and build the entire solution again just for it to do the deployment 🤔

**Comment by Mo-way** [comment]
I agree this is a bug. 
We had this issue when trying to re-run failed jobs. To fix this, we made the publish task `dependOn` the tasks before:
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops

 This way, it would only publish once we were happy with the artifacts that would be published. Cant protect against failures later on in the pipeline. Though, if your publish task depends on tasks run later on, it might make sense to let it actually `dependsOn` them.

**Comment by klodoma** [comment]
+1
Why is this issue "closed". Same issue here.

**Comment by Real-Iron-Man** [comment]
Experienced the same and the run should see it as different


Below worked for me (replace your details  : you're "crazy stack", subscriptions , DEV app name , PROD app name, both env names of pipeline)  : 


**This is DEV   >>>   Approval Step   >>>   PROD**

*confirm it by looking at both "Download Artifact" steps

![Image](https://github.com/user-attachments/assets/321b0c0b-42b8-4635-b663-8a842f991748)




`
# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscriptionPROD: '########-####-####-####-############'
  azureSubscriptionDEV: '########-####-####-####-############'

  # Web app name
  webAppNamePROD: 'prod-app'
  webAppNameDEV: 'dev-app'

  # Environment name
  environmentNamePROD: 'prod-env'
  environmentNameDEV: 'dev-env'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build_DEV
  displayName: Build DEV stage
  jobs:
  - job: Build
    displayName: Build DEV stage
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy_DEV
  displayName: Deploy code to DEV app
  dependsOn: Build_DEV
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentNameDEV)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: dev-app'
            inputs:
              azureSubscription: $(azureSubscriptionDEV)
              appType: webAppLinux
              appName: $(webAppNameDEV)
              runtimeStack: 'NODE|20LTS'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start'

- stage: Review_DEV_App
  displayName: Review DEV deployed app dev-app
  dependsOn: Deploy_DEV
  condition: succeeded()
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation  
    pool: server    
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
         notifyUsers: |
            bame@email.com
         instructions: 'Please validate the DEV build before release to PROD'

- stage: Build_PROD
  displayName: Build PROD stage
  dependsOn: Review_DEV_App
  condition: succeeded()
  jobs:
  - job: Build
    displayName: Build PROD stage
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'

- stage: Deploy_PROD
  displayName: Deploy code to PROD app
  dependsOn: Build_PROD
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentNamePROD)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: prod-app'
            inputs:
              azureSubscription: $(azureSubscriptionPROD)
              appType: webAppLinux
              appName: $(webAppNamePROD)
              runtimeStack: 'NODE|20LTS'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start'
`

**Comment by karpikpl** [comment]
I think this may work for single pipeline but it's going to be harder to manage when one pipeline takes artifacts from another. Having a dynamic name with `$(Build.BuildId).zip` might be harder to deal with.

It's a cool workaround though, but not the ability to re-upload an artifact if already exists

**Comment by Real-Iron-Man** [comment]
@karpikpl 

Good point + you're right

**Assumptions** with my solution : 
- single pipeline (DEV to PROD stages only)
- Use build of DEV as inputs to PROD build but only on success

It would be interesting to reference like you said; I'm not an expert in this.

**Comment by KUGA2** [comment]
You can to move all upload steps at the end, so you _possibly failing_ steps (the cause for rerun) does not interfere. But I still think a more general solution would be nicer.

Like, if it is a rerun, allow overwrites automatically.
