### ISSUE TITLE
Deploy Service Fabric Application to local windows cluster fails

### ISSUE THREAD

**Issue by KnutNiehaus** [microsoft/azure-pipelines-tasks#12788]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Deploy Service Fabric Application

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/nordex-tfs/Nordex%20Interface%20IoT%20(IoT-NIF)/_release?_a=releases&view=mine&definitionId=2

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016  - Agent Version 2.166.4

## Issue Description

After setting up a new release pipeline and to a new created service connection the connection to the on premise service fabric cluster with windows security. To the service connections created some weeks ago everything works as usual.

The difference I see in the logs is that with an "old" it logs **"Windows security is specified. -WindowsCredential switch will be used while connecting."**. This is missing with a new connection, it says directly **"Failed to contact Naming Service. Attempting to contact Failover Manager Service..."**.

### Task logs
[ReleaseLogs_13.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4547026/ReleaseLogs_13.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
2020-04-28T15:03:29.1072012Z Added TLS 1.2 in session.
2020-04-28T15:04:09.7112880Z ##[warning]Failed to contact Naming Service. Attempting to contact Failover Manager Service...
2020-04-28T15:04:09.7134640Z ##[debug]Processed: ##vso[task.logissue type=warning]Failed to contact Naming Service. Attempting to contact Failover Manager Service...
2020-04-28T15:04:49.7064685Z ##[warning]Failed to contact Failover Manager Service, Attempting to contact FMM...
2020-04-28T15:04:49.7065574Z ##[debug]Processed: ##vso[task.logissue type=warning]Failed to contact Failover Manager Service, Attempting to contact FMM...
2020-04-28T15:05:29.7316128Z ##[debug]System.Fabric.FabricTransientException: Could not ping any of the provided Service Fabric gateway endpoints. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C49
2020-04-28T15:05:29.7351815Z ##[debug]   at System.Fabric.Interop.NativeClient.IFabricQueryClient11.EndGetPartitionList2(IFabricAsyncOperationContext context)
2020-04-28T15:05:29.7391780Z ##[debug]   at System.Fabric.FabricClient.QueryClient.GetPartitionListAsyncEndWrapper(IFabricAsyncOperationContext context)
2020-04-28T15:05:29.7431284Z ##[debug]   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
2020-04-28T15:05:29.7477602Z ##[debug]   --- End of inner exception stack trace ---
2020-04-28T15:05:29.7644191Z ##[debug]System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
2020-04-28T15:05:29.7693381Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2020-04-28T15:05:29.7738345Z ##[debug]   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
2020-04-28T15:05:29.7775326Z ##[debug]   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase.TestClusterConnection(IClusterConnection clusterConnection, Boolean testNetwork)
2020-04-28T15:05:29.7817809Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
2020-04-28T15:05:29.7877370Z ##[debug]System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
2020-04-28T15:05:29.7916311Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2020-04-28T15:05:29.7957500Z ##[debug]   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
2020-04-28T15:05:29.7989910Z ##[debug]   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
2020-04-28T15:05:47.2608419Z ##[debug]Re-evaluate condition on job cancellation for step: 'Deploy Service Fabric Application'.
2020-04-28T15:05:47.3156359Z ##[debug]Leaving Connect-ServiceFabricClusterFromServiceEndpoint.
2020-04-28T15:05:47.3745655Z ##[debug]Leaving E:\VSTSBuildAgent\_work\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.9.0\deploy.ps1.
```

**Comment by KnutNiehaus** [comment]
What I could investigate so far by having a closer look at the Connect-ServiceFabricClusterFromServiceEndpoint.ps1 script, that somehow the Hashtable $ConnectedServiceEndpoint does have the Parameter $ConnectedServiceEndpoint.Auth.Parameters.UseWindowsSecurity set to true when called with a newly created service endpoint. When I, for evaluationg only, remove the row `if ($ConnectedServiceEndpoint.Auth.Parameters.UseWindowsSecurity -eq "true")` the deployment works again. 

So could you please investigate, why the $ConnectedServiceEndpoint does not contain that parameter anymore?

**Comment by bishal-pdMSFT** [comment]
Thanks @KnutNiehaus we will investigate this.

**Comment by issacnitin** [comment]
I've raised a PR https://github.com/microsoft/azure-pipelines-tasks/pull/12837 for the bug. Thanks @KnutNiehaus

**Comment by KnutNiehaus** [comment]
> I've raised a PR #12837 for the bug. Thanks @KnutNiehaus

Hi @issacnitin ,

I tested your fix by manually changing the powerhellscript locally.  I think you must use

` if ($ConnectedServiceEndpoint.Auth.Parameters.Unsecured -ne "true")`

instead of

`if ($ConnectedServiceEndpoint.Auth.Parameters.Unsecured -eq "false")`

because if (and this is the case here) the unsecured parameter is null the -eq "false" will not work.

**Comment by issacnitin** [comment]
> > I've raised a PR #12837 for the bug. Thanks @KnutNiehaus
> 
> Hi @issacnitin ,
> 
> I tested your fix by manually changing the powerhellscript locally. I think you must use
> 
> ` if ($ConnectedServiceEndpoint.Auth.Parameters.Unsecured -ne "true")`
> 
> instead of
> 
> `if ($ConnectedServiceEndpoint.Auth.Parameters.Unsecured -eq "false")`
> 
> because if (and this is the case here) the unsecured parameter is null the -eq "false" will not work.

You're right, thanks

**Comment by bishal-pdMSFT** [comment]
@KnutNiehaus this fix will of course help you, but during the course of fixing it we realized that the service connection should actually be having `$ConnectedServiceEndpoint.Auth.Parameters.UseWindowsSecurity` property. But there one small bug due to which it is not present in some connections.
Can you please go to the service connection which is being used in this task for you and try to edit it. Open the service connection UI and you will see an option for "Unsecured" under "Windows security using  gMSA". It will be unchecked. please check it and then uncheck again and then save the connection.
And then re-try you release. Let me know if that works. If it works, you need not wait for the task fix.

**Comment by KnutNiehaus** [comment]
> @KnutNiehaus this fix will of course help you, but during the course of fixing it we realized that the service connection should actually be having `$ConnectedServiceEndpoint.Auth.Parameters.UseWindowsSecurity` property. But there one small bug due to which it is not present in some connections.
> Can you please go to the service connection which is being used in this task for you and try to edit it. Open the service connection UI and you will see an option for "Unsecured" under "Windows security using gMSA". It will be unchecked. please check it and then uncheck again and then save the connection.
> And then re-try you release. Let me know if that works. If it works, you need not wait for the task fix.

Hi @bishal-pdMSFT, this would be great if this works ;-)  My fast, first try over my smartphone seems to work, but it's hard to read logs on the small screen.  I will evaluate on Monday on my full-size work screen and give you feedback!

BR

Knut

**Comment by KnutNiehaus** [comment]
> > @KnutNiehaus this fix will of course help you, but during the course of fixing it we realized that the service connection should actually be having `$ConnectedServiceEndpoint.Auth.Parameters.UseWindowsSecurity` property. But there one small bug due to which it is not present in some connections.
> > Can you please go to the service connection which is being used in this task for you and try to edit it. Open the service connection UI and you will see an option for "Unsecured" under "Windows security using gMSA". It will be unchecked. please check it and then uncheck again and then save the connection.
> > And then re-try you release. Let me know if that works. If it works, you need not wait for the task fix.
> 
> Hi @bishal-pdMSFT, this would be great if this works ;-) My fast, first try over my smartphone seems to work, but it's hard to read logs on the small screen. I will evaluate on Monday on my full-size work screen and give you feedback!
> 
> BR
> 
> Knut

Hey @bishal-pdMSFT , this works!

I edited the not working connections, check the unsecured, uncheck it and then saved them. After that they are working again.

Thank you!

BR

Knut

**Comment by issacnitin** [comment]
We've fixed and rolled out! Closing the issue. Thanks!
