### ISSUE TITLE
[Publish Pipeline Artifact] BUG: Fails on warning.

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-tasks#12790]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Publish Pipeline Artifact

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Unit4
- Agent - Hosted
```
Pool: Azure Pipelines
Image: vs2017-win2016
Agent: Hosted Agent
```

### Task logs

I don't have a debug log, as this won't repo that easily:

```
2020-04-24T19:05:25.0174601Z ##[section]Starting: Publish Pipeline Artifact Sys
2020-04-24T19:05:25.0351761Z ==============================================================================
2020-04-24T19:05:25.0352130Z Task         : Publish Pipeline Artifacts
2020-04-24T19:05:25.0352456Z Description  : Publish (upload) a file or directory as a named artifact for the current run
2020-04-24T19:05:25.0352738Z Version      : 1.2.2
2020-04-24T19:05:25.0352987Z Author       : Microsoft Corporation
2020-04-24T19:05:25.0353327Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
2020-04-24T19:05:25.0353706Z ==============================================================================
2020-04-24T19:05:25.4488316Z Artifact name input: VeniceSys
2020-04-24T19:05:25.4645208Z Uploading pipeline artifact from D:\a\1\a for build #107003
2020-04-24T19:05:25.8970465Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session c6d4deec-3098-4f09-8271-23f11dec733d
2020-04-24T19:05:25.9208917Z Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session c6d4deec-3098-4f09-8271-23f11dec733d
2020-04-28T17:53:27.4876520Z Information, 78 files processed.
2020-04-28T17:53:28.4601474Z Information, 178 files processed.
2020-04-28T17:53:28.4609933Z Information, 278 files processed.
2020-04-28T17:53:28.4638477Z Information, 378 files processed.
2020-04-28T17:53:28.4639380Z Information, 478 files processed.
2020-04-28T17:53:28.4639772Z Information, 578 files processed.
2020-04-28T17:53:28.4640288Z Information, 678 files processed.
2020-04-28T17:53:28.4742789Z Information, 778 files processed.
2020-04-28T17:53:28.4762310Z Information, 878 files processed.
2020-04-28T17:53:28.4784687Z Information, 978 files processed.
2020-04-28T17:53:28.4812282Z Information, 1078 files processed.
2020-04-28T17:53:28.4839712Z Information, 1178 files processed.
2020-04-28T17:53:28.4845622Z Information, 1278 files processed.
2020-04-28T17:53:28.4890874Z Information, 1378 files processed.
2020-04-28T17:53:28.5110160Z Information, 1478 files processed.
2020-04-28T17:53:28.5157511Z Information, 1578 files processed.
2020-04-28T17:53:28.5170612Z Information, 1678 files processed.
2020-04-28T17:53:28.5213308Z Information, 1778 files processed.
2020-04-28T17:53:28.5226848Z Information, 1878 files processed.
2020-04-28T17:53:28.5321315Z Information, 1978 files processed.
2020-04-28T17:53:28.5332490Z Information, 2078 files processed.
2020-04-28T17:53:28.5333309Z Information, 2178 files processed.
2020-04-28T17:53:28.5365990Z Information, 2278 files processed.
2020-04-28T17:53:28.5414049Z Information, 2378 files processed.
2020-04-28T17:53:28.5419199Z Information, 2478 files processed.
2020-04-28T17:53:28.5441717Z Information, 2578 files processed.
2020-04-28T17:53:28.5442270Z Information, 2678 files processed.
2020-04-28T17:53:28.5470315Z Information, 2778 files processed.
2020-04-28T17:53:28.5473785Z Information, 2878 files processed.
2020-04-28T17:53:28.5474210Z Information, 2978 files processed.
2020-04-28T17:53:28.5654680Z Information, 3078 files processed.
2020-04-28T17:53:28.5664061Z Information, Processed 3078 files from D:\a\1\a successfully.
2020-04-28T17:53:29.3669514Z Information, Uploading 3078 files from directory D:\a\1\a.
2020-04-28T17:53:29.3698897Z Information, Uploaded 0 out of 229,463,744 bytes.
2020-04-24T19:05:21.1870118Z Information, Uploaded 419,261 out of 225,320,408 bytes
2020-04-24T19:05:21.1871054Z Information, Content upload is done!
2020-04-24T19:05:21.1900075Z Information, 
2020-04-24T19:05:21.1901495Z Content upload statistics:
2020-04-24T19:05:21.1902284Z Total Content: 450.2 MB
2020-04-24T19:05:21.1903088Z Physical Content Uploaded: 0.2 MB
2020-04-24T19:05:21.1903918Z Logical Content Uploaded: 0.4 MB
2020-04-24T19:05:21.1904681Z Compression Saved: 0.2 MB
2020-04-24T19:05:21.1905430Z Deduplication Saved: 449.8 MB
2020-04-24T19:05:21.1906212Z Number of Chunks Uploaded: 4
2020-04-24T19:05:21.1906826Z 
2020-04-24T19:05:21.9108481Z Warning, [] Try 1/3, non-retryable exception caught. Throwing. Details:
2020-04-24T19:05:21.9129789Z No LastRequestResponse on exception VssServiceException: Adding of root failed because dedup has expired. Dedup ID: 469A38C6E67EE2CBD10F8E0BA9AEA8D8D2A41228678916AADED1BDCA618857A7 Microsoft.VisualStudio.Services.Common.VssServiceException: Adding of root failed because dedup has expired. Dedup ID: 469A38C6E67EE2CBD10F8E0BA9AEA8D8D2A41228678916AADED1BDCA618857A7
2020-04-24T19:05:21.9158436Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
2020-04-24T19:05:21.9163512Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
2020-04-24T19:05:21.9164773Z    at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
2020-04-24T19:05:21.9166291Z    at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
2020-04-24T19:05:21.9168169Z    at Agent.Plugins.PipelineArtifact.BuildServer.AssociateArtifactAsync(Guid projectId, Int32 pipelineId, String name, String jobId, String type, String data, Dictionary`2 propertiesDictionary, CancellationToken cancellationToken)
2020-04-24T19:05:21.9170952Z    at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.<>c__DisplayClass2_1.<<UploadAsync>b__2>d.MoveNext()
2020-04-24T19:05:21.9171659Z --- End of stack trace from previous location where exception was thrown ---
2020-04-24T19:05:21.9172343Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2020-04-24T19:05:21.9184803Z Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session c6d4deec-3098-4f09-8271-23f11dec733d
2020-04-24T19:05:21.9233759Z ##[error]Adding of root failed because dedup has expired. Dedup ID: 469A38C6E67EE2CBD10F8E0BA9AEA8D8D2A41228678916AADED1BDCA618857A7
2020-04-24T19:05:22.1615785Z ##[section]Finishing: Publish Pipeline Artifact Sys
```

**Comment by jahsu-MSFT** [comment]
Thanks for reporting. Assigning to @fadnavistanmay who is maintaining the Pipeline Artifact tasks to investigate the issue.

**Comment by fadnavistanmay** [comment]
Failed to reply to this thread. If you check the timestamp, there is a 4 day delay between when the job started, and the files were processed. Something definitely is not right with the agent for the particular run. I am going to close this as s one off issue.
