### ISSUE TITLE
"Ambiguous project name" when using yaml build file.

### ISSUE THREAD

**Issue by vern-mix** [microsoft/azure-pipelines-tasks#12838]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2 

## Environment
- Server - Azure Pipelines?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: MiXTelematics/Comms/MiX.Quarry/master_2020.05.07.2

- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Current agent version: '2.165.2'

## Issue Description

When I create a dotnet restore task in yaml, the task fails with: 

**System.InvalidOperationException: Ambiguous project name 'ProjectName'.**

When I create the same dotnet restore task using the sysiwyg task creator that spits out the exact same yaml that I use in my file it works perfectly. Comparing the two log files side by side indicates that there seems to be some kind of concurrency issue. The logs are roughly the same until some point where certain parts of the logs appear at different locations. Then later on suddenly the one approach just fails. Rolling back SDK does not work, using the latest SDK also does not seem to have any affect. (3.1.201)

Here is the YAML:

```
#globals
variables:
    assemblyName: ProjectName
    projectFile: $(assemblyName).csproj
    projectFilePath: $(assemblyName)/$(projectFile)
    nugetConfigPath: $(assemblyName)/NuGet.Config

#dotnet restore
- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: restore
    projects: $(projectFilePath)
    feedsToUse: config
    nugetConfigPath: $(System.DefaultWorkingDirectory)/$(nugetConfigPath)
```

That exact config works if I do it using the drag and drop interface with a dotnet restore task.

```
2020-05-07T11:25:04.9698076Z      1>Target "Restore" in file "/home/ubuntu/myagent/_work/_tool/dotnet/sdk/3.1.201/NuGet.targets" from project "/home/ubuntu/myagent/_work/2783/s/MiX.Quarry/MiX.Quarry.csproj" (entry point):
2020-05-07T11:25:04.9698791Z        Task "RemoveDuplicates"
2020-05-07T11:25:04.9699147Z        Done executing task "RemoveDuplicates".
2020-05-07T11:25:04.9699781Z        Using "RestoreTask" task from assembly "/home/ubuntu/myagent/_work/_tool/dotnet/sdk/3.1.201/NuGet.Build.Tasks.dll".
2020-05-07T11:25:04.9700333Z        Task "RestoreTask"
2020-05-07T11:25:04.9701025Z          (in) RestoreGraphItems Count '17'
2020-05-07T11:25:04.9701690Z          (in) RestoreDisableParallel 'False'
2020-05-07T11:25:04.9702345Z          (in) RestoreNoCache 'False'
2020-05-07T11:25:04.9702997Z          (in) RestoreIgnoreFailedSources 'False'
2020-05-07T11:25:04.9703642Z          (in) RestoreRecursive 'True'
2020-05-07T11:25:04.9704255Z          (in) RestoreForce 'False'
2020-05-07T11:25:04.9704859Z          (in) HideWarningsAndErrors 'False'
2020-05-07T11:25:04.9705514Z          (in) RestoreForceEvaluate 'False'
2020-05-07T11:25:04.9706190Z          (in) RestorePackagesConfig 'False'
2020-05-07T11:25:05.0927600Z          Running restore with 2 concurrent jobs.
2020-05-07T11:25:05.1511275Z          Reading project file /home/ubuntu/myagent/_work/2783/s/MiX.Quarry.Core/MiX.Quarry.Core.csproj.
2020-05-07T11:25:05.1513313Z          Reading project file /home/ubuntu/myagent/_work/2783/s/MiX.Quarry/MiX.Quarry.csproj.
2020-05-07T11:25:05.1515978Z          Persisting no-op dg to /home/ubuntu/myagent/_work/2783/s/MiX.Quarry.Core/obj/MiX.Quarry.Core.csproj.nuget.dgspec.json
2020-05-07T11:25:05.1518288Z          Persisting no-op dg to /home/ubuntu/myagent/_work/2783/s/MiX.Quarry/obj/MiX.Quarry.csproj.nuget.dgspec.json
2020-05-07T11:25:05.1520066Z          Restoring packages for /home/ubuntu/myagent/_work/2783/s/MiX.Quarry.Core/MiX.Quarry.Core.csproj...
2020-05-07T11:25:05.1521629Z          Restoring packages for /home/ubuntu/myagent/_work/2783/s/MiX.Quarry/MiX.Quarry.csproj...
2020-05-07T11:25:05.1574736Z      1>/home/ubuntu/myagent/_work/_tool/dotnet/sdk/3.1.201/NuGet.targets(124,5): error : Ambiguous project name 'MiX.Quarry'. [/home/ubuntu/myagent/_work/2783/s/MiX.Quarry/MiX.Quarry.csproj]
2020-05-07T11:25:05.1603347Z          Restoring packages for .NETStandard,Version=v2.1...
2020-05-07T11:25:05.1669742Z          System.InvalidOperationException: Ambiguous project name 'MiX.Quarry'.
2020-05-07T11:25:05.1671021Z             at NuGet.Commands.RestoreCommand.GetProjectReferences(RemoteWalkContext context)
2020-05-07T11:25:05.1672462Z             at NuGet.Commands.RestoreCommand.ExecuteRestoreAsync(NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteWalkContext context, CancellationToken token, TelemetryActivity telemetryActivity)
2020-05-07T11:25:05.1673825Z             at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
2020-05-07T11:25:05.1674742Z             at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
2020-05-07T11:25:05.1675789Z             at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
2020-05-07T11:25:05.1676777Z             at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
2020-05-07T11:25:05.1678102Z             at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token)
2020-05-07T11:25:05.1679147Z             at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
2020-05-07T11:25:05.1680707Z             at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, ILogger log, CancellationToken cancellationToken)
2020-05-07T11:25:05.1682006Z             at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log)
2020-05-07T11:25:05.1683305Z        Done executing task "RestoreTask" -- FAILED.
2020-05-07T11:25:05.1684157Z      1>Done building target "Restore" in project "MiX.Quarry.csproj" -- FAILED.
2020-05-07T11:25:05.1685234Z      1>Done Building Project "/home/ubuntu/myagent/_work/2783/s/MiX.Quarry/MiX.Quarry.csproj" (Restore target(s)) -- FAILED.
2020-05-07T11:25:05.1714853Z 
2020-05-07T11:25:05.1715732Z Build FAILED.
2020-05-07T11:25:05.1716093Z 
2020-05-07T11:25:05.1717288Z        "/home/ubuntu/myagent/_work/2783/s/MiX.Quarry/MiX.Quarry.csproj" (Restore target) (1) ->
2020-05-07T11:25:05.1718253Z        (Restore target) -> 
2020-05-07T11:25:05.1719643Z          /home/ubuntu/myagent/_work/_tool/dotnet/sdk/3.1.201/NuGet.targets(124,5): error : Ambiguous project name 'MiX.Quarry'. [/home/ubuntu/myagent/_work/2783/s/MiX.Quarry/MiX.Quarry.csproj]
2020-05-07T11:25:05.1720525Z 
2020-05-07T11:25:05.1720894Z     0 Warning(s)
2020-05-07T11:25:05.1721279Z     1 Error(s)
2020-05-07T11:25:05.1721623Z 
2020-05-07T11:25:05.1722009Z Time Elapsed 00:00:00.78
```

**Comment by issacnitin** [comment]
@vern-mix I'm sorry, I didn't fully understand What is sysiwyg task creator? Could you check if the project Id in MiX.Quarry.csproj does not conflict with any of the packages that's being restored?

**Comment by issacnitin** [comment]
@vern-mix Were you able to check if the project GUID has conflicts?

**Comment by issacnitin** [comment]
@vern-mix We're closing the issue for now as we couldn't get a response from you. Please feel free to re-open in case of any questions or concerns

**Comment by lkfabu2022** [comment]
I'm running into this exact thing.
Was there any resolution to this issue?
