### ISSUE TITLE
Publish artifact fails when retry failed job

### ISSUE THREAD

**Issue by Thilas** [microsoft/azure-pipelines-tasks#12854]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishPipelineArtifact
(and its `publish` yaml alias)

## Environment
- Server - Azure Pipelines

    - account name, team project name, build definition name/build number: https://dev.azure.com/totodem/Test/_build?definitionId=13 (this is just a reproduction environment, it is not my actual pipeline)

- Agent - Any

## Issue Description

I have a 1st job that runs some tests and then publishes a report of what happened. Then I have a 2nd job that downloads this report to process it on some specific environment (it can't be done in the 1st job).

If tests fail at first and if I retry it and tests pass, then the job will still be failing because of the publish task saying that the artifact already exists for the run.

I really can't see any workaround in my scenario. Besides I think overwriting an existing artifact should be allowed (at least as an option if not as the default behavior).

### Task logs

[task_logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4602990/logs_717.zip) 
See: https://dev.azure.com/totodem/Test/_build/results?buildId=717&view=results

### Error logs

```
Content upload statistics:
Total Content: 0.0 MB
Physical Content Uploaded: 0.0 MB
Logical Content Uploaded: 0.0 MB
Compression Saved: 0.0 MB
Deduplication Saved: 0.0 MB
Number of Chunks Uploaded: 0

##[debug]Processed: ##vso[telemetry.publish area=AzurePipelinesAgent;feature=PipelineArtifact]{"FileCount":"1","PlanId":"16a9d149-f35b-4aea-8c1f-d63b3e4a34cb","JobId":"1fc5331a-005d-5eb9-d395-42342757d3b4","TaskInstanceId":"bd882dcf-5562-57f6-a529-d6a16c88322e","ActionDurationMs":"541","ActionName":"PipelineArtifact.UploadAsync","ActionResult":"Success","AttemptNumber":"1","ItemCount":"0","Level":"ThirdParty","CreatedUtcNow":"2020-05-09T08:15:55.1548872Z","SentUtcNow":"2020-05-09T08:15:55.6992532Z","BaseAddress":"https://vsblobprodsu6weu.vsblob.visualstudio.com/Aff8dda6f-003c-49c5-b7b0-8098c9542150/","X_TFS_Session":"40831976-1c66-4fe1-94f6-42ee4d5dc7ad","DeploymentEnvironment":"PRODUCTION","DeploymentEnvironmentIsProduction":"True","VSOAccount":"vsblobprodsu6weu","OSName":"Linux","OSVersion":"2020","FrameworkDescription":".NET Core ","ProcessName":"Agent.PluginHost","DotNetReleaseDword":"-1","Version":"18.166.29828.0","ExceptionCount":"0"}
Warning, [] Try 1/3, non-retryable exception caught. Throwing. Details:
No LastRequestResponse on exception ArtifactExistsException: Artifact Report already exists for build 717. Microsoft.TeamFoundation.Build.WebApi.ArtifactExistsException: Artifact Report already exists for build 717.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Agent.Plugins.PipelineArtifact.BuildServer.AssociateArtifactAsync(Guid projectId, Int32 pipelineId, String name, String jobId, String type, String data, Dictionary`2 propertiesDictionary, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.<>c__DisplayClass2_1.<<UploadAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 40831976-1c66-4fe1-94f6-42ee4d5dc7ad
##[error]Artifact Report already exists for build 717.
##[debug]Processed: ##vso[task.logissue type=error;]Artifact Report already exists for build 717.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Agent.Plugins.PipelineArtifact.BuildServer.AssociateArtifactAsync(Guid projectId, Int32 pipelineId, String name, String jobId, String type, String data, Dictionary`2 propertiesDictionary, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.<>c__DisplayClass2_1.<<UploadAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.ExceptionExtensions.ReThrow(Exception ex)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.UploadAsync(AgentTaskPluginExecutionContext context, Guid projectId, Int32 pipelineId, String name, String source, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: Publish report
```

**Comment by abatishchev** [comment]
This affects us internally too!

**Comment by vijayma** [comment]
This is currently a limitation of pipeline artifacts. You have a few options: (a) Use publish/download build artifacts tasks instead of publish/download pipeline artifacts. (b) Generate a unique name for your pipeline artifact upon retry (for e.g., by using the System.JobAttempt variable).

**Comment by abatishchev** [comment]
Thanks for the info and the tip, I'll implement it.

Can the task have a flag to instruct it to overwrite the artifacts?

**Comment by vijayma** [comment]
The way they are implemented, pipeline artifacts are immutable. So, no. Even if we implemented a flag, it would be at the task layer to create a unique identifier. It would be better to leave that up to the user as to how they want to name their artifact. We should document this though. We will do that.

**Comment by goldsam** [comment]
If your API does not provide a reasonable way bypass reuploading an existing artifact, deleting it, or overwriting it, then there is no way re-running a failed artifact publishing job will ever succeed. That sir is called a bug. 

Furthermore, you have received overwhelming feedback from the community that the current behavior is problematic.

Please stop arguing with your paying customers and fix it.

**Comment by CrispyDrone** [comment]
> This is currently a limitation of pipeline artifacts. You have a few options: (a) Use publish/download build artifacts tasks instead of publish/download pipeline artifacts. (b) Generate a unique name for your pipeline artifact upon retry (for e.g., by using the System.JobAttempt variable).

The documentations specifies using the `System.JobId` variable. If we include this in our artifact name, how can another job get access to this variable? Don't want to rely on `buildType: current` for the `DownloadPipelineArtifact` task, which might include a lot of other artifacts we don't need.

[can-i-delete-pipeline-artifacts-when-rerunning-failed-jobs](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#q-can-i-delete-pipeline-artifacts-when-rerunning-failed-jobs)
