### ISSUE TITLE
Azure Powershell Task intermittently throwing "504 Gateway Timeout"

### ISSUE THREAD

**Issue by ricohomewood** [microsoft/azure-pipelines-tasks#12891]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
       
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
     Org: `Spektrix`
     Project: `Spektrix`
     Pipeline: `Migrate Client Database to Azure (Pipeline A)`
     Release definition Id: `36`

- Agent - Hosted or Private: Private

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    OS: `Windows Server 2016`
    Agent: `2.168.2`

## Issue Description

During the job initialization, I get an intermittent error message:

```powershell
2020-05-12T14:52:59.2265912Z ##[command]Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
2020-05-12T14:52:59.3747729Z ##[error]An error occurred while sending the request.
2020-05-12T14:52:59.4074891Z ##[error]Initializing Az module failed: For troubleshooting, refer: https://aka.ms/azurepowershelltroubleshooting
2020-05-12T14:52:59.4967707Z ##[error]There was an error with the service principal used for the deployment. 
```

When we look into the debug logs it seems the underlying issue is that there is a `The remote server returned an error: (504) Gateway Timeout.` error thrown.

### Task logs

```
2020-05-12T14:52:55.6749944Z ##[section]Starting: Bring client back online in Netscalers
2020-05-12T14:52:55.7131210Z ==============================================================================
2020-05-12T14:52:55.7131418Z Task         : Azure PowerShell
2020-05-12T14:52:55.7131605Z Description  : Run a PowerShell script within an Azure environment
2020-05-12T14:52:55.7131740Z Version      : 4.168.0
2020-05-12T14:52:55.7131875Z Author       : Microsoft Corporation
2020-05-12T14:52:55.7132013Z Help         : [Learn more about this task](https://go.microsoft.com/fwlink/?LinkID=613749)
2020-05-12T14:52:55.7132176Z ==============================================================================
2020-05-12T14:52:56.7123809Z ## Validating Inputs
2020-05-12T14:52:56.7151347Z ## Validating Inputs Complete
2020-05-12T14:52:56.7158715Z ## Initializing Az module
2020-05-12T14:52:56.9586820Z Added TLS 1.2 in session.
2020-05-12T14:52:57.1804280Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\1.7.5\Az.Accounts.psd1 -Global
2020-05-12T14:52:57.8124863Z ##[command]Clear-AzContext -Scope Process
2020-05-12T14:52:58.5032124Z ##[command]Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
2020-05-12T14:52:59.2265912Z ##[command]Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
2020-05-12T14:52:59.3747729Z ##[error]An error occurred while sending the request.
2020-05-12T14:52:59.4074891Z ##[error]Initializing Az module failed: For troubleshooting, refer: https://aka.ms/azurepowershelltroubleshooting
2020-05-12T14:52:59.4967707Z ##[error]There was an error with the service principal used for the deployment.
2020-05-12T14:52:59.5356403Z ##[section]Finishing: Bring client back online in Netscalers
```
### Error logs

```
Module : Az.Accounts
Cmdlet : Connect-AzAccount
Parameters
 -ServicePrincipal : True
 -Tenant : b00144c3-14f7-4e45-882a-223f538efe33
 -Credential : System.Management.Automation.PSCredential
 -Environment : AzureCloud
 -Scope : Process
 -WarningAction : SilentlyContinue
[Common.Authentication]: Authenticating using configuration values: Domain: 'b00144c3-14f7-4e45-882a-223f538efe33', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
[ADAL]: Information: 2020-05-13T11:03:05.1971779Z: 78beb7a8-194b-41f7-a968-04a8580262a3 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
[ADAL]: Information: 2020-05-13T11:03:05.1971779Z: 78beb7a8-194b-41f7-a968-04a8580262a3 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
[ADAL]: Information: 2020-05-13T11:03:05.1971779Z: 78beb7a8-194b-41f7-a968-04a8580262a3 - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: Client
	, Authority Host: login.microsoftonline.com
[ADAL]: Information: 2020-05-13T11:03:05.1971779Z: 78beb7a8-194b-41f7-a968-04a8580262a3 - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/b00144c3-14f7-4e45-882a-223f538efe33/
	Resource: https://management.core.windows.net/
	ClientId: d8441486-902a-488c-8db1-bf4d185cb4bf
	CacheType: null
	Authentication Target: Client
[ADAL]: Error: 2020-05-13T11:03:05.2752875Z: 78beb7a8-194b-41f7-a968-04a8580262a3 - LoggerBase.cs: Exception type: System.Net.Http.HttpRequestException ---> Exception type: System.Net.WebException
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
--- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery.<DiscoverAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery.<GetMetadataEntryAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator.<UpdateFromTemplateAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<PreRunAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
[ADAL]: Error: 2020-05-13T11:03:05.2752875Z: 78beb7a8-194b-41f7-a968-04a8580262a3 - LoggerBase.cs: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery.<DiscoverAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery.<GetMetadataEntryAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator.<UpdateFromTemplateAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<PreRunAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
```

**Comment by ricohomewood** [comment]
Seems this _could_ be related: https://github.com/Azure/azure-powershell/issues/9467
