### ISSUE TITLE
DownloadPipelineArtifact: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by abatishchev** [microsoft/azure-pipelines-tasks#12937]
## Required Information

**Question, Bug, or Feature?**  Bug
**Enter Task Name**: `DownloadPipelineArtifact@2`

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines,

Org: microsoft
Project: Universal Store
Build: 50530

- Agent - Hosted or Private: 
    
Pool: Universal Store

## Issue Description

DownloadPipelineArtifact fails with `NullReferenceException` and without any further explanation what's wrong exactly.

### Task logs

```
##[debug]Evaluating condition for step: 'DownloadPipelineArtifact'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: DownloadPipelineArtifact
==============================================================================
Task         : Download Pipeline Artifacts
Description  : Download build and pipeline artifacts
Version      : 2.3.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
==============================================================================
##[error]Object reference not set to an instance of an object.
##[debug]Processed: ##vso[task.logissue type=error;]Object reference not set to an instance of an object.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV2_0_0.GetPipelineIdAsync(AgentTaskPluginExecutionContext context, String pipelineDefinition, String pipelineVersionToDownload, String project, String[] tagFilters, BuildResult resultFilter, String branchName, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV2_0_0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: DownloadPipelineArtifact
```

**Comment by abatishchev** [comment]
Ping?

**Comment by henning-krause** [comment]
I have the same issue. This is the step from my template:

```yaml
steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: <ProjectName>
      artifactName: core-services
      pipeline: core-services
      preferTriggeringPipeline: true
      path: Build
```

**Comment by henning-krause** [comment]
In my case, the artifactName was incorrect. After specifying the correct name, everything works.

**Comment by henning-krause** [comment]
@abatishchev Why was this closed? Shouldn't the task provide a clear error message when the name is incorrect?

**Comment by abatishchev** [comment]
No traction from the service team, tired from trying get their attention. But you're right, let's keept it open.
