### ISSUE TITLE
NullReference exception while publishing test results

### ISSUE THREAD

**Issue by uandrei** [microsoft/azure-pipelines-tasks#13013]
## Steps to reproduce
This doesn't happen all the time, it's on and off, although recently it seems to be happening more often than before. Our CI pipeline in DevOps fails at the test stage. The test run is successful and when test results are published the vstest app crashes with a null reference exception.

Captured diagnostics and full debug log from the Azure DevOps console and attached to this email alongside the output trx.

Considering the fact that is not always failing i'm just wondering if it's a timing issue whereby the trx is not yet flushed to the disk before it tries to read it?

```
Error stack trace

Error occurred while publishing test results : System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.<>c__DisplayClass16_0.<ReadActualResults>b__1(String xunitParentNodeKey)
    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ReadActualResults(XmlNodeList resultsNodes, TestType testType, Dictionary`2 xUnitTestCaseCounts)
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ParseTestResultFile(TestRunContext runContext, String filePath)
    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ParseTestResultFiles(TestRunContext runContext, IList`1 resultFilePaths)
    at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.ParseTrx(TestRunContext testRunContext, IList`1 trxFilePaths)
    at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.PublishTestRunResults(TestRunModel testRunModel)
    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.CreateOrUpdateTestRun(TestRunModel testRunModel)
    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.Publish(VstestConsoleRunContext testRunContext)
    ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.<>c__DisplayClass16_0.<ReadActualResults>b__1(String xunitParentNodeKey)
    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
```

## Attachments
[github-issue.zip](https://github.com/microsoft/vstest/files/4355112/github-issue.zip)
[logs.txt](https://github.com/microsoft/vstest/files/4355113/logs.txt)

> Operating system, Build version of vstest.console
OS: Windows (Windows Server 2016 Datacenter)
VSTest: 16.5.0

**Comment by ShreyasRmsft** [comment]
@uandrei can you confirm if you are still facing this issue with the vstestv2 task? This was patched a couple of weeks ago.

In the publish test results task it will be patched in a couple of days

**Comment by uandrei** [comment]
hi @ShreyasRmsft , haven't upgraded vstest v2 task for some time, will do that and keep an eye on it.  do we need to update the vstest version too? at the moment that is pinned to 16.4.0

**Comment by ShreyasRmsft** [comment]
You cannot pin VSTest@2 task version as it is controlled by the server. Let me know if you are still running into this issue with the vstestv2 task and please provide full zip of logs with system.debug = true.

**Comment by uandrei** [comment]
@ShreyasRmsft should we also upgrade to latest version of  VSTest?

**Comment by ShreyasRmsft** [comment]
@uandrei it's generally a good practice to stay on the latest stable unless your run into some issues, so yeah go ahead.

**Comment by upadhyayap** [comment]
@uandrei please update to latest version of publish test results task and do let me know of you are still facing issue in that task.

**Comment by Arwinder4** [comment]
@uandrei can you please confirm if the issue is resolved or not?

**Comment by uandrei** [comment]
@Arwinder4 really sorry but not in a position to test this, so i'd just close the issue at the moment
