### ISSUE TITLE
DownloadPipelineArtifact Cancelled after 20min well over 100%

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-tasks#13144]
## Required Information
As described [here](https://developercommunity.visualstudio.com/content/problem/1067515/etimeout-on-nodetool.html) we are seeing download tasks fail in weird ways across different platforms, agents and even across YAML or Classic Pipelines.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPipelineArtifact

## Environment
- Server - Azure Pipelines    
    - Account: buhlergroup
    - Project: myBühler
    - Pipeline: images-build-new (YAML)
    - Build Id: 80854
- Agent - Private: 
    - ecom-app02-dev
    - Windows

## Issue Description

The Download task runs to >100% (e.g. 230%) then fails. Checking the server it seems the Artifact has been downloaded but the Agent is confused and gives up after 20min.

Interestingly we are seeing similar weird behaviour with the NodeJS task. We are behind a firewall and proxy but we have failry convincingly excluded this as a problem by watching the traffic and seeing it pass through.

```
==============================================================================
Task         : Download pipeline artifact
Description  : Download a named artifact from a pipeline to a local path
Version      : 1.2.5
Author       : Microsoft Corporation
Help         : Download a named artifact from a pipeline to a local path
==============================================================================
```

### Task logs

```
2020-06-15T08:21:10.9220984Z ##[debug]Evaluating condition for step: 'Download Artifact'
2020-06-15T08:21:10.9265409Z ##[debug]Evaluating: SucceededNode()
2020-06-15T08:21:10.9271801Z ##[debug]Evaluating SucceededNode:
2020-06-15T08:21:10.9311707Z ##[debug]=> True
2020-06-15T08:21:10.9321060Z ##[debug]Result: True
2020-06-15T08:21:10.9362732Z ##[section]Starting: Download Artifact
2020-06-15T08:21:10.9981484Z ==============================================================================
2020-06-15T08:21:10.9981958Z Task         : Download pipeline artifact
2020-06-15T08:21:10.9982325Z Description  : Download a named artifact from a pipeline to a local path
2020-06-15T08:21:10.9982530Z Version      : 1.2.5
2020-06-15T08:21:10.9982811Z Author       : Microsoft Corporation
2020-06-15T08:21:10.9983251Z Help         : Download a named artifact from a pipeline to a local path
2020-06-15T08:21:10.9983648Z ==============================================================================
2020-06-15T08:21:11.4935609Z Download from the specified build: #80854
2020-06-15T08:21:11.4937674Z Download artifact to: D:\prg\azure\vm\_work\2/
2020-06-15T08:21:12.6417083Z ##[debug]Dedup parallelism: 192
2020-06-15T08:21:13.0468945Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 315e8fda-7ca5-4f0f-a664-***
2020-06-15T08:21:13.1480618Z Downloading 2 pipeline artifacts...
2020-06-15T08:21:13.1602500Z Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session 315e8fda-7ca5-4f0f-a664-***
2020-06-15T08:21:13.1603123Z Information, Start downloading artifact - ImagesLinux
2020-06-15T08:21:13.1619014Z Information, Minimatch patterns: [**]
2020-06-15T08:21:14.3046144Z Information, Filtered 3588 files from the Minimatch filters supplied.
2020-06-15T08:21:14.3287849Z Information, Downloaded 0.0 MB out of 95.8 MB (0%).
2020-06-15T08:21:19.7023491Z Information, Downloaded 87.3 MB out of 95.8 MB (91%).
2020-06-15T08:21:24.6869564Z Information, Downloaded 95.2 MB out of 95.8 MB (99%).
2020-06-15T08:21:29.7005744Z Information, Downloaded 95.2 MB out of 95.8 MB (99%).
2020-06-15T08:21:34.7117930Z Information, Downloaded 95.2 MB out of 95.8 MB (99%).
2020-06-15T08:21:39.7199801Z Information, Downloaded 95.2 MB out of 95.8 MB (99%).
2020-06-15T08:21:44.7276772Z Information, Downloaded 95.2 MB out of 95.8 MB (99%).
2020-06-15T08:21:49.7321244Z Information, Downloaded 95.2 MB out of 95.8 MB (99%).
2020-06-15T08:21:54.7427336Z Information, Downloaded 95.2 MB out of 95.8 MB (99%).
2020-06-15T08:21:59.7553679Z Information, Downloaded 95.2 MB out of 95.8 MB (99%).
2020-06-15T08:27:45.4205722Z Information, Downloaded 108.4 MB out of 95.8 MB (113%).
2020-06-15T08:27:50.4248787Z Information, Downloaded 108.4 MB out of 95.8 MB (113%).
2020-06-15T08:27:55.4354670Z Information, Downloaded 108.4 MB out of 95.8 MB (113%)
....
2020-06-15T08:30:45.8429927Z Information, Downloaded 108.4 MB out of 95.8 MB (113%).
2020-06-15T08:30:50.8485507Z Information, Downloaded 108.4 MB out of 95.8 MB (113%).
2020-06-15T08:30:55.8636450Z Information, Downloaded 108.4 MB out of 95.8 MB (113%).
2020-06-15T08:31:00.8715654Z Information, Downloaded 108.4 MB out of 95.8 MB (113%).
2020-06-15T08:31:05.8743736Z Information, Downloaded 109.0 MB out of 95.8 MB (114%).
2020-06-15T08:31:10.8817250Z Information, Downloaded 117.2 MB out of 95.8 MB (122%).
2020-06-15T08:31:15.8868252Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:31:20.8900517Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:31:25.9017621Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
...
2020-06-15T08:35:16.3509455Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:35:21.3761208Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:35:26.3877364Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:35:31.3928947Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:35:36.4084329Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:35:41.4209211Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:35:46.4256214Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:35:51.4389578Z Information, Downloaded 121.6 MB out of 95.8 MB (127%).
2020-06-15T08:35:56.4486181Z Information, Downloaded 122.3 MB out of 95.8 MB (128%).
2020-06-15T08:36:01.4511784Z Information, Downloaded 129.0 MB out of 95.8 MB (135%).
2020-06-15T08:36:06.4666617Z Information, Downloaded 130.5 MB out of 95.8 MB (136%).
2020-06-15T08:36:11.4787401Z Information, Downloaded 134.3 MB out of 95.8 MB (140%).
2020-06-15T08:36:16.4828271Z Information, Downloaded 134.9 MB out of 95.8 MB (141%).
2020-06-15T08:36:21.4836456Z Information, Downloaded 134.9 MB out of 95.8 MB (141%).
2020-06-15T08:36:26.5006151Z Information, Downloaded 134.9 MB out of 95.8 MB (141%).
...
2020-06-15T08:41:02.0216316Z Information, Downloaded 134.9 MB out of 95.8 MB (141%).
2020-06-15T08:41:07.0318641Z Information, Downloaded 134.9 MB out of 95.8 MB (141%).
2020-06-15T08:41:08.7820009Z Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 315e8fda-7ca5-4f0f-a664-05c9ea9f7e33
2020-06-15T08:41:08.7858263Z ##[error]An error occurred while sending the request.
2020-06-15T08:41:08.7871018Z ##[debug]Processed: ##vso[task.logissue type=error;]An error occurred while sending the request.
2020-06-15T08:41:08.7879770Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2020-06-15T08:41:08.7887886Z ##[debug]   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.Common.TaskCancellationExtensions.EnforceCancellation[TResult](Task`1 task, CancellationToken cancellationToken, Func`1 makeMessage, String file, String member, Int32 line)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.<>c__DisplayClass57_0.<<GetRedirectResponseAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.<>c__DisplayClass60_0.<<HandleRedirectAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.<>c__DisplayClass37_2.<<GetDedupGettersAsync>b__5>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.DownloadToFileAsync(DedupIdentifier dedupId, String fullPath, GetDedupAsyncFunc dedupFetcher, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClientWithDataport.DownloadToFileAsync(IDedupDataPort dataport, DedupIdentifier dedupId, String fullPath, UInt64 fileSize, GetDedupAsyncFunc dedupFetcher, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.<>c__DisplayClass25_2.<<DownloadAsyncWithManifestPath>b__9>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper.<>c__DisplayClass10_0.<<CreateTaskWrapper>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.<>c__DisplayClass25_0.<<DownloadAsyncWithManifestPath>b__5>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingActionBlock.<>c__DisplayClass5_0`1.<<CreateNonSwallowingFunc>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.TargetBlockExtensions.SendAllAndCompleteAsync[T1,T2](ITargetBlock`1 targetBlock, IEnumerable`1 inputs, ITargetBlock`1 finalBlock, CancellationToken token)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadAsyncWithManifestPath(DownloadDedupManifestArtifactOptions downloadOptions, IEnumerable`1 minimatcherFuncs, Boolean downloadManifestReferences, ISet`1 excludedPaths, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadSingleManifestAsync(DownloadDedupManifestArtifactOptions downloadOptions, Boolean downloadManifestReferences, ISet`1 excludedPaths, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadAsync(DownloadDedupManifestArtifactOptions downloadOptions, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.<>c__DisplayClass4_1.<<DownloadAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.BlobStore.Common.Telemetry.BlobStoreClientTelemetry.<>c__DisplayClass5_0.<<MeasureActionAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.Telemetry.ClientTelemetry.MeasureActionAsync[TResult,TRecord](TRecord record, Func`1 actionAsync, Func`2 actionResultToTelemetryStatus, Func`2 actionResultToItemCountAsync, Action`2 updateRecord)
   at Microsoft.VisualStudio.Services.Content.Common.Telemetry.ClientTelemetry.MeasureActionAsync[TResult,TRecord](TRecord record, Func`1 actionAsync, Func`2 actionResultToTelemetryStatus, Func`2 actionResultToItemCountAsync, Action`2 updateRecord)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.DownloadAsync(AgentTaskPluginExecutionContext context, PipelineArtifactDownloadParameters downloadParameters, DownloadOptions downloadOptions, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2020-06-15T08:41:08.8316619Z ##[section]Finishing: Download Artifact
```

**Comment by cawoodm** [comment]
I can confirm this issue using classic pipelines and a deployment job in a YAML pipeline.

**Comment by cawoodm** [comment]
Also, the classic pipeline shows a flashing play button although the stage and job is already running. Pressing the button does nothing except take you to the logs of the job which has been running for some time.

![image](https://user-images.githubusercontent.com/498834/85127798-6754b380-b230-11ea-9d28-2b9ee5ad18d7.png)


![image](https://user-images.githubusercontent.com/498834/85125198-78e78c80-b22b-11ea-8fa8-cf2f8d17067e.png)

**Comment by cawoodm** [comment]
We can now also confirm the issue is on one particular windows server here. It works on other Linux and Windows Servers.

**Comment by cawoodm** [comment]
Worker logs this every 5 seconds:
```
[2020-06-19 11:26:11Z INFO JobServerQueue] Try to append 1 batches web console lines for record '9fc62f4b-1df1-49d6-89b8-d145c4c31eaa', success rate: 1/1.
[2020-06-19 11:26:15Z INFO JobServerQueue] Try to append 1 batches web console lines for record '9fc62f4b-1df1-49d6-89b8-d145c4c31eaa', success rate: 1/1.
[2020-06-19 11:26:20Z INFO JobServerQueue] Try to append 1 batches web console lines for record '9fc62f4b-1df1-49d6-89b8-d145c4c31eaa', success rate: 1/1.
[2020-06-19 11:26:26Z INFO JobServerQueue] Try to append 1 batches web console lines for record '9fc62f4b-1df1-49d6-89b8-d145c4c31eaa', success rate: 1/1.
[2020-06-19 11:26:31Z INFO JobServerQueue] Try to append 1 batches web console lines for record '9fc62f4b-1df1-49d6-89b8-d145c4c31eaa', success rate: 1/1.
[2020-06-19 11:26:35Z INFO JobServerQueue] Try to append 1 batches web console lines for record '9fc62f4b-1df1-49d6-89b8-d145c4c31eaa', success rate: 1/1.
```

**Comment by cawoodm** [comment]
Agent tail of log is:
```
[2020-06-19 11:21:53Z INFO JobDispatcher] Successfully renew job request 96923, job is valid till 19.06.2020 11:31:53
[2020-06-19 11:22:53Z INFO JobDispatcher] Successfully renew job request 96923, job is valid till 19.06.2020 11:32:53
[2020-06-19 11:23:53Z INFO JobDispatcher] Successfully renew job request 96923, job is valid till 19.06.2020 11:33:53
[2020-06-19 11:24:53Z INFO JobDispatcher] Successfully renew job request 96923, job is valid till 19.06.2020 11:34:53
[2020-06-19 11:25:53Z INFO JobDispatcher] Successfully renew job request 96923, job is valid till 19.06.2020 11:35:53
[2020-06-19 11:26:54Z INFO JobDispatcher] Successfully renew job request 96923, job is valid till 19.06.2020 11:36:54
```

**Comment by cawoodm** [comment]
Debugging the PROXY with Fiddler we see a continuous repeating pattern of PATCH, some POSTS a very slow GET (50s) and then some POSTS - rinse and repeat.
![image](https://user-images.githubusercontent.com/498834/85128275-3aed6700-b231-11ea-8eb7-f073cce241e3.png)

**Comment by cawoodm** [comment]
The working server reports `Agent.OSVersion = 6.3.9600` (Windows Server 2012R2) whilst the problem server reports `Agent.OSVersion = 10.0.14393` (Windows Server 2016).

**Comment by cawoodm** [comment]
We have downgraded our agent to `2.165.0` and now everything works:

```
2020-06-19T12:31:38.0762964Z ##[debug]Evaluating condition for step: 'Download artifact - Test1Artifact - Test1Windows'
2020-06-19T12:31:38.0804569Z ##[debug]Evaluating: succeeded()
2020-06-19T12:31:38.0810551Z ##[debug]Evaluating succeeded:
2020-06-19T12:31:38.0850692Z ##[debug]=> True
2020-06-19T12:31:38.0860254Z ##[debug]Result: True
2020-06-19T12:31:38.0902900Z ##[section]Starting: Download artifact - Test1Artifact - Test1Windows
2020-06-19T12:31:38.1442652Z ==============================================================================
2020-06-19T12:31:38.1443173Z Task         : Download pipeline artifact
2020-06-19T12:31:38.1443557Z Description  : Download a named artifact from a pipeline to a local path
2020-06-19T12:31:38.1443779Z Version      : 1.2.5
2020-06-19T12:31:38.1444077Z Author       : Microsoft Corporation
2020-06-19T12:31:38.1444538Z Help         : Download a named artifact from a pipeline to a local path
2020-06-19T12:31:38.1444816Z ==============================================================================
2020-06-19T12:31:38.9848808Z Download from the specified build: #81654
2020-06-19T12:31:38.9849973Z Download artifact to: D:\prg\azure\deploy2\_work\r1\a/Test1Artifact/Test1Windows
2020-06-19T12:31:38.9861118Z ##[debug]Dedup parallelism: 192
2020-06-19T12:31:39.2879936Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 45f78447-7ddc-4bd5-9d03-eccec6e81011
2020-06-19T12:31:39.5145367Z Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session 45f78447-7ddc-4bd5-9d03-eccec6e81011
2020-06-19T12:31:39.5172640Z Information, Minimatch patterns: [**]
2020-06-19T12:31:40.5028777Z Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/A4838db1c-cf4a-4889-81a7-06f3fa968607/_apis/dedup/chunks/9B31019AF116BD18199BE3954EAAFEC7ACC0324D0B93A3421220FD37AD64890A01 attempt 1/6 failed with StatusCode RedirectMethod, IsRetryableResponse False
2020-06-19T12:31:40.7958694Z Information, Filtered 355 files from the Minimatch filters supplied.
2020-06-19T12:31:40.8333673Z Information, Downloaded 0.0 MB out of 1.9 MB (0%).
2020-06-19T12:31:45.8392017Z Information, Downloaded 1.9 MB out of 1.9 MB (100%).
2020-06-19T12:31:46.6548961Z Information, Downloaded 1.9 MB out of 1.9 MB (100%).
2020-06-19T12:31:46.6556470Z Information, 
2020-06-19T12:31:46.6558181Z Download statistics:
2020-06-19T12:31:46.6571229Z Total Content: 1.9 MB
2020-06-19T12:31:46.6571980Z Physical Content Downloaded: 0.9 MB
2020-06-19T12:31:46.6572534Z Compression Saved: 1.1 MB
2020-06-19T12:31:46.6573106Z Local Caching Saved: 0.0 MB
2020-06-19T12:31:46.6573686Z Chunks Downloaded: 358
2020-06-19T12:31:46.6574360Z Nodes Downloaded: 0
2020-06-19T12:31:46.6574697Z 
2020-06-19T12:31:46.6699607Z Information, Download completed.
2020-06-19T12:31:46.7146625Z ##[debug]Processed: ##vso[telemetry.publish area=AzurePipelinesAgent;feature=PipelineArtifact]{"FileCount":"0","PlanId":"938202b7-1716-471d-a22e-c2fc6fd76ed9","JobId":"59f70bef-8cd8-4a43-b7db-ca428aa7392b","TaskInstanceId":"dc1466f9-4067-4e73-a871-f3a079ee44e2","ActionDurationMs":"7154","ActionName":"PipelineArtifact.DownloadAsync","ActionResult":"Success","AttemptNumber":"1","ItemCount":"0","Level":"ThirdParty","CreatedUtcNow":"2020-06-19T12:31:39.5066901Z","SentUtcNow":"2020-06-19T12:31:46.6647492Z","BaseAddress":"https://vsblobprodsu6weu.vsblob.visualstudio.com/A4838db1c-cf4a-4889-81a7-06f3fa968607/","X_TFS_Session":"45f78447-7ddc-4bd5-9d03-eccec6e81011","DeploymentEnvironment":"PRODUCTION","DeploymentEnvironmentIsProduction":"True","VSOAccount":"vsblobprodsu6weu","OSName":"Microsoft Windows","OSVersion":"10.0.14393","FrameworkDescription":".NET Core ","ProcessName":"Agent.PluginHost","DotNetReleaseDword":"-1","Version":"18.164.29709.0 built by: master (818ce344aa)","ExceptionCount":"0"}
2020-06-19T12:31:47.6773967Z Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 45f78447-7ddc-4bd5-9d03-eccec6e81011
2020-06-19T12:31:47.6775563Z Downloading artifact finished.
2020-06-19T12:31:47.7257232Z ##[section]Finishing: Download artifact - Test1Artifact - Test1Windows
```
