### ISSUE TITLE
HelmInstallerV1 is not able to find Helm after pipeline migraton to TFS

### ISSUE THREAD

**Issue by elvinasp** [microsoft/azure-pipelines-tasks#13152]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmInstallerV1 (HelmInstallerV0 too)

## Environment
- Server - Azure Pipelines or TFS on-premises?
Now TFS.    
    - If using TFS on-premises, provide the version: 
Version Dev17.M153.4    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
OS: Ubuntu 18.04
Agent version: 2.168.2

## Issue Description

Release pipeline was migrated from Azure DevOps to on premises TFS by doing export and import. 

Helm Installer fails to deploy Helm3. It fails to download tool from the repo because used repository does not have Helm3 release packages.
https://storage.googleapis.com/kubernetes-helm/

Removing and re adding task did not help. Exported JSON does not seem to have this repo. Changing task version also does not change repo used.

### Task logs

```
2020-06-19T07:01:14.3392744Z ##[debug]isExplicit: 3.2.4
2020-06-19T07:01:14.3400729Z ##[debug]explicit? true
2020-06-19T07:01:14.3413095Z ##[debug]Agent.Version=2.168.2
2020-06-19T07:01:14.3418888Z ##[debug]Agent.ToolsDirectory=/opt/vsts/agent/_work/_tool
2020-06-19T07:01:14.3424922Z ##[debug]checking cache: /opt/vsts/agent/_work/_tool/helm/3.2.4/x64
2020-06-19T07:01:14.3433087Z ##[debug]not found
2020-06-19T07:01:14.3458151Z ##[debug]helm-v3.2.4-fef3ba13-5990-43db-9658-36e4a7dd13c2.zip
2020-06-19T07:01:14.3465736Z ##[debug]Agent.Version=2.168.2
2020-06-19T07:01:14.3472072Z ##[debug]Agent.TempDirectory=/opt/vsts/agent/_work/_temp
2020-06-19T07:01:14.3478934Z Downloading: https://storage.googleapis.com/kubernetes-helm/helm-v3.2.4-linux-amd64.zip
2020-06-19T07:01:14.3486250Z ##[debug]destination /opt/vsts/agent/_work/_temp/helm-v3.2.4-fef3ba13-5990-43db-9658-36e4a7dd13c2.zip
2020-06-19T07:01:14.3494636Z ##[debug]creating stream
2020-06-19T07:01:14.3537520Z ##[debug]downloading
2020-06-19T07:01:14.4142373Z (node:124362) Warning: Ignoring extra certs from `/etc/ssl/certs/ca-certificates.crt`, load failed: error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table
2020-06-19T07:01:14.4148698Z 
2020-06-19T07:01:14.6691730Z ##[warning]Can\'t find loc string for key: HelmDownloadFailed
2020-06-19T07:01:14.6701185Z ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: HelmDownloadFailed
2020-06-19T07:01:14.6789695Z ##[debug]task result: Failed
2020-06-19T07:01:14.6848833Z ##[error]Error: HelmDownloadFailed https://storage.googleapis.com/kubernetes-helm/helm-v3.2.4-linux-amd64.zip Error: Unexpected HTTP response: 404
    at Object.<anonymous> (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:197:36)
    at next (native)
    at fulfilled (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
2020-06-19T07:01:14.6851200Z ##[debug]Processed: ##vso[task.issue type=error;]Error: HelmDownloadFailed https://storage.googleapis.com/kubernetes-helm/helm-v3.2.4-linux-amd64.zip Error: Unexpected HTTP response: 404%0A    at Object.<anonymous> (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:197:36)%0A    at next (native)%0A    at fulfilled (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:4:58)%0A    at process._tickCallback (internal/process/next_tick.js:109:7)
2020-06-19T07:01:14.6871129Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: HelmDownloadFailed https://storage.googleapis.com/kubernetes-helm/helm-v3.2.4-linux-amd64.zip Error: Unexpected HTTP response: 404%0A    at Object.<anonymous> (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:197:36)%0A    at next (native)%0A    at fulfilled (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:4:58)%0A    at process._tickCallback (internal/process/next_tick.js:109:7)
2020-06-19T07:01:14.6996403Z ##[section]Finishing: Install Helm 3.2.4
```

### Error logs

```
2020-06-19T07:01:14.6848833Z ##[error]Error: HelmDownloadFailed https://storage.googleapis.com/kubernetes-helm/helm-v3.2.4-linux-amd64.zip Error: Unexpected HTTP response: 404
    at Object.<anonymous> (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:197:36)
    at next (native)
    at fulfilled (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
2020-06-19T07:01:14.6851200Z ##[debug]Processed: ##vso[task.issue type=error;]Error: HelmDownloadFailed https://storage.googleapis.com/kubernetes-helm/helm-v3.2.4-linux-amd64.zip Error: Unexpected HTTP response: 404%0A    at Object.<anonymous> (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:197:36)%0A    at next (native)%0A    at fulfilled (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:4:58)%0A    at process._tickCallback (internal/process/next_tick.js:109:7)
2020-06-19T07:01:14.6871129Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: HelmDownloadFailed https://storage.googleapis.com/kubernetes-helm/helm-v3.2.4-linux-amd64.zip Error: Unexpected HTTP response: 404%0A    at Object.<anonymous> (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:197:36)%0A    at next (native)%0A    at fulfilled (/opt/vsts/agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.153.1/node_modules/vsts-task-tool-lib/tool.js:4:58)%0A    at process._tickCallback (internal/process/next_tick.js:109:7)
2020-06-19T07:01:14.6996403Z ##[section]Finishing: Install Helm 3.2.4
```

**Comment by elvinasp** [comment]
I managed manually "install" Helm on an agent so Task now is able to find it in cache. However I see that task tries to use Helm2 commands, i.e. "helm init".

I suspect this and download issue might be due to an older task version on on premises TFS deployment. However I cannot check at the moment if the task can be upgraded as I do not have permissions. 

```
This is the version on TFS:
2020-06-19T08:33:21.0178449Z ##[section]Starting: Install Helm 3.2.4
2020-06-19T08:33:21.0186424Z ==============================================================================
2020-06-19T08:33:21.0186756Z Task         : Helm tool installer
2020-06-19T08:33:21.0187050Z Description  : Install Helm on an agent machine
**2020-06-19T08:33:21.0187299Z Version      : 1.153.1**
2020-06-19T08:33:21.0187558Z Author       : Microsoft Corporation
2020-06-19T08:33:21.0188044Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/helm-installer


This is the version on Public Azure pipelines
2020-06-17T07:35:15.5851985Z ##[section]Starting: Install Helm 3.0.3
2020-06-17T07:35:15.5854225Z ==============================================================================
2020-06-17T07:35:15.5854336Z Task         : Helm tool installer
2020-06-17T07:35:15.5854391Z Description  : Install Helm on an agent machine
**2020-06-17T07:35:15.5854440Z Version      : 1.169.1**
2020-06-17T07:35:15.5854535Z Author       : Microsoft Corporation
2020-06-17T07:35:15.5854697Z Help         : https://aka.ms/azpipes-helm-installer-tsg
2020-06-17T07:35:15.5854788Z ==============================================================================
```

**Comment by shigupt202** [comment]
@elvinasp The issue is indeed because of older version of the task. You can use the following set of steps to upgrade the HelmInstallerV1 and HelmDeployV0.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/57620559/85364460-cb34f000-b540-11ea-8f2e-7d6ce22d37cd.png)


[HelmInstallerV1.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4817289/HelmInstallerV1.zip)

[HelmDeployV0.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4817290/HelmDeployV0.zip)

**Comment by elvinasp** [comment]
Thanks @shigupt202.
It was indeed version issue. I have asked administrator to update the task and that did the job.

**Comment by ljani** [comment]
@shigupt202: Thanks for the pointer. Did you build the tasks yourself or are they available from some package source?

**Comment by shigupt202** [comment]
@ljani I built it myself. But you can build the latest version of task anytime. Just clone the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks) repo and run `node make.js build --task HelmDeployV0` and then check the _build folder.
