### ISSUE TITLE
DotNetCoreCLI@2 does not use the proxy correctly

### ISSUE THREAD

**Issue by temelj** [microsoft/azure-pipelines-tasks#13171]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug ?

**Enter Task Name**: DotNetCoreCLI@2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines 
- Agent - Both
    - Private: Agent 2.170.1, one behind proxy, another one not behind a proxy (Windows Server 2016)
    - Cloud Hosted - windows-latest

## Issue Description

The issue is described in the logs.  Firstly I would like to specify what Task I am calling:
```
  - task: DotNetCoreCLI@2
    displayName: 'Restore Packages'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: '00000a00-ef00-0e00-0fb0-000bf0bda000'
      includeNuGetOrg: false   
```

### No Proxy
In the logs, the following line shows up: `##[debug]SYSTEMVSSCONNECTION=https://dev.azure.com/REMOVED/`
but then the next step shows: `##[debug]Discovered URL prefixes: https://dev.azure.com/REMOVED/,https://REMOVED.pkgs.visualstudio.com/,https://pkgsprodcus1.pkgs.visualstudio.com/,https://REMOVED.pkgs.visualstudio.com/,https://REMOVED.pkgs.visualstudio.com/,https://pkgs.dev.azure.com/REMOVED/`

### With Proxy (where I know api.nuget.org is blocked)
`##[debug]NuGet.OverwritePackagingCollectionUrl=undefined`
`##[debug]Getting registry url from https://REMOVED.pkgs.visualstudio.com/`

[Include task name(s), screenshots and any other relevant details]

### Task Logs - No Proxy
```
##[debug]Setting up auth
##[debug]SYSTEMVSSCONNECTION=https://dev.azure.com/REMOVED/
##[debug]Discovered URL prefixes: https://dev.azure.com/REMOVED/,https://REMOVED.pkgs.visualstudio.com/,https://pkgsprodcus1.pkgs.visualstudio.com/,https://REMOVED.pkgs.visualstudio.com/,https://REMOVED.pkgs.visualstudio.com/,https://pkgs.dev.azure.com/REMOVED/
##[debug]DotNetCoreCLITask.ExtraUrlPrefixesForTesting=undefined
##[debug]Getting credentials for local feeds
SYSTEMVSSCONNECTION exists true
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Got auth token
##[debug]externalEndpoints=null
##[debug]Setting up sources
##[debug]selectOrConfig=select
##[debug]Agent.BuildDirectory=D:\TEMELJ_v1\_work\1
##[debug]build.buildId=15518

##[debug]feedRestore=00000a00-ef00-0e00-0fb0-000bf0bda000
##[debug]NuGet.OverwritePackagingCollectionUrl=undefined
##[debug]Getting registry url from https://REMOVED.pkgs.visualstudio.com/
##[debug]Agent.ProxyUrl=undefined
##[debug]Created webApi client for https://REMOVED.pkgs.visualstudio.com/; options: {"proxy":null,"allowRetries":true,"maxRetries":5,"ignoreSslError":false}
##[debug]Feed registry url: https://REMOVED.pkgs.visualstudio.com/_packaging/00000a00-ef00-0e00-0fb0-000bf0bda000/nuget/v3/index.json
##[debug]includeNuGetOrg=false
##[debug]Adding the following sources to the config file: 00000a00-ef00-0e00-0fb0-000bf0bda000
##[debug]Adding sources to nuget.config
##[debug]Saving NuGet.config to a temporary config file.
```

### Task Logs - Proxy

```
##[debug]Setting up auth
##[debug]SYSTEMVSSCONNECTION=https://dev.azure.com/REMOVED/
##[debug]Discovered URL prefixes: https://dev.azure.com/REMOVED/
##[debug]DotNetCoreCLITask.ExtraUrlPrefixesForTesting=undefined
##[debug]Getting credentials for local feeds
SYSTEMVSSCONNECTION exists true
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Got auth token
##[debug]externalEndpoints=null
##[debug]Setting up sources
##[debug]selectOrConfig=select
##[debug]Agent.BuildDirectory=D:\TEMELJ_v1\_work\1
##[debug]build.buildId=15522
##[debug]feedRestore=00000a00-ef00-0e00-0fb0-000bf0bda000
##[debug]NuGet.OverwritePackagingCollectionUrl=undefined
##[debug]Getting registry url from https://dev.azure.com/REMOVED/
##[debug]Agent.ProxyUrl=http://127.0.0.1:3128
##[debug]Agent.ProxyUsername=undefined
##[debug]Agent.ProxyPassword=undefined
##[debug]Agent.ProxyBypassList=undefined
##[debug]Created webApi client for https://dev.azure.com/REMOVED/; options: {"proxy":{"proxyUrl":"http://127.0.0.1:3128","proxyBypassHosts":[]},"allowRetries":true,"maxRetries":5,"ignoreSslError":false}
##[debug]Network call failed. Number of retries left: 2
##[warning]Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
##[debug]Processed: ##vso[task.issue type=warning;]Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
##[debug]Error: Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
    at beginGetLocation.then (D:\TEMELJ_v1\_work\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.171.3\node_modules\azure-devops-node-api\VsoClient.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

### Additional Findings - When Proxy is used

It also appears that the private feed does NOT have the latest version of a particular package - see log (redacted)

URL: https://REMOVED.pkgs.visualstudio.com/_packaging/00000a00-ef00-0e00-0fb0-000bf0bda000/nuget/v3/flat2/specflow/3.1.97/specflow.3.1.97.nupkg'.
```
{"$id":"1","innerException":null,"message":"The resource specflow.3.1.97.nupkg'. for package 'specflow 3.1.97' doesn't exist. Did you mean specflow.3.1.97.nupkg?","typeName":"Microsoft.VisualStudio.Services.NuGet.WebApi.Exceptions.PackageSubresourceNotFoundException, Microsoft.VisualStudio.Services.NuGet.WebApi","typeKey":"PackageSubresourceNotFoundException","errorCode":0,"eventId":3000}
```

However, if I go through Azure DevOps, I can clearly see that the private feed has indeed specflow version 3.1.97.

Is the tooling somehow targeting api.nuget.org to fetch information about a package before it attempts to get it from the private feed?
Please note that in the task I have explicitly specified       `includeNuGetOrg: false`

**Comment by temelj** [comment]
It appears that as part of the DotNetCoreCLI@2 - it does not use the proxy properly.

**Comment by bishal-pdMSFT** [comment]
Duplicate issue
