### ISSUE TITLE
Paralell jobs, race in workspace clean causing failure

### ISSUE THREAD

**Issue by arynaq** [microsoft/azure-pipelines-tasks#13228]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: job

## Environment
Self hosted agent pool. Cannot share details on azure devops org.

## Issue Description
We have a self-hosted agent pool (6 agents) and use multi-stage yaml pipelines.
The first step in our pipeline is a build stage, which used to run 6 jobs, but now runs 7, these jobs have no dependencies so are are assumed to run in paralell.

Each job is responsible for cleaning its workspace to avoid running out of storage on the agent... which triggers a delete call to the to the `_work\{n}\s` folder.

The problem is that since we have 7 jobs, at least two jobs will always run (in paralell) on the same agent on the same `{n}` folder, but since each job has a workspace cleanup both jobs fail as they try to delete a folder that is in use by the other... 

Exception:
```
##[error]The process cannot access the file 'D:\agent1\_work\19\s' because it is being used by another process.
##[debug]System.IO.IOException: The process cannot access the file 'D:\agent1\_work\19\s' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.DirectoryInfo.Delete()
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.DeleteDirectory(IExecutionContext executionContext, String description, String path)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.CreateDirectory(IExecutionContext executionContext, String description, String path, Boolean deleteExisting)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.PrepareDirectory(IExecutionContext executionContext, IList`1 repositories, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
```

### Task logs
Cannot share.
### Error logs
**Job One**
```c#
##[debug]System.IO.IOException: The process cannot access the file 'D:\agent1\_work\19\s' because it is being used by another process.
```

**Job Two**
```c#
##[debug]System.IO.IOException: The process cannot access the file 'D:\agent1\_work\19\s' because it is being used by another process.
```

**Comment by arynaq** [comment]
Actually, this happens regardless. It seems we have no gurantee that the jobs will be distributed evenly to each agent, so with M<=N for M jobs and N agents this still happens as I just confirmed by adding an explicit dependsOn to get a workaround.

Was there a release that broke this?

**Comment by damccorm** [comment]
Hi, this looks like a general service issue, not an issue with a specific task. Please file service issues here - https://developercommunity.visualstudio.com/spaces/21/index.html - this will also allow you to share info directly with Microsoft employees
