### ISSUE TITLE
download fails when passing a variable to a parameter with [error]Value cannot be null. (Parameter 'hashAndAlgorithm')

### ISSUE THREAD

**Issue by jdholbrook81** [microsoft/azure-pipelines-tasks#13266]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPipelineArtifact

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Org: wegmans
Project: DevOps
Build Def: SampleIOSApp
Build Num: 20200710.13

- Agent - Hosted or Private: 
        - If using Hosted agent, provide agent queue name:
Pool: Azure Pipelines, windows-latest image

## Issue Description
I have a pipeline template that contains the DownloadPipelineArtifact task. It's implementation in the template is:

- name: artifact
  type: string
  default: ''

jobs:
- job: install_airwatch_app
  displayName: Install Airwatch App
  pool:
    vmImage: windows-latest
  dependsOn: ${{ parameters.dependsOn }}
  variables:
    - group: ${{ parameters.varGroup }}

  steps:
  - download: airwatch-cmdlets
    artifact: airwatch-cmdlets

  - download: current
    ${{ if eq( parameters.artifact , '') }}:
      artifact: noArtifact
    ${{ if ne( parameters.artifact , '') }}:
      artifact: ${{ parameters.artifact }}
    condition: ne('${{ parameters.artifact }}', '')

If the artifact parameter is hardcoded to a string by the calling pipeline, it succeeds. If the artifact parameter is omitted the download step does not occur which is intended. However if I try to set the parameter using a variable, it fails. Example:

  - stage: NonProd
    jobs:
    - template: pipeline-templates/jobs/install.airwatchApp.yml@airwatch_pipeline_template
      parameters:
        varGroup: Airwatch-Test
        bundlePath: "$(Pipeline.Workspace)/$(artifactName)/AppName*.ipa"
        applicationName: AzDO Testing
        deviceType: Apple
        supportedModelsPath: "$(Pipeline.Workspace)/$(artifactName)/supportedModels.json"
        artifact: $(artifactName)

The artifactName variable is used in other parameters when calling the template and works fine there. It is only the artifact parameter being passed to the download task that has issues. 

### Task logs

Starting: Download
==============================================================================
Task         : Download pipeline artifact
Description  : Download a named artifact from a pipeline to a local path
Version      : 1.2.5
Author       : Microsoft Corporation
Help         : Download a named artifact from a pipeline to a local path
==============================================================================
Download from the specified build: #115563
Download artifact to: D:\a\1/MyMobileApp
##[debug]Dedup parallelism: 192
##[error]Value cannot be null. (Parameter 'hashAndAlgorithm')
##[debug]Processed: ##vso[task.logissue type=error;]Value cannot be null. (Parameter 'hashAndAlgorithm')
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Microsoft.VisualStudio.Services.BlobStore.Common.DedupIdentifier.Create(HashAndAlgorithm hashAndAlgorithm)
   at Microsoft.VisualStudio.Services.BlobStore.Common.DedupIdentifier.Create(String valueIncludingAlgorithm)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.DownloadAsync(AgentTaskPluginExecutionContext context, PipelineArtifactDownloadParameters downloadParameters, DownloadOptions downloadOptions, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: Download

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[error]Value cannot be null. (Parameter 'hashAndAlgorithm')

**Comment by jdholbrook81** [comment]
Resolved. I had to use a template expression variable.
