### ISSUE TITLE
Getting Error " Microsoft.VisualStudio.TestService.VstestAdapter.TestsNotFoundException" while executing TestCases

### ISSUE THREAD

**Issue by samgengiti** [microsoft/azure-pipelines-tasks#13408]
Getting below error while executing testcases in Microsoft Azure.
[ReleaseLogs_57707.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5058392/ReleaseLogs_57707.zip)

Downloading artifacts failed: Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.ArtifactDirectoryCreationFailedException: Failed to create Release artifact directory 'C:\agent\_work\r1\a'. ---> System.UnauthorizedAccessException: Access to the path 'C:\agent\_work\r1\a\USP-SDET-MAIN-REST-BUILD-SELENIUM\USPMain\USP_Automation_UI\bin\Release\IEDriverServer.exe' is denied.
   at System.IO.Win32FileSystem.DeleteFile(String fullPath)
   at System.IO.FileInfo.Delete()
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.<>c__DisplayClass9_1.<DeleteDirectory>b__0(FileSystemInfo item)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseFileSystemManager.EnsureEmptyDirectory(String directoryPath, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.Execute(Action action)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.CreateArtifactsFolder(IExecutionContext executionContext, String artifactsWorkingFolder)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<DownloadArtifacts>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<DownloadArtifactsAndCommitsAsync>d__35.MoveNext()
1 more errors. Click on expand view in the context menu to view complete logs.

Note: Kindly provide solution with screen shots.
![error](https://user-images.githubusercontent.com/69529641/89928788-f75a1c80-dc25-11ea-87d2-172d53a20c3b.png)

**Comment by ds-ms** [comment]
Is this a self hosted agent? If it is, you may need to ensure correct permissions for the relevant folders.

**Comment by ds-ms** [comment]
Closing stale issue; feel free to reopen if this problem still persists.
