### ISSUE TITLE
Publish Test Results is completed but has some exceptions written in the log

### ISSUE THREAD

**Issue by mithsapurva** [microsoft/azure-pipelines-tasks#13475]
On Azure DevOps server, the publish test results task is completed but has following exception written in the logs:

`##[section]Starting: Publish : Client Side Test Results 
==============================================================================
Task         : Publish Test Results
Description  : Publish test results to Azure Pipelines
Version      : 2.153.5
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
==============================================================================
[command]C:\agent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.153.5\modules\TestResultsPublisher.exe @C:\agent\_work\_temp\c04fcd20-e8c8-11ea-b6d4-8358b98362a4.txt
No build level attachments to publish.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsEndpointManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState) in D:\V2.0\A1\_work\56\s\Ta\Tasks\PublishTestResults\PublishTestResultsEndpointManager.cs:line 159
---> (Inner Exception #0) Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.TestLogStoreOnTCMService
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0<---

   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsEndpointManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState) in D:\V2.0\A1\_work\56\s\Ta\Tasks\PublishTestResults\PublishTestResultsEndpointManager.cs:line 159
---> (Inner Exception #0) Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.PublishOnTestLogStoreEnabled
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0<---

   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsEndpointManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState) in D:\V2.0\A1\_work\56\s\Ta\Tasks\PublishTestResults\PublishTestResultsEndpointManager.cs:line 159
---> (Inner Exception #0) Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.TestLogStoreTelemetryDisabledFF
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0<---

   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsEndpointManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState) in D:\V2.0\A1\_work\56\s\Ta\Tasks\PublishTestResults\PublishTestResultsEndpointManager.cs:line 159
---> (Inner Exception #0) Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.TestLogStoreOnTCMService
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0<---

   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.PublishTestResultsEndpointManager.TryGetFeatureFlagStateFromService(FeatureAvailabilityHttpClient featureAvailabilityHttpClient, String FFName, Boolean& featureFlagState) in D:\V2.0\A1\_work\56\s\Ta\Tasks\PublishTestResults\PublishTestResultsEndpointManager.cs:line 159
---> (Inner Exception #0) Microsoft.VisualStudio.Services.Common.VssServiceException: TestManagement.Server.PublishOnTestLogStoreEnabled
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 921
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 867
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 0<---

Publishing test results to test run '289'.`

Why this exception is coming on Azure DevOps server? This same task is working fine on Azure DevOps Services. Is there something different need to be done on Azure DevOps Server for this task?

**Comment by upadhyayap** [comment]
@mithsapurva Could you please upgrade the publish Test result task to the latest version and let me know if this keeps coming

**Comment by fedorbirjukov** [comment]
@upadhyayap How do you upgrade the publish Test result task to the latest version?

I have just upgraded all agents to the latest version, following advice from issue #12426, but that did not help.

**Comment by fedorbirjukov** [comment]
According to [this comment](https://github.com/Microsoft/azure-pipelines-tasks/issues/9660#issuecomment-466398753) in another issue, the only way to update the publish Test result task to the latest version is to update the Azure DevOps Server. Since DevOps Server 2020 was [released yesterday](https://devblogs.microsoft.com/devops/azure-devops-server-2020-rtw-now-available/) you might give that a shot.

**Comment by fedorbirjukov** [comment]
According to [this comment](https://github.com/microsoft/azure-pipelines-tasks/issues/3768#issuecomment-286014710) there is a way to upgrade a built-in task. Didn't try yet.

**Comment by Christ0phH** [comment]
@fedorbirjukov Any Luck? At my organization have now this very same issue popping up. I'll try to update the task to see if that resolves this issue.

**Comment by fedorbirjukov** [comment]
@Christ0phH Didn't try yet/it's still on my todo list.

**Comment by Christ0phH** [comment]
@fedorbirjukov have you resolved the issue with updating the task?

**Comment by praveendvd** [comment]
i used version 1.* and it worked fine ,

```  
steps:
- task: PublishTestResults@1
  displayName: 'Publish Test Results a.xml'
  inputs:
    testResultsFiles: a.xml
    mergeTestResults: true
    testRunTitle: 'Test results'
    platform: Windows
    configuration: 1
  continueOnError: true

```
