### ISSUE TITLE
Publish Test Results contains error message and doesnt show publish Code Coverage

### ISSUE THREAD

**Issue by Hack3l** [microsoft/azure-pipelines-tasks#13536]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Publish Test Results@2

## Environment
- TFS On-Premise Version: Dev17.M153.5
- Agent: Windows_NT Version:  10.0.17763

## Issue Description

Publish Test Results Task is used in a Release Pipeline.
Task succeeds, but error message in log.
Unit Test Runs get importet but Code Coverage does not, even though it is in the attachment.

### Task logs

```
at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<CreateRequestMessageAsync>d__34.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 538
2020-09-11T12:28:23.6997305Z --- End of stack trace from previous location where exception was thrown ---
2020-09-11T12:28:23.6997399Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2020-09-11T12:28:23.6997716Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-09-11T12:28:23.6997767Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 413
2020-09-11T12:28:23.6997805Z    --- End of inner exception stack trace ---
2020-09-11T12:28:23.6997869Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2020-09-11T12:28:23.6997912Z    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2020-09-11T12:28:23.6997958Z    at System.Threading.Tasks.Task`1.get_Result()
2020-09-11T12:28:23.6998008Z    at Microsoft.Azure.Pipelines.TestClient.PublishCodeCoverage.CodeCoverageInvoker.<QueueCodeCoverageMerge>d__2.MoveNext() in D:\V2.0\A1\_work\56\s\Ta\Tasks\PublishCodeCoverage\Merge\CodeCoverageInvoker.cs:line 53
2020-09-11T12:28:23.6998082Z ---> (Inner Exception #0) Microsoft.VisualStudio.Services.WebApi.VssResourceNotFoundException: API resource location 9b3e1ece-c6ab-4fbb-8167-8a32a0c92216 is not registered on [CollectionURL].
2020-09-11T12:28:23.6998140Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<CreateRequestMessageAsync>d__34.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 538
2020-09-11T12:28:23.6998208Z --- End of stack trace from previous location where exception was thrown ---
2020-09-11T12:28:23.6998247Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2020-09-11T12:28:23.6998287Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-09-11T12:28:23.6998498Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext() in D:\V2.0\A1\_work\56\s\Vssf\Client\WebApi\VssHttpClientBase.cs:line 413<---
```

**Comment by DineshChirnanchu** [comment]
@Hack3l ,

Thank you for the details shared.
Could you please set **system debug:true** while running it and share the full logs.

**Comment by DineshChirnanchu** [comment]
@Hack3l 

It would be great if you can share the pipeline definition and detailed logs(system debug: true) that help us to troubleshoot it faster.

**Comment by Hack3l** [comment]
It now shows an error message that code coverage cannot be published in a Releae Pipeline
