### ISSUE TITLE
VSTest Task unable to find custom test logger when testSelector: testPlan

### ISSUE THREAD

**Issue by davidguidali** [microsoft/azure-pipelines-tasks#13542]
**Problem**

I have written a custom logger to log test results in a kusto database. I added the loggers friendly name to my runsettings file like:

`<Logger friendlyName="KustoTestLogger" />`

The assembly of the test logger is located in the same folder as the test container .dll is.

When executing tests via the VSTest task and settng the **testSelector: testAssemblies**, everything works fine, the logger gets executed. 

However, when settings **testSelector: testPlan**, the task fails to find the test selector:

> 2020-09-14T08:51:28.0307526Z ##[debug]ProxyDiscoveryRequest: HandleLogMessage Entered
2020-09-14T08:51:28.0410963Z ##[error]DiscoveryMessage : Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException: Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'KustoTestLogger'.
2020-09-14T08:51:28.0427960Z ##[debug]Processed: ##vso[task.logissue type=error;]DiscoveryMessage : Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException: Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'KustoTestLogger'.
2020-09-14T08:51:28.0431675Z    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.TestLoggerManager.Initialize(String runSettings)
2020-09-14T08:51:28.0432367Z    at Microsoft.VisualStudio.TestPlatform.Client.TestPlatform.CreateDiscoveryRequest(IRequestData requestData, DiscoveryCriteria discoveryCriteria, TestPlatformOptions options)
2020-09-14T08:51:28.0433451Z    at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.DiscoverTests(DiscoveryRequestPayload discoveryPayload, ITestDiscoveryEventsRegistrar discoveryEventsRegistrar, ProtocolConfig protocolConfig)
2020-09-14T08:51:28.0434203Z    at Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient.<>c__DisplayClass24_0.<StartDiscovery>b__0()
2020-09-14T08:51:28.0434876Z ##[debug]ProxyDiscoveryRequest: HandleDiscoveryComplete Entered
2020-09-14T08:51:28.0435330Z ##[debug]ProxyDiscoveryRequest: Dispose Entered
2020-09-14T08:51:28.0435743Z ##[debug]ProxyDiscoveryRequest: Abort Entered

I tried to also set the custom adapter path but this didnt fix the issue (however since the logger is located at the same place as the test container, this shouldn't be required).

I have had a look into your code in this repo, however I am at the point DTAExecutionHost gets called (I couldn't find the source code of this one). Everything looks good so far and I couldn't find the issue, so I am guessing there is maybe something wrong in the execution host?

Or is it not possible to add a custom logger when executing tests with testSelector: testPlan? Do I have to add another custom adapter path?

I execute the tests as container job btw.

**Expected behavior**
I can set the custom logger in the .runsettings file. VSTest task takes the custom logger (as well as the default trx logger) and uses it during test execution. I do not need to add any additional test adapter path if the path to the test logger is the same as the path to the test container.

**Current behavior**
Custom test logger is not found when added to .runsettings file. Tests won't get executed.

**Comment by davidguidali** [comment]
Any updates on this?

**Comment by S121Pradhan** [comment]
@davidguidali Can you please share the .runsettings file as we need to ensure it follows the desired structure for logger:
      <Logger friendlyName="xxx" enabled="True">
        <Configuration>
          <LogFileName>foo.trx</LogFileName>
        </Configuration>
      </Logger>

**Comment by nehsharmMS** [comment]
@davidguidali any update on this?

**Comment by ShreyasRmsft** [comment]
Closing due to no response.
