### ISSUE TITLE
azurermwebappdeplymentv3 version 3.175.3 fails with error code 2148734720

### ISSUE THREAD

**Issue by d-burr** [microsoft/azure-pipelines-tasks#13611]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

** Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: azurermwebappdeplymentv3

## Environment
- Server - Azure Pipelines
- Agent - Private Windows, agent version 2.164.7

## Issue Description

azurermwebappdeplymentv3 version 3.175.3 fails with error code 2148734720. Do you know if this is this an issue with the task or our private agent?

### Task logs
020-09-25T10:35:06.0091140Z ##[section]Starting: Deploy Azure App Service to prod
2020-09-25T10:35:06.0269006Z ==============================================================================
2020-09-25T10:35:06.0269147Z Task         : Azure App Service deploy
2020-09-25T10:35:06.0269241Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2020-09-25T10:35:06.0269347Z Version      : 3.175.3
2020-09-25T10:35:06.0269404Z Author       : Microsoft Corporation
2020-09-25T10:35:06.0269486Z Help         : https://aka.ms/azureappservicetroubleshooting
2020-09-25T10:35:06.0269568Z ==============================================================================
2020-09-25T10:35:06.6592757Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6609480Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6609722Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6610334Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6610499Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6611006Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6611176Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6611669Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6611831Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6612335Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6612494Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6613921Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6614102Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6614671Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6614852Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6615368Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6615514Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6616017Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6616158Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6616658Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6616802Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6617317Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6617458Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6617589Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6617914Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6621052Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6621283Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6621917Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6622097Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6622685Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6622854Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6623453Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6623674Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6624874Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6625079Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:06.6637868Z Got connection details for Azure App Service:'app'
2020-09-25T10:35:10.7503105Z (node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-25T10:35:12.0018228Z [command]"C:\Agents\agent\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.175.3\webdeployment-common\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\Agents\agent\_work\r853\a\app-build\drop\67465.zip' -dest:contentPath='app',ComputerName='https://app.scm:443/msdeploy.axd?site=app',UserName='$app',Password='XX',AuthType='Basic' -skip:Directory=App_Data -allowUntrusted:true -userAgent:VSTS_22dce153-ad2a-4467-bf6f-48dcc3b02806_Release__87_256_1
2020-09-25T10:35:12.0293745Z Error: C:\Agents\agent\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.175.3\webdeployment-common\MSDeploy3.6\msdeploy.exe failed with return code: 2148734720
2020-09-25T10:35:12.0294217Z     at ChildProcess.<anonymous> (C:\Agents\agent\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.175.3\node_modules\vsts-task-lib\toolrunner.js:569:30)
2020-09-25T10:35:12.0294455Z     at emitTwo (events.js:106:13)
2020-09-25T10:35:12.0294580Z     at ChildProcess.emit (events.js:191:7)
2020-09-25T10:35:12.0294730Z     at maybeClose (internal/child_process.js:920:16)
2020-09-25T10:35:12.0294885Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
2020-09-25T10:35:12.0295158Z Retrying to deploy the package.
2020-09-25T10:35:12.0299685Z [command]"C:\Agents\agent\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.175.3\webdeployment-common\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\Agents\agent\_work\r853\a\app-build\drop\67465.zip' -dest:contentPath='app',ComputerName='https://app.scm:443/msdeploy.axd?site=app',UserName='$app',Password='XX',AuthType='Basic' -skip:Directory=App_Data -allowUntrusted:true -userAgent:VSTS_22dce153-ad2a-4467-bf6f-48dcc3b02806_Release__87_256_1
2020-09-25T10:35:12.0538260Z Error: C:\Agents\agent\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.175.3\webdeployment-common\MSDeploy3.6\msdeploy.exe failed with return code: 2148734720
2020-09-25T10:35:12.0538574Z     at ChildProcess.<anonymous> (C:\Agents\agent\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.175.3\node_modules\vsts-task-lib\toolrunner.js:569:30)
2020-09-25T10:35:12.0538949Z     at emitTwo (events.js:106:13)
2020-09-25T10:35:12.0539086Z     at ChildProcess.emit (events.js:191:7)
2020-09-25T10:35:12.0539214Z     at maybeClose (internal/child_process.js:920:16)
2020-09-25T10:35:12.0539343Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
2020-09-25T10:35:12.0539484Z Retrying to deploy the package.
2020-09-25T10:35:12.7449116Z [command]"C:\Agents\agent\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.175.3\webdeployment-common\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\Agents\agent\_work\r853\a\app-build\drop\67465.zip' -dest:contentPath='app',ComputerName='https://app.scm:443/msdeploy.axd?site=app',UserName='$app',Password='XX',AuthType='Basic' -skip:Directory=App_Data -allowUntrusted:true -userAgent:VSTS_22dce153-ad2a-4467-bf6f-48dcc3b02806_Release__87_256_1
2020-09-25T10:35:12.7497671Z ##[error]Failed to deploy web package to App Service.
2020-09-25T10:35:12.7506794Z ##[error]Error: C:\Agents\agent\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.175.3\webdeployment-common\MSDeploy3.6\msdeploy.exe failed with return code: 2148734720
2020-09-25T10:35:14.5315679Z Successfully added release annotation to the Application Insight : app-ai
2020-09-25T10:35:14.7462112Z Successfully updated deployment History at https://app.scm/api/deployments/871601030114519
2020-09-25T10:35:14.7864533Z ##[section]Finishing: Deploy Azure App Service to prod

**Comment by jsuen123** [comment]
Having the same issue. Previous version 3.163.5 was working. After 3.175.3, the issue starts.
Is there a work around?

**Comment by AmrutaKawade** [comment]
@jsuen123 are you also facing this issue on private agent? 
@d-burr can you share .net framework version installed on your agent?

**Comment by jsuen123** [comment]
@AmrutaKawade yes, on private agent. Agent - Windows, agent version: 2.7.41491.993

**Comment by d-burr** [comment]
@AmrutaKawade we are on version 4.7.03062

**Comment by AmrutaKawade** [comment]
@damccorm can you check this?
@d-burr and @jsuen123 can you try installing ".Net Framework 3.5" check if that works as mentioned [here](https://www.benday.com/2018/01/09/how-to-fix-msdeploy-exe-failed-with-return-code-2148734720/)

**Comment by jsuen123** [comment]
@AmrutaKawade I was unable to install .NET Framework 3.5 due to some VM issues. But running in Task Version 4.* worked, so I have switched to 4.*

**Comment by jsuen123** [comment]
@AmrutaKawade Also, do you know why instaling .NET Framework 3.5 could be the solution? It was working prior to task version 3.175.3, it's a bit strange that a newer task version requires an old version of the .NET Framework.

**Comment by AmrutaKawade** [comment]
Its great to hear that you are unblocked. 
Can you run below command in CMD of your machine where agent is installed. It will give you proper error message

`C:\Agents\agent_work_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.175.3\webdeployment-common\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\Agents\agent_work\r853\a\app-build\drop\67465.zip' -dest:contentPath='app',ComputerName='https://app.scm:443/msdeploy.axd?site=app',UserName='$app',Password='XX',AuthType='Basic' -skip:Directory=App_Data -allowUntrusted:true -userAgent:VSTS_22dce153-ad2a-4467-bf6f-48dcc3b02806_Release__87_256_1`

**Comment by d-burr** [comment]
> @AmrutaKawade Also, do you know why instaling .NET Framework 3.5 could be the solution? It was working prior to task version 3.175.3, it's a bit strange that a newer task version requires an old version of the .NET Framework.

@AmrutaKawade I have installed .NET Framework 3.5 on a test agent and it fixes the issue, but I echo the comments above and also ask how come this dependency was introduced on a minor version?

**Comment by AmrutaKawade** [comment]
@d-burr this is not introduced in minor version. msdeploy.exe requires .Net Framework 3.5. But as it was working for you before this without this version of .Net Framework. we need to investigate this further. Can you provide logs for older version of task ?

**Comment by d-burr** [comment]
Ok thanks for that, I was unware of it. Here are the logs (sorry debug wasn't enabled)

2020-09-07T13:41:38.8344901Z ##[section]Starting: Deploy Azure App Service to prod
2020-09-07T13:41:38.8533760Z ==============================================================================
2020-09-07T13:41:38.8533899Z Task         : Azure App Service deploy
2020-09-07T13:41:38.8534010Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2020-09-07T13:41:38.8534104Z Version      : 3.163.5
2020-09-07T13:41:38.8534175Z Author       : Microsoft Corporation
2020-09-07T13:41:38.8534247Z Help         : https://aka.ms/azureappservicetroubleshooting
2020-09-07T13:41:38.8534343Z ==============================================================================
2020-09-07T13:41:39.6523382Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6523852Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6524378Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6524808Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6525100Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6525445Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6525754Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6526038Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6526342Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6526688Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6526989Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6528320Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6528628Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6528989Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6529311Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6529598Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6529899Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6530183Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6530610Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6530881Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6531154Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6531425Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6531726Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6532001Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6532260Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6532546Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6532803Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6533034Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6533245Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6533472Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6533685Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6533909Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6534151Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6534713Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6535023Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:39.6556690Z Got connection details for Azure App Service:'app'
2020-09-07T13:41:44.1064679Z (node:7784) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-07T13:41:45.7449318Z [command]"C:\Agents\agent\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.163.5\node_modules\webdeployment-common\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\Agents\agent\_work\r120\a\app-build\drop\67465.zip' -dest:contentPath='app',ComputerName='https://app.scm:443/msdeploy.axd?site=app',UserName='$app',Password='***',AuthType='Basic' -skip:Directory=App_Data -allowUntrusted:true -userAgent:VSTS_22dce153-ad2a-4467-bf6f-48dcc3b02806_Release__77_226_1
2020-09-07T13:41:46.1226092Z Info: Using ID '2895759d-c167-4ed4-9c72-657e6e570e46' for connections to the remote server.
2020-09-07T13:41:58.2644780Z Total changes: 0 (0 added, 0 deleted, 0 updated, 0 parameters changed, 0 bytes copied)
2020-09-07T13:41:58.2869281Z Successfully deployed web package to App Service.
2020-09-07T13:42:03.3883901Z Successfully added release annotation to the Application Insight : app-ai
2020-09-07T13:42:04.4881840Z Successfully updated deployment History at https://app.scm/api/deployments/771599486123386
2020-09-07T13:42:04.5357215Z ##[section]Finishing: Deploy Azure App Service to prod

**Comment by AmrutaKawade** [comment]
@d-burr can you tell me which Windows OS version you are using?

**Comment by d-burr** [comment]
@AmrutaKawade sorry for the delay. The version is Windows Server 2016 Datacenter version 1607

**Comment by AmrutaKawade** [comment]
As this pipeline was working before and suddenly started failing. Net Framework 3.5 might have removed from your machine. 
I have verified from our side whether task minor version change caused this removal or Windows Server 2016 .Net Framework [Update](https://support.microsoft.com/en-in/help/4576478/kb4576478-cumulative-update-for-net-framework) but none of these has removed it.

I am closing this issue as original issue is resolved and this removal has not happened from our side

You can further debug this on your machine. You can check from setup logs whether there is any event logged for this removal 

![image](https://user-images.githubusercontent.com/65217380/95840917-61945800-0d62-11eb-8d4e-4ef44f08d335.png)
