### ISSUE TITLE
Azure IoTEdge tasks error

### ISSUE THREAD

**Issue by franperezlopez** [microsoft/azure-pipelines-tasks#13641]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureIoTEdgeV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 

- Agent - Hosted or Private: Hosted - ubuntu-18.04
    
## Issue Description

Error when executing any action

### Task logs

```
2020-10-01T09:14:15.1836825Z ##[debug]which 'iotedgedev'
2020-10-01T09:14:15.1837301Z ##[debug]found: '/usr/local/bin/iotedgedev'
2020-10-01T09:14:15.1837734Z ##[debug]which 'iotedgedev'
2020-10-01T09:14:15.1838626Z ##[debug]found: '/usr/local/bin/iotedgedev'
2020-10-01T09:14:15.1839150Z ##[debug]/usr/local/bin/iotedgedev arg: --version
2020-10-01T09:14:15.1839668Z ##[debug]/usr/local/bin/iotedgedev arg: --version
2020-10-01T09:14:15.1840086Z ##[debug]exec tool: /usr/local/bin/iotedgedev
2020-10-01T09:14:15.1840514Z ##[debug]exec tool: /usr/local/bin/iotedgedev
2020-10-01T09:14:15.1840887Z ##[debug]arguments:
2020-10-01T09:14:15.1841201Z ##[debug]arguments:
2020-10-01T09:14:15.1841663Z ##[debug]   --version
2020-10-01T09:14:15.1842062Z ##[debug]   --version
2020-10-01T09:14:15.7157650Z ##[debug]
2020-10-01T09:14:15.7191239Z ##[error]/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
Traceback (most recent call last):
  File "/usr/local/bin/iotedgedev", line 7, in <module>
    from iotedgedev.cli import main
  File "/usr/local/lib/python2.7/dist-packages/iotedgedev/cli.py", line 30, in <module>
    envvars.load()
  File "/usr/local/lib/python2.7/dist-packages/iotedgedev/envvars.py", line 143, in load
    raise ValueError(msg)
ValueError: Environment variables not configured correctly. Run `iotedgedev new` to create a new solution with sample .env file. 

2020-10-01T09:14:15.7206207Z ##[debug]Processed: ##vso[task.issue type=error;]/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.%0A  from cryptography import x509%0ATraceback (most recent call last):%0A  File "/usr/local/bin/iotedgedev", line 7, in <module>%0A    from iotedgedev.cli import main%0A  File "/usr/local/lib/python2.7/dist-packages/iotedgedev/cli.py", line 30, in <module>%0A    envvars.load()%0A  File "/usr/local/lib/python2.7/dist-packages/iotedgedev/envvars.py", line 143, in load%0A    raise ValueError(msg)%0AValueError: Environment variables not configured correctly. Run `iotedgedev new` to create a new solution with sample .env file. %0A
2020-10-01T09:14:15.7208405Z ##[debug]task result: Failed
2020-10-01T09:14:15.7209193Z ##[error]Error: iotedgedev installation failed, see detailed error in debug mode
2020-10-01T09:14:15.7210187Z ##[debug]Processed: ##vso[task.issue type=error;]Error: iotedgedev installation failed, see detailed error in debug mode
```

## Troubleshooting
I already tested using task `UsePythonVersion@0` and executing bash `sudo pip install --upgrade cryptography`

**Comment by oliverchristen** [comment]
We have the same problem. But only since today. Yesterday the error did not occur yet. We are now completely blocked. Is there a workaround?

**Comment by franperezlopez** [comment]
In our case, the culprit was an outdated linux kernel version ... launch `uname -a` and check that the linux kernel version is from this year. We updated the linux version and now is working.

**Comment by oliverchristen** [comment]
With agent image ubuntu-20.04 it works again.

**Comment by ds-ms** [comment]
@marianan / @tameraw / @pprovost could you take a look

**Comment by marianan** [comment]
Per @oliverchristen's comment, the issue no longer reproduces on ubuntu-20.04. @franperezlopez - could you please confirm that switching the agent resolves the issue? We have added to our backlog the action to investigate the behavior on ubuntu-18.04 but I wanted to make sure that you are not blocked.

**Comment by oliverchristen** [comment]
For me it now works again on both agent images ubuntu-18.04 and ubuntu-20.04. Cannot explain why.

**Comment by marianan** [comment]
@ammohant - as repo owner, please close this issue as I don't have permissions to do so.
