### ISSUE TITLE
 KubernetesV1 tasks with logout command hides Kubernetes service connection field

### ISSUE THREAD

**Issue by Gupta-Amrit** [microsoft/azure-pipelines-tasks#13704]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesV1  

## Environment
- Server - Azure Pipelines
    
- Agent -  Hosted Ubuntu 1604

## Issue Description

KubernetesV1 task with Command as **logout** hides the **Kubernetes service connection** field which creates unnecessary confusion. 
In my case, I added two KubernetesV1 tasks, one with login command and another one with logout command. It was working fine until I deleted the existing Kubernetes service connection and created a new one. As only in login command task Kubernetes service connection was visible, I updated only there but started getting below error 

```
##[Error 1]
Exception Message: The pipeline is not valid. Job Phase_1: Step Kubernetes3 input kubernetesServiceEndpoint references service connection 06ffaa89-0a1a-4d5e-a100-b2f375d3534a which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. (type PipelineValidationException)
Exception Stack Trace:    at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.ValidatePipelineProcess(IVssRequestContext requestContext, Guid scopeIdentifier, Int32 definitionId, Guid planId, PipelineEnvironment environment, PipelineProcess pipeline, BuildOptions options) in D:\v2.0\P1\_work\5\s\DistributedTask\Sdk\Server\TaskHub.cs:line 6205
   at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.ValidateProcess(IVssRequestContext requestContext, Guid scopeIdentifier, TaskOrchestrationOwner definition, Guid planId, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions options) in D:\v2.0\P1\_work\5\s\DistributedTask\Sdk\Server\TaskHub.cs:line 6126
   at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.CreatePlan(IVssRequestContext requestContext, Guid scopeIdentifier, Guid planId, String planGroup, PlanTemplateType templateType, Uri artifactUri, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions validationOptions, Guid requestedForId, TaskOrchestrationOwner definitionReference, TaskOrchestrationOwner ownerReference, String pipelineInitializationLog, String pipelineExpandedYaml) in D:\v2.0\P1\_work\5\s\DistributedTask\Sdk\Server\TaskHub.cs:line 344
   at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.RunPlan(IVssRequestContext requestContext, TaskAgentPoolReference pool, Guid scopeIdentifier, Guid planId, String planGroup, PlanTemplateType templateType, Uri artifactUri, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions validationOptions, Guid requestedForId, TaskOrchestrationOwner definitionReference, TaskOrchestrationOwner ownerReference, String pipelineInitializationLog, String pipelineExpandedYaml) in D:\v2.0\P1\_work\5\s\DistributedTask\Sdk\Server\TaskHub.cs:line 1308
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.DistributedTask.PipelineOrchestrator.StartDeployment(AutomationEngineInput input) in D:\v2.0\P1\_work\5\s\ReleaseManagement\Service\ReleaseManagement2\Server\DistributedTask\PipelineOrchestrator.cs:line 77
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.Run(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep deployStep, DeployPhaseSnapshot snapshotToProcess) in D:\v2.0\P1\_work\5\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 222 


```

Upon investigating I found out the KubernetesV1 task with logout command was still using the previous deleted service connection which caused the issue. To fix this, I had to change the command from logout to login and then updating the service connection. 
With hidden Kubernetes service connection field in logout command in KubernetesV1 task, creates a confusion and should be visible like in login command. 

**Below is the screenshot of KubernetesV1 task with login command**
![image](https://user-images.githubusercontent.com/37998182/95970779-f87a1680-0e2d-11eb-9ea9-d3c8dc1c5465.png)

**Below is the screenshot of KubernetesV1 task with logout command**
![image](https://user-images.githubusercontent.com/37998182/95970804-ffa12480-0e2d-11eb-88f1-29624e492a55.png)

**Comment by Gupta-Amrit** [comment]
Raised a PR to fix this issue https://github.com/microsoft/azure-pipelines-tasks/pull/13705
Please review

**Comment by ds-ms** [comment]
Logout doesn't need a kubernetes service connection, it just cleans up the `KUBECONFIG` path. 
From the error it looks like you haven't authorised this pipeline to use the chosen K8s service connection. Here's some documentation: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#use-a-service-connection

**Comment by Gupta-Amrit** [comment]
Hi @ds-ms 
Correctly said Logout command should not require the service connection as it just cleans the KUBECONFIG path but if you see the code https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesV1/task.json#L26
its just gets hide for the user. This creates problem when someone clones kubectl task where service connection is getting used(ex- login) and then changing the command to logout. In this case, the logout command also be using the kubernetes service connection as the value was already set in login command.

You can follow the below steps to replicate the issue : 
1) add a kubectl task with login command and and select the kubernetes service connection
2) clone the above kubectl login command and change the command here to logout
3) delete the kubernetes service connection and crate a new one
4) now when you see the both the tasks it will only ask to update the kubernetes service connection in login command and not in the logout command reason being its hidden from the user but if you save the release pipeline it will start throwing the error mentioned in the description of this ticket.

so, the quick fix(https://github.com/microsoft/azure-pipelines-tasks/pull/13705) could be to make that kubernetes service connection visible to user to avoid unnecessary confusion

**Comment by ds-ms** [comment]
Aah! I see your point now. But given that you're forced to update all the tasks which use this K8s connection, I believe it's logically expected to update this task as well. 

Your fix will become a breaking change for existing users. If you change the visibility of this group for `logout`. It becomes a required input  for all the existing customers. This would also force the users to always supply a k8s connection when you want to leverage `logout`.

I don't think this is a good fix. 

Side Note: Have you considered moving to YAML pipelines? This editor experience is considered Classic

**Comment by ds-ms** [comment]
Closing this issue. Feel free to reopen this if you don't agree with my solution 😄
