### ISSUE TITLE
Robocopy.exe command not found. cmd.exe command not found

### ISSUE THREAD

**Issue by clifmo** [microsoft/azure-pipelines-tasks#13757]
**Question**  
*Type*: What would cause 'robocopy' command to not be recognized when using this Windows machine file copy?

**Enter Task Name**: Windows machine file copy

## Environment
Azure DevOps Server 2019 Version Dev17.M153.5

- Agent - Hosted or Private: 
Private - v2.166.4
## Issue Description

Robocopy not found.
The term 'robocopy' is not recognized as the name of a cmdlet, function, script file, or operable program. 

### Task logs
```
2020-10-22T14:59:11.3770380Z ==============================================================================
2020-10-22T14:59:11.3770880Z Task         : Windows machine file copy
2020-10-22T14:59:11.3771214Z Description  : Copy files to remote Windows machines
2020-10-22T14:59:11.3771810Z Version      : 2.1.11
2020-10-22T14:59:11.3772108Z Author       : Microsoft Corporation
2020-10-22T14:59:11.3772466Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy
2020-10-22T14:59:11.3772735Z ==============================================================================
2020-10-22T14:59:12.3452116Z ##[debug]VstsTaskSdk 0.8.2 commit 
2020-10-22T14:59:12.4798230Z ##[debug]Entering D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\WindowsMachineFileCopy.ps1.
2020-10-22T14:59:12.5080762Z ##[debug]INPUT_MACHINENAMES: '<HOSTNAME>'
2020-10-22T14:59:12.5117721Z ##[debug]INPUT_ADMINUSERNAME: '<SVCACCNT>'
2020-10-22T14:59:12.5212537Z ##[debug]INPUT_ADMINPASSWORD: '***'
2020-10-22T14:59:12.5219224Z ##[debug]INPUT_SOURCEPATH: 'D:\TFSBuildAgent\_work\r56\a\<PATH>'
2020-10-22T14:59:12.5234607Z ##[debug]INPUT_TARGETPATH: ...
2020-10-22T14:59:12.5269304Z ##[debug]INPUT_ADDITIONALARGUMENTS (empty)
2020-10-22T14:59:12.5355118Z ##[debug]INPUT_CLEANTARGETBEFORECOPY: 'false'
2020-10-22T14:59:12.5369532Z ##[debug]INPUT_COPYFILESINPARALLEL: 'true'
2020-10-22T14:59:12.5402508Z ##[debug]Loading resource strings from: D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11/Task.json
2020-10-22T14:59:12.5662714Z ##[debug]Loaded 12 strings.
2020-10-22T14:59:12.5731900Z ##[debug]SYSTEM_CULTURE: 'en-US'
2020-10-22T14:59:12.5768082Z ##[debug]Loading resource strings from: D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\Strings\resources.resjson\en-US\resources.resjson
2020-10-22T14:59:12.6032990Z ##[debug]Loaded 12 strings.
2020-10-22T14:59:12.7651393Z Copy started for - <HOSTNAME>
2020-10-22T14:59:12.7830347Z ##[debug]Loading module from path 'D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'.
2020-10-22T14:59:12.7866702Z ##[debug]Importing function 'Assert-VstsPath'.
2020-10-22T14:59:12.7889687Z ##[debug]Importing function 'Find-VstsFiles'.
2020-10-22T14:59:12.7912085Z ##[debug]Importing function 'Find-VstsMatch'.
2020-10-22T14:59:12.7935242Z ##[debug]Importing function 'Get-VstsAssemblyReference'.
2020-10-22T14:59:12.7976902Z ##[debug]Importing function 'Get-VstsEndpoint'.
2020-10-22T14:59:12.7980132Z ##[debug]Importing function 'Get-VstsInput'.
2020-10-22T14:59:12.8004974Z ##[debug]Importing function 'Get-VstsLocString'.
2020-10-22T14:59:12.8027651Z ##[debug]Importing function 'Get-VstsTaskVariable'.
2020-10-22T14:59:12.8050753Z ##[debug]Importing function 'Get-VstsTaskVariableInfo'.
2020-10-22T14:59:12.8072050Z ##[debug]Importing function 'Get-VstsTfsClientCredentials'.
2020-10-22T14:59:12.8093349Z ##[debug]Importing function 'Get-VstsTfsService'.
2020-10-22T14:59:12.8118300Z ##[debug]Importing function 'Get-VstsVssCredentials'.
2020-10-22T14:59:12.8140581Z ##[debug]Importing function 'Get-VstsVssHttpClient'.
2020-10-22T14:59:12.8164777Z ##[debug]Importing function 'Import-VstsLocStrings'.
2020-10-22T14:59:12.8186389Z ##[debug]Importing function 'Invoke-VstsTool'.
2020-10-22T14:59:12.9074923Z ##[debug]Importing function 'New-VstsFindOptions'.
2020-10-22T14:59:12.9094505Z ##[debug]Importing function 'New-VstsMatchOptions'.
2020-10-22T14:59:12.9131302Z ##[debug]Importing function 'Out-VstsDefault'.
2020-10-22T14:59:12.9141261Z ##[debug]Importing function 'Select-VstsMatch'.
2020-10-22T14:59:12.9161565Z ##[debug]Importing function 'Set-VstsTaskVariable'.
2020-10-22T14:59:12.9190829Z ##[debug]Importing function 'Trace-VstsEnteringInvocation'.
2020-10-22T14:59:12.9211174Z ##[debug]Importing function 'Trace-VstsLeavingInvocation'.
2020-10-22T14:59:12.9237955Z ##[debug]Importing function 'Trace-VstsPath'.
2020-10-22T14:59:12.9263812Z ##[debug]Importing function 'Write-VstsAddAttachment'.
2020-10-22T14:59:12.9286384Z ##[debug]Importing function 'Write-VstsAddBuildTag'.
2020-10-22T14:59:12.9306653Z ##[debug]Importing function 'Write-VstsAssociateArtifact'.
2020-10-22T14:59:12.9327309Z ##[debug]Importing function 'Write-VstsLogDetail'.
2020-10-22T14:59:12.9347501Z ##[debug]Importing function 'Write-VstsSetProgress'.
2020-10-22T14:59:12.9367739Z ##[debug]Importing function 'Write-VstsSetResult'.
2020-10-22T14:59:12.9392553Z ##[debug]Importing function 'Write-VstsSetSecret'.
2020-10-22T14:59:12.9412605Z ##[debug]Importing function 'Write-VstsSetVariable'.
2020-10-22T14:59:12.9433350Z ##[debug]Importing function 'Write-VstsTaskDebug'.
2020-10-22T14:59:12.9453734Z ##[debug]Importing function 'Write-VstsTaskError'.
2020-10-22T14:59:12.9477843Z ##[debug]Importing function 'Write-VstsTaskVerbose'.
2020-10-22T14:59:12.9497213Z ##[debug]Importing function 'Write-VstsTaskWarning'.
2020-10-22T14:59:12.9516343Z ##[debug]Importing function 'Write-VstsUpdateBuildNumber'.
2020-10-22T14:59:12.9538078Z ##[debug]Importing function 'Write-VstsUploadArtifact'.
2020-10-22T14:59:12.9559440Z ##[debug]Importing function 'Write-VstsUploadBuildLog'.
2020-10-22T14:59:12.9585189Z ##[debug]Loading resource strings from: D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11/Task.json
2020-10-22T14:59:12.9631564Z ##[debug]Loaded 12 strings.
2020-10-22T14:59:12.9663415Z ##[debug]SYSTEM_CULTURE: 'en-US'
2020-10-22T14:59:12.9689086Z ##[debug]Loading resource strings from: D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\Strings\resources.resjson\en-US\resources.resjson
2020-10-22T14:59:12.9745551Z ##[debug]Loaded 12 strings.
2020-10-22T14:59:12.9826868Z ##[debug]Entering script RobocopyJob.ps1
2020-10-22T14:59:12.9853458Z ##[debug]fqdn = <HOSTNAME>
2020-10-22T14:59:12.9877851Z ##[debug]sourcePath = D:\TFSBuildAgent\_work\r56\a\<PATH>
2020-10-22T14:59:12.9899996Z ##[debug]targetPath = ...
2020-10-22T14:59:12.9945878Z ##[debug]credential = System.Net.NetworkCredential
2020-10-22T14:59:12.9966987Z ##[debug]cleanTargetBeforeCopy = false
2020-10-22T14:59:12.9988631Z ##[debug]additionalArguments = 
2020-10-22T14:59:13.0342811Z ##[debug]machine share= \\<HOSTNAME>
2020-10-22T14:59:13.0364748Z ##[debug]destination network path= \\<HOSTNAME>\<PATH>
2020-10-22T14:59:13.0455642Z ##[debug]Creating path to directory: \\<HOSTNAME>\<PATH>
2020-10-22T14:59:13.2768909Z VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM 
2020-10-22T14:59:13.2779859Z Win32_LogicalDisk WHERE DeviceId='<DEVICE-ID>','queryDialect' = WQL,'namespaceName' = root\cimv2'.
2020-10-22T14:59:13.2952289Z VERBOSE: Operation 'Query CimInstances' complete.
2020-10-22T14:59:13.3087560Z VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM 
2020-10-22T14:59:13.3089711Z Win32_LogicalDisk WHERE DeviceId='t$','queryDialect' = WQL,'namespaceName' = root\cimv2'.
2020-10-22T14:59:13.3126780Z VERBOSE: Operation 'Query CimInstances' complete.
2020-10-22T14:59:13.3212108Z VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM 
2020-10-22T14:59:13.3221325Z Win32_LogicalDisk WHERE DeviceId='<DEVICE-ID>','queryDialect' = WQL,'namespaceName' = root\cimv2'.
2020-10-22T14:59:13.3227324Z VERBOSE: Operation 'Query CimInstances' complete.
2020-10-22T14:59:13.3251163Z VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM 
2020-10-22T14:59:13.3266987Z Win32_LogicalDisk WHERE DeviceId='t$','queryDialect' = WQL,'namespaceName' = root\cimv2'.
2020-10-22T14:59:13.3277317Z VERBOSE: Operation 'Query CimInstances' complete.
2020-10-22T14:59:13.3389734Z 
2020-10-22T14:59:13.3401262Z Name           Used (GB)     Free (GB) Provider      Root                                               CurrentLocation
2020-10-22T14:59:13.3405042Z ----           ---------     --------- --------      ----                                               ---------------
2020-10-22T14:59:13.3411542Z WFCPSDrive                             FileSystem    \\<HOSTNAME>\t...                               
2020-10-22T14:59:13.3437206Z ##[debug]Found parent path
2020-10-22T14:59:13.3550284Z ##[debug]Caught exception: The path is not of a legal form..Exception.Message
2020-10-22T14:59:13.3595780Z ##[debug]Check if parent path exists: \\<HOSTNAME>\<PATH>
2020-10-22T14:59:13.3736130Z VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM 
2020-10-22T14:59:13.3739494Z Win32_LogicalDisk WHERE DeviceId='<DEVICE-ID>','queryDialect' = WQL,'namespaceName' = root\cimv2'.
2020-10-22T14:59:13.3761356Z VERBOSE: Operation 'Query CimInstances' complete.
2020-10-22T14:59:13.3778304Z VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM 
2020-10-22T14:59:13.3779540Z Win32_LogicalDisk WHERE DeviceId='t$','queryDialect' = WQL,'namespaceName' = root\cimv2'.
2020-10-22T14:59:13.3815255Z VERBOSE: Operation 'Query CimInstances' complete.
2020-10-22T14:59:13.3847757Z VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM 
2020-10-22T14:59:13.3849209Z Win32_LogicalDisk WHERE DeviceId='<DEVICE-ID>','queryDialect' = WQL,'namespaceName' = root\cimv2'.
2020-10-22T14:59:13.3875557Z VERBOSE: Operation 'Query CimInstances' complete.
2020-10-22T14:59:13.3892150Z VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM 
2020-10-22T14:59:13.3894070Z Win32_LogicalDisk WHERE DeviceId='t$','queryDialect' = WQL,'namespaceName' = root\cimv2'.
2020-10-22T14:59:13.3929213Z VERBOSE: Operation 'Query CimInstances' complete.
2020-10-22T14:59:13.3954777Z WFCPSDrive                             FileSystem    \\<HOSTNAME>\t...                               
2020-10-22T14:59:14.6954913Z ##[debug]Attempting to remove PSDrive 'WFCPSDrive'
2020-10-22T14:59:14.7014096Z ##[debug]RemoteSharePath: \\<HOSTNAME>\<PATH>
2020-10-22T14:59:14.7073299Z ##[debug][command] cmd.exe /c net use /delete "\\<HOSTNAME>\<PATH>" "2>NUL"
2020-10-22T14:59:14.7720833Z ##[debug]Unable to remove path: \\<HOSTNAME>\<PATH>. Ignoring error message: The term 'cmd.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-10-22T14:59:14.7846849Z ##[debug]System.Management.Automation.CommandNotFoundException: The term 'robocopy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-10-22T14:59:14.7869374Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2020-10-22T14:59:14.7945391Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2020-10-22T14:59:14.7970456Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interpre tedFrame frame)
2020-10-22T14:59:14.8088269Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-10-22T14:59:14.8161373Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2020-10-22T14:59:14.8163971Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2020-10-22T14:59:14.8176199Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
2020-10-22T14:59:14.8197946Z ##[debug]   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
2020-10-22T14:59:14.8229835Z ##[debug]   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
2020-10-22T14:59:14.8271826Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
2020-10-22T14:59:14.8336625Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
2020-10-22T14:59:14.8355313Z ##[debug]   at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
2020-10-22T14:59:14.8399271Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2020-10-22T14:59:14.8445646Z ##[debug]Leaving D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\WindowsMachineFileCopy.ps1.
2020-10-22T14:59:14.8508198Z ##[debug]Caught exception from task script.
2020-10-22T14:59:14.8568602Z ##[debug]Error record:
2020-10-22T14:59:14.9467992Z ##[debug]Invoke-Expression : The term 'robocopy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-10-22T14:59:14.9482959Z ##[debug]At D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\RoboCopyJob.ps1:241 char:9
2020-10-22T14:59:14.9496598Z ##[debug]+         Invoke-Expression $command
2020-10-22T14:59:14.9521390Z ##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-10-22T14:59:14.9526192Z ##[debug]    + CategoryInfo          : ObjectNotFound: (robocopy:String) [Invoke-Expression], CommandNotFoundException
2020-10-22T14:59:14.9549977Z ##[debug]    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
2020-10-22T14:59:14.9571131Z ##[debug] 
2020-10-22T14:59:14.9586607Z ##[debug]Script stack trace:
2020-10-22T14:59:14.9624686Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-10-22T14:59:14.9655252Z ##[debug]at <ScriptBlock>, D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\RoboCopyJob.ps1: line 241
2020-10-22T14:59:14.9671898Z ##[debug]at <ScriptBlock>, D:\TFSBuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\WindowsMachineFileCopy.ps1: line 55
2020-10-22T14:59:14.9681224Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-10-22T14:59:14.9702583Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-10-22T14:59:15.2192002Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-10-22T14:59:15.2192501Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-10-22T14:59:15.2192950Z ##[debug]Exception:
2020-10-22T14:59:15.2193549Z ##[debug]System.Management.Automation.CommandNotFoundException: The term 'robocopy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-10-22T14:59:15.2194304Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2020-10-22T14:59:15.2194864Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2020-10-22T14:59:15.2195312Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-10-22T14:59:15.2195807Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-10-22T14:59:15.2196298Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2020-10-22T14:59:15.2196856Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2020-10-22T14:59:15.2197579Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
2020-10-22T14:59:15.2198385Z ##[debug]   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
2020-10-22T14:59:15.2198769Z ##[debug]   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
2020-10-22T14:59:15.2199444Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
2020-10-22T14:59:15.2200198Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
2020-10-22T14:59:15.2202024Z ##[debug]   at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
2020-10-22T14:59:15.2202333Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2020-10-22T14:59:15.2226705Z ##[error]The term 'robocopy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-10-22T14:59:15.2234853Z ##[debug]Processed: ##vso[task.logissue type=error]The term 'robocopy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-10-22T14:59:15.2242188Z ##[debug]Processed: ##vso[task.complete result=Failed]
```

**Comment by AmrutaKawade** [comment]
are you running this on hosted agent or private agent?

**Comment by AmrutaKawade** [comment]
@clifmo sorry i did not check your description thoroughly. you had mentioned its private agent. can you check C:\Windows\System32 is added to your path on private agent. Ref https://stackoverflow.com/questions/51856618/vsts-windows-machine-file-copy-robocopy-not-found

**Comment by clifmo** [comment]
Thank you. I am almost certain I confirmed this but will check again. 

It's definitely agent configuration, since I resolve this issue by using other agents.

Will update soon.

**Comment by AmrutaKawade** [comment]
@clifmo did you get a chance to verify? can we close this? as this is not related to task but agent configuration and you found the solution.

**Comment by clifmo** [comment]
I haven't but please close. I worked around it. Ty
