### ISSUE TITLE
Delete files task v1.177.0 fails with "supported task execution handler was not found."

### ISSUE THREAD

**Issue by ahmedilyasms** [microsoft/azure-pipelines-tasks#13761]
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: Delete files

list here (V# not needed):  1.177.0

## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version: 2.164.3
    
- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version:
      Agent version: 2.164.3 and OS is Windows Server 2019

## Issue Description

After the task got upgraded from 1.76.0 to 1.77.0, looks like it started to error on delete files.
This is the error being shown:

2020-10-23T13:55:10.7183647Z ##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.
2020-10-23T13:55:10.7192208Z ##[debug]System.Exception: A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2020-10-23T13:55:10.7193307Z ##[section]Finishing: Delete unattend file

**Comment by damccorm** [comment]
Hey, we are working on a fix to this right now - in the meantime, upgrading your agents to the most recent version should fix this

**Comment by damccorm** [comment]
This should be fixed now!
