### ISSUE TITLE
The task doesn't work after upgrading to the 1.177.0 version

### ISSUE THREAD

**Issue by jeisonmp** [microsoft/azure-pipelines-tasks#13767]
## Note  
The DeleteFiles@01 task doesn't work after upgrading to the 1.176.0 -> 1.177.0 version. The same issue occurs if we change DeleteFiles@01 to CommandLine.

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DeleteFiles@01

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version:  Ubuntu / 2.168.2

## Issue Description

![image](https://user-images.githubusercontent.com/9480995/97064244-e2313080-157a-11eb-86d2-2c84fba60ee3.png)
![image](https://user-images.githubusercontent.com/9480995/97064252-fc6b0e80-157a-11eb-9c87-5e0954533ed7.png)

## Task logs

2020-10-24T00:50:28.6542830Z ##[debug]Evaluating condition for step: 'Remove unneeded files'
2020-10-24T00:50:28.6551653Z ##[debug]Evaluating: SucceededNode()
2020-10-24T00:50:28.6552119Z ##[debug]Evaluating SucceededNode:
2020-10-24T00:50:28.6565543Z ##[debug]=> True
2020-10-24T00:50:28.6573739Z ##[debug]Result: True
2020-10-24T00:50:28.6625125Z ##[section]Starting: Remove unneeded files
2020-10-24T00:50:28.6846007Z ==============================================================================
2020-10-24T00:50:28.6846725Z Task         : Delete files
2020-10-24T00:50:28.6847298Z Description  : Delete folders, or files matching a pattern
2020-10-24T00:50:28.6847589Z Version      : 1.177.1
2020-10-24T00:50:28.6848092Z Author       : Microsoft Corporation
2020-10-24T00:50:28.6848712Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/delete-files
2020-10-24T00:50:28.6849084Z ==============================================================================
2020-10-24T00:50:28.7027511Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
2020-10-24T00:50:28.7041965Z ##[debug]System.InvalidOperationException: The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2020-10-24T00:50:28.7045209Z ##[section]Finishing: Remove unneeded files

**Comment by mztse** [comment]
@jeisonmp Similar issue on my side seems can be resolved by upgrading the private agent to latest 2.175.2. Can you try the same?

**Comment by damccorm** [comment]
@jeisonmp, @mzts is right, upgrading agents should fix this issue. In theory, this upgrade should've happened automatically - do you have agent auto-upgrades disabled for this pool? You can see the auto-upgrade setting via "Org settings"=>"Agent Pools"=><your pool>=>"Settings"

**Comment by damccorm** [comment]
Closing due to inactivity and since a workaround has been added
