### ISSUE TITLE
Azure CLI task fails to login with MSI Service Connection

### ISSUE THREAD

**Issue by lagalbra** [microsoft/azure-pipelines-tasks#13787]
**Question, Bug, or Feature?**  
Bug

*Type*: Azure CLI

**Enter Task Name**: AzureCLIV2  

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/msazure/One/_releaseDefinition?definitionId=1812&_a=definition-tasks&environmentId=8365
Failing Release ID: 3173580, environment ID 9885690

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

    - If using private agent, provide the OS of the machine running the agent and the agent version: Ubuntu 16.04, 2.175.2

## Issue Description

Agent phase -> Azure CLI step fails to log in with the identity from a brand-new Service Connection. The Service Connection was created with subscription-level scope

### Error logs
```
[command]/usr/bin/az cloud set -n AzureCloud
[command]/usr/bin/az login --identity
CLIInternalError: The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
##[error]Error Code: [1]
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 136, in login
    return profile.find_subscriptions_in_vm_with_msi(username, allow_no_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 346, in find_subscriptions_in_vm_with_msi
    msi_creds = MSIAuthenticationWrapper(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 600, in set_token
    token_entry = self._vm_msi.get_token(self.resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 649, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 704, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError
To open an issue, please run: 'az feedback'
##[error]Error: Azure login failed using Managed Service Identity
##[error]Script failed with error: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
```

**Comment by lagalbra** [comment]
@bishal-pdMSFT Ping!

FYI I have removed the step from our Release for now, but can add it back if needed for further debugging.

**Comment by anuragc617** [comment]
@lagalbra sorry for late reply. Yes, I'm able to repro this. It looks like a bug in Azure CLI itself, not in a task. I am looking into it if we can fix in task. I will come back to you with more information.

**Comment by anuragc617** [comment]
@lagalbra For using managed identity, you will need to create it and then install on the agent VM. Creation of service connection doesn't create any MI. Have you completed this step? If not you can follow this [doc](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) for setting up MI on VM
Also, as mentioned you are using Hosted agent, here you won't be able to install MSI. You will need to create VM on azure portal and then use that VM as agent.

**Comment by lagalbra** [comment]
@anuragc617 Thank you for the clarification; I will look into changing our Release to use VM instead of Hosted agent.
Closing this thread as I now have the references I need

**Comment by cceeci99** [comment]
I have created an Azure VM and enabled System Assigned Managed Identity, also i registered it as Agent and it's online.
But when i run the pipeline i get the same error... do i need to create another managed identity and assign it on the VM? or i need to add some RBAC? 
I thought that the system assigned managed identity allows the connection of the vm
Any help?
