### ISSUE TITLE
BUG: Missing credentials in WindowsMachineFileCopyV2 task?

### ISSUE THREAD

**Issue by Eneuman** [microsoft/azure-pipelines-tasks#13867]
This is a bug report

It seems like the credentials are missing from the Test-Path check in the WindowsMachineFileCopyV2 task.

https://github.com/microsoft/azure-pipelines-tasks/blob/178e687dcc35c116d867c2f1eb3b96e76981a6cd/Tasks/WindowsMachineFileCopyV2/Utility.ps1#L26

Lets say you have a onprem Deployment Server D1 and it runs as user "A".
It has a task to copy files from server S1 to S2. User "A" has no access to the network share on S1 or S2.
When setting up the task you enter the credentials to use.

When the task gets run, it will crash since user A has not access to the source path, and no error handling is being done.

```
2020-11-09T14:53:35.1925326Z ##[debug]System.UnauthorizedAccessException: Access is denied ---> System.ComponentModel.Win32Exception: Access is denied
2020-11-09T14:53:35.1938255Z ##[debug]   --- End of inner exception stack trace ---
2020-11-09T14:53:35.1951598Z ##[debug]   at Microsoft.PowerShell.Commands.FileSystemProvider.ItemExists(String path, ErrorRecord& error)
2020-11-09T14:53:35.1981419Z ##[debug]Leaving E:\Appl\Agents\XXX\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\WindowsMachineFileCopy.ps1.
2020-11-09T14:53:35.2061283Z ##[debug]Caught exception from task script.
2020-11-09T14:53:35.2274283Z ##[debug]Error record:
2020-11-09T14:53:35.2659185Z ##[debug]Test-Path : Access is denied
2020-11-09T14:53:35.2672952Z ##[debug]At E:\Appl\Agents\A1-Platina\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\Utility.ps1:26 char:14
2020-11-09T14:53:35.2686803Z ##[debug]+     if(-not (Test-Path -LiteralPath $value))
2020-11-09T14:53:35.2699815Z ##[debug]+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-11-09T14:53:35.2713205Z ##[debug]    + CategoryInfo          : PermissionDenied: (\\nc11464.rsvc.... Components    \Bin:String) [Test-Path], UnauthorizedAccessException
2020-11-09T14:53:35.2726674Z ##[debug]    + FullyQualifiedErrorId : ItemExistsUnauthorizedAccessError,Microsoft.Powe    rShell.Commands.TestPathCommand
2020-11-09T14:53:35.2741228Z ##[debug] 
2020-11-09T14:53:35.2764972Z ##[debug]Script stack trace:
2020-11-09T14:53:35.2806105Z ##[debug]at Validate-SourcePath, E:\Appl\Agents\XXX\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\Utility.ps1: line 26
2020-11-09T14:53:35.2819877Z ##[debug]at <ScriptBlock>, E:\Appl\Agents\XXX\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.11\WindowsMachineFileCopy.ps1: line 35
2020-11-09T14:53:35.2833989Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-11-09T14:53:35.3641401Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-11-09T14:53:35.3642696Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-11-09T14:53:35.3643236Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-11-09T14:53:35.3643683Z ##[debug]Exception:
2020-11-09T14:53:35.3644121Z ##[debug]System.UnauthorizedAccessException: Access is denied ---> System.ComponentModel.Win32Exception: Access is denied
2020-11-09T14:53:35.3644545Z ##[debug]   --- End of inner exception stack trace ---
2020-11-09T14:53:35.3644974Z ##[debug]   at Microsoft.PowerShell.Commands.FileSystemProvider.ItemExists(String path, ErrorRecord& error)
2020-11-09T14:53:35.3829899Z ##[error]Access is denied
2020-11-09T14:53:35.3838743Z ##[debug]Processed: ##vso[task.logissue type=error]Access is denied
2020-11-09T14:53:35.3856725Z ##[debug]Processed: ##vso[task.complete result=Failed]
```

Access denied exceptions should be handled gracefully and testing if source path exists should use the supplied credentials.

**Comment by 20shivangi** [comment]
@Eneuman  It is assumed that agent running has permission on the sourcePath so credentials need not be passed while validating the sourcePath. However, we pass machineName when validating destination path as can be seen [here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/WindowsMachineFileCopyV2/WindowsMachineFileCopy.ps1#L36)

**Comment by 20shivangi** [comment]
Any update here?

**Comment by Eneuman** [comment]
@20shivangi 

Hi

The problem we have is that the release agent on machine A tries to copy files from Machine B to Machine C (using UNC paths).
The relase agent account does not have permissions to machine B or C, and we though the account information, entered into the task, would be used to access both source and destination, but as I understand that is not the case?

**Comment by 20shivangi** [comment]
@Eneuman Yeah we are not supporting this scenario.  In or task it is assumed that agent running has permission on the sourcePath so credentials are not passed
Please feel free to re-open if you are facing any issue.
