### ISSUE TITLE
HELMDEPLOY1_HELMOUTPUT exceeds maximum length for lint command

### ISSUE THREAD

**Issue by agilekevin** [microsoft/azure-pipelines-tasks#13999]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Bug*: helm deploy `lint` command fail due to variable overrun when writing output to `helmoutput` variable.
`template` and `update` commands are still successful

## Environment
- Server - Azure Pipelines 

- Agent - Hosted windows latest and ubuntu-latest

## Issue Description

When executing HelmDeploy task with command  `lint`, the task fails with an error (linux) or passes with a warning (windows) due to text being written to a variable that cannot hold its length.

It seems that the entire helm output is being written to a variable, based on line 167 of helm.ts:
```typescript
  tl.setVariable("helmOutput", execResult.stdout);
```

Here is the pipeline.yaml:
```yaml
trigger:
  branches:
    include:
      - '*'

stages:
  - stage: Build
    displayName: Validate and Lint Helm Charts
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          #Generate the templates before linting, because their error message for missing values are more helpful
          - task: HelmDeploy@0
            displayName: Helm Template
            inputs:
              ConnectionType: Kubernetes Service Connection
              kubernetesServiceEndpoint: k8s-endpoint
              command: template
              arguments: multipass ./multi-helm -f $(Build.SourcesDirectory)/multi-helm/spec/LINT/values.yaml                        
          - task: HelmDeploy@0
            displayName: Helm Lint
            inputs:
              ConnectionType: Kubernetes Service Connection
              kubernetesServiceEndpoint: k8s-endpoint
              command: lint
              arguments: ./multi-helm -f $(Build.SourcesDirectory)/multi-helm/spec/LINT/values.yaml
```

The "real" helm deploy is not in this file, but it seems to pass.

### Task logs
```
##[debug]Evaluating condition for step: 'Helm Lint'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Helm Lint
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.178.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
##[debug]Using node path: /home/vsts/agents/2.177.1/externals/node/bin/node
##[error]Argument list too long
##[debug]System.ComponentModel.Win32Exception (7): Argument list too long
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
Finishing: Helm Lint
```
with windows:
```
2020-12-01T01:35:49.2293085Z ##[debug]Evaluating condition for step: 'Helm Lint'
2020-12-01T01:35:49.2295033Z ##[debug]Evaluating: SucceededNode()
2020-12-01T01:35:49.2295660Z ##[debug]Evaluating SucceededNode:
2020-12-01T01:35:49.2297636Z ##[debug]=> True
2020-12-01T01:35:49.2298309Z ##[debug]Result: True
2020-12-01T01:35:49.2300307Z ##[section]Starting: Helm Lint
2020-12-01T01:35:49.2490676Z ==============================================================================
2020-12-01T01:35:49.2491088Z Task         : Package and deploy Helm charts
2020-12-01T01:35:49.2491500Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
2020-12-01T01:35:49.2491878Z Version      : 0.178.0
2020-12-01T01:35:49.2492147Z Author       : Microsoft Corporation
2020-12-01T01:35:49.2492438Z Help         : https://aka.ms/azpipes-helm-tsg
2020-12-01T01:35:49.2492792Z ==============================================================================
2020-12-01T01:35:49.2901094Z ##[warning]Environment variable 'HELMDEPLOY1_HELMOUTPUT' exceeds the maximum supported length. Environment variable length: 137522 , Maximum supported length: 32766
2020-12-01T01:35:49.2990050Z ##[debug]Using node path: C:\agents\2.177.1\externals\node\bin\node.exe
2020-12-01T01:35:49.5937882Z ##[debug]agent.TempDirectory=D:\a\_temp
2020-12-01T01:35:49.5975892Z ##[debug]loading inputs and endpoints
2020-12-01T01:35:49.6006782Z ##[debug]loading ENDPOINT_AUTH_160a0274-f0a2-4603-81cf-bb745a703015
2020-12-01T01:35:49.6021726Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_160a0274-f0a2-4603-81cf-bb745a703015_APITOKEN
2020-12-01T01:35:49.6027289Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_160a0274-f0a2-4603-81cf-bb745a703015_AZUREENVIRONMENT
2020-12-01T01:35:49.6031527Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_160a0274-f0a2-4603-81cf-bb745a703015_AZURETENANTID
2020-12-01T01:35:49.6033847Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_160a0274-f0a2-4603-81cf-bb745a703015_ROLEBINDINGNAME
2020-12-01T01:35:49.6037577Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_160a0274-f0a2-4603-81cf-bb745a703015_SECRETNAME
2020-12-01T01:35:49.6040356Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_160a0274-f0a2-4603-81cf-bb745a703015_SERVICEACCOUNTCERTIFICATE
2020-12-01T01:35:49.6045026Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_160a0274-f0a2-4603-81cf-bb745a703015_SERVICEACCOUNTNAME
2020-12-01T01:35:49.6048071Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-12-01T01:35:49.6052265Z ##[debug]loading ENDPOINT_AUTH_SCHEME_160a0274-f0a2-4603-81cf-bb745a703015
2020-12-01T01:35:49.6078115Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-12-01T01:35:49.6079039Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-12-01T01:35:49.6079709Z ##[debug]loading INPUT_ARGUMENTS
2020-12-01T01:35:49.6080166Z ##[debug]loading INPUT_CANARYIMAGE
2020-12-01T01:35:49.6088226Z ##[debug]loading INPUT_CHARTPATH
2020-12-01T01:35:49.6097479Z ##[debug]loading INPUT_CHARTPATHFORACR
2020-12-01T01:35:49.6103918Z ##[debug]loading INPUT_CHARTTYPE
2020-12-01T01:35:49.6107955Z ##[debug]loading INPUT_COMMAND
2020-12-01T01:35:49.6113930Z ##[debug]loading INPUT_CONNECTIONTYPE
2020-12-01T01:35:49.6145828Z ##[debug]loading INPUT_DESTINATION
2020-12-01T01:35:49.6146317Z ##[debug]loading INPUT_ENABLETLS
2020-12-01T01:35:49.6146937Z ##[debug]loading INPUT_FAILONSTDERR
2020-12-01T01:35:49.6147400Z ##[debug]loading INPUT_FORCE
2020-12-01T01:35:49.6147817Z ##[debug]loading INPUT_INSTALL
2020-12-01T01:35:49.6148257Z ##[debug]loading INPUT_KUBERNETESSERVICEENDPOINT
2020-12-01T01:35:49.6150738Z ##[debug]loading INPUT_RECREATE
2020-12-01T01:35:49.6157556Z ##[debug]loading INPUT_RESETVALUES
2020-12-01T01:35:49.6165276Z ##[debug]loading INPUT_SAVE
2020-12-01T01:35:49.6171122Z ##[debug]loading INPUT_UPDATEDEPENDENCY
2020-12-01T01:35:49.6190923Z ##[debug]loading INPUT_UPGRADETILLER
2020-12-01T01:35:49.6199452Z ##[debug]loading INPUT_USECLUSTERADMIN
2020-12-01T01:35:49.6229468Z ##[debug]loading INPUT_VALUEFILE
2020-12-01T01:35:49.6244603Z ##[debug]loading INPUT_WAITFOREXECUTION
2020-12-01T01:35:49.6261969Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2020-12-01T01:35:49.6305056Z ##[debug]loaded 34
2020-12-01T01:35:49.6333694Z ##[debug]Agent.ProxyUrl=undefined
2020-12-01T01:35:49.6337604Z ##[debug]Agent.CAInfo=undefined
2020-12-01T01:35:49.6339941Z ##[debug]Agent.ClientCert=undefined
2020-12-01T01:35:49.6341346Z ##[debug]Agent.SkipCertValidation=undefined
2020-12-01T01:35:49.7029678Z ##[debug]namespace=null
2020-12-01T01:35:49.7371053Z ##[debug]agent.proxyurl=undefined
2020-12-01T01:35:49.7372299Z ##[debug]VSTS_ARM_REST_IGNORE_SSL_ERRORS=undefined
2020-12-01T01:35:49.7372910Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_85db2504-13f1-458d-84d5-a5c9ab0d53ec_build_5665_0
2020-12-01T01:35:49.7399246Z ##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/daimler-mic/
2020-12-01T01:35:49.7400328Z ##[debug]System.HostType=build
2020-12-01T01:35:49.7401200Z ##[debug]System.DefaultWorkingDirectory=D:\a\1\s
2020-12-01T01:35:49.7402056Z ##[debug]Build.SourceBranchName=master
2020-12-01T01:35:49.7402586Z ##[debug]Build.Repository.Provider=TfsGit
2020-12-01T01:35:49.7403177Z ##[debug]Build.Repository.Uri=https://daimler-mic@dev.azure.com/daimler-mic/MIC-Perimeter/_git/ambassador-mtls
2020-12-01T01:35:49.7431027Z ##[debug]namespace=null
2020-12-01T01:35:49.7435431Z ##[debug]check path : D:\a\_tasks\HelmDeploy_afa7d54d-537b-4dc8-b60a-e0eeea2c9a87\0.178.0\task.json
2020-12-01T01:35:49.7443567Z ##[debug]adding resource file: D:\a\_tasks\HelmDeploy_afa7d54d-537b-4dc8-b60a-e0eeea2c9a87\0.178.0\task.json
2020-12-01T01:35:49.7444266Z ##[debug]system.culture=en-US
2020-12-01T01:35:49.7483407Z ##[debug]check path : D:\a\_tasks\HelmDeploy_afa7d54d-537b-4dc8-b60a-e0eeea2c9a87\0.178.0\node_modules\azure-pipelines-tasks-azure-arm-rest-v2\module.json
2020-12-01T01:35:49.7484618Z ##[debug]adding resource file: D:\a\_tasks\HelmDeploy_afa7d54d-537b-4dc8-b60a-e0eeea2c9a87\0.178.0\node_modules\azure-pipelines-tasks-azure-arm-rest-v2\module.json
2020-12-01T01:35:49.7485314Z ##[debug]system.culture=en-US
2020-12-01T01:35:49.7601317Z ##[debug]command=lint
2020-12-01T01:35:49.7605148Z ##[debug]connectionType=Kubernetes Service Connection
2020-12-01T01:35:49.7614317Z ##[debug]connectionType=Kubernetes Service Connection
2020-12-01T01:35:49.7615003Z ##[debug]azureSubscriptionEndpoint=null
2020-12-01T01:35:49.7773206Z ##[debug]Agent.ProxyUrl=undefined
2020-12-01T01:35:49.7778067Z ##[debug]Agent.CAInfo=undefined
2020-12-01T01:35:49.7780333Z ##[debug]Agent.ClientCert=undefined
2020-12-01T01:35:49.7788011Z ##[debug]check path : D:\a\_tasks\HelmDeploy_afa7d54d-537b-4dc8-b60a-e0eeea2c9a87\0.178.0\node_modules\azure-pipelines-tool-lib\lib.json
2020-12-01T01:35:49.7788938Z ##[debug]adding resource file: D:\a\_tasks\HelmDeploy_afa7d54d-537b-4dc8-b60a-e0eeea2c9a87\0.178.0\node_modules\azure-pipelines-tool-lib\lib.json
2020-12-01T01:35:49.7790073Z ##[debug]system.culture=en-US
2020-12-01T01:35:49.7824055Z ##[debug]kubernetesServiceEndpoint=160a0274-f0a2-4603-81cf-bb745a703015
2020-12-01T01:35:49.7824787Z ##[debug]160a0274-f0a2-4603-81cf-bb745a703015 data authorizationType = AzureSubscription
2020-12-01T01:35:49.7828048Z ##[debug]160a0274-f0a2-4603-81cf-bb745a703015=https://amap-nprcusa-ambassador-465c1beb.hcp.centralus.azmk8s.io/
2020-12-01T01:35:49.7836627Z ##[debug]160a0274-f0a2-4603-81cf-bb745a703015 auth param serviceAccountCertificate = ***
2020-12-01T01:35:49.7840913Z ##[debug]160a0274-f0a2-4603-81cf-bb745a703015 auth param apiToken = ***
2020-12-01T01:35:49.7852779Z ##[debug]agent.tempDirectory=D:\a\_temp
2020-12-01T01:35:49.7876864Z ##[debug]Kubeconfig file path: D:\a\_temp\helmTask\1606786549784\config
2020-12-01T01:35:49.7888135Z ##[debug]which 'kubectl'
2020-12-01T01:35:49.8169311Z ##[debug]found: 'C:\ProgramData\Chocolatey\bin\kubectl.exe'
2020-12-01T01:35:49.8171820Z ##[debug]which 'kubectl'
2020-12-01T01:35:49.8325261Z ##[debug]found: 'C:\ProgramData\Chocolatey\bin\kubectl.exe'
2020-12-01T01:35:49.8355723Z ##[debug]which 'helm'
2020-12-01T01:35:49.8445661Z ##[debug]found: 'C:\ProgramData\Chocolatey\bin\helm.exe'
2020-12-01T01:35:49.8447007Z ##[debug]which 'helm'
2020-12-01T01:35:49.8584741Z ##[debug]found: 'C:\ProgramData\Chocolatey\bin\helm.exe'
2020-12-01T01:35:49.8587796Z ##[debug]connectionType=Kubernetes Service Connection
2020-12-01T01:35:49.8589070Z ##[debug]SYSTEM_JOBID=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3
2020-12-01T01:35:49.8592337Z ##[debug]failOnStderr=false
2020-12-01T01:35:49.9162764Z ##[debug]Processed: ##vso[telemetry.publish area=TaskEndpointId;feature=HelmDeployV0]{"connectionType":"Kubernetes Service Connection","command":"lint","jobId":"3dc8fd7e-4368-5a92-293e-d53cefc8c4b3"}
2020-12-01T01:35:49.9164398Z ##[debug]tillernamespace=null
2020-12-01T01:35:49.9165152Z ##[debug]system.debug=true
2020-12-01T01:35:49.9165817Z ##[debug]namespace=null
2020-12-01T01:35:49.9167100Z ##[debug]arguments=./multi-helm -f D:\a\1\s/multi-helm/spec/LINT/values.yaml
2020-12-01T01:35:49.9167841Z ##[debug]enableTls=false
2020-12-01T01:35:49.9168319Z ##[debug]which 'C:\ProgramData\Chocolatey\bin\helm.exe'
2020-12-01T01:35:49.9168865Z ##[debug]found: 'C:\ProgramData\Chocolatey\bin\helm.exe'
2020-12-01T01:35:49.9169370Z ##[debug]which 'C:\ProgramData\Chocolatey\bin\helm.exe'
2020-12-01T01:35:49.9169870Z ##[debug]found: 'C:\ProgramData\Chocolatey\bin\helm.exe'
2020-12-01T01:35:49.9170405Z ##[debug]C:\ProgramData\Chocolatey\bin\helm.exe arg: lint
2020-12-01T01:35:49.9170998Z ##[debug]C:\ProgramData\Chocolatey\bin\helm.exe arg: --debug
2020-12-01T01:35:49.9171639Z ##[debug]C:\ProgramData\Chocolatey\bin\helm.exe arg: ./multi-helm -f D:\a\1\s/multi-helm/spec/LINT/values.yaml
2020-12-01T01:35:49.9172299Z ##[debug]exec tool: C:\ProgramData\Chocolatey\bin\helm.exe
2020-12-01T01:35:49.9172770Z ##[debug]arguments:
2020-12-01T01:35:49.9173237Z ##[debug]   lint
2020-12-01T01:35:49.9173665Z ##[debug]   --debug
2020-12-01T01:35:49.9174083Z ##[debug]   ./multi-helm
2020-12-01T01:35:49.9174483Z ##[debug]   -f
2020-12-01T01:35:49.9174959Z ##[debug]   D:\a\1\s/multi-helm/spec/LINT/values.yaml
2020-12-01T01:35:49.9175441Z [command]C:\ProgramData\Chocolatey\bin\helm.exe lint --debug ./multi-helm -f D:\a\1\s/multi-helm/spec/LINT/values.yaml
2020-12-01T01:35:50.1970317Z ==> Linting ./multi-helm
2020-12-01T01:35:50.1971179Z [INFO] Chart.yaml: icon is recommended
2020-12-01T01:35:50.1971539Z 
2020-12-01T01:35:50.1971873Z 1 chart(s) linted, 0 chart(s) failed
2020-12-01T01:35:50.1976147Z ##[debug]set helmExitCode=0
2020-12-01T01:35:50.1984958Z ##[debug]Processed: ##vso[task.setvariable variable=helmExitCode;issecret=false;]0
2020-12-01T01:35:50.1985824Z ##[debug]set helmOutput===> Linting ./multi-helm
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

2020-12-01T01:35:50.1987513Z ##[debug]Processed: ##vso[task.setvariable variable=helmOutput;issecret=false;]==> Linting ./multi-helm%0A[INFO] Chart.yaml: icon is recommended%0A%0A1 chart(s) linted, 0 chart(s) failed%0A
2020-12-01T01:35:50.1992882Z ##[debug]connectionType=Kubernetes Service Connection
2020-12-01T01:35:50.2110377Z ##[section]Finishing: Helm Lint
```

**Comment by shigupt202** [comment]
This PR should fix the issue: https://github.com/microsoft/azure-pipelines-tasks/pull/13884
The deployment will take a few days to rollout to all the customers.

**Comment by agilekevin** [comment]
Awesome, thanks!

**Comment by agilekevin** [comment]
It seems that after this PR, the task will print a warning in the ADO pipeline.  Is there some way for me to prevent or suppress this warning?

From my side, I have a big Chart, hence lots of output.  I don't think I'm doing anything wrong here, so I'm not sure what I'm supposed to do with this warning.

**Comment by shigupt202** [comment]
There's no way to suppress this warning. You can safely ignore it.
