### ISSUE TITLE
NuGet Authenticate v. 0.179.0 started failing with 'File not found'

### ISSUE THREAD

**Issue by dmgonch** [microsoft/azure-pipelines-tasks#14015]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetAuthenticateTask

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
- Agent - Hosted or Private: 

## Issue Description

After 'NuGet Authenticate' got auto-updated from 0.175.0 to 0.179.0 it started failing consistently at the very beginning of its execution.

### Task logs

See Error logs below

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
2020-12-02T22:10:05.6405908Z ##[section]Starting: NuGet Authenticate
2020-12-02T22:10:05.6693760Z ==============================================================================
2020-12-02T22:10:05.6694221Z Task         : NuGet authenticate
2020-12-02T22:10:05.6695613Z Description  : Configure NuGet tools to authenticate with Azure Artifacts and other NuGet repositories. Requires NuGet >= 4.8.5385, dotnet >= 2.1.400, or MSBuild >= 15.8.166.59604
2020-12-02T22:10:05.6696219Z Version      : 0.179.0
2020-12-02T22:10:05.6696553Z Author       : Microsoft Corporation
2020-12-02T22:10:05.6697385Z Help         : https://aka.ms/NuGetAuthenticateTask
2020-12-02T22:10:05.6699036Z ==============================================================================
2020-12-02T22:10:05.7764239Z ##[error]File not found: 'D:\a\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.0\bash.js'
2020-12-02T22:10:05.7830548Z ##[section]Finishing: NuGet Authenticate 
```

**Comment by satbai** [comment]
Updated the NuGet Authenticate task to 0.179.1 with a fix, this should now be resolved.

**Comment by slandsaw** [comment]
I get this error with task version 0.179.1

    ##[debug]nuGetServiceConnections=undefined
    ##[debug]Finding the URI for the packaging service
    ##[debug]Getting credentials for local feeds
    ##[debug]SYSTEMVSSCONNECTION exists true
    ##[debug]Got auth token
    ##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/foo/
    ##[debug]System.ServerType=Hosted
    ##[debug]Agent.ProxyUrl=undefined
    ##[debug]Attempt failed. Number of tries left: 2
    ##[debug]Invalid regular expression: /*dev.azure.com*/: Nothing to repeat
    ##[debug]SyntaxError: Invalid regular expression: /*dev.azure.com*/: Nothing to repeat
    at new RegExp (<anonymous>)
    at HttpClient.no_proxy.split.forEach.bypass (E:\b\2\_work\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.1\node_modules\azure-pipelines-tasks-artifacts-common\node_modules\typed-rest-client\HttpClient.js:114:49)
    at Array.forEach (<anonymous>)
    at new HttpClient (E:\b\2\_work\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.1\node_modules\azure-pipelines-tasks-artifacts-common\node_modules\typed-rest-client\HttpClient.js:113:33)
    at new RestClient (E:\b\2\_work\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.1\node_modules\azure-pipelines-tasks-artifacts-common\node_modules\typed-rest-client\RestClient.js:25:23)
    at new WebApi (E:\b\2\_work\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.1\node_modules\azure-pipelines-tasks-artifacts-common\node_modules\azure-devops-node-api\WebApi.js:162:21)
    at Object.getWebApiWithProxy (E:\b\2\_work\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.1\node_modules\azure-pipelines-tasks-artifacts-common\webapi.js:13:12)
    at E:\b\2\_work\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.1\node_modules\azure-pipelines-tasks-artifacts-common\connectionDataUtils.js:77:28
    at Generator.next (<anonymous>)
    at E:\b\2\_work\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.1\node_modules\azure-pipelines-tasks-artifacts-common\connectionDataUtils.js:8:71
`
