### ISSUE TITLE
Caching storage capacity

### ISSUE THREAD

**Issue by mfiumara** [microsoft/azure-pipelines-tasks#14013]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache@2

## Environment
- Server - Azure Pipelines
bGridSolutions is our team name.

- Agent - Hosted or Private: 
Virtual Machine Scaling Set

## Issue Description

Cache@2 task fails when trying to store files bigger than the OS disk. It is failing on the post-cache step as it looks like it is using a temp directory on the 30GB OS disk, wherease we are trying to cache something on an attached 1TB disk. Trying to cancel the build crashes the agent.

This is on a container build where we mount the extra disk via a bind-mount:
```
  - container
    options: -v /mnt/workspace:/workspace
```

### Task logs
```
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.0.1
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - cachetest                                [string]
 - b40c12b9340fcd3f9c9af64d409d3342289c4814 [string]
Resolved to: cachetest|b40c12b9340fcd3f9c9af64d409d3342289c4814
Verbose, ArtifactHttpClientFactory.CreateVssHttpClient: DedupStoreHttpClient with BaseUri: https://vsblobprodsu6weu.vsblob.visualstudio.com/Ac357220b-da23-45c0-ada1-5995a04fdb4f/, MaxRetries:5, SendTimeout:00:00:50
##[debug]Dedup parallelism: 192
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 55108ff0-3033-4f37-896e-8ddf655d2f8d
Verbose, Started ITelemetrySender BlobStoreApplicationInsightsTelemetrySender.
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `cachetest|b40c12b9340fcd3f9c9af64d409d3342289c4814`
Information, There is a cache miss.
##[debug]Processed: ##vso[telemetry.publish area=AzurePipelinesAgent;feature=PipelineCache]{"FileCount":"0","PlanId":"32c3b007-0f21-4eb6-8928-dcdebaabbc8d","JobId":"a2ee7b20-88b5-55d1-fa60-95d90270713c","TaskInstanceId":"ff7c70a4-d8d0-5353-e667-b6b5183dadab","CacheResult":"Miss","ActionDurationMs":"162","ActionName":"PipelineCache.RestoreCache","ActionResult":"Success","AttemptNumber":"1","ItemCount":"0","Level":"ThirdParty","CreatedUtcNow":"2020-12-02T14:12:16.3919060Z","SentUtcNow":"2020-12-02T14:12:16.5593015Z","BaseAddress":"https://vsblobprodsu6weu.vsblob.visualstudio.com/Ac357220b-da23-45c0-ada1-5995a04fdb4f/","X_TFS_Session":"55108ff0-3033-4f37-896e-8ddf655d2f8d","DeploymentEnvironment":"PRODUCTION","DeploymentEnvironmentIsProduction":"True","VSOAccount":"vsblobprodsu6weu","OSName":"Linux","OSVersion":"2019","FrameworkDescription":".NET Core ","ProcessName":"Agent.PluginHost","DotNetReleaseDword":"-1","Version":"18.177.30628.0","ExceptionCount":"0"}
##[debug]Starting 'tar' with arguments '-v -cf "555b27247a27416da775c2e772219f77_archive.tar" -C "/mnt/workspace/cachetest" .'...
./
./dummyfile
Verbose, ApplicationInsightsTelemetrySender sent PipelineCache.RestoreCache telemetry
tar: 555b27247a27416da775c2e772219f77_archive.tar: Wrote only 8192 of 10240 bytes
tar: Error is not recoverable: exiting now
Verbose, ApplicationInsightsTelemetrySender waiting for 0 of 1 TrackEvent operations to complete...
Verbose, ApplicationInsightsTelemetrySender operations completed in 0 ms
Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session 55108ff0-3033-4f37-896e-8ddf655d2f8d
Verbose, Stopped ITelemetrySender BlobStoreApplicationInsightsTelemetrySender.
##[error]Process returned non-zero exit code: 2
##[debug]Processed: ##vso[task.logissue type=error;]Process returned non-zero exit code: 2
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Agent.Plugins.PipelineCache.TarUtils.RunProcessAsync(AgentTaskPluginExecutionContext context, ProcessStartInfo processStartInfo, Func`3 additionalTaskToExecuteWhilstRunningProcess, Action actionOnFailure, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.TarUtils.RunProcessAsync(AgentTaskPluginExecutionContext context, ProcessStartInfo processStartInfo, Func`3 additionalTaskToExecuteWhilstRunningProcess, Action actionOnFailure, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.TarUtils.ArchiveFilesToTarAsync(AgentTaskPluginExecutionContext context, String inputPath, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.PipelineCacheServer.GetUploadPathAsync(ContentFormat contentFormat, AgentTaskPluginExecutionContext context, String path, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.PipelineCacheServer.UploadAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, String path, CancellationToken cancellationToken, ContentFormat contentFormat)
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, Func`1 restoreKeysGenerator, String path, CancellationToken token)
   at Agent.Plugins.PipelineCache.PipelineCacheTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: Cache
```

Not sure how to proceed, how can we remove this restriction? It works perfectly for smaller size caches.

**Comment by dylancourt** [comment]
+1 for this! Been looking everywhere for the .tar staging in the cache task to be done on a different path that has more storage space.

**Comment by johnterickson** [comment]
Can you change the tmp directory to point to the better/bigger disk?

**Comment by dylancourt** [comment]
We're using VSS hosts so /etc/fstab is out of the question. However I think I've found a solution with changing the environment variables and then capturing the image for the VSS. I guess this is more of a nice to have to have a parameter that allows you to specify where the .tar file is staged. However this would work as well.

However I stumbled across the VSS update command to extend the OS disk with the CLI as you can't do so via the web interface. We opted to extend the OS disk of the VM instance type to 500GB and used an instance type without a temp disk.

az vmss update --resource-group $rg --name $name --set virtualMachineProfile.storageProfile.osDisk.diskSizeGb=500

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#customizing-pipeline-agent-configuration

**Comment by mfiumara** [comment]
Hi we tried pointing the `/tmp` disk somewhere else from within the pipeline but that causes a lot of other things that break. So for now we have solved it with a bigger OS disk but implementation wise I think it's better to have to have the cache task work from the same disk as that's being tarred.

**Comment by jason-swissre** [comment]
Why did this get closed?  We are running into this issue on hosted agents and I don't see a resolution?

**Comment by ariyurek** [comment]
we have the same issue and did not find any solution at hosted agents

**Comment by httran13** [comment]
Help we have the same problem

**Comment by mfiumara** [comment]
Hey I can't re-open this issue myself it seems.
