### ISSUE TITLE
PublishPipelineArtifact@1 task not available when using multistage pipelines in Azure DevOps Server 2020

### ISSUE THREAD

**Issue by farlop** [microsoft/azure-pipelines-tasks#14206]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Feature

**Enter Task Name**: PublishPipelineArtifact@1
Version: 1.2.3

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure DevOps Server 2020

- Agent - Hosted or Private: 
   Private Windows 2.170.1

## Issue Description

Now that Azure DevOps Server fully supports multistaging pipelines, should be reasonable that we coud use this task. Currently an error message is thrown when trying to use the 'publish' shorthand:

```
- publish: $(outputDirectory)
  displayName: Publish Artifact
  artifact: app
```

### Task logs

```
2021-01-11T08:25:49.4276920Z ##[debug]Evaluating condition for step: 'Publish Artifact'
2021-01-11T08:25:49.4280705Z ##[debug]Evaluating: True
2021-01-11T08:25:49.4282072Z ##[debug]Evaluating Boolean:
2021-01-11T08:25:49.4283413Z ##[debug]=> True
2021-01-11T08:25:49.4284447Z ##[debug]Result: True
2021-01-11T08:25:49.4285596Z ##[section]Iniciando: Publish Artifact
2021-01-11T08:25:49.4450369Z ==============================================================================
2021-01-11T08:25:49.4451586Z Task         : Publicar artefacto de canalizaciÃ³n
2021-01-11T08:25:49.4452620Z Description  : Publicar artefacto de canalizaciÃ³n
2021-01-11T08:25:49.4453573Z Version      : 1.2.3
2021-01-11T08:25:49.4454436Z Author       : Microsoft Corporation
2021-01-11T08:25:49.4455875Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
2021-01-11T08:25:49.4457323Z ==============================================================================
2021-01-11T08:25:50.2750776Z Artifact name input: app
2021-01-11T08:25:50.3243887Z ##[error]No se admite la tarea de artefacto de canalizaciÃ³n en el entorno local. En su lugar, use la tarea de artefacto de compilaciÃ³n.
2021-01-11T08:25:50.3246809Z ##[debug]Processed: ##vso[task.logissue type=error;]No se admite la tarea de artefacto de canalizaciÃ³n en el entorno local. En su lugar, use la tarea de artefacto de compilaciÃ³n.
2021-01-11T08:25:50.3249859Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2021-01-11T08:25:50.4727767Z ##[debug]   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2021-01-11T08:25:50.4887141Z ##[section]Finalizando: Publish Artifact
```

**Comment by michaelfaith** [comment]
Definitely need this.  PublishBuildArtifacts has been deprecated in favor of this task, which doesn't seem to work on-prem.  Big gap in capability

**Comment by michaelfaith** [comment]
Still relevant
