### ISSUE TITLE
PublishTestResultsV2

### ISSUE THREAD

**Issue by karambawow** [microsoft/azure-pipelines-tasks#14212]
today we tryed to get the Publish test Results Task working 
in Verion 2.158 

we imported the Task via avalable script 
and the update just takes care of the VStest Task 
the seperate publish Task will not be updated 
so we tryed to Imort just the Publish Task  in our case nUnit Files
it works but it is a mess wrong File Names ans at the end some errors in the script 
can someone please look into it to get it fixed
i will prepare some Logs in a Minute

**Comment by karambawow** [comment]
##[error]File not found: 'C:\Users\xxx\Downloads\vsts-agent-win-x64-2.175.2 (4)\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.158.0\publishtestresults.js'
first  try 
than we adapted the Task to get publishtestresults.ts
so  we run into this issue
2021-01-11T13:45:02.4365398Z C:\Users\xxx\Downloads\vsts-agent-win-x64-2.175.2 (4)\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.158.3\publishtestresults.js:1
2021-01-11T13:45:02.4365949Z (function (exports, require, module, __filename, __dirname) { import * as path from 'path';
2021-01-11T13:45:02.4366454Z                                                                                               ^^^^^^
2021-01-11T13:45:02.4366603Z 
2021-01-11T13:45:02.4366716Z SyntaxError: Unexpected token import
2021-01-11T13:45:02.4366868Z     at createScript (vm.js:56:10)
2021-01-11T13:45:02.4367041Z     at Object.runInThisContext (vm.js:97:10)
2021-01-11T13:45:02.4368002Z     at Module._compile (module.js:549:28)
2021-01-11T13:45:02.4368380Z     at Object.Module._extensions..js (module.js:586:10)
2021-01-11T13:45:02.4368590Z     at Module.load (module.js:494:32)
2021-01-11T13:45:02.4368757Z     at tryModuleLoad (module.js:453:12)
2021-01-11T13:45:02.4368932Z     at Function.Module._load (module.js:445:3)
2021-01-11T13:45:02.4369108Z     at Module.runMain (module.js:611:10)
2021-01-11T13:45:02.4369277Z     at run (bootstrap_node.js:394:7)
2021-01-11T13:45:02.4369443Z     at startup (bootstrap_node.js:160:9)

**Comment by karambawow** [comment]
the^^^^ are shown under  { import *

**Comment by vivek425ster** [comment]
@karambawow Can you please tell me the script which you are using to update the task ?
And how also are you using On Prem or hosted version.

And what is the agent which you are using ?
Is it hosted or your own agent machine ?

**Comment by navin22** [comment]
Closing this because of no activity. Please reopen this if you still face the issue.
