### ISSUE TITLE
##[error]TypeError: Cannot read property 'locationServiceData' of null Error

### ISSUE THREAD

**Issue by IanBFarrell** [microsoft/azure-pipelines-tasks#14282]
I am putting this here because the Developer Community told me to talk about my issue here. https://developercommunity2.visualstudio.com/t/errorTypeError:-Cannot-read-property/1285892

*Type*: Task Error

**Enter Task Name**: .Net Core and npm

## Environment
- Server - Azure Pipelines (rigsystemsis)

- Agent - Private (Linux)

## Issue Description

when .Net Core or npm runs about 50% (or more) of the time the task fails with "##[error]TypeError: Cannot read property 'locationServiceData' of null Error"

### Task logs

```
##[debug]Evaluating condition for step: 'npm install'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
Starting: npm install
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.179.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
==============================================================================
##[debug]Using node path: /opt/novapps/adb/agent-04/externals/node/bin/node
##[debug]agent.TempDirectory=/opt/novapps/adb/agent-04/_work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_COMMAND
##[debug]loading INPUT_WORKINGDIR
##[debug]loading INPUT_VERBOSE
##[debug]loading INPUT_CUSTOMREGISTRY
##[debug]loading INPUT_PUBLISHREGISTRY
##[debug]loading INPUT_PUBLISHPACKAGEMETADATA
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loaded 9
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : /opt/novapps/adb/agent-04/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.179.1/task.json
##[debug]adding resource file: /opt/novapps/adb/agent-04/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.179.1/task.json
##[debug]system.culture=en-US
##[debug]Getting Packaging service access points
##[debug]System.TeamFoundationCollectionUri=https://rigsystemsis.visualstudio.com/
##[debug]System.ServerType=Hosted
##[debug]Getting credentials for local feeds
SYSTEMVSSCONNECTION exists true
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Got auth token
##[debug]System.ServerType=Hosted
##[debug]Agent.ProxyUrl=undefined
##[debug]Created webApi client for https://rigsystemsis.visualstudio.com/; options: {"proxy":null,"allowRetries":true,"maxRetries":5,"ignoreSslError":false}
##[debug]Getting URI for area ID 4C83CFC1-F33A-477E-A789-29D38FFCA52E from https://rigsystemsis.visualstudio.com/
##[debug]Found resource area with locationUrl: https://rigsystemsis.pkgs.visualstudio.com/
##[debug]Found serviceUri: https://rigsystemsis.pkgs.visualstudio.com/
##[debug]Getting credentials for local feeds
SYSTEMVSSCONNECTION exists true
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Got auth token
##[debug]Agent.ProxyUrl=undefined
##[debug]Created webApi client for https://rigsystemsis.pkgs.visualstudio.com/; options: {"proxy":null,"allowRetries":true,"maxRetries":5,"ignoreSslError":false}
##[debug]Acquiring Packaging endpoints...
##[debug]Successfully acquired the connection data
##[debug]Unable to get packaging URIs
##[debug]Cannot read property 'locationServiceData' of null
##[debug]TypeError: Cannot read property 'locationServiceData' of null
    at Object.<anonymous> (/opt/novapps/adb/agent-04/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.179.1/node_modules/packaging-common/locationUtilities.js:96:50)
    at next (native)
```

**Comment by IanBFarrell** [comment]
I wanted to know if this is a issue that is known about and/or being worked. It is causing problems with the day to day development and use of Azure DevOps Pipelines. It is also almost entirely blocking our SPA deployments because we use multiple npm tasks in the build.

**Comment by anatolybolshakov** [comment]
Hey @satbai could you please take a look at this issue?

**Comment by satbai** [comment]
I think it may be related to [this commit](https://github.com/microsoft/azure-pipelines-tasks/commit/6e24f3b285397073443f29db64e654e578f885db#diff-2a16291e21f5d87ab0937629d2bed76d67019a344b2d1e4c05270cbba7000794). @zhenghao104 could you have a look when you have a chance?

**Comment by zhenghao104** [comment]
@IanBFarrell Hi there, since your private agent run on linux, can you try setting this debug flag on to get more information on the HTTP request?

https://github.com/microsoft/typed-rest-client#debugging 

Note that the output will contain some secrets, please do not remove them in the comments when you provide the new logs.

**Comment by jmyersmsft** [comment]
(edited the above comment to clarify that you _should_ remove secrets before sending logs)

**Comment by IanBFarrell** [comment]
Which debug flag? when I select debug on the Build variables the above output is what is given.

**Comment by zhenghao104** [comment]
https://github.com/microsoft/typed-rest-client#debugging

**Comment by IanBFarrell** [comment]
I think I have removed any secrets but if I missed anything please let me know and I can remove it.

2021-02-03T19:42:57.8221428Z ##[debug]Evaluating condition for step: 'npm install'
2021-02-03T19:42:57.8222679Z ##[debug]Evaluating: succeeded()
2021-02-03T19:42:57.8223086Z ##[debug]Evaluating succeeded:
2021-02-03T19:42:57.8224021Z ##[debug]=> True
2021-02-03T19:42:57.8224483Z ##[debug]Result: True
2021-02-03T19:42:57.8225039Z ##[section]Starting: npm install
2021-02-03T19:42:57.8231622Z ==============================================================================
2021-02-03T19:42:57.8231891Z Task         : npm
2021-02-03T19:42:57.8232221Z Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
2021-02-03T19:42:57.8232565Z Version      : 1.180.0
2021-02-03T19:42:57.8232776Z Author       : Microsoft Corporation
2021-02-03T19:42:57.8233071Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
2021-02-03T19:42:57.8233392Z ==============================================================================
2021-02-03T19:42:57.8395874Z ##[debug]Using node path: /opt/novapps/adb/agent-04/externals/node/bin/node
2021-02-03T19:42:57.9484149Z ##[debug]agent.TempDirectory=/opt/novapps/adb/agent-04/_work/_temp
2021-02-03T19:42:57.9500634Z ##[debug]loading inputs and endpoints
2021-02-03T19:42:57.9504445Z ##[debug]loading INPUT_COMMAND
2021-02-03T19:42:57.9513160Z ##[debug]loading INPUT_WORKINGDIR
2021-02-03T19:42:57.9515526Z ##[debug]loading INPUT_VERBOSE
2021-02-03T19:42:57.9516287Z ##[debug]loading INPUT_CUSTOMREGISTRY
2021-02-03T19:42:57.9516955Z ##[debug]loading INPUT_PUBLISHREGISTRY
2021-02-03T19:42:57.9517805Z ##[debug]loading INPUT_PUBLISHPACKAGEMETADATA
2021-02-03T19:42:57.9518346Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2021-02-03T19:42:57.9518896Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2021-02-03T19:42:57.9519477Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2021-02-03T19:42:57.9522765Z ##[debug]loaded 9
2021-02-03T19:42:57.9549088Z ##[debug]Agent.ProxyUrl=undefined
2021-02-03T19:42:57.9549816Z ##[debug]Agent.CAInfo=undefined
2021-02-03T19:42:57.9550351Z ##[debug]Agent.ClientCert=undefined
2021-02-03T19:42:57.9550921Z ##[debug]Agent.SkipCertValidation=undefined
2021-02-03T19:42:58.7582245Z HTTP 94566: call onSocket 0 0
2021-02-03T19:42:58.7592797Z ##[debug]check path : /opt/novapps/adb/agent-04/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.180.0/task.json
2021-02-03T19:42:58.7597265Z HTTP 94566: createConnection rigsystemsis.visualstudio.com:443::::::::: { servername: 'rigsystemsis.visualstudio.com',
2021-02-03T19:42:58.7600024Z ##[debug]adding resource file: /opt/novapps/adb/agent-04/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.180.0/task.json
2021-02-03T19:42:58.7693809Z   _defaultAgent: 
2021-02-03T19:42:58.7696976Z ##[debug]system.culture=en-US
2021-02-03T19:42:58.7699819Z    Agent {
2021-02-03T19:42:58.7701195Z ##[debug]Getting Packaging service access points
2021-02-03T19:42:58.7704095Z      domain: null,
2021-02-03T19:42:58.7705808Z      _events: { free: [Function] },
2021-02-03T19:42:58.7707046Z ##[debug]System.TeamFoundationCollectionUri=https://rigsystemsis.visualstudio.com/
2021-02-03T19:42:58.7709227Z      _eventsCount: 1,
2021-02-03T19:42:58.7710488Z ##[debug]System.ServerType=Hosted
2021-02-03T19:42:58.7712250Z      _maxListeners: undefined,
2021-02-03T19:42:58.7714070Z ##[debug]Getting credentials for local feeds
2021-02-03T19:42:58.7716031Z      defaultPort: 443,
2021-02-03T19:42:58.7716802Z SYSTEMVSSCONNECTION exists true
2021-02-03T19:42:58.7717745Z ##[debug]SYSTEMVSSCONNECTION exists true
2021-02-03T19:42:58.7719616Z      protocol: 'https:',
2021-02-03T19:42:58.7720243Z      options: { path: null },
2021-02-03T19:42:58.7721403Z      requests: {},
2021-02-03T19:42:58.7722432Z ##[debug]Got auth token
2021-02-03T19:42:58.7723238Z ##[debug]System.ServerType=Hosted
2021-02-03T19:42:58.7725692Z      sockets: { 'rigsystemsis.visualstudio.com:443:::::::::': [] },
2021-02-03T19:42:58.7726113Z      freeSockets: {},
2021-02-03T19:42:58.7727489Z ##[debug]Agent.ProxyUrl=undefined
2021-02-03T19:42:58.7729746Z      keepAliveMsecs: 1000,
2021-02-03T19:42:58.7730853Z ##[debug]Created webApi client for https://rigsystemsis.visualstudio.com/; options: {"proxy":null,"allowRetries":true,"maxRetries":5,"ignoreSslError":false}
2021-02-03T19:42:58.7732395Z ##[debug]Getting URI for area ID 4C83CFC1-F33A-477E-A789-29D38FFCA52E from https://rigsystemsis.visualstudio.com/
2021-02-03T19:42:58.7733672Z      keepAlive: false,
2021-02-03T19:42:58.7734966Z ##[debug]Found resource area with locationUrl: https://rigsystemsis.pkgs.visualstudio.com/
2021-02-03T19:42:58.7736071Z ##[debug]Found serviceUri: https://rigsystemsis.pkgs.visualstudio.com/
2021-02-03T19:42:58.7736726Z ##[debug]Getting credentials for local feeds
2021-02-03T19:42:58.7736997Z SYSTEMVSSCONNECTION exists true
2021-02-03T19:42:58.7737555Z ##[debug]SYSTEMVSSCONNECTION exists true
2021-02-03T19:42:58.7738145Z ##[debug]Got auth token
2021-02-03T19:42:58.7738689Z ##[debug]Agent.ProxyUrl=undefined
2021-02-03T19:42:58.7739534Z ##[debug]Created webApi client for https://rigsystemsis.pkgs.visualstudio.com/; options: {"proxy":null,"allowRetries":true,"maxRetries":5,"ignoreSslError":false}
2021-02-03T19:42:58.7740304Z ##[debug]Acquiring Packaging endpoints...
2021-02-03T19:42:58.7741284Z      maxSockets: Infinity,
2021-02-03T19:42:58.7741753Z      maxFreeSockets: 256,
2021-02-03T19:42:58.7742221Z      maxCachedSessions: 100,
2021-02-03T19:42:58.7742840Z      _sessionCache: { map: {}, list: [] } },
2021-02-03T19:42:58.7743661Z   host: 'rigsystemsis.visualstudio.com',
2021-02-03T19:42:58.7744088Z   port: 443,
2021-02-03T19:42:58.7744988Z   path: null,
2021-02-03T19:42:58.7745525Z   method: 'OPTIONS',
2021-02-03T19:42:58.7745941Z   headers: 
2021-02-03T19:42:58.7746450Z    { accept: 'application/json',
2021-02-03T19:42:58.7747079Z      'user-agent': 'node-Locations-api',
2021-02-03T19:42:58.7750522Z      Authorization: 'Basic dnN__REMOVED__==',
2021-02-03T19:42:58.7753280Z      'X-TFS-FedAuthRedirect': 'Suppress' },
2021-02-03T19:42:58.7753628Z   agent: 
2021-02-03T19:42:58.7753795Z    Agent {
2021-02-03T19:42:58.7754424Z      domain: null,
2021-02-03T19:42:58.7754645Z      _events: { free: [Function] },
2021-02-03T19:42:58.7754885Z      _eventsCount: 1,
2021-02-03T19:42:58.7755369Z      _maxListeners: undefined,
2021-02-03T19:42:58.7755824Z      defaultPort: 443,
2021-02-03T19:42:58.7756196Z      protocol: 'https:',
2021-02-03T19:42:58.7756435Z      options: { path: null },
2021-02-03T19:42:58.7756635Z      requests: {},
2021-02-03T19:42:58.7757039Z      sockets: { 'rigsystemsis.visualstudio.com:443:::::::::': [] },
2021-02-03T19:42:58.7757740Z      freeSockets: {},
2021-02-03T19:42:58.7757946Z      keepAliveMsecs: 1000,
2021-02-03T19:42:58.7758166Z      keepAlive: false,
2021-02-03T19:42:58.7758365Z      maxSockets: Infinity,
2021-02-03T19:42:58.7758586Z      maxFreeSockets: 256,
2021-02-03T19:42:58.7758800Z      maxCachedSessions: 100,
2021-02-03T19:42:58.7759478Z      _sessionCache: { map: {}, list: [] } },
2021-02-03T19:42:58.7759950Z   _agentKey: 'rigsystemsis.visualstudio.com:443:::::::::' }
2021-02-03T19:42:58.7760291Z HTTP 94566: sockets rigsystemsis.visualstudio.com:443::::::::: 1
2021-02-03T19:42:58.7760561Z HTTP 94566: outgoing message end.
2021-02-03T19:42:58.7760802Z HTTP 94566: AGENT incoming response!
2021-02-03T19:42:58.7761032Z HTTP 94566: AGENT isHeadResponse false
2021-02-03T19:42:58.7761442Z HTTP 94566: AGENT socket.destroySoon()
2021-02-03T19:42:58.7761788Z HTTP 94566: call onSocket 1 0
2021-02-03T19:42:58.7762435Z HTTP 94566: createConnection rigsystemsis.visualstudio.com:443::::::::: { servername: 'rigsystemsis.visualstudio.com',
2021-02-03T19:42:58.7762960Z   _defaultAgent: 
2021-02-03T19:42:58.7763231Z    Agent {
2021-02-03T19:42:58.7763549Z      domain: null,
2021-02-03T19:42:58.7764228Z      _events: { free: [Function] },
2021-02-03T19:42:58.7764456Z      _eventsCount: 1,
2021-02-03T19:42:58.7764960Z      _maxListeners: undefined,
2021-02-03T19:42:58.7765166Z      defaultPort: 443,
2021-02-03T19:42:58.7765566Z      protocol: 'https:',
2021-02-03T19:42:58.7765784Z      options: { path: null },
2021-02-03T19:42:58.7765983Z      requests: {},
2021-02-03T19:42:58.7766627Z      sockets: { 'rigsystemsis.visualstudio.com:443:::::::::': [Object] },
2021-02-03T19:42:58.7767047Z      freeSockets: {},
2021-02-03T19:42:58.7767350Z      keepAliveMsecs: 1000,
2021-02-03T19:42:58.7767591Z      keepAlive: false,
2021-02-03T19:42:58.7767808Z      maxSockets: Infinity,
2021-02-03T19:42:58.7768011Z      maxFreeSockets: 256,
2021-02-03T19:42:58.7768365Z      maxCachedSessions: 100,
2021-02-03T19:42:58.7768701Z      _sessionCache: { map: [Object], list: [Object] } },
2021-02-03T19:42:58.7769308Z   host: 'rigsystemsis.visualstudio.com',
2021-02-03T19:42:58.7769643Z   port: 443,
2021-02-03T19:42:58.7769871Z   path: null,
2021-02-03T19:42:58.7770162Z   method: 'GET',
2021-02-03T19:42:58.7770356Z   headers: 
2021-02-03T19:42:58.7770912Z    { accept: 'application/json;api-version=5.1-preview.1',
2021-02-03T19:42:58.7771461Z      'user-agent': 'node-Locations-api',
2021-02-03T19:42:59.7561576Z      Authorization: 'Basic dnN__REMOVED__==',
2021-02-03T19:42:59.7566180Z ##[debug]Successfully acquired the connection data
2021-02-03T19:42:59.7626092Z      'X-TFS-FedAuthRedirect': 'Suppress' },
2021-02-03T19:42:59.7627723Z ##[debug]Unable to get packaging URIs
2021-02-03T19:42:59.7628286Z   agent: 
2021-02-03T19:42:59.7628989Z ##[debug]Cannot read property 'locationServiceData' of null
2021-02-03T19:42:59.7629423Z    Agent {
2021-02-03T19:42:59.7630731Z ##[debug]TypeError: Cannot read property 'locationServiceData' of null
    at Object.<anonymous> (/opt/novapps/adb/agent-04/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.180.0/node_modules/packaging-common/locationUtilities.js:96:50)
    at next (native)
    at fulfilled (/opt/novapps/adb/agent-04/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.180.0/node_modules/packaging-common/locationUtilities.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
2021-02-03T19:42:59.7631860Z      domain: null,
2021-02-03T19:42:59.7632634Z ##[debug]Agent.BuildDirectory=/opt/novapps/adb/agent-04/_work/84
2021-02-03T19:42:59.7633190Z      _events: { free: [Function] },
2021-02-03T19:42:59.7634037Z ##[debug]testing directory '/opt/novapps/adb/agent-04/_work/84/npm'
2021-02-03T19:42:59.7634494Z      _eventsCount: 1,
2021-02-03T19:42:59.7635247Z ##[debug]testing directory '/opt/novapps/adb/agent-04/_work/84'
2021-02-03T19:42:59.7635727Z      _maxListeners: undefined,
2021-02-03T19:42:59.7636891Z ##[debug]mkdir '/opt/novapps/adb/agent-04/_work/84/npm'
2021-02-03T19:42:59.7637376Z      defaultPort: 443,
2021-02-03T19:42:59.7637849Z ##[debug]rm -rf /opt/novapps/adb/agent-04/_work/84/npm
2021-02-03T19:42:59.7638415Z      protocol: 'https:',
2021-02-03T19:42:59.7638757Z ##[debug]removing directory
2021-02-03T19:42:59.7639113Z      options: { path: null },
2021-02-03T19:42:59.7639456Z ##[debug]task result: Failed
2021-02-03T19:42:59.7639819Z      requests: {},
2021-02-03T19:42:59.7668549Z ##[error]TypeError: Cannot read property 'locationServiceData' of null
2021-02-03T19:42:59.7678322Z ##[debug]Processed: ##vso[task.issue type=error;]TypeError: Cannot read property 'locationServiceData' of null
2021-02-03T19:42:59.7680012Z      sockets: { 'rigsystemsis.visualstudio.com:443:::::::::': [Object] },
2021-02-03T19:42:59.7687472Z ##[debug]Processed: ##vso[task.complete result=Failed;]TypeError: Cannot read property 'locationServiceData' of null
2021-02-03T19:42:59.7688097Z      freeSockets: {},
2021-02-03T19:42:59.7691407Z      keepAliveMsecs: 1000,
2021-02-03T19:42:59.7705871Z      keepAlive: false,
2021-02-03T19:42:59.7706381Z      maxSockets: Infinity,
2021-02-03T19:42:59.7706610Z      maxFreeSockets: 256,
2021-02-03T19:42:59.7706839Z      maxCachedSessions: 100,
2021-02-03T19:42:59.7707098Z      _sessionCache: { map: [Object], list: [Object] } },
2021-02-03T19:42:59.7707886Z   _agentKey: 'rigsystemsis.visualstudio.com:443:::::::::' }
2021-02-03T19:42:59.7708334Z HTTP 94566: sockets rigsystemsis.visualstudio.com:443::::::::: 2
2021-02-03T19:42:59.7708638Z HTTP 94566: outgoing message end.
2021-02-03T19:42:59.7708853Z HTTP 94566: CLIENT socket onClose
2021-02-03T19:42:59.7709212Z HTTP 94566: removeSocket rigsystemsis.visualstudio.com:443::::::::: writable: false
2021-02-03T19:42:59.7709518Z HTTP 94566: HTTP socket close
2021-02-03T19:42:59.7709752Z HTTP 94566: AGENT incoming response!
2021-02-03T19:42:59.7709980Z HTTP 94566: AGENT isHeadResponse false
2021-02-03T19:42:59.7710236Z HTTP 94566: AGENT socket.destroySoon()
2021-02-03T19:42:59.7710452Z HTTP 94566: call onSocket 0 0
2021-02-03T19:42:59.7711045Z HTTP 94566: createConnection rigsystemsis.pkgs.visualstudio.com:443::::::::: { servername: 'rigsystemsis.pkgs.visualstudio.com',
2021-02-03T19:42:59.7711404Z   _defaultAgent: 
2021-02-03T19:42:59.7711578Z    Agent {
2021-02-03T19:42:59.7711740Z      domain: null,
2021-02-03T19:42:59.7711958Z      _events: { free: [Function] },
2021-02-03T19:42:59.7712166Z      _eventsCount: 1,
2021-02-03T19:42:59.7712366Z      _maxListeners: undefined,
2021-02-03T19:42:59.7712583Z      defaultPort: 443,
2021-02-03T19:42:59.7712892Z      protocol: 'https:',
2021-02-03T19:42:59.7713315Z      options: { path: null },
2021-02-03T19:42:59.7713613Z      requests: {},
2021-02-03T19:42:59.7713801Z      sockets: 
2021-02-03T19:42:59.7714208Z       { 'rigsystemsis.visualstudio.com:443:::::::::': [Object],
2021-02-03T19:42:59.7714699Z         'rigsystemsis.pkgs.visualstudio.com:443:::::::::': [] },
2021-02-03T19:42:59.7714977Z      freeSockets: {},
2021-02-03T19:42:59.7715192Z      keepAliveMsecs: 1000,
2021-02-03T19:42:59.7715386Z      keepAlive: false,
2021-02-03T19:42:59.7715581Z      maxSockets: Infinity,
2021-02-03T19:42:59.7715801Z      maxFreeSockets: 256,
2021-02-03T19:42:59.7716005Z      maxCachedSessions: 100,
2021-02-03T19:42:59.7716280Z      _sessionCache: { map: [Object], list: [Object] } },
2021-02-03T19:42:59.7716684Z   host: 'rigsystemsis.pkgs.visualstudio.com',
2021-02-03T19:42:59.7716906Z   port: 443,
2021-02-03T19:42:59.7717061Z   path: null,
2021-02-03T19:42:59.7717349Z   method: 'OPTIONS',
2021-02-03T19:42:59.7717518Z   headers: 
2021-02-03T19:42:59.7717816Z    { accept: 'application/json',
2021-02-03T19:42:59.7718193Z      'user-agent': 'node-Locations-api',
2021-02-03T19:42:59.7721540Z      Authorization: 'Basic dnN__REMOVED__==',
2021-02-03T19:42:59.7724037Z      'X-TFS-FedAuthRedirect': 'Suppress' },
2021-02-03T19:42:59.7724271Z   agent: 
2021-02-03T19:42:59.7724422Z    Agent {
2021-02-03T19:42:59.7724597Z      domain: null,
2021-02-03T19:42:59.7724803Z      _events: { free: [Function] },
2021-02-03T19:42:59.7725028Z      _eventsCount: 1,
2021-02-03T19:42:59.7725229Z      _maxListeners: undefined,
2021-02-03T19:42:59.7725431Z      defaultPort: 443,
2021-02-03T19:42:59.7725757Z      protocol: 'https:',
2021-02-03T19:42:59.7725976Z      options: { path: null },
2021-02-03T19:42:59.7726188Z      requests: {},
2021-02-03T19:42:59.7726353Z      sockets: 
2021-02-03T19:42:59.7726762Z       { 'rigsystemsis.visualstudio.com:443:::::::::': [Object],
2021-02-03T19:42:59.7727240Z         'rigsystemsis.pkgs.visualstudio.com:443:::::::::': [] },
2021-02-03T19:42:59.7727530Z      freeSockets: {},
2021-02-03T19:42:59.7727732Z      keepAliveMsecs: 1000,
2021-02-03T19:42:59.7727946Z      keepAlive: false,
2021-02-03T19:42:59.7728142Z      maxSockets: Infinity,
2021-02-03T19:42:59.7728342Z      maxFreeSockets: 256,
2021-02-03T19:42:59.7728562Z      maxCachedSessions: 100,
2021-02-03T19:42:59.7728819Z      _sessionCache: { map: [Object], list: [Object] } },
2021-02-03T19:42:59.7729301Z   _agentKey: 'rigsystemsis.pkgs.visualstudio.com:443:::::::::' }
2021-02-03T19:42:59.7729650Z HTTP 94566: sockets rigsystemsis.pkgs.visualstudio.com:443::::::::: 1
2021-02-03T19:42:59.7729954Z HTTP 94566: outgoing message end.
2021-02-03T19:42:59.7730163Z HTTP 94566: CLIENT socket onClose
2021-02-03T19:42:59.7730548Z HTTP 94566: removeSocket rigsystemsis.visualstudio.com:443::::::::: writable: false
2021-02-03T19:42:59.7730837Z HTTP 94566: HTTP socket close
2021-02-03T19:42:59.7731069Z HTTP 94566: AGENT incoming response!
2021-02-03T19:42:59.7731305Z HTTP 94566: AGENT isHeadResponse false
2021-02-03T19:42:59.7731557Z HTTP 94566: AGENT socket.destroySoon()
2021-02-03T19:42:59.7731778Z HTTP 94566: call onSocket 1 0
2021-02-03T19:42:59.7732363Z HTTP 94566: createConnection rigsystemsis.pkgs.visualstudio.com:443::::::::: { servername: 'rigsystemsis.pkgs.visualstudio.com',
2021-02-03T19:42:59.7732790Z   _defaultAgent: 
2021-02-03T19:42:59.7732966Z    Agent {
2021-02-03T19:42:59.7733125Z      domain: null,
2021-02-03T19:42:59.7733346Z      _events: { free: [Function] },
2021-02-03T19:42:59.7733622Z      _eventsCount: 1,
2021-02-03T19:42:59.7733823Z      _maxListeners: undefined,
2021-02-03T19:42:59.7734041Z      defaultPort: 443,
2021-02-03T19:42:59.7734354Z      protocol: 'https:',
2021-02-03T19:42:59.7734594Z      options: { path: null },
2021-02-03T19:42:59.7734785Z      requests: {},
2021-02-03T19:42:59.7735231Z      sockets: { 'rigsystemsis.pkgs.visualstudio.com:443:::::::::': [Object] },
2021-02-03T19:42:59.7735521Z      freeSockets: {},
2021-02-03T19:42:59.7735811Z      keepAliveMsecs: 1000,
2021-02-03T19:42:59.7736005Z      keepAlive: false,
2021-02-03T19:42:59.7736219Z      maxSockets: Infinity,
2021-02-03T19:42:59.7736419Z      maxFreeSockets: 256,
2021-02-03T19:42:59.7736624Z      maxCachedSessions: 100,
2021-02-03T19:42:59.7736894Z      _sessionCache: { map: [Object], list: [Object] } },
2021-02-03T19:42:59.7737304Z   host: 'rigsystemsis.pkgs.visualstudio.com',
2021-02-03T19:42:59.7737523Z   port: 443,
2021-02-03T19:42:59.7737677Z   path: null,
2021-02-03T19:42:59.7737959Z   method: 'GET',
2021-02-03T19:42:59.7738122Z   headers: 
2021-02-03T19:42:59.7738489Z    { accept: 'application/json;api-version=5.1-preview.1',
2021-02-03T19:42:59.7738876Z      'user-agent': 'node-Locations-api',
2021-02-03T19:42:59.7742232Z      Authorization: 'Basic dnN__REMOVED__==',
2021-02-03T19:42:59.7744631Z      'X-TFS-FedAuthRedirect': 'Suppress' },
2021-02-03T19:42:59.7744861Z   agent: 
2021-02-03T19:42:59.7745009Z    Agent {
2021-02-03T19:42:59.7745183Z      domain: null,
2021-02-03T19:42:59.7745385Z      _events: { free: [Function] },
2021-02-03T19:42:59.7745607Z      _eventsCount: 1,
2021-02-03T19:42:59.7745811Z      _maxListeners: undefined,
2021-02-03T19:42:59.7746026Z      defaultPort: 443,
2021-02-03T19:42:59.7746331Z      protocol: 'https:',
2021-02-03T19:42:59.7746541Z      options: { path: null },
2021-02-03T19:42:59.7746849Z      requests: {},
2021-02-03T19:42:59.7747287Z      sockets: { 'rigsystemsis.pkgs.visualstudio.com:443:::::::::': [Object] },
2021-02-03T19:42:59.7747597Z      freeSockets: {},
2021-02-03T19:42:59.7747796Z      keepAliveMsecs: 1000,
2021-02-03T19:42:59.7748010Z      keepAlive: false,
2021-02-03T19:42:59.7748213Z      maxSockets: Infinity,
2021-02-03T19:42:59.7748429Z      maxFreeSockets: 256,
2021-02-03T19:42:59.7748634Z      maxCachedSessions: 100,
2021-02-03T19:42:59.7748903Z      _sessionCache: { map: [Object], list: [Object] } },
2021-02-03T19:42:59.7749373Z   _agentKey: 'rigsystemsis.pkgs.visualstudio.com:443:::::::::' }
2021-02-03T19:42:59.7749748Z HTTP 94566: sockets rigsystemsis.pkgs.visualstudio.com:443::::::::: 2
2021-02-03T19:42:59.7750039Z HTTP 94566: outgoing message end.
2021-02-03T19:42:59.7750255Z HTTP 94566: CLIENT socket onClose
2021-02-03T19:42:59.7750591Z HTTP 94566: removeSocket rigsystemsis.pkgs.visualstudio.com:443::::::::: writable: false
2021-02-03T19:42:59.7750904Z HTTP 94566: HTTP socket close
2021-02-03T19:42:59.7751147Z HTTP 94566: AGENT incoming response!
2021-02-03T19:42:59.7751426Z HTTP 94566: AGENT isHeadResponse false
2021-02-03T19:42:59.7751773Z HTTP 94566: SOCKET ERROR: read ECONNRESET Error: read ECONNRESET
2021-02-03T19:42:59.7752081Z     at exports._errnoException (util.js:1020:11)
2021-02-03T19:42:59.7752447Z     at TLSWrap.onread (net.js:580:26)
2021-02-03T19:42:59.7752680Z HTTP 94566: CLIENT socket onClose
2021-02-03T19:42:59.7753022Z HTTP 94566: removeSocket rigsystemsis.pkgs.visualstudio.com:443::::::::: writable: false
2021-02-03T19:42:59.7753332Z HTTP 94566: HTTP socket close
2021-02-03T19:42:59.7763020Z ##[section]Finishing: npm install

**Comment by zhenghao104** [comment]
@anatolybolshakov  
A recent [commit](https://github.com/microsoft/azure-pipelines-tasks/commit/6e24f3b285397073443f29db64e654e578f885db#diff-2a16291e21f5d87ab0937629d2bed76d67019a344b2d1e4c05270cbba7000794) forces the task to fail if location service call fails, and the logs showed that [getConnectionData](https://github.com/microsoft/azure-pipelines-tasks/blob/a6ec2c2e967c4e792ac81654c39dc46811ff5e28/common-npm-packages/packaging-common/locationUtilities.ts#L95) return null without throwing an error, does the pipeline team knows what may cause this?

**Comment by anatolybolshakov** [comment]
@zhenghao104 we didn't faced similar issues before... Could there be some issue on azure-pipelines-node-api side or with api?

**Comment by IanBFarrell** [comment]
Thank you for the help trying to figure this out and resolve this. Is there anything I can do to help with this? It has been a problem for a couple months now and it is starting to wear on our development group. We basically have to run most build multiple times, hoping for it to succeed.

**Comment by zhenghao104** [comment]
@anatolybolshakov The previous implementation will set the packagingUrl to a default one, and hide away the error. The recent commit i linked above force it to fail and throw the error, I think we need more information on what may be causing getConnectionData to return null, if you know who can help on this issue that would be great.

**Comment by lpgoncalves** [comment]
Any updates?

**Comment by IanBFarrell** [comment]
I am really hoping to have some updates for this issue, so we can have a clean build pipeline.

Thanks

**Comment by anatolybolshakov** [comment]
@IanBFarrell @lpgoncalves do you experience any issues with agent network? Is it reproducible for you for agent on other machines/hosted agents?
@zhenghao104 there is an ECONNRESET error during package uri's request - looks like connection is being reset for some reason.

**Comment by IanBFarrell** [comment]
I have two different build agents and it happens on both of them.

**Comment by anatolybolshakov** [comment]
@IanBFarrell are they located on different machines/networks?

**Comment by IanBFarrell** [comment]
They are for sure on the same network, but are different vms.

**Comment by hamillwj** [comment]
Is there any update on this? Ian has moved on and I'm taking over this project. We're in desperate need of a more dependable CI pipeline.

**Comment by praveen-jayaraman-arch** [comment]
Was there any resolution for this issue?
