### ISSUE TITLE
Publishing code coverage results with VSTest task is slow or fails with timeout

### ISSUE THREAD

**Issue by hollowdrutt** [microsoft/azure-pipelines-tasks#14304]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest@2

## Environment
Azure Pipelines
Private Agent running on VM in Azure
OS: Windows Server 2016
Agent version:2.179.0

## Issue Description

I am using the VSTest@2 task to run tests with code coverage enabled and publishing the coverage results to be able to see code coverage in Pull Requests.

The task looks like

```yml
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Contoso.dll
      !**\obj\**
      !**\contoso\bin\debug\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    runSettingsFile: 'test.runsettings'
    testFiltercriteria: 'FullyQualifiedName!=Contoso.Tests.SlowTest'
    codeCoverageEnabled: true
```

Running the tests takes ~5 minutes, uploading the results, a ~3.5MB large .TRX file and a ~7.8 MB large .coverage file takes at least 5 minutes, sometimes the upload will fail after 10-15 minutes with a message such as:
```
2021-01-28T10:06:41.7183728Z **************** Completed test execution *********************
2021-01-28T10:06:41.7184628Z Test results files: C:\agent\_work\_temp\TestResults\CONTOSO.trx
2021-01-28T10:06:44.1164698Z Created test run: 1016834
2021-01-28T10:06:44.1167066Z Publishing test results: 1072
2021-01-28T10:06:44.8173928Z Publishing test results to test run '1016834'.
2021-01-28T10:06:44.8176020Z TestResults To Publish 1072, Test run id:1016834
2021-01-28T10:06:44.8349898Z Test results publishing 1000, remaining: 72. Test run id: 1016834
2021-01-28T10:06:46.1272410Z Test results publishing 72, remaining: 0. Test run id: 1016834
2021-01-28T10:06:46.2645975Z Published test results: 1072
2021-01-28T10:06:46.2646931Z Publishing Attachments: 2
2021-01-28T10:21:47.6180514Z ##[warning]Failed to upload file CONTOSO.trx to Blob Transfer exception with errorcode Unknown, exception message Microsoft.Azure.Storage.DataMovement.TransferException: The transfer failed. ---> Microsoft.Azure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
2021-01-28T10:21:47.6182381Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-01-28T10:21:47.6182856Z    at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
2021-01-28T10:21:47.6183190Z    --- End of inner exception stack trace ---
2021-01-28T10:21:47.6183591Z    --- End of inner exception stack trace ---
2021-01-28T10:21:47.6183924Z    at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
2021-01-28T10:21:47.6184318Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.6184657Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.6185029Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.6185558Z    at Microsoft.Azure.Storage.Blob.CloudBlockBlob.<UploadFromStreamAsyncHelper>d__31.MoveNext()
2021-01-28T10:21:47.6186074Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.6186462Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.6186865Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.6187361Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<DoUploadAndSetBlobAttributes>d__26.MoveNext()
2021-01-28T10:21:47.6187810Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.6188198Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.6188597Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.6189160Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<UploadBlobAndSetAttributesAsync>d__25.MoveNext()
2021-01-28T10:21:47.6189600Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.6189941Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.6296565Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.6297224Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<DoWorkInternalAsync>d__17.MoveNext()
2021-01-28T10:21:47.6297693Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.6298074Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.6298454Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.6298925Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.SyncTransferController.<DoWorkInternalAsync>d__14.MoveNext()
2021-01-28T10:21:47.6299348Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.6299716Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.6300097Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.6300803Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.TransferControllerBase.<DoWorkAsync>d__34.MoveNext()
2021-01-28T10:21:47.6301215Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.6301572Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.6302233Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.6314904Z    at Microsoft.Azure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__28.MoveNext()
2021-01-28T10:21:47.6315870Z    --- End of inner exception stack trace ---
2021-01-28T10:21:47.6316275Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<_executeWithRetry>d__33.MoveNext()
2021-01-28T10:21:47.6316694Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.6317050Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.6317436Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.6317858Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<UploadInternalAsync>d__19.MoveNext()
2021-01-28T10:21:47.6318243Z Failed to upload run logs to LogStore, Trying to upload to FileService
2021-01-28T10:21:47.7127537Z ##[warning]Failed to upload file CONTOSO.coverageto Blob Transfer exception with errorcode Unknown, exception message Microsoft.Azure.Storage.DataMovement.TransferException: The transfer failed. ---> Microsoft.Azure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
2021-01-28T10:21:47.7129978Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-01-28T10:21:47.7130633Z    at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
2021-01-28T10:21:47.7163570Z    --- End of inner exception stack trace ---
2021-01-28T10:21:47.7164137Z    --- End of inner exception stack trace ---
2021-01-28T10:21:47.7164523Z    at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
2021-01-28T10:21:47.7164887Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.7165317Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.7165693Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.7166236Z    at Microsoft.Azure.Storage.Blob.CloudBlockBlob.<UploadFromStreamAsyncHelper>d__31.MoveNext()
2021-01-28T10:21:47.7166620Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.7166983Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.7170177Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.7170755Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<DoUploadAndSetBlobAttributes>d__26.MoveNext()
2021-01-28T10:21:47.7171212Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.7171556Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.7171940Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.7172388Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<UploadBlobAndSetAttributesAsync>d__25.MoveNext()
2021-01-28T10:21:47.7172804Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.7173424Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.7173792Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.7174242Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<DoWorkInternalAsync>d__17.MoveNext()
2021-01-28T10:21:47.7174767Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.7175171Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.7175578Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.7176132Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.SyncTransferController.<DoWorkInternalAsync>d__14.MoveNext()
2021-01-28T10:21:47.7176584Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.7176944Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.7177362Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.7177820Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.TransferControllerBase.<DoWorkAsync>d__34.MoveNext()
2021-01-28T10:21:47.7178242Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.7178626Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.7179015Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.7179555Z    at Microsoft.Azure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__28.MoveNext()
2021-01-28T10:21:47.7179889Z    --- End of inner exception stack trace ---
2021-01-28T10:21:47.7180257Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<_executeWithRetry>d__33.MoveNext()
2021-01-28T10:21:47.7180651Z --- End of stack trace from previous location where exception was thrown ---
2021-01-28T10:21:47.7180985Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-01-28T10:21:47.7486876Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-01-28T10:21:47.7487538Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<UploadInternalAsync>d__19.MoveNext()
2021-01-28T10:21:47.7488061Z Failed to upload run logs to LogStore, Trying to upload to FileService
2021-01-28T10:21:48.5820574Z Failed to publish Telemetry Exception: Object reference not set to an instance of an object.
2021-01-28T10:21:54.4232794Z Completed TestExecution Model...
2021-01-28T10:21:54.4624368Z ##[section]Finishing: VSTest
```

**Comment by phanikmmsft** [comment]
@ganesp @anshii03  pls triage this

**Comment by navin22** [comment]
@hollowdrutt Is the agent behind a firewall? If yes can we get the fiddler traces and see if any URLs are blocked 

Follow the below documents for whitelisting the URLs needed for the PTR task.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#im-running-a-firewall-and-my-code-is-in-azure-repos-what-urls-does-the-agent-need-to-communicate-with

**Comment by hollowdrutt** [comment]
@navin22 I ran the build on different times of day and on different days with the agent going through Fiddler.
I have not been able to capture when upload of test reports fails, but eventhough the .coverage and .trx files are about the same size, the time it takes to upload varies quite a lot.
The build server is running in a VM in Azure North Europe

```
Host: etqtcmprodweu11.vstmrblob.vsassets.io
Content-Length: 7979748



Request Count:   1
Bytes Sent:      7,980,450		(headers:702; body:7,979,748)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	11:58:30.049
ClientBeginRequest:	11:58:30.971
GotRequestHeaders:	11:58:30.971
ClientDoneRequest:	12:03:23.640
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	12:03:22.693
FiddlerBeginRequest:	12:03:23.642
ServerGotRequest:	12:03:23.754
ServerBeginResponse:	12:03:23.863
GotResponseHeaders:	12:03:23.863
ServerDoneResponse:	12:03:23.863
ClientBeginResponse:	12:03:23.863
ClientDoneResponse:	12:03:23.863

	Overall Elapsed:	0:04:52.892
	
	
	
Host: etqtcmprodweu11.vstmrblob.vsassets.io
Content-Length: 3574973


Request Count:   1
Bytes Sent:      3,575,678		(headers:705; body:3,574,973)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	11:58:30.049
ClientBeginRequest:	11:58:30.987
GotRequestHeaders:	11:58:30.987
ClientDoneRequest:	12:03:22.232
Determine Gateway:	0ms
DNS Lookup: 		424ms
TCP/IP Connect:	35ms
HTTPS Handshake:	12ms
ServerConnected:	12:03:22.693
FiddlerBeginRequest:	12:03:22.705
ServerGotRequest:	12:03:22.933
ServerBeginResponse:	12:03:23.072
GotResponseHeaders:	12:03:23.072
ServerDoneResponse:	12:03:23.072
ClientBeginResponse:	12:03:23.072
ClientDoneResponse:	12:03:23.072

	Overall Elapsed:	0:04:52.085
	
	
Host: etqtcmprodweu11.vstmrblob.vsassets.io
Content-Length: 7978836
	
	
	
	
Request Count:   1
Bytes Sent:      7,979,540		(headers:704; body:7,978,836)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	10:09:36.773
ClientBeginRequest:	10:09:37.626
GotRequestHeaders:	10:09:37.626
ClientDoneRequest:	10:09:38.240
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	10:09:36.783
FiddlerBeginRequest:	10:09:38.250
ServerGotRequest:	10:09:38.497
ServerBeginResponse:	10:09:38.638
GotResponseHeaders:	10:09:38.638
ServerDoneResponse:	10:09:38.638
ClientBeginResponse:	10:09:38.638
ClientDoneResponse:	10:09:38.638

	Overall Elapsed:	0:00:01.012		

	
Host: etqtcmprodweu11.vstmrblob.vsassets.io
Content-Length: 4367889


	
Request Count:   1
Bytes Sent:      4,368,596		(headers:707; body:4,367,889)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	10:09:36.779
ClientBeginRequest:	10:09:37.662
GotRequestHeaders:	10:09:37.662
ClientDoneRequest:	10:09:38.048
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	10:09:36.783
FiddlerBeginRequest:	10:09:38.050
ServerGotRequest:	10:09:38.160
ServerBeginResponse:	10:09:38.283
GotResponseHeaders:	10:09:38.283
ServerDoneResponse:	10:09:38.283
ClientBeginResponse:	10:09:38.283
ClientDoneResponse:	10:09:38.283

	Overall Elapsed:	0:00:00.621	
	
	
Host: etqtcmprodweu11.vstmrblob.vsassets.io
Content-Length: 7979748


Request Count:   1
Bytes Sent:      7,980,448		(headers:700; body:7,979,748)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	08:56:58.252
ClientBeginRequest:	08:56:59.040
GotRequestHeaders:	08:56:59.040
ClientDoneRequest:	08:58:49.812
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	08:58:48.785
FiddlerBeginRequest:	08:58:49.816
ServerGotRequest:	08:58:49.880
ServerBeginResponse:	08:58:50.055
GotResponseHeaders:	08:58:50.055
ServerDoneResponse:	08:58:50.055
ClientBeginResponse:	08:58:50.055
ClientDoneResponse:	08:58:50.055

	Overall Elapsed:	0:01:51.014
	

Host: etqtcmprodweu11.vstmrblob.vsassets.io
Content-Length: 3628133


Request Count:   1
Bytes Sent:      3,628,836		(headers:703; body:3,628,133)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------

NOTE: This request was retried after a Send operation failed.

ClientConnected:	08:56:58.251
ClientBeginRequest:	08:56:59.000
GotRequestHeaders:	08:56:59.000
ClientDoneRequest:	08:58:48.780
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	3ms
HTTPS Handshake:	2ms
ServerConnected:	08:58:48.785
FiddlerBeginRequest:	08:58:48.788
ServerGotRequest:	08:58:48.812
ServerBeginResponse:	08:58:48.875
GotResponseHeaders:	08:58:48.875
ServerDoneResponse:	08:58:48.875
ClientBeginResponse:	08:58:48.875
ClientDoneResponse:	08:58:48.875

	Overall Elapsed:	0:01:49.874

RESPONSE BYTES (by Content-Type)
--------------
~headers~: 508	
```

**Comment by vivek425ster** [comment]
@hollowdrutt Is this still happening for you?
If yes, can you please share some recent timestamps during which this happened ?
Also, Is this issue persistent or it happens transiently ?

**Comment by suyash691** [comment]
@hollowdrutt Any data available as per @vivek425ster and @navin22's request

**Comment by hollowdrutt** [comment]
@vivek425ster  @navin22 @suyash691 
I have run builds at different times of day, I have not had any time outs during these attempts, but the time to upload the code coverage varies between 1m 50s - 5m 52s

The calls are to etqtcmprodweu11.vstmrblob.vsassets.io
The time stamps are in UTC
```
2021-04-29:

Bytes Sent:      3,541,540		(headers:703; body:3,540,837)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	15:21:51.625
ClientBeginRequest:	15:21:52.130
GotRequestHeaders:	15:21:52.130
ClientDoneRequest:	15:27:22.412
Determine Gateway:	0ms
DNS Lookup: 		8ms
TCP/IP Connect:	1ms
HTTPS Handshake:	19ms
ServerConnected:	15:27:22.422
FiddlerBeginRequest:	15:27:22.443
ServerGotRequest:	15:27:22.468
ServerBeginResponse:	15:27:22.614
GotResponseHeaders:	15:27:22.614
ServerDoneResponse:	15:27:22.614
ClientBeginResponse:	15:27:22.614
ClientDoneResponse:	15:27:22.614

	Overall Elapsed:	0:05:30.483
	
Request Count:   1
Bytes Sent:      7,988,387		(headers:700; body:7,987,687)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	15:21:51.626
ClientBeginRequest:	15:21:52.406
GotRequestHeaders:	15:21:52.406
ClientDoneRequest:	15:27:23.579
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	15:27:22.422
FiddlerBeginRequest:	15:27:23.584
ServerGotRequest:	15:27:23.652
ServerBeginResponse:	15:27:23.842
GotResponseHeaders:	15:27:23.843
ServerDoneResponse:	15:27:23.843
ClientBeginResponse:	15:27:23.843
ClientDoneResponse:	15:27:23.843

	Overall Elapsed:	0:05:31.436

----	

2021-04-30:

Request Count:   1
Bytes Sent:      7,988,393		(headers:706; body:7,987,687)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	06:35:33.665
ClientBeginRequest:	06:35:34.201
GotRequestHeaders:	06:35:34.201
ClientDoneRequest:	06:41:26.242
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	06:41:25.683
FiddlerBeginRequest:	06:41:26.246
ServerGotRequest:	06:41:26.363
ServerBeginResponse:	06:41:26.593
GotResponseHeaders:	06:41:26.593
ServerDoneResponse:	06:41:26.593
ClientBeginResponse:	06:41:26.593
ClientDoneResponse:	06:41:26.593

	Overall Elapsed:	0:05:52.391
	
Request Count:   1
Bytes Sent:      3,623,187		(headers:709; body:3,622,478)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	06:35:33.666
ClientBeginRequest:	06:35:34.665
GotRequestHeaders:	06:35:34.665
ClientDoneRequest:	06:41:25.292
Determine Gateway:	0ms
DNS Lookup: 		387ms
TCP/IP Connect:	2ms
HTTPS Handshake:	9ms
ServerConnected:	06:41:25.683
FiddlerBeginRequest:	06:41:25.692
ServerGotRequest:	06:41:25.723
ServerBeginResponse:	06:41:25.943
GotResponseHeaders:	06:41:25.943
ServerDoneResponse:	06:41:25.943
ClientBeginResponse:	06:41:25.943
ClientDoneResponse:	06:41:25.943

	Overall Elapsed:	0:05:51.277	
	
-------	

Request Count:   1
Bytes Sent:      7,988,371		(headers:702; body:7,987,669)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------

NOTE: This request was retried after a Send operation failed.

ClientConnected:	09:43:27.476
ClientBeginRequest:	09:43:28.062
GotRequestHeaders:	09:43:28.062
ClientDoneRequest:	09:45:18.147
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	4ms
HTTPS Handshake:	2ms
ServerConnected:	09:45:18.156
FiddlerBeginRequest:	09:45:18.159
ServerGotRequest:	09:45:18.221
ServerBeginResponse:	09:45:18.470
GotResponseHeaders:	09:45:18.470
ServerDoneResponse:	09:45:18.470
ClientBeginResponse:	09:45:18.470
ClientDoneResponse:	09:45:18.470

	Overall Elapsed:	0:01:50.407

Request Count:   1
Bytes Sent:      3,604,213		(headers:705; body:3,603,508)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	09:43:27.476
ClientBeginRequest:	09:43:28.017
GotRequestHeaders:	09:43:28.017
ClientDoneRequest:	09:48:37.991
Determine Gateway:	0ms
DNS Lookup: 		204ms
TCP/IP Connect:	0ms
HTTPS Handshake:	9ms
ServerConnected:	09:48:38.198
FiddlerBeginRequest:	09:48:38.208
ServerGotRequest:	09:48:38.370
ServerBeginResponse:	09:48:38.504
GotResponseHeaders:	09:48:38.504
ServerDoneResponse:	09:48:38.504
ClientBeginResponse:	09:48:38.504
ClientDoneResponse:	09:48:38.504

	Overall Elapsed:	0:05:10.486	
----
Request Count:   1
Bytes Sent:      3,560,923		(headers:707; body:3,560,216)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	11:59:21.688
ClientBeginRequest:	11:59:22.233
GotRequestHeaders:	11:59:22.233
ClientDoneRequest:	12:04:32.249
Determine Gateway:	0ms
DNS Lookup: 		396ms
TCP/IP Connect:	1ms
HTTPS Handshake:	15ms
ServerConnected:	12:04:32.649
FiddlerBeginRequest:	12:04:32.664
ServerGotRequest:	12:04:32.718
ServerBeginResponse:	12:04:32.832
GotResponseHeaders:	12:04:32.832
ServerDoneResponse:	12:04:32.832
ClientBeginResponse:	12:04:32.832
ClientDoneResponse:	12:04:32.832

	Overall Elapsed:	0:05:10.598


	
	Request Count:   1
Bytes Sent:      7,988,391		(headers:704; body:7,987,687)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	11:59:21.688
ClientBeginRequest:	11:59:22.232
GotRequestHeaders:	11:59:22.232
ClientDoneRequest:	12:04:32.241
Determine Gateway:	0ms
DNS Lookup: 		404ms
TCP/IP Connect:	1ms
HTTPS Handshake:	13ms
ServerConnected:	12:04:32.648
FiddlerBeginRequest:	12:04:32.662
ServerGotRequest:	12:04:32.955
ServerBeginResponse:	12:04:33.079
GotResponseHeaders:	12:04:33.079
ServerDoneResponse:	12:04:33.079
ClientBeginResponse:	12:04:33.079
ClientDoneResponse:	12:04:33.080

	Overall Elapsed:	0:05:10.847
	
----		
	
2021-05-04:

Request Count:   1
Bytes Sent:      3,613,546		(headers:707; body:3,612,839)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------

NOTE: This request was retried after a Send operation failed.

ClientConnected:	13:17:23.337
ClientBeginRequest:	13:17:24.439
GotRequestHeaders:	13:17:24.439
ClientDoneRequest:	13:19:14.365
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	4ms
HTTPS Handshake:	2ms
ServerConnected:	13:19:14.370
FiddlerBeginRequest:	13:19:14.373
ServerGotRequest:	13:19:14.510
ServerBeginResponse:	13:19:14.700
GotResponseHeaders:	13:19:14.701
ServerDoneResponse:	13:19:14.701
ClientBeginResponse:	13:19:14.701
ClientDoneResponse:	13:19:14.701

	Overall Elapsed:	0:01:50.261	
	
	
Request Count:   1
Bytes Sent:      7,988,391		(headers:704; body:7,987,687)
Bytes Received:  508		(headers:508; body:0)

ACTUAL PERFORMANCE
--------------
ClientConnected:	13:17:23.339
ClientBeginRequest:	13:17:24.813
GotRequestHeaders:	13:17:24.813
ClientDoneRequest:	13:19:15.081
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	13:19:14.370
FiddlerBeginRequest:	13:19:15.083
ServerGotRequest:	13:19:15.154
ServerBeginResponse:	13:19:15.310
GotResponseHeaders:	13:19:15.310
ServerDoneResponse:	13:19:15.310
ClientBeginResponse:	13:19:15.310
ClientDoneResponse:	13:19:15.310

	Overall Elapsed:	0:01:50.497	
```

**Comment by hollowdrutt** [comment]
Since I have gotten no more feedback here and I still have the same problem I decided to disable publishing the code coverage but then I ran into the issue that the test task ignores the publishRunAttachments parameter, which is described in this issue which was closed without any response #13798

**Comment by dhabierre** [comment]
Hi @hollowdrutt,

Any feedback about `publishRunAttachments`?
Have you found a solution to disable publishing or bypass the slow timeout?

Thanks.

**Comment by hollowdrutt** [comment]
@dhabierre Unfortunately no. No feedback and I haven't found any solution. I disabled generating code coverage in the test runner.

**Comment by JaneMaTest** [comment]
@hollowdrutt I resolved this issue by adding `https://*.vsassets.io` to my proxy whitelist.
