### ISSUE TITLE
OData filter does not work for "az rest" call in AzureCLI@2

### ISSUE THREAD

**Issue by schmidtd-enb** [microsoft/azure-pipelines-tasks#14485]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: AzureCLI@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines

- Agent - Hosted or Private: 
    Hosted

## Issue Description

Executing task in YAML as follows:

steps:
- task: AzureCLI@2
  displayName: 'Get application information'
  inputs:
    azureSubscription: ${{ parameters.azureConnection }}
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az rest --method GET --url 'https://graph.microsoft.com/v1.0/applications?$filter=appId eq ${{ parameters.appId }}' --query '\"value\"' --debug

Execution returns the bad request error "Invalid filter clause". I have tried to apply the filter contents in the "--uri-parameters" parameter, but the filter text is parsed by string instead:

Command arguments: ['rest', '--method', 'GET', '--url', 'https://graph.microsoft.com/v1.0/applications', '--uri-parameters', '"$filter=appId', 'eq', '\'***\'"', '--query', '"value"', '--debug']

### Task logs

2021-02-26T17:29:55.9940887Z DEBUG: cli.knack.cli: Command arguments: ['rest', '--method', 'GET', '--url', 'https://graph.microsoft.com/v1.0/applications?$filter=appId eq ***', '--query', '"value"', '--debug']
2021-02-26T17:29:55.9942752Z DEBUG: cli.knack.cli: __init__ debug log:
2021-02-26T17:29:55.9944880Z Cannot enable color.
2021-02-26T17:29:55.9945946Z DEBUG: cli.knack.cli: Event: Cli.PreExecute []
2021-02-26T17:29:55.9947335Z DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x02EA0F18>, <function OutputProducer.on_global_arguments at 0x02F3D3D8>, <function CLIQuery.on_global_arguments at 0x02F5A348>]
2021-02-26T17:29:56.0477119Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
2021-02-26T17:29:56.0478598Z DEBUG: cli.azure.cli.core: Modules found from index for 'rest': ['azure.cli.command_modules.util']
2021-02-26T17:29:56.0479331Z DEBUG: cli.azure.cli.core: Loading command modules:
2021-02-26T17:29:56.0480008Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
2021-02-26T17:29:56.0555796Z DEBUG: cli.azure.cli.core: util                      0.003         2         4
2021-02-26T17:29:56.0556783Z DEBUG: cli.azure.cli.core: Total (1)                 0.003         2         4
2021-02-26T17:29:56.0581289Z DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples']
2021-02-26T17:29:56.0582458Z DEBUG: cli.azure.cli.core: Loading extensions:
2021-02-26T17:29:56.0584541Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
2021-02-26T17:29:56.0586128Z DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0  
2021-02-26T17:29:56.0587775Z DEBUG: cli.azure.cli.core: Loaded 2 groups, 4 commands.
2021-02-26T17:29:56.0588904Z DEBUG: cli.azure.cli.core: Found a match in the command table.
2021-02-26T17:29:56.0589880Z DEBUG: cli.azure.cli.core: Raw command  : rest
2021-02-26T17:29:56.0590832Z DEBUG: cli.azure.cli.core: Command table: rest
2021-02-26T17:29:56.0592037Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03285738>]
2021-02-26T17:29:56.0601084Z INFO: az_command_data_logger: command args: rest --method {} --url {} --query {} --debug
2021-02-26T17:29:56.0602572Z DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'D:\a\_temp\.azclitask\commands'.
2021-02-26T17:29:56.0613762Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x032E3270>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x032E39C0>]
2021-02-26T17:29:56.0782012Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
2021-02-26T17:29:56.0783276Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x032E3A08>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x032E3A98>]
2021-02-26T17:29:56.0796381Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
2021-02-26T17:29:56.0797176Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
2021-02-26T17:29:56.0870144Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x02F3D420>, <function CLIQuery.handle_query_parameter at 0x02F5A390>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x032E3978>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x032E3A50>]
2021-02-26T17:29:56.3071594Z DEBUG: cli.azure.cli.core.util: Retrieving token for resource https://graph.microsoft.com/
2021-02-26T17:29:56.3072832Z DEBUG: cli.azure.cli.core._profile: Profile.get_raw_token invoked with resource='https://graph.microsoft.com/', subscription=None, tenant=None
2021-02-26T17:29:56.3643068Z DEBUG: cli.azure.cli.core.util: attempting to read file D:\a\_temp\.azclitask\accessTokens.json as utf-8-sig
2021-02-26T17:29:56.3653304Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - Authority:Performing instance discovery: ...
2021-02-26T17:29:56.3654878Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - Authority:Performing static instance discovery
2021-02-26T17:29:56.3657943Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - Authority:Authority validated via static instance discovery
2021-02-26T17:29:56.3659473Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - TokenRequest:Getting token with client credentials.
2021-02-26T17:29:56.3660894Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - TokenRequest:No user_id passed for cache query
2021-02-26T17:29:56.3662290Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - CacheDriver:finding with query keys: {'_clientId': '...'}
2021-02-26T17:29:56.3663771Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - CacheDriver:Looking for potential cache entries: {'_clientId': '...'}
2021-02-26T17:29:56.3666382Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - CacheDriver:Found 0 potential entries.
2021-02-26T17:29:56.3749192Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
2021-02-26T17:29:56.6112434Z DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /***/oauth2/token HTTP/1.1" 200 1721
2021-02-26T17:29:56.6142929Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - OAuth2Client:Get Token Server returned this correlation_id: df44b551-b489-4218-aa52-087499636afd
2021-02-26T17:29:56.6144754Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - CacheDriver:Adding entry AccessTokenId: b'1ct044l/Dz/Cd0py2JQci1lCgGBcF184bjidR+En8N8='
2021-02-26T17:29:56.6146058Z DEBUG: adal-python: df44b551-b489-4218-aa52-087499636afd - CacheDriver:Added entry is MRRT
2021-02-26T17:29:56.6186912Z INFO: cli.azure.cli.core.util: Request URL: 'https://graph.microsoft.com/v1.0/applications?$filter=appId%20eq%20***'
2021-02-26T17:29:56.6187862Z INFO: cli.azure.cli.core.util: Request method: 'GET'
2021-02-26T17:29:56.6188457Z INFO: cli.azure.cli.core.util: Request headers:
2021-02-26T17:29:56.6189643Z INFO: cli.azure.cli.core.util:     'User-Agent': 'python/3.6.8 (Windows-10-10.0.17763-SP0) AZURECLI/2.19.1 (MSI) VSTS_de5ec03c-4d40-48bc-9826-28dba363df49_build_79_0'
2021-02-26T17:29:56.6200728Z INFO: cli.azure.cli.core.util:     'Accept-Encoding': 'gzip, deflate'
2021-02-26T17:29:56.6202307Z INFO: cli.azure.cli.core.util:     'Accept': '*/*'
2021-02-26T17:29:56.6203336Z INFO: cli.azure.cli.core.util:     'Connection': 'keep-alive'
2021-02-26T17:29:56.6204523Z INFO: cli.azure.cli.core.util:     'x-ms-client-request-id': '710c6451-5247-47fc-b230-9a565d9dcc26'
2021-02-26T17:29:56.6205799Z INFO: cli.azure.cli.core.util:     'CommandName': 'rest'
2021-02-26T17:29:56.6206995Z INFO: cli.azure.cli.core.util:     'ParameterSetName': '--method --url --query --debug'
2021-02-26T17:29:56.6208754Z INFO: cli.azure.cli.core.util:     'Authorization': 'Bearer eyJ0eXAiOiJKV...'
2021-02-26T17:29:56.6209398Z INFO: cli.azure.cli.core.util: Request body:
2021-02-26T17:29:56.6209973Z INFO: cli.azure.cli.core.util: None
2021-02-26T17:29:56.6217767Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): graph.microsoft.com:443
2021-02-26T17:29:56.7103329Z DEBUG: urllib3.connectionpool: https://graph.microsoft.com:443 "GET /v1.0/applications?$filter=appId%20eq%20*** HTTP/1.1" 400 None
2021-02-26T17:29:56.7114299Z INFO: cli.azure.cli.core.util: Response status: 400
2021-02-26T17:29:56.7115419Z INFO: cli.azure.cli.core.util: Response headers:
2021-02-26T17:29:56.7116117Z INFO: cli.azure.cli.core.util:     'Date': 'Fri, 26 Feb 2021 17:29:56 GMT'
2021-02-26T17:29:56.7116795Z INFO: cli.azure.cli.core.util:     'Content-Type': 'application/json'
2021-02-26T17:29:56.7117507Z INFO: cli.azure.cli.core.util:     'Transfer-Encoding': 'chunked'
2021-02-26T17:29:56.7209088Z INFO: cli.azure.cli.core.util:     'Content-Encoding': 'gzip'
2021-02-26T17:29:56.7210813Z INFO: cli.azure.cli.core.util:     'Vary': 'Accept-Encoding'
2021-02-26T17:29:56.7212171Z INFO: cli.azure.cli.core.util:     'Strict-Transport-Security': 'max-age=31536000'
2021-02-26T17:29:56.7213563Z INFO: cli.azure.cli.core.util:     'request-id': 'dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16'
2021-02-26T17:29:56.7217126Z INFO: cli.azure.cli.core.util:     'client-request-id': 'dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16'
2021-02-26T17:29:56.7218823Z INFO: cli.azure.cli.core.util:     'x-ms-ags-diagnostic': '{"ServerInfo":{"DataCenter":"Canada East","Slice":"E","Ring":"2","ScaleUnit":"000","RoleInstance":"QB1PEPF00000F23"}}'
2021-02-26T17:29:56.7222160Z INFO: cli.azure.cli.core.util: Response content:
2021-02-26T17:29:56.7222975Z INFO: cli.azure.cli.core.util: {
2021-02-26T17:29:56.7223214Z 
2021-02-26T17:29:56.7223597Z   "error": {
2021-02-26T17:29:56.7223801Z 
2021-02-26T17:29:56.7225020Z     "code": "BadRequest",
2021-02-26T17:29:56.7225243Z 
2021-02-26T17:29:56.7225666Z     "message": "Invalid filter clause",
2021-02-26T17:29:56.7225893Z 
2021-02-26T17:29:56.7226292Z     "innerError": {
2021-02-26T17:29:56.7226477Z 
2021-02-26T17:29:56.7226918Z       "date": "2021-02-26T17:29:56",
2021-02-26T17:29:56.7227140Z 
2021-02-26T17:29:56.7227610Z       "request-id": "dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16",
2021-02-26T17:29:56.7227862Z 
2021-02-26T17:29:56.7228347Z       "client-request-id": "dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16"
2021-02-26T17:29:56.7228607Z 
2021-02-26T17:29:56.7228967Z     }
2021-02-26T17:29:56.7229108Z 
2021-02-26T17:29:56.7229455Z   }
2021-02-26T17:29:56.7229593Z 
2021-02-26T17:29:56.7229940Z }
2021-02-26T17:29:56.8935245Z DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
2021-02-26T17:29:56.8943793Z DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
2021-02-26T17:29:56.8945289Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
2021-02-26T17:29:56.8946607Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 664, in execute
2021-02-26T17:29:56.8947737Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 727, in _run_jobs_serially
2021-02-26T17:29:56.8949340Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 720, in _run_job
2021-02-26T17:29:56.8950145Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py", line 703, in reraise
2021-02-26T17:29:56.8950925Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 698, in _run_job
2021-02-26T17:29:56.8951883Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 331, in __call__
2021-02-26T17:29:56.8952880Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 816, in default_command_handler
2021-02-26T17:29:56.8953818Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7as_bwui\azure\cli\command_modules\util\custom.py", line 17, in rest_call
2021-02-26T17:29:56.8954972Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\util.py", line 930, in send_raw_request
2021-02-26T17:29:56.8955617Z knack.util.CLIError: Bad Request({
2021-02-26T17:29:56.8955846Z 
2021-02-26T17:29:56.8956213Z   "error": {
2021-02-26T17:29:56.8956392Z 
2021-02-26T17:29:56.8956783Z     "code": "BadRequest",
2021-02-26T17:29:56.8956978Z 
2021-02-26T17:29:56.8957387Z     "message": "Invalid filter clause",
2021-02-26T17:29:56.8957610Z 
2021-02-26T17:29:56.8958721Z     "innerError": {
2021-02-26T17:29:56.8958933Z 
2021-02-26T17:29:56.8959360Z       "date": "2021-02-26T17:29:56",
2021-02-26T17:29:56.8959605Z 
2021-02-26T17:29:56.8960060Z       "request-id": "dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16",
2021-02-26T17:29:56.8960323Z 
2021-02-26T17:29:56.8960793Z       "client-request-id": "dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16"
2021-02-26T17:29:56.8961073Z 
2021-02-26T17:29:56.8961429Z     }
2021-02-26T17:29:56.8961692Z 
2021-02-26T17:29:56.8962110Z   }
2021-02-26T17:29:56.8962258Z 
2021-02-26T17:29:56.8962608Z })
2021-02-26T17:29:56.8962743Z 
2021-02-26T17:29:56.8963257Z ERROR: cli.azure.cli.core.azclierror: Bad Request({
2021-02-26T17:29:56.8963499Z 
2021-02-26T17:29:56.8963872Z   "error": {
2021-02-26T17:29:56.8964032Z 
2021-02-26T17:29:56.8964430Z     "code": "BadRequest",
2021-02-26T17:29:56.8964609Z 
2021-02-26T17:29:56.8965035Z     "message": "Invalid filter clause",
2021-02-26T17:29:56.8965247Z 
2021-02-26T17:29:56.8965639Z     "innerError": {
2021-02-26T17:29:56.8965812Z 
2021-02-26T17:29:56.8966244Z       "date": "2021-02-26T17:29:56",
2021-02-26T17:29:56.8966467Z 
2021-02-26T17:29:56.8966937Z       "request-id": "dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16",
2021-02-26T17:29:56.8967184Z 
2021-02-26T17:29:56.8967665Z       "client-request-id": "dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16"
2021-02-26T17:29:56.8968717Z 
2021-02-26T17:29:56.8969113Z     }
2021-02-26T17:29:56.8969271Z 
2021-02-26T17:29:56.8969610Z   }
2021-02-26T17:29:56.8969759Z 
2021-02-26T17:29:56.8970094Z })
2021-02-26T17:29:56.8970558Z ERROR: cli.azure.cli.core.azclierror: Bad Request({
2021-02-26T17:29:56.8970801Z 
2021-02-26T17:29:56.8971172Z   "error": {
2021-02-26T17:29:56.8971331Z 
2021-02-26T17:29:56.8971721Z     "code": "BadRequest",
2021-02-26T17:29:56.8971901Z 
2021-02-26T17:29:56.8972446Z     "message": "Invalid filter clause",
2021-02-26T17:29:56.8972660Z 
2021-02-26T17:29:56.8973051Z     "innerError": {
2021-02-26T17:29:56.8973223Z 
2021-02-26T17:29:56.8973655Z       "date": "2021-02-26T17:29:56",
2021-02-26T17:29:56.8973870Z 
2021-02-26T17:29:56.8974346Z       "request-id": "dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16",
2021-02-26T17:29:56.8974593Z 
2021-02-26T17:29:56.8975072Z       "client-request-id": "dfaf8cf7-9fce-40f7-9f3b-b7cc7706cd16"
2021-02-26T17:29:56.8975329Z 
2021-02-26T17:29:56.8975679Z     }
2021-02-26T17:29:56.8976585Z 
2021-02-26T17:29:56.8976949Z   }
2021-02-26T17:29:56.8977086Z 
2021-02-26T17:29:56.8977434Z })

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by vineetmimrot** [comment]
@schmidtd-enb Can you try with url encoding of `appId eq ${{ parameters.appId }}` by replacing it with `appId%20eq%20%24%7B%7B%20parameters.appId%20%7D%7D`

**Comment by schmidtd-enb** [comment]
`${{ parameters.appId }}` is substituted before the pipeline is executed, so there is no point in escaping it.

I replaced it with `appId%20eq%20%${{ parameters.appId }}` to allow the substitution. Here is the debug log from the result:

2021-03-02T16:21:52.6058469Z DEBUG: cli.knack.cli: Command arguments: ['rest', '--method', 'GET', '--url', 'https://graph.microsoft.com/v1.0/applications', '--uri-parameters', '"$filter=appId%20eq%20***"', '--query', '"value"', '--debug']
2021-03-02T16:21:52.6062705Z DEBUG: cli.knack.cli: __init__ debug log:
2021-03-02T16:21:52.6063618Z Cannot enable color.
2021-03-02T16:21:52.6064777Z DEBUG: cli.knack.cli: Event: Cli.PreExecute []
2021-03-02T16:21:52.6065841Z DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x03052030>, <function OutputProducer.on_global_arguments at 0x030ED4B0>, <function CLIQuery.on_global_arguments at 0x03109420>]
2021-03-02T16:21:52.6494578Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
2021-03-02T16:21:52.6495817Z DEBUG: cli.azure.cli.core: Modules found from index for 'rest': ['azure.cli.command_modules.util']
2021-03-02T16:21:52.6496711Z DEBUG: cli.azure.cli.core: Loading command modules:
2021-03-02T16:21:52.6497769Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
2021-03-02T16:21:52.6525836Z DEBUG: cli.azure.cli.core: util                      0.003         2         4
2021-03-02T16:21:52.6527002Z DEBUG: cli.azure.cli.core: Total (1)                 0.003         2         4
2021-03-02T16:21:52.6542779Z DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples']
2021-03-02T16:21:52.6544168Z DEBUG: cli.azure.cli.core: Loading extensions:
2021-03-02T16:21:52.6545192Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
2021-03-02T16:21:52.6546368Z DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0  
2021-03-02T16:21:52.6547577Z DEBUG: cli.azure.cli.core: Loaded 2 groups, 4 commands.
2021-03-02T16:21:52.6548640Z DEBUG: cli.azure.cli.core: Found a match in the command table.
2021-03-02T16:21:52.6550148Z DEBUG: cli.azure.cli.core: Raw command  : rest
2021-03-02T16:21:52.6551149Z DEBUG: cli.azure.cli.core: Command table: rest
2021-03-02T16:21:52.6552017Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03455810>]
2021-03-02T16:21:52.6560735Z INFO: az_command_data_logger: command args: rest --method {} --url {} --uri-parameters {} --query {} --debug
2021-03-02T16:21:52.6561955Z DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'D:\a\_temp\.azclitask\commands'.
2021-03-02T16:21:52.6571507Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x034B3348>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x034B3A98>]
2021-03-02T16:21:52.6730747Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
2021-03-02T16:21:52.6736741Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x034B3AE0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x034B3B70>]
2021-03-02T16:21:52.6737775Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
2021-03-02T16:21:52.6738413Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
2021-03-02T16:21:52.6782831Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x030ED4F8>, <function CLIQuery.handle_query_parameter at 0x03109468>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x034B3A50>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x034B3B28>]
2021-03-02T16:21:53.0377879Z DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
2021-03-02T16:21:53.0386558Z DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
2021-03-02T16:21:53.0388023Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
2021-03-02T16:21:53.0389465Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 664, in execute
2021-03-02T16:21:53.0392161Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 727, in _run_jobs_serially
2021-03-02T16:21:53.0393689Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 720, in _run_job
2021-03-02T16:21:53.0395019Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py", line 703, in reraise
2021-03-02T16:21:53.0396104Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 698, in _run_job
2021-03-02T16:21:53.0396975Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 331, in __call__
2021-03-02T16:21:53.0397882Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 816, in default_command_handler
2021-03-02T16:21:53.0398771Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7as_bwui\azure\cli\command_modules\util\custom.py", line 17, in rest_call
2021-03-02T16:21:53.0399666Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\util.py", line 854, in send_raw_request
2021-03-02T16:21:53.0400623Z ValueError: dictionary update sequence element #0 has length 1; 2 is required
2021-03-02T16:21:53.0400918Z 
2021-03-02T16:21:53.0401560Z ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
2021-03-02T16:21:53.0402418Z ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
2021-03-02T16:21:53.0408046Z ERROR: cli.azure.cli.core.azclierror: dictionary update sequence element #0 has length 1; 2 is required
2021-03-02T16:21:53.0409385Z Traceback (most recent call last):
2021-03-02T16:21:53.0410653Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
2021-03-02T16:21:53.0411945Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 664, in execute
2021-03-02T16:21:53.0413286Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 727, in _run_jobs_serially
2021-03-02T16:21:53.0414577Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 720, in _run_job
2021-03-02T16:21:53.0417987Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py", line 703, in reraise
2021-03-02T16:21:53.0419052Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 698, in _run_job
2021-03-02T16:21:53.0419938Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 331, in __call__
2021-03-02T16:21:53.0421174Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 816, in default_command_handler
2021-03-02T16:21:53.0422105Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7as_bwui\azure\cli\command_modules\util\custom.py", line 17, in rest_call
2021-03-02T16:21:53.0422961Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\util.py", line 854, in send_raw_request
2021-03-02T16:21:53.0423744Z ValueError: dictionary update sequence element #0 has length 1; 2 is required
2021-03-02T16:21:53.0424861Z ERROR: cli.azure.cli.core.azclierror: dictionary update sequence element #0 has length 1; 2 is required
2021-03-02T16:21:53.0425554Z Traceback (most recent call last):
2021-03-02T16:21:53.0427416Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
2021-03-02T16:21:53.0428422Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 664, in execute
2021-03-02T16:21:53.0429298Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 727, in _run_jobs_serially
2021-03-02T16:21:53.0430197Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 720, in _run_job
2021-03-02T16:21:53.0431345Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py", line 703, in reraise
2021-03-02T16:21:53.0432205Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 698, in _run_job
2021-03-02T16:21:53.0433062Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 331, in __call__
2021-03-02T16:21:53.0433927Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 816, in default_command_handler
2021-03-02T16:21:53.0434807Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7as_bwui\azure\cli\command_modules\util\custom.py", line 17, in rest_call
2021-03-02T16:21:53.0436460Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\util.py", line 854, in send_raw_request
2021-03-02T16:21:53.0437273Z ValueError: dictionary update sequence element #0 has length 1; 2 is required
2021-03-02T16:21:53.0437882Z To open an issue, please run: 'az feedback'
2021-03-02T16:21:53.0438564Z DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03455930>]
2021-03-02T16:21:53.0439238Z INFO: az_command_data_logger: exit code: 1
2021-03-02T16:21:53.0439871Z INFO: cli.__main__: Command ran in 0.655 seconds (init: 0.216, invoke: 0.439)
2021-03-02T16:21:53.1299161Z INFO: telemetry.save: Save telemetry record of length 6214 in cache
2021-03-02T16:21:53.1300582Z WARNING: telemetry.check: Negative: The D:\a\_temp\.azclitask\telemetry.txt was modified at 2021-03-02 16:21:49.696897, which in less than 600.000000 s
2021-03-02T16:21:53.4272749Z ##[error]Script failed with exit code: 1
2021-03-02T16:21:53.4464525Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
2021-03-02T16:21:53.9242892Z ##[section]Finishing: Get service principal information

**Comment by tejasd1990** [comment]
Hi @schmidtd-enb ,
can you try with `appId%20eq%20'${{ parameters.appId }}'` or `appId%20eq%20%27${{ parameters.appId }}%27` ?
The app id should be enquoted.

**Comment by anuragc617** [comment]
@schmidtd-enb Does the above workaround suggested by tejasd1990 work for you?

**Comment by ddivanshu** [comment]
Closing this as user has not replied for a long time.
Feel free to reopen if you face any issue
