### ISSUE TITLE
Maven task succeeds on maven build failure

### ISSUE THREAD

**Issue by anupam128** [microsoft/azure-pipelines-tasks#14514]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven

list here (V# not needed):  https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/MavenV3

## Environment
- Server - Azure Pipelines

    - Account : ailens-io; Project: truera; BuildId=13244 or 20210302.9

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

Maven task succeeds even though maven build failed. This is likely caused by a bad symlink in the filesystem which makes node_modules/azure-pipelines-task-lib/task.js crash, see below. More in general, seems like pipeline code crash allows task to be marked as successful.
![image](https://user-images.githubusercontent.com/2722772/109728188-931f8b80-7b6a-11eb-9adb-9ce5ef9ba07a.png)

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (default-resources) on project rbac: /home/vsts/work/1/s/java/rbac-svc/target/classes/clients.yaml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :rbac
The process '/usr/bin/mvn' failed with exit code 1
Could not retrieve code analysis results - Maven run failed.
(node:2721) UnhandledPromiseRejectionWarning: Error: Failed find: ENOENT: no such file or directory, stat '/home/vsts/work/1/s/java/rbac-svc/target/classes/clients.yaml'
    at find (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/azure-pipelines-task-lib/task.js:819:15)
    at Object.findMatch (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/azure-pipelines-task-lib/task.js:1411:35)
    at publishJUnitTestResults (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/maventask.js:320:39)
    at /home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/maventask.js:263:17
    at _fulfilled (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:854:54)
    at /home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:816:13)
    at /home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:624:44
    at runSingle (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:137:13)
    at flush (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:125:13)
(node:2721) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2721) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Finishing: Maven
```

### Task logs

Attached the relevant log above.

Logs from Maven task set up:
```
==============================================================================
Task         : Maven
Description  : Build, test, and deploy with Apache Maven
Version      : 3.181.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/maven
==============================================================================
/usr/bin/mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/apache-maven-3.6.3
Java version: 1.8.0_282, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1039-azure", arch: "amd64", family: "unix"
FindBugs analysis is enabled.
PMD analysis is enabled.
```

**Comment by anatolybolshakov** [comment]
Hi @anupam128 we have rolled out related changes - closing it at the moment since it's resolved, please let us know if you have further questions.
