### ISSUE TITLE
dotnet tool install doesnt work anymore

### ISSUE THREAD

**Issue by mswilson4040** [microsoft/azure-pipelines-tasks#14551]
## Required Information
All of the sudden, my builds are failing due to the installation step of a dotnet tool (swashbuckel).

Here is the YAML:
```
  - task: DotNetCoreCLI@2
    displayName: 'Install Swashbuckle CLI'
    inputs:
      command: custom
      vstsFeed: '<feed guide>'
      includeNuGetOrg: true
      custom: tool
      arguments: 'install swashbuckle.aspnetcore.cli --version 5.5.1'
```

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
I tried to install the tool differently by simply restoring it from the dotnet-tools.json manifest, but it didn't work either.

```
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      includeNuGetOrg: true
      arguments: 'restore'
```

### Error logs
The thing that sticks out to me the most is the SSL failure, but looking at previous (successful) builds, I don't see the URL it's calling out

> Starting: DotNetCoreCLI
> ==============================================================================
> Task         : .NET Core
> Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
> Version      : 2.181.0
> Author       : Microsoft Corporation
> Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
> ==============================================================================
> C:\windows\system32\chcp.com 65001
> Active code page: 65001
> Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
> C:\hostedtoolcache\windows\dncs\3.1.100\x64\dotnet.exe tool restore
> C:\hostedtoolcache\windows\dncs\3.1.100\x64\sdk\3.1.100\NuGet.targets(123,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json. [C:\Users\VssAdministrator\AppData\Local\Temp\gxqe4klj.iwu\restore.csproj]
> C:\hostedtoolcache\windows\dncs\3.1.100\x64\sdk\3.1.100\NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [C:\Users\VssAdministrator\AppData\Local\Temp\gxqe4klj.iwu\restore.csproj]
> C:\hostedtoolcache\windows\dncs\3.1.100\x64\sdk\3.1.100\NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [C:\Users\VssAdministrator\AppData\Local\Temp\gxqe4klj.iwu\restore.csproj]
> 
> Package "swashbuckle.aspnetcore.cli" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
>    at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
>    at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
>    at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
> 
> Restore failed.
> ##[error]Error: The process 'C:\hostedtoolcache\windows\dncs\3.1.100\x64\dotnet.exe' failed with exit code 1
> Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
> ##[error]Dotnet command failed with non-zero exit code on the following projects : 
> Finishing: DotNetCoreCLI

I believe something externally changed since there haven't been any updates to anything related. I re-ran a successful build (last release on master branch) and that now fails with the same error. Running everything locally, however, works just fine.

**Comment by Gismork** [comment]
Hello,

It's caused by myget repository. It seems they have a certificate issue.

I had this error when opening the feed index url in my Firefox browser : https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

![image](https://user-images.githubusercontent.com/2140163/110610186-45200e80-818e-11eb-9733-348eb38dd34f.png)
