### ISSUE TITLE
Build Modules Task - Fails to install iotedgedev package on execution

### ISSUE THREAD

**Issue by toolboc** [microsoft/azure-pipelines-tasks#14679]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  AzureIoTEdgeV2 - Build Moules Task

## Environment
- Server - Azure Pipelines 
  - Account Name - pdecarlo
  - Team Project - IoTEdge-DevOps
  - Release 28 - Create Deployment Step
  
- Agent - Hosted  
    
    - Hosted Ubuntu 1604

## Issue Description

![image](https://user-images.githubusercontent.com/2018336/113330787-bca41200-92e4-11eb-8f30-322d7f76809a.png)

![image](https://user-images.githubusercontent.com/2018336/113330841-d04f7880-92e4-11eb-8c11-9a3ab81e5013.png)

### Task logs

```
2021-04-01T17:09:46.2988933Z ##[section]Starting: Azure IoT Edge - Build module images
2021-04-01T17:09:46.2998109Z ==============================================================================
2021-04-01T17:09:46.2998453Z Task         : Azure IoT Edge
2021-04-01T17:09:46.2998714Z Description  : Build and deploy an Azure IoT Edge image
2021-04-01T17:09:46.2998950Z Version      : 2.4.5
2021-04-01T17:09:46.2999202Z Author       : Microsoft Corporation
2021-04-01T17:09:46.2999532Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
2021-04-01T17:09:46.2999919Z ==============================================================================
2021-04-01T17:09:46.6055094Z Building module images...
2021-04-01T17:09:46.6075282Z /home/vsts/work/r1/a/_IoTEdge-DevOps-CI/drop/EdgeSolution /home/vsts/work/r1/a
2021-04-01T17:10:24.0784901Z ##[error]/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/iotedgedev", line 7, in <module>
    from iotedgedev.cli import main
  File "/usr/local/lib/python2.7/dist-packages/iotedgedev/cli.py", line 15, in <module>
    from .dockercls import Docker
  File "/usr/local/lib/python2.7/dist-packages/iotedgedev/dockercls.py", line 7, in <module>
    from .deploymentmanifest import DeploymentManifest
  File "/usr/local/lib/python2.7/dist-packages/iotedgedev/deploymentmanifest.py", line 12, in <module>
    import jsonschema
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/__init__.py", line 21, in <module>
    from jsonschema._types import TypeChecker
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/_types.py", line 3, in <module>
    from pyrsistent import pmap
  File "/usr/local/lib/python2.7/dist-packages/pyrsistent/__init__.py", line 3, in <module>
    from pyrsistent._pmap import pmap, m, PMap
  File "/usr/local/lib/python2.7/dist-packages/pyrsistent/_pmap.py", line 98
    ) from e
         ^
SyntaxError: invalid syntax

2021-04-01T17:10:24.0800901Z ##[error]Error: iotedgedev installation failed, see detailed error in debug mode
2021-04-01T17:11:24.5426717Z ##[section]Finishing: Azure IoT Edge - Build module images
```

**Comment by cindydeng1998** [comment]
Hello @toolboc , thank you for filing this issue. We are aware that the current version of the DevOps task is facing issues and we are working to resolve it as soon as we can by deploying a new version. We will let you know as soon as possible when the new version goes live
