### ISSUE TITLE
IISWebAppDeploymentOnMachineGroup error - DLL not found - exit code 3762504530

### ISSUE THREAD

**Issue by roofiq** [microsoft/azure-pipelines-tasks#14699]
**Bug**  
Hello,
From yestarday evening our CD pipelines are failing. We are using deployment groups targeting to windows VMs on Azure.
I was trying to upgrade targets (agents) to the newest version but the issue persist.

I checked on the server and this DLL - Microsoft.Web.Deployment.Tracing - is in the folder where msbuild is being invoked from.
Don't know how to fix it.
Below some details and logs.

**Enter Task Name**: IISWebAppDeploymentOnMachineGroup

- Agent - Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    - Windows 10

### Task logs

```
2021-04-07T13:44:25.0606673Z ##[section]Starting: IIS Web App Deploy
2021-04-07T13:44:25.0757935Z ==============================================================================
2021-04-07T13:44:25.0758548Z Task         : IIS web app deploy
2021-04-07T13:44:25.0759031Z Description  : Deploy a website or web application using Web Deploy
2021-04-07T13:44:25.0759556Z Version      : 0.184.2
2021-04-07T13:44:25.0760155Z Author       : Microsoft Corporation
2021-04-07T13:44:25.0760729Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
2021-04-07T13:44:25.0761324Z ==============================================================================
2021-04-07T13:44:25.9532847Z [command]"C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\Program Files\VSTSAgents\VM-machine\_work\r90\a\Artifact\drop\drop.zip' -dest:auto -setParam:name='IIS Web Application Name',value='iis-web-url' -skip:objectname='dirPath',absolutepath='\\Configs'
2021-04-07T13:44:26.0126321Z Error: The process 'C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 3762504530
2021-04-07T13:44:26.0128507Z     at ExecState._setResult (C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-task-lib\toolrunner.js:937:25)
2021-04-07T13:44:26.0131628Z     at ExecState.CheckComplete (C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-task-lib\toolrunner.js:920:18)
2021-04-07T13:44:26.0133871Z     at ChildProcess.<anonymous> (C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-task-lib\toolrunner.js:833:19)
2021-04-07T13:44:26.0135629Z     at ChildProcess.emit (events.js:198:13)
2021-04-07T13:44:26.0136384Z     at maybeClose (internal/child_process.js:982:16)
2021-04-07T13:44:26.0137154Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2021-04-07T13:44:26.0137767Z Retrying to deploy the package.
2021-04-07T13:44:26.0168376Z [command]"C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\Program Files\VSTSAgents\VM-machine\_work\r90\a\Artifact\drop\drop.zip' -dest:auto -setParam:name='IIS Web Application Name',value='iis-web-url' -skip:objectname='dirPath',absolutepath='\\Configs'
2021-04-07T13:44:26.0741031Z Error: The process 'C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 3762504530
2021-04-07T13:44:26.0743164Z     at ExecState._setResult (C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-task-lib\toolrunner.js:937:25)
2021-04-07T13:44:26.0747438Z     at ExecState.CheckComplete (C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-task-lib\toolrunner.js:920:18)
2021-04-07T13:44:26.0750942Z     at ChildProcess.<anonymous> (C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-task-lib\toolrunner.js:833:19)
2021-04-07T13:44:26.0752447Z     at ChildProcess.emit (events.js:198:13)
2021-04-07T13:44:26.0753055Z     at maybeClose (internal/child_process.js:982:16)
2021-04-07T13:44:26.0753751Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2021-04-07T13:44:26.0754423Z Retrying to deploy the package.
2021-04-07T13:44:26.0770703Z [command]"C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\Program Files\VSTSAgents\VM-machine\_work\r90\a\Artifact\drop\drop.zip' -dest:auto -setParam:name='IIS Web Application Name',value='iis-web-url' -skip:objectname='dirPath',absolutepath='\\Configs'
2021-04-07T13:44:26.1354123Z ##[error]Failed to deploy web package to IIS website.
2021-04-07T13:44:26.1373194Z ##[error]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Web.Deployment.Tracing, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Web.Deployment.TraceWrapper.EventWriteVerboseHelper(String message, String user, String siteName)
   at Microsoft.Web.Deployment.TraceWrapper.EventWriteVerbose(String message, String user, String siteName)
   at MSDeploy.MSDeploy.Main(String[] unusedArgs)

2021-04-07T13:44:26.1478537Z ##[error]Error: The process 'C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 3762504530
2021-04-07T13:44:26.1660560Z ##[section]Finishing: IIS Web App Deploy
```

Thanks,
Rafal

**Comment by roofiq** [comment]
I checked few things, I'm quite sure this error is for 2.184.2 version, previous one works fine.
The thing that has change is also folder structure in node_modules. It's moved to `azure-pipelines-tasks-webdeployment-common` and before it was in `webdeployment-common-v2`.

**Comment by AmrutaKawade** [comment]
@roofiq yes there is change in `webdeployment-common` folder but its just folder structure change. nothing else changed inside folder. 

Can you login to your private agent machine and delete this folder `C:\Program Files\VSTSAgents\VM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba`?

**Comment by roofiq** [comment]
Thanks for answer @AmrutaKawade. I have fixed it already by re-registering each agent nn `C:\azagent` directory. This should be the recommend folder to use on windows VM?
I'm not sure if deleting this folder would help anyway. When I have registered it in new location, the command used to deploy website in the logs is like this (same task is being used).
`[command]"C:\azagent\CM-machine\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.184.2\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe"`

**Comment by AmrutaKawade** [comment]
Yes this the recommended folder to use for agent.
Good to know that you resolved your problem.
Closing this issue

**Comment by riollo** [comment]
I think that the problem it's related to the Maximum Path Length Limitation in windows (260 characters).
With the new folder structure 31 characters have been introduced!

OLD path
_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.179.0\node_modules\webdeployment-common-v2\MSDeploy3.6\Microsoft.Web.Deployment.Tracing.dll

NEW path
_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.222.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\Microsoft.Web.Deployment.Tracing.dll

And the task fail when try to use this dll

@roofiq I think you resolved the problem because you reinstall the agents in a shorter path
