### ISSUE TITLE
Got almost to compile 

### ISSUE THREAD

**Issue by brunodefrancavalli** [microsoft/azure-pipelines-tasks#14706]
This is related to issue #14669

I got this command to work fine to build:
```
node make.js build --task AzureRmWebAppDeploymentV3
```

But when I try to compile this other task:
```
node make.js build --task AzureRmWebAppDeploymentV4
```

I get this instead:

```
> prepending PATH D:\github\azure-pipelines-tasks-master\node_modules\.bin
tsc tool:
Version 2.3.4
D:\github\azure-pipelines-tasks-master\node_modules\.bin\tsc
npm tool:
7.0.15
C:\Program Files\nodejs\npm

------------------------------------------------------------
Building: AzureRmWebAppDeploymentV4
------------------------------------------------------------

> getting task externals

------------------------------------------------------------
Module Directory:D:\github\azure-pipelines-tasks-master\Tasks\Common\webdeployment-common-v2
------------------------------------------------------------

Building module D:\github\azure-pipelines-tasks-master\Tasks\Common\webdeployment-common-v2

> cd Tasks\Common\webdeployment-common-v2

> npm install

> tsc --outDir "D:\github\azure-pipelines-tasks-master\_build\Tasks\Common\webdeployment-common-v2" --rootDir "D:\github\azure-pipelines-tasks-master\Tasks\Common\webdeployment-common-v2"

> cd ..\..\..

> copying module resources
copying *.ps1
copying *.psd1
copying *.psm1
copying *.sh
copying *.txt
copying icon.png
copying icon.svg
copying module.json
copying node_modules
copying package.json
copying task.json
copying task.loc.json
copying Tests

> getting module externals
Downloading file: https://vstsagenttools.blob.core.windows.net/tools/7zip/1/7zip.zip
Could not use "nc", falling back to slower node.js method for sync requests.
command:C:\Program Files\nodejs\node.exe
args:D:\github\azure-pipelines-tasks-master\node_modules\sync-request\lib\legacy-worker.js
method:GET
url:https://vstsagenttools.blob.core.windows.net/tools/7zip/1/7zip.zip
option:undefined
req:{"method":"GET","url":"https://vstsagenttools.blob.core.windows.net/tools/7zip/1/7zip.zip"}
res:[object Object]
My error:(null)
D:\github\azure-pipelines-tasks-master\node_modules\sync-request\index.js:85
    throw new Error(res.stderr.toString());
    ^

Error
    at doRequestWith (D:\github\azure-pipelines-tasks-master\node_modules\sync-request\index.js:85:11)
    at doRequest (D:\github\azure-pipelines-tasks-master\node_modules\sync-request\index.js:20:10)
    at downloadFile (D:\github\azure-pipelines-tasks-master\make-util.js:411:22)
    at downloadArchive (D:\github\azure-pipelines-tasks-master\make-util.js:451:27)
    at D:\github\azure-pipelines-tasks-master\make-util.js:644:33
    at Array.forEach (<anonymous>)
    at getExternals (D:\github\azure-pipelines-tasks-master\make-util.js:639:25)
    at D:\github\azure-pipelines-tasks-master\make.js:236:25
    at Array.forEach (<anonymous>)
    at D:\github\azure-pipelines-tasks-master\make.js:203:20
```

I have noticed any Task that uses the ```node_modules\sync-request\index.js``` fails.

Am I doing something wrong?

Please help me correct my noob mistakes

**Comment by AmrutaKawade** [comment]
@brunodefrancavalli can you tell me what version of `sync-request` is being used in package.json?

**Comment by brunodefrancavalli** [comment]
@AmrutaKawade I got whatever version was on master when I opened this issue. Is that what you mean? The sync-request call is in the code itself right? Sorry I am not very familiar with npm so I might be understanding your question.

**Comment by brunodefrancavalli** [comment]
Thank you so much, that fixed the issue :)
