### ISSUE TITLE
Can't use a template parameter to give pipeline name in DownloadPipelineArtifactV2 task

### ISSUE THREAD

**Issue by Philippe85** [microsoft/azure-pipelines-tasks#14730]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPipelineArtifactV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Pool: Azure Pipelines
Image: windows-latest
Agent: Azure Pipelines 5

## Issue Description
I can't use a template parameter to define the pipeline Name in the download task. Here is my template :
The ${{ parameters.PipelineName }} parameter should be resolved at compile time.

```
parameters:
- name: Environment
  type: string
- name: PipelineName
  type: string

jobs:
- deployment: Deploy_API
  environment: ${{ parameters.Environment }}
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: ${{ parameters.PipelineName }}
          displayName: 'Download API packages'

```

### Task logs

```
2021-04-14T10:20:26.0057499Z ##[section]Starting: Initialize job
2021-04-14T10:20:26.0059005Z Agent name: 'Azure Pipelines 9'
2021-04-14T10:20:26.0059430Z Agent machine name: 'fv-az105-761'
2021-04-14T10:20:26.0059701Z Current agent version: '2.184.2'
2021-04-14T10:20:26.0106454Z ##[group]Operating System
2021-04-14T10:20:26.0106782Z Microsoft Windows Server 2019
2021-04-14T10:20:26.0106994Z 10.0.17763
2021-04-14T10:20:26.0107164Z Datacenter
2021-04-14T10:20:26.0107336Z ##[endgroup]
2021-04-14T10:20:26.0107543Z ##[group]Virtual Environment
2021-04-14T10:20:26.0107771Z Environment: windows-2019
2021-04-14T10:20:26.0107996Z Version: 20210411.1
2021-04-14T10:20:26.0108337Z Included Software: https://github.com/actions/virtual-environments/blob/win19/20210411.1/images/win/Windows2019-Readme.md
2021-04-14T10:20:26.0108976Z Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210411.1
2021-04-14T10:20:26.0109285Z ##[endgroup]
2021-04-14T10:20:26.0110187Z Current image version: '20210411.1'
2021-04-14T10:20:26.0117907Z Agent running as: 'VssAdministrator'
2021-04-14T10:20:26.0155533Z ##[debug]Triggering repository: dshb2. repository type: Git
2021-04-14T10:20:26.0159505Z Prepare build directory.
2021-04-14T10:20:26.0377699Z ##[debug]Creating build directory: 'D:\a\1'
2021-04-14T10:20:26.0380178Z ##[debug]Delete existing artifacts directory: 'D:\a\1\a'
2021-04-14T10:20:26.0383362Z ##[debug]Creating artifacts directory: 'D:\a\1\a'
2021-04-14T10:20:26.0385716Z ##[debug]Delete existing test results directory: 'D:\a\1\TestResults'
2021-04-14T10:20:26.0386537Z ##[debug]Creating test results directory: 'D:\a\1\TestResults'
2021-04-14T10:20:26.0394062Z ##[debug]Creating binaries directory: 'D:\a\1\b'
2021-04-14T10:20:26.0396317Z ##[debug]Creating source directory: 'D:\a\1\s'
2021-04-14T10:20:26.0436888Z Set build variables.
2021-04-14T10:20:26.0472068Z Download all required tasks.
2021-04-14T10:20:26.0603591Z Downloading task: Download (1.0.0)
2021-04-14T10:20:26.1443099Z ##[warning]Failed to download task 'Download'. Error No task definition found matching ID 30f35852-3f7e-4c0c-9a88-e127b4f97211 and version 1.0.0. You must register the task definition before uploading the package.
2021-04-14T10:20:26.1456520Z ##[warning]Back off 24.244 seconds before retry.
2021-04-14T10:20:50.4472390Z ##[warning]Failed to download task 'Download'. Error No task definition found matching ID 30f35852-3f7e-4c0c-9a88-e127b4f97211 and version 1.0.0. You must register the task definition before uploading the package.
2021-04-14T10:20:50.4475861Z ##[warning]Back off 16.86 seconds before retry.
2021-04-14T10:21:07.4269875Z ##[error]No task definition found matching ID 30f35852-3f7e-4c0c-9a88-e127b4f97211 and version 1.0.0. You must register the task definition before uploading the package.
2021-04-14T10:21:07.4278516Z ##[debug]Microsoft.TeamFoundation.DistributedTask.WebApi.TaskDefinitionNotFoundException: No task definition found matching ID 30f35852-3f7e-4c0c-9a88-e127b4f97211 and version 1.0.0. You must register the task definition before uploading the package.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentHttpClient.GetTaskContentZipAsync(Guid taskId, TaskVersion version, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, TaskStepDefinitionReference task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, IEnumerable`1 steps)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
2021-04-14T10:21:07.4290097Z ##[section]Finishing: Initialize job

```

Thank you for your help.

**Comment by anatolybolshakov** [comment]
Hi @Philippe85 could you please try to use DownloadPipelineArtifactV2 task without as alias - as described here?
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops

**Comment by Philippe85** [comment]
I don't know how to use the DownloadPipelineArtifactV2 task without as alias, with pipeline name as parameter. Could you show how to do ?

**Comment by anatolybolshakov** [comment]
@Philippe85 you can use it just like in this example:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#download-a-specific-artifact

**Comment by anatolybolshakov** [comment]
Hi @Philippe85 do you have any updates?

**Comment by Philippe85** [comment]
The build of applications is done by a first pipeline named "Full-CI", which is triggering a second pipeline "Full-CD" to deploy on Azure. Here is an extract of my CD pipeline "Full-CD" :

```
resources:
  pipelines:
  - pipeline: Full-CI
    source: Full-CI
    trigger:
      branches:
      - release/*
      - hotfix/*

stages:
- stage: ${{ parameters.Environment }}
  jobs:
  - deployment: Deploy_API_${{ parameters.AppName }}
    displayName: 'Deploy API-${{ parameters.AppName }} in ${{ parameters.Environment }}'
    environment: ${{ parameters.Environment }}
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
```
With this step :
```
   - task: DownloadPipelineArtifact@2
          displayName: 'Download API packages'
          inputs:
            artifact: 'dshb2'
            patterns: '*/API/*.zip'
```
I have this error :
![image](https://user-images.githubusercontent.com/25458469/115689021-fb653f00-a35b-11eb-8fbc-b94cd04777d8.png)

With this step :
```
        - task: DownloadPipelineArtifact@2
          displayName: 'Download API packages'
          inputs:
            source: 'specific'
            project: 'MyProject'
            pipeline: $(resources.pipeline.Full-CI.pipelineID)
            runVersion: 'specific'
            runId: $(resources.pipeline.Full-CI.runID)
            artifact: 'dshb2'
            patterns: '*/API/*.zip'
```
The DownloadPipelineArtifact@2 task succeed, but it has not the same behavior of the alias "download" !

With the DownloadPipelineArtifact@2 task, folder are skipped and zip files are keept and saved at the root :
![image](https://user-images.githubusercontent.com/25458469/115723574-67599e80-a380-11eb-9923-ebd8989416d3.png)
Downloading: D:\a\1\API/xxx.zip

With the "download" alias, all path of file is kept :
Downloaded dshb2/API/KPMG.FR.ITS.PUBLICATION.API.zip to D:\a\1\Full-CI\dshb2\API\KPMG.FR.ITS.PUBLICATION.API.zip

Questions :
1) Why to have to provide all these data ?
            source: 'specific'
            project: 'MyProject'
            pipeline: $(resources.pipeline.Full-CI.pipelineID)
            runVersion: 'specific'
            runId: $(resources.pipeline.Full-CI.runID)
Then "download" version is better to use, to read :
```
        - download: Full-CI
          displayName: 'Download API packages'
          artifact: 'dshb2'
          patterns: '*/API/*.zip'
```


2) My problem is not resolved : How to use a parameter to provide pipeline name ?
$(resources.pipeline.Full-CI.pipelineID) => $(resources.pipeline.${{ parameter.PipelineName }}.pipelineID)

**Comment by Philippe85** [comment]
Hi @anatolybolshakov, do you have any updates on these several bugs ?

**Comment by anatolybolshakov** [comment]
Hi @Philippe85 you don't need to provide optional parameters - please see the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#yaml-snippet).
This issue with task alias is not related to the pipeline task itself, but this repo is mostly for pipeline tasks issues - could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by anatolybolshakov** [comment]
Hi @Philippe85 I'm closing this at the moment due to inactivity - please let us know if you have any further questions.
