### ISSUE TITLE
JenkinsQueueJob fails on writing summary markdown, even though Jenkins job itself is successful 

### ISSUE THREAD

**Issue by walczakp** [microsoft/azure-pipelines-tasks#14939]
## Required Information
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: JenkinsQueueJob  

## Environment
- Server - Azure Pipelines

- Agent:  private (I think), version 2.187.2 on Linux x86-64

## Issue Description
I'm having an issue with JenkinsQueueJob. With parameters provided below, it fails despite underlying remote Jenkins build finishes correctly.
```          - task: JenkinsQueueJob@2
            name: deployToSandbox
            displayName: deploy to sandbox
            condition: and(succeeded(), eq(variables.shouldBePublished, true), eq(variables['isMasterBranch'], true), not(endsWith(variables['currentVersion.CURRENT_VERSION'],'-SNAPSHOT')))
            inputs:
              serverEndpoint: 'some-kind-of-jenkins'
              jobName: 'MyJob_Formatted-Name'
              captureConsole: true
              capturePipeline: false
              isParameterizedJob: true
              jobParameters: |
                PARAM1=PARAM1
                PARAM2=VALUE2
```

Underlying Jenkins Job is an `com.tikal.jenkins.plugins.multijob.MultiJobProject`

### Task logs

```##[debug](2:MyJob_Formatted-Name:156) debug: Tracking progress of job URL: https://jenkins-url/job/MyJob_Formatted-Name/156/logText/progressiveText/?start=3486
##[debug]streamConsole().requestCallback()

##[debug](2:MyJob_Formatted-Name:156) debug: Tracking progress of job URL: https://jenkins-url/job/MyJob_Formatted-Name/156/logText/progressiveText/?start=3486
##[debug]streamConsole().requestCallback()

##[debug](2:MyJob_Formatted-Name:156) debug: Tracking progress of job URL: https://jenkins-url/job/MyJob_Formatted-Name/156/logText/progressiveText/?start=3486
##[debug]streamConsole().requestCallback()

##[debug](2:MyJob_Formatted-Name:156) debug: Tracking progress of job URL: https://jenkins-url/job/MyJob_Formatted-Name/156/logText/progressiveText/?start=3486
##[debug]streamConsole().requestCallback()

##[debug](2:MyJob_Formatted-Name:156) debug: Tracking progress of job URL: https://jenkins-url/job/MyJob_Formatted-Name/156/logText/progressiveText/?start=3486
##[debug]streamConsole().requestCallback()

##[debug](2:MyJob_Formatted-Name:156) debug: Tracking progress of job URL: https://jenkins-url/job/MyJob_Formatted-Name/156/logText/progressiveText/?start=3486
##[debug]streamConsole().requestCallback()
quiet period for Inner_Job_1 is 0 seconds.Finished Build : #2120 of Job : Inner_Job_1 with status : SUCCESS at 16:58:19
Finished: SUCCESS

##[debug](2:MyJob_Formatted-Name:156) debug: state changed from Streaming to Finishing
##[debug]finish()
##[debug](3:MyJob_Formatted-Name:156) debug: Tracking completion status of job: https://jenkins-url/job/MyJob_Formatted-Name/156/api/json?tree=result,timestamp
##[debug]finish().requestCallback()
##[debug](3:MyJob_Formatted-Name:156) debug: parsedBody for: https://jenkins-url/job/MyJob_Formatted-Name/156/api/json?tree=result,timestamp : {"_class":"com.tikal.jenkins.plugins.multijob.MultiJobBuild","result":"SUCCESS","timestamp":1623085062451}
******************************************************************************
Jenkins job finished: MyJob_Formatted-Name
https://jenkins-url/job/MyJob_Formatted-Name/156 
******************************************************************************
##[debug](3:MyJob_Formatted-Name:156) debug: state changed from Finishing to Done
##[debug]jobQueue.stop()
##[debug]writing summary markdown
##[debug]markdown location: /tmp/JenkinsJob_MyJob_Formatted-Name_156.md
##[debug]writeFinalMarkdown().writeFile().callback()
##[error]Unable to process command '##vso[task.addattachment type=Distributedtask.Core.Summary;name=Jenkins Results;]/tmp/JenkinsJob_MyJob_Formatted-Name_156.md' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Value cannot be null. (Parameter 'Cannot upload task attachment file, attachment file location is not specified or attachment file not exist on disk')
##[debug]System.ArgumentNullException: Value cannot be null. (Parameter 'Cannot upload task attachment file, attachment file location is not specified or attachment file not exist on disk')
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskAddAttachmentCommand.AddAttachment(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskAddAttachmentCommand.Execute(IExecutionContext context, Command command)
   at Microsoft.VisualStudio.Services.Agent.Worker.BaseWorkerCommandExtension.ProcessCommand(IExecutionContext context, Command command)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
##[debug]Processed: ##vso[task.addattachment type=Distributedtask.Core.Summary;name=Jenkins Results;]/tmp/JenkinsJob_MyJob_Formatted-Name_156.md
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]Jenkins job complete
##[debug]Handler exit code: 0
```

### Error logs

```##[error]Unable to process command '##vso[task.addattachment type=Distributedtask.Core.Summary;name=Jenkins Results;]/tmp/JenkinsJob_MyJob_Formatted-Name_156.md' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Value cannot be null. (Parameter 'Cannot upload task attachment file, attachment file location is not specified or attachment file not exist on disk')
##[debug]System.ArgumentNullException: Value cannot be null. (Parameter 'Cannot upload task attachment file, attachment file location is not specified or attachment file not exist on disk')
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskAddAttachmentCommand.AddAttachment(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskAddAttachmentCommand.Execute(IExecutionContext context, Command command)
   at Microsoft.VisualStudio.Services.Agent.Worker.BaseWorkerCommandExtension.ProcessCommand(IExecutionContext context, Command command)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)```

**Comment by kuleshovilya** [comment]
Hello @walczakp , tried reproducing the issue with provided info but wasn't able to. But from logs we can tell that the issue is not necessarily with the agent, it tracks job fine, but then cant write to a log file and read it afterwards. Could you please provide a little more details on environment:
- does folder /tmp exists?
- Is user from which agent is running have access to a /tmp folder? 
- do files with the name like JenkinsJob_MyJob_Formatted-Name_156.md appear there?
- was job working fine before? or is this first time using it?

**Comment by piotrwielgolaski-tomtom** [comment]
@kuleshovilya  I think I noticed that is problem, this step does not work when run in container
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops
Simple run it in i.e. ubuntu container to reproduce it.
Issue is that it saves files in container, but agent looks up for it in own folders.

Step should write to path that is mounted as agent temp and it should solve the issue, I noticed that other steps are using 
https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/MavenV3/mavenutil.ts#L303
maybe it helps

**Comment by kuleshovilya** [comment]
Yes, tried it on the fresh env with separate jenkins and agent containers, and it works fine. 
The issue @walczakp has is with the log files that agent produces, and not external files.
But thank you for heads up on the Maven task, if you've noticed an issue, please register that issue as well, we'll look into it.

**Comment by walczakp** [comment]
@piotrwielgolaski-tomtom actually reported workaround for the exact same issue I had. It seems that when we run it straight on agent (no container), JenkinsQueueJob task finishes successfully.
Here's how we made JenkinsQueueJob work for us:
![image](https://user-images.githubusercontent.com/17193925/128703866-c5ca7aed-bcda-43ea-b805-4ade03b31ab9.png)
Maybe there's some kind of issue when writing temp files inside a container? Or perhaps this specific container? We definitely had issues on `python:3.9-slim`, I remember also having trouble with `openjdk:11`.

**Comment by kuleshovilya** [comment]
Still, in the fresh environment, everything works with no issues, container or not. And from the logs we can conclude that agent got some troubles reading from the file in tmp directory.
Can you describe your pipeline setup as well, we'll need to understand the exact process and container\agent placements to reproduce the issue. 
You can also contact me at v-ikuleshov@microsoft.com

**Comment by walczakp** [comment]
Checked the answer to your questions before, it this matter it behaves exactly the same as with or without container. It always creates the .md file with content, so it seems it always has access to /tmp. 
I executed some commands after the task JenkinsQueueJob fired, there is no difference in the output regardless if its running in container or not:
No container - build goes green:
```
root
+ whoami
+ who am i
+ id -u -n
root
+ stat /tmp
  File: /tmp
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 99h/153d	Inode: 4662578     Links: 1
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-08-10 07:11:27.209847367 +0000
Modify: 2021-08-10 07:11:36.906034390 +0000
Change: 2021-08-10 07:11:36.906034390 +0000
 Birth: -
+ find /tmp -name 'JenkinsJob*' -printf '%a %s %u %g\t%p\n'
Tue Aug 10 07:11:36.9060343900 2021 140 root root	/tmp/JenkinsJob_walczakp-test_16.md
+ cat /tmp/JenkinsJob_walczakp-test_16.md
[walczakp-test #16](jenkins.url.com/job/walczakp-test/16) <font color='green'>succeeded</font><br />+ echo ''

+ xxd /tmp/JenkinsJob_walczakp-test_16.md
00000000: 5b77 616c 637a 616b 702d 7465 7374 2023  [walczakp-test #
00000010: 3136 5d28 6874 7470 733a 2f2f 6a65 6e6b  16](https://jenk
(...jenkins url redacted...)
00000050: 7761 6c63 7a61 6b70 2d74 6573 742f 3136  walczakp-test/16
00000060: 2920 3c66 6f6e 7420 636f 6c6f 723d 2767  ) <font color='g
00000070: 7265 656e 273e 7375 6363 6565 6465 643c  reen'>succeeded<
00000080: 2f66 6f6e 743e 3c62 7220 2f3e            /font><br />

``` 
With container - job fails:
```
root
+ whoami
+ who am i
+ id -u -n
root
+ stat /tmp
  File: /tmp
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 8ah/138d	Inode: 13428668    Links: 1
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-08-10 07:11:16.286095790 +0000
Modify: 2021-08-10 07:11:21.534207959 +0000
Change: 2021-08-10 07:11:21.534207959 +0000
 Birth: -
+ find /tmp -name 'JenkinsJob*' -printf '%a %s %u %g\t%p\n'
Tue Aug 10 07:11:21.5342079590 2021 140 root root	/tmp/JenkinsJob_walczakp-test_15.md
+ cat /tmp/JenkinsJob_walczakp-test_15.md
[walczakp-test #15](https://jenkins.url.com/job/walczakp-test/15) <font color='green'>succeeded</font><br />+ echo ''
+ xxd /tmp/JenkinsJob_walczakp-test_15.md

00000000: 5b77 616c 637a 616b 702d 7465 7374 2023  [walczakp-test #
00000010: 3135 5d28 6874 7470 733a 2f2f 6a65 6e6b  15](https://jenk
(...jenkins url redacted...)
00000050: 7761 6c63 7a61 6b70 2d74 6573 742f 3135  walczakp-test/15
00000060: 2920 3c66 6f6e 7420 636f 6c6f 723d 2767  ) <font color='g
00000070: 7265 656e 273e 7375 6363 6565 6465 643c  reen'>succeeded<
00000080: 2f66 6f6e 743e 3c62 7220 2f3e            /font><br />
```

**Comment by kuleshovilya** [comment]
I see, still issue seems to be local, so we'll need to know the setup to understand wheres the issue.

**Comment by walczakp** [comment]
We have a private agent pool set up, on which I don't have much knowledge about. I'll ask around to see what kind of details can I share, in the meanwhile the workaround with no container is working fine for us. Thanks for your assistance.

**Comment by kuleshovilya** [comment]
Sure thing, I'll close the issue for now, please send the details to v-ikuleshov@microsoft.com if you'll decide to go into investigation. Thank you

**Comment by GaTechThomas** [comment]
I just spent a lot of time trying to figure this out. The only thing that worked for me was to run it in bash and remove quotation marks from around the echoed value. 

This fails:

`echo "##vso[task.uploadsummary]$(Agent.TempDirectory)/AdditionalInfo.md"`

This succeeds:

`echo ##vso[task.uploadsummary]$(Agent.TempDirectory)/AdditionalInfo.md`
