### ISSUE TITLE
Release Pipeline unable to stop application pool without powershell.exe crashing!

### ISSUE THREAD

**Issue by Berthelmaster** [microsoft/azure-pipelines-tasks#14949]
Hi guys

We're having issues with a specific server that is unable to receive commands to stop applications pools. 

I get the following message when attempting to stop the application pool of X website:

`Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1'''))"'.`

A more detailed log:

```
2021-06-07T11:51:58.8079600Z ##[debug]Evaluating condition for step: 'Stop Application Pool'
2021-06-07T11:51:58.8081287Z ##[debug]Evaluating: succeeded()
2021-06-07T11:51:58.8081685Z ##[debug]Evaluating succeeded:
2021-06-07T11:51:58.8082564Z ##[debug]=> True
2021-06-07T11:51:58.8082991Z ##[debug]Result: True
2021-06-07T11:51:58.8083433Z ##[section]Starting: Stop Application Pool
2021-06-07T11:51:58.8251812Z ==============================================================================
2021-06-07T11:51:58.8252059Z Task         : IIS web app manage
2021-06-07T11:51:58.8252296Z Description  : Create or update websites, web apps, virtual directories, or application pools
2021-06-07T11:51:58.8252530Z Version      : 0.5.15
2021-06-07T11:51:58.8252688Z Author       : Microsoft Corporation
2021-06-07T11:51:58.8252957Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group
2021-06-07T11:51:58.8253255Z ==============================================================================
2021-06-07T11:52:09.7504426Z ##[debug]VstsTaskSdk 0.8.2 commit 
2021-06-07T11:52:11.2003134Z ##[debug]Entering E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1.
2021-06-07T11:52:11.2171446Z ##[debug]Loading resource strings from: E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\Task.json
2021-06-07T11:52:11.2425871Z ##[debug]Loaded 8 strings.
2021-06-07T11:52:11.2567035Z ##[debug]SYSTEM_CULTURE: 'en-US'
2021-06-07T11:52:11.2677726Z ##[debug]Loading resource strings from: E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\Strings\resources.resjson\en-US\resources.resjson
2021-06-07T11:52:11.3034150Z ##[debug]Loaded 8 strings.
2021-06-07T11:52:12.1075098Z ##[debug]Loading module from path 'E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\TaskModuleIISManageUtility\TaskModuleIISManageUtility.psd1'.
2021-06-07T11:52:12.1296021Z ##[debug]Loading module from path 'E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\TaskModuleIISManageUtility\TaskModuleIISManageUtility.psm1'.
2021-06-07T11:52:12.9365472Z ##[debug]NonInteractive: False
2021-06-07T11:52:13.7455224Z ##[debug]Entering script AppCmdOnTargetMachines.ps1
2021-06-07T11:52:13.7577583Z ##[debug]Exporting function 'Invoke-Main'.
2021-06-07T11:52:13.7662617Z ##[debug]Adding exceptions types.
2021-06-07T11:52:13.9158650Z ##[debug]Importing function 'Invoke-Main'.
2021-06-07T11:52:13.9334726Z ##[debug]INPUT_ENABLEIIS: 'false'
2021-06-07T11:52:13.9439589Z ##[debug]INPUT_ACTIONIISWEBSITE: 'CreateOrUpdateWebsite'
2021-06-07T11:52:13.9544550Z ##[debug]INPUT_WEBSITENAME (empty)
2021-06-07T11:52:13.9678080Z ##[debug]INPUT_STARTSTOPWEBSITENAME (empty)
2021-06-07T11:52:13.9886539Z ##[debug]INPUT_WEBSITEPHYSICALPATH: '%SystemDrive%\inetpub\wwwroot'
2021-06-07T11:52:14.0034351Z ##[debug]INPUT_WEBSITEPHYSICALPATHAUTH: 'WebsiteUserPassThrough'
2021-06-07T11:52:14.0120345Z ##[debug]INPUT_WEBSITEAUTHUSERNAME (empty)
2021-06-07T11:52:14.0226663Z ##[debug]INPUT_WEBSITEAUTHUSERPASSWORD (empty)
2021-06-07T11:52:14.0360453Z ##[debug]INPUT_ADDBINDING: 'false'
2021-06-07T11:52:14.0466121Z ##[debug]INPUT_PROTOCOL: 'http'
2021-06-07T11:52:14.0571102Z ##[debug]INPUT_IPADDRESS: 'All Unassigned'
2021-06-07T11:52:14.0675830Z ##[debug]INPUT_PORT: '80'
2021-06-07T11:52:14.0798749Z ##[debug]INPUT_SERVERNAMEINDICATION: 'false'
2021-06-07T11:52:14.0903227Z ##[debug]INPUT_HOSTNAMEWITHOUTSNI (empty)
2021-06-07T11:52:14.1007300Z ##[debug]INPUT_HOSTNAMEWITHHTTP (empty)
2021-06-07T11:52:14.1116201Z ##[debug]INPUT_HOSTNAMEWITHSNI (empty)
2021-06-07T11:52:14.1246588Z ##[debug]INPUT_SSLCERTTHUMBPRINT (empty)
2021-06-07T11:52:14.1350784Z ##[debug]INPUT_BINDINGS (empty)
2021-06-07T11:52:14.1896796Z ##[debug]INPUT_CREATEORUPDATEAPPPOOLFORWEBSITE: 'false'
2021-06-07T11:52:14.1995841Z ##[debug]INPUT_APPPOOLNAMEFORWEBSITE (empty)
2021-06-07T11:52:14.2136282Z ##[debug]INPUT_DOTNETVERSIONFORWEBSITE: 'v4.0'
2021-06-07T11:52:14.2313809Z ##[debug]INPUT_PIPELINEMODEFORWEBSITE: 'Integrated'
2021-06-07T11:52:14.2428553Z ##[debug]INPUT_APPPOOLIDENTITYFORWEBSITE: 'ApplicationPoolIdentity'
2021-06-07T11:52:14.2535273Z ##[debug]INPUT_APPPOOLUSERNAMEFORWEBSITE (empty)
2021-06-07T11:52:14.2638609Z ##[debug]INPUT_APPPOOLPASSWORDFORWEBSITE (empty)
2021-06-07T11:52:14.2759116Z ##[debug]INPUT_CONFIGUREAUTHENTICATIONFORWEBSITE: 'false'
2021-06-07T11:52:14.2864354Z ##[debug]INPUT_ANONYMOUSAUTHENTICATIONFORWEBSITE: 'false'
2021-06-07T11:52:14.2980199Z ##[debug]INPUT_BASICAUTHENTICATIONFORWEBSITE: 'false'
2021-06-07T11:52:14.3091749Z ##[debug]INPUT_WINDOWSAUTHENTICATIONFORWEBSITE: 'true'
2021-06-07T11:52:14.3203077Z ##[debug]INPUT_PARENTWEBSITENAMEFORVD (empty)
2021-06-07T11:52:14.3443397Z ##[debug]INPUT_VIRTUALPATHFORVD (empty)
2021-06-07T11:52:14.3467635Z ##[debug]INPUT_PHYSICALPATHFORVD: '%SystemDrive%\inetpub\wwwroot'
2021-06-07T11:52:14.3800306Z ##[debug]INPUT_VDPHYSICALPATHAUTH: 'VDUserPassThrough'
2021-06-07T11:52:14.3905995Z ##[debug]INPUT_VDAUTHUSERNAME (empty)
2021-06-07T11:52:14.4029584Z ##[debug]INPUT_VDAUTHUSERPASSWORD (empty)
2021-06-07T11:52:14.4135046Z ##[debug]INPUT_PARENTWEBSITENAMEFORAPPLICATION (empty)
2021-06-07T11:52:14.4239241Z ##[debug]INPUT_VIRTUALPATHFORAPPLICATION (empty)
2021-06-07T11:52:14.4345547Z ##[debug]INPUT_PHYSICALPATHFORAPPLICATION: '%SystemDrive%\inetpub\wwwroot'
2021-06-07T11:52:14.4450390Z ##[debug]INPUT_APPLICATIONPHYSICALPATHAUTH: 'ApplicationUserPassThrough'
2021-06-07T11:52:14.4555493Z ##[debug]INPUT_APPLICATIONAUTHUSERNAME (empty)
2021-06-07T11:52:14.4681431Z ##[debug]INPUT_APPLICATIONAUTHUSERPASSWORD (empty)
2021-06-07T11:52:14.4827608Z ##[debug]INPUT_CREATEORUPDATEAPPPOOLFORAPPLICATION: 'false'
2021-06-07T11:52:14.4932223Z ##[debug]INPUT_APPPOOLNAMEFORAPPLICATION (empty)
2021-06-07T11:52:14.5042656Z ##[debug]INPUT_DOTNETVERSIONFORAPPLICATION: 'v4.0'
2021-06-07T11:52:14.5159293Z ##[debug]INPUT_PIPELINEMODEFORAPPLICATION: 'Integrated'
2021-06-07T11:52:14.5291989Z ##[debug]INPUT_APPPOOLIDENTITYFORAPPLICATION: 'ApplicationPoolIdentity'
2021-06-07T11:52:14.5421328Z ##[debug]INPUT_APPPOOLUSERNAMEFORAPPLICATION (empty)
2021-06-07T11:52:14.5532011Z ##[debug]INPUT_APPPOOLPASSWORDFORAPPLICATION (empty)
2021-06-07T11:52:14.5654948Z ##[debug]INPUT_ACTIONIISAPPLICATIONPOOL: 'StopAppPool'
2021-06-07T11:52:14.5812341Z ##[debug]INPUT_APPPOOLNAME (empty)
2021-06-07T11:52:14.5918345Z ##[debug]INPUT_STARTSTOPRECYCLEAPPPOOLNAME: 'XX-CUSTOMER'
2021-06-07T11:52:14.6023111Z ##[debug]INPUT_DOTNETVERSION: 'v4.0'
2021-06-07T11:52:14.6126021Z ##[debug]INPUT_PIPELINEMODE: 'Integrated'
2021-06-07T11:52:14.6229315Z ##[debug]INPUT_APPPOOLIDENTITY: 'ApplicationPoolIdentity'
2021-06-07T11:52:14.6347183Z ##[debug]INPUT_APPPOOLUSERNAME (empty)
2021-06-07T11:52:14.6449415Z ##[debug]INPUT_APPPOOLPASSWORD (empty)
2021-06-07T11:52:14.6554964Z ##[debug]INPUT_APPCMDCOMMANDS (empty)
2021-06-07T11:52:14.6666068Z ##[debug]INPUT_IISDEPLOYMENTTYPE: 'IISApplicationPool'
2021-06-07T11:52:14.6899078Z ##[debug]Triming inputs for excess spaces, double quotes
2021-06-07T11:52:14.7104971Z ##[debug]Entering Invoke-Main function
2021-06-07T11:52:14.7187237Z ##[debug]ActionIISWebsite = 
2021-06-07T11:52:14.7269782Z ##[debug]ActionIISApplicationPool = StopAppPool
2021-06-07T11:52:14.7352007Z ##[debug]CreateApplication = 
2021-06-07T11:52:14.7434716Z ##[debug]CreateVirtualDirectory = 
2021-06-07T11:52:14.7544820Z ##[debug]VirtualPath = 
2021-06-07T11:52:14.7629898Z ##[debug]WebsiteName = 
2021-06-07T11:52:14.7713598Z ##[debug]PhysicalPath = 
2021-06-07T11:52:14.7797751Z ##[debug]PhysicalPathAuth = 
2021-06-07T11:52:14.7907806Z ##[debug]AddBinding = 
2021-06-07T11:52:14.8005670Z ##[debug]AppPoolName = XX-CUSTOMER
2021-06-07T11:52:14.8101340Z ##[debug]DotNetVersion = 
2021-06-07T11:52:14.8184607Z ##[debug]PipeLineMode = 
2021-06-07T11:52:14.8267515Z ##[debug]AppPoolIdentity = 
2021-06-07T11:52:14.8352277Z ##[debug]ConfigureAuthentication = 
2021-06-07T11:52:14.8840551Z ##[debug]AnonymousAuthentication = 
2021-06-07T11:52:14.8924218Z ##[debug]BasicAuthentication = 
2021-06-07T11:52:14.9006613Z ##[debug]WindowsAuthentication = 
2021-06-07T11:52:14.9097838Z ##[debug]AppCmdCommands = 
2021-06-07T11:52:14.9403124Z ##[debug]Performing action 'stop' on application pool 'XX-CUSTOMER'. Running command "C:\Windows\system32\inetsrv\appcmd.exe" stop apppool /apppool.name:"XX-CUSTOMER"
2021-06-07T11:52:14.9549759Z ##[debug]Entering Invoke-VstsTool.
2021-06-07T11:52:14.9715129Z ##[debug] FileName: 'C:\Windows\system32\inetsrv\appcmd.exe'
2021-06-07T11:52:14.9826230Z ##[debug] Arguments: 'stop apppool /apppool.name:"XX-CUSTOMER"'
2021-06-07T11:52:14.9974613Z ##[debug] RequireExitCodeZero: 'True'
2021-06-07T11:52:14.9990201Z ##[command]"C:\Windows\system32\inetsrv\appcmd.exe" stop apppool /apppool.name:"XX-CUSTOMER"
2021-06-07T11:52:18.3880093Z "XX-CUSTOMER" successfully stopped
2021-06-07T11:52:18.4003716Z ##[debug]Exit code: 0
2021-06-07T11:52:18.4111494Z ##[debug]Leaving Invoke-VstsTool.
2021-06-07T11:52:18.4327961Z ##[debug]Exiting Execute-Main function
2021-06-07T11:52:18.4441351Z ##[debug]Leaving E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1.
2021-06-07T11:52:18.5180986Z ##[error]Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1'''))"'.
2021-06-07T11:52:18.5196487Z ##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''E:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1'''))"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2021-06-07T11:52:18.5201907Z ##[section]Finishing: Stop Application Pool
```

This is happening on all of websites that is hosted on this specific machine.

Anyone that have any idea what this is caused by?

Would love to give any information needed in order to solve the problem.

Agent Version: 2.172.2

Regards,
Thomas

**Comment by secretcoder** [comment]
I'm also having the same issue. Anyone out there have an answer. Any server I try to deploy I get the same error. Please help!!

**Comment by secretcoder** [comment]
Solved the issue, make sure you are running powershell version 5.1

Instructions on how to upgrade/update link below.

http://woshub.com/install-update-powershell-windows/
