### ISSUE TITLE
Could not download groovy-all.jar (org.codehaus.groovy:groovy-all:2.4.15) Azure DevOps Build pipeline run not executed and getting this error

### ISSUE THREAD

**Issue by pragnesh1234** [microsoft/azure-pipelines-tasks#14958]
=> Azure DevOps Build pipeline run not executed and getting this error. Anyway, build the project in Android Studio 4.2 (local machine) successfully without error. I don't know what is causing it to stop downloading or not allowing it to download the groovy file but I am stuck here and can't release my app :(

**Error logs:**
- Execution failed for task ':app:lint'.
           > Could not resolve all files for configuration ':app:lintClassPath'.
           > Could not GET 'https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15.jar'.
           > Connection reset
            > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.3.21)
            > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.3.21/kotlin-reflect-1.3.21.jar'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.3.21/kotlin-reflect-1.3.21.jar'.
            > Connection reset
           
           * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 9m 34s Error: The process 'D:\a\1\s\gradlew.bat'
           failed with exit code 1
               at ExecState._setResult (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.186.0\node_modules\azure-pipelines-task-lib\toolrunner.js:937:25)
               at ExecState.CheckComplete (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.186.0\node_modules\azure-pipelines-task-lib\toolrunner.js:920:18)
               at ChildProcess.<anonymous> (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.186.0\node_modules\azure-pipelines-task-lib\toolrunner.js:833:19)
               at ChildProcess.emit (events.js:198:13)
               at maybeClose (internal/child_process.js:982:16)
               at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) No test result files matching
           D:\a\1\s\**\TEST-*.xml were found, so publishing JUnit test results
           is being skipped.
           ##[error]Error: The process 'D:\a\1\s\gradlew.bat' failed with exit code 1 Finishing: gradlew build
        
    Project Gradle
        
        buildscript {
            
            repositories {
                jcenter()
                mavenCentral()
                maven {
                    url "https://jitpack.io"
                }
        
                google()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:3.3.2'
                // NOTE: Do not place your application dependencies here; they belong
                // in the individual module build.gradle files
                // Check for v3.1.2 or higher
                classpath 'com.google.gms:google-services:4.3.0'
        
                // Add dependency
                classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'
            }
        }
        
        plugins {
            id "org.sonarqube" version "2.7"
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
                jcenter()
                maven {
                    url "https://jitpack.io"
                }
        
                flatDir {
                    dirs 'src/main/libs'
                }
        
                configurations.all {
                    resolutionStrategy {
                        force "com.google.android.gms:play-services-basement:16.2.0"
                    }
                }
            }
        }
        
        task clean(type: Delete) {
            delete rootProject.buildDir
        }

**Comment by alexander-smolyakov** [comment]
Hi @pragnesh1234, it seems the issue is related to problems with the internet connection. As a workaround, could you please try to increase the timeout for the connection?

For Gradle it can be done by adding the following parameters to your build command:
```
./gradlew build -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000
```

**Comment by pragnesh1234** [comment]
@alexander-smolyakov 
Thanks for the replay. 

I have added it in gradle.properties file but it is not working, still getting the same error in Azure DevOps build. 
I have attached the code snippet of gradle.properties file please check it.

android.enableJetifier=true
org.gradle.jvmargs=-Xmx1024M -Dkotlin.daemon.jvm.options\="-Xmx1024M"
org.gradle.internal.http.connectionTimeout =120000
org.gradle.internal.http.socketTimeout=120000
android.useAndroidX=true

**Comment by alexander-smolyakov** [comment]
@pragnesh1234, could you please try to upgrade the Gradle to the 6.7.1 version and see if the issue is resolved?

**Comment by alexander-smolyakov** [comment]
@pragnesh1234, is this issue still actual to you?

**Comment by alexander-smolyakov** [comment]
@pragnesh1234, closing this issue due to inactivity, please feel free to reopen it.
