### ISSUE TITLE
 'subscriptionId' cannot be null while updating a function app with a Docker container

### ISSUE THREAD

**Issue by rjmarques01** [microsoft/azure-pipelines-tasks#15039]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureFunctionAppContainer@1

## Environment
- Server - Azure Pipelines or TFS on-premises?
  
    - Azure Pipelines

- Agent - Hosted or Private: 
    
    - Hosted agent

## Issue Description

I have a Docker image on an ACR which I'm trying to pull and deploy into a Function App using the task below.:

  - task: AzureFunctionAppContainer@1
    displayName: Deploy Docker image
    inputs:
      azureSubscription: $(azureServiceConnectionName)
      appName: 'function-app-with-docker'
      imageName: companyapps.azurecr.io/$(imageRepository):$(build.buildNumber)

Whenever I try to deploy this I get the error below. I suspect that this has to do with permissions, unfortunately I can't find documentation on that. DevOps is using a service connection with Contributor access at the subscription level, including on the ACR.

Any thought on this? The error message does not help much on understanding the issue.

### Task logs

[7_Deploy Docker image.txt](https://github.com/microsoft/azure-pipelines-tasks/files/6807496/7_Deploy.Docker.image.txt)

### Error logs

Starting: Deploy Docker image
==============================================================================
Task         : Azure Functions for container
Description  : Update a function app with a Docker container
Version      : 1.187.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azurefunctioncontainertroubleshooting
==============================================================================
(node:6260) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getApplicationURL' of undefined
    at AzureFunctionOnContainerDeploymentProvider.<anonymous> (D:\a\_tasks\AzureFunctionAppContainer_13c22ce0-3b93-43f9-aeb7-71fbce7bf5b2\1.187.0\azurefunctiononcontainerprovider.js:62:73)
    at Generator.next (<anonymous>)
    at D:\a\_tasks\AzureFunctionAppContainer_13c22ce0-3b93-43f9-aeb7-71fbce7bf5b2\1.187.0\azurefunctiononcontainerprovider.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\a\_tasks\AzureFunctionAppContainer_13c22ce0-3b93-43f9-aeb7-71fbce7bf5b2\1.187.0\azurefunctiononcontainerprovider.js:4:12)
    at AzureFunctionOnContainerDeploymentProvider.UpdateDeploymentStatus (D:\a\_tasks\AzureFunctionAppContainer_13c22ce0-3b93-43f9-aeb7-71fbce7bf5b2\1.187.0\azurefunctiononcontainerprovider.js:56:16)
    at D:\a\_tasks\AzureFunctionAppContainer_13c22ce0-3b93-43f9-aeb7-71fbce7bf5b2\1.187.0\azurefunctiononcontainerdeployment.js:37:42
    at Generator.throw (<anonymous>)
    at rejected (D:\a\_tasks\AzureFunctionAppContainer_13c22ce0-3b93-43f9-aeb7-71fbce7bf5b2\1.187.0\azurefunctiononcontainerdeployment.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Got service connection details for Azure App Service:'function-app-with-docker'
##[error]Error: 'subscriptionId' cannot be null.
Finishing: Deploy Docker image

**Comment by rjmarques01** [comment]
Found the solution, the issue was that the service connection that was being used was created at the management group scope, which apparently is not supported: https://github.com/microsoft/azure-pipelines-tasks/issues/13779

Yet, the error should be more clear.

In my case, I simply created a new service connection at the subscription level.
