### ISSUE TITLE
Dotnet test task can't run net48 unit tests 

### ISSUE THREAD

**Issue by eransha** [microsoft/azure-pipelines-tasks#15096]
*Type*: Question

**Enter Task Name**: DotNetCoreCLIV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
dynamicscrm/Solutions/CRM.BAS.FSI.PR/20210728.64

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted Windows 2019 with VS2019

## Issue Description

When trying to run unit tests which were build in a .net4.8 anycpu dll, xunit tests are being found but not running stating that:
--> task output
Starting test execution, please wait...
2021-07-28T15:47:00.5294580Z Logging Vstest Diagnostics in file: D:\a\1\s\target\release\AnyCPU\tests\diag.txt
2021-07-28T15:47:00.6936578Z A total of 1 test files matched the specified pattern.
2021-07-28T15:47:03.6525577Z Logging TestHost Diagnostics in file: D:\a\1\s\target\release\AnyCPU\tests\diag.host.21-07-28_15-47-00_71247_1.txt
2021-07-28T15:47:05.9283182Z [xUnit.net 00:00:00.02] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (32-bit Desktop .NET 4.0.30319.42000)
2021-07-28T15:47:07.7645754Z [xUnit.net 00:00:01.86] Skipping: FSIClientView.Plugins.UnitTest (could not find dependent assembly 'FSIClientView.Plugins.UnitTest, Version=1.0.0')
2021-07-28T15:47:07.8133796Z No test is available in D:\a\1\s\target\release\AnyCPU\tests\FSIClientView.Plugins.UnitTest\release\FSIClientView.Plugins.UnitTest.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
--> end of task output
[taskLogs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6894761/taskLogs.zip)

### Task logs

Attached - also in the zip is the vstest diagnostics file

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by bishal-pdMSFT** [comment]
@ShreyasRmsft can you please take a look at this test issue in .Net Core CLI task.

**Comment by ShreyasRmsft** [comment]
Failing with

```
TpTrace Warning: 0 : 6984, 3, 2021/07/28, 15:47:04.821, 3443675261, testhost.net48.x86.exe, TestPluginDiscoverer: Failed to load extensions from file 'C:\Program Files\dotnet\sdk\5.0.302\Extensions\Microsoft.TestPlatform.TestHostRuntimeProvider.dll'.  Skipping test extension scan for this file.  Error: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TestPlatform.TestHostRuntimeProvider' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.TestPlatform.TestHostRuntimeProvider'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromFiles[TPluginInfo,TExtension](String[] files, Dictionary`2 pluginInfos)
```
