### ISSUE TITLE
Publish Pipeline Artifacts erroneously reporting "max quantity exceeded" and failing

### ISSUE THREAD

**Issue by andschwa** [microsoft/azure-pipelines-tasks#15094]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug, I think

**Enter Task Name**: Publish Pipeline Artifacts version 1.2.3

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishPipelineArtifactV1/task.json

## Environment
- Server - Azure Pipelines    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Debug run: https://dev.azure.com/powershell/PowerShellEditorServices/_build/results?buildId=83241&view=results

Task failure: https://dev.azure.com/powershell/PowerShellEditorServices/_build/results?buildId=83241&view=logs&j=4a71b71a-2122-57c3-951b-d39ad969ab87&t=3a30d8b6-df5a-5bab-f4d7-89aa82eafb18&l=137

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

Pool: Azure Pipelines
Image: vs2017-win2016
Agent: Azure Pipelines 4

## Issue Description
My CI is failing because the `publish` task says I'm hitting some quota:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2226434/127216067-a0639fc8-a087-41d0-a549-6bb6221a150b.png)

This is the only pipeline in this project. There are no feeds, no packages are published. I am only publishing pipeline artifacts. Furthermore, I deleted every other run of the pipeline to clear out any used storage, yet over 4 GB is still reported in total as used, and the task is still failing, but note that 0 and -- are reported in the breakdown:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2226434/127216063-1e672f88-7a10-4133-bd1a-13546fdb9f5a.png)

The linked documentation from the error plainly states:

> You don't get billed for the storage of Pipeline Artifacts, Build Artifacts, and Pipeline Caching.
Since I am only using pipeline artifacts (and was previously only using build artifacts, but those runs are since deleted over 12 hours ago), this _shouldn't_ be an issue whatsoever.

Perhaps it's complaining about not having payment setup, but this is the free dev.azure.com instance for public CI builds, and I've never before yesterday had an issue not having a payment account attached (including when uploading build and pipeline artifacts).

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/2226434/127216060-2e9d1226-4660-447d-b8b6-d12383eae8cb.png)

### Task logs

[DebugLogOfFailingRun.txt.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6888235/DebugLogOfFailingRun.txt.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
##[debug]Processed: ##vso[telemetry.publish area=AzurePipelinesAgent;feature=PipelineArtifact]{"FileCount":"1","PlanId":"c830968e-dbd0-4ce7-9727-47374ecfde0f","JobId":"4a71b71a-2122-57c3-951b-d39ad969ab87","TaskInstanceId":"3a30d8b6-df5a-5bab-f4d7-89aa82eafb18","ActionDurationMs":"2856","ActionName":"PipelineArtifact.UploadAsync","ActionResult":"Success","AttemptNumber":"1","ItemCount":"0","Level":"ThirdParty","CreatedUtcNow":"2021-07-27T19:29:04.3004044Z","SentUtcNow":"2021-07-27T19:29:07.1593708Z","BaseAddress":"https://vsblobprodcus3.vsblob.visualstudio.com/A8fe51ba5-a538-48e0-9fed-5e27d4a56df4/","X_TFS_Session":"94b130d3-c26d-45da-ba32-e6cf9be74dbc","DeploymentEnvironment":"PRODUCTION","DeploymentEnvironmentIsProduction":"True","VSOAccount":"vsblobprodcus3","OSName":"Linux","OSVersion":"2021","FrameworkDescription":".NET Core ","ProcessName":"Agent.PluginHost","DotNetReleaseDword":"-1","Version":"18.189.31425.0","ExceptionCount":"0"}
Verbose, ApplicationInsightsTelemetrySender sent PipelineArtifact.UploadAsync telemetry
Verbose, ApplicationInsightsTelemetrySender sent DedupUpload.UploadAsync telemetry
Verbose, [] Try 1/3, non-retryable exception caught. Throwing. Details:
No LastRequestResponse on exception ArtifactBillingException: Artifact cannot be uploaded because max quantity has been exceeded or the payment instrument is invalid. https://aka.ms/artbilling for details. Microsoft.VisualStudio.Services.Content.Common.ArtifactBillingException: Artifact cannot be uploaded because max quantity has been exceeded or the payment instrument is invalid. 
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Agent.Plugins.BuildServer.AssociateArtifactAsync(Guid projectId, Int32 pipelineId, String name, String jobId, String type, String data, Dictionary`2 propertiesDictionary, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifactServer.<>c__DisplayClass2_1.<<UploadAsync>b__5>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
Verbose, ApplicationInsightsTelemetrySender waiting for 0 of 2 TrackEvent operations to complete...
Verbose, ApplicationInsightsTelemetrySender operations completed in 0 ms
Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 94b130d3-c26d-45da-ba32-e6cf9be74dbc
Verbose, Stopped ITelemetrySender BlobStoreApplicationInsightsTelemetrySender.
##[error]Artifact cannot be uploaded because max quantity has been exceeded or the payment instrument is invalid. https://aka.ms/artbilling for details.
```

**Comment by andschwa** [comment]
Uhh in the debug logs my friend just noticed that it's the auto-inserted telemetry upload that's failing!

**Comment by andschwa** [comment]
Resolved internally (the FAQ answer does not apply to Microsoft owned projects and so was misleading).
