### ISSUE TITLE
Automation Test Fail in CI-CD pipe line, But working as expected in Local system and Command line. 

### ISSUE THREAD

**Issue by amin3498amin** [microsoft/azure-pipelines-tasks#15106]
Stack Trace:
      at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Enum.Parse(Type enumType, String value)
   at ECS360.Configuration.AppConfigReader.GetBrowser() in D:\a\1\s\ECS360\Configuration\AppConfigReader.cs:line 17
   at ECS360.BaseClasses.TestBaseClass.InitializeTest(TestContext context) in D:\a\1\s\ECS360\BaseClasses\TestBaseClass.cs:line 51
  Failed NavigatetoCorporateCommitee
  Error Message:
   Assembly Initialization method ECS360.BaseClasses.TestBaseClass.InitializeTest threw exception. System.ArgumentNullException: System.ArgumentNullException: Value cannot be null.
Parameter name: value. Aborting test execution.
  Stack Trace:
      at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Enum.Parse(Type enumType, String value)
   at ECS360.Configuration.AppConfigReader.GetBrowser() in D:\a\1\s\ECS360\Configuration\AppConfigReader.cs:line 17
   at ECS360.BaseClasses.TestBaseClass.InitializeTest(TestContext context) in D:\a\1\s\ECS360\BaseClasses\TestBaseClass.cs:line 51
Results File: D:\a\_temp\TestResults\VssAdministrator_fv-az26-430_2021-07-30_16_26_02.trx
Total tests: 24
     Passed: 3
     Failed: 21
 Total time: 23.7391 Seconds
##[error]Test Run Failed.
Vstest.console.exe exited with code 1.
**************** Completed test execution *********************
Test results files: D:\a\_temp\TestResults\VssAdministrator_fv-az26-430_2021-07-30_16_26_02.trx
Created test run: 128
Publishing test results: 24
Publishing test results to test run '128'.
TestResults To Publish 24, Test run id:128
Test results publishing 24, remaining: 0. Test run id: 128
Published test results: 24
Publishing Attachments: 1
Execution Result Code 1 is non zero, checking for failed results
Completed TestExecution Model...
##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
##[error]Error: The process 'D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\Modules\DTAExecutionHost.exe' failed with exit code 1
##[error]Vstest failed with error. Check logs for failures. There might be failed tests.

**Comment by DaniilShmelev** [comment]
Hi @amin3498amin! Could you please provide the name of the task that is causing the issue? Also, could you attach your logs with [Enable system diagnostics](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs) flag set? You can send them to my email: v-dshmelev@microsoft.com.

**Comment by DaniilShmelev** [comment]
@amin3498amin do you have any updates on this?

**Comment by DaniilShmelev** [comment]
Closing due to inactivity
