### ISSUE TITLE
AzureCLI@2 ERROR: psutil.AccessDenied

### ISSUE THREAD

**Issue by PetrPospisil** [microsoft/azure-pipelines-tasks#15138]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: 
AzureCLI@2
2.1.1

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
https://dev.azure.com/safetica-dev/Safetica/_build/results?buildId=43063&view=logs&j=9ebe2f87-16a6-5593-01d7-0a72e4047a88&t=3a7ec5df-c26a-561d-6db2-600a7a094f14

- Agent - Private: 
built from (today latest) https://github.com/actions/virtual-environments/commit/dcb58dee7ac5640f41ae3fa851458f8afbe2b45c

OS Name:                   Microsoft Windows Server 2019 Datacenter
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB5004332
                           [02]: KB4486153
                           [03]: KB4535680
                           [04]: KB4589208
                           [05]: KB5003711
                           [06]: KB5004244

Agent deployed using https://vstsagenttools.blob.core.windows.net/tools/ElasticPools/Windows/6/enableagent.ps1
Running under Administrator account created by the script
Agent version:
Tried 2.186.1 and 2.190.0 (no difference)

## Issue Description

Every execution of the AzureCLI@2 ends with the same error. The same setup works with the virtual-environments image generated a few month ago (older OS and older az cli), but it does not work with the image generated today morning. 
I suspect some collision with the OS.

If needed I am able to prepare in a minute a VM accessible using RDP with or without pre-deployed agent (with given pool name and PAT token) for debug session.

Please help. Thx.

### Error logs
2021-08-10T05:19:11.6010812Z ##[section]Starting: Execute script
2021-08-10T05:19:11.6161697Z ==============================================================================
2021-08-10T05:19:11.6162120Z Task         : Azure CLI
2021-08-10T05:19:11.6162644Z Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
2021-08-10T05:19:11.6164783Z Version      : 2.1.1
2021-08-10T05:19:11.6165149Z Author       : Microsoft Corporation
2021-08-10T05:19:11.6165523Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2021-08-10T05:19:11.6166033Z ==============================================================================
2021-08-10T05:19:12.0438496Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2021-08-10T05:19:21.2180660Z 
2021-08-10T05:19:21.2182168Z azure-cli                         2.27.0
2021-08-10T05:19:21.2184205Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-08-10T05:19:21.2184621Z 
2021-08-10T05:19:21.2186202Z ERROR: psutil.AccessDenied (pid=1080)
2021-08-10T05:19:21.2186971Z core                              2.27.0
2021-08-10T05:19:21.2188591Z Traceback (most recent call last):
2021-08-10T05:19:21.2189252Z telemetry                          1.0.6
2021-08-10T05:19:21.2190833Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_common.py", line 447, in wrapper
2021-08-10T05:19:21.2191421Z 
2021-08-10T05:19:21.2192473Z AttributeError: _cache
2021-08-10T05:19:21.2193136Z Extensions:
2021-08-10T05:19:21.2193577Z 
2021-08-10T05:19:21.2194264Z azure-devops                      0.20.0
2021-08-10T05:19:21.2195118Z During handling of the above exception, another exception occurred:
2021-08-10T05:19:21.2195395Z 
2021-08-10T05:19:21.2195910Z 
2021-08-10T05:19:21.2196390Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2021-08-10T05:19:21.2197309Z Traceback (most recent call last):
2021-08-10T05:19:21.2197854Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2021-08-10T05:19:21.2198774Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 679, in wrapper
2021-08-10T05:19:21.2199107Z 
2021-08-10T05:19:21.2199978Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_common.py", line 450, in wrapper
2021-08-10T05:19:21.2200783Z Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
2021-08-10T05:19:21.2201937Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 766, in exe
2021-08-10T05:19:21.2202262Z 
2021-08-10T05:19:21.2203069Z PermissionError: [WinError 24] The program issued a command but the command length is incorrect: '(originated from NtQuerySystemInformation)'
2021-08-10T05:19:21.2203837Z Legal docs and information: aka.ms/AzureCliLegal
2021-08-10T05:19:21.2204382Z 
2021-08-10T05:19:21.2204511Z 
2021-08-10T05:19:21.2205135Z During handling of the above exception, another exception occurred:
2021-08-10T05:19:21.2205416Z 
2021-08-10T05:19:21.2205712Z 
2021-08-10T05:19:21.2206580Z Your CLI is up-to-date.
2021-08-10T05:19:21.2207871Z Traceback (most recent call last):
2021-08-10T05:19:21.2242699Z ##[error]Error Code: [1]
2021-08-10T05:19:21.2268330Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 223, in invoke
2021-08-10T05:19:21.2272020Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 132, in show_version
2021-08-10T05:19:21.2272754Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 131, in print_styled_text
2021-08-10T05:19:21.2273450Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 131, in <listcomp>
2021-08-10T05:19:21.2275906Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 158, in format_styled_text
2021-08-10T05:19:21.2276625Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1266, in get_parent_proc_name
2021-08-10T05:19:21.2277341Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1254, in _get_parent_proc_name
2021-08-10T05:19:21.2278594Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/__init__.py", line 617, in name
2021-08-10T05:19:21.2279249Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 750, in name
2021-08-10T05:19:21.2279885Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 681, in wrapper
2021-08-10T05:19:21.2280633Z psutil.AccessDenied: psutil.AccessDenied (pid=1080)
2021-08-10T05:19:21.2281107Z To open an issue, please run: 'az feedback'
2021-08-10T05:19:21.2291227Z ##[error]Script failed with error: 
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: psutil.AccessDenied (pid=1080)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_common.py", line 447, in wrapper
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 679, in wrapper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_common.py", line 450, in wrapper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 766, in exe
PermissionError: [WinError 24] The program issued a command but the command length is incorrect: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 223, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 132, in show_version
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 131, in print_styled_text
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 131, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 158, in format_styled_text
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1266, in get_parent_proc_name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1254, in _get_parent_proc_name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/__init__.py", line 617, in name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 750, in name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 681, in wrapper
psutil.AccessDenied: psutil.AccessDenied (pid=1080)
To open an issue, please run: 'az feedback'

2021-08-10T05:19:21.2322290Z ##[section]Finishing: Execute script

**Comment by PetrPospisil** [comment]
I debugged the issue and the reason for the failure is too long path for node.exe tool in agent's path

call
"C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.12\Downloads\0\externals\node10\bin\node.exe" "D:\a\_tasks\AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815\2.1.1\azureclitask.js" fails (path length is more than 107chars)
but call
"C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.12\Downloads\0\externals\node10_\node.exe" "D:\a\_tasks\AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815\2.1.1\azureclitask.js" succeedes (path length is less or equal to 107chars)

This is caused by AZ CLI parent process name checks added in v2.20.0. They try to get parents process names few levels up, but because path to agent's node.exe is too long it fails. They use psutil lib so I suspect that the bug is in python psutil lib.

So, no issue from your side. Thx.
