### ISSUE TITLE
##[error]The type initializer for 'Category does not exist.' threw an exception.

### ISSUE THREAD

**Issue by herecydev** [microsoft/azure-pipelines-tasks#15145]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache@2

## Environment
- Server - Azure Pipelines
- Agent - Hosted

Image: ubuntu-latest
Agent: Azure Pipelines 2

## Issue Description

The following failure is seen randomly:

`##[error]The type initializer for 'Category does not exist.' threw an exception.`

Current workaround is to retry until it succeeds

**Comment by sefelk** [comment]
The failure occurs in the Post-job execution handler of the Cache@2 task.

This is the stack trace:

```
2021-08-12T08:39:19.4831852Z Verbose, Stopped ITelemetrySender BlobStoreApplicationInsightsTelemetrySender.
2021-08-12T08:39:19.4898097Z ##[error]The type initializer for 'Category does not exist.' threw an exception.
2021-08-12T08:39:19.4908165Z ##[debug]Processed: ##vso[task.logissue type=error;]The type initializer for 'Category does not exist.' threw an exception.
2021-08-12T08:39:19.4910305Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2021-08-12T08:39:19.4917191Z ##[debug]   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.PipelineCache.WebApi.PipelineCacheClient.CreatePipelineCacheArtifactAsync(CreatePipelineCacheArtifactContract createContract, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.PipelineCache.WebApi.PipelineCacheClient.<>c__DisplayClass8_0.<<CreatePipelineCacheArtifactAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.BlobStore.Common.Telemetry.BlobStoreClientTelemetry.MeasureActionAsync[TResult](BlobStoreTelemetryRecord record, Func`1 actionAsync)
   at Microsoft.VisualStudio.Services.Content.Common.ExceptionExtensions.ReThrow(Exception ex)
   at Microsoft.VisualStudio.Services.BlobStore.Common.Telemetry.BlobStoreClientTelemetry.MeasureActionAsync[TResult](BlobStoreTelemetryRecord record, Func`1 actionAsync)
   at Microsoft.VisualStudio.Services.PipelineCache.WebApi.PipelineCacheClient.CreatePipelineCacheArtifactAsync(CreatePipelineCacheArtifactContract createContract, CancellationToken cancellationToken, PipelineCacheTelemetryRecord cacheRecordOptional)
   at Agent.Plugins.PipelineCache.PipelineCacheServer.UploadAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, String path, CancellationToken cancellationToken, ContentFormat contentFormat)
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, Func`1 restoreKeysGenerator, String path, CancellationToken token)
   at Agent.Plugins.PipelineCache.PipelineCacheTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
 ```
