### ISSUE TITLE
VsTestV2 task often failed to fetch test run summary at end step

### ISSUE THREAD

**Issue by atifield** [microsoft/azure-pipelines-tasks#15230]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2

## Environment
- Server - Azure Pipelines

https://dev.azure.com/msasg/ContentServices/_build/results?buildId=23616194&view=logs&j=07162caa-69dd-5b6c-b542-af1b88f5e571&s=0cd2885c-f124-518f-01e7-16f9f8d7f0d9&t=ca41290c-5313-5428-ef94-47aa428ba3d1&l=10608

- Agent - Private
    
```
Agent name: 'peregrine-vp-1es 34'
Current agent version: '2.190.0'
Operating System
Microsoft Windows Server 2019
10.0.17763
1ES Hosted Pool
SKU: Standard_D4as_v4
Image: MMS2019
Image Version: 20210725.1.0
```

## Issue Description

In our test suites, we quite often failed the vstest task after tests are completed. This was always happening at lower rate but recently more than 5% of runs failed due to the same issue - failure to fetch run summary. This issue usually goes away after retriggering job but this is reducing dev agility because we run a lot of parallel jobs and they had to retrigger jobs often.

How can we mitigate this or increase the number of retries? I am assuming this was due to availability issues on Azure Pipelines Test API.

Or is it possible to distinguish this error in particular and rerun vstest? Currently the error code is the same as regular test failure so we cannot tell.

### Task logs

Will update the issue when we are able to capture the issue with debug logs. Regular log attached below
[vstest-failure.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7068827/vstest-failure.txt)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

The error is always the same below:

```
##[error]Test Run Failed.
Vstest.console.exe exited with code 1.
**************** Completed test execution *********************
Test results files: C:\__w\_temp\TestResults\ContainerAdministrator_0071807FC046_2021-08-27_16_08_40.trx
Created test run: 253865926
Publishing test results: 28
Publishing test results to test run '253865926'.
TestResults To Publish 28, Test run id:253865926
Test results publishing 28, remaining: 0. Test run id: 253865926
Published test results: 28
Publishing Attachments: 1
Execution Result Code 1 is non zero, checking for failed results
Retry count is exhausted while performing System.Threading.Tasks.Task`1[Microsoft.TeamFoundation.TestManagement.WebApi.TestRunStatistic] <GetTestRunSummaryByOutcome>b__0()
Failure attempting to call the test run summary and retry counter is exhausted Microsoft.TeamFoundation.DistributedTask.Task.TestResults.RetryCountExhaustedException: Max retries count: 3 is exhausted ---> Microsoft.TeamFoundation.TestManagement.WebApi.TestObjectNotFoundException: Run summary is not available, It is recommended to try again after 1 sec.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestRunPublisher.<GetTestRunSummaryAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.TeamFoundation.DistributedTask.Task.TestResults.RetryHelper.<Retry>d__1`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.DistributedTask.Task.TestResults.RetryHelper.<Retry>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by olstakh** [comment]
This is still happening. We're experiencing the same
