### ISSUE TITLE
ExtractFiles 1.189.0 is failing to extract huge tarballs on Linux with node.js v14 (current LTS)

### ISSUE THREAD

**Issue by am11** [microsoft/azure-pipelines-tasks#15261]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ExtractFiles@1 (1.189.0)  

## Issue Description

With node.js current LTS v14, the ExtractFiles v1.189.0 failed with `ENOBUFS` as follow:

```
stderr:  
error: Error: spawnSync /bin/tar ENOBUFS
    at Object.spawnSync (internal/child_process.js:1074:20)
    at Object.spawnSync (child_process.js:746:24)
    at ToolRunner.execSync (/__w/_tasks/ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988/1.189.0/node_modules/azure-pipelines-task-lib/toolrunner.js:874:23)
    at tarExtract (/__w/_tasks/ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988/1.189.0/extractfilestask.js:217:33)
    at extractFiles (/__w/_tasks/ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988/1.189.0/extractfilestask.js:286:17)
    at doWork (/__w/_tasks/ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988/1.189.0/extractfilestask.js:319:9)
    at Object.<anonymous> (/__w/_tasks/ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988/1.189.0/extractfilestask.js:328:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32) {
  errno: -105,
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/tar',
  path: '/bin/tar',
  spawnargs: [Array]
};
``` 

The workaround of this issue is described here: https://github.com/microsoft/azure-pipelines-task-lib/issues/630#issuecomment-829039089.

We are going to downgrade node.js to v10, but please update the dependencies so we can use this task reliably with the current LTS version.

**Comment by am11** [comment]
cc @ViktorHofer, FYI: we would need a downgrade of node.js for this issue. 🤷‍♂️ dncng failed to extract coreclr test artifacts on Alpine 3.13 (WithNode), where we just upgraded to node.js v14:  https://dev.azure.com/dnceng/public/_build/results?buildId=1348632&view=logs&j=a4a1c843-10b1-5245-33a1-211fde9b6ab5&t=fc6e1706-74db-553b-0aab-e2ad9e61105c. Helix queues are otherwise fine. I'm working on the downgrade for codeflow..

**Comment by anatolybolshakov** [comment]
Hi @am11 could you please share more info about your case? Pipeline agent uses pre-installed NodeJS versions for tasks execution (which don't depend on NodeJS version installed on the agent machine), and currently there are Node 6 and Node 10 execution handlers supported for the pipeline tasks.

**Comment by EzzhevNikita** [comment]
@am11 Is the issue still exist actual for you?

**Comment by EzzhevNikita** [comment]
@am11 ExtractFiles task is designed to work with Node 10 execution handler, so it should be running under Node 10. The current version of the agent doesn't have an execution handler with Node 14, so if we will update this task to support Node 14, we could potentially see any incompatibilities for the users who are using the Node version that is shipped with an agent. Adding support of Node 14 requires changes not only in the task but also in related libraries like _azure-pipelines-task-lib_ and in the agent. Updating of the task itself won't have much sense and could produce potential problems for most users.
