### ISSUE TITLE
VSTest failing to upload .coverage and .trx files due to SSL trust issues

### ISSUE THREAD

**Issue by luizgrs** [microsoft/azure-pipelines-tasks#15285]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: VSTest

## Environment
- Server - Azure Pipelines
- Agent - Private - 2.186.1 - Windows Server 2012

## Issue Description

VSTest successfully runs all tests then takes a long time and eventually fail when uploading .coverage and .trx files with error:
```
##[warning]Failed to upload file XXXXXX_2021-09-14_22_14_46.trx to Blob Transfer exception with errorcode Unknown, exception message Microsoft.Azure.Storage.DataMovement.TransferException: The transfer failed. ---> Microsoft.Azure.Storage.StorageException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
##[warning]Failed to upload file XXXXXX 2021-09-14 22_14_20.coverage to Blob Transfer exception with errorcode Unknown, exception message Microsoft.Azure.Storage.DataMovement.TransferException: The transfer failed. ---> Microsoft.Azure.Storage.StorageException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure
```
We do have a proxy with SSL Inspection in our network so it's very likely to be related to that however I'm failing to find out where I need to setup the Root CA used by it.

Such Root CA is already in the local computer Window Cert Store and accessing https://etqtcmprodweu11.vstmrblob.vsassets.io/  using IE under the same user used by Azure Devops service in the server works "fine" (400 Bad Request) and I can see our proxy is indeed inspecting such communication.

So my questions are:
- What are the URLs used for those operations? (I found out articles mentioning vsassets.io and just got https://etqtcmprodweu11.vstmrblob.vsassets.io/ from a random post actually)
- Which certificate store is used and how I make it trust my Root CA?
- Why it takes about 10min to fail with such message?

### Task logs
```
2021-09-14T20:20:05.4369089Z Test execution time: 5.7347 Minutes
2021-09-14T20:20:05.4621620Z Vstest.console.exe exited with code 0.
2021-09-14T20:20:05.4622172Z **************** Completed test execution *********************
2021-09-14T20:20:05.4725612Z Test results files: XXXXXXXXXXXXXXXXXXXXXX_2021-09-14_22_14_46.trx
2021-09-14T20:20:06.1874176Z Created test run: 1025120
2021-09-14T20:20:06.1876596Z Publishing test results: 1972
2021-09-14T20:20:06.4151879Z Publishing test results to test run '1025120'.
2021-09-14T20:20:06.4181396Z TestResults To Publish 1972, Test run id:1025120
2021-09-14T20:20:06.4264307Z Test results publishing 1000, remaining: 972. Test run id: 1025120
2021-09-14T20:20:07.2627054Z Test results publishing 972, remaining: 0. Test run id: 1025120
2021-09-14T20:20:07.7662698Z Published test results: 1972
2021-09-14T20:20:07.7679654Z Publishing Attachments: 2
2021-09-14T20:30:58.3057349Z ##[warning]Failed to upload file XXXXXXXXXXXX 2021-09-14 22_14_20.coverage to Blob Transfer exception with errorcode Unknown, exception message Microsoft.Azure.Storage.DataMovement.TransferException: The transfer failed. ---> Microsoft.Azure.Storage.StorageException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
2021-09-14T20:30:58.3059587Z    at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
2021-09-14T20:30:58.3059998Z    at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
2021-09-14T20:30:58.3060381Z    --- End of inner exception stack trace ---
2021-09-14T20:30:58.3060708Z    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2021-09-14T20:30:58.3061139Z    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
2021-09-14T20:30:58.3061470Z    --- End of inner exception stack trace ---
2021-09-14T20:30:58.3061790Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:30:58.3062177Z    at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
2021-09-14T20:30:58.3062513Z    --- End of inner exception stack trace ---
2021-09-14T20:30:58.3062978Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<HandleFetchAttributesResultAsync>d__19.MoveNext()
2021-09-14T20:30:58.3064053Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:30:58.3064443Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:30:58.3064838Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:30:58.3065316Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<FetchAttributesAsync>d__18.MoveNext()
2021-09-14T20:30:58.3065758Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:30:58.3066117Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:30:58.3066863Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:30:58.3067345Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<DoWorkInternalAsync>d__17.MoveNext()
2021-09-14T20:30:58.3067858Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:30:58.3068225Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:30:58.3068636Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:30:58.3069110Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.SyncTransferController.<DoWorkInternalAsync>d__14.MoveNext()
2021-09-14T20:30:58.3069887Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:30:58.3070251Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:30:58.3070645Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:30:58.3071123Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.TransferControllerBase.<DoWorkAsync>d__34.MoveNext()
2021-09-14T20:30:58.3071553Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:30:58.3071932Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:30:58.3072327Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:30:58.3072785Z    at Microsoft.Azure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__28.MoveNext()
2021-09-14T20:30:58.3073156Z    --- End of inner exception stack trace ---
2021-09-14T20:30:58.3073531Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<_executeWithRetry>d__33.MoveNext()
2021-09-14T20:30:58.3074012Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:30:58.3074379Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:30:58.3074786Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:30:58.3075244Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<UploadInternalAsync>d__19.MoveNext()
2021-09-14T20:30:58.3096909Z Failed to upload run logs to LogStore, Trying to upload to FileService
2021-09-14T20:30:58.8181750Z Failed to publish Telemetry Exception: Object reference not set to an instance of an object.
2021-09-14T20:31:20.6267530Z ##[warning]Failed to upload file XXXXXXXXX_2021-09-14_22_14_46.trx to Blob Transfer exception with errorcode Unknown, exception message Microsoft.Azure.Storage.DataMovement.TransferException: The transfer failed. ---> Microsoft.Azure.Storage.StorageException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
2021-09-14T20:31:20.6269923Z    at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
2021-09-14T20:31:20.6270748Z    at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
2021-09-14T20:31:20.6271245Z    --- End of inner exception stack trace ---
2021-09-14T20:31:20.6271672Z    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2021-09-14T20:31:20.6272126Z    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
2021-09-14T20:31:20.6272572Z    --- End of inner exception stack trace ---
2021-09-14T20:31:20.6272974Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:31:20.6273448Z    at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
2021-09-14T20:31:20.6273875Z    --- End of inner exception stack trace ---
2021-09-14T20:31:20.6274384Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<HandleFetchAttributesResultAsync>d__19.MoveNext()
2021-09-14T20:31:20.6274917Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:31:20.6275623Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:31:20.6276113Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:31:20.6276693Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<FetchAttributesAsync>d__18.MoveNext()
2021-09-14T20:31:20.6277420Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:31:20.6277953Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:31:20.6278430Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:31:20.6279018Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBlobWriter.<DoWorkInternalAsync>d__17.MoveNext()
2021-09-14T20:31:20.6279536Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:31:20.6279994Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:31:20.6280487Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:31:20.6281067Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.SyncTransferController.<DoWorkInternalAsync>d__14.MoveNext()
2021-09-14T20:31:20.6281596Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:31:20.6282054Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:31:20.6282536Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:31:20.6283424Z    at Microsoft.Azure.Storage.DataMovement.TransferControllers.TransferControllerBase.<DoWorkAsync>d__34.MoveNext()
2021-09-14T20:31:20.6283926Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:31:20.6284380Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:31:20.6284881Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:31:20.6285690Z    at Microsoft.Azure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__28.MoveNext()
2021-09-14T20:31:20.6286365Z    --- End of inner exception stack trace ---
2021-09-14T20:31:20.6287455Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<_executeWithRetry>d__33.MoveNext()
2021-09-14T20:31:20.6288663Z --- End of stack trace from previous location where exception was thrown ---
2021-09-14T20:31:20.6289401Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-14T20:31:20.6290258Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-14T20:31:20.6291359Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<UploadInternalAsync>d__19.MoveNext()
2021-09-14T20:31:20.6292500Z Failed to upload run logs to LogStore, Trying to upload to FileService
2021-09-14T20:31:20.9973149Z Failed to publish Telemetry Exception: Object reference not set to an instance of an object.
2021-09-14T20:31:22.1140439Z Completed TestExecution Model...
2021-09-14T20:31:22.1615967Z ##[section]Finishing: Run .NET Tests
```

**Comment by AlWoe** [comment]
We are having the same issue on our build pipeline, so we could still use the answers to @luizgrs 's questions!
How can I find out, what causes the problem?
And as we are not missing anything from this successful test task: can we just turn off the attempt to publish the test attatchments?
Our problem is just that the duration of the entire build is dominated by what seems to be a pointless wait of over 10 minutes here! 
e.g. the tests in this VStest task take only 1.4 seconds, but the step completes successfully after over 14 minutes!! The total time of the build pipeline is then 18' 15" ...
