### ISSUE TITLE
VSTest task fails on publishing test results even though it's passing all the test cases

### ISSUE THREAD

**Issue by indrani-insight** [microsoft/azure-pipelines-tasks#15283]
Hello,

I have created a pipeline in Azure DevOps contain couple of tasks. I used VSTest Task for testing UnitTests for my .Net Project. Pipelines are running on self hosted build agent. VSTest task is failing after passing all the tests and it's saying "Failed to publish test results". (FYI: I used VSTest task in another pipeline and it's working fine).Could you please help me out from this issue.

**Self Hosted Build agent:**

AgentVersion : 2.189.0
Agent OS : Windows_NT(Used Windows Server 2016 with Visual Studio 2017 )

**Pipeline description:**

task: VSTest@2
displayName: 'Run Unit Tests'
inputs:
testSelector: 'testAssemblies'
testAssemblyVer2: |
\ServicesUnitTest.dll
!*TestAdapter.dll
!**\obj**
searchFolder: '$(Build.SourcesDirectory)\UnitTest\ServicesUnitTest\bin\Debug'
runOnlyImpactedTests: false
testRunTitle: 'KioskTests'
publishRunAttachments: false

**error is:**

2021-09-13T15:34:12.8455574Z Results File: C:\agent\w_temp\TestResults\Kiosk-agent_rg-gp-kiosk-bui_2021-09-13_15_32_25.trx
2021-09-13T15:34:12.8603675Z Test Run Successful.
2021-09-13T15:34:12.8604022Z Total tests: 1367
2021-09-13T15:34:12.8604376Z Passed: 1367
2021-09-13T15:34:12.8612412Z Total time: 1.8063 Minutes
2021-09-13T15:34:12.8921503Z Vstest.console.exe exited with code 0.
2021-09-13T15:34:12.8921984Z **************** Completed test execution *********************
2021-09-13T15:34:12.9012745Z Test results files: C:\agent\w_temp\TestResults\Kiosk-agent_rg-gp-kiosk-bui_2021-09-13_15_32_25.trx
2021-09-13T15:34:13.2853891Z Created test run: 1098308
2021-09-13T15:34:13.2855705Z Publishing test results: 989
2021-09-13T15:34:13.3830626Z Publishing test results to test run '1098308'.
2021-09-13T15:34:13.3864635Z TestResults To Publish 989, Test run id:1098308
2021-09-13T15:34:13.3969497Z Test results publishing 989, remaining: 0. Test run id: 1098308
2021-09-13T15:34:13.5937216Z Failed to publish test results.
2021-09-13T15:34:13.5991760Z Publishing Attachments: 1
2021-09-13T15:34:14.3834885Z ##[error]Error occurred while publishing test results : System.AggregateException: One or more errors occurred. ---> Microsoft.TeamFoundation.TestManagement.WebApi.InvalidPropertyException: Invalid Priority specified
2021-09-13T15:34:14.3836265Z at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.d__53.MoveNext()
2021-09-13T15:34:14.3836733Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3837160Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3837705Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3838211Z at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.d__51.MoveNext()
2021-09-13T15:34:14.3838655Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3839077Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3839494Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3839963Z at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.d__471.MoveNext() 2021-09-13T15:34:14.3840407Z --- End of stack trace from previous location where exception was thrown --- 2021-09-13T15:34:14.3840827Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 2021-09-13T15:34:14.3841273Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 2021-09-13T15:34:14.3841761Z at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__281.MoveNext()
2021-09-13T15:34:14.3842231Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3842643Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3843110Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3843639Z at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.d__10.MoveNext()
2021-09-13T15:34:14.3844140Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3844546Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3845014Z at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.d__6.MoveNext()
2021-09-13T15:34:14.3845510Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3846235Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3846706Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3847231Z at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.d__2.MoveNext()
2021-09-13T15:34:14.3847727Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3848134Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3848548Z at Polly.Retry.AsyncRetryEngine.d__01.MoveNext() 2021-09-13T15:34:14.3848953Z --- End of stack trace from previous location where exception was thrown --- 2021-09-13T15:34:14.3849363Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 2021-09-13T15:34:14.3849830Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 2021-09-13T15:34:14.3850258Z at Polly.AsyncPolicy.<ExecuteAsync>d__211.MoveNext()
2021-09-13T15:34:14.3850726Z --- End of inner exception stack trace ---
2021-09-13T15:34:14.3851124Z at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2021-09-13T15:34:14.3851618Z at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2021-09-13T15:34:14.3852120Z at Microsoft.VisualStudio.TestService.RestApiHelpers.HttpRetryWrapper.Execute[TResult](Func1 func) 2021-09-13T15:34:14.3852675Z at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.PublishTestRunResults(TestRunModel testRunModel) 2021-09-13T15:34:14.3853259Z at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.CreateOrUpdateTestRun(TestRunModel testRunModel) 2021-09-13T15:34:14.3853791Z at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.Publish(VstestConsoleRunContext testRunContext) 2021-09-13T15:34:14.3854406Z ---> (Inner Exception #0) Microsoft.TeamFoundation.TestManagement.WebApi.InvalidPropertyException: Invalid Priority specified 2021-09-13T15:34:14.3854982Z at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext() 2021-09-13T15:34:14.3855456Z --- End of stack trace from previous location where exception was thrown --- 2021-09-13T15:34:14.3855864Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 2021-09-13T15:34:14.3856331Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 2021-09-13T15:34:14.3856809Z at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext() 2021-09-13T15:34:14.3857251Z --- End of stack trace from previous location where exception was thrown --- 2021-09-13T15:34:14.3857671Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 2021-09-13T15:34:14.3858120Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 2021-09-13T15:34:14.3858623Z at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__471.MoveNext()
2021-09-13T15:34:14.3859065Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3859486Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3859934Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3860431Z at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.d__281.MoveNext() 2021-09-13T15:34:14.3860880Z --- End of stack trace from previous location where exception was thrown --- 2021-09-13T15:34:14.3861292Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 2021-09-13T15:34:14.3861750Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 2021-09-13T15:34:14.3862335Z at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<PublishSingleBatch>d__10.MoveNext() 2021-09-13T15:34:14.3862842Z --- End of stack trace from previous location where exception was thrown --- 2021-09-13T15:34:14.3863251Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 2021-09-13T15:34:14.3863731Z at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<PublishResults>d__6.MoveNext() 2021-09-13T15:34:14.3864207Z --- End of stack trace from previous location where exception was thrown --- 2021-09-13T15:34:14.3864620Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 2021-09-13T15:34:14.3865080Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 2021-09-13T15:34:14.3865602Z at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<AddTestResultsAsync>d__2.MoveNext() 2021-09-13T15:34:14.3866100Z --- End of stack trace from previous location where exception was thrown --- 2021-09-13T15:34:14.3866514Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 2021-09-13T15:34:14.3866990Z at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__01.MoveNext()
2021-09-13T15:34:14.3867405Z --- End of stack trace from previous location where exception was thrown ---
2021-09-13T15:34:14.3867828Z at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-09-13T15:34:14.3868274Z at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-09-13T15:34:14.3868706Z at Polly.AsyncPolicy.d__21`1.MoveNext()<---
2021-09-13T15:34:14.3868909Z
2021-09-13T15:34:14.3877669Z ##[error]Skipping marking test run as complete as test run id 0 is invalid.
2021-09-13T15:34:14.4522445Z Completed TestExecution Model...
2021-09-13T15:34:14.4890344Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2021-09-13T15:34:14.4891978Z ##[error]Error: The process 'C:\agent\w_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\Modules\DTAExecutionHost.exe' failed with exit code 1
2021-09-13T15:34:14.4894196Z ##[error]Vstest failed with error. Check logs for failures. There might be failed tests.
2021-09-13T15:34:14.5009001Z ##[section]Finishing: Run Unit Tests

I appreciate your help!.

Thanks,
Rani

**Comment by nadesu** [comment]
@v-pkoneti - pls look into it

**Comment by acprince** [comment]
```
2021-09-13T15:34:14.3834885Z ##[error]Error occurred while publishing test results : System.AggregateException: One or more errors occurred. ---> Microsoft.TeamFoundation.TestManagement.WebApi.InvalidPropertyException: Invalid Priority specified
```
This was due to a `[Priority(-1)]` attribute in our unit tests. Removing the negative priority resolved the issue.
