### ISSUE TITLE
System.IO.IOException: The file '/usr/bin/dotnet' already exists

### ISSUE THREAD

**Issue by minoseah629** [microsoft/azure-pipelines-tasks#15453]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question / Bug?

**Enter Task Name**: DotNetCoreCLI@2 & CmdLine@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
bamtech / usaf-myvector / bam-oauth /  20211027.16 
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: ubuntu-latest

    - If using private agent, provide the OS of the machine running the agent and the agent version: ubuntu 5.4.0-1045-aws

## Issue Description

In both self host and microsoft hosted ubuntu agents, I get the same exact error. 

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/1980068/139147428-a6e508ee-1640-4e7f-a633-0e3959cd29ae.png)
![image](https://user-images.githubusercontent.com/1980068/139147839-d3e71c91-cd8e-4f55-8722-e9d673058b76.png)

### Task logs
2021-10-27T20:55:39.0419560Z ##[section]Starting: dotnet build
2021-10-27T20:55:39.0430716Z ==============================================================================
2021-10-27T20:55:39.0431063Z Task         : .NET Core
2021-10-27T20:55:39.0431416Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
2021-10-27T20:55:39.0431782Z Version      : 2.187.0
2021-10-27T20:55:39.0432029Z Author       : Microsoft Corporation
2021-10-27T20:55:39.0432390Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
2021-10-27T20:55:39.0432807Z ==============================================================================
2021-10-27T20:55:39.5928709Z Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
2021-10-27T20:55:39.5948186Z [command]/usr/bin/dotnet build -dl:CentralLogger,"/home/vsts/work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.187.0/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"*ForwardingLogger,"/home/vsts/work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.187.0/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" -c Release --version-suffix master.ec4cbc10b0fba68e8563857cea997502946c09c9.20211027.16
2021-10-27T20:55:50.0890608Z System.IO.IOException: The file '/usr/bin/dotnet' already exists.
2021-10-27T20:55:50.0892320Z    at System.IO.FileSystem.CreateDirectory(String fullPath)
2021-10-27T20:55:50.0893483Z    at System.IO.Directory.CreateDirectory(String path)
2021-10-27T20:55:50.0895179Z    at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
2021-10-27T20:55:50.0896336Z    at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
2021-10-27T20:55:50.0897448Z    at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
2021-10-27T20:55:50.0898647Z    at Microsoft.DotNet.Configurer.FileSystemExtensions.CreateIfNotExists(IFileSystem fileSystem, String filePath)
2021-10-27T20:55:50.0899641Z    at Microsoft.DotNet.Configurer.FileSentinel.Create()
2021-10-27T20:55:50.0900680Z    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
2021-10-27T20:55:50.0902086Z    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
2021-10-27T20:55:50.0903712Z    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
2021-10-27T20:55:50.0907271Z    at Microsoft.DotNet.Cli.Program.Main(String[] args)
2021-10-27T20:55:50.1155407Z ##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
2021-10-27T20:55:50.1170831Z ##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
2021-10-27T20:55:50.1175500Z Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
2021-10-27T20:55:50.1178332Z ##[error]Dotnet command failed with non-zero exit code on the following projects : 
2021-10-27T20:55:50.1201349Z ##[section]Finishing: dotnet build
[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by minoseah629** [comment]
just reporting this as a problem. i moved to a windows server
