### ISSUE TITLE
PublishSymbols v2: The remote server returned an error (401) Unauthorized

### ISSUE THREAD

**Issue by tbolon** [microsoft/azure-pipelines-tasks#15488]
## Required Information

*Type*: Bug
*Task Name*:  PublishSymbols

## Environment
- Azure DevOps Server 18.181.31626.1 (Azure DevOps Server 2020 Update 1.1)
- Agent: Private (version 2.181.2, Windows Server 2019 datacenter)

## Issue Description

I am trying to use the PublishSymbols task to push a pdb from my project to our internal devops server.

We already use the artifacts to publish nuget packages without any problem so far.

I receive a strange 401 error when the task tries to obtain the service location to this url: `http://tfs.fabrikam.lan/DefaultCollection//_apis/servicedefinitions/locationservice2/951917ac-a960-4999-8464-e3f0aa25b381`

I tried adding NuGetAutrhenticate task before, but I am able to push nuget packages on the same pipeline.

Also note that when I try to reach this url directly, it returns a `null` response.

### Logs

```
2021-11-09T13:50:03.5680470Z ##[debug]Evaluating condition for step: 'PublishSymbols'
2021-11-09T13:50:03.5682567Z ##[debug]Evaluating: SucceededNode()
2021-11-09T13:50:03.5683154Z ##[debug]Evaluating SucceededNode:
2021-11-09T13:50:03.5684704Z ##[debug]=> True
2021-11-09T13:50:03.5685347Z ##[debug]Result: True
2021-11-09T13:50:03.5686135Z ##[section]Starting: PublishSymbols
2021-11-09T13:50:03.5804193Z ==============================================================================
2021-11-09T13:50:03.5804782Z Task         : Index sources and publish symbols
2021-11-09T13:50:03.5805212Z Description  : Index your source code and publish symbols to a file share or Azure Artifacts symbol server
2021-11-09T13:50:03.5805573Z Version      : 2.172.0
2021-11-09T13:50:03.5805804Z Author       : Microsoft Corporation
2021-11-09T13:50:03.5806201Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/index-sources-publish-symbols
2021-11-09T13:50:03.5806762Z ==============================================================================
2021-11-09T13:50:04.3853514Z ##[debug]VstsTaskSdk 0.9.0 commit 6c48b16164b9a1c9548776ad2062dad5cd543352
2021-11-09T13:50:04.5422655Z ##[debug]Entering C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\PublishSymbols.ps1.
2021-11-09T13:50:04.5511504Z ##[debug]Loading module from path 'C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\ps_modules\PowershellHelpers\PowershellHelpers.psm1'.
2021-11-09T13:50:04.5587249Z ##[debug]Loading resource strings from: C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\ps_modules\PowershellHelpers\module.json
2021-11-09T13:50:04.5698103Z ##[debug]Loaded 3 strings.
2021-11-09T13:50:04.5742750Z ##[debug]SYSTEM_CULTURE: 'en-US'
2021-11-09T13:50:04.5770215Z ##[debug]Loading resource strings from: C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\ps_modules\PowershellHelpers\Strings\resources.resjson\en-US\resources.resjson
2021-11-09T13:50:04.5867091Z ##[debug]Loaded 3 strings.
2021-11-09T13:50:04.5940549Z ##[debug]Exporting function 'Invoke-ActionWithRetries'.
2021-11-09T13:50:04.5960545Z ##[debug]Exporting function 'Get-TempDirectoryPath'.
2021-11-09T13:50:04.5981094Z ##[debug]Importing function 'Get-TempDirectoryPath'.
2021-11-09T13:50:04.5999818Z ##[debug]Importing function 'Invoke-ActionWithRetries'.
2021-11-09T13:50:04.6025111Z ##[debug]Loading resource strings from: C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\Task.json
2021-11-09T13:50:04.6481989Z ##[debug]Loaded 23 strings.
2021-11-09T13:50:04.6511680Z ##[debug]SYSTEM_CULTURE: 'en-US'
2021-11-09T13:50:04.6537249Z ##[debug]Loading resource strings from: C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\Strings\resources.resjson\en-US\resources.resjson
2021-11-09T13:50:04.7045087Z ##[debug]Loaded 23 strings.
2021-11-09T13:50:04.7068177Z ##[debug]Loading module from path 'C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\SymbolsCommon.psm1'.
2021-11-09T13:50:04.7236948Z ##[debug]Exporting function 'Get-PdbstrPath'.
2021-11-09T13:50:04.7255940Z ##[debug]Exporting function 'Get-DbghelpPath'.
2021-11-09T13:50:04.7275031Z ##[debug]Exporting function 'Get-SymStorePath'.
2021-11-09T13:50:04.7295750Z ##[debug]Importing function 'Get-DbghelpPath'.
2021-11-09T13:50:04.7315001Z ##[debug]Importing function 'Get-PdbstrPath'.
2021-11-09T13:50:04.7335577Z ##[debug]Importing function 'Get-SymStorePath'.
2021-11-09T13:50:04.7610700Z ##[debug]INPUT_SYMBOLSERVERTYPE: 'TeamServices'
2021-11-09T13:50:04.7640365Z ##[debug]INPUT_DETAILEDLOG: 'true'
2021-11-09T13:50:04.7677799Z ##[debug] Converted to bool: True
2021-11-09T13:50:04.7712727Z ##[debug]INPUT_INDEXSOURCES: 'false'
2021-11-09T13:50:04.7731761Z ##[debug] Converted to bool: False
2021-11-09T13:50:04.7757817Z ##[debug]INPUT_COMPRESSSYMBOLS: 'false'
2021-11-09T13:50:04.7777274Z ##[debug] Converted to bool: False
2021-11-09T13:50:04.7804296Z ##[debug]INPUT_TREATNOTINDEXEDASWARNING: 'false'
2021-11-09T13:50:04.7871044Z ##[debug] Converted to bool: False
2021-11-09T13:50:04.7955009Z ##[debug]BUILD_SOURCESDIRECTORY: 'C:\agent_local\_work\93\s'
2021-11-09T13:50:04.7955819Z ##[debug]INPUT_SYMBOLSFOLDER: 'C:\agent_local\_work\93\s'
2021-11-09T13:50:04.7973628Z ##[debug]INPUT_SEARCHPATTERN: 'C:\agent_local\_work\93\a/Bin/*.pdb'
2021-11-09T13:50:04.8785433Z ##[debug]Entering Find-VstsMatch.
2021-11-09T13:50:04.8898497Z ##[debug]DefaultRoot: 'C:\agent_local\_work\93\s'
2021-11-09T13:50:04.9015057Z ##[debug]FindOptions.FollowSpecifiedSymbolicLink: 'True'
2021-11-09T13:50:04.9043814Z ##[debug]FindOptions.FollowSymbolicLinks: 'True'
2021-11-09T13:50:04.9167734Z ##[debug]MatchOptions.Dot: 'True'
2021-11-09T13:50:04.9196586Z ##[debug]MatchOptions.FlipNegate: 'False'
2021-11-09T13:50:04.9225586Z ##[debug]MatchOptions.MatchBase: 'False'
2021-11-09T13:50:04.9253820Z ##[debug]MatchOptions.NoBrace: 'True'
2021-11-09T13:50:04.9282120Z ##[debug]MatchOptions.NoCase: 'True'
2021-11-09T13:50:04.9310326Z ##[debug]MatchOptions.NoComment: 'False'
2021-11-09T13:50:04.9338466Z ##[debug]MatchOptions.NoExt: 'False'
2021-11-09T13:50:04.9367424Z ##[debug]MatchOptions.NoGlobStar: 'False'
2021-11-09T13:50:04.9395187Z ##[debug]MatchOptions.NoNegate: 'False'
2021-11-09T13:50:04.9423011Z ##[debug]MatchOptions.NoNull: 'False'
2021-11-09T13:50:04.9517333Z ##[debug]Pattern: 'C:\agent_local\_work\93\a/Bin/*.pdb'
2021-11-09T13:50:05.0418267Z ##[debug]FindPath: 'C:\agent_local\_work\93\a\Bin'
2021-11-09T13:50:05.0446757Z ##[debug]StatOnly: 'False'
2021-11-09T13:50:05.1596454Z ##[debug]Found 12 paths.
2021-11-09T13:50:05.1612890Z ##[debug]Applying include pattern.
2021-11-09T13:50:05.1728975Z ##[debug]2 matches
2021-11-09T13:50:05.1799948Z ##[debug]2 final results
2021-11-09T13:50:05.1821703Z ##[debug]Leaving Find-VstsMatch.
2021-11-09T13:50:05.1905073Z Found 2 files.
2021-11-09T13:50:05.1950352Z Skipping indexing.
2021-11-09T13:50:05.1973952Z ##[debug]INPUT_PUBLISHSYMBOLS: 'true'
2021-11-09T13:50:05.1991177Z ##[debug] Converted to bool: True
2021-11-09T13:50:05.2041537Z ##[debug]SYSTEM_TEAMPROJECT: 'Diagnostics'
2021-11-09T13:50:05.2095196Z ##[debug]BUILD_DEFINITIONNAME: 'PreRelease - CI'
2021-11-09T13:50:05.2152106Z ##[debug]BUILD_BUILDNUMBER: '1.6.2.58471_ci58471'
2021-11-09T13:50:05.2203790Z ##[debug]BUILD_BUILDID: '58471'
2021-11-09T13:50:05.2256904Z Symbol Request Name = diagnostics/prerelease - ci/1.6.2.58471_ci58471/58471/5adfe5d7-31ab-4525-a026-66181c962003
2021-11-09T13:50:05.2314800Z ##[debug]ARTIFACTSERVICES_SYMBOL_ACCOUNTNAME (empty)
2021-11-09T13:50:05.2382674Z ##[debug]ARTIFACTSERVICES_SYMBOL_PAT (empty)
2021-11-09T13:50:05.2429341Z ##[debug]ARTIFACTSERVICES_SYMBOL_USEAAD (empty)
2021-11-09T13:50:05.2445932Z ##[debug] Converted to bool: False
2021-11-09T13:50:05.2499103Z ##[debug]SYSTEM_TEAMFOUNDATIONCOLLECTIONURI: 'http://tfs.fabrikam.lan/DefaultCollection/'
2021-11-09T13:50:05.2825115Z ##[debug]GET http://tfs.fabrikam.lan/DefaultCollection//_apis/servicedefinitions/locationservice2/951917ac-a960-4999-8464-e3f0aa25b381 with 0-byte payload
2021-11-09T13:50:05.3262374Z Exception occurred: System.Net.WebException
2021-11-09T13:50:06.3316980Z ##[debug]GET http://tfs.fabrikam.lan/DefaultCollection//_apis/servicedefinitions/locationservice2/951917ac-a960-4999-8464-e3f0aa25b381 with 0-byte payload
2021-11-09T13:50:06.3478364Z Exception occurred: System.Net.WebException
2021-11-09T13:50:07.3498346Z ##[debug]GET http://tfs.fabrikam.lan/DefaultCollection//_apis/servicedefinitions/locationservice2/951917ac-a960-4999-8464-e3f0aa25b381 with 0-byte payload
2021-11-09T13:50:07.3644074Z Exception occurred: System.Net.WebException
2021-11-09T13:50:08.3687087Z ##[debug]GET http://tfs.fabrikam.lan/DefaultCollection//_apis/servicedefinitions/locationservice2/951917ac-a960-4999-8464-e3f0aa25b381 with 0-byte payload
2021-11-09T13:50:08.3819748Z Exception occurred: System.Net.WebException
2021-11-09T13:50:09.3841527Z ##[debug]GET http://tfs.fabrikam.lan/DefaultCollection//_apis/servicedefinitions/locationservice2/951917ac-a960-4999-8464-e3f0aa25b381 with 0-byte payload
2021-11-09T13:50:09.3979861Z Exception occurred: System.Net.WebException
2021-11-09T13:50:09.4130098Z ##[debug]Leaving C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\PublishSymbols.ps1.
2021-11-09T13:50:09.4248575Z ##[debug]Caught exception from task script.
2021-11-09T13:50:09.4331140Z ##[debug]Error record:
2021-11-09T13:50:09.6432370Z ##[debug]The remote server returned an error: (401) Unauthorized.
2021-11-09T13:50:09.6467135Z ##[debug]At C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\ps_modules\PowershellHelpers\Helpers.ps1:70 char:17
2021-11-09T13:50:09.6500047Z ##[debug]+                 throw $exception
2021-11-09T13:50:09.6533610Z ##[debug]+                 ~~~~~~~~~~~~~~~~
2021-11-09T13:50:09.6567495Z ##[debug]    + CategoryInfo          : OperationStopped: (:) [], WebException
2021-11-09T13:50:09.6602567Z ##[debug]    + FullyQualifiedErrorId : The remote server returned an error: (401) Unauthorized.
2021-11-09T13:50:09.6634974Z ##[debug] 
2021-11-09T13:50:09.6687867Z ##[debug]Script stack trace:
2021-11-09T13:50:09.6786114Z ##[debug]at Invoke-ActionWithRetries, C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\ps_modules\PowershellHelpers\Helpers.ps1: line 70
2021-11-09T13:50:09.6824149Z ##[debug]at Get-SymbolServiceUri, C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\PublishSymbols.ps1: line 22
2021-11-09T13:50:09.6858710Z ##[debug]at <ScriptBlock>, C:\agent_local\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.172.0\PublishSymbols.ps1: line 204
2021-11-09T13:50:09.6891476Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-11-09T13:50:09.6925912Z ##[debug]at <ScriptBlock>, <No file>: line 22
2021-11-09T13:50:09.6958000Z ##[debug]at <ScriptBlock>, <No file>: line 18
2021-11-09T13:50:09.6990071Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-11-09T13:50:09.7042133Z ##[debug]Exception:
2021-11-09T13:50:09.7150614Z ##[debug]System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2021-11-09T13:50:09.7182887Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2021-11-09T13:50:09.7215221Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2021-11-09T13:50:09.7810726Z ##[error]The remote server returned an error: (401) Unauthorized.
2021-11-09T13:50:09.7814750Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (401) Unauthorized.
2021-11-09T13:50:09.7833295Z ##[debug]Processed: ##vso[task.complete result=Failed]
2021-11-09T13:50:09.8480231Z ##[section]Finishing: PublishSymbols
```

**Comment by tbolon** [comment]
Ok, it seems this is not even supported: #11435 

Seriously...
