### ISSUE TITLE
Yaml Pipeline KeyVault task does not grab whole connection string

### ISSUE THREAD

**Issue by MayTheForkBeWithU** [microsoft/azure-pipelines-tasks#15556]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Question - How do I get the whole connection string from keyvault task

AzureKeyVault@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure Pipelines 

## Issue Description
KeyVault task does not grab the whole keyvault secret 

Here is my connection string:

`Server=test.database.windows.net;Initial Catalog=test-azdb;Integrated Security=False;Persist Security Info=False;User ID=myuser;Password=mypass;Enlist=False;Pooling=True;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;ConnectRetryCount=20;ConnectRetryInterval=30`

When I do Write-Output $connectionString - The following information is printed:

`Server=test.database.windows.net`

Here is how I am calling the keyvault secret
```
      steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: $(azure_subscription_name)
          KeyVaultName: ${{parameters.database_credential_key_vault_name}}
          SecretsFilter: "lab--myname--connectionstring"
          RunAsPreJob: false     
```

When running a powershell script in a yaml pipeline I get the following:

```
##[debug]System.Management.Automation.MethodInvocationException: Exception calling "Open" with "0" argument(s): "Login failed for user ''." ---> System.Data.SqlClient.SqlException: Login failed for user ''.
##[debug]   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
##[debug]   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
##[debug]   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
##[debug]   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
##[debug]   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
##[debug]   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
##[debug]   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
##[debug]   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
##[debug]   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
##[debug]   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
##[debug]   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
```

From debugging it looks like its not handling the string after the first ";"

**Comment by MattRalph** [comment]
Hi, this is still a problem. I have the same issue. 
Only get the first value in the connection string returned from the AzureKeyVault@2 task, everything else cut off after the first ;
I.e., only get this DefaultEndpointsProtocol=https 
returned from:
DefaultEndpointsProtocol=https;AccountName=xxxxxxxxxxxxxxxxxxxx;AccountKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==;EndpointSuffix=core.windows.net
This looks like a bug - a few people seem to have this issue, no workarounds found
Would be great to get a fix for this
