### ISSUE TITLE
IISWebAppManagementOnMachineGroup Version 0.5.15 => 0.198.0?

### ISSUE THREAD

**Issue by benjaminoerskov** [microsoft/azure-pipelines-tasks#15837]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: IISWebAppManagementOnMachineGroup 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

4 days ago when running the task: IISWebAppManagementOnMachineGroup@0 it defaulted to version 0.5.15 and this ran fine.

When im running it today, its using version 0.198.0 and failing. I have not changed anything in my yaml file, so I dont understand why this is failing now, or while we're getting such a big versionchange?

Its also not possible for me to use version 0.5.15 anymore, as devops is telling me that it does not exist.

**Comment by jrafamonagas** [comment]
Hi, I would like to know what is the status here

**Comment by benjaminoerskov** [comment]
@jrafamonagas I fixed the issue, by removing an invalid binding in our IIS. However im still courious to know about the rapid versionchange, and why I couldnt specify a specific version to use eg: @0.5.15?

**Comment by jrafamonagas** [comment]
Hi, @benjaminoerskov it fails for me still. I don't have any specific invalid bindings in IIS. Also, this error happens in some of the servers where the agent is installed but not all of them.

**Comment by jrafamonagas** [comment]
Hi, @nadesu any progress with this issue?

**Comment by nadesu** [comment]
@v-nagarajku - pls take a look

**Comment by v-nagarajku** [comment]
Hi @jrafamonagas , we have checked the task by creating sample website using deployment group job and it is working for latest version 0.198.0. Could you please share the complete logs and the configuration details using at your end, so that we will  repro the same in our environment and check for the scenario.

**Comment by jrafamonagas** [comment]
Hi, @v-nagarajku this is the error we get:
[](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group)Deploy IIS 

Exit code 1 returned from process: file name 'C:\Agents\UC-On-Site-Deployment-Agent\externals\node10\bin\node.exe', arguments '"C:\Agents\UC-On-Site-Deployment-Agent\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.198.0\deployiiswebapp.js"'.

And the stacktrace:
2022-01-25T12:01:01.3557310Z ##[section]Starting: Deploy IIS App
2022-01-25T12:01:01.3781658Z ==============================================================================
2022-01-25T12:01:01.3781984Z Task         : IIS web app deploy
2022-01-25T12:01:01.3782297Z Description  : Deploy a website or web application using Web Deploy
2022-01-25T12:01:01.3782549Z Version      : 0.198.0
2022-01-25T12:01:01.3782759Z Author       : Microsoft Corporation
2022-01-25T12:01:01.3783113Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
2022-01-25T12:01:01.3783491Z ==============================================================================
2022-01-25T12:01:01.5868410Z C:\Agents\UC-On-Site-Deployment-Agent\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.198.0\node_modules\shelljs\commands.js:1
2022-01-25T12:01:01.5869418Z 
2022-01-25T12:01:01.5869605Z 
2022-01-25T12:01:01.5869763Z 
2022-01-25T12:01:01.5870323Z SyntaxError: Invalid or unexpected token
2022-01-25T12:01:01.5871424Z     at Module._compile (internal/modules/cjs/loader.js:723:23)
2022-01-25T12:01:01.5875022Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2022-01-25T12:01:01.5878264Z     at Module.load (internal/modules/cjs/loader.js:653:32)
2022-01-25T12:01:01.5880942Z     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2022-01-25T12:01:01.5884329Z     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2022-01-25T12:01:01.5888505Z     at Module.require (internal/modules/cjs/loader.js:692:17)
2022-01-25T12:01:01.5890931Z     at require (internal/modules/cjs/helpers.js:25:18)
2022-01-25T12:01:01.5901083Z     at Object.<anonymous> (C:\Agents\UC-On-Site-Deployment-Agent\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.198.0\node_modules\shelljs\shell.js:24:1)
2022-01-25T12:01:01.5906673Z     at Module._compile (internal/modules/cjs/loader.js:778:30)
2022-01-25T12:01:01.5907424Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2022-01-25T12:01:01.6217855Z ##[error]Exit code 1 returned from process: file name 'C:\Agents\UC-On-Site-Deployment-Agent\externals\node10\bin\node.exe', arguments '"C:\Agents\UC-On-Site-Deployment-Agent\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.198.0\deployiiswebapp.js"'.
2022-01-25T12:01:01.6233825Z ##[section]Finishing: Deploy IIS App

**Comment by jrafamonagas** [comment]
Hi, @v-nagarajku  
2022-02-10T17:29:07.9524712Z ##[debug]Evaluating condition for step: 'Deploy IIS App'
2022-02-10T17:29:07.9527189Z ##[debug]Evaluating: and(succeeded(), eq('true', 'true'))
2022-02-10T17:29:07.9527931Z ##[debug]Evaluating and:
2022-02-10T17:29:07.9528327Z ##[debug]..Evaluating succeeded:
2022-02-10T17:29:07.9529732Z ##[debug]..=> True
2022-02-10T17:29:07.9530217Z ##[debug]..Evaluating eq:
2022-02-10T17:29:07.9530753Z ##[debug]....Evaluating String:
2022-02-10T17:29:07.9531211Z ##[debug]....=> 'true'
2022-02-10T17:29:07.9531738Z ##[debug]....Evaluating String:
2022-02-10T17:29:07.9532186Z ##[debug]....=> 'true'
2022-02-10T17:29:07.9532573Z ##[debug]..=> True
2022-02-10T17:29:07.9532895Z ##[debug]=> True
2022-02-10T17:29:07.9534178Z ##[debug]Expanded: and(True, eq('true', 'true'))
2022-02-10T17:29:07.9534948Z ##[debug]Result: True
2022-02-10T17:29:07.9535918Z ##[section]Starting: Deploy IIS App
2022-02-10T17:29:07.9749547Z ==============================================================================
2022-02-10T17:29:07.9749934Z Task         : IIS web app deploy
2022-02-10T17:29:07.9750219Z Description  : Deploy a website or web application using Web Deploy
2022-02-10T17:29:07.9750494Z Version      : 0.198.0
2022-02-10T17:29:07.9750699Z Author       : Microsoft Corporation
2022-02-10T17:29:07.9751045Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
2022-02-10T17:29:07.9751446Z ==============================================================================
2022-02-10T17:29:07.9818361Z ##[debug]Using node path: C:\Agents\Agent\externals\node10\bin\node.exe
2022-02-10T17:29:08.1844655Z C:\Agents\Agent\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.198.0\node_modules\shelljs\commands.js:1
2022-02-10T17:29:08.1846432Z 
2022-02-10T17:29:08.1846703Z 
2022-02-10T17:29:08.1846931Z 
2022-02-10T17:29:08.1847617Z SyntaxError: Invalid or unexpected token
2022-02-10T17:29:08.1852763Z     at Module._compile (internal/modules/cjs/loader.js:723:23)
2022-02-10T17:29:08.1860364Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2022-02-10T17:29:08.1864992Z     at Module.load (internal/modules/cjs/loader.js:653:32)
2022-02-10T17:29:08.1869583Z     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2022-02-10T17:29:08.1874729Z     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2022-02-10T17:29:08.1879488Z     at Module.require (internal/modules/cjs/loader.js:692:17)
2022-02-10T17:29:08.1885353Z     at require (internal/modules/cjs/helpers.js:25:18)
2022-02-10T17:29:08.1901258Z     at Object.<anonymous> (C:\Agents\Agent\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.198.0\node_modules\shelljs\shell.js:24:1)
2022-02-10T17:29:08.1905191Z     at Module._compile (internal/modules/cjs/loader.js:778:30)
2022-02-10T17:29:08.1910640Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2022-02-10T17:29:08.2231181Z ##[error]Exit code 1 returned from process: file name 'C:\Agents\Agent\externals\node10\bin\node.exe', arguments '"C:\Agents\Agent\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.198.0\deployiiswebapp.js"'.
2022-02-10T17:29:08.2246569Z ##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name 'C:\Agents\Agent\externals\node10\bin\node.exe', arguments '"C:\Agents\Agent\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.198.0\deployiiswebapp.js"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2022-02-10T17:29:08.2253516Z ##[section]Finishing: Deploy IIS App

**Comment by v-nagarajku** [comment]
@jrafamonagas  can you please provide entire logs instead of task logs alone.

**Comment by jrafamonagas** [comment]
@v-nagarajku 
[tasklog_45.log](https://github.com/microsoft/azure-pipelines-tasks/files/8056601/tasklog_45.log)

**Comment by v-nagarajku** [comment]
@jrafamonagas  can you please provide your YAML configuration file for this task.

**Comment by jrafamonagas** [comment]
Hi @v-nagarajku 

variables:
  customer: 'customer'

steps:
- task: IISWebAppDeploymentOnMachineGroup@0
  displayName: 'Deploy IIS App'
  inputs:
    WebSiteName: DPAWebSite
    VirtualApplication: '/dap-release-$(customer)-dpp'
    Package: '$(System.DefaultWorkingDirectory)\Backend.Release\$(customer).Debug\DPP.Api.zip'
    TakeAppOfflineFlag: true
    XmlTransformation: true
    XmlVariableSubstitution: true
  condition: and(succeeded(), eq('true', 'true'))

This is it. We use release pipelines using the classic pipeline editor.
It has always worked until the last version of node.exe

**Comment by v-nagarajku** [comment]
@jrafamonagas,  from the above data provided these are all our assumptions for the configuration and we repro with the below configuration as per the YAML shared.
Using Release pipelines with **Deployment group job** with VM as target which has sample website in IIS.
Using **IIS web app deploy** task 0.198.0v
Mimic similar YAML config for deployment

PS: **Task is working fine in the above said configuration. Can you please confirm still facing the issues.**

**Comment by v-nagarajku** [comment]
Hi @jrafamonagas  Can you please confirm here whether you still facing the issue?

**Comment by jrafamonagas** [comment]
Hi, @v-nagarajku  same issue still. 
After the latest release, our deployment stage broke and since then it is not working again.
Is there a way to manually choose the version that will be used for the deployment?
Thanks very much
Jose M

**Comment by v-nagarajku** [comment]
Hi @jrafamonagas  you cannot manually choose the version as the task is updated to 0.198.0. As explained we had mimic the above said configuration, but we do not see any issues in our local environment. Can you please check once in the path variables. As it is blaming as syntax error.

**Comment by jrafamonagas** [comment]
@v-nagarajku what do you mean in the path variables? could you guide me there?

**Comment by v-nagarajku** [comment]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/96724708/155548446-8ec353ed-31e7-4a21-a1da-1732275aac14.png">

 $customer one. Can you please check once.

**Comment by jrafamonagas** [comment]
Hi @v-nagarajku  i have checked and the variable is there. 
We have three stages and for two of them the pipeline is failing with the above mentioned error, for the other stage the pipeline runs correctly.

**Comment by v-nagarajku** [comment]
Hi @jrafamonagas , Is there any change in the settings in other 2 stages which is failing and can you compare the one with which is working?. Without proper configuration we cannot repro your issue, we have done our repro based on the above shared YAML and it worked fine.

**Comment by v-nagarajku** [comment]
Hi @jrafamonagas  any updates on this??

**Comment by jrafamonagas** [comment]
Hi, @v-nagarajku there is no changes anywhere at all. The error appeared on the day that the new version was released. Variables are the same. Everything is exactly the same as it was before. 
How can we find the issue?
https://github.com/microsoft/azure-pipelines-tasks/issues/15837#issuecomment-1029607260 check this comment. Maybe it can guide us to look in the IIS and not in the agent itself (?) 
But there has been no change in any part. This pipeline was working for 2 years +
