### ISSUE TITLE
PublishTestResults does not follow "retryCountOnTaskFailure" and instead fails immediately after failure

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/azure-pipelines-tasks#15922]
## Required Information

*Type*: Bug

**Enter Task Name**: PublishTestResults@2  

## Environment
- Server - Azure Pipelines Internal Microsoft

## Issue Description

We have encountered flakiness in the Publish Test results task which is critical for us since we use post processing to determine if a test that failed was flaky or not and modify the final build result based on that.

Recently we have received a major source of flakiness when trying to publish the the test results with an error of : 

```
##[error]The HTTP request timed out after 00:00:30.
```

To mitigate this we tried to add the retry param : 

```retryCountOnTaskFailure: 4``` 

This did not actual perform any retries

### Task logs

```
##[error]The HTTP request timed out after 00:00:30.
##[debug]System.TimeoutException: The HTTP request timed out after 00:00:30.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.EnsureConnectedAsync(ConnectOptions optionsNeeded, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.CheckForServerUpdatesAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.FindServiceDefinitionAsync(String serviceType, Guid serviceIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.LocationForCurrentConnectionAsync(String serviceType, Guid serviceIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
   at Microsoft.VisualStudio.Services.Agent.Worker.LegacyTestResults.TestResultsServer.InitializeServer(VssConnection connection, IExecutionContext executionContext)
   at Microsoft.VisualStudio.Services.Agent.Worker.LegacyTestResults.TestRunPublisher.InitializePublisher(IExecutionContext executionContext, VssConnection connection, String projectName, IResultReader resultReader)
   at Microsoft.VisualStudio.Services.Agent.Worker.LegacyTestResults.LegacyTestRunDataPublisher.InitializePublisher(IExecutionContext context, String projectName, VssConnection connection, String testRunner, Boolean publishRunLevelAttachments)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.PublishTestResultsCommand.PublishTestRunDataAsync(String teamProject, TestRunContext testRunContext)
   at Microsoft.VisualStudio.Services.Agent.Worker.AsyncCommandContext.WaitAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
Finishing: Publish Test Results
```

**Comment by octogonz** [comment]
We encountered `[error]The HTTP request timed out after 00:00:30` yesterday using Microsoft cloud-hosted Azure DevOps. 

(Here's the ID if someone wants to investigate:  `_build/results?buildId=108733&view=logs&jobId=8b5257b2-d883-523e-fd34-84fe1dbbb47f&j=8b5257b2-d883-523e-fd34-84fe1dbbb47f&t=a0de8091-1550-55e0-ec93-68ec4652c8f1&s=96ac2280-8cb4-5df5-99de-dd2da759617d` at `Mar 14, 2022 at 3:25 PM PDT`)

The pipeline succeeded when it was rerun, which suggests that `PublishTestResults@2` is not retrying robustly.

**Comment by golubev-ivan** [comment]
Hi @mastrzyz, I think this problem is related to the agent.
Could you please provide some additional information on this issue?
- What agent are you using, Azure Pipelines or self-hosted?
- What version of the agent are you using? (If you are using self-hosted agent)
- Сould you please share the error logs from _diag folder?

**Comment by DenisRumyantsev** [comment]
Hi @mastrzyz @octogonz, let me close this issue for now. Feel free to reopen it and provide additional info for further investigation

**Comment by octogonz** [comment]
Our issue was with Microsoft-hosted agents, not self-hosted.

**Comment by octogonz** [comment]
> To mitigate this we tried to add the retry param :
>
> `retryCountOnTaskFailure: 4`
>
> This did not actual perform any retries



@DenisRumyantsev how do you explain this? Is it expected behavior?

**Comment by DenisRumyantsev** [comment]
@octogonz could you please share logs of the failed pipeline with
`System.Debug` and `agent.diagnostic` pipeline variables enabled?
```yml
variables:
  System.Debug: true
  agent.diagnostic: true
```
