### ISSUE TITLE
Unable to build VSTestV2

### ISSUE THREAD

**Issue by tbolon** [microsoft/azure-pipelines-tasks#15939]
## Required Information

**Type**: Bug
**Enter Task Name**: VSTestV2 and VSTestV3

## Environment

```
> node -v && npm -v
v17.0.1
8.1.3
```

## Issue Description

Unable to build VsTestV2

### Task logs

```
> node .\make.js build --task VsTestV2

> prepending PATH C:\code\external\microsoft\azure-pipelines-tasks\node_modules\.bin
tsc tool:
Version 2.3.4
C:\CODE\EXTERNAL\MICROSOFT\AZURE-PIPELINES-TASKS\NODE_MODULES\.BIN\TSC.CMD
npm tool:
8.1.3
C:\PROGRAM FILES\NODEJS\NPM.CMD

------------------------------------------------------------
Building: VsTestV2
------------------------------------------------------------

> getting task externals
Downloading file: https://testselectorv2.blob.core.windows.net/testselector/7841796/TestSelector.zip
Could not use "nc", falling back to slower node.js method for sync requests.
C:\code\external\microsoft\azure-pipelines-tasks\node_modules\sync-request\index.js:77
    throw new Error(res.stderr.toString());
    ^

Error
    at doRequestWith (C:\code\external\microsoft\azure-pipelines-tasks\node_modules\sync-request\index.js:77:11)
    at doRequest (C:\code\external\microsoft\azure-pipelines-tasks\node_modules\sync-request\index.js:20:10)
    at downloadFile (C:\code\external\microsoft\azure-pipelines-tasks\make-util.js:411:22)
    at downloadArchive (C:\code\external\microsoft\azure-pipelines-tasks\make-util.js:451:27)
    at C:\code\external\microsoft\azure-pipelines-tasks\make-util.js:644:33
    at Array.forEach (<anonymous>)
    at getExternals (C:\code\external\microsoft\azure-pipelines-tasks\make-util.js:639:25)
    at C:\code\external\microsoft\azure-pipelines-tasks\make.js:193:13
    at Array.forEach (<anonymous>)
    at Function.target.build (C:\code\external\microsoft\azure-pipelines-tasks\make.js:158:14)

Node.js v17.0.1
```

**Comment by tbolon** [comment]
The issue is still present on a clean install

```
> node -v && npm -v
v17.4.0
8.11.0
> node .\make.js build --task VsTestV2

> prepending PATH C:\code\extern\microsoft\azure-pipelines-tasks\node_modules\.bin
tsc tool:
Version 2.3.4
C:\CODE\EXTERN\MICROSOFT\AZURE-PIPELINES-TASKS\NODE_MODULES\.BIN\TSC.CMD
npm tool:
8.11.0
C:\PROGRAM FILES\NODEJS\NPM.CMD

------------------------------------------------------------
Building: VsTestV2
------------------------------------------------------------

> getting task externals
Downloading file: https://testselectorv2.blob.core.windows.net/testselector/7841796/TestSelector.zip
Could not use "nc", falling back to slower node.js method for sync requests.
C:\code\extern\microsoft\azure-pipelines-tasks\node_modules\sync-request\index.js:77
    throw new Error(res.stderr.toString());
    ^

Error
    at doRequestWith (C:\code\extern\microsoft\azure-pipelines-tasks\node_modules\sync-request\index.js:77:11)
    at doRequest (C:\code\extern\microsoft\azure-pipelines-tasks\node_modules\sync-request\index.js:20:10)
    at downloadFile (C:\code\extern\microsoft\azure-pipelines-tasks\make-util.js:411:22)
    at downloadArchive (C:\code\extern\microsoft\azure-pipelines-tasks\make-util.js:451:27)
    at C:\code\extern\microsoft\azure-pipelines-tasks\make-util.js:644:33
    at Array.forEach (<anonymous>)
    at getExternals (C:\code\extern\microsoft\azure-pipelines-tasks\make-util.js:639:25)
    at C:\code\extern\microsoft\azure-pipelines-tasks\make.js:183:13
    at Array.forEach (<anonymous>)
    at Object.CLI.build (C:\code\extern\microsoft\azure-pipelines-tasks\make.js:149:14)

Node.js v17.4.0
```

**Comment by tbolon** [comment]
Still there:

```
node .\make.js build --task VsTestV2

> prepending PATH C:\code\external\microsoft\azure-pipelines-tasks\node_modules\.bin
tsc tool:
Version 2.3.4
C:\CODE\EXTERNAL\MICROSOFT\AZURE-PIPELINES-TASKS\NODE_MODULES\.BIN\TSC.CMD
npm tool:
8.1.3
C:\PROGRAM FILES\NODEJS\NPM.CMD

------------------------------------------------------------
Building: VsTestV2
------------------------------------------------------------

> getting task externals
Downloading file: https://testselectorv2.blob.core.windows.net/testselector/7841796/TestSelector.zip
Could not use "nc", falling back to slower node.js method for sync requests.
C:\code\external\microsoft\azure-pipelines-tasks\node_modules\sync-request\index.js:77
    throw new Error(res.stderr.toString());
    ^

Error
    at doRequestWith (C:\code\external\microsoft\azure-pipelines-tasks\node_modules\sync-request\index.js:77:11)
    at doRequest (C:\code\external\microsoft\azure-pipelines-tasks\node_modules\sync-request\index.js:20:10)
    at downloadFile (C:\code\external\microsoft\azure-pipelines-tasks\make-util.js:414:22)
    at downloadArchive (C:\code\external\microsoft\azure-pipelines-tasks\make-util.js:458:27)
    at C:\code\external\microsoft\azure-pipelines-tasks\make-util.js:655:33
    at Array.forEach (<anonymous>)
    at getExternals (C:\code\external\microsoft\azure-pipelines-tasks\make-util.js:650:25)
    at C:\code\external\microsoft\azure-pipelines-tasks\make.js:185:13
    at Array.forEach (<anonymous>)
    at CLI.build (C:\code\external\microsoft\azure-pipelines-tasks\make.js:151:14)

Node.js v18.7.0
```

I will now try VSTestV3...

**Comment by tbolon** [comment]
I updated the title of the issue with VSTestV3 as I have exactly the same problem.

Also note that I am using windows to build tasks.

It's hard to contribute when the build does not work :(

**Comment by pvanbaren** [comment]
The problem is the version of sync-request.  If you edit the package.json file to use sync-request version 6.1.0 (instead of 4.1.0) then the build will succeed.

**Comment by tbolon** [comment]
As said in the comments when trying to build:

```
==========================================
IMPORTANT NOTE: There are additional tasks that need to be build with a different node configuration.
Unfortunately, we cannot switch node versions while running make.js.  Run the following commands to continue:
nvm use 20.3.1
node make.js build --task VsTestV2 --node Node20
==========================================
```

you have to install nvm (using winget on windows `Winget install nvm-windows`), then you can restart your prompt and run the commands. The build will succeed.
