### ISSUE TITLE
(S)FTP behind a proxy

### ISSUE THREAD

**Issue by paule96** [microsoft/azure-pipelines-tasks#16087]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Bug, or Feature**  (depends how you see it)
*Type*: Proxy support

**Enter Task Name**: FtpUpload

## Environment
- Server - Azure DevOps Server on-premises?
    
    - If using Azure DevOps Server on-premises, provide the version: Version Dev17.M153.5 -  Azure DevOps Server 2020 Update 1.1 

- Agent - Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
       - Windows 6.3.9600 - 10.0.17763 
       -  Agent: 2.153.1

## Issue Description

(S)FTP has inbuild Proxy support, but you can't enable this support with the FTP task here. Our agents are configured with [this guide](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows).
The Ftp task should use the proxy function of the sdk described [here](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/proxy.md) to get the proxy configuration. Then it should call the (s)ftp tool with the proxy option.
Saddly I don't have myself the know how to do it.

I only know that setting the environment variable `ftp_proxy` should help.

### Task logs

```bash
SFTP:

2022-03-29T18:19:15.0684898Z connecting to: ****:22
2022-03-29T18:19:45.1046666Z (node:10572) UnhandledPromiseRejectionWarning: Error: Timeout (control socket)
2022-03-29T18:19:45.1046996Z     at Socket.socket.once (F:\Agent_01\_tasks\FtpUpload_6f8c69a5-b023-428e-a125-fccf4efcb929\2.151.2\node_modules\basic-ftp\dist\FtpContext.js:269:58)
2022-03-29T18:19:45.1047132Z     at Object.onceWrapper (events.js:273:13)
2022-03-29T18:19:45.1047201Z     at Socket.emit (events.js:182:13)
2022-03-29T18:19:45.1047252Z     at Socket._onTimeout (net.js:449:8)
2022-03-29T18:19:45.1047303Z     at ontimeout (timers.js:436:11)
2022-03-29T18:19:45.1047372Z     at tryOnTimeout (timers.js:300:5)
2022-03-29T18:19:45.1047436Z     at listOnTimeout (timers.js:263:5)
2022-03-29T18:19:45.1047500Z     at Timer.processTimers (timers.js:223:10)
2022-03-29T18:19:45.1047581Z (node:10572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2022-03-29T18:19:45.1047680Z (node:10572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2022-03-29T18:19:45.1111206Z ##[section]Finishing: FTP Upload: $(Build.ArtifactStagingDirectory)

FTP:

2022-03-29T18:08:30.4592120Z connecting to: ****:21
2022-03-29T18:08:31.5301328Z (node:11312) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED ***.***.***.***:21 (control socket)
2022-03-29T18:08:31.5301568Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
2022-03-29T18:08:31.5301726Z (node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2022-03-29T18:08:31.5301850Z (node:11312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by KonstantinTyukalov** [comment]
Hi @paule96! Thank you for providing information. 
The `FtpUpload` task does not yet support proxy configuration. We will consider possible solutions once we have dealt with the higher priority tickets.

**Comment by max-zaytsev** [comment]
@paule96, please note that **_FTP Upload task_** supports (`FTP`) and  `FTPS` protocols, not `SFTP` (see [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/ftp-upload?view=azure-devops)).
The task uses [basic-ftp](https://github.com/patrickjuchli/basic-ftp) package under the hood which doesn't provide such [functionality](https://github.com/patrickjuchli/basic-ftp/issues/192), so this cannot be added at the moment.

As far as I can see, there is an existing solution in marketplace for this ([SFTP Upload](https://marketplace.visualstudio.com/items?itemName=jean-marc-ducasse.sftpupload&ssr=false#overview))
Could you please try this task and provide your feedback?

**Comment by paule96** [comment]
@max-zaytsev yes I saw this reference on basic-ftp. And as mentioned in your linked issue there is a possibility to implement proxy support.
So maybe we could still bring proxy support in a longer iteration. So the question is, if we can add the support to basic-ftp. The problem for me, is just that I don't have enough know how about ftp as a protocol. So for me it would be a relatively long way. 

The problem with external extensions is always, that they must be go over multiple iteration and count as external software in my company. So it's easier to get the next version of Azure Devops server then a new extension. (and yes I know it's an internal problem)

**Comment by paule96** [comment]
Please don't close it github bot 🙏
