### ISSUE TITLE
Blob is incomplete (missing block)

### ISSUE THREAD

**Issue by pradipd** [microsoft/azure-pipelines-tasks#16132]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug and question

**Enter Task Name**: 
- task: PublishBuildArtifacts@1

## Environment
Server: Azure Pipelines
Agent: Private
OS: Ubuntu 20.04 (or 18.04)

## Issue Description
We are running into the following error when trying to publish a zipped vhd (~6GB I think).  Is there a size limit on publish task?
```
2022-04-08T18:08:14.7384927Z Chunk '1599' attempt '1' of file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: 3202b98e64b7ec11997e0050f2a59898, Expected Offset: 0, Actual Offset: 6702497792
 ---> System.InvalidOperationException: Blob is incomplete (missing block). Blob: 3202b98e64b7ec11997e0050f2a59898, Expected Offset: 0, Actual Offset: 6702497792
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState).
2022-04-08T18:08:14.7387071Z Backoff 7.584 seconds before attempt '2' chunk '1599' of file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz'.
2022-04-08T18:08:14.7387502Z Attempt '2' for uploading chunk '1599' of file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz'.
2022-04-08T18:08:14.7387952Z Generate new HttpRequest for uploading file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz', chunk '1599' of '1599'.
2022-04-08T18:08:14.7388434Z Start uploading file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz' to server, chunk '1599'.
2022-04-08T18:08:14.7391060Z Chunk '1599' attempt '2' of file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: 3202b98e64b7ec11997e0050f2a59898, Expected Offset: 0, Actual Offset: 6702497792
```

### Task logs

We can provide zipped logs.  Where do we upload them?

## Troubleshooting
Unfortunately, I did not see anything related to this issue here: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
```
2022-04-08T18:08:14.7384927Z Chunk '1599' attempt '1' of file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: 3202b98e64b7ec11997e0050f2a59898, Expected Offset: 0, Actual Offset: 6702497792
 ---> System.InvalidOperationException: Blob is incomplete (missing block). Blob: 3202b98e64b7ec11997e0050f2a59898, Expected Offset: 0, Actual Offset: 6702497792
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState).
2022-04-08T18:08:14.7387071Z Backoff 7.584 seconds before attempt '2' chunk '1599' of file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz'.
2022-04-08T18:08:14.7387502Z Attempt '2' for uploading chunk '1599' of file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz'.
2022-04-08T18:08:14.7387952Z Generate new HttpRequest for uploading file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz', chunk '1599' of '1599'.
2022-04-08T18:08:14.7388434Z Start uploading file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz' to server, chunk '1599'.
2022-04-08T18:08:14.7391060Z Chunk '1599' attempt '2' of file 'ASE-Images/ase-image-1.21.7-182073-vhd.tar.gz' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: 3202b98e64b7ec11997e0050f2a59898, Expected Offset: 0, Actual Offset: 6702497792

```

**Comment by pradipd** [comment]
@angop95 FYI

**Comment by pradipd** [comment]
We were able to resolve this by moving from publishbuildartifact to publishpipelineartifact.
