### ISSUE TITLE
AzureStaticWebApp@0 gets permission denied error when executed on self-hosted agent

### ISSUE THREAD

**Issue by jswiniarski** [microsoft/azure-pipelines-tasks#16156]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*:  Bug

**Enter Task Name**: AzureStaticWebApp@0

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      -  Account: nethansa
      -  Project: Clipperon
      - Build def name: React app DEV 
      - Build no.: 20220414.2

- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
      - Ubuntu
      - Agent ver.: 2.200.2

## Issue Description

When task is executed some files are created in Build.SourcesDirectory.
In my case those new files are located in node_modules and build directories and they are a normal outbut from building Create React App build.
When pipeline is executed on hosted agent each bulid gets clean workspace, so there are no output files from previous build. In this case everything is ok.

But when pipeline is executed on **self-hosted** agent the next build fails at git checkout task because `git clean` cannot remove output files which are generated within git workspace directory. Execution fails with many errors like this one:
```
##[error]System.UnauthorizedAccessException: Access to the path '/home/agent/AZagent/_work/38/s/node_modules/core-js/web/index.js' is denied.
```

The reason is that files generated as output from the task are owned by different user than user under which agent is executed.
This different user is an user under which Docker daemon is running, because as I've learned AzureStaticWebApp task is performed by running Docker container.

On screenshot you can see directories `node_modules` and `builds` owned by root (Docker daemon run under root) and input files owned by agent user. 

![Zrzut ekranu 2022-04-14 111609-2](https://user-images.githubusercontent.com/67765588/163482370-f6ca5c96-7c0f-4e05-8fb7-b81b3d58bdeb.jpg)

### Task logs

[logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8492402/logs.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Fragment of logs. Full logs with diagnostics zipped and attached above.

```
2022-04-13T22:24:02.4831001Z warning: failed to remove node_modules/core-js/README.md: Permission denied
2022-04-13T22:24:02.4832926Z ##[debug]STDOUT/STDERR stream read finished.
2022-04-13T22:24:02.4833339Z ##[debug]STDOUT/STDERR stream read finished.
2022-04-13T22:24:02.4833777Z ##[debug]Exited process 21487 with exit code 1
2022-04-13T22:24:02.4834210Z ##[debug]Finished process 21487 with exit code 1, and elapsed time 00:00:00.5372445.
2022-04-13T22:24:02.4835023Z ##[debug]'git clean -ffdx' failed with exit code 1, this normally caused by:
    1) Path too long
    2) Permission issue
    3) File in use
For futher investigation, manually run 'git clean -ffdx' on repo root: /home/agent/AZagent/_work/38/s after each build.
2022-04-13T22:24:02.4852631Z ##[warning]Unable to run "git clean -ffdx" and "git reset --hard HEAD" successfully, delete source folder instead.
2022-04-13T22:24:02.4858328Z ##[debug]Processed: ##vso[task.logissue type=warning;]Unable to run "git clean -ffdx" and "git reset --hard HEAD" successfully, delete source folder instead.
2022-04-13T22:24:02.4859011Z ##[error]One or several exceptions have been occurred.
2022-04-13T22:24:02.4859463Z ##[debug]Processed: ##vso[task.logissue type=error;]One or several exceptions have been occurred.
2022-04-13T22:24:02.4864380Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2022-04-13T22:24:02.4867599Z ##[error]System.UnauthorizedAccessException: Access to the path '/home/agent/AZagent/_work/38/s/node_modules/core-js/web/index.js' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.FileInfo.Delete()
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.<>c__DisplayClass11_0.<DeleteDirectory>b__0(FileSystemInfo item)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by sapeavy** [comment]
This has become an enormous issue in our pipeline since adopting this task. Please fix this ASAP. The workspace isn't cleaning due to this elevated permission and it absolutely devastates every build on the same pipeline until the agent is removed. It happens for every single deployment.

**Comment by knnhcn** [comment]
Just ran into this today. Any updates on how to fix or improve?

**Comment by iamaslam17** [comment]
I am having the similar issue 

##[warning]Unable to run "git clean -ffdx" and "git reset --hard HEAD" successfully, delete source folder instead.
##[error]One or several exceptions have been occurred.
##[error]System.UnauthorizedAccessException: Access to the path '/home/myuser/myagent/_work/25/s/myartifacts/myfiles/.gitignore' is denied.

is there any updates on the issue?

**Comment by MtSimba** [comment]
I receive the same error and I don't identify a solid fix. 

Can this issue be re-opened and addressed so a solution can be discovered?

**Comment by KoenduBuf** [comment]
We ran into the same problem. For anyone still struggeling with this issue, here is a possible solution that worked for us.

After the `AzureStaticWebApp@0` task, we added a task to clean up a possible docker container and delete any files left in the project folder using this pipeline step:
```
  - task: Bash@3
    condition: always()
    inputs:
      targetType: 'inline'
      script: |
        SWA_DOCKER_ID=$(docker ps -a -q --filter ancestor=mcr.microsoft.com/appsvc/staticappsclient:stable --format="{{.ID}}")
        echo "Stopping docker container '$SWA_DOCKER_ID' if any"
        [ ! -z "$SWA_DOCKER_ID" ] && docker rm $(docker stop $SWA_DOCKER_ID)
        echo "Cleaning files in working dir: $PWD"
        sudo chmod -R 777 ./*
        sudo rm -r ./*
```

This resolved the permission denied errors on the next and any subsequent runs.

**Comment by felicksLindgren** [comment]
@KoenduBuf Do you guys cache .next/cache as well before AzureStaticWebApp@0?

**Comment by KoenduBuf** [comment]
Well no, but we don't use next.js
