### ISSUE TITLE
Azure pipeline XCode build task times out on Running script '[CP] Check Pods Manifest.lock'

### ISSUE THREAD

**Issue by aimore** [microsoft/azure-pipelines-tasks#16475]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
I am running a Xcode clean build pipeline task in Azure devops

- task: Xcode@5 

and it does get stuck when running the script bellow.

If I run it using the UAT scheme it does succeed the issue happens only using release build

``` 
▸ Running script '[CP] Check Pods Manifest.lock'
##[debug]Re-evaluate condition on job cancellation for step: 'Xcode Build'.
##[error]The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
```

Here is the task:

```      
        - task: Xcode@5
        displayName: 'Xcode Build'
        continueOnError: ${{ parameters.CanContinue }}
        inputs:
          actions: 'clean build'
          ${{ if eq(variables['configuration'], 'DEBUG' ) }}:
            scheme: 'MyProject_UAT_Debug'
          ${{ if eq(variables['configuration'], 'UAT' ) }}:
            scheme: 'MyProject_UAT_Release'
          ${{ if eq(variables['configuration'], 'RELEASE' ) }}:
            scheme: 'MyProject_PROD_Release'
          sdk: '$(sdk)'
          configuration: $(configuration)
          xcWorkspacePath: 'MyProject.xcworkspace'
          xcodeVersion: 'default'
          packageApp: true
          signingOption: 'manual'
          provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
          signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
          exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'

**Enter Task Name**:  task: Xcode@5

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 


- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by SvetlanaMaliugina** [comment]
Hi @aimore, could you please share the following info?

- Do you use Azure DevOps Services or On-prem solution?
- Which type of agent pool is used in your pipeline?(Self-hosted/MS-hosted)?
- Could you please share full pipeline logs from the last successful run and failed run? ([Related doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#view-and-download-logs))
- If you are using an On-prem solution could you please share agent logs? ([Worker diagnostic log](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#worker-diagnostic-logs) / [Agent diagnostic logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#agent-diagnostic-logs))
- If you are using Azure DevOps Services could you please share the link to failed pipeline run?
- Please clarify the pipeline agent version that is used for your pipeline?

**Comment by aimore** [comment]
- Azure DevOps Services
- MS-hosted
**- Azure DevOps pipeline link** 
[Pipelines - Run 20220623.7 (visualstudio.com)](https://linkgroup-ds.visualstudio.com/Investor%20Centre/_build/results?buildId=73913&view=results)

**LOGS**

2022-06-23T07:32:43.9274780Z                                                                      ^

2022-06-23T07:32:43.9285660Z

2022-06-23T07:32:43.9316700Z

2022-06-23T07:32:43.9342410Z ▸ Compiling RCNConstants3P.m

2022-06-23T07:32:43.9364460Z ▸ Compiling RCNConfigSettings.m

2022-06-23T07:32:43.9371630Z ▸ Compiling RCNConfigExperiment.m

2022-06-23T07:32:43.9372930Z ▸ Compiling RCNConfigDBManager.m

2022-06-23T07:32:43.9374180Z ▸ Compiling RCNConfigContent.m

2022-06-23T07:32:43.9375430Z ▸ Compiling FirebaseRemoteConfig_vers.c

2022-06-23T07:32:43.9376790Z ▸ Compiling FirebaseRemoteConfig-dummy.m

2022-06-23T07:32:43.9378030Z ▸ Compiling FIRRemoteConfigComponent.m

2022-06-23T07:32:43.9379260Z ▸ Compiling FIRRemoteConfig.m

2022-06-23T07:32:44.0199430Z ▸ Compiling FIRConfigValue.m

2022-06-23T07:32:44.0208390Z ▸ Linking Eureka

2022-06-23T07:32:46.4604380Z ▸ Generating 'AlamofireNetworkActivityLogger.framework.dSYM'

2022-06-23T07:32:46.4610000Z ▸ Touching AlamofireNetworkActivityLogger.framework (in target 'AlamofireNetworkActivityLogger' from project 'Pods')

2022-06-23T07:32:46.4620300Z ▸ Touching FirebaseRemoteConfig.framework (in target 'FirebaseRemoteConfig' from project 'Pods')

2022-06-23T07:32:46.4621810Z ▸ Generating 'Eureka.framework.dSYM'

2022-06-23T07:32:46.7204380Z ▸ Touching Eureka.framework (in target 'Eureka' from project 'Pods')

2022-06-23T07:32:46.7355870Z ▸ Processing Pods-LinkProject-Info.plist

2022-06-23T07:32:46.7379150Z ▸ Copying Pods-LinkProject-umbrella.h

2022-06-23T07:32:46.7443560Z ▸ Compiling Pods-LinkProject-dummy.m

2022-06-23T07:32:46.9422320Z ▸ Compiling Pods_LinkProject_vers.c

2022-06-23T07:32:46.9688640Z ▸ Touching Pods_LinkProject.framework (in target 'Pods-LinkProject' from project 'Pods')

2022-06-23T07:32:46.9851100Z ▸ Running script '[CP] Check Pods Manifest.lock'

2022-06-23T07:41:15.0947680Z ##[debug]Re-evaluate condition on job cancellation for step: 'Xcode Build'.

2022-06-23T07:41:15.1320760Z ##[error]The operation was canceled.

2022-06-23T07:41:15.1339750Z ##[debug]System.OperationCanceledException: The operation was canceled.

   at System.Threading.CancellationToken.ThrowOperationCanceledException()

   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)

   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)

   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)

   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()

   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()

   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)

2022-06-23T07:41:15.1344480Z ##[section]Finishing: Xcode Build

**- Agent version**

2022-06-23T06:41:16.6034130Z Current agent version: '2.204.0'
