### ISSUE TITLE
DownloadPipelineArtifact V2.198.0 throws an error : ##[error]An error occurred while sending the request.

### ISSUE THREAD

**Issue by solkee** [microsoft/azure-pipelines-tasks#16532]
#Download Pipeline Artifacts tasks both in YAML and Classic pipelines throws an error when trying to download artifacts published as a part of previous job.
#Agent version:  '2.194.0'

#Raw Log from the task run:
2022-07-05T15:46:22.9253749Z ##[debug]Evaluating condition for step: 'Download Pipeline Artifact'
2022-07-05T15:46:22.9255109Z ##[debug]Evaluating: SucceededNode()
2022-07-05T15:46:22.9255567Z ##[debug]Evaluating SucceededNode:
2022-07-05T15:46:22.9256132Z ##[debug]=> True
2022-07-05T15:46:22.9256531Z ##[debug]Result: True
2022-07-05T15:46:22.9257012Z ##[section]Starting: Download Pipeline Artifact
2022-07-05T15:46:22.9335240Z ==============================================================================
2022-07-05T15:46:22.9335607Z Task         : Download Pipeline Artifacts
2022-07-05T15:46:22.9335919Z Description  : Download build and pipeline artifacts
2022-07-05T15:46:22.9336186Z Version      : 2.198.0
2022-07-05T15:46:22.9336428Z Author       : Microsoft Corporation
2022-07-05T15:46:22.9336780Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
2022-07-05T15:46:22.9337205Z ==============================================================================
2022-07-05T15:46:23.1690638Z ##[debug]TargetPath: D:\azuredevops_devagent_2\_work\501
2022-07-05T15:46:23.1699824Z ##[debug]ArtifactName: 
2022-07-05T15:46:23.1701448Z ##[debug]BuildResult: Succeeded
2022-07-05T15:46:23.1702152Z ##[debug]Run: CurrentRun
2022-07-05T15:46:23.1711404Z ##[debug]ProjectId: 16555bc9-fd33-4386-8f2b-caea3a1d1fa2
2022-07-05T15:46:23.1759735Z Download from the specified build: #95489
2022-07-05T15:46:23.1773991Z ##[debug]Processed: ##vso[task.setvariable variable=BuildNumber;issecret=False;]95489
2022-07-05T15:46:23.1774721Z Download artifact to: D:\azuredevops_devagent_2\_work\501
2022-07-05T15:47:05.9696377Z ##[error]An error occurred while sending the request.
2022-07-05T15:47:05.9706007Z ##[debug]Processed: ##vso[task.logissue type=error;]An error occurred while sending the request.
2022-07-05T15:47:05.9714201Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2022-07-05T15:47:05.9734805Z ##[debug]   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Agent.Plugins.BuildServer.GetArtifactsAsync(Guid project, Int32 pipelineId, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifactServer.DownloadAsyncV2(AgentTaskPluginExecutionContext context, ArtifactDownloadParameters downloadParameters, DownloadOptions downloadOptions, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV2_0_0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2022-07-05T15:47:05.9876156Z ##[section]Finishing: Download Pipeline Artifact

The agent where this task is running is self-hosted.
It is not behind proxy and is not blocked by any firewall rules.

**Comment by solkee** [comment]
You can **close** this issue as we discovered it was on our side where the agent servers were running for a long time. We rebooted the server and re-ran the pipelines and the error does not exists any more.
