### ISSUE TITLE
Internal Error in PublishTestResults@2 resulted in failed tests not failing the task

### ISSUE THREAD

**Issue by willieowens** [microsoft/azure-pipelines-tasks#16641]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      - Account Name: MicrosoftEsports
      - Team Project Name: hovercraft
      - Build Definition Name: hc-production
      - Build Number: #20220725.3
      - Build ID: 29944272
      - URL to task: https://msasg.visualstudio.com/MicrosoftEsports/_build/results?buildId=29944272&view=logs&j=b36e81a0-eb4f-54b4-8225-8ce966dd7e9d&t=e0591013-6e01-5cd5-218a-28b626131900

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
      - Agent name: 'Azure Pipelines 340'
      - Agent machine name: 'fv-az378-371'
      - Current agent version: '2.206.1'

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

**Internal task error resulted in failed tests not being reported, pipeline continued and caused a live site**.

![image](https://user-images.githubusercontent.com/1161333/180983263-3677b569-42f1-4aa4-aa6c-afd40c08d58e.png)

![image](https://user-images.githubusercontent.com/1161333/180983360-9a01d451-e87f-4c44-ba2d-e855b34a9dcc.png)

Task configuration in pipeline:
```
      - task: PublishTestResults@2
        displayName: Publish test result to ADO
        inputs:
          testRunner: JUnit
          testResultsFiles: 'test-*.xml'
          searchFolder: $(System.DefaultWorkingDirectory)/cypress-results
          failTaskOnFailedTests: true
          mergeTestResults: true
          testRunTitle: $(buildIdTag)
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

This was an intermittent error, so pasting logs directly below:
```
Starting: Publish test result to ADO
==============================================================================
Task         : Publish Test Results
Description  : Publish test results to Azure Pipelines
Version      : 2.203.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
==============================================================================
/usr/bin/dotnet --version
6.0.302
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
No Result Found to Publish '/home/vsts/work/1/s/cypress-results/test-output-57f4d8778c4987bda6a1790eaa703782.xml'.
Async Command Start: Publish test results
Publishing test results to test run '376211378'.
TestResults To Publish 108, Test run id:376211378
Test results publishing 108, remaining: 0. Test run id: 376211378
Published Test Run : https://msasg.visualstudio.com/MicrosoftEsports/_TestManagement/Runs?runId=376211378&_a=runCharts
##[warning]Intermittent failure attempting to call the restapis System.Threading.Tasks.Task`1[Microsoft.TeamFoundation.TestManagement.WebApi.TestRunStatistic] <GetTestRunSummaryAsync>b__0(). Retry attempt 0. Exception: Run summary is not available, It is recommended to try again after 1 sec. 
##[warning]Intermittent failure attempting to call the restapis System.Threading.Tasks.Task`1[Microsoft.TeamFoundation.TestManagement.WebApi.TestRunStatistic] <GetTestRunSummaryAsync>b__0(). Retry attempt 1. Exception: Run summary is not available, It is recommended to try again after 1 sec. 
##[warning]Intermittent failure attempting to call the restapis System.Threading.Tasks.Task`1[Microsoft.TeamFoundation.TestManagement.WebApi.TestRunStatistic] <GetTestRunSummaryAsync>b__0(). Retry attempt 2. Exception: Run summary is not available, It is recommended to try again after 1 sec. 
TestRunDataPublisher.DoesRunsContainsFailures: Exception occured using test run summary api System.AggregateException: One or more errors occurred. (Run summary is not available, It is recommended to try again after 1 sec.)
 ---> Microsoft.TeamFoundation.TestManagement.WebApi.TestObjectNotFoundException: Run summary is not available, It is recommended to try again after 1 sec.
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.RetryHelper.Retry[T](Func`1 action, Func`2 timeDelayInterval, Func`2 shouldRetryOnException)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestRunPublisher.GetTestRunSummaryAsync(String projectName, Int32 testRunId, Boolean allowRetry, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestRunDataPublisherHelper.DoesRunsContainsFailures(IList`1 testRuns, String projectName)
##[warning]TestRunDataPublisher.DoesRunsContainsFailures: Validating if test run is failed or succeeded based on summary where calulation of summary is not in completed state.
TestRunPublisher.IsTestRunFailed: Getting test run summary with run id: 376211378 using stats api
TestRunPublisher.IsTestRunFailed: checking if test run is failed using run summary input
Async Command End: Publish test results
Finishing: Publish test result to ADO
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
TestRunDataPublisher.DoesRunsContainsFailures: Exception occured using test run summary api System.AggregateException: One or more errors occurred. (Run summary is not available, It is recommended to try again after 1 sec.)
 ---> Microsoft.TeamFoundation.TestManagement.WebApi.TestObjectNotFoundException: Run summary is not available, It is recommended to try again after 1 sec.
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.RetryHelper.Retry[T](Func`1 action, Func`2 timeDelayInterval, Func`2 shouldRetryOnException)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestRunPublisher.GetTestRunSummaryAsync(String projectName, Int32 testRunId, Boolean allowRetry, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestRunDataPublisherHelper.DoesRunsContainsFailures(IList`1 testRuns, String projectName)
```

**Comment by willieowens** [comment]
Related: https://github.com/microsoft/azure-pipelines-tasks/issues/13275
