### ISSUE TITLE
Gradle build in Azure Devops Failure while using Selfhosted agents

### ISSUE THREAD

**Issue by yugeshmothukuru** [microsoft/azure-pipelines-tasks#16760]
##[debug]STDIO streams have closed for tool '/home/sfccdevopsuser01/selfhosted_agent/_work/3/QA_REPO/gradlew'
Error: The process '/home/sfccdevopsuser01/selfhosted_agent/_work/3/QA_REPO/gradlew' failed with exit code 1
##[debug]taskRunner fail
##[debug]Processing code analysis results
##[debug]System.DefaultWorkingDirectory=/home/sfccdevopsuser01/selfhosted_agent/_work/3/s
##[debug]build.artifactStagingDirectory=/home/sfccdevopsuser01/selfhosted_agent/_work/3/a
##[debug]build.buildNumber=20220818.6
##[debug][CA] Attempting to find report files from 4 code analysis tool(s)
##[debug]checkstyleAnalysisEnabled=false
##[debug][CA] Checkstyle analysis is not enabled.
##[debug]findbugsAnalysisEnabled=true
    at ExecState._setResult (/home/sfccdevopsuser01/selfhosted_agent/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.208.0/node_modules/azure-pipelines-task-lib/toolrunner.js:944:25)
    at ExecState.CheckComplete (/home/sfccdevopsuser01/selfhosted_agent/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.208.0/node_modules/azure-pipelines-task-lib/toolrunner.js:927:18)
    at ChildProcess.<anonymous> (/home/sfccdevopsuser01/selfhosted_agent/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.208.0/node_modules/azure-pipelines-task-lib/toolrunner.js:840:19)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
##[debug][CA] FindBugs parser found 0 possible modules to upload results from.
##[debug]pmdAnalysisEnabled=false
##[debug][CA] PMD analysis is not enabled.
##[debug]spotBugsAnalysisEnabled=false
##[debug][CA] SpotBugs analysis is not enabled.
##[debug][CA] Skipping artifact upload: No analysis results
##[debug]task result: Failed
##[error]Error: The process '/home/sfccdevopsuser01/selfhosted_agent/_work/3/QA_REPO/gradlew' failed with exit code 1
##[debug]Processed: ##vso[task.issue type=error;]Error: The process '/home/sfccdevopsuser01/selfhosted_agent/_work/3/QA_REPO/gradlew' failed with exit code 1
##[debug]Processed: ##vso[task.complete result=Failed;]Error: The process '/home/sfccdevopsuser01/selfhosted_agent/_work/3/QA_REPO/gradlew' failed with exit code 1
Finishing: Gradl

**Comment by kirill-ivlev** [comment]
Hi @yugeshmothukuru!
Thank you for your report,
Could you please confirm that you have a copy of the Gradle Wrapper in your project (as described in [official docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops#arguments))?

If the issue will still exist even with the shell wrapper, please share the YML step for this job, Agent Version, Operating system where agent is running.

**Comment by kirill-ivlev** [comment]
Hi @bhanukotturi 

We have no heard any updates on this issue during past 4 weeks.
I will close this issue due to inactivity.
Please, feel free to re-open it if this issue is still exist.
