### ISSUE TITLE
Artifacts is not downloaded - task Download Pipeline Artifacts successfully

### ISSUE THREAD

**Issue by ArturKedz** [microsoft/azure-pipelines-tasks#17023]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Download Pipeline Artifacts

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    -  Azure Pipelines, provide the account name, team project name, build definition name/build number: private but is more than one pipeline and more than one server
     

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version:  windows 2012 or 2019, azagent v2.202.1 or v2.210.1

## Issue Description

The release is a success but the download of the artefact failed on the self-hosted agent (Deployment group or agent).
The problem is not related to downloading Artifact - the error during download is an internal problem.
The reported problem is related to “Download Pipeline Artifacts”.
It is not good when the pipeline does not fail when one of the tasks is unsuccessful.
“Download Pipeline Artifacts” task cannot download artefacts but be finished successfully - that reported problem.

In that particular case, other task use artefacts downloaded in the previous release and deploy them.
Everything looks correct but isn’t and we still have the running the previous version.

See more https://developercommunity.visualstudio.com/t/Artifact-download-fail-Error-12002-call/10165868?space=21&q=%22Error+12002%22+calling+WINHTTP_CALLBACK_STATUS_REQUEST_ERROR&sort=newest&entry=myfeedback&viewtype=all

### Task logs

![image](https://user-images.githubusercontent.com/99714660/195054602-9cde13ab-b738-4ffd-8d81-6446094e393f.png)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
2022-10-06T11:31:52.0510930Z ##[debug]Evaluating condition for step: 'Download Pipeline Artifact'
2022-10-06T11:31:52.0583654Z ##[debug]Evaluating: succeeded()
2022-10-06T11:31:52.0593161Z ##[debug]Evaluating succeeded:
2022-10-06T11:31:52.0658425Z ##[debug]=> True
2022-10-06T11:31:52.0673308Z ##[debug]Result: True
2022-10-06T11:31:52.0750858Z ##[section]Starting: Download Pipeline Artifact
2022-10-06T11:31:52.1901103Z ==============================================================================
2022-10-06T11:31:52.1902538Z Task         : Download Pipeline Artifacts
2022-10-06T11:31:52.1903830Z Description  : Download build and pipeline artifacts
2022-10-06T11:31:52.1906856Z Version      : 2.198.0
2022-10-06T11:31:52.1908010Z Author       : Microsoft Corporation
2022-10-06T11:31:52.1909484Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
2022-10-06T11:31:52.1910637Z ==============================================================================
2022-10-06T11:31:53.5349680Z Download from the specified build: #88411
2022-10-06T11:31:53.5431367Z ##[debug]Processed: ##vso[task.setvariable variable=BuildNumber;issecret=False;]88411
2022-10-06T11:31:53.5433369Z Download artifact to: C:\azagent\A3\_work\r1\a/Deploy/output
2022-10-06T11:33:53.0177808Z ##[debug]Dedup parallelism: 192
2022-10-06T11:33:53.1450378Z ##[debug]Dedup parallelism: 192
2022-10-06T11:33:53.4123286Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 2a892b42-0f2c-47da-bfa2-3fe4fXXXXXXX
2022-10-06T11:33:53.4188207Z Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session 2a892b42-0f2c-47da-bfa2-3fe4fXXXXXXX
2022-10-06T11:33:53.4212549Z Information, Minimatch patterns: [output/WindowsService/*,output/WindowsService/**]
2022-10-06T11:34:25.6516124Z Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/Ab5e96b3e-d47a-4162-9dcc-2dd47eXXXXXXX/_apis/dedup/nodes/01E415FEDCD59F58B2FB9F09089DB6EE0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX attempt 1/6 failed with StatusCode RedirectMethod, IsRetryableResponse False
2022-10-06T11:34:47.4931161Z Warning, [https://23lvsblobprodsu6weus9.blob.core.windows.net/dbb5e96b3ed47a41629dcc2dd47ed309af/225EF2AF3C99CA3AE27097D0772B7C803EEFCAA111XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?sv=2019-07-07&sr=b&sig=F1IcYIJqNxPjtt7brfap834x%2FiRVLtetJN8XXXXXXX%3D&spr=https&se=2022-10-07T12%3A08%3A03Z&sp=r&rscl=x-e2eid-03e6d7df-336c462a-94d84a08-0XXXXXXX-session-2a892b42-0f2c47da-bfa23fe4-fbXXXXXX] Try 1/5, retryable exception caught. Retrying in 00:00:01. System.Net.Http.HttpRequestException: An error occurred while sending the request.
2022-10-06T11:34:47.4937980Z  ---> System.Net.Http.WinHttpException (80072EE2, 12002): Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.
2022-10-06T11:34:47.4939606Z    at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
2022-10-06T11:34:47.4940483Z    at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
2022-10-06T11:34:47.4941236Z    --- End of inner exception stack trace ---
2022-10-06T11:34:47.4942238Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2022-10-06T11:34:47.4944502Z    at Microsoft.VisualStudio.Services.Common.TaskCancellationExtensions.EnforceCancellation[TResult](Task`1 task, CancellationToken cancellationToken, Func`1 makeMessage, String file, String member, Int32 line)
2022-10-06T11:34:47.4945870Z    at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.<>c__DisplayClass57_0.<<GetRedirectResponseAsync>b__0>d.MoveNext()
2022-10-06T11:34:47.4946903Z --- End of stack trace from previous location where exception was thrown ---
2022-10-06T11:34:47.4947696Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2022-10-06T11:34:49.1835824Z Information, Filtered 0 files from the Minimatch filters supplied.
2022-10-06T11:34:49.2187092Z Information, Downloaded 0.0 MB out of 0.0 MB (100%).
2022-10-06T11:34:49.2468068Z Information, Downloaded 0.0 MB out of 0.0 MB (100%).
2022-10-06T11:34:49.2482844Z Information, 
2022-10-06T11:34:49.2484559Z Download statistics:
2022-10-06T11:34:49.2486328Z Total Content: 0.0 MB
2022-10-06T11:34:49.2493661Z Physical Content Downloaded: 0.0 MB
2022-10-06T11:34:49.2496892Z Compression Saved: 0.0 MB
2022-10-06T11:34:49.2499886Z Local Caching Saved: 0.0 MB
2022-10-06T11:34:49.2544597Z Chunks Downloaded: 0
2022-10-06T11:34:49.2546101Z Nodes Downloaded: 0
2022-10-06T11:34:49.2547469Z 
2022-10-06T11:34:49.2592367Z Information, Download completed.
2022-10-06T11:34:49.3136305Z ##[debug]Processed: ##vso[telemetry.publish area=AzurePipelinesAgent;feature=PipelineArtifact]{"FileCount":"0","PlanId":"5fe326d0-d831-45ab-bdf5-2c02ebXXXXXX","JobId":"fa06d1e8-155f-465c-b6b7-dff2e1XXXXXX","TaskInstanceId":"27bf3cd1-b572-4c29-a4c4-c3f5ceXXXXXX","ActionDurationMs":"55850","ActionName":"PipelineArtifact.DownloadMultipleArtifactsAsync","ActionResult":"Success","AttemptNumber":"1","ItemCount":"0","Level":"ThirdParty","CreatedUtcNow":"2022-10-06T11:33:53.4024879Z","SentUtcNow":"2022-10-06T11:34:49.2605028Z","BaseAddress":"https://vsblobprodsu6weu.vsblob.visualstudio.com/Ab5e96b3e-d47a-4162-9dcc-2dd47XXXXXX/","X_TFS_Session":"2a892b42-0f2c-47da-bfa2-3fe4fbXXXXXX","DeploymentEnvironment":"PRODUCTION","DeploymentEnvironmentIsProduction":"True","VSOAccount":"vsblobprodsu6weu","OSName":"Microsoft Windows","OSVersion":"10.0.17763","FrameworkDescription":".NET Core ","ProcessName":"Agent.PluginHost","DotNetReleaseDword":"-1","Version":"18.164.29709.0 built by: master (818cXXXXXX)","ExceptionCount":"0"}
2022-10-06T11:35:04.2853016Z Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 2a892b42-0f2c-47da-bfa2-3fe4fbXXXXXX
2022-10-06T11:35:04.2868517Z Downloading artifact finished.
2022-10-06T11:35:04.3120969Z ##[section]Finishing: Download Pipeline Artifact```

**Comment by ArturKedz** [comment]
issue resolved, wrong settings. Can be closed.
