### ISSUE TITLE
Workflow to label issues failed with 401

### ISSUE THREAD

**Issue by abatishchev** [microsoft/azure-pipelines-tasks#17253]
See also https://github.com/microsoft/azure-pipelines-tasks/issues/17107.

A workflow for https://github.com/microsoft/azure-pipelines-tasks/issues/17252 failed with an error:

```
Error: Failed request: (401)
    at RestClient.<anonymous> (/home/runner/work/azure-pipelines-tasks/azure-pipelines-tasks/node_modules/typed-rest-client/RestClient.js:202:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/azure-pipelines-tasks/azure-pipelines-tasks/node_modules/typed-rest-client/RestClient.js:6:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 401
```

See https://github.com/microsoft/azure-pipelines-tasks/actions/runs/3518879727/jobs/5898253969#step:6:126

**Comment by Roman-Shchukin** [comment]
Hi @abatishchev  thanks for reporting! Fixed.

**Comment by abatishchev** [comment]
Hey @Roman-Shchukin it's failing again:

```
Error: ﻿{"$id":"1","customProperties":{"Descriptor":null,"IdentityDisplayName":null,"Token":null,"RequestedPermissions":0,"NamespaceId":"00000000-0000-0000-0000-000000000000"},"innerException":null,"message":"Access Denied: The Personal Access Token used has expired.","typeName":"Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi","typeKey":"AccessCheckException","errorCode":0,"eventId":3000}
```

See https://github.com/microsoft/azure-pipelines-tasks/actions/runs/5698212298/job/15445847160#step:6:99
