### ISSUE TITLE
DownloadPipelineArtifact fails with exit code 137

### ISSUE THREAD

**Issue by ppennanen** [microsoft/azure-pipelines-tasks#17353]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPipelineArtifactV1, DownloadPipelineArtifactV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

offerata, Offerta, offerta-migration, #20221206.9  

- Agent - Hosted or Private: 
    
Private. 

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Agent is running in a docker image based on Ubuntu 20.04,  agent version `2.213.2`. 

## Issue Description

The `DownloadPipelineArtifactV2` task in our db migration pipeline fails with exit code `137` after upgrading the agent docker image from Ubuntu 18.04 with agent `2.194.0`  to Ubuntu 20.04 and agent `2.213.2`.

Please note that the agent pod is _not_ killed with OOM (it is below memory requirements), that is only the return code for the task itself.

### Task logs

```
2022-12-06T12:26:02.6955938Z ##[debug]Evaluating condition for step: 'Download Artifact'
2022-12-06T12:26:02.6959549Z ##[debug]Evaluating: SucceededNode()
2022-12-06T12:26:02.6960592Z ##[debug]Evaluating SucceededNode:
2022-12-06T12:26:02.6962490Z ##[debug]=> True
2022-12-06T12:26:02.6964254Z ##[debug]Result: True
2022-12-06T12:26:02.6965425Z ##[section]Starting: Download Artifact
2022-12-06T12:26:02.6994978Z ==============================================================================
2022-12-06T12:26:02.6995770Z Task         : Download pipeline artifact
2022-12-06T12:26:02.6996768Z Description  : Download a named artifact from a pipeline to a local path
2022-12-06T12:26:02.6997437Z Version      : 1.198.0
2022-12-06T12:26:02.6997955Z Author       : Microsoft Corporation
2022-12-06T12:26:02.6999222Z Help         : Download a named artifact from a pipeline to a local path
2022-12-06T12:26:02.7000041Z ==============================================================================
2022-12-06T12:26:03.0440405Z Download from the specified build: #76867
2022-12-06T12:26:03.0446939Z Download artifact to: /azp/_work/1/
2022-12-06T12:26:03.0920318Z Using default max parallelism.
2022-12-06T12:26:03.0936851Z Max dedup parallelism: 192
2022-12-06T12:26:03.8326891Z Verbose, ArtifactHttpClientFactory.CreateVssHttpClient: DedupStoreHttpClient with BaseUri: https://vsblobprodsu6weu.vsblob.visualstudio.com/A8ec123a9-0799-42db-8437-baca372761d1/, MaxRetries:5, SendTimeout:00:01:40
2022-12-06T12:26:03.9182785Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 5cfb3ef5-1276-4a67-a138-3bca4a33a56f
2022-12-06T12:26:03.9218111Z Verbose, Started ITelemetrySender BlobStoreApplicationInsightsTelemetrySender.
2022-12-06T12:26:03.9858886Z Downloading 1 pipeline artifacts...
2022-12-06T12:26:03.9931094Z Verbose, PipelineArtifact.DownloadAsync starting
2022-12-06T12:26:04.0035808Z Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session 5cfb3ef5-1276-4a67-a138-3bca4a33a56f
2022-12-06T12:26:04.0038800Z Information, Start downloading artifact - offerta-migration
2022-12-06T12:26:04.0044391Z Information, Minimatch patterns: [**]
2022-12-06T12:26:04.3023511Z Information, Filtered 45 files from the Minimatch filters supplied.
2022-12-06T12:26:04.3045388Z Verbose, Could not initialize dataport: Dataport will not be used as it is only currently available on Windows.
2022-12-06T12:26:04.3073102Z Information, Downloaded 0.0 MB out of 12.8 MB (0%).
2022-12-06T12:26:04.7860980Z Verbose, Downloaded /Microsoft.Bcl.AsyncInterfaces.dll
2022-12-06T12:26:05.3807257Z Verbose, Downloaded /Microsoft.IdentityModel.Protocols.dll
2022-12-06T12:26:05.3827029Z Verbose, Downloaded /Microsoft.SqlServer.Server.dll
2022-12-06T12:26:05.3828320Z Verbose, Downloaded /Microsoft.Win32.SystemEvents.dll
2022-12-06T12:26:05.3829472Z Verbose, Downloaded /Microsoft.Identity.Client.Extensions.Msal.dll
2022-12-06T12:26:05.3830599Z Verbose, Downloaded /Microsoft.IdentityModel.JsonWebTokens.dll
2022-12-06T12:26:05.3831886Z Verbose, Downloaded /Microsoft.IdentityModel.Abstractions.dll
2022-12-06T12:26:05.3832959Z Verbose, Downloaded /Microsoft.IdentityModel.Logging.dll
2022-12-06T12:26:05.3833909Z Verbose, Downloaded /Offerta.Migration.pdb
2022-12-06T12:26:05.3834846Z Verbose, Downloaded /Offerta.Data.OffertaSeMigration.deps.json
2022-12-06T12:26:05.3835854Z Verbose, Downloaded /Offerta.Data.OffertaSeMigration.pdb
2022-12-06T12:26:05.3836869Z Verbose, Downloaded /Offerta.Data.OffertaSeMigration.runtimeconfig.json
2022-12-06T12:26:05.3837861Z Verbose, Downloaded /Offerta.Migration.dll
2022-12-06T12:26:05.3838772Z Verbose, Downloaded /System.Memory.Data.dll
2022-12-06T12:26:05.3840327Z Verbose, Downloaded /dbup-sqlserver.dll
2022-12-06T12:26:05.3841379Z Verbose, Downloaded /runtimes/win/lib/netcoreapp3.0/Microsoft.Win32.SystemEvents.dll
2022-12-06T12:26:05.3842492Z Verbose, Downloaded /runtimes/win/lib/netcoreapp3.0/System.Windows.Extensions.dll
2022-12-06T12:26:05.3843600Z Verbose, Downloaded /Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
2022-12-06T12:26:05.3845028Z Verbose, Downloaded /System.IdentityModel.Tokens.Jwt.dll
2022-12-06T12:26:05.3846123Z Verbose, Downloaded /runtimes/win/lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll
2022-12-06T12:26:05.3847290Z Verbose, Downloaded /System.Security.Cryptography.ProtectedData.dll
2022-12-06T12:26:05.3848311Z Verbose, Downloaded /System.Windows.Extensions.dll
2022-12-06T12:26:06.4200165Z ##[error]Exit code 137 returned from process: file name '/azp/bin/Agent.PluginHost', arguments 'task "Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1_1_3, Agent.Plugins"'.
2022-12-06T12:26:06.4211379Z ##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 137 returned from process: file name '/azp/bin/Agent.PluginHost', arguments 'task "Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1_1_3, Agent.Plugins"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.AgentPluginManager.RunPluginTaskAsync(IExecutionContext context, String plugin, Dictionary`2 inputs, Dictionary`2 environment, Variables runtimeVariables, EventHandler`1 outputHandler)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.AgentPluginHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2022-12-06T12:26:06.4221271Z ##[section]Finishing: Download Artifact
```

### Error logs

```
##[error]Exit code 137 returned from process: file name '/azp/bin/Agent.PluginHost', arguments 'task "Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1_1_3, Agent.Plugins"'.
##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 137 returned from process: file name '/azp/bin/Agent.PluginHost', arguments 'task "Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1_1_3, Agent.Plugins"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.AgentPluginManager.RunPluginTaskAsync(IExecutionContext context, String plugin, Dictionary`2 inputs, Dictionary`2 environment, Variables runtimeVariables, EventHandler`1 outputHandler)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.AgentPluginHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

**Comment by ArneSchoonvliet** [comment]
@ppennanen Have you figured this one out? I'm hitting the same problem now with other versions. I feel it's something specific with the configuration. We run the agent in a k8s cluster and it's indeed the process itself killing it, not kubelet.
