### ISSUE TITLE
VSTest tests fail when batched and requiring access to intranet sql server

### ISSUE THREAD

**Issue by marshallw** [microsoft/azure-pipelines-tasks#17679]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest@2

## Environment

    Azure Pipelines
    Account name: iqmetrix
    Project Name: Phoenix
    build definition name: iQmetrix.Catalogs (1) 
    Build Number: #2.4.4.35

- Agent - Hosted or Private: 
    Agent is private.  
    Version: 2.200.2
    OS Version: WINDOWS_NT 10.0.14393

## Issue Description

I have a set of NUnit integration tests that take a long time to run.  I attempted to use the `distributionBatchType` option in order to batch the work by assembly and speed up execution.  What I found though is that our tests now fail while either setting up or tearing down tests, in particular while connecting to databases and other services on our local network.  These tests have succeeded on the exact same machine (a build agent running within our network) without batching.  Last bit of details is that the solution is built in one job, archived and published to artifact storage which is then downloaded in another job and extracted before tests are ran.  

### Task logs

[logs_461513.zip](https://github.com/microsoft/azure-pipelines-tasks/files/10528684/logs_461513.zip)

### Error logs

Example error: (sensitive information has been redacted; it only points to a local SQL server)

```##[debug]ProxyRunRequest: HandleLogMessage Entered
##[warning]RunMessage : TearDown failed for test fixture IQ.Catalogs.Services.IntegrationTests.CatalogRepositoryIntegrationTests
##[debug]Processed: ##vso[task.logissue type=warning;]RunMessage : TearDown failed for test fixture IQ.Catalogs.Services.IntegrationTests.CatalogRepositoryIntegrationTests
##[debug]ProxyRunRequest: HandleLogMessage Entered
##[warning]RunMessage : System.Exception : Can't connect to Data Source=IQ-RGVSQL018;Initial Catalog=Catalogs_IntegrationTest;User ID=CatalogsUser;Password=ZIvGWEjmzTIDbU5LKZ3v
##[debug]Processed: ##vso[task.logissue type=warning;]RunMessage : System.Exception : Can't connect to Data Source=[REDACTED]
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
##[debug]ProxyRunRequest: HandleLogMessage Entered
##[warning]RunMessage :    at IQ.Catalogs.IntegrationTests.Common.SqlTestDbHelper.BuildDatabase() in C:\Builds\_work\361\s\tests\IQ.Catalogs.IntegrationTests.Common\SqlTestDbHelper.cs:line 115
##[debug]Processed: ##vso[task.logissue type=warning;]RunMessage :    at IQ.Catalogs.IntegrationTests.Common.SqlTestDbHelper.BuildDatabase() in C:\Builds\_work\361\s\tests\IQ.Catalogs.IntegrationTests.Common\SqlTestDbHelper.cs:line 115
   at IQ.Catalogs.IntegrationTests.Common.SqlTestDbHelper.Build() in C:\Builds\_work\361\s\tests\IQ.Catalogs.IntegrationTests.Common\SqlTestDbHelper.cs:line 89
   at IQ.Catalogs.IntegrationTests.Common.SqlTestDbHelper..ctor() in C:\Builds\_work\361\s\tests\IQ.Catalogs.IntegrationTests.Common\SqlTestDbHelper.cs:line 31
   at IQ.Catalogs.IntegrationTests.Common.Scaffolding.SqlServerDatabaseIntegrationTestFixture.Setup() in C:\Builds\_work\361\s\tests\IQ.Catalogs.IntegrationTests.Common\Scaffolding\SqlServerDatabaseIntegrationTestFixture.cs:line 12
   at IQ.Catalogs.IntegrationTests.Common.SqlServerDatabaseIntegrationTestBase.run_once_before_any_tests_in_child_classes_are_run() in C:\Builds\_work\361\s\tests\IQ.Catalogs.IntegrationTests.Common\SqlServerDatabaseIntegrationTestBase.cs:line 27
--TearDown
   at IQ.Catalogs.IntegrationTests.Common.Scaffolding.SqlServerDatabaseIntegrationTestFixture.TearDown() in C:\Builds\_work\361\s\tests\IQ.Catalogs.IntegrationTests.Common\Scaffolding\SqlServerDatabaseIntegrationTestFixture.cs:line 17
   at IQ.Catalogs.IntegrationTests.Common.SqlServerDatabaseIntegrationTestBase.run_once_after_all_tests_in_child_classes_complete() in C:\Builds\_work\361\s\tests\IQ.Catalogs.IntegrationTests.Common\SqlServerDatabaseIntegrationTestBase.cs:line 41
```

**Comment by marshallw** [comment]
A quick update, this behavior also happens when not batching as well.  The common behavior seems to be running in a different job. (makes no difference if it's on the same machine or not)

**Comment by marshallw** [comment]
After modifying our ancient tests and fixing some errors that were getting eaten, it turns out a hardcoded file that we use isn't being copied over.  Closing issue.
