### ISSUE TITLE
Task DownloadBuildArtifacts v0.216.0 fails to download artifacts with a permissions error

### ISSUE THREAD

**Issue by lorengordon** [microsoft/azure-pipelines-tasks#17695]
Appears the task DownloadBuildArtifacts v0.216.0 was released within the last day, and jobs are now failing to actually download artifacts. Same jobs worked fine using 0.212.0 yesterday... Example of failing job: https://dev.azure.com/plus3it/watchmaker/_build/results?buildId=5479&view=logs&j=d4aecca3-a437-5e55-8920-532a8eb17862&t=d2b60228-a4a0-59db-48e2-009687a5b468&l=34

_Originally posted by @lorengordon in https://github.com/microsoft/azure-pipelines-tasks/issues/17299#issuecomment-1412662105_

Error message:

```
##[error]Failed in Download zip - .pyinstaller with error: Error: Failed rmRF: EPERM: operation not permitted, unlink 'D:\a\1\.pyinstaller.zip'
    at Object.rmRF (D:\a\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.216.0\node_modules\azure-pipelines-task-lib\task.js:1184:23)
    at D:\a\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.216.0\DownloadHandlers\DownloadHandlerContainerZip.js:87:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Successfully downloaded artifacts to D:\a\1\
##[error]Error: Failed rmRF: EPERM: operation not permitted, unlink 'D:\a\1\.pyinstaller.zip'
```

**Comment by lorengordon** [comment]
Was able to workaround the failure by disabling the auto-injected v0 task, and using v1:

```
        - download: none
        - task: DownloadBuildArtifacts@1
          displayName: Download Artifacts
          inputs:
            artifactName: $(artifactDir)
            downloadPath: $(System.DefaultWorkingDirectory)
```
