### ISSUE TITLE
DTAExecutionHost.exe' failed with exit code 3762504530

### ISSUE THREAD

**Issue by chilakamarthi** [microsoft/azure-pipelines-tasks#17744]
Current agent version: '2.213.2'
Task Version 2 for Visual Studio Test

We are encountering this issue once in 15-20 days and what we observe is test execution completed but task failed with this error

Using new test platform for test execution
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper instance will be created
##[error]Unhandled exception : System.AggregateException: One or more errors occurred. ---> Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\RSAcceptanceagent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.215.0\Modules\DTAExecutionHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.InitializeExtensions(IEnumerable`1 pathToAdditionalExtensions)
   at MS.VS.TestService.TestPlatform.v2.VsTestPlatformV2..ctor(String vstestConsolePath, List`1 adapterPaths, String diagFile, IConsoleWrapperFactory consoleWrapperFactory, String traceFile, ConsoleWrapperSettings consoleWrapperSettings)
   at Microsoft.VisualStudio.TestService.VstestAdapter.VstestUtilities.GetTestPlatformV2(IEnumerable`1 customVstestAdapterPaths, ConsoleWrapperSettings consoleWrapperSettings)
   at Microsoft.VisualStudio.TestService.VstestAdapter.DiscoverTests.PerformDiscovery(TestAutomationRunSlice sliceDetails, IAddTestCasesToTcmRunHandler addTestCasesToTcmRunHandler, ExecutionStateContext stateModelContext)
   at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.FetchPreviousPhaseData(ExecutionStateContext stateModelContext)
   at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.VisualStudio.TestService.ExecutionStateModel.DistributedTestExecutionAgent.ExecuteCurrentPhase(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestService.ExecutionStateModel.DistributedTestExecutionAgent.Execute(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestService.ExecutionStateModel.DistributedTestExecutionAgent.Start()
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.DistributedTestRunHost.InitializeAndStartExecutionHost(Boolean debugLogs)
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.DistributedTestRunHost.Execute(Boolean debugLogs)
---> (Inner Exception #0) Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\RSAcceptanceagent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.215.0\Modules\DTAExecutionHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.InitializeExtensions(IEnumerable`1 pathToAdditionalExtensions)
   at MS.VS.TestService.TestPlatform.v2.VsTestPlatformV2..ctor(String vstestConsolePath, List`1 adapterPaths, String diagFile, IConsoleWrapperFactory consoleWrapperFactory, String traceFile, ConsoleWrapperSettings consoleWrapperSettings)
   at Microsoft.VisualStudio.TestService.VstestAdapter.VstestUtilities.GetTestPlatformV2(IEnumerable`1 customVstestAdapterPaths, ConsoleWrapperSettings consoleWrapperSettings)
   at Microsoft.VisualStudio.TestService.VstestAdapter.DiscoverTests.PerformDiscovery(TestAutomationRunSlice sliceDetails, IAddTestCasesToTcmRunHandler addTestCasesToTcmRunHandler, ExecutionStateContext stateModelContext)
   at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.FetchPreviousPhaseData(ExecutionStateContext stateModelContext)
   at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

   at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.FetchPreviousPhaseData(ExecutionStateContext stateModelContext)
   at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.VisualStudio.TestService.ExecutionStateModel.DistributedTestExecutionAgent.ExecuteCurrentPhase(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestService.ExecutionStateModel.DistributedTestExecutionAgent.Execute(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestService.ExecutionStateModel.DistributedTestExecutionAgent.Start()
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.DistributedTestRunHost.InitializeAndStartExecutionHost(Boolean debugLogs)
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.DistributedTestRunHost.Execute(Boolean debugLogs)
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.Program.Main(String[] args)
---> (Inner Exception #0) Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\RSAcceptanceagent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.215.0\Modules\DTAExecutionHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.InitializeExtensions(IEnumerable`1 pathToAdditionalExtensions)
   at MS.VS.TestService.TestPlatform.v2.VsTestPlatformV2..ctor(String vstestConsolePath, List`1 adapterPaths, String diagFile, IConsoleWrapperFactory consoleWrapperFactory, String traceFile, ConsoleWrapperSettings consoleWrapperSettings)
   at Microsoft.VisualStudio.TestService.VstestAdapter.VstestUtilities.GetTestPlatformV2(IEnumerable`1 customVstestAdapterPaths, ConsoleWrapperSettings consoleWrapperSettings)
   at Microsoft.VisualStudio.TestService.VstestAdapter.DiscoverTests.PerformDiscovery(TestAutomationRunSlice sliceDetails, IAddTestCasesToTcmRunHandler addTestCasesToTcmRunHandler, ExecutionStateContext stateModelContext)
   at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.FetchPreviousPhaseData(ExecutionStateContext stateModelContext)
   at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: C:\RSAcceptanceagent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.215.0\Modules\DTAExecutionHost.exe process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.InitializeExtensions(IEnumerable`1 pathToAdditionalExtensions)
   at MS.VS.TestService.TestPlatform.v2.VsTestPlatformV2..ctor(String vstestConsolePath, List`1 adapterPaths, String diagFile, IConsoleWrapperFactory consoleWrapperFactory, String traceFile, ConsoleWrapperSettings consoleWrapperSettings)
   at Microsoft.VisualStudio.TestService.VstestAdapter.VstestUtilities.GetTestPlatformV2(IEnumerable`1 customVstestAdapterPaths, ConsoleWrapperSettings consoleWrapperSettings)
   at Microsoft.VisualStudio.TestService.VstestAdapter.DiscoverTests.PerformDiscovery(TestAutomationRunSlice sliceDetails, IAddTestCasesToTcmRunHandler addTestCasesToTcmRunHandler, ExecutionStateContext stateModelContext)
   at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.FetchPreviousPhaseData(ExecutionStateContext stateModelContext)
   at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.VisualStudio.TestService.ExecutionStateModel.DistributedTestExecutionAgent.ExecuteCurrentPhase(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestService.ExecutionStateModel.DistributedTestExecutionAgent.Execute(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestService.ExecutionStateModel.DistributedTestExecutionAgent.Start()
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.DistributedTestRunHost.InitializeAndStartExecutionHost(Boolean debugLogs)
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.DistributedTestRunHost.Execute(Boolean debugLogs)
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.Program.Main(String[] args)
##[error]Error: The process 'C:\RSAcceptanceagent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.215.0\Modules\DTAExecutionHost.exe' failed with exit code 3762504530
Finishing: Test Assemblies Parallel Test

**Comment by chilakamarthi** [comment]
Setting environment variable VSTEST_CONNECTION_TIMEOUT and time to 4 min (240 sec) solved my problem. Seems if not defined its value is 90 sec.

**Comment by kepikhin-mwb** [comment]
> Setting environment variable VSTEST_CONNECTION_TIMEOUT and time to 4 min (240 sec) solved my problem. Seems if not defined its value is 90 sec.

Where do you set this variable? Should it be set on Azure DevOps side or on work assets/VMs?

**Comment by chilakamarthi** [comment]
On agent machine environment variables
