### ISSUE TITLE
[BUG]: bicep.exe not found with AzureCLI@2 when using "az bicep <cmd>"

### ISSUE THREAD

**Issue by JeffreySchmitz-Motion10** [microsoft/azure-pipelines-tasks#17956]
### Task name

AzureCLI

### Task version

2.217.1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Task log

```shell
2023-03-14T07:32:25.2305422Z ##[section]Starting: Azure CLI ACR Push
2023-03-14T07:32:25.2423805Z ==============================================================================
2023-03-14T07:32:25.2424059Z Task         : Azure CLI
2023-03-14T07:32:25.2424178Z Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
2023-03-14T07:32:25.2424535Z Version      : 2.217.1
2023-03-14T07:32:25.2424667Z Author       : Microsoft Corporation
2023-03-14T07:32:25.2424813Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2023-03-14T07:32:25.2425003Z ==============================================================================
2023-03-14T07:32:25.7013583Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2023-03-14T07:32:26.6060915Z azure-cli                         2.46.0
2023-03-14T07:32:26.6061566Z 
2023-03-14T07:32:26.6061930Z core                              2.46.0
2023-03-14T07:32:26.6062286Z telemetry                          1.0.8
2023-03-14T07:32:26.6062517Z 
2023-03-14T07:32:26.6062795Z Extensions:
2023-03-14T07:32:26.6063130Z azure-devops                      0.26.0
2023-03-14T07:32:26.6063348Z 
2023-03-14T07:32:26.6063625Z Dependencies:
2023-03-14T07:32:26.6063951Z msal                              1.20.0
2023-03-14T07:32:26.6064302Z azure-mgmt-resource             21.1.0b1
2023-03-14T07:32:26.6064524Z 
2023-03-14T07:32:26.6065663Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2023-03-14T07:32:26.6066170Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2023-03-14T07:32:26.6066480Z 
2023-03-14T07:32:26.6066927Z Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
2023-03-14T07:32:26.6067265Z 
2023-03-14T07:32:26.6067615Z Legal docs and information: aka.ms/AzureCliLegal
2023-03-14T07:32:26.6067869Z 
2023-03-14T07:32:26.6068059Z 
2023-03-14T07:32:26.6068349Z Your CLI is up-to-date.
2023-03-14T07:32:26.6082824Z Setting AZURE_CONFIG_DIR env variable to: D:\a\_temp\.azclitask
2023-03-14T07:32:26.6089012Z Setting active cloud to: AzureCloud
2023-03-14T07:32:26.6284024Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
2023-03-14T07:32:27.1806996Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** "--password=***" --tenant *** --allow-no-subscriptions"
2023-03-14T07:32:28.2697740Z [
2023-03-14T07:32:28.2698294Z   {
2023-03-14T07:32:28.2698624Z     "cloudName": "AzureCloud",
2023-03-14T07:32:28.2699022Z     "homeTenantId": "***",
2023-03-14T07:32:28.2699459Z     "id": "***",
2023-03-14T07:32:28.2699846Z     "isDefault": true,
2023-03-14T07:32:28.2700171Z     "managedByTenants": [],
2023-03-14T07:32:28.2700498Z     "name": "***",
2023-03-14T07:32:28.2700798Z     "state": "Enabled",
2023-03-14T07:32:28.2701172Z     "tenantId": "***",
2023-03-14T07:32:28.2701515Z     "user": {
2023-03-14T07:32:28.2702248Z       "name": "***",
2023-03-14T07:32:28.2702580Z       "type": "servicePrincipal"
2023-03-14T07:32:28.2702875Z     }
2023-03-14T07:32:28.2703142Z   }
2023-03-14T07:32:28.2703391Z ]
2023-03-14T07:32:28.2971097Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription ***"
2023-03-14T07:32:28.8407351Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1678779145655.ps1'"
2023-03-14T07:32:29.9486048Z ERROR: The command failed with an unexpected error. Here is the traceback:
2023-03-14T07:32:29.9492529Z ERROR: [WinError 2] The system cannot find the file specified
2023-03-14T07:32:29.9492859Z Traceback (most recent call last):
2023-03-14T07:32:29.9493243Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
2023-03-14T07:32:29.9493759Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
2023-03-14T07:32:29.9494336Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
2023-03-14T07:32:29.9494917Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
2023-03-14T07:32:29.9495464Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
2023-03-14T07:32:29.9496033Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2023-03-14T07:32:29.9496624Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3708, in publish_bicep_file
2023-03-14T07:32:29.9497261Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 193, in bicep_version_greater_than_or_equal_to
2023-03-14T07:32:29.9498065Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 264, in _get_bicep_installed_version
2023-03-14T07:32:29.9498678Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 302, in _run_command
2023-03-14T07:32:29.9499098Z   File "subprocess.py", line 503, in run
2023-03-14T07:32:29.9499388Z   File "subprocess.py", line 971, in __init__
2023-03-14T07:32:29.9499679Z   File "subprocess.py", line 1440, in _execute_child
2023-03-14T07:32:29.9500027Z FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-03-14T07:32:29.9500409Z To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
2023-03-14T07:32:29.9500748Z To open a new issue, please run `az feedback`

<error repeats many times because command is called in a for loop>

2023-03-14T07:33:10.8904309Z ##[error]Script failed with exit code: 1
2023-03-14T07:33:10.9054423Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
2023-03-14T07:33:11.5753862Z ##[section]Finishing: Azure CLI ACR Push
```

### Relevant log output

```shell
2023-03-14T07:32:28.8407351Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1678779145655.ps1'"
2023-03-14T07:32:29.9486048Z ERROR: The command failed with an unexpected error. Here is the traceback:
2023-03-14T07:32:29.9492529Z ERROR: [WinError 2] The system cannot find the file specified
2023-03-14T07:32:29.9492859Z Traceback (most recent call last):
2023-03-14T07:32:29.9493243Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
2023-03-14T07:32:29.9493759Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
2023-03-14T07:32:29.9494336Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
2023-03-14T07:32:29.9494917Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
2023-03-14T07:32:29.9495464Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
2023-03-14T07:32:29.9496033Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2023-03-14T07:32:29.9496624Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3708, in publish_bicep_file
2023-03-14T07:32:29.9497261Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 193, in bicep_version_greater_than_or_equal_to
2023-03-14T07:32:29.9498065Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 264, in _get_bicep_installed_version
2023-03-14T07:32:29.9498678Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 302, in _run_command
2023-03-14T07:32:29.9499098Z   File "subprocess.py", line 503, in run
2023-03-14T07:32:29.9499388Z   File "subprocess.py", line 971, in __init__
2023-03-14T07:32:29.9499679Z   File "subprocess.py", line 1440, in _execute_child
2023-03-14T07:32:29.9500027Z FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-03-14T07:32:29.9500409Z To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
2023-03-14T07:32:29.9500748Z To open a new issue, please run `az feedback`
```

### Aditional info

```shell
The command that fails is "az bicep publish". I already looked at the source code of AzureCLI and the problem is that it expects bicep.exe in <AZURE_CONFIG_DIR>/bin/bicep.exe, but it's not there. The last run that worked is task version 2.216.0
```

**Comment by mike-wood-dywidag** [comment]
Also experiencing this with ubuntu-latest

**Comment by JeffreySchmitz-Motion10** [comment]
@mike-wood-dywidag solution that works for now is calling `bicep publish` directly instead of `az bicep publish` because bicep itself is in the environment path, but it would save a lot of headache with debugging if the az version also works as expected

**Comment by mike-wood-dywidag** [comment]
The above did work. However a later stage failed on something else which was previously working.
I suspect this is due to a recent update to the AZ CLI in hosted agents. (v2.46.0)

**Comment by JeffreySchmitz-Motion10** [comment]
@ochampet if you use the bicep publish directly, leave out the --file/-f completly. Just use the filename/path as the first parameter and it works.

**Comment by ochampet** [comment]
To verify the above I went back to a branch that run successfully prior to ubuntu az cli upgrade
Per suggestion I modify the code 
from 
                    az bicep publish \
                      --file ./bicep/privateAppService.bicep \
                       --target 'br:acrm6txyynfkimr4.azurecr.io/bicep/modules/private-app-service:v2.8'
to
                     bicep publish \
                       ./bicep/privateAppService.bicep \
                        'br:acrm6txyynfkimr4.azurecr.io/bicep/modules/private-app-service:v2.8'

The error is "The input file path cannot be specified multiple times."
It does not make sense the backward compatibility break.  There is no documentation on using bicep vs az bicep.

The command below is very simple

  - stage: Deploy
    jobs:
    - deployment: DeployBicepToRegistry
      displayName: Deploy bicep files to registry
      environment: Infra
      strategy:
        runOnce:
          deploy:            
            steps:
              - checkout: self
              - task: AzureCLI@2
                name: 'DeployBicepFile'
                displayName: 'Deploy Bicep file'
                inputs:
                  azureSubscription: $(azureServiceConnection)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    bicep publish \
                       ./bicep/privateAppService.bicep \
                       'br:acrm6txyynfkimr4.azurecr.io/bicep/modules/private-app-service:v2.8'

**Comment by ochampet** [comment]
> I'm curious whether the following would solve your problem.
> 
> ```
> bicep publish
> './bicep/privateAppService.bicep'
> --target 'br:acrm6txyynfkimr4.azurecr.io/bicep/modules/private-app-service:v2.8'
> ```
> 
> Without `--target` I can see why it does think you are specifying 2 `--file` params

That worked for me. Thanks
