### ISSUE TITLE
[BUG]: Gradle task does not apply sonarQubeGradlePluginVersion

### ISSUE THREAD

**Issue by kaito-ms** [microsoft/azure-pipelines-tasks#18127]
### Task name

Gradle

### Task version

2.x, AND 3.x

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Task log

```shell
A problem was found with the configuration of task ':sonarqube' (type 'SonarQubeTask').
  - In plugin 'org.sonarqube' type 'org.sonarqube.gradle.SonarQubeTask' property 'pluginVersion' is private and annotated with @Internal.
    
    Reason: Annotations on private getters are ignored.
    
    Possible solutions:
      1. Make the getter public.
      2. Annotate the public version of the getter.
    
    Please refer to https://docs.gradle.org/7.6.1/userguide/validation_problems.html#private_getter_must_not_be_annotated for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
##[debug]Exit code 1 received from tool '/home/azureuser/myagent/_work/10/s/gradlew'
##[debug]STDIO streams have closed for tool '/home/azureuser/myagent/_work/10/s/gradlew'
Error: The process '/home/azureuser/myagent/_work/10/s/gradlew' failed with exit code 1
##[debug]taskRunner fail
    at ExecState._setResult (/home/azureuser/myagent/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.219.0/node_modules/azure-pipelines-task-lib/toolrunner.js:942:25)
    at ExecState.CheckComplete (/home/azureuser/myagent/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.219.0/node_modules/azure-pipelines-task-lib/toolrunner.js:925:18)
    at ChildProcess.<anonymous> (/home/azureuser/myagent/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.219.0/node_modules/azure-pipelines-task-lib/toolrunner.js:838:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

### Relevant log output

```shell
n/a
```

### Aditional info

```yaml
# YAML Pipeline
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
```

This problem occurs when sonar.gradle already exists under the task directory.

```shell
$ cat myagent/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.219.0/node_modules/azure-pipelines-tasks-codeanalysis-common/sonar.gradle
allprojects {
    // Apply to the main build script a new repository and a dependency on the SonarQube plugin
    buildscript  {
        repositories {
            maven {
                url "https://plugins.gradle.org/m2/"
            }
        }
        dependencies {
            classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.6.1"
        }
    }

    // After the project has been evaluated (and the dependency above has been added, apply the SonarQube plugin
    afterEvaluate { project ->
        if (project.getParent() == null && !project.plugins.hasPlugin('org.sonarqube')) {
            //Add sonar plugin only to root projects, and only if it is not already applied
            project.apply plugin: 'org.sonarqube'
        }
    }
```

The expected behavior is that the contents of sonar.gradle will be updated if sonarQubeGradlePluginVersion is specified.

// sonar.gradle
classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.3"

A temporary workaround is to delete the Gradle task directory.

```shell
$ rm -rf myagent/_work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/
```
```

**Comment by vmapetr** [comment]
Hi, @kaito-ms thanks for reporting!
We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by abhivarma007** [comment]
Encountering similar issue with Maven project. I have the similar setup with SonarQube is on on-premises and executing the workflow on self-hosted runners. Any workaround for it?

**Comment by leontodd** [comment]
Same issue here. The sonar.gradle file is not updated when changing the sonarQubeGradlePluginVersion.
