### ISSUE TITLE
[BUG]: Can not extract dacpac with Azure SQL Database deployment v1 task

### ISSUE THREAD

**Issue by gloriaz17** [microsoft/azure-pipelines-tasks#18125]
### Task name

SqlAzureDacpacDeployment

### Task version

1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 8

### Task log

```shell
2023-03-28T20:15:32.6576848Z ##[debug]Entering Add-AzureSqlDatabaseServerFirewallRule.
2023-03-28T20:15:32.6755618Z ##[debug] endpoint: '@{Url=https://management.azure.com/; Data=; Auth=}'
2023-03-28T20:15:32.6787968Z ##[debug] startIPAddress: '52.235.28.181'
2023-03-28T20:15:32.6815526Z ##[debug] endIPAddress: '52.235.28.181'
2023-03-28T20:15:32.7089526Z ##[debug] serverName: 'eddv1sqlcdp01'
2023-03-28T20:15:32.7115787Z ##[debug] firewallRuleName: '95c4982b-c4cf-47ec-9017-b2f72225813d'
2023-03-28T20:15:32.7167795Z ##[debug]Creating firewall rule 95c4982b-c4cf-47ec-9017-b2f72225813d
2023-03-28T20:15:32.7238740Z ##[debug]Connection type used is ServicePrincipal
2023-03-28T20:15:32.7292257Z ##[debug]Connection type used is ServicePrincipal
2023-03-28T20:15:32.7333128Z ##[debug]Connection type used is ServicePrincipal
2023-03-28T20:15:32.7424603Z ##[debug]Get-AzureRMAccessToken - started - endpoint=@{Url=https://management.azure.com/; Data=; Auth=} - scheme=ServicePrincipal
2023-03-28T20:15:32.7487671Z ##[debug]USE_MSAL (empty)
2023-03-28T20:15:32.7512386Z ##[debug]MSAL - useMSAL = False
2023-03-28T20:15:32.7834578Z ##[warning]The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.
2023-03-28T20:15:32.7842378Z ##[debug]Processed: ##vso[task.logissue type=warning]The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.
2023-03-28T20:15:32.7912406Z ##[debug]MSAL - Get-EnvironmentAuthUrl - endpoint=@{Url=https://management.azure.com/; Data=; Auth=}
2023-03-28T20:15:32.7931985Z ##[debug]MSAL - Get-EnvironmentAuthUrl - useMSAL=False
2023-03-28T20:15:32.7951484Z ##[debug]MSAL - Get-EnvironmentAuthUrl - envAuthUrl=https://login.windows.net/
2023-03-28T20:15:32.8046770Z ##[debug]Fetching Access Token
2023-03-28T20:15:32.9113799Z ##[debug]POST https://login.windows.net/38b7fc89-dbe8-4ed1-a78b-39dfb6a217a8/oauth2/token with -1-byte payload
2023-03-28T20:15:33.2970617Z ##[debug]received 1468-byte response of content type application/json; charset=utf-8
2023-03-28T20:15:33.3045286Z ##[debug][Azure Rest Call] Get Resource Groups
2023-03-28T20:15:33.3105317Z ##[debug]Fetching Resources from https://management.azure.com//subscriptions/3e27d033-4741-4556-ab83-665f4758094b/resources?api-version=2014-04-01
2023-03-28T20:15:33.3138319Z ##[debug]GET https://management.azure.com//subscriptions/3e27d033-4741-4556-ab83-665f4758094b/resources?api-version=2014-04-01 with 0-byte payload
2023-03-28T20:15:35.7154864Z ##[debug]received 312510-byte response of content type application/json; charset=utf-8
2023-03-28T20:15:35.8519495Z ##[debug]PUT https://management.azure.com///subscriptions/3e27d033-4741-4556-ab83-665f4758094b/resourceGroups/EDDV1-RG-CDP/providers/Microsoft.Sql/servers/EDDV1SQLCDP01/firewallRules/95c4982b-c4cf-47ec-9017-b2f72225813d/?api-version=2014-04-01 with -1-byte payload
2023-03-28T20:15:36.2141884Z ##[debug]Exception message - System.Net.WebException: The remote server returned an error: (400) Bad Request.
2023-03-28T20:15:36.2155170Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2023-03-28T20:15:36.2168058Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2023-03-28T20:15:36.3626860Z ##[debug]Exception message extracted from response {"code":"40645","message":"Servername \"EDDV1SQLCDP01\" cannot be empty or null. It can only be made up of lowercase letters \u0027a\u0027-\u0027z\u0027, the numbers 0-9 and the hyphen. The hyphen may not lead or trail in the name.","target":null,"details":[{"code":"40645","message":"Servername \"EDDV1SQLCDP01\" cannot be empty or null. It can only be made up of lowercase letters \u0027a\u0027-\u0027z\u0027, the numbers 0-9 and the hyphen. The hyphen may not lead or trail in the name.","target":null,"severity":"16"}],"innererror":[]}
2023-03-28T20:15:36.3736652Z ##[debug]Processed: ##vso[task.logissue code=40645;type=error]
2023-03-28T20:15:36.3888916Z ##[debug]No Firewall Rule was added
2023-03-28T20:15:36.3995924Z ##[debug]Caught exception from task script.
2023-03-28T20:15:36.4031175Z ##[debug]Error record:
2023-03-28T20:15:36.4575603Z ##[debug]Servername "EDDV1SQLCDP01" cannot be empty or null. It can only be made up of lowercase letters 'a'-'z', the numbers 0-9 and the hyphen. The hyphen may not lead or trail in the name.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-03-28T20:15:36.4592225Z ##[debug]At C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.218.0\DeploySqlAzure.ps1:220 char:5
2023-03-28T20:15:36.4610032Z ##[debug]+     throw $errorMessage
2023-03-28T20:15:36.4625242Z ##[debug]+     ~~~~~~~~~~~~~~~~~~~
2023-03-28T20:15:36.4639587Z ##[debug]    + CategoryInfo          : OperationStopped: (Servername "EDD...roubleshooting-:String) [], RuntimeException
2023-03-28T20:15:36.4653815Z ##[debug]    + FullyQualifiedErrorId : Servername "EDDV1SQLCDP01" cannot be empty or null. It can only be made up of lowercase     letters 'a'-'z', the numbers 0-9 and the hyphen. The hyphen may not lead or trail in the name.Check out how to tro    ubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-03-28T20:15:36.4667405Z ##[debug] 
2023-03-28T20:15:36.4691189Z ##[debug]Script stack trace:
2023-03-28T20:15:36.4733175Z ##[debug]at <ScriptBlock>, C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.218.0\DeploySqlAzure.ps1: line 220
2023-03-28T20:15:36.4748053Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-03-28T20:15:36.4760946Z ##[debug]at <ScriptBlock>, <No file>: line 22
2023-03-28T20:15:36.4773196Z ##[debug]at <ScriptBlock>, <No file>: line 18
2023-03-28T20:15:36.4785755Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-03-28T20:15:36.4806259Z ##[debug]Exception:
2023-03-28T20:15:36.4851035Z ##[debug]System.Management.Automation.RuntimeException: Servername "EDDV1SQLCDP01" cannot be empty or null. It can only be made up of lowercase letters 'a'-'z', the numbers 0-9 and the hyphen. The hyphen may not lead or trail in the name.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-03-28T20:15:36.4869307Z ##[error]Servername "EDDV1SQLCDP01" cannot be empty or null. It can only be made up of lowercase letters 'a'-'z', the numbers 0-9 and the hyphen. The hyphen may not lead or trail in the name.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-03-28T20:15:36.4870422Z ##[debug]Processed: ##vso[task.logissue type=error]Servername "EDDV1SQLCDP01" cannot be empty or null. It can only be made up of lowercase letters 'a'-'z', the numbers 0-9 and the hyphen. The hyphen may not lead or trail in the name.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-03-28T20:15:36.4887528Z ##[debug]Processed: ##vso[task.complete result=Failed]
2023-03-28T20:15:36.5350478Z ##[section]Finishing: Azure SQL DacpacTask
```

### Relevant log output

```shell
2023-04-17T16:29:37.8238562Z Temporary inline SQL file: C:\Users\ContainerAdministrator\AppData\Local\Temp\tmp561E.tmp
2023-04-17T16:29:37.8390451Z Invoke-Sqlcmd -AccessToken "**********" -ServerInstance "eddv1sqlcdp01.database.windows.net" -Database "eddv1sqldbcdpedw01"  -Inputfile "C:\Users\ContainerAdministrator\AppData\Local\Temp\tmp561E.tmp" 
2023-04-17T16:29:59.1842197Z ##[debug]Removing File C:\Users\ContainerAdministrator\AppData\Local\Temp\tmp561E.tmp
2023-04-17T16:29:59.1947275Z ##[debug]Failed to reach SQL server eddv1sqlcdp01.database.windows.net. A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
2023-04-17T16:29:59.2075874Z ##[debug]Error Message : System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
2023-04-17T16:29:59.2110589Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2023-04-17T16:29:59.2131290Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2023-04-17T16:29:59.2155832Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-04-17T16:29:59.2176225Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-04-17T16:29:59.2204992Z ##[debug]Message To Parse: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
2023-04-17T16:29:59.2263866Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2023-04-17T16:29:59.2281718Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2023-04-17T16:29:59.2306195Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-04-17T16:29:59.2323954Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-04-17T16:29:59.2440874Z ##[debug]
2023-04-17T16:29:59.2553748Z ##[debug]Sql configured firewall wait time is invalid. So, setting it to defaul : 10
2023-04-17T16:29:59.2581924Z ##[debug]Sql firewall configured wait time : 10
2023-04-17T16:30:09.2650360Z ##[debug]Creating output files directory: C:\azp\agent\w\r4\a\GeneratedOutputFiles
2023-04-17T16:30:09.2715765Z ##[debug]Executing 'Extract' action.
2023-04-17T16:30:09.3862050Z ##[debug]Sql Versions installed on machine VS2017_CA4 as read from registry: 150 140 130 120 110
2023-04-17T16:30:09.4242568Z ##[debug]Sql Version Specific Root Dir for version 150 as read from registry: C:\Program Files (x86)\Microsoft SQL Server\150\
2023-04-17T16:30:10.0909486Z ##[debug]Sql Version Specific Root Dir for version 140 as read from registry: C:\Program Files (x86)\Microsoft SQL Server\140\
2023-04-17T16:30:10.0910194Z ##[debug]Sql Version Specific Root Dir for version 130 as read from registry: C:\Program Files\Microsoft SQL Server\130\
2023-04-17T16:30:10.0910787Z ##[debug]Sql Version Specific Root Dir for version 130 as read from registry: C:\Program Files (x86)\Microsoft SQL Server\130\
2023-04-17T16:30:10.0911391Z ##[debug]Sql Version Specific Root Dir for version 120 as read from registry: C:\Program Files (x86)\Microsoft SQL Server\120\
2023-04-17T16:30:10.0911906Z ##[debug]Sql Version Specific Root Dir for version 110 as read from registry: C:\Program Files (x86)\Microsoft SQL Server\110\
2023-04-17T16:30:10.0912385Z ##[debug]Dac Framework (installed with SQL) not found on machine VS2017_CA4
2023-04-17T16:30:10.0912802Z ##[debug]Dac Framework (installed with DAC Framework) not found on machine VS2017_CA4
2023-04-17T16:30:10.0913235Z ##[debug]Getting latest Visual Studio 15 setup instance.
2023-04-17T16:30:10.0913604Z ##[debug]Entering Invoke-VstsTool.
2023-04-17T16:30:10.0914070Z ##[debug] FileName: 'C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.219.0\vswhere.exe'
2023-04-17T16:30:10.0914557Z ##[debug] Arguments: '-version [15.0,18.0) -latest -format json'
2023-04-17T16:30:10.0914971Z ##[debug] RequireExitCodeZero: 'True'
2023-04-17T16:30:10.0916948Z ##[command]"C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.219.0\vswhere.exe" -version [15.0,18.0) -latest -format json
2023-04-17T16:30:10.0917574Z ##[debug][
2023-04-17T16:30:10.0917872Z ##[debug]  {
2023-04-17T16:30:10.0918194Z ##[debug]    "instanceId": "d2899839",
2023-04-17T16:30:10.0918555Z ##[debug]    "installDate": "2022-02-07T20:04:55Z",
2023-04-17T16:30:10.0918986Z ##[debug]    "installationName": "VisualStudio/15.9.43+28307.1778",
2023-04-17T16:30:10.0919400Z ##[debug]    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise",
2023-04-17T16:30:10.0923026Z ##[debug]    "installationVersion": "15.9.28307.1778",
2023-04-17T16:30:10.0923431Z ##[debug]    "displayName": "Visual Studio Enterprise 2017",
2023-04-17T16:30:10.0923938Z ##[debug]    "description": "Microsoft DevOps solution for productivity and coordination across teams of any size",
2023-04-17T16:30:10.0924404Z ##[debug]    "updateDate": "2022-02-07T20:04:55.7034124Z",
2023-04-17T16:30:10.0924855Z ##[debug]    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
2023-04-17T16:30:10.0925489Z ##[debug]    "channelId": "VisualStudio.15.Release",
2023-04-17T16:30:10.0925851Z ##[debug]    "channelUri": "https://aka.ms/vs/15/release/channel",
2023-04-17T16:30:10.0926232Z ##[debug]    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660692#15.9.43",
2023-04-17T16:30:10.0926671Z ##[debug]    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660708"
2023-04-17T16:30:10.0927023Z ##[debug]  }
2023-04-17T16:30:10.0927602Z ##[debug]]
2023-04-17T16:30:10.0927903Z ##[debug]Exit code: 0
2023-04-17T16:30:10.0928225Z ##[debug]Leaving Invoke-VstsTool.
2023-04-17T16:30:10.0929121Z ##[debug]Dac Framework installed with Visual Studio found at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\SqlPackage.exe on machine VS2017_CA4
2023-04-17T16:30:10.0929757Z "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\SqlPackage.exe" /Action:Extract /TargetFile:"C:\azp\agent\w\r4\a\GeneratedOutputFiles\eddv1sqldbcdpedw01.dacpac" /SourceServerName:"eddv1sqlcdp01.database.windows.net" /SourceDatabaseName:"eddv1sqldbcdpedw01" /AccessToken:"********" 
2023-04-17T16:30:10.3545611Z Connecting to database 'eddv1sqldbcdpedw01' on server 'eddv1sqlcdp01.database.windows.net'.
2023-04-17T16:30:10.9519660Z Extracting schema
2023-04-17T16:30:10.9655927Z Extracting schema from database
2023-04-17T16:30:11.1955415Z ##[debug]Error record:
2023-04-17T16:30:11.2691997Z ##[debug]Execute-Command : *** An unexpected failure occurred: Exception has been thrown by the target of an invocation..
2023-04-17T16:30:11.2717456Z ##[debug]At C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.219.0\SqlAzureActions.ps1:477 char:5
2023-04-17T16:30:11.2737788Z ##[debug]+     Execute-Command -FileName $sqlPackagePath -Arguments $sqlpackageA ...
2023-04-17T16:30:11.2792258Z ##[debug]+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-04-17T16:30:11.2822006Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2023-04-17T16:30:11.2843779Z ##[debug]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Execute-Command
2023-04-17T16:30:11.2867307Z ##[debug] 
2023-04-17T16:30:11.2899294Z ##[debug]Script stack trace:
2023-04-17T16:30:11.2973077Z ##[debug]at Execute-Command, C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.219.0\Utility.ps1: line 292
2023-04-17T16:30:11.2985079Z ##[debug]at Execute-SqlPackage, C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.219.0\SqlAzureActions.ps1: line 477
2023-04-17T16:30:11.3009197Z ##[debug]at Extract-Dacpac, C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.219.0\SqlAzureActions.ps1: line 19
2023-04-17T16:30:11.3117174Z ##[debug]at <ScriptBlock>, C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.219.0\DeploySqlAzure.ps1: line 154
2023-04-17T16:30:11.3139137Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-04-17T16:30:11.3156652Z ##[debug]at <ScriptBlock>, <No file>: line 22
2023-04-17T16:30:11.3229853Z ##[debug]at <ScriptBlock>, <No file>: line 18
2023-04-17T16:30:11.3249327Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-04-17T16:30:11.3326250Z ##[debug]Exception:
2023-04-17T16:30:11.3405775Z ##[debug]Microsoft.PowerShell.Commands.WriteErrorException: *** An unexpected failure occurred: Exception has been thrown by the target of an invocation..
2023-04-17T16:30:11.3867636Z ##[error]*** An unexpected failure occurred: Exception has been thrown by the target of an invocation..
2023-04-17T16:30:11.3878836Z ##[debug]Processed: ##vso[task.logissue type=error]*** An unexpected failure occurred: Exception has been thrown by the target of an invocation..
2023-04-17T16:30:11.4043167Z ##[debug]No Firewall Rule was added
2023-04-17T16:30:11.4319681Z ##[debug]Caught exception from task script.
2023-04-17T16:30:11.4353003Z ##[debug]Error record:
2023-04-17T16:30:11.4561596Z ##[debug]The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-04-17T16:30:11.4585493Z ##[debug]At C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.219.0\DeploySqlAzure.ps1:220 char:5
2023-04-17T16:30:11.4612977Z ##[debug]+     throw $errorMessage
2023-04-17T16:30:11.4638601Z ##[debug]+     ~~~~~~~~~~~~~~~~~~~
2023-04-17T16:30:11.4655442Z ##[debug]    + CategoryInfo          : OperationStopped: (The Azure SQL D...roubleshooting-:String) [], RuntimeException
2023-04-17T16:30:11.4674342Z ##[debug]    + FullyQualifiedErrorId : The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to tro    ubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-04-17T16:30:11.4693451Z ##[debug] 
2023-04-17T16:30:11.4718176Z ##[debug]Script stack trace:
2023-04-17T16:30:11.4743083Z ##[debug]at <ScriptBlock>, C:\azp\agent\w\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.219.0\DeploySqlAzure.ps1: line 220
2023-04-17T16:30:11.4761261Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-04-17T16:30:11.4782706Z ##[debug]at <ScriptBlock>, <No file>: line 22
2023-04-17T16:30:11.4797868Z ##[debug]at <ScriptBlock>, <No file>: line 18
2023-04-17T16:30:11.4814309Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-04-17T16:30:11.4837584Z ##[debug]Exception:
2023-04-17T16:30:11.4891194Z ##[debug]System.Management.Automation.RuntimeException: The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-04-17T16:30:11.4935289Z ##[error]The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-04-17T16:30:11.4936462Z ##[debug]Processed: ##vso[task.logissue type=error]The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2023-04-17T16:30:11.4967887Z ##[debug]Processed: ##vso[task.complete result=Failed]
2023-04-17T16:30:11.5527346Z ##[section]Finishing: Azure SQL DacpacTask
```

### Aditional info

```shell
I believe this task is failing because of the "Specify Firewall Rules Using" field. It is a mandatory field with 2 given options, but neither "AutoDetect" nor "IPAddressRange" work. Please see "task log" for error log output when choosing "IPAddressRange", and "relevant log output" for error log output when choosing "AutoDetect"
```

**Comment by Tsjunne** [comment]
This is still a bug. It seems to occur when the SQL Server resource is named in upper case and trying to use the IpDetectionMode 'AutoDetect'
