### ISSUE TITLE
[BUG]: Azure App Service deploy failing  with latest version 

### ISSUE THREAD

**Issue by zainuvk** [microsoft/azure-pipelines-tasks#18178]
### Task name

Azure App Service deploy

### Task version

 4.221.101

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Task log

```shell
The Azure App Service deployment is failing and looks like this issue poppedup with the latest updated version 

2023-04-25T09:22:09.1350635Z ##[section]Starting: Deploy Azure App Service
2023-04-25T09:22:09.1522461Z ==============================================================================
2023-04-25T09:22:09.1522821Z Task         : Azure App Service deploy
2023-04-25T09:22:09.1522895Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2023-04-25T09:22:09.1523039Z Version      : 4.221.101
2023-04-25T09:22:09.1523119Z Author       : Microsoft Corporation
2023-04-25T09:22:09.1523189Z Help         : https://aka.ms/azureappservicetroubleshooting
2023-04-25T09:22:09.1523525Z ==============================================================================
2023-04-25T09:22:10.0343692Z Got service connection details for Azure App Service:'genevaappcvescan'
2023-04-25T09:26:34.0972135Z Trying to update App Service Application settings. Data: null
2023-04-25T09:26:34.3248592Z App Service Application settings are already present.
2023-04-25T09:26:34.7223073Z Package deployment using ZIP Deploy initiated.
2023-04-25T09:26:55.3773281Z Updating submodules.
2023-04-25T09:26:55.3773624Z Preparing deployment for commit id 'edcbb0a3f5'.
2023-04-25T09:26:55.3773920Z Generating deployment script.
2023-04-25T09:26:55.6847002Z Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"'.
2023-04-25T09:26:55.6847770Z C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153
2023-04-25T09:26:55.6848108Z                 ...StatusLogger.DEFAULT_STATUS,
2023-04-25T09:26:55.6848352Z                 ^^^
2023-04-25T09:26:55.6848483Z 
2023-04-25T09:26:55.6848695Z SyntaxError: Unexpected token ...
2023-04-25T09:26:55.6849041Z     at createScript (vm.js:56:10)
2023-04-25T09:26:55.6849308Z     at Object.runInThisContext (vm.js:97:10)
2023-04-25T09:26:55.6849595Z     at Module._compile (module.js:542:28)
2023-04-25T09:26:55.6850036Z     at Object.Module._extensions..js (module.js:579:10)
2023-04-25T09:26:55.6850323Z     at Module.load (module.js:487:32)
2023-04-25T09:26:55.6850592Z     at tryModuleLoad (module.js:446:12)
2023-04-25T09:26:55.6850850Z     at Function.Module._load (module.js:438:3)
2023-04-25T09:26:55.6851138Z     at Module.require (module.js:497:17)
2023-04-25T09:26:55.6851375Z     at module.js:669:12
2023-04-25T09:26:55.6851618Z     at Array.forEach (native)
2023-04-25T09:26:55.6852649Z C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153\r\n                ...StatusLogger.DEFAULT_STATUS,\r\n                ^^^\r\n\r\nSyntaxError: Unexpected token ...\r\n    at createScript (vm.js:56:10)\r\n    at Object.runInThisContext (vm.js:97:10)\r\n    at Module._compile (module.js:542:28)\r\n    at Object.Module._extensions..js (module.js:579:10)\r\n    at Module.load (module.js:487:32)\r\n    at tryModuleLoad (module.js:446:12)\r\n    at Function.Module._load (module.js:438:3)\r\n    at Module.require (module.js:497:17)\r\n    at module.js:669:12\r\n    at Array.forEach (native)\r\nC:\Program Files (x86)\SiteExtensions\Kudu\100.50331.6204\bin\Scripts\starter.cmd "C:\Program Files (x86)\SiteExtensions\Kudu\100.50331.6204\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"
2023-04-25T09:26:55.6854010Z Deployment Failed.
```

### Relevant log output

```shell
2023-04-25T09:22:09.1350635Z ##[section]Starting: Deploy Azure App Service
2023-04-25T09:22:09.1522461Z ==============================================================================
2023-04-25T09:22:09.1522821Z Task         : Azure App Service deploy
2023-04-25T09:22:09.1522895Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2023-04-25T09:22:09.1523039Z Version      : 4.221.101
2023-04-25T09:22:09.1523119Z Author       : Microsoft Corporation
2023-04-25T09:22:09.1523189Z Help         : https://aka.ms/azureappservicetroubleshooting
2023-04-25T09:22:09.1523525Z ==============================================================================
2023-04-25T09:22:10.0343692Z Got service connection details for Azure App Service:'genevaappcvescan'
2023-04-25T09:26:34.0972135Z Trying to update App Service Application settings. Data: null
2023-04-25T09:26:34.3248592Z App Service Application settings are already present.
2023-04-25T09:26:34.7223073Z Package deployment using ZIP Deploy initiated.
2023-04-25T09:26:55.3773281Z Updating submodules.
2023-04-25T09:26:55.3773624Z Preparing deployment for commit id 'edcbb0a3f5'.
2023-04-25T09:26:55.3773920Z Generating deployment script.
2023-04-25T09:26:55.6847002Z Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"'.
2023-04-25T09:26:55.6847770Z C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153
2023-04-25T09:26:55.6848108Z                 ...StatusLogger.DEFAULT_STATUS,
2023-04-25T09:26:55.6848352Z                 ^^^
2023-04-25T09:26:55.6848483Z 
2023-04-25T09:26:55.6848695Z SyntaxError: Unexpected token ...
2023-04-25T09:26:55.6849041Z     at createScript (vm.js:56:10)
2023-04-25T09:26:55.6849308Z     at Object.runInThisContext (vm.js:97:10)
2023-04-25T09:26:55.6849595Z     at Module._compile (module.js:542:28)
2023-04-25T09:26:55.6850036Z     at Object.Module._extensions..js (module.js:579:10)
2023-04-25T09:26:55.6850323Z     at Module.load (module.js:487:32)
2023-04-25T09:26:55.6850592Z     at tryModuleLoad (module.js:446:12)
2023-04-25T09:26:55.6850850Z     at Function.Module._load (module.js:438:3)
2023-04-25T09:26:55.6851138Z     at Module.require (module.js:497:17)
2023-04-25T09:26:55.6851375Z     at module.js:669:12
2023-04-25T09:26:55.6851618Z     at Array.forEach (native)
2023-04-25T09:26:55.6852649Z C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153\r\n                ...StatusLogger.DEFAULT_STATUS,\r\n                ^^^\r\n\r\nSyntaxError: Unexpected token ...\r\n    at createScript (vm.js:56:10)\r\n    at Object.runInThisContext (vm.js:97:10)\r\n    at Module._compile (module.js:542:28)\r\n    at Object.Module._extensions..js (module.js:579:10)\r\n    at Module.load (module.js:487:32)\r\n    at tryModuleLoad (module.js:446:12)\r\n    at Function.Module._load (module.js:438:3)\r\n    at Module.require (module.js:497:17)\r\n    at module.js:669:12\r\n    at Array.forEach (native)\r\nC:\Program Files (x86)\SiteExtensions\Kudu\100.50331.6204\bin\Scripts\starter.cmd "C:\Program Files (x86)\SiteExtensions\Kudu\100.50331.6204\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"
2023-04-25T09:26:55.6854010Z Deployment Failed.
2023-04-25T09:26:55.6905484Z ##[error]Failed to deploy web package to App Service.
2023-04-25T09:26:55.6918141Z ##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
2023-04-25T09:26:58.8315177Z Successfully added release annotation to the Application Insight : CVESolutionAppInsight
2023-04-25T09:26:59.2580259Z Successfully updated deployment History at https://genevaappcvescan.scm.azurewebsites.net/api/deployments/99633001682414818825
2023-04-25T09:27:11.6900371Z App Service Application URL: http://genevaappcvescan.azurewebsites.net
2023-04-25T09:27:11.7082726Z ##[section]Finishing: Deploy Azure App Service
```

**Comment by sewalsh** [comment]
I am also getting the same error today.

```
2023-04-25T17:44:57.5886182Z ##[section]Starting: Deploy Azure App Service
2023-04-25T17:44:57.6009841Z ==============================================================================
2023-04-25T17:44:57.6010025Z Task         : Azure App Service deploy
2023-04-25T17:44:57.6010097Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2023-04-25T17:44:57.6010234Z Version      : 4.221.101
2023-04-25T17:44:57.6010320Z Author       : Microsoft Corporation
2023-04-25T17:44:57.6010387Z Help         : https://aka.ms/azureappservicetroubleshooting
2023-04-25T17:44:57.6010470Z ==============================================================================
2023-04-25T17:44:58.2707376Z Got service connection details for Azure App Service:'app-tcm-prod-api'
2023-04-25T17:44:59.3374726Z Trying to update App Service Application settings. Data: null
2023-04-25T17:44:59.5414129Z App Service Application settings are already present.
2023-04-25T17:44:59.6152360Z Package deployment using ZIP Deploy initiated.
2023-04-25T17:45:10.6776885Z Updating submodules.
2023-04-25T17:45:10.6777837Z Preparing deployment for commit id '8b08a0b2b8'.
2023-04-25T17:45:10.6778215Z Generating deployment script.
2023-04-25T17:45:10.7653918Z Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"'.
2023-04-25T17:45:10.7654719Z C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153
2023-04-25T17:45:10.7655061Z                 ...StatusLogger.DEFAULT_STATUS,
2023-04-25T17:45:10.7655272Z                 ^^^
2023-04-25T17:45:10.7655485Z 
2023-04-25T17:45:10.7656014Z SyntaxError: Unexpected token ...
2023-04-25T17:45:10.7656330Z     at createScript (vm.js:56:10)
2023-04-25T17:45:10.7656541Z     at Object.runInThisContext (vm.js:97:10)
2023-04-25T17:45:10.7656779Z     at Module._compile (module.js:542:28)
2023-04-25T17:45:10.7657010Z     at Object.Module._extensions..js (module.js:579:10)
2023-04-25T17:45:10.7657244Z     at Module.load (module.js:487:32)
2023-04-25T17:45:10.7657446Z     at tryModuleLoad (module.js:446:12)
2023-04-25T17:45:10.7657641Z     at Function.Module._load (module.js:438:3)
2023-04-25T17:45:10.7657871Z     at Module.require (module.js:497:17)
2023-04-25T17:45:10.7658041Z     at module.js:669:12
2023-04-25T17:45:10.7658202Z     at Array.forEach (native)
2023-04-25T17:45:10.7660068Z C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153\r\n                ...StatusLogger.DEFAULT_STATUS,\r\n                ^^^\r\n\r\nSyntaxError: Unexpected token ...\r\n    at createScript (vm.js:56:10)\r\n    at Object.runInThisContext (vm.js:97:10)\r\n    at Module._compile (module.js:542:28)\r\n    at Object.Module._extensions..js (module.js:579:10)\r\n    at Module.load (module.js:487:32)\r\n    at tryModuleLoad (module.js:446:12)\r\n    at Function.Module._load (module.js:438:3)\r\n    at Module.require (module.js:497:17)\r\n    at module.js:669:12\r\n    at Array.forEach (native)\r\nC:\Program Files (x86)\SiteExtensions\Kudu\100.50331.6204\bin\Scripts\starter.cmd "C:\Program Files (x86)\SiteExtensions\Kudu\100.50331.6204\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"
2023-04-25T17:45:10.7661211Z Deployment Failed.
2023-04-25T17:45:10.7693319Z ##[error]Failed to deploy web package to App Service.
2023-04-25T17:45:10.7701375Z ##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
2023-04-25T17:45:11.5741368Z Successfully added release annotation to the Application Insight : ai-tcm-prod-api
2023-04-25T17:45:11.7272444Z Successfully updated deployment History at https://app-tcm-prod-api.scm.azurewebsites.net/api/deployments/68221682444711568
2023-04-25T17:45:12.9742423Z App Service Application URL: https://app-tcm-prod-api.azurewebsites.net
2023-04-25T17:45:12.9873658Z ##[section]Finishing: Deploy Azure App Service
```

**Comment by merlynomsft** [comment]
Thank you for the report!  

To get you unblocked: if you're using YAML pipelines, you can pin the older version of the task using @4.220.0.  It would be great if you could let us know if this fixed the issue for you of if you're still have the problem.

While the above might get you unblocked, we'd really appreciate your help for us to get to the root cause by collecting diagnostic logs.  
1. When manually running the build, check "Enable system diagnostics" when running the build.  
2. When the run completes, use "..." and Download logs to get a zip file.  
3. You can upload a file privately to us at: https://developercommunity.visualstudio.com/AzureDevOps/report .  Important: To ensure your attachment is private, after posting the issue, create private comment and attach the file.  
4. Please post a link here to the issue in Developer Community.

Thank you!

**Comment by sewalsh** [comment]
Resolution:

My `WEBSITE_NODE_DEFAULT_VERSION` was set to `6.9.1`, this appears to be the version configured out of the box.

Setting it to the latest of `18.16.0` will resolve the issue.

![image](https://user-images.githubusercontent.com/7760319/234366735-3dca6e0f-5b8a-4193-8044-2e8d41bf42c5.png)

**Comment by zainuvk** [comment]
Thanks @sewalsh .This helps.

**Comment by yellesh12** [comment]
Hello @sewalsh I tried the above yaml and setting node the node version issue seems to be same is there any other suggestions here we are using linux agent with version 20.0.4

**Comment by brunochaina** [comment]
I also had the same issue and this was fixed by the resolution pointed out by @sewalsh

**Comment by RealcodeDev** [comment]
Thanks @sewalsh. Changing the version helped.

**Comment by nikolayyordanov** [comment]
Thanks for the tip. Actually, saw that on the app services where the deployment is done without issues the specific configuration for NODE was missing. Deleted it on the one which was giving errors and now the task is run successfully.

**Comment by tiagodresch** [comment]
For me the issue was solved by reviewing all parameters on WebApp configuration section.  Someone setup the Application Insights in my resource group, and it generated a lot of parameters there that were making my deploy fail.

**Comment by justinflint** [comment]
Thanks @sewalsh you solved an issue that was quite confusing.
