### ISSUE TITLE
[BUG]: AzureStaticWebApp task changes ownership of working directory to root

### ISSUE THREAD

**Issue by torbjvi** [microsoft/azure-pipelines-tasks#18242]
### Task name

AzureStaticWebApp

### Task version

0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest, ubuntu-22.04

### Task log

```shell
2023-05-04T11:01:56.5218541Z ##[section]Starting: AzureStaticWebApp
2023-05-04T11:01:56.5221968Z ==============================================================================
2023-05-04T11:01:56.5222071Z Task         : Deploy Azure Static Web App
2023-05-04T11:01:56.5222145Z Description  : [PREVIEW] Build and deploy an Azure Static Web App
2023-05-04T11:01:56.5222226Z Version      : 0.220.0
2023-05-04T11:01:56.5222280Z Author       : Microsoft Corporation
2023-05-04T11:01:56.5222343Z Help         : https://aka.ms/swadocs
2023-05-04T11:01:56.5222411Z ==============================================================================
2023-05-04T11:01:56.6936292Z [command]/usr/bin/bash /home/vsts/work/_tasks/AzureStaticWebApp_18aad896-e191-4720-88d6-8ced4806941a/0.220.0/launch-docker.sh
2023-05-04T11:01:57.0142723Z stable: Pulling from appsvc/staticappsclient
2023-05-04T11:01:57.0155092Z b0248cf3e63c: Already exists
2023-05-04T11:01:57.0186357Z 127e97b4daf7: Already exists
2023-05-04T11:01:57.0200459Z 0336c50c9f69: Already exists
2023-05-04T11:01:57.0222514Z e64712e6a804: Pulling fs layer
2023-05-04T11:01:57.0223084Z b6de3bd1abd2: Pulling fs layer
2023-05-04T11:01:57.0223235Z 81cd8b7e2f26: Pulling fs layer
2023-05-04T11:01:57.0223370Z c95f5fa56356: Pulling fs layer
2023-05-04T11:01:57.0223511Z b30ad8ef1888: Pulling fs layer
2023-05-04T11:01:57.0223746Z acdf66eee352: Pulling fs layer
2023-05-04T11:01:57.0223886Z 340c9ed3bb74: Pulling fs layer
2023-05-04T11:01:57.0224430Z 74246855058e: Pulling fs layer
2023-05-04T11:01:57.0225373Z bf81fb31b274: Pulling fs layer
2023-05-04T11:01:57.0234909Z e1287fdd84e2: Pulling fs layer
2023-05-04T11:01:57.0235624Z b7395d383c00: Pulling fs layer
2023-05-04T11:01:57.0235955Z 50dd96d4c8eb: Pulling fs layer
2023-05-04T11:01:57.0236469Z 88e9f12d98e2: Pulling fs layer
2023-05-04T11:01:57.0236799Z c69b00659014: Pulling fs layer
2023-05-04T11:01:57.0237313Z 3d82388b1668: Pulling fs layer
2023-05-04T11:01:57.0237599Z c95f5fa56356: Waiting
2023-05-04T11:01:57.0238089Z b30ad8ef1888: Waiting
2023-05-04T11:01:57.0238371Z acdf66eee352: Waiting
2023-05-04T11:01:57.0238857Z 340c9ed3bb74: Waiting
2023-05-04T11:01:57.0239142Z 74246855058e: Waiting
2023-05-04T11:01:57.0239615Z bf81fb31b274: Waiting
2023-05-04T11:01:57.0239902Z e1287fdd84e2: Waiting
2023-05-04T11:01:57.0240389Z b7395d383c00: Waiting
2023-05-04T11:01:57.0240663Z 50dd96d4c8eb: Waiting
2023-05-04T11:01:57.0241153Z 88e9f12d98e2: Waiting
2023-05-04T11:01:57.0241426Z c69b00659014: Waiting
2023-05-04T11:01:57.0241910Z 3d82388b1668: Waiting
2023-05-04T11:01:57.0937635Z b6de3bd1abd2: Download complete
2023-05-04T11:01:57.2986243Z 81cd8b7e2f26: Verifying Checksum
2023-05-04T11:01:57.2986767Z 81cd8b7e2f26: Download complete
2023-05-04T11:01:57.3572439Z b30ad8ef1888: Verifying Checksum
2023-05-04T11:01:57.3572720Z b30ad8ef1888: Download complete
2023-05-04T11:01:57.4213805Z acdf66eee352: Verifying Checksum
2023-05-04T11:01:57.4214706Z acdf66eee352: Download complete
2023-05-04T11:01:57.5300543Z c95f5fa56356: Verifying Checksum
2023-05-04T11:01:57.5300907Z c95f5fa56356: Download complete
2023-05-04T11:01:57.6055378Z 74246855058e: Verifying Checksum
2023-05-04T11:01:57.6055986Z 74246855058e: Download complete
2023-05-04T11:01:57.6712367Z bf81fb31b274: Verifying Checksum
2023-05-04T11:01:57.6712550Z bf81fb31b274: Download complete
2023-05-04T11:01:57.7299127Z e1287fdd84e2: Verifying Checksum
2023-05-04T11:01:57.7300711Z e1287fdd84e2: Download complete
2023-05-04T11:01:57.7452267Z e64712e6a804: Verifying Checksum
2023-05-04T11:01:57.7452463Z e64712e6a804: Download complete
2023-05-04T11:01:58.2972484Z 50dd96d4c8eb: Verifying Checksum
2023-05-04T11:01:58.2972673Z 50dd96d4c8eb: Download complete
2023-05-04T11:01:58.3841951Z 88e9f12d98e2: Verifying Checksum
2023-05-04T11:01:58.3842130Z 88e9f12d98e2: Download complete
2023-05-04T11:01:58.4654102Z c69b00659014: Verifying Checksum
2023-05-04T11:01:58.4654285Z c69b00659014: Download complete
2023-05-04T11:01:58.5880455Z 3d82388b1668: Verifying Checksum
2023-05-04T11:01:58.5880625Z 3d82388b1668: Download complete
2023-05-04T11:01:58.9558999Z b7395d383c00: Verifying Checksum
2023-05-04T11:01:58.9559471Z b7395d383c00: Download complete
2023-05-04T11:01:59.9504416Z 340c9ed3bb74: Verifying Checksum
2023-05-04T11:01:59.9504789Z 340c9ed3bb74: Download complete
2023-05-04T11:02:01.2827250Z e64712e6a804: Pull complete
2023-05-04T11:02:01.3778518Z b6de3bd1abd2: Pull complete
2023-05-04T11:02:01.9155190Z 81cd8b7e2f26: Pull complete
2023-05-04T11:02:03.1431053Z c95f5fa56356: Pull complete
2023-05-04T11:02:03.1961742Z b30ad8ef1888: Pull complete
2023-05-04T11:02:03.2797430Z acdf66eee352: Pull complete
2023-05-04T11:02:10.6409272Z 340c9ed3bb74: Pull complete
2023-05-04T11:02:10.7444219Z 74246855058e: Pull complete
2023-05-04T11:02:10.7912226Z bf81fb31b274: Pull complete
2023-05-04T11:02:10.8512833Z e1287fdd84e2: Pull complete
2023-05-04T11:02:15.2914109Z b7395d383c00: Pull complete
2023-05-04T11:02:16.2330392Z 50dd96d4c8eb: Pull complete
2023-05-04T11:02:16.2790875Z 88e9f12d98e2: Pull complete
2023-05-04T11:02:16.3357664Z c69b00659014: Pull complete
2023-05-04T11:02:16.3945843Z 3d82388b1668: Pull complete
2023-05-04T11:02:16.3991834Z Digest: sha256:a3481d117b2193899077d69ece5fa38410f4b71c4ee7f472d2c7af33f544ad25
2023-05-04T11:02:16.4015040Z Status: Downloaded newer image for mcr.microsoft.com/appsvc/staticappsclient:stable
2023-05-04T11:02:16.8952616Z DeploymentId: 36a2a219-7c08-4d7e-b39d-64442ddeb153
2023-05-04T11:02:16.8953122Z 
2023-05-04T11:02:17.0279142Z [37mApp Directory Location: '/app' was found.[0m
2023-05-04T11:02:17.0285480Z [37mLooking for event info[0m
2023-05-04T11:02:21.8036921Z [37mStarting to build app with Oryx[0m
2023-05-04T11:02:21.8038731Z [33mAzure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx[0m
2023-05-04T11:02:21.8039137Z [37m---Oryx build logs---[0m
2023-05-04T11:02:21.8039392Z [37m[0m
2023-05-04T11:02:21.8039604Z [37m[0m
2023-05-04T11:02:22.2262303Z [37mOperation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx[0m
2023-05-04T11:02:22.2263046Z [37mYou can report issues at https://github.com/Microsoft/Oryx/issues[0m
2023-05-04T11:02:22.2263662Z [37m[0m
2023-05-04T11:02:22.2264147Z [37mOryx Version: 0.2.20230501.1, Commit: 58513374525ab2977af68fc5b3c344d32858d8af, ReleaseTagName: 20230501.1[0m
2023-05-04T11:02:22.2264717Z [37m[0m
2023-05-04T11:02:22.2265087Z [37mBuild Operation ID: 54605be3a677b955[0m
2023-05-04T11:02:22.2265651Z [37mOS Type           : bullseye[0m
2023-05-04T11:02:22.2265996Z [37mImage Type        : jamstack[0m
2023-05-04T11:02:22.2266513Z [37m[0m
2023-05-04T11:02:22.2408818Z [37mDetecting platforms...[0m
2023-05-04T11:02:24.0905527Z [37mDetected following platforms:[0m
2023-05-04T11:02:24.0931564Z [37m  nodejs: 18.16.0[0m
2023-05-04T11:02:24.0955183Z [37mVersion '18.16.0' of platform 'nodejs' is not installed. Generating script to install it...[0m
2023-05-04T11:02:24.1539190Z [37mDetected the following frameworks: Typescript,React[0m
2023-05-04T11:02:24.2560493Z [37m[0m
2023-05-04T11:02:24.3104052Z [37m[0m
2023-05-04T11:02:24.3117227Z [37mSource directory     : /working_dir/app[0m
2023-05-04T11:02:24.3117549Z [37mDestination directory: /36a2a219-7c08-4d7e-b39d-64442ddeb153-swa-oryx/app[0m
2023-05-04T11:02:24.3117758Z [37m[0m
2023-05-04T11:02:24.3117960Z [37mInstalling common platform dependencies...[0m
2023-05-04T11:02:25.2363180Z [37mGet:1 http://deb.debian.org/debian bullseye InRelease [116 kB][0m
2023-05-04T11:02:25.3062082Z [37mGet:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB][0m
2023-05-04T11:02:25.3073543Z [37mGet:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB][0m
2023-05-04T11:02:26.1442370Z [37mGet:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB][0m
2023-05-04T11:02:26.2673683Z [37mGet:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [237 kB][0m
2023-05-04T11:02:26.3610445Z [37mGet:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB][0m
2023-05-04T11:02:27.4695473Z [37mFetched 8643 kB in 2s (3614 kB/s)[0m
2023-05-04T11:02:27.9474353Z [37mReading package lists...[0m
2023-05-04T11:02:28.4459256Z [37mReading package lists...[0m
2023-05-04T11:02:28.5673102Z [37mBuilding dependency tree...[0m
2023-05-04T11:02:28.5673795Z [37mReading state information...[0m
2023-05-04T11:02:28.6412270Z [37mCalculating upgrade...[0m
2023-05-04T11:02:28.7266138Z [37m0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.[0m
2023-05-04T11:02:29.2144263Z [37mReading package lists...[0m
2023-05-04T11:02:29.3351774Z [37mBuilding dependency tree...[0m
2023-05-04T11:02:29.3366102Z [37mReading state information...[0m
2023-05-04T11:02:29.4675055Z [37mgit is already the newest version (1:2.30.2-1+deb11u2).[0m
2023-05-04T11:02:29.4675381Z [37m0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.[0m
2023-05-04T11:02:29.4742466Z [37m[0m
2023-05-04T11:02:29.4748660Z [37mDownloading and extracting 'nodejs' version '18.16.0' to '/opt/nodejs/18.16.0'...[0m
2023-05-04T11:02:29.5056294Z [37mDetected image debian flavor: bullseye.[0m
2023-05-04T11:02:30.9937315Z [37mDownloaded in 1 sec(s).[0m
2023-05-04T11:02:30.9944103Z [37mVerifying checksum...[0m
2023-05-04T11:02:31.0200499Z [37mExtracting contents...[0m
2023-05-04T11:02:32.4230187Z [37mperforming sha512 checksum for: nodejs...[0m
2023-05-04T11:02:32.6153326Z [37mDone in 3 sec(s).[0m
2023-05-04T11:02:32.6153582Z [37m[0m
2023-05-04T11:02:32.6793867Z [37mRemoving existing manifest file[0m
2023-05-04T11:02:32.6809022Z [37mCreating directory for command manifest file if it does not exist[0m
2023-05-04T11:02:32.7195626Z [37mCreating a manifest file...[0m
2023-05-04T11:02:32.7195896Z [37mNode Build Command Manifest file created.[0m
2023-05-04T11:02:32.7196072Z [37m[0m
2023-05-04T11:02:32.7196313Z [37mFound npm version spec to follow in package.json: '^9.3.1'[0m
2023-05-04T11:02:32.7196575Z [37mUpdating version of npm installed to meet the above version spec.[0m
2023-05-04T11:02:35.2300256Z [37m[0m
2023-05-04T11:02:35.2300808Z [37mremoved 1 package, and changed 60 packages in 2s[0m
2023-05-04T11:02:35.2301082Z [37m[0m
2023-05-04T11:02:35.2301370Z [37m27 packages are looking for funding[0m
2023-05-04T11:02:35.2301656Z [37m  run `npm fund` for details[0m
2023-05-04T11:02:35.2376670Z [37m[0m
2023-05-04T11:02:35.2377078Z [37m[0m
2023-05-04T11:02:35.2377348Z [37mUsing Node version:[0m
2023-05-04T11:02:35.2433506Z [37mv18.16.0[0m
2023-05-04T11:02:35.2497210Z [37m[0m
2023-05-04T11:02:35.2497741Z [37mUsing Npm version:[0m
2023-05-04T11:02:35.5419808Z [37m9.6.6[0m
2023-05-04T11:02:35.6237333Z [37m[0m
2023-05-04T11:02:35.6237937Z [37mRunning 'npm install'...[0m
2023-05-04T11:02:35.6238395Z [37m[0m
2023-05-04T11:02:52.3178652Z [37m[0m
2023-05-04T11:02:52.3178925Z [37madded 752 packages in 16s[0m
2023-05-04T11:02:52.3185282Z [37m[0m
2023-05-04T11:02:52.3185520Z [37m150 packages are looking for funding[0m
2023-05-04T11:02:52.3185742Z [37m  run `npm fund` for details[0m
2023-05-04T11:02:52.3478634Z [37m[0m
2023-05-04T11:02:52.3482226Z [37mRunning 'npm run build'...[0m
2023-05-04T11:02:52.3482417Z [37m[0m
2023-05-04T11:02:52.6173680Z [37m[0m
2023-05-04T11:02:52.6173958Z [37m> customers@1.0.0 build[0m
2023-05-04T11:02:52.6174139Z [37m> tsc && vite build[0m
2023-05-04T11:02:52.6174280Z [37m[0m
2023-05-04T11:03:02.4712759Z [37mvite v4.2.1 building for production...[0m
2023-05-04T11:03:02.6660020Z [37mtransforming...[0m
2023-05-04T11:03:28.7796566Z [37m✓ 12139 modules transformed.[0m
2023-05-04T11:03:29.3561882Z [31mGenerated an empty chunk: "dom-helpers".[0m
2023-05-04T11:03:29.3574027Z [31mGenerated an empty chunk: "html-parse-stringify".[0m
2023-05-04T11:03:29.3637315Z [31mGenerated an empty chunk: "prop-types".[0m
2023-05-04T11:03:29.4170804Z [31mGenerated an empty chunk: "void-elements".[0m
2023-05-04T11:03:29.6836418Z [37mrendering chunks...[0m
2023-05-04T11:03:30.7892213Z [37mcomputing gzip size...[0m
2023-05-04T11:03:30.8967131Z [37mbuild/assets/AdminTag-4cac5679.svg                    0.16 kB[0m
2023-05-04T11:03:30.8972334Z [37mbuild/assets/WarningIcon-3698bbd3.svg                 0.39 kB[0m
2023-05-04T11:03:30.8975256Z [37mbuild/index.html                                      3.37 kB[0m
2023-05-04T11:03:30.8978079Z [37mbuild/assets/errorIllustration-e71ee9a8.png          23.84 kB[0m
2023-05-04T11:03:30.8980494Z [37mbuild/assets/Nk-logo-positiv-b045f92b.png            73.70 kB[0m
2023-05-04T11:03:30.8982812Z [37mbuild/assets/loginPageIllustration-3f707991.png     225.16 kB[0m
2023-05-04T11:03:30.8985242Z [37mbuild/assets/dom-helpers-4ed993c7.js                  0.00 kB │ gzip:   0.02 kB[0m
2023-05-04T11:03:30.8991639Z [37mbuild/assets/html-parse-stringify-4ed993c7.js         0.00 kB │ gzip:   0.02 kB[0m
2023-05-04T11:03:30.8994739Z [37mbuild/assets/prop-types-4ed993c7.js                   0.00 kB │ gzip:   0.02 kB[0m
2023-05-04T11:03:30.8997279Z [37mbuild/assets/void-elements-4ed993c7.js                0.00 kB │ gzip:   0.02 kB[0m
2023-05-04T11:03:30.9005109Z [37mbuild/assets/clsx-1229b3e0.js                         0.36 kB │ gzip:   0.23 kB[0m
2023-05-04T11:03:30.9008012Z [37mbuild/assets/react-error-boundary-e160aa8d.js         1.45 kB │ gzip:   0.71 kB[0m
2023-05-04T11:03:30.9011105Z [37mbuild/assets/react-is-1aacdabe.js                     2.16 kB │ gzip:   0.79 kB[0m
2023-05-04T11:03:30.9016389Z [37mbuild/assets/react-router-dom-a3350d59.js             2.63 kB │ gzip:   1.35 kB[0m
2023-05-04T11:03:30.9019622Z [37mbuild/assets/hoist-non-react-statics-691fe6cb.js      2.65 kB │ gzip:   0.97 kB[0m
2023-05-04T11:03:30.9022565Z [37mbuild/assets/scheduler-04ce0582.js                    4.14 kB │ gzip:   1.80 kB[0m
2023-05-04T11:03:30.9025715Z [37mbuild/assets/stylis-581c9ed0.js                       4.21 kB │ gzip:   1.95 kB[0m
2023-05-04T11:03:30.9030628Z [37mbuild/assets/@babel-60581b80.js                       4.56 kB │ gzip:   1.82 kB[0m
2023-05-04T11:03:30.9033649Z [37mbuild/assets/react-i18next-9b51b0f4.js                5.27 kB │ gzip:   2.28 kB[0m
2023-05-04T11:03:30.9036158Z [37mbuild/assets/react-transition-group-c9677172.js       6.42 kB │ gzip:   2.21 kB[0m
2023-05-04T11:03:30.9041445Z [37mbuild/assets/react-router-04b8a35a.js                 7.88 kB │ gzip:   3.11 kB[0m
2023-05-04T11:03:30.9060885Z [37mbuild/assets/react-985293de.js                        8.12 kB │ gzip:   3.08 kB[0m
2023-05-04T11:03:30.9061177Z [37mbuild/assets/@remix-run-6e40cad8.js                   8.72 kB │ gzip:   3.78 kB[0m
2023-05-04T11:03:30.9061469Z [37mbuild/assets/@emotion-656d2da0.js                    18.02 kB │ gzip:   7.79 kB[0m
2023-05-04T11:03:30.9068599Z [37mbuild/assets/@popperjs-f3391c26.js                   20.09 kB │ gzip:   7.49 kB[0m
2023-05-04T11:03:30.9073064Z [37mbuild/assets/i18next-3588fa67.js                     55.98 kB │ gzip:  15.08 kB[0m
2023-05-04T11:03:30.9076669Z [37mbuild/assets/recoil-ec59a727.js                      78.46 kB │ gzip:  24.61 kB[0m
2023-05-04T11:03:30.9079801Z [37mbuild/assets/react-dom-fbbf7044.js                  129.97 kB │ gzip:  41.79 kB[0m
2023-05-04T11:03:30.9085060Z [37mbuild/assets/@microsoft-1a4f250d.js                 131.82 kB │ gzip:  51.75 kB[0m
2023-05-04T11:03:30.9090624Z [37mbuild/assets/@mui-c5b0e9d9.js                       165.17 kB │ gzip:  51.11 kB[0m
2023-05-04T11:03:30.9094033Z [37mbuild/assets/index-799ca6b2.js                      304.87 kB │ gzip:  72.15 kB[0m
2023-05-04T11:03:30.9096545Z [37mbuild/assets/@azure-8884ac44.js                     335.18 kB │ gzip:  71.80 kB[0m
2023-05-04T11:03:30.9102686Z [37mbuild/assets/@norkart-53ba1808.js                 1,308.20 kB │ gzip: 376.96 kB[0m
2023-05-04T11:03:30.9106831Z [31m[0m
2023-05-04T11:03:30.9109322Z [31m(!) Some chunks are larger than 500 kBs after minification. Consider:[0m
2023-05-04T11:03:30.9118894Z [31m- Using dynamic import() to code-split the application[0m
2023-05-04T11:03:30.9119245Z [31m- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks[0m
2023-05-04T11:03:30.9119700Z [31m- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.[0m
2023-05-04T11:03:30.9126037Z [37m✓ built in 28.44s[0m
2023-05-04T11:03:31.0384576Z [37mPreparing output...[0m
2023-05-04T11:03:31.0387080Z [37m[0m
2023-05-04T11:03:31.0389658Z [37mCopying files to destination directory '/36a2a219-7c08-4d7e-b39d-64442ddeb153-swa-oryx/app'...[0m
2023-05-04T11:03:35.6063829Z [37mDone in 4 sec(s).[0m
2023-05-04T11:03:35.6074798Z [37m[0m
2023-05-04T11:03:35.6075070Z [37mRemoving existing manifest file[0m
2023-05-04T11:03:35.6096123Z [37mCreating a manifest file...[0m
2023-05-04T11:03:35.6097772Z [37mManifest file created.[0m
2023-05-04T11:03:35.6098032Z [37mCopying .ostype to manifest output directory.[0m
2023-05-04T11:03:35.6119198Z [37m[0m
2023-05-04T11:03:35.6119412Z [37mDone in 71 sec(s).[0m
2023-05-04T11:03:35.6771600Z [37m[0m
2023-05-04T11:03:35.6771821Z [37m[0m
2023-05-04T11:03:35.6772014Z [37m---End of Oryx build logs---[0m
2023-05-04T11:03:35.6772211Z [37mFinished building app with Oryx[0m
2023-05-04T11:03:35.9948096Z [37mUsing 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.[0m
2023-05-04T11:03:36.0033560Z [37mCopying 'staticwebapp.config.json' to build output[0m
2023-05-04T11:03:36.0253111Z [37mNo Api directory specified. Azure Functions will not be created.[0m
2023-05-04T11:03:36.1154646Z [33mEither no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.[0m
2023-05-04T11:03:47.5282201Z [37mZipping App Artifacts[0m
2023-05-04T11:03:47.6524223Z [37mDone Zipping App Artifacts[0m
2023-05-04T11:03:47.6524539Z [37mUploading build artifacts.[0m
2023-05-04T11:04:01.8534638Z [32mFinished Upload. Polling on deployment.[0m
2023-05-04T11:04:01.8910825Z [37mStatus: InProgress. Time: 0.0377411(s)[0m
2023-05-04T11:04:16.9226016Z [37mStatus: InProgress. Time: 15.0679224(s)[0m
2023-05-04T11:04:31.9617676Z [37mStatus: Succeeded. Time: 30.1030912(s)[0m
2023-05-04T11:04:31.9618010Z [32mDeployment Complete :)[0m
2023-05-04T11:04:31.9618272Z [32mVisit your site at: https://white-grass-0c1d11903.1.azurestaticapps.net[0m
2023-05-04T11:04:31.9803307Z [37mThanks for using Azure Static Web Apps![0m
2023-05-04T11:04:31.9803593Z [37mExiting[0m
2023-05-04T11:04:32.2312021Z ##[section]Finishing: AzureStaticWebApp
```

### Relevant log output

```shell
Before task:
-rw-r--r-- 1 vsts docker 1379 May  4 11:01 app/.npmrc
After task:
-rw-r--r-- 1 root root 1379 May  4 11:01 app/.npmrc

2023-05-04T11:04:32.3743391Z ##[section]Starting: npmAuthenticate
2023-05-04T11:04:32.3746567Z ==============================================================================
2023-05-04T11:04:32.3746673Z Task         : npm authenticate (for task runners)
2023-05-04T11:04:32.3746876Z Description  : Don't use this task if you're also using the npm task. Provides npm credentials to an .npmrc file in your repository for the scope of the build. This enables npm task runners like gulp and Grunt to authenticate with private registries.
2023-05-04T11:04:32.3747065Z Version      : 0.218.0
2023-05-04T11:04:32.3747119Z Author       : Microsoft Corporation
2023-05-04T11:04:32.3747192Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm-authenticate
2023-05-04T11:04:32.3747288Z ==============================================================================
2023-05-04T11:04:32.4959884Z ##[error]Unhandled: EACCES: permission denied, open '/home/vsts/work/1/s/app/.npmrc'
2023-05-04T11:04:32.4976036Z ##[error]Error: EACCES: permission denied, open '/home/vsts/work/1/s/app/.npmrc'
    at Object.openSync (node:fs:594:3)
    at Object.writeFileSync (node:fs:2207:35)
    at copyFile (/home/vsts/work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.218.0/node_modules/azure-pipelines-tasks-packaging-common-v3/util.js:20:8)
    at Object.restoreFileWithName (/home/vsts/work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.218.0/node_modules/azure-pipelines-tasks-packaging-common-v3/util.js:58:13)
    at /home/vsts/work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.218.0/npmauthcleanup.js:27:18
    at Generator.next (<anonymous>)
    at /home/vsts/work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.218.0/npmauthcleanup.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/vsts/work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.218.0/npmauthcleanup.js:4:12)
    at run (/home/vsts/work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.218.0/npmauthcleanup.js:18:12)
2023-05-04T11:04:32.5009123Z ##[section]Finishing: npmAuthenticate
```

### Aditional info

```shell
The task runs fine but cleanup fails
```

**Comment by matthewtmurray** [comment]
I was getting the same error as shown above on the npmauthenticate clean-up task. it just seems to have started happening today. I had been using the task specified like this:
```
 - task: npmAuthenticate@0
              inputs:
                workingFile: 'frontend/.npmrc'
```
but then tried specifying a (presumably earlier version)  and it fixed my issue. so now I have the task specified as :

```
 - task: npmAuthenticate@0.208.1
              inputs:
                workingFile: 'frontend/.npmrc'
```

**Comment by bkempinski** [comment]
I have the same issue, the "s" directory in the _work path changed ownership to root.
The first run work, but any subsequent results in permission denied:

`Starting: Checkout Front-End@develop to s
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Syncing repository: Front-End (Git)
git version
git version 2.34.1
git config --get remote.origin.url
##[warning]'git config --get remote.origin.url' failed with exit code: 1, output: ''
##[error]One or several exceptions have been occurred.
##[error]System.UnauthorizedAccessException: Access to the path '/data/devops-agent/_work/1/s/.gitignore' is denied.`

`tb-admin@tb-tools-test1:/data/devops-agent/_work/1$ ls -al
total 24
drwxr-xr-x 6 tb-admin tb-admin 4096 May  8 12:40 .
drwxrwxr-x 9 tb-admin tb-admin 4096 May  8 12:37 ..
drwxr-xr-x 2 tb-admin tb-admin 4096 May  8 12:40 TestResults
drwxr-xr-x 2 tb-admin tb-admin 4096 May  8 12:40 a
drwxr-xr-x 2 tb-admin tb-admin 4096 May  8 12:34 b
drwxr-xr-x 8 root     root     4096 May  8 12:36 s
tb-admin@tb-tools-test1:/data/devops-agent/_work/1$
`

**Comment by richp582** [comment]
Confirmed seeing it too on linux self-hosted

**Comment by brandon-gibbs** [comment]
We are seeing this as well

**Comment by srisurya777** [comment]
Does anyone have a workaround for this ? 
we tried adding a shell script to change the folder permissions after the static app task and it fails, too. Very strange it works sometimes and most of the times it does not. Whats even strange is shell script checking for node path

below is the log and attached screenshot for details.

##[debug]Evaluating condition for step: 'change permissions back'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
<img width="1146" alt="Screenshot 2023-06-29 at 12 52 26 AM" src="https://github.com/microsoft/azure-pipelines-tasks/assets/15880389/30d6661e-d734-4a2f-acc4-2611a8ff5945">

##[debug]Result: True
Starting: change permissions back
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.224.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
##[debug]Using node path: /agent/externals/node16/bin/node
##[error]An error occurred trying to start process '/agent/externals/node16/bin/node' with working directory '/agent/_work/1/s'. Permission denied
##[debug]System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/agent/externals/node16/bin/node' with working directory '/agent/_work/1/s'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, Boolean continueAfterCancelProcessTreeKillAttempt, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Agent.Sdk/ProcessInvoker.cs:line 291
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, Boolean continueAfterCancelProcessTreeKillAttempt, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Microsoft.VisualStudio.Services.Agent/ProcessInvoker.cs:line 308
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, Boolean continueAfterCancelProcessTreeKillAttempt, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Agent.Worker/Handlers/StepHost.cs:line 76
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync() in /home/vsts/work/1/s/src/Agent.Worker/Handlers/NodeHandler.cs:line 206
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync() in /home/vsts/work/1/s/src/Agent.Worker/TaskRunner.cs:line 407
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken) in /home/vsts/work/1/s/src/Agent.Worker/StepsRunner.cs:line 236

**Comment by Tasin5541** [comment]
Commenting to keep the issue from going stale. This is still an issue.

**Comment by pszujewski** [comment]
Commenting to keep the issue from going stale. This is still an issue.

**Comment by tw-hedgehog** [comment]
We encountered this too!

**Comment by srbrills** [comment]
Just encountered this for myself as well!  Commenting to keep from going stale.  Task version 0.248.1 on a self-hosted Ubuntu agent.

**Comment by asendall** [comment]
Same problem May 2025 - Downgrade to 0.208.1 still working

**Comment by pintert3** [comment]
Same here! I keep having to delete the pipeline folder. Only happens with the one for AzureStaticWebApps. Doesn't happen with the other pipelines of my own.

**Comment by JarroVGIT** [comment]
It baffles me that this incredible flaw, which was reported over 3 years(!) ago is still an issue. We moved to using the SWA CLI for now, but this is just weird.

**Comment by roland-part** [comment]
Time goes by, the issue remains... commenting to keep the issue open.

**Comment by pintert3** [comment]
No solution yet. Commenting to keep open.

**Comment by derBobby** [comment]
Same for me. Vote 4 fix.
