### ISSUE TITLE
[BUG]: Failed to deploy web package to App Service.

### ISSUE THREAD

**Issue by akshay6000** [microsoft/azure-pipelines-tasks#18765]
### Task name

Azure App Service deploy

### Task version

4.225.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Task log

```shell
2023-08-03T06:28:50.0253262Z Generating deployment script.
2023-08-03T06:28:50.0254497Z Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"'.
2023-08-03T06:28:50.0254967Z C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153
2023-08-03T06:28:50.0255383Z                 ...StatusLogger.DEFAULT_STATUS,
2023-08-03T06:28:50.0255618Z                 ^^^
2023-08-03T06:28:50.0255728Z 
2023-08-03T06:28:50.0255932Z SyntaxError: Unexpected token ...
2023-08-03T06:28:50.0256159Z     at createScript (vm.js:56:10)
2023-08-03T06:28:50.0256417Z     at Object.runInThisContext (vm.js:97:10)
2023-08-03T06:28:50.0256692Z     at Module._compile (module.js:542:28)
2023-08-03T06:28:50.0256985Z     at Object.Module._extensions..js (module.js:579:10)
2023-08-03T06:28:50.0257259Z     at Module.load (module.js:487:32)
2023-08-03T06:28:50.0257498Z     at tryModuleLoad (module.js:446:12)
2023-08-03T06:28:50.0257765Z     at Function.Module._load (module.js:438:3)
2023-08-03T06:28:50.0258012Z     at Module.require (module.js:497:17)
2023-08-03T06:28:50.0258253Z     at module.js:669:12
2023-08-03T06:28:50.0258481Z     at Array.forEach (native)
2023-08-03T06:28:50.0259471Z C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153\r\n                ...StatusLogger.DEFAULT_STATUS,\r\n                ^^^\r\n\r\nSyntaxError: Unexpected token ...\r\n    at createScript (vm.js:56:10)\r\n    at Object.runInThisContext (vm.js:97:10)\r\n    at Module._compile (module.js:542:28)\r\n    at Object.Module._extensions..js (module.js:579:10)\r\n    at Module.load (module.js:487:32)\r\n    at tryModuleLoad (module.js:446:12)\r\n    at Function.Module._load (module.js:438:3)\r\n    at Module.require (module.js:497:17)\r\n    at module.js:669:12\r\n    at Array.forEach (native)\r\nC:\Program Files (x86)\SiteExtensions\Kudu\100.50622.6321\bin\Scripts\starter.cmd "C:\Program Files (x86)\SiteExtensions\Kudu\100.50622.6321\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"
2023-08-03T06:28:50.0260430Z Deployment Failed.
2023-08-03T06:28:50.0293508Z ##[error]Failed to deploy web package to App Service.
2023-08-03T06:28:50.0306695Z ##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
```

### Relevant log output

```shell
2023-08-03T06:28:50.0255932Z SyntaxError: Unexpected token ...
2023-08-03T06:28:50.0256159Z     at createScript (vm.js:56:10)
2023-08-03T06:28:50.0256417Z     at Object.runInThisContext (vm.js:97:10)
2023-08-03T06:28:50.0256692Z     at Module._compile (module.js:542:28)
2023-08-03T06:28:50.0256985Z     at Object.Module._extensions..js (module.js:579:10)
2023-08-03T06:28:50.0257259Z     at Module.load (module.js:487:32)
2023-08-03T06:28:50.0257498Z     at tryModuleLoad (module.js:446:12)
2023-08-03T06:28:50.0257765Z     at Function.Module._load (module.js:438:3)
2023-08-03T06:28:50.0258012Z     at Module.require (module.js:497:17)
2023-08-03T06:28:50.0258253Z     at module.js:669:12
2023-08-03T06:28:50.0258481Z     at Array.forEach (native)
2023-08-03T06:28:50.0259471Z C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153\r\n                ...StatusLogger.DEFAULT_STATUS,\r\n                ^^^\r\n\r\nSyntaxError: Unexpected token ...\r\n    at createScript (vm.js:56:10)\r\n    at Object.runInThisContext (vm.js:97:10)\r\n    at Module._compile (module.js:542:28)\r\n    at Object.Module._extensions..js (module.js:579:10)\r\n    at Module.load (module.js:487:32)\r\n    at tryModuleLoad (module.js:446:12)\r\n    at Function.Module._load (module.js:438:3)\r\n    at Module.require (module.js:497:17)\r\n    at module.js:669:12\r\n    at Array.forEach (native)\r\nC:\Program Files 
x86)\SiteExtensions\Kudu\100.50622.6321\bin\Scripts\starter.cmd "C:\Program Files (x86)\SiteExtensions\Kudu\100.50622.6321\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"
```

### Aditional info

```shell
We recently started seeing deployment failures, upon checking one thing I see it the version of task got upgraded from the last working deployment from 4.223.2 to 4.225.0.

Upon searching for the issue, I see it was recommended to upgrade WEBSITE_NODE_DEFAULT_VERSION to some version but we are not using WEBSITE_NODE_DEFAULT_VERSION in our app service configuration.

Only nodejs related key in the configuration we are using is- XDT_MicrosoftApplicationInsights_NodeJS: 1

We havenoticed this error from yesterday.
```

**Comment by v-mohithgc** [comment]
Can you enable the debug logs (systm.debug=true) and share here please?
Thanks

**Comment by akshay6000** [comment]
Hey, sorry for the late response on this. I was able to mitigate this error by explicitly adding WEBSITE_NODE_DEFAULT_VERSION to some supported version by our App service.

**Comment by v-mohithgc** [comment]
Thanks for confirming.

**Comment by Mike-E-angelo** [comment]
In my case I got this issue after enabling Application Insights on my AppService.  Specifically `XDT_MicrosoftApplicationInsights_NodeJS` was set to 1 during the install, which in turn looked for the `WEBSITE_NODE_DEFAULT_VERSION` value which was assigned to `6.9.1`.  This in turn destroyed my workflow execution, resulting in the stack trace above.
