### ISSUE TITLE
[BUG]: IISWebAppDeploymentOnMachineGroup@0 - Error: Unrecognized argument 'Files\IIS\Microsoft'. All arguments must begin with "-"

### ISSUE THREAD

**Issue by R-Damian** [microsoft/azure-pipelines-tasks#18811]
### Task name

IISWebAppDeploymentOnMachineGroup

### Task version

0.226.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 10 and Windows Server 2012 R2

### Task log

```shell
Version      : 0.226.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
==============================================================================
"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp='C:\azagent\A1\_work\1\build' -dest:iisApp='insurancesandclaimsservices' -enableRule:DoNotDeleteRule
Error: The process 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe' failed with exit code 4294967295
    at ExecState._setResult (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.226.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
    at ExecState.CheckComplete (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.226.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
    at ChildProcess.<anonymous> (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.226.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Retrying to deploy the package.
"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp='C:\azagent\A1\_work\1\build' -dest:iisApp='insurancesandclaimsservices' -enableRule:DoNotDeleteRule
Error: The process 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe' failed with exit code 4294967295
    at ExecState._setResult (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.226.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
    at ExecState.CheckComplete (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.226.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
    at ChildProcess.<anonymous> (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.226.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Retrying to deploy the package.
"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp='C:\azagent\A1\_work\1\build' -dest:iisApp='insurancesandclaimsservices' -enableRule:DoNotDeleteRule
##[error]Failed to deploy web package to IIS website.
##[error]Error: Unrecognized argument 'Files\IIS\Microsoft'. All arguments must begin with "-".
Error count: 1.

##[error]Error: The process 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe' failed with exit code 4294967295
Finishing: IISWebAppDeploymentOnMachineGroup
```

### Relevant log output

```shell
"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp='C:\azagent\A1\_work\1\build' -dest:iisApp='insurancesandclaimsservices' -enableRule:DoNotDeleteRule
##[error]Failed to deploy web package to IIS website.
##[error]Error: Unrecognized argument 'Files\IIS\Microsoft'. All arguments must begin with "-".
Error count: 1.
```

### Aditional info

```shell
This error does not occur if I downgrade to version 0.222.0. I have other servers where the task works and I think the difference is that it uses an msdeploy executable inside the agent directory and that path has no whitespace

This path works:

C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.226.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe

this path DOES NOT work:

"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
```

**Comment by garethmonk** [comment]
Encountered this issue today. How would one go about downgrading to 0.222.0?

**Comment by R-Damian** [comment]
In yaml pipelines you have to use the full version of the task
  IISWebAppDeploymentOnMachineGroup@0.222.0 as documented here https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-versions.

I didn't want to ask the customer to uninstall msdeploy on their servers because I'm not sure what impact this would have. My solution was to go to the directory where the task is cached and modify the file deployingusingmsdeploy.js changing line 36 with this:

var msDeployPath = process.cwd().replace("\\_work\\1\\s","") + "\\_work\\_tasks\\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\\0.226.0 \\node_modules\\azure-pipelines-tasks-webdeployment-common\\MSDeploy3.6\\MSDeploy3.6\\msdeploy.exe"

This forces the task to use the version of msdeploy that is included with it.
