### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by jappenzesr** [microsoft/azure-pipelines-tasks#18839]
### Task name

UseDotNet@2

### Task version

2.226.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Task log

```shell
2023-08-17T09:19:57.7821487Z Setting up proxy configuration for NuGet.
2023-08-17T09:19:57.7826995Z ##[debug]which '/usr/bin/nuget'
2023-08-17T09:19:57.7831271Z ##[debug]found: '/usr/bin/nuget'
2023-08-17T09:19:57.7835092Z ##[debug]/usr/bin/nuget arg: config
2023-08-17T09:19:57.7838792Z ##[debug]/usr/bin/nuget arg: -set
2023-08-17T09:19:57.7842252Z ##[debug]/usr/bin/nuget arg: http_proxy=http://192.168.1.1:8080
2023-08-17T09:19:57.7850028Z ##[debug]exec tool: /usr/bin/nuget
2023-08-17T09:19:57.7854688Z ##[debug]arguments:
2023-08-17T09:19:57.7860082Z ##[debug]   config
2023-08-17T09:19:57.7863574Z ##[debug]   -set
2023-08-17T09:19:57.7868111Z ##[debug]   http_proxy=http://192.168.1.1:8080
2023-08-17T09:19:57.7876187Z [command]/usr/bin/nuget config -set http_proxy=http://192.168.1.1:8080
2023-08-17T09:19:58.1187183Z ##[debug]which '/usr/bin/nuget'
2023-08-17T09:19:58.1193877Z ##[debug]found: '/usr/bin/nuget'
2023-08-17T09:19:58.1197567Z ##[debug]/usr/bin/nuget arg: config
2023-08-17T09:19:58.1201393Z ##[debug]/usr/bin/nuget arg: -set
2023-08-17T09:19:58.1204392Z ##[debug]/usr/bin/nuget arg: http_proxy.user=undefined
2023-08-17T09:19:58.1207552Z ##[debug]exec tool: /usr/bin/nuget
2023-08-17T09:19:58.1210426Z ##[debug]arguments:
2023-08-17T09:19:58.1213283Z ##[debug]   config
2023-08-17T09:19:58.1216100Z ##[debug]   -set
2023-08-17T09:19:58.1219319Z ##[debug]   http_proxy.user=undefined
2023-08-17T09:19:58.1223200Z [command]/usr/bin/nuget config -set http_proxy.user=undefined
2023-08-17T09:19:58.1288100Z ##[debug]which '/usr/bin/nuget'
2023-08-17T09:19:58.1294944Z ##[debug]found: '/usr/bin/nuget'
2023-08-17T09:19:58.1298132Z ##[debug]/usr/bin/nuget arg: config
2023-08-17T09:19:58.1302416Z ##[debug]/usr/bin/nuget arg: -set
2023-08-17T09:19:58.1303336Z ##[debug]/usr/bin/nuget arg: http_proxy.password=undefined
2023-08-17T09:19:58.1313405Z ##[debug]exec tool: /usr/bin/nuget
2023-08-17T09:19:58.1314176Z ##[debug]arguments:
2023-08-17T09:19:58.1315280Z ##[debug]   config
2023-08-17T09:19:58.1315835Z ##[debug]   -set
2023-08-17T09:19:58.1316634Z ##[debug]   http_proxy.password=undefined
2023-08-17T09:19:58.1317342Z [command]/usr/bin/nuget config -set http_proxy.password=undefined
2023-08-17T09:19:58.1403431Z ##[debug]task result: Succeeded
2023-08-17T09:19:58.1404699Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]
2023-08-17T09:20:01.3299346Z NuGet.Config is not valid XML. Path: '/agent/_work/1/s/$HOME/.config/NuGet/NuGet.Config'.
2023-08-17T09:20:01.3299965Z   Root element is missing.
2023-08-17T09:20:01.3311200Z NuGet.Config is not valid XML. Path: '/agent/_work/1/s/$HOME/.config/NuGet/NuGet.Config'.
2023-08-17T09:20:01.3311662Z   Root element is missing.
2023-08-17T09:20:01.3598779Z ##[debug]Exit code 1 received from tool '/usr/bin/nuget'
2023-08-17T09:20:01.3615203Z ##[debug]STDIO streams have closed for tool '/usr/bin/nuget'
2023-08-17T09:20:01.3615622Z ##[debug]task result: Failed
2023-08-17T09:20:01.3646965Z ##[error]Unhandled: The process '/usr/bin/nuget' failed with exit code 1
2023-08-17T09:20:01.3654253Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: The process '/usr/bin/nuget' failed with exit code 1
2023-08-17T09:20:01.3655321Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: The process '/usr/bin/nuget' failed with exit code 1
2023-08-17T09:20:01.3657181Z ##[error]Error: The process '/usr/bin/nuget' failed with exit code 1
    at ExecState._setResult (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:943:25)
    at ExecState.CheckComplete (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:926:18)
    at ChildProcess.<anonymous> (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:839:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
2023-08-17T09:20:01.3659275Z ##[debug]Processed: ##vso[task.issue type=error;]Error: The process '/usr/bin/nuget' failed with exit code 1
    at ExecState._setResult (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:943:25)
    at ExecState.CheckComplete (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:926:18)
    at ChildProcess.<anonymous> (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:839:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
2023-08-17T09:20:01.3723388Z ##[debug]Exit code 1 received from tool '/usr/bin/nuget'
2023-08-17T09:20:01.3723860Z ##[debug]STDIO streams have closed for tool '/usr/bin/nuget'
2023-08-17T09:20:01.3724245Z ##[debug]task result: Failed
2023-08-17T09:20:01.3724765Z ##[error]Unhandled: The process '/usr/bin/nuget' failed with exit code 1
2023-08-17T09:20:01.3725237Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: The process '/usr/bin/nuget' failed with exit code 1
2023-08-17T09:20:01.3725956Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: The process '/usr/bin/nuget' failed with exit code 1
2023-08-17T09:20:01.3727983Z ##[error]Error: The process '/usr/bin/nuget' failed with exit code 1
    at ExecState._setResult (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:943:25)
    at ExecState.CheckComplete (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:926:18)
    at ChildProcess.<anonymous> (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:839:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
2023-08-17T09:20:01.3729610Z ##[debug]Processed: ##vso[task.issue type=error;]Error: The process '/usr/bin/nuget' failed with exit code 1
    at ExecState._setResult (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:943:25)
    at ExecState.CheckComplete (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:926:18)
    at ChildProcess.<anonymous> (/agent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.226.0/node_modules/azure-pipelines-task-lib/toolrunner.js:839:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
2023-08-17T09:20:01.4112361Z ##[debug]Exit code 0 received from tool '/usr/bin/nuget'
2023-08-17T09:20:01.4112841Z ##[debug]STDIO streams have closed for tool '/usr/bin/nuget'
2023-08-17T09:20:01.4260203Z ##[section]Finishing: Use .NET Core sdk 3.1
```

### Relevant log output

```shell
2023-08-17T09:20:01.3299346Z NuGet.Config is not valid XML. Path: '/agent/_work/1/s/$HOME/.config/NuGet/NuGet.Config'.
```

### Aditional info

```shell
The task version creates an actual directory '$HOME' in /agent/_work/1_s, and creates the NuGet config file in /agent/_work/1/s/$HOME/.config/NuGet/NuGet.Config, 
instead of $HOME/.config/NuGet/NuGet.Config

This makes the task fail. 

The task is running on an agent configured behind a corporate proxy.
```

**Comment by jblafage** [comment]
Hello,

I can reproduce this issue on Ubuntu-22.04 VMSS which is behind a corporate proxy.

**Comment by dev-git** [comment]
Can also report this is an issue on Windows Server 2019 Standard behind a corporate proxy.

**Comment by Poltergeisen** [comment]
This is also a problem for us on a corporate proxy

**Comment by Poltergeisen** [comment]
Are there any workarounds to fix this?

**Comment by Mikaciu** [comment]
There are some mentions in the code that it may have been possible to install another version of nuget : 
* https://github.com/microsoft/azure-pipelines-tasks/blob/6ea095ec7e00d2c33b91c6a553ef3c587c509233/Tasks/UseDotNetV2/usedotnet.ts#L46
* https://github.com/microsoft/azure-pipelines-tasks/blob/6ea095ec7e00d2c33b91c6a553ef3c587c509233/Tasks/UseDotNetV2/usedotnet.ts#L24

Maybe this would solve the issue ?

**Comment by JonWaide** [comment]
We were able to work around this issue in our build pipelines by specifying the the 2.222 version of the "UseDotNet" task.  
Before:
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/9054459/a203c66f-24b7-4ca0-b6fa-146955e0b3b8)

After:
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/9054459/e2d38313-b0a2-4040-9a11-dd76aefdf543)

**Comment by Poltergeisen** [comment]
The only thing that changed between 2.222 and 2.226 was this PR based on the release notes at least

https://github.com/microsoft/azure-pipelines-tasks/pull/18676/files#diff-134b12c1bfc47023619ec12014a09ca6d64594c616b0265f342471be30414bb5

**Comment by Poltergeisen** [comment]
I submitted a support ticket through Azure for this bug. I am hoping to hear more sometime this week

**Comment by DmitriiBobreshev** [comment]
Hi @jappenzesr, @Poltergeisen, Sorry for the inconvenience, seems like the error started to happen because of a new logic of the uncaughtException in node16 and how we handle it in [task-lib](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/task.ts#L117). 
To check it in detail, could someone please send me a successful and failed sample with debug logs? You can send me the logs here or via email at v-bobreshevd@microsoft.com

**Comment by Poltergeisen** [comment]
@DmitriiBobreshev I sent those logs to the support team already.

#2308240010014724 is the tracking number.

Maybe check with v-bcascante@microsoft.com

**Comment by Poltergeisen** [comment]
@DmitriiBobreshev this seems to have broken in the Nuget task now as well

```
==============================================================================
Task         : NuGet
Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
Version      : 2.227.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
==============================================================================

Found tool in cache: NuGet 4.9.6 x64
Detected NuGet version 4.9.6.8 / 4.9.6+a32bce39889f724fbd11cfd12e946f802168b583
/usr/bin/mono /home/az_devops_agent/agent/_work/_tool/NuGet/4.9.6/x64/nuget.exe push /home/az_devops_agent/agent/_work/334/release-pipeline/nupkgs/example.4.0.0.nupkg -NonInteractive -Source https://pkgs.dev.azure.com/XXX/XXX/nuget/v3/index.json -ApiKey VSTS -Verbosity Detailed
NuGet.Config is not valid XML. Path: '/home/az_devops_agent/.config/NuGet/NuGet.Config'.
  Data at the root level is invalid. Line 11, position 1.
NuGet.Configuration.NuGetConfigurationException: NuGet.Config is not valid XML. Path: '/home/az_devops_agent/.config/NuGet/NuGet.Config'. ---> System.Xml.XmlException: Data at the root level is invalid. Line 11, position 1.
  at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x00027] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.Throw (System.String res, System.String arg) [0x00029] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.Throw (System.String res) [0x00000] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace () [0x0012c] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x002d4] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.Read () [0x0008c] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.Linq.XContainer.ReadContentFrom (System.Xml.XmlReader r) [0x00025] in <8d6554d17b084e8689fdd20da40c74a1>:0 
  at System.Xml.Linq.XContainer.ReadContentFrom (System.Xml.XmlReader r, System.Xml.Linq.LoadOptions o) [0x00005] in <8d6554d17b084e8689fdd20da40c74a1>:0 
  at System.Xml.Linq.XDocument.Load (System.Xml.XmlReader reader, System.Xml.Linq.LoadOptions options) [0x00024] in <8d6554d17b084e8689fdd20da40c74a1>:0 
  at NuGet.Configuration.XmlUtility.LoadSafe (System.IO.Stream input, System.Xml.Linq.LoadOptions options) [0x0000e] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.XmlUtility.GetDocument (System.String fullPath) [0x00007] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.XmlUtility.GetOrCreateDocument (System.Xml.Linq.XDocument content, System.String fullPath) [0x0000b] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.SettingsFile+<>c__DisplayClass27_0.<.ctor>b__0 () [0x00017] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.SettingsFile+<>c__DisplayClass38_0.<ExecuteSynchronized>b__0 () [0x00000] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
   --- End of inner exception stack trace ---
  at NuGet.Configuration.SettingsFile+<>c__DisplayClass38_0.<ExecuteSynchronized>b__0 () [0x00087] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked (System.String filePath, System.Action action) [0x00087] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.SettingsFile.ExecuteSynchronized (System.Action ioOperation) [0x0001a] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.SettingsFile..ctor (System.String directoryPath, System.String fileName, System.Boolean isMachineWide) [0x00087] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.Settings.ReadSettings (System.String settingsRoot, System.String settingsPath, System.Boolean isMachineWideSettings) [0x00013] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.Settings.LoadUserSpecificSettings (System.String root, System.String configFileName, System.Boolean useTestingGlobalPath) [0x00053] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs (System.String root, System.String configFileName, System.Collections.Generic.List`1[T] validSettingFiles, NuGet.Configuration.IMachineWideSettings machineWideSettings, System.Boolean loadUserWideSettings, System.Boolean useTestingGlobalPath) [0x00007] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.Settings.LoadSettings (System.String root, System.String configFileName, NuGet.Configuration.IMachineWideSettings machineWideSettings, System.Boolean loadUserWideSettings, System.Boolean useTestingGlobalPath) [0x00072] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.Configuration.Settings.LoadDefaultSettings (System.String root, System.String configFileName, NuGet.Configuration.IMachineWideSettings machineWideSettings) [0x00000] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.CommandLine.Command.Execute () [0x00066] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) [0x001b2] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
##[error]The nuget command failed with exit code(1) and error(NuGet.Config is not valid XML. Path: '/home/az_devops_agent/.config/NuGet/NuGet.Config'.
  Data at the root level is invalid. Line 11, position 1.)
##[error]Packages failed to publish

```
