### ISSUE TITLE
[BUG]: Failed to parse result files: System.UnauthorizedAccessException: Access to the path 

### ISSUE THREAD

**Issue by pimjansen** [microsoft/azure-pipelines-tasks#18842]
### Task name

PublishTestResults@2

### Task version

2

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [x] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Task log

```shell
Starting: Publish Test Results
==============================================================================
Task         : Publish Test Results
Description  : Publish test results to Azure Pipelines
Version      : 2.216.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
==============================================================================
/usr/bin/dotnet --version
7.0.306
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
Failed to parse result files: System.UnauthorizedAccessException: Access to the path '/home/vsts/work/1/s/backend/.build/pest/junit' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ReadFile(String filePath, XmlDocument doc)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFile(TestRunContext runContext, String filePath)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.<>c__DisplayClass1_0.<ParseTestResultFiles>b__0(String file)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFiles(TestRunContext runContext, IList`1 resultFilePaths)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.Parser.ParseFiles(IExecutionContext executionContext, TestRunContext testRunContext, List`1 testResultsFiles, ITestResultParser testResultParser) in /__w/1/s/src/Agent.Worker/TestResults/Parser.cs:line 57
Async Command Start: Publish test results
Async Command End: Publish test results
Finishing: Publish Test Results
```

### Relevant log output

```shell
# Output of an `ls -lah` on both root as log folder:

ls -lah backend/.build/pest

total 16K
drwxr-xr-x 4 vsts docker 4.0K Aug 17 15:01 .
drwxr-xr-x 5 vsts docker 4.0K Aug 17 15:01 ..
drwxr-xr-x 6 vsts docker 4.0K Aug 17 15:01 html
drwxr-xr-x 3 vsts docker 4.0K Aug 17 15:01 junit

ls -lah backend

total 508K
drwxr-xr-x 15 vsts docker 4.0K Aug 17 15:01 .
drwxr-xr-x  6 vsts docker 4.0K Aug 17 15:00 ..
drwxr-xr-x  3 vsts docker 4.0K Aug 17 15:00 .azuredevops
drwxr-xr-x  5 vsts docker 4.0K Aug 17 15:01 .build
drwxr-xr-x  6 vsts docker 4.0K Aug 17 15:00 .docker
-rw-r--r--  1 vsts docker 2.1K Aug 17 15:00 .env
-rw-r--r--  1 vsts docker 2.1K Aug 17 15:00 .env.local
-rw-r--r--  1 vsts docker  215 Aug 17 15:00 .env.test
-rw-r--r--  1 vsts docker  380 Aug 17 15:00 .gitignore
-rw-r--r--  1 vsts docker 5.6K Aug 17 15:00 .php-cs-fixer.dist.php
drwxr-xr-x  8 vsts docker 4.0K Aug 17 15:00 .tasks
-rw-r--r--  1 vsts docker  916 Aug 17 15:00 Dockerfile
-rw-r--r--  1 vsts docker 2.1K Aug 17 15:00 Taskfile.yml
drwxr-xr-x  2 vsts docker 4.0K Aug 17 15:00 bin
-rw-r--r--  1 vsts docker  564 Aug 17 15:00 common-services.yml
-rw-r--r--  1 vsts docker 2.8K Aug 17 15:00 composer.json
-rw-r--r--  1 vsts docker 388K Aug 17 15:00 composer.lock
drwxr-xr-x  4 vsts docker 4.0K Aug 17 15:00 config
-rw-r--r--  1 vsts docker 1.7K Aug 17 15:00 docker-compose.yml
drwxr-xr-x  2 vsts docker 4.0K Aug 17 15:00 migrations
-rw-r--r--  1 vsts docker    0 Aug 17 15:00 phpstan-baseline.neon
-rw-r--r--  1 vsts docker  312 Aug 17 15:00 phpstan.neon
-rw-r--r--  1 vsts docker  536 Aug 17 15:00 phpunit.xml
drwxr-xr-x  3 vsts docker 4.0K Aug 17 15:01 public
drwxr-xr-x  3 vsts docker 4.0K Aug 17 15:00 src
-rw-r--r--  1 vsts docker 6.4K Aug 17 15:00 symfony.lock
drwxr-xr-x  2 vsts docker 4.0K Aug 17 15:00 templates
drwxr-xr-x  4 vsts docker 4.0K Aug 17 15:00 tests
drwxrwxrwx  4 vsts docker 4.0K Aug 17 15:01 var
drwxr-xr-x 37 vsts docker 4.0K Aug 17 15:01 vendor
Finishing: Debug
```

### Aditional info

```shell
- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFiles: backend/.build/pest/junit
  condition: succeeded()
```
```

**Comment by vincenthuxford-enable** [comment]
Encountering this exact issue too, on ubuntu-latest (also tried the older available versions, same behaviour). Have adjusted permissions via chmod (even to allow all access, eg 777) and verified file is accessible but the following stack trace persists.

```bash
2023-08-28T22:42:32.4842007Z ##[section]Starting: Publish Test Results **/reports/test-*.xml
2023-08-28T22:42:32.4847006Z ==============================================================================
2023-08-28T22:42:32.4847137Z Task         : Publish Test Results
2023-08-28T22:42:32.4847202Z Description  : Publish test results to Azure Pipelines
2023-08-28T22:42:32.4847379Z Version      : 2.216.2
2023-08-28T22:42:32.4847438Z Author       : Microsoft Corporation
2023-08-28T22:42:32.4847505Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
2023-08-28T22:42:32.4847611Z ==============================================================================
2023-08-28T22:42:32.7476920Z [command]/usr/bin/dotnet --version
2023-08-28T22:42:33.1100708Z 7.0.400
2023-08-28T22:42:34.0528002Z Result Attachments will be stored in LogStore
2023-08-28T22:42:34.0763432Z Run Attachments will be stored in LogStore
2023-08-28T22:42:34.1154349Z Failed to parse result files: System.UnauthorizedAccessException: Access to the path '/home/vsts/work/r1/a/reports/test-report.xml' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ReadFile(String filePath, XmlDocument doc)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFile(TestRunContext runContext, String filePath)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.<>c__DisplayClass1_0.<ParseTestResultFiles>b__0(String file)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFiles(TestRunContext runContext, IList`1 resultFilePaths)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.Parser.ParseFiles(IExecutionContext executionContext, TestRunContext testRunContext, List`1 testResultsFiles, ITestResultParser testResultParser) in /__w/1/s/src/Agent.Worker/TestResults/Parser.cs:line 57
2023-08-28T22:42:34.1288370Z ##[section]Async Command Start: Publish test results
2023-08-28T22:42:34.1734776Z ##[section]Async Command End: Publish test results
2023-08-28T22:42:34.1735729Z ##[section]Finishing: Publish Test Results **/reports/test-*.xml
```

**Comment by bnachtweh** [comment]
> Encountering this exact issue too, on ubuntu-latest (also tried the older available versions, same behaviour). Have adjusted permissions via chmod (even to allow all access, eg 777) and verified file is accessible but the following stack trace persists.
> 
> ```shell
> 2023-08-28T22:42:32.4842007Z ##[section]Starting: Publish Test Results **/reports/test-*.xml
> 2023-08-28T22:42:32.4847006Z ==============================================================================
> 2023-08-28T22:42:32.4847137Z Task         : Publish Test Results
> 2023-08-28T22:42:32.4847202Z Description  : Publish test results to Azure Pipelines
> 2023-08-28T22:42:32.4847379Z Version      : 2.216.2
> 2023-08-28T22:42:32.4847438Z Author       : Microsoft Corporation
> 2023-08-28T22:42:32.4847505Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
> 2023-08-28T22:42:32.4847611Z ==============================================================================
> 2023-08-28T22:42:32.7476920Z [command]/usr/bin/dotnet --version
> 2023-08-28T22:42:33.1100708Z 7.0.400
> 2023-08-28T22:42:34.0528002Z Result Attachments will be stored in LogStore
> 2023-08-28T22:42:34.0763432Z Run Attachments will be stored in LogStore
> 2023-08-28T22:42:34.1154349Z Failed to parse result files: System.UnauthorizedAccessException: Access to the path '/home/vsts/work/r1/a/reports/test-report.xml' is denied.
>  ---> System.IO.IOException: Permission denied
>    --- End of inner exception stack trace ---
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
>    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
>    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>    at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
>    at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
>    at System.Xml.XmlTextReaderImpl.FinishInitUriString()
>    at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
>    at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
>    at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
>    at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ReadFile(String filePath, XmlDocument doc)
>    at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFile(TestRunContext runContext, String filePath)
>    at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.<>c__DisplayClass1_0.<ParseTestResultFiles>b__0(String file)
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
>    at Microsoft.TeamFoundation.TestClient.PublishTestResults.JUnitResultParser.ParseTestResultFiles(TestRunContext runContext, IList`1 resultFilePaths)
>    at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.Parser.ParseFiles(IExecutionContext executionContext, TestRunContext testRunContext, List`1 testResultsFiles, ITestResultParser testResultParser) in /__w/1/s/src/Agent.Worker/TestResults/Parser.cs:line 57
> 2023-08-28T22:42:34.1288370Z ##[section]Async Command Start: Publish test results
> 2023-08-28T22:42:34.1734776Z ##[section]Async Command End: Publish test results
> 2023-08-28T22:42:34.1735729Z ##[section]Finishing: Publish Test Results **/reports/test-*.xml
> ```

I'm having the same issue. Changing the rights should not be the issue I think. The owner and group are the same and the rights are 755, so it should perfectly be able to read the file, right?

**Comment by pimjansen** [comment]
Indeed, but looking at the time it is open nobody at microsoft seems to bother "again".

**Comment by bnachtweh** [comment]
@pimjansen my issue was that the xml file was actually a directory, because I imported it as an artifact. Artifacts are stored as directory by default. Can you try using a pattern for files? So: `backend/.build/pest/junit/**/*.xml` or `backend/.build/pest/junit/*.xml` for example. I've managed to get it working.
