### ISSUE TITLE
[BUG]: Copy files over SSH task doesn't work for IBM AIX target servers

### ISSUE THREAD

**Issue by Shahyads** [microsoft/azure-pipelines-tasks#18880]
### Task name

Copy files over SSH

### Task version

0.205.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2022.0.1

### Operation system

Windows Server 2019

### Task log

```shell
2023-08-25T14:39:37.3586349Z ##[debug]Evaluating condition for step: 'Securely copy files to the remote machine'
2023-08-25T14:39:37.3588246Z ##[debug]Evaluating: succeeded()
2023-08-25T14:39:37.3588645Z ##[debug]Evaluating succeeded:
2023-08-25T14:39:37.3589466Z ##[debug]=> True
2023-08-25T14:39:37.3590409Z ##[debug]Result: True
2023-08-25T14:39:37.3591237Z ##[section]Starting: Securely copy files to the remote machine
2023-08-25T14:39:37.6339851Z ==============================================================================
2023-08-25T14:39:37.6340020Z Task         : Copy files over SSH
2023-08-25T14:39:37.6340143Z Description  : Copy files or build artifacts to a remote machine over SSH
2023-08-25T14:39:37.6340291Z Version      : 0.205.0
2023-08-25T14:39:37.6340375Z Author       : Microsoft Corporation
2023-08-25T14:39:37.6340451Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh
2023-08-25T14:39:37.6340585Z ==============================================================================
2023-08-25T14:39:37.7367843Z ##[debug]Using node path: E:\TFSAgents\CB-CB-01-SVRD-agent1\externals\node10\bin\node.exe
2023-08-25T14:39:38.2748679Z ##[debug]agent.TempDirectory=E:\TFSAgents\CB-CB-01-SVRD-agent1\_work\_temp
2023-08-25T14:39:38.2825406Z ##[debug]loading inputs and endpoints
2023-08-25T14:39:38.2826329Z ##[debug]loading ENDPOINT_AUTH_431a2cce-b431-4bca-8b3b-443282d528a6
2023-08-25T14:39:38.2827583Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_431a2cce-b431-4bca-8b3b-443282d528a6_PASSWORD
2023-08-25T14:39:38.2836486Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_431a2cce-b431-4bca-8b3b-443282d528a6_USERNAME
2023-08-25T14:39:38.2841076Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2023-08-25T14:39:38.2846989Z ##[debug]loading ENDPOINT_AUTH_SCHEME_431a2cce-b431-4bca-8b3b-443282d528a6
2023-08-25T14:39:38.2852284Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2023-08-25T14:39:38.2857651Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2023-08-25T14:39:38.2864771Z ##[debug]loading INPUT_CLEANHIDDENFILESINTARGET
2023-08-25T14:39:38.2870604Z ##[debug]loading INPUT_CLEANTARGETFOLDER
2023-08-25T14:39:38.2876088Z ##[debug]loading INPUT_CONTENTS
2023-08-25T14:39:38.2880809Z ##[debug]loading INPUT_FAILONEMPTYSOURCE
2023-08-25T14:39:38.2886026Z ##[debug]loading INPUT_FLATTENFOLDERS
2023-08-25T14:39:38.2890897Z ##[debug]loading INPUT_ISWINDOWSONTARGET
2023-08-25T14:39:38.2896687Z ##[debug]loading INPUT_OVERWRITE
2023-08-25T14:39:38.2903741Z ##[debug]loading INPUT_READYTIMEOUT
2023-08-25T14:39:38.2909637Z ##[debug]loading INPUT_SOURCEFOLDER
2023-08-25T14:39:38.2915186Z ##[debug]loading INPUT_SSHENDPOINT
2023-08-25T14:39:38.2920438Z ##[debug]loading INPUT_TARGETFOLDER
2023-08-25T14:39:38.2957141Z ##[debug]loading SECRET_AGENT_PROXYPASSWORD
2023-08-25T14:39:38.2968884Z ##[debug]loaded 19
2023-08-25T14:39:38.2975602Z ##[debug]Agent.ProxyUrl=http://myproxy.mydom:8080
2023-08-25T14:39:38.2976983Z ##[debug]Agent.ProxyUsername=mydomain\mybuildaccount
2023-08-25T14:39:38.2978820Z ##[debug]Agent.ProxyPassword=***
2023-08-25T14:39:38.2979685Z ##[debug]Agent.ProxyBypassList=[""\\.mydomain"]
2023-08-25T14:39:38.2980515Z ##[debug]Agent.TempDirectory=E:\TFSAgents\CB-CB-01-SVRD-agent1\_work\_temp
2023-08-25T14:39:38.3015798Z ##[debug]expose agent proxy configuration.
2023-08-25T14:39:38.3016575Z ##[debug]Agent.CAInfo=E:\TFSAgents\ca-bundle.crt
2023-08-25T14:39:38.3017303Z ##[debug]Agent.ClientCert=undefined
2023-08-25T14:39:38.3017872Z ##[debug]expose agent certificate configuration.
2023-08-25T14:39:38.3018407Z ##[debug]Agent.SkipCertValidation=undefined
2023-08-25T14:39:38.4615229Z ##[debug]check path : E:\TFSAgents\CB-CB-01-SVRD-agent1\_work\_tasks\CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96\0.205.0\task.json
2023-08-25T14:39:38.4618579Z ##[debug]adding resource file: E:\TFSAgents\CB-CB-01-SVRD-agent1\_work\_tasks\CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96\0.205.0\task.json
2023-08-25T14:39:38.4622027Z ##[debug]system.culture=en-US
2023-08-25T14:39:38.4673540Z ##[debug]sshEndpoint=431a2cce-b431-4bca-8b3b-443282d528a6
2023-08-25T14:39:38.4677209Z ##[debug]431a2cce-b431-4bca-8b3b-443282d528a6 auth param username = ***
2023-08-25T14:39:38.4683245Z ##[debug]431a2cce-b431-4bca-8b3b-443282d528a6 auth param password = ***
2023-08-25T14:39:38.4684393Z ##[debug]431a2cce-b431-4bca-8b3b-443282d528a6 data host = 10.53.32.170
2023-08-25T14:39:38.4685409Z ##[debug]431a2cce-b431-4bca-8b3b-443282d528a6 data port = 22
2023-08-25T14:39:38.4690679Z ##[debug]readyTimeout=20000
2023-08-25T14:39:38.4691417Z ##[debug]Using private key for ssh connection.
2023-08-25T14:39:38.4696589Z ##[debug]contents=*.csv
2023-08-25T14:39:38.4702900Z ##[debug]sourceFolder=E:\TFSAgents\CB-CB-01-SVRD-agent1\_work\490\s
2023-08-25T14:39:38.4703544Z ##[debug]check path : E:\TFSAgents\CB-CB-01-SVRD-agent1\_work\490\s
2023-08-25T14:39:38.4709140Z ##[debug]targetFolder=/datahub/ist/BCBJ_WealthETL/target/ghr/blueoptima/
2023-08-25T14:39:38.4715109Z ##[debug]cleanTargetFolder=false
2023-08-25T14:39:38.4720124Z ##[debug]overwrite=true
2023-08-25T14:39:38.4725253Z ##[debug]failOnEmptySource=false
2023-08-25T14:39:38.4729595Z ##[debug]flattenFolders=false
2023-08-25T14:39:38.4762887Z Setting up SSH service connection to remote host 10.53.32.170.
2023-08-25T14:39:38.4858152Z (node:52196) Warning: Use Cipheriv for counter mode of aes-256-ctr
2023-08-25T14:39:38.5665707Z ##[debug]task result: Failed
2023-08-25T14:39:38.5693408Z ##[error]Error: Failed to connect to remote machine. Verify the SSH service connection details. Failed to connect to remote machine. Verify the SSH service connection details. Error: All configured authentication methods failed..
2023-08-25T14:39:38.5700729Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Failed to connect to remote machine. Verify the SSH service connection details. Failed to connect to remote machine. Verify the SSH service connection details. Error: All configured authentication methods failed..
2023-08-25T14:39:38.5708331Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Failed to connect to remote machine. Verify the SSH service connection details. Failed to connect to remote machine. Verify the SSH service connection details. Error: All configured authentication methods failed..
2023-08-25T14:39:38.5709250Z ##[debug]Closing the client connection
2023-08-25T14:39:38.5709725Z ##[debug]Task successfully accomplished
2023-08-25T14:39:38.5800738Z ##[section]Finishing: Securely copy files to the remote machine
```

### Relevant log output

```shell
##[error]Error: Failed to connect to remote machine. Verify the SSH service connection details. Failed to connect to remote machine. Verify the SSH service connection details. Error: All configured authentication methods failed..
```

### Aditional info

```shell
It works perfect for all linux based servers. 
but it doesn't work on the IBM AIX target servers.
```

**Comment by SimonCtl** [comment]
Hi, have you found a solution ?
Looking forward to do the same process soon.

**Comment by krenson** [comment]
Hello, we actually have the same issue with a Solaris machine.

```
##[error]Failed to connect to remote machine. Verify the SSH service connection details. Error: Error: All configured authentication methods failed
    at doNextAuth (/opt/devops/formaccomp/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.226.2/node_modules/ssh2/lib/client.js:803:21)
    at tryNextAuth (/opt/devops/formaccomp/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.226.2/node_modules/ssh2/lib/client.js:993:7)
    at USERAUTH_FAILURE (/opt/devops/formaccomp/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.226.2/node_modules/ssh2/lib/client.js:373:11)
    at 51 (/opt/devops/formaccomp/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.226.2/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)
    at Protocol.onPayload (/opt/devops/formaccomp/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.226.2/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
    at AESGCMDecipherNative.decrypt (/opt/devops/formaccomp/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.226.2/node_modules/ssh2/lib/protocol/crypto.js:987:26)
    at Protocol.parsePacket [as _parse] (/opt/devops/formaccomp/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.226.2/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/opt/devops/formaccomp/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.226.2/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/opt/devops/formaccomp/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.226.2/node_modules/ssh2/lib/client.js:713:21)
    at Socket.emit (node:events:527:28) {
  level: 'client-authentication'

```

Many thanks

Regards

**Comment by NeubauerJohannes** [comment]
We have the same issue on RockyLinux 9 machine

```
##[error]Error: Failed to connect to remote machine. Verify the SSH service connection details. Failed to connect to remote machine. Verify the SSH service connection details. Error: All configured authentication methods failed
    at doNextAuth (/azp/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.231.1/node_modules/ssh2/lib/client.js:802:21)
    at tryNextAuth (/azp/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.231.1/node_modules/ssh2/lib/client.js:992:7)
    at USERAUTH_FAILURE (/azp/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.231.1/node_modules/ssh2/lib/client.js:373:11)
    at 51 (/azp/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.231.1/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)
    at Protocol.onPayload (/azp/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.231.1/node_modules/ssh2/lib/protocol/Protocol.js:2024:10)
    at AESGCMDecipherNative.decrypt (/azp/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.231.1/node_modules/ssh2/lib/protocol/crypto.js:992:26)
    at Protocol.parsePacket [as _parse] (/azp/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.231.1/node_modules/ssh2/lib/protocol/Protocol.js:1993:25)
    at Protocol.parse (/azp/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.231.1/node_modules/ssh2/lib/protocol/Protocol.js:292:16)
    at Socket.<anonymous> (/azp/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.231.1/node_modules/ssh2/lib/client.js:712:21)
    at Socket.emit (node:events:513:28) {
  level: 'client-authentication'
}..
```

**Comment by Shahyads** [comment]
Any update?
