### ISSUE TITLE
[BUG]: Docker@2 throws "docker inspect" requires at least 1 argument.

### ISSUE THREAD

**Issue by KristofKuli** [microsoft/azure-pipelines-tasks#19045]
### Task name

Docker

### Task version

2.221.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Task log

```shell
/usr/bin/docker history --format createdAt:{{.CreatedAt}}; layerSize:{{.Size}}; createdBy:{{.CreatedBy}}; layerId:{{.ID}} --no-trunc ***/sr-grp-db:master-14.1.0
createdAt:2023-09-27T06:43:56Z; layerSize:0B; createdBy:CMD ["-?"]; layerId:sha256:aceeb39d9204ce5ee8cb7d4a9076e1a8a6e59db1193e5de1e54dd0b985d58dc7
createdAt:2023-09-27T06:43:56Z; layerSize:0B; createdBy:ENTRYPOINT ["flyway"]; layerId:<missing>
createdAt:2023-09-27T06:43:56Z; layerSize:31.2kB; createdBy:COPY sr-grp-db/flyway_postgres sql # buildkit; layerId:<missing>
createdAt:2023-09-27T06:43:56Z; layerSize:0B; createdBy:WORKDIR /flyway; layerId:<missing>
createdAt:2023-09-27T06:43:56Z; layerSize:0B; createdBy:USER flyway; layerId:<missing>
createdAt:2023-09-27T06:43:56Z; layerSize:169kB; createdBy:RUN /bin/sh -c keytool -noprompt -import -trustcacerts -alias -file /tmp/ca22.crt -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts # buildkit; layerId:<missing>
createdAt:2023-09-27T06:43:55Z; layerSize:167kB; createdBy:RUN /bin/sh -c keytool -noprompt -import -trustcacerts -alias -file /tmp/ca2.crt -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts # buildkit; layerId:<missing>
createdAt:2023-09-27T06:43:55Z; layerSize:0B; createdBy:USER root; layerId:<missing>
createdAt:2021-02-22T15:23:54Z; layerSize:0B; createdBy:/bin/sh -c #(nop)  CMD ["-?"]; layerId:<missing>
createdAt:2021-02-22T15:23:54Z; layerSize:0B; createdBy:/bin/sh -c #(nop)  ENTRYPOINT ["flyway"]; layerId:<missing>
createdAt:2021-02-22T15:23:54Z; layerSize:0B; createdBy:/bin/sh -c #(nop)  ENV PATH=/flyway:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin; layerId:<missing>
createdAt:2021-02-22T15:23:53Z; layerSize:63.3MB; createdBy:/bin/sh -c wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}.tar.gz   && tar -xzf flyway-commandline-${FLYWAY_VERSION}.tar.gz   && mv flyway-${FLYWAY_VERSION}/* .   && rm flyway-commandline-${FLYWAY_VERSION}.tar.gz; layerId:<missing>
createdAt:2021-02-22T15:23:49Z; layerSize:0B; createdBy:/bin/sh -c #(nop)  ENV FLYWAY_VERSION=7.5.4; layerId:<missing>
createdAt:2021-02-22T15:23:49Z; layerSize:0B; createdBy:/bin/sh -c #(nop)  USER flyway; layerId:<missing>
createdAt:2021-02-22T15:23:48Z; layerSize:0B; createdBy:/bin/sh -c #(nop) WORKDIR /flyway; layerId:<missing>
createdAt:2021-02-22T15:23:48Z; layerSize:4.67kB; createdBy:/bin/sh -c addgroup flyway     && adduser -S -h /flyway -D -G flyway flyway; layerId:<missing>
createdAt:2021-02-22T15:23:47Z; layerSize:2.68MB; createdBy:/bin/sh -c apk --no-cache add --update bash openssl; layerId:<missing>
createdAt:2021-02-21T19:31:24Z; layerSize:0B; createdBy:/bin/sh -c #(nop)  ENV JAVA_HOME=/opt/java/openjdk PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin; layerId:<missing>
createdAt:2021-02-21T19:31:21Z; layerSize:130MB; createdBy:/bin/sh -c set -eux;     apk add --no-cache --virtual .fetch-deps curl;     ARCH="$(apk --print-arch)";     case "${ARCH}" in        aarch64|arm64)          ESUM='5f9a894bd694f598f2befa4a605169685ac8bcb8ec68d25e587e8db4d2307b74';          BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jre_aarch64_linux_hotspot_11.0.10_9.tar.gz';          ;;        armhf|armv7l)          ESUM='2f2da2149c089c84f00b0eda63c31b77c8b51a1c080e18a70ecb5a78ba40d8c6';          BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jre_arm_linux_hotspot_11.0.10_9.tar.gz';          ;;        ppc64el|ppc64le)          ESUM='d269b646af32eb41d74b3a5259f634921a063c67642ab5c227142463824b2a6d';          BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jre_ppc64le_linux_hotspot_11.0.10_9.tar.gz';          ;;        s390x)          ESUM='2c9ec28b10bf1628b20a157c746988f323e0dcbf1053b616aa6593923e3a70df';          BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jre_s390x_linux_hotspot_11.0.10_9.tar.gz';          ;;        amd64|x86_64)          ESUM='25fdcf9427095ac27c8bdfc82096ad2e615693a3f6ea06c700fca7ffb271131a';          BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jre_x64_linux_hotspot_11.0.10_9.tar.gz';          ;;        *)          echo "Unsupported arch: ${ARCH}";          exit 1;          ;;     esac;     curl -LfsSo /tmp/openjdk.tar.gz ${BINARY_URL};     echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -;     mkdir -p /opt/java/openjdk;     cd /opt/java/openjdk;     tar -xf /tmp/openjdk.tar.gz --strip-components=1;     apk del --purge .fetch-deps;     rm -rf /var/cache/apk/*;     rm -rf /tmp/openjdk.tar.gz;; layerId:<missing>
createdAt:2021-02-21T19:31:11Z; layerSize:0B; createdBy:/bin/sh -c #(nop)  ENV JAVA_VERSION=jdk-11.0.10+9; layerId:<missing>
createdAt:2021-02-21T19:31:10Z; layerSize:14.2MB; createdBy:/bin/sh -c apk add --no-cache tzdata --virtual .build-deps curl binutils zstd     && GLIBC_VER="2.31-r0"     && ALPINE_GLIBC_REPO="https://github.com/sgerrand/alpine-pkg-glibc/releases/download"     && GCC_LIBS_URL="https://archive.archlinux.org/packages/g/gcc-libs/gcc-libs-10.1.0-2-x86_64.pkg.tar.zst"     && GCC_LIBS_SHA256="f80320a03ff73e82271064e4f684cd58d7dbdb07aa06a2c4eea8e0f3c507c45c"     && ZLIB_URL="https://archive.archlinux.org/packages/z/zlib/zlib-1%3A1.2.11-3-x86_64.pkg.tar.xz"     && ZLIB_SHA256=17aede0b9f8baa789c5aa3f358fbf8c68a5f1228c5e6cba1a5dd34102ef4d4e5     && curl -LfsS https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub -o /etc/apk/keys/sgerrand.rsa.pub     && SGERRAND_RSA_SHA256="823b54589c93b02497f1ba4dc622eaef9c813e6b0f0ebbb2f771e32adf9f4ef2"     && echo "${SGERRAND_RSA_SHA256} */etc/apk/keys/sgerrand.rsa.pub" | sha256sum -c -     && curl -LfsS ${ALPINE_GLIBC_REPO}/${GLIBC_VER}/glibc-${GLIBC_VER}.apk > /tmp/glibc-${GLIBC_VER}.apk     && apk add --no-cache /tmp/glibc-${GLIBC_VER}.apk     && curl -LfsS ${ALPINE_GLIBC_REPO}/${GLIBC_VER}/glibc-bin-${GLIBC_VER}.apk > /tmp/glibc-bin-${GLIBC_VER}.apk     && apk add --no-cache /tmp/glibc-bin-${GLIBC_VER}.apk     && curl -Ls ${ALPINE_GLIBC_REPO}/${GLIBC_VER}/glibc-i18n-${GLIBC_VER}.apk > /tmp/glibc-i18n-${GLIBC_VER}.apk     && apk add --no-cache /tmp/glibc-i18n-${GLIBC_VER}.apk     && /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 "$LANG" || true     && echo "export LANG=$LANG" > /etc/profile.d/locale.sh     && curl -LfsS ${GCC_LIBS_URL} -o /tmp/gcc-libs.tar.zst     && echo "${GCC_LIBS_SHA256} */tmp/gcc-libs.tar.zst" | sha256sum -c -     && mkdir /tmp/gcc     && zstd -d /tmp/gcc-libs.tar.zst --output-dir-flat /tmp     && tar -xf /tmp/gcc-libs.tar -C /tmp/gcc     && mv /tmp/gcc/usr/lib/libgcc* /tmp/gcc/usr/lib/libstdc++* /usr/glibc-compat/lib     && strip /usr/glibc-compat/lib/libgcc_s.so.* /usr/glibc-compat/lib/libstdc++.so*     && curl -LfsS ${ZLIB_URL} -o /tmp/libz.tar.xz     && echo "${ZLIB_SHA256} */tmp/libz.tar.xz" | sha256sum -c -     && mkdir /tmp/libz     && tar -xf /tmp/libz.tar.xz -C /tmp/libz     && mv /tmp/libz/usr/lib/libz.so* /usr/glibc-compat/lib     && apk del --purge .build-deps glibc-i18n     && rm -rf /tmp/*.apk /tmp/gcc /tmp/gcc-libs.tar* /tmp/libz /tmp/libz.tar.xz /var/cache/apk/*; layerId:<missing>
createdAt:2021-02-21T19:31:02Z; layerSize:0B; createdBy:/bin/sh -c #(nop)  ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8; layerId:<missing>
createdAt:2020-12-17T00:19:42Z; layerSize:0B; createdBy:/bin/sh -c #(nop)  CMD ["/bin/sh"]; layerId:<missing>
createdAt:2020-12-17T00:19:41Z; layerSize:5.57MB; createdBy:/bin/sh -c #(nop) ADD file:ec475c2abb2d46435286b5ae5efacf5b50b1a9e3b6293b69db3c0172b5b9658b in / ; layerId:<missing>
/usr/bin/docker inspect -f {{.RootFS.Layers}}
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
##[error]"docker inspect" requires at least 1 argument.
##[error]See 'docker inspect --help'.
##[error]Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]
##[error]Return low-level information on Docker objects
Finishing: Docker Build and Push
```

### Relevant log output

```shell
/usr/bin/docker inspect -f {{.RootFS.Layers}}
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
##[error]"docker inspect" requires at least 1 argument.
##[error]See 'docker inspect --help'.
##[error]Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]
##[error]Return low-level information on Docker objects
Finishing: Docker Build and Push
```

### Aditional info

```shell
As you can see, the layerID is missing from every step (layerId:<missing>), therefore the docker inspect command is failing. This is happening during docker push. During docker build the log says that the Docker version is "19.03.8", however the agent has 24.0.5 installed. Is this task tied to a specific Docker version? Please be aware that if execute the docker push in a simple bash task, we don't get this error.
```

**Comment by KristofKuli** [comment]
Hi,
Can someone check this issue?
Thanks

**Comment by sql-dr-watson** [comment]
I am getting the same issue

**Comment by KristofKuli** [comment]
Issue seems to be resolved in task version 2.231.0.

**Comment by AvinashPamula** [comment]
can you tell me how you resolved the issue and also what command did you used

**Comment by davewilton** [comment]
I am still getting this issue with version  2.243.0. This is when pushing to Google Cloud Platform container registry.

If I use the task 'buildAndpush' it works fine. If I use a command line it works fine. So this is definitely an issue with the azure pipeline task. Oddly I have another task running in the pipeline which publishes my server and that one works fine (both running in Ubuntu-latest pipeline images).

My workaround for now is just to run the cmd
```

  - task: CmdLine@2
    displayName: 'push to GCP'
    inputs:
      script: docker  push eu.gcr.io/${{parameters.projectID}}//${{parameters.serviceName}}:$(tag)

```
```

##[error]"docker inspect" requires at least 1 argument.
##[error]See 'docker inspect --help'.
##[error]Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]
##[error]Return low-level information on Docker objects
##[error]Unhandled: The process '/usr/bin/docker' failed with exit code 1
##[error]Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/vsts/work/_tasks/Docker_e28912f1-0114-4464-802a-a3a35437fd16/2.243.0/node_modules/azure-pipelines-task-lib/toolrunner.js:1249:25)
    at ExecState.CheckComplete (/home/vsts/work/_tasks/Docker_e28912f1-0114-4464-802a-a3a35437fd16/2.243.0/node_modules/azure-pipelines-task-lib/toolrunner.js:1232:18)
    at ChildProcess.<anonymous> (/home/vsts/work/_tasks/Docker_e28912f1-0114-4464-802a-a3a35437fd16/2.243.0/node_modules/azure-pipelines-task-lib/toolrunner.js:1160:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)


```
