### ISSUE TITLE
Automated Test Aborts when executed from test plan

### ISSUE THREAD

**Issue by Sam7son** [microsoft/azure-pipelines-tasks#19222]
### Task name

VsTest - testRun

### Task version

2.x

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows

### Question

```shell
I have dotnet core project with a few xunit test & few specflow test. these tests are triggered from the testplan. but the task getting failed and aborted with below message

-----------------------------------------------------------------------------------------------
2023-11-04T12:53:34.7839929Z [RunStatistics]This execution slice with id '5', received '1' testcases to execute out of which '0' is discovered.
2023-11-04T12:53:34.7916290Z List of test cases in slice with id: 5
2023-11-04T12:53:34.7917022Z Source: mytest.dll, FullyQualifiedTestName: mytest.MyTestClass.Test1
2023-11-04T12:53:34.8417236Z ##[error]ExecutionAndPublish.Run : Microsoft.VisualStudio.TestService.VstestAdapter.TestsNotFoundException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2023-11-04T12:53:34.8430487Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken)
2023-11-04T12:53:34.8432567Z    at Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken)
2023-11-04T12:53:34.8438693Z ##[error]The slice of type 'Execution' is 'Aborted' because of the error : Microsoft.VisualStudio.TestService.VstestAdapter.TestsNotFoundException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2023-11-04T12:53:34.8442851Z    at Microsoft.VisualStudio.TestService.VstestAdapter.Execution.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken)
2023-11-04T12:53:34.8445089Z    at 
Microsoft.VisualStudio.TestService.VstestAdapter.ExecutionAndPublish.Run(ExecutionStateContext stateModelContext, CancellationToken cancellationToken)
2023-11-04T12:53:44.6884889Z Received the command : Stop
2023-11-04T12:53:44.6885879Z TestExecutionHost.ProcessCommand. Stop Command handled
2023-11-04T12:53:44.6890841Z SliceFetch Aborted. Moving to the TestHostEnd phase
-----------------------------------------------------------------------------------------------

Tried with different Windows agents, same result
Tried with a few different test platform versions, same result

Able to execute those tests in the local machine without any issues using the dotnet test command.
```

**Comment by sailesh89** [comment]
I got the same issue. Seems like its happening since the update to VSTest task to 2.229.0. the last successful run in our pipelines how the version as 2.228.0 WE are using VMSS pool. i am also able to reproduce this in Microsoft hosted agents as well. This is happening when we run custom tests from a plan using Test run.
