### ISSUE TITLE
[BUG]: IISWebAppDeploymentOnMachineGroup not working with regular expressions after 0.230.0

### ISSUE THREAD

**Issue by penihel** [microsoft/azure-pipelines-tasks#19220]
### Task name

IISWebAppDeploymentOnMachineGroup 

### Task version

0.230.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Task log

```shell
2023-11-03T13:45:53.5794584Z ##[section]Starting: Deploy - /auditoria
2023-11-03T13:45:53.5911812Z ==============================================================================
2023-11-03T13:45:53.5912164Z Task         : IIS web app deploy
2023-11-03T13:45:53.5912459Z Description  : Deploy a website or web application using Web Deploy
2023-11-03T13:45:53.5912760Z Version      : 0.230.0
2023-11-03T13:45:53.5912990Z Author       : Microsoft Corporation
2023-11-03T13:45:53.5913355Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
2023-11-03T13:45:53.5913785Z ==============================================================================
2023-11-03T13:45:53.9953594Z [command]C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\7zip\7zip\7z.exe x -oC:\azagent\A1\_work\_temp\temp_web_package_9276827749342635 C:\azagent\A1\_work\r1\a\IMPLANTANET\Auditoria\Implanta.Auditoria.MvcApplication.zip
2023-11-03T13:45:54.0169837Z 
2023-11-03T13:45:54.0170931Z 7-Zip [64] 16.00 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-10
2023-11-03T13:45:54.0171246Z 
2023-11-03T13:45:54.0171541Z Scanning the drive for archives:
2023-11-03T13:45:54.0171876Z 1 file, 24323816 bytes (24 MiB)
2023-11-03T13:45:54.0172014Z 
2023-11-03T13:45:54.0172391Z Extracting archive: C:\azagent\A1\_work\r1\a\IMPLANTANET\Auditoria\Implanta.Auditoria.MvcApplication.zip
2023-11-03T13:45:55.0714042Z --
2023-11-03T13:45:55.0714661Z Path = C:\azagent\A1\_work\r1\a\IMPLANTANET\Auditoria\Implanta.Auditoria.MvcApplication.zip
2023-11-03T13:45:55.0715079Z Type = zip
2023-11-03T13:45:55.0715372Z Physical Size = 24323816
2023-11-03T13:45:55.0715504Z 
2023-11-03T13:45:55.0715784Z Everything is Ok
2023-11-03T13:45:55.0715905Z 
2023-11-03T13:45:55.0716144Z Folders: 66
2023-11-03T13:45:55.0716407Z Files: 368
2023-11-03T13:45:55.0716670Z Size:       104840077
2023-11-03T13:45:55.0716948Z Compressed: 24323816
2023-11-03T13:45:55.1940001Z ConnectionString attributes in Web.config is parameterized by default. Note that the transformation has no effect on connectionString attributes as the value is overridden during deployment by 'Parameters.xml or 'SetParameters.xml' files. You can disable the auto-parameterization by setting /p:AutoParameterizationWebConfigConnectionStrings=False during MSBuild package generation.
2023-11-03T13:45:55.2571841Z ##[warning]Unable to apply transformation for the given package. Verify the following.
2023-11-03T13:45:55.2573967Z ##[warning]1. Whether the Transformation is already applied for the MSBuild generated package during build. If yes, remove the <DependentUpon> tag for each config in the csproj file and rebuild. 
2023-11-03T13:45:55.2575912Z ##[warning]2. Ensure that the config file and transformation files are present in the same folder inside the package.
2023-11-03T13:45:55.3563772Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\ApplicationInsights.config
2023-11-03T13:45:55.3645512Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\ApplicationInsights.config
2023-11-03T13:45:55.3647435Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Areas\Auditoria\Views\web.config
2023-11-03T13:45:55.3678416Z Processing substitution for xml node : appSettings
2023-11-03T13:45:55.3682273Z Processing substitution for xml node : configSections
2023-11-03T13:45:55.3693025Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Areas\Auditoria\Views\web.config
2023-11-03T13:45:55.3696474Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Areas\Cadastro\Views\web.config
2023-11-03T13:45:55.3703690Z Processing substitution for xml node : appSettings
2023-11-03T13:45:55.3705053Z Processing substitution for xml node : configSections
2023-11-03T13:45:55.3709700Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Areas\Cadastro\Views\web.config
2023-11-03T13:45:55.3711313Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Areas\Report\Views\web.config
2023-11-03T13:45:55.3718722Z Processing substitution for xml node : appSettings
2023-11-03T13:45:55.3720053Z Processing substitution for xml node : configSections
2023-11-03T13:45:55.3726270Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Areas\Report\Views\web.config
2023-11-03T13:45:55.3728922Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Areas\Sistema\Views\web.config
2023-11-03T13:45:55.3737968Z Processing substitution for xml node : appSettings
2023-11-03T13:45:55.3739307Z Processing substitution for xml node : configSections
2023-11-03T13:45:55.3744312Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Areas\Sistema\Views\web.config
2023-11-03T13:45:55.3745308Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\SysDataBase.config
2023-11-03T13:45:55.3754407Z Processing substitution for xml node : connectionStrings
2023-11-03T13:45:55.3778217Z Config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\SysDataBase.config updated.
2023-11-03T13:45:55.3779540Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\SysServiceBehaviors.config
2023-11-03T13:45:55.4094629Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\SysServiceBehaviors.config
2023-11-03T13:45:55.4096411Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\SysServiceBinding.config
2023-11-03T13:45:55.4127506Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\SysServiceBinding.config
2023-11-03T13:45:55.4128511Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\SysServiceClient.config
2023-11-03T13:45:55.4354799Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\SysServiceClient.config
2023-11-03T13:45:55.4357062Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Views\web.config
2023-11-03T13:45:55.4699208Z Processing substitution for xml node : appSettings
2023-11-03T13:45:55.4700584Z Processing substitution for xml node : configSections
2023-11-03T13:45:55.4708250Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Views\web.config
2023-11-03T13:45:55.4710543Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Web.config
2023-11-03T13:45:55.5459301Z Processing substitution for xml node : appSettings
2023-11-03T13:45:55.5464529Z Updating value for key= Producao with token value: CONFIG_FILE_SETTINGS_TOKEN(Producao)
2023-11-03T13:45:55.5465371Z Updating value for key= ForceSSL with token value: CONFIG_FILE_SETTINGS_TOKEN(ForceSSL)
2023-11-03T13:45:55.5467797Z Updating value for key= BuildName with token value: CONFIG_FILE_SETTINGS_TOKEN(BuildName)
2023-11-03T13:45:55.5468569Z Updating value for key= ShowInfoBuild with token value: CONFIG_FILE_SETTINGS_TOKEN(ShowInfoBuild)
2023-11-03T13:45:55.5469522Z Updating value for key= aiConnectionString with token value: CONFIG_FILE_SETTINGS_TOKEN(aiConnectionString)
2023-11-03T13:45:55.5470356Z Processing substitution for xml node : connectionStrings
2023-11-03T13:45:55.5471147Z Processing substitution for xml node : configSections
2023-11-03T13:45:55.5500336Z Config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\Web.config updated.
2023-11-03T13:45:55.5501828Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\bin\Implanta.Common.ArquivosAnexos.AzureStorage.dll.config
2023-11-03T13:45:55.5512198Z Skipped Updating file: C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\bin\Implanta.Common.ArquivosAnexos.AzureStorage.dll.config
2023-11-03T13:45:55.5513201Z Initiated variable substitution in config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\bin\SysDataBase.config
2023-11-03T13:45:55.5517585Z Processing substitution for xml node : connectionStrings
2023-11-03T13:45:55.5528027Z Config file : C:\azagent\A1\_work\_temp\temp_web_package_9276827749342635\Content\C_C\a\2\s\src\Auditoria\Implanta.Auditoria.MvcApplication\obj\Release\Package\PackageTmp\bin\SysDataBase.config updated.
2023-11-03T13:45:55.5528691Z XML variable substitution applied successfully.
2023-11-03T13:45:58.5865541Z [command]"C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A1\_work\r1\a\temp_web_package_061461094123006044.zip' -dest:auto -setParam:name='IIS Web Application Name',value='cau-sp.***.net.br/auditoria' -skip:Directory=App_Data -skip:Directory=(^servico$|^api$)
2023-11-03T13:45:58.6221729Z Error: The process 'C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 255
2023-11-03T13:45:58.6223240Z     at ExecState._setResult (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-03T13:45:58.6225635Z     at ExecState.CheckComplete (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-03T13:45:58.6226595Z     at ChildProcess.<anonymous> (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-03T13:45:58.6227264Z     at ChildProcess.emit (events.js:198:13)
2023-11-03T13:45:58.6227646Z     at maybeClose (internal/child_process.js:982:16)
2023-11-03T13:45:58.6228060Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2023-11-03T13:45:58.6228443Z Retrying to deploy the package.
2023-11-03T13:45:58.6364467Z [command]"C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A1\_work\r1\a\temp_web_package_061461094123006044.zip' -dest:auto -setParam:name='IIS Web Application Name',value='cau-sp.***.net.br/auditoria' -skip:Directory=App_Data -skip:Directory=(^servico$|^api$)
2023-11-03T13:45:58.6602323Z Error: The process 'C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 255
2023-11-03T13:45:58.6603442Z     at ExecState._setResult (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-03T13:45:58.6604440Z     at ExecState.CheckComplete (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-03T13:45:58.6605358Z     at ChildProcess.<anonymous> (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-03T13:45:58.6605992Z     at ChildProcess.emit (events.js:198:13)
2023-11-03T13:45:58.6606393Z     at maybeClose (internal/child_process.js:982:16)
2023-11-03T13:45:58.6606808Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2023-11-03T13:45:58.6607478Z Retrying to deploy the package.
2023-11-03T13:45:58.6617391Z [command]"C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A1\_work\r1\a\temp_web_package_061461094123006044.zip' -dest:auto -setParam:name='IIS Web Application Name',value='cau-sp.***.net.br/auditoria' -skip:Directory=App_Data -skip:Directory=(^servico$|^api$)
2023-11-03T13:45:58.6827195Z ##[error]Failed to deploy web package to IIS website.
2023-11-03T13:45:58.6848686Z ##[error]'api$)' is not recognized as an internal or external command,
operable program or batch file.

2023-11-03T13:45:58.7085651Z ##[error]Error: The process 'C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 255
2023-11-03T13:45:58.7240116Z ##[section]Finishing: Deploy - /auditoria
```

### Relevant log output

```shell
2023-11-03T13:45:58.5865541Z [command]"C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A1\_work\r1\a\temp_web_package_061461094123006044.zip' -dest:auto -setParam:name='IIS Web Application Name',value='cau-sp.***.net.br/auditoria' -skip:Directory=App_Data -skip:Directory=(^servico$|^api$)
2023-11-03T13:45:58.6221729Z Error: The process 'C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 255
2023-11-03T13:45:58.6223240Z     at ExecState._setResult (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-03T13:45:58.6225635Z     at ExecState.CheckComplete (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-03T13:45:58.6226595Z     at ChildProcess.<anonymous> (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-03T13:45:58.6227264Z     at ChildProcess.emit (events.js:198:13)
2023-11-03T13:45:58.6227646Z     at maybeClose (internal/child_process.js:982:16)
2023-11-03T13:45:58.6228060Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)


2023-11-03T13:45:58.6848686Z ##[error]'api$)' is not recognized as an internal or external command,
```

### Aditional info

```shell
When we use a regular expression in the "skip" parameter, the character "|" is probably used. pipe generates the error.

Until the previous version, it worked

Look the YML


steps:
- task: IISWebAppDeploymentOnMachineGroup@0
  displayName: 'Deploy -'
  inputs:
    WebSiteName: '$(WebSiteName)'
    VirtualApplication: auditoria
    Package: '$(System.DefaultWorkingDirectory)/IMPLANTANET/Auditoria/Implanta.Auditoria.MvcApplication.zip'
    RemoveAdditionalFilesFlag: true
    ExcludeFilesFromAppDataFlag: true
    AdditionalArguments: '-skip:Directory=(^servico$|^api$)'
    XmlTransformation: true
    XmlVariableSubstitution: true
```

**Comment by v-mohithgc** [comment]
Hi, maybe, if possible, you can try to add this variable "AGENT_USE_NODE10=true"

**Comment by JuanCruzTrinidad** [comment]
Hello, we have the same issue. Do you know if the way regex is interpreted will be corrected? Or should we modify our regular expression ourselves?
I'll provide the example expression we use: ".keepAlive.*asp(x)?(_PRUEBA_INTERNA)?$|.*newrelic.config$|.*ads.txt$|.*app-ads.txt$"
