### ISSUE TITLE
[BUG]: A '-dest' argument must be specified with the 'sync' verb.

### ISSUE THREAD

**Issue by TrevorFourie** [microsoft/azure-pipelines-tasks#19254]
### Task name

IIS web app deploy

### Task version

0.230.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2019/2022

### Task log

```shell
2023-11-08T15:25:24.6390044Z ##[section]Starting: Deploy Master Website
2023-11-08T15:25:24.8786573Z ==============================================================================
2023-11-08T15:25:24.8786962Z Task         : IIS web app deploy
2023-11-08T15:25:24.8787280Z Description  : Deploy a website or web application using Web Deploy
2023-11-08T15:25:24.8787598Z Version      : 0.230.0
2023-11-08T15:25:24.8787854Z Author       : Microsoft Corporation
2023-11-08T15:25:24.8788273Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
2023-11-08T15:25:24.8788775Z ==============================================================================
2023-11-08T15:25:29.5446503Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:30.2377991Z Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:30.2381018Z     at ExecState._setResult (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-08T15:25:30.2403607Z     at ExecState.CheckComplete (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-08T15:25:30.2413425Z     at ChildProcess.<anonymous> (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-08T15:25:30.2426387Z     at ChildProcess.emit (node:events:527:28)
2023-11-08T15:25:30.2430939Z     at maybeClose (node:internal/child_process:1092:16)
2023-11-08T15:25:30.2432266Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-11-08T15:25:30.2433519Z     at Process.callbackTrampoline (node:internal/async_hooks:130:17)
2023-11-08T15:25:30.2435088Z Retrying to deploy the package.
2023-11-08T15:25:30.2458513Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:30.9353956Z Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:30.9356159Z     at ExecState._setResult (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-08T15:25:30.9357950Z     at ExecState.CheckComplete (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-08T15:25:30.9359539Z     at ChildProcess.<anonymous> (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-08T15:25:30.9361275Z     at ChildProcess.emit (node:events:527:28)
2023-11-08T15:25:30.9361947Z     at maybeClose (node:internal/child_process:1092:16)
2023-11-08T15:25:30.9364818Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-11-08T15:25:30.9365676Z     at Process.callbackTrampoline (node:internal/async_hooks:130:17)
2023-11-08T15:25:30.9366295Z Retrying to deploy the package.
2023-11-08T15:25:30.9386202Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\ Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:31.6161495Z ##[error]Failed to deploy web package to IIS website.
2023-11-08T15:25:31.6176104Z ##[error]Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
'All' is not recognized as an internal or external command,
operable program or batch file.

2023-11-08T15:25:31.7174337Z ##[error]Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:31.8731989Z ##[section]Finishing: Deploy Master Website
```

### Relevant log output

```shell
2023-11-09T10:47:06.2927659Z [command]"C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A1\_work\r121\a\EMS Web & All Databases\EMS Web\EMSWebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/UAT' -enableRule:DoNotDeleteRule
2023-11-09T10:47:06.9209269Z ##[error]Failed to deploy web package to IIS website.
2023-11-09T10:47:06.9219656Z ##[error]Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
'All' is not recognized as an internal or external command,
operable program or batch file.

2023-11-09T10:47:06.9866341Z ##[error]Error: The process 'C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
```

### Aditional info

```shell
Pipelines have not been changed, nor any server changes.

I have tried to encase the Package Folder in Quatation marks with the same result.

The only thing that seems to work is to remove any special characters like '&' from the Build Artifact Source Alias
```

**Comment by jledgett** [comment]
I am also encountering this issue.

**Comment by JackTNeely** [comment]
I am seeing the same issue with IISWebAppDeploymentOnMachineGroup@0 task version 0.230.0. 

Deployments have started failing for source packages that contain an ampersand (&) in the file path. 
This issue did/does not occur with previous IISWebAppDeploymentOnMachineGroup@0 task versions.

Log file error:
A '-dest' argument must be specified with the 'sync'

2023-11-14T21:24:46.7536559Z ##[error]Failed to deploy web package to IIS website.
2023-11-14T21:24:46.7547686Z ##[debug]Processed: ##vso[task.issue type=error;]Failed to deploy web package to IIS website.
2023-11-14T21:24:46.7548834Z ##[debug]{}
2023-11-14T21:24:46.7549716Z ##[debug]System.DefaultWorkingDirectory=C:\azagent\A1\_work\r1\a
2023-11-14T21:24:46.7551433Z ##[error]Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
The system cannot find the path specified.

**Comment by karl-dickman-icf** [comment]
I am affected by this bug as well. The last successful deployment using this task was October 25. I tried deploying the exact same build today and got an error.
```
2023-11-16T21:11:08.9313341Z ##[debug]C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe arg: ["-verb:sync","-source:package='D:\\a\\r1\\a\\_ecosystems-test & ecosystems\\drop\\Web.zip'","-dest:auto,ComputerName='https://-test.scm.azurewebsites.net:443/msdeploy.axd?site=ecosystems',UserName='$',Password='***',AuthType='Basic'","-setParam:name='IIS Web Application Name',value=''","-enableRule:DoNotDeleteRule","-userAgent:VSTS_8a7e5186-1f2d-497c-824a-3e3033fc674d_Release__5940_9642_2"]
2023-11-16T21:11:08.9317403Z ##[debug]exec tool: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe
2023-11-16T21:11:08.9318614Z ##[debug]exec tool: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe
2023-11-16T21:11:08.9319910Z ##[debug]arguments:
2023-11-16T21:11:08.9321362Z ##[debug]arguments:
2023-11-16T21:11:08.9321979Z ##[debug]   -verb:sync
2023-11-16T21:11:08.9322491Z ##[debug]   -verb:sync
2023-11-16T21:11:08.9323300Z ##[debug]   -source:package='D:\a\r1\a\_ecosystems-test & ecosystems\drop\Web.zip'
2023-11-16T21:11:08.9328850Z ##[debug]   -source:package='D:\a\r1\a\_ecosystems-test & ecosystems\drop\Web.zip'
2023-11-16T21:11:08.9331187Z ##[debug]   -dest:auto,ComputerName='https://-test.scm.azurewebsites.net:443/msdeploy.axd?site=',UserName='$',Password='***',AuthType='Basic'
2023-11-16T21:11:08.9333798Z ##[debug]   -dest:auto,ComputerName='https://-test.scm.azurewebsites.net:443/msdeploy.axd?site=',UserName='$',Password='***',AuthType='Basic'
2023-11-16T21:11:08.9335405Z ##[debug]   -setParam:name='IIS Web Application Name',value=''
2023-11-16T21:11:08.9336344Z ##[debug]   -setParam:name='IIS Web Application Name',value=''
2023-11-16T21:11:08.9337155Z ##[debug]   -enableRule:DoNotDeleteRule
2023-11-16T21:11:08.9337780Z ##[debug]   -enableRule:DoNotDeleteRule
2023-11-16T21:11:08.9338634Z ##[debug]   -userAgent:VSTS_8a7e5186-1f2d-497c-824a-3e3033fc674d_Release__5940_9642_2
2023-11-16T21:11:08.9339742Z ##[debug]   -userAgent:VSTS_8a7e5186-1f2d-497c-824a-3e3033fc674d_Release__5940_9642_2
2023-11-16T21:11:08.9345112Z [command]"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package='D:\a\r1\a\_ecosystems-test & ecosystems\drop\Web.zip' -dest:auto,ComputerName='https://-test.scm.azurewebsites.net:443/msdeploy.axd?site=',UserName='$',Password='***',AuthType='Basic' -setParam:name='IIS Web Application Name',value='' -enableRule:DoNotDeleteRule -userAgent:VSTS_8a7e5186-1f2d-497c-824a-3e3033fc674d_Release__5940_9642_2
2023-11-16T21:11:09.0430274Z ##[debug]Exit code 1 received from tool 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2023-11-16T21:11:09.0432375Z ##[debug]Exit code 1 received from tool 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2023-11-16T21:11:09.0433909Z ##[debug]STDIO streams have closed for tool 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2023-11-16T21:11:09.0435417Z ##[debug]STDIO streams have closed for tool 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2023-11-16T21:11:09.0436404Z ##[debug]{}
2023-11-16T21:11:09.0436929Z ##[debug]System.DefaultWorkingDirectory=D:\a\r1\a
2023-11-16T21:11:09.0438619Z ##[debug]Deployment Failed with Error: Error: Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
The system cannot find the path specified.

2023-11-16T21:11:09.0440021Z ##[debug]task result: Failed
2023-11-16T21:11:09.0475341Z ##[error]Error: Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
The system cannot find the path specified.

2023-11-16T21:11:09.0483954Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
The system cannot find the path specified.

2023-11-16T21:11:09.0487504Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
The system cannot find the path specified.

```

**Comment by jledgett** [comment]
@karl-dickman-icf remove any special characters from the Pipeline.   Update your Artifacts of your release to point to the new special character-free path.

**Comment by karl-dickman-icf** [comment]
I confirmed that renaming the artifact to remove the ampersand fixed the problem. But this is a breaking change; the pipeline had created over 1500 releases before this problem was encountered.

**Comment by jledgett** [comment]
I agree, it is a breaking change.   I just wanted to confirm the workaround so that folks weren't stuck with a non-functioning pipeline.
