### ISSUE TITLE
[BUG]: AzureFileCopy@5 to VM with WinRM prerequisites is creating invalid Expired Certificate breaking our deployments

### ISSUE THREAD

**Issue by rogerdaryl** [microsoft/azure-pipelines-tasks#19251]
### Task name

AzureFileCopyV5

### Task version

5.230.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Task log

```shell
2023-11-08T20:13:46.8431103Z [Azure Call]Getting the custom script extension 'WinRMCustomScriptExtension' for vm '{MachineName}'
2023-11-08T20:13:46.8433350Z ##[debug]Get-AzureRMAccessToken - started - endpoint=@{Url=https://management.azure.com/; Data=; Auth=} - scheme=ServicePrincipal
2023-11-08T20:13:46.8451219Z ##[debug]USE_MSAL: 'true'
2023-11-08T20:13:46.8476125Z ##[debug]MSAL - USE_MSAL override is found: true
2023-11-08T20:13:46.8517208Z ##[debug]MSAL - useMSAL = True
2023-11-08T20:13:46.8518333Z ##[debug]Fetching Access Token - MSAL
2023-11-08T20:13:46.8525520Z ##[debug]GET https://management.azure.com//subscriptions/{subscription}/resourceGroups/{ResourceGroup}?api-version=2016-02-01 with 0-byte payload
2023-11-08T20:13:46.8704578Z ##[debug]received 218-byte response of content type application/json; charset=utf-8
2023-11-08T20:13:46.8728604Z ##[debug]GET https://management.azure.com//subscriptions/{subscription}/resourceGroups/{ResourceGroup}/providers/Microsoft.Compute/virtualMachines/{MachineName}/extensions/WinRMCustomScriptExtension?api-version=2016-03-30 with 0-byte payload
2023-11-08T20:13:46.9377881Z ##[debug]received 655-byte response of content type application/json; charset=utf-8
2023-11-08T20:13:46.9401440Z [Azure Call]Got the custom script extension 'WinRMCustomScriptExtension' for vm '{VMName}'
2023-11-08T20:13:46.9543954Z ##[debug]Validating the winrm configuration custom script extension status
2023-11-08T20:13:46.9596225Z [Azure Call]Getting the status for vm '{VMName}'
2023-11-08T20:13:47.5003405Z [Azure Call]Got the status for vm '{VMName}'
2023-11-08T20:13:47.5243686Z ##[debug]Custom script extension execution statuses: 
2023-11-08T20:13:47.5256758Z ##[debug]
2023-11-08T20:13:47.5269665Z ##[debug]Code          : ComponentStatus/StdOut/succeeded
2023-11-08T20:13:47.5282308Z ##[debug]Level         : Info
2023-11-08T20:13:47.5294847Z ##[debug]DisplayStatus : Provisioning succeeded
2023-11-08T20:13:47.5307328Z ##[debug]Message       : Config
2023-11-08T20:13:47.5320913Z ##[debug]                    MaxEnvelopeSizekb = 8192
2023-11-08T20:13:47.5332984Z ##[debug]                    MaxTimeoutms = 60000
2023-11-08T20:13:47.5345667Z ##[debug]                    MaxBatchItems = 32000
2023-11-08T20:13:47.5357735Z ##[debug]                    MaxProviderRequests = 4294967295
2023-11-08T20:13:47.5369668Z ##[debug]                    Client
2023-11-08T20:13:47.5382232Z ##[debug]                        NetworkDelayms = 5000
2023-11-08T20:13:47.5394462Z ##[debug]                        URLPrefix = wsman
2023-11-08T20:13:47.5406988Z ##[debug]                        AllowUnencrypted = false
2023-11-08T20:13:47.5419693Z ##[debug]                        Auth
2023-11-08T20:13:47.5432124Z ##[debug]                            Basic = true
2023-11-08T20:13:47.5444279Z ##[debug]                            Digest = true
2023-11-08T20:13:47.5456813Z ##[debug]                            Kerberos = true
2023-11-08T20:13:47.5468953Z ##[debug]                            Negotiate = true
2023-11-08T20:13:47.5482123Z ##[debug]                            Certificate = true
2023-11-08T20:13:47.5494790Z ##[debug]                            CredSSP = false
2023-11-08T20:13:47.5507327Z ##[debug]                        DefaultPorts
2023-11-08T20:13:47.5520887Z ##[debug]                            HTTP = 5985
2023-11-08T20:13:47.5533247Z ##[debug]                            HTTPS = 5986
2023-11-08T20:13:47.5545460Z ##[debug]                        TrustedHosts
2023-11-08T20:13:47.5557821Z ##[debug]                    Service
2023-11-08T20:13:47.5570421Z ##[debug]                        RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)(A;;GR;;;IU)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;WD)
2023-11-08T20:13:47.5582549Z ##[debug]                        MaxConcurrentOperations = 4294967295
2023-11-08T20:13:47.5597268Z ##[debug]                        MaxConcurrentOperationsPerUser = 1500
2023-11-08T20:13:47.5614288Z ##[debug]                        EnumerationTimeoutms = 240000
2023-11-08T20:13:47.5627069Z ##[debug]                        MaxConnections = 300
2023-11-08T20:13:47.5640056Z ##[debug]                        MaxPacketRetrievalTimeSeconds = 120
2023-11-08T20:13:47.5652504Z ##[debug]                        AllowUnencrypted = false
2023-11-08T20:13:47.5666315Z ##[debug]                        Auth
2023-11-08T20:13:47.5678917Z ##[debug]                            Basic = false
2023-11-08T20:13:47.5693120Z ##[debug]                            Kerberos = true
2023-11-08T20:13:47.5705240Z ##[debug]                            Negotiate = true
2023-11-08T20:13:47.5716591Z ##[debug]                            Certificate = false
2023-11-08T20:13:47.5728999Z ##[debug]                            CredSSP = false
2023-11-08T20:13:47.5743427Z ##[debug]                            CbtHardeningLevel = Relaxed
2023-11-08T20:13:47.5755213Z ##[debug]                        DefaultPorts
2023-11-08T20:13:47.5768642Z ##[debug]                            HTTP = 5985
2023-11-08T20:13:47.5781633Z ##[debug]                            HTTPS = 5986
2023-11-08T20:13:47.5795734Z ##[debug]                        IPv4Filter = *
2023-11-08T20:13:47.5807947Z ##[debug]                        IPv6Filter = *
2023-11-08T20:13:47.5822017Z ##[debug]                        EnableCompatibilityHttpListener = false
2023-11-08T20:13:47.5835944Z ##[debug]                        EnableCompatibilityHttpsListener = false
2023-11-08T20:13:47.5850700Z ##[debug]                        CertificateThumbprint
2023-11-08T20:13:47.5862990Z ##[debug]                        AllowRemoteAccess = true
2023-11-08T20:13:47.5876128Z ##[debug]                    Winrs
2023-11-08T20:13:47.5888654Z ##[debug]                        AllowRemoteShellAccess = true
2023-11-08T20:13:47.5902924Z ##[debug]                        IdleTimeout = 7200000
2023-11-08T20:13:47.5915632Z ##[debug]                        MaxConcurrentUsers = 2147483647
2023-11-08T20:13:47.5930176Z ##[debug]                        MaxShellRunTime = 2147483647
2023-11-08T20:13:47.5942699Z ##[debug]                        MaxProcessesPerShell = 2147483647
2023-11-08T20:13:47.5957438Z ##[debug]                        MaxMemoryPerShellMB = 2147483647
2023-11-08T20:13:47.5970173Z ##[debug]                        MaxShellsPerUser = 2147483647
2023-11-08T20:13:47.5983806Z ##[debug]                
2023-11-08T20:13:47.5996278Z ##[debug]                ResourceCreated
2023-11-08T20:13:47.6010631Z ##[debug]                    Address = http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
2023-11-08T20:13:47.6022234Z ##[debug]                    ReferenceParameters
2023-11-08T20:13:47.6034616Z ##[debug]                        ResourceURI = http://schemas.microsoft.com/wbem/wsman/1/config/listener
2023-11-08T20:13:47.6048255Z ##[debug]                        SelectorSet
2023-11-08T20:13:47.6060772Z ##[debug]                            Selector: Address = *, Transport = HTTPS
2023-11-08T20:13:47.6073697Z ##[debug]                
2023-11-08T20:13:47.6086161Z ##[debug]                Auth
2023-11-08T20:13:47.6098392Z ##[debug]                    Basic = true
2023-11-08T20:13:47.6112820Z ##[debug]                    Kerberos = true
2023-11-08T20:13:47.6131343Z ##[debug]                    Negotiate = true
2023-11-08T20:13:47.6159285Z ##[debug]                    Certificate = false
2023-11-08T20:13:47.6176823Z ##[debug]                    CredSSP = false
2023-11-08T20:13:47.6189737Z ##[debug]                    CbtHardeningLevel = Relaxed
2023-11-08T20:13:47.6207452Z ##[debug]                
2023-11-08T20:13:47.6223671Z ##[debug]                
2023-11-08T20:13:47.6239000Z ##[debug]                No rules match the specified criteria.
2023-11-08T20:13:47.6252619Z ##[debug]                
2023-11-08T20:13:47.6268791Z ##[debug]                Ok.
2023-11-08T20:13:47.6281479Z ##[debug]                
2023-11-08T20:13:47.6295882Z ##[debug]                
2023-11-08T20:13:47.6308054Z ##[debug]Time          : 
2023-11-08T20:13:47.6348782Z ##[debug]
2023-11-08T20:13:47.6354154Z ##[debug]Code          : ComponentStatus/StdErr/succeeded
2023-11-08T20:13:47.6355316Z ##[debug]Level         : Info
2023-11-08T20:13:47.6432375Z ##[debug]DisplayStatus : Provisioning succeeded
2023-11-08T20:13:47.6444759Z ##[debug]Message       : 
2023-11-08T20:13:47.6459546Z ##[debug]Time          : 
2023-11-08T20:13:47.6471718Z ##[debug]
2023-11-08T20:13:47.6485459Z ##[debug]
2023-11-08T20:13:47.6497081Z ##[debug]
2023-11-08T20:13:47.6510305Z ##[debug]
2023-11-08T20:13:47.6577467Z ##[debug]Validated the script execution successfully
2023-11-08T20:13:47.6599765Z ##[debug]IsExtensionExists: True
2023-11-08T20:13:47.6701121Z ##[debug]Trying to add a network security group rule
2023-11-08T20:13:47.6803956Z ##[debug][Azure Call]Getting network interfaces in resource group {ResourceGroup} for vm /subscriptions/{subscription}/resourceGroups/{ResourceGroup}/providers/Microsoft.Compute/virtualMachines/{VMName}
2023-11-08T20:13:48.3629083Z ##[debug][Azure Call]Got network interfaces in resource group {ResourceGroup}
2023-11-08T20:13:48.3631079Z ##[debug]Number of network interface cards present in the vm: 1
2023-11-08T20:13:48.3634483Z ##[debug]Network Security Group Id: /subscriptions/{subscription}/resourceGroups/{ResourceGroup}/providers/Microsoft.Network/networkSecurityGroups/{NetworkSecurityGroup}
2023-11-08T20:13:48.3638244Z ##[debug]Security Group name is {NetworkSecurityGroup} and the related resource group {ResourceGroup}
2023-11-08T20:13:48.3640740Z ##[debug][Azure Call]Getting network security group {NetworkSecurityGroup} in resource group {ResourceGroup}
2023-11-08T20:13:48.5840968Z ##[debug][Azure Call]Got network security group {NetworkSecurityGroup} in resource group {ResourceGroup}
2023-11-08T20:13:48.6059386Z ##[debug][Azure Call]Getting network security rule config VSO-Custom-WinRM-Https-Port under security group {NetworkSecurityGroup}
2023-11-08T20:13:48.6403940Z ##[debug][Azure Call]Got network security rule config VSO-Custom-WinRM-Https-Port under security group {NetworkSecurityGroup}
2023-11-08T20:13:48.6437304Z ##[debug]Skipping the addition of custom script extension 'WinRMCustomScriptExtension' as it already exists
2023-11-08T20:13:48.6503373Z ##[debug]Azure VMs Admin Username: .\{Username}
2023-11-08T20:13:48.7006445Z ##[debug][Azure Call]Generating SasToken for container: 9038520c-1a83-452c-ba62-8b8f3d9c5466 in storage: {StorageAccount} with expiry time: 240 minutes
2023-11-08T20:13:48.7856290Z ##[debug][Azure Call]Generated SasToken: ?sv=2021-10-04&se=2023-11-09T00%3A13%3A48Z&sr=c&sp=rwdl&sig=Tr5LU9viBu5ZkMPohZxIPl8gQbPNO6eASuUXG9txDxY%3D successfully for container: 9038520c-1a83-452c-ba62-8b8f3d9c5466 in storage: {StorageAccount}
2023-11-08T20:13:48.9333588Z ##[debug]Starting parallel file copy
2023-11-08T20:13:48.9536794Z ##[debug]Entering Invoke-RemoteScript.
2023-11-08T20:13:48.9555682Z ##[debug] targetMachineNames: '{IPAddress}:5986'
2023-11-08T20:13:48.9681691Z ##[debug]Entering Get-TargetMachines.
2023-11-08T20:13:48.9791094Z ##[debug]Target Machines: {IPAddress}:5986
2023-11-08T20:13:48.9792606Z ##[debug]ComputerName = {IPAddress}
2023-11-08T20:13:48.9830044Z ##[debug]WSManPort = 5986
2023-11-08T20:13:48.9855662Z ##[debug]Authentication = Default
2023-11-08T20:13:48.9872947Z ##[debug]SessionConfigurationName = microsoft.powershell
2023-11-08T20:13:48.9936994Z ##[debug]UseSSL = True
2023-11-08T20:13:48.9977666Z ##[debug]Total target machines are: 1
2023-11-08T20:13:48.9996694Z ##[debug]Leaving Get-TargetMachines.
2023-11-08T20:13:49.0182428Z ##[debug]Entering Get-WinRmConnectionToTargetMachine.
2023-11-08T20:13:49.0202668Z ##[debug] computerName: '{IPAddress}'
2023-11-08T20:13:49.0218764Z ##[debug] port: '5986'
2023-11-08T20:13:49.0263295Z ##[debug] credential: 'System.Management.Automation.PSCredential'
2023-11-08T20:13:49.0279599Z ##[debug] authentication: 'Default'
2023-11-08T20:13:49.0298913Z ##[debug] sessionName: 'a1bb54be-ed5b-40e2-939e-87123450a03a'
2023-11-08T20:13:49.0315735Z ##[debug] sessionConfigurationName: 'microsoft.powershell'
2023-11-08T20:13:49.0332865Z ##[debug] useSsl: 'True'
2023-11-08T20:13:49.0446032Z ##[debug]Entering Get-NewPSSessionCommand.
2023-11-08T20:13:49.0490439Z ##[debug] computerName: '{IPAddress}'
2023-11-08T20:13:49.0491593Z ##[debug] port: '5986'
2023-11-08T20:13:49.0508598Z ##[debug] authentication: 'Default'
2023-11-08T20:13:49.0526883Z ##[debug] sessionName: 'a1bb54be-ed5b-40e2-939e-87123450a03a'
2023-11-08T20:13:49.0544187Z ##[debug] useSsl: 'True'
2023-11-08T20:13:49.0561446Z ##[debug] sessionConfigurationName: 'microsoft.powershell'
2023-11-08T20:13:49.0590278Z ##[debug] NoCredential: 'False'
2023-11-08T20:13:49.0599587Z ##[debug]New-PSSessionCommand: New-PSSession -ComputerName '{IPAddress}' -Port 5986 -Authentication Default -Name 'a1bb54be-ed5b-40e2-939e-87123450a03a' -Credential $credential -UseSSL -ErrorAction 'SilentlyContinue' -ErrorVariable sessionErrors -ConfigurationName 'microsoft.powershell'
2023-11-08T20:13:49.0617207Z ##[debug]Leaving Get-NewPSSessionCommand.
2023-11-08T20:13:49.0645735Z ##[debug]Trying to establish connection: Attempt #1
2023-11-08T20:13:49.3034377Z ##[debug]New-PSSession Error: Connecting to remote server {IPAddress} failed with the following error message : The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
2023-11-08T20:13:49.3048344Z ##[debug]The SSL certificate is expired. For more information, see the about_Remote_Troubleshooting Help topic.
2023-11-08T20:14:19.9428591Z ##[debug]Trying to establish connection: Attempt #2
2023-11-08T20:14:20.4478058Z ##[debug]New-PSSession Error: Connecting to remote server {IPAddress} failed with the following error message : The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
2023-11-08T20:14:20.4480665Z ##[debug]The SSL certificate is expired. For more information, see the about_Remote_Troubleshooting Help topic.
2023-11-08T20:14:49.3628138Z ##[debug]Trying to establish connection: Attempt #3
2023-11-08T20:14:49.3924079Z ##[debug]New-PSSession Error: Connecting to remote server {IPAddress} failed with the following error message : The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
2023-11-08T20:14:49.3937307Z ##[debug]The SSL certificate is expired. For more information, see the about_Remote_Troubleshooting Help topic.
2023-11-08T20:15:19.4469242Z ##[debug]Leaving Get-WinRmConnectionToTargetMachine.
2023-11-08T20:15:19.4816267Z ##[debug]Entering Disconnect-WinRmConnectionToTargetMachines.
2023-11-08T20:15:19.4969212Z ##[debug]Entering Get-RemoteConnection.
2023-11-08T20:15:19.6736444Z ##[debug]Leaving Get-RemoteConnection.
2023-11-08T20:15:19.6765204Z ##[debug]Leaving Disconnect-WinRmConnectionToTargetMachines.
2023-11-08T20:15:19.6801836Z ##[debug]Parallel file copy: Invoke-RemoteScript threw exception
2023-11-08T20:15:19.7151151Z ##[debug]System.Management.Automation.RuntimeException: The remote session query failed for {IPAddress} with the following error message: The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
2023-11-08T20:15:19.7164566Z ##[debug]The SSL certificate is expired.     ---> System.InvalidOperationException: <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="12175" Machine="fv-az786-214"><f:Message>The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
2023-11-08T20:15:19.7175884Z ##[debug]The SSL certificate is expired.    </f:Message></f:WSManFault>
2023-11-08T20:15:19.7188750Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2023-11-08T20:15:19.7201359Z ##[debug]   --- End of inner exception stack trace ---
2023-11-08T20:15:19.7452501Z ##[debug]Processed: ##vso[task.logissue type=error;code={"Task_Internal_Error":"CopyingToAzureVMFailed"};]
2023-11-08T20:15:19.7505158Z ##[debug][Azure Call]Deleting container: 9038520c-1a83-452c-ba62-8b8f3d9c5466 in storage account: {StorageAccount}
2023-11-08T20:15:19.9506987Z ##[debug]Removed container '9038520c-1a83-452c-ba62-8b8f3d9c5466' successfully.
2023-11-08T20:15:19.9850920Z ##[debug][Azure Call]Deleted container: 9038520c-1a83-452c-ba62-8b8f3d9c5466 in storage account: {StorageAccount}
2023-11-08T20:15:19.9937254Z ##[debug]Completed Azure File Copy Task for Azure VMs Destination
2023-11-08T20:15:19.9981795Z ##[debug]Leaving D:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\5.230.0\AzureFileCopy.ps1.
2023-11-08T20:15:20.0040251Z ##[debug]Trying to disconnect from Azure and clear context at process scope
2023-11-08T20:15:20.0123309Z ##[debug]Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
2023-11-08T20:15:20.0149222Z ##[debug]Populating RepositorySourceLocation property for module Az.Accounts.
2023-11-08T20:15:20.0173436Z ##[debug]Loading module from path 'C:\Modules\az_9.3.0\Az.Accounts\2.13.1\Az.Accounts.psm1'.
2023-11-08T20:15:20.0785660Z ##[command]Disconnect-AzAccount -Scope Process -ErrorAction Stop
2023-11-08T20:15:20.1161284Z ##[command]Clear-AzContext -Scope Process -ErrorAction Stop
2023-11-08T20:15:20.1881317Z ##[debug]Caught exception from task script.
2023-11-08T20:15:20.1920599Z ##[debug]Error record:
2023-11-08T20:15:20.2482665Z ##[debug]The remote session query failed for {IPAddress} with the following error message: The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
2023-11-08T20:15:20.2497159Z ##[debug]The SSL certificate is expired.    
2023-11-08T20:15:20.2510513Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
2023-11-08T20:15:20.2523155Z ##[debug]    + FullyQualifiedErrorId : RuntimeException
2023-11-08T20:15:20.2536266Z ##[debug] 
2023-11-08T20:15:20.2562738Z ##[debug]Script stack trace:
2023-11-08T20:15:20.2593031Z ##[debug]
2023-11-08T20:15:20.2622148Z ##[debug]Exception:
2023-11-08T20:15:20.2639050Z ##[debug]System.Management.Automation.RuntimeException: The remote session query failed for {IPAddress} with the following error message: The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
2023-11-08T20:15:20.2652603Z ##[debug]The SSL certificate is expired.     ---> System.InvalidOperationException: <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="12175" Machine="fv-az786-214"><f:Message>The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
2023-11-08T20:15:20.2663772Z ##[debug]The SSL certificate is expired.    </f:Message></f:WSManFault>
2023-11-08T20:15:20.2676985Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2023-11-08T20:15:20.2689580Z ##[debug]   --- End of inner exception stack trace ---
2023-11-08T20:15:20.2748662Z ##[error]The remote session query failed for {IPAddress} with the following error message: The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
The SSL certificate is expired.    
2023-11-08T20:15:20.2752924Z ##[debug]Processed: ##vso[task.logissue type=error]The remote session query failed for {IPAddress} with the following error message: The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
The SSL certificate is expired.    
2023-11-08T20:15:20.2761027Z ##[debug]Processed: ##vso[task.complete result=Failed]
```

### Relevant log output

```shell
2023-11-08T20:15:20.2748662Z ##[error]The remote session query failed for {IPAddress} with the following error message: The server certificate on the destination computer ({IPAddress}:5986) has the following errors:      
The SSL certificate is expired.
```

### Aditional info

```shell
This has been an issue in the last two days. It was working as expected before then. It affects different pipelines using the AzureFileCopy task
```

```[tasklist]
### Tasks
```

**Comment by rogerdaryl** [comment]
using the method details here, I have created a new certificate on the VM and it is working again https://github.com/microsoft/azure-pipelines-tasks/issues/15656#issuecomment-1013458886

**Comment by benjiecov** [comment]
We recently started experiencing this in a pipeline that's been working for a year without changes. It looks like there are two factors that contribute to this issue, and it seems to affect all versions of this task. (Note: this is specifically when copying to a VM and using the "Enable Copy Prerequisites" option.)

* The [ConfigureWinRM.ps1](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/demos/vm-winrm-windows/ConfigureWinRM.ps1) script creates the certificate with an expiration date set to 1 year in the future. It also doesn't create a new certificate if it finds an existing expired one.

* The Add-AzureVMCustomScriptExtension function in the [Utility.ps1](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureFileCopyV5/Utility.ps1) script only runs the ConfigureWinRM.ps1 script if the extension is not already installed.

So this task initially creates the certificate with a 1 year extension, but it never updates the certificate, so it starts failing after 1 year.

Another workaround for this is to remove the existing certificate and uninstall the WinRMCustomScriptExtension. Then the next time the task is run, it will reinstall the extension and create a new certificate.
