### ISSUE TITLE
[BUG]: IISWebAppDeploymentOnMachineGroup@0 task is failing with "command not found" error

### ISSUE THREAD

**Issue by KristofKuli** [microsoft/azure-pipelines-tasks#19268]
### Task name

IISWebAppDeploymentOnMachineGroup@0

### Task version

0.230.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2016

### Task log

```shell
2023-11-10T10:52:07.7155216Z ##[section]Starting: IIS Web App Deploy
2023-11-10T10:52:07.7394649Z ==============================================================================
2023-11-10T10:52:07.7395147Z Task         : IIS web app deploy
2023-11-10T10:52:07.7395451Z Description  : Deploy a website or web application using Web Deploy
2023-11-10T10:52:07.7395675Z Version      : 0.230.0
2023-11-10T10:52:07.7395869Z Author       : Microsoft Corporation
2023-11-10T10:52:07.7396200Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
2023-11-10T10:52:07.7396561Z ==============================================================================
2023-11-10T10:52:08.3303338Z [command]C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\7zip\7zip\7z.exe x -oC:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004 C:\vstsagent\A1\_work\r3\a\_EBESNG-BUILD\drop\***.eBesNg.Api.zip
2023-11-10T10:52:08.3648819Z 
2023-11-10T10:52:08.3671659Z 7-Zip [64] 16.00 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-10
2023-11-10T10:52:08.3672077Z 
2023-11-10T10:52:08.3680798Z Scanning the drive for archives:
2023-11-10T10:52:08.3681125Z 1 file, 156915423 bytes (150 MiB)
2023-11-10T10:52:08.3681250Z 
2023-11-10T10:52:08.3681558Z Extracting archive: C:\vstsagent\A1\_work\r3\a\_EBESNG-BUILD\drop\***.eBesNg.Api.zip
2023-11-10T10:52:12.3627980Z --
2023-11-10T10:52:12.3645493Z Path = C:\vstsagent\A1\_work\r3\a\_EBESNG-BUILD\drop\***.eBesNg.Api.zip
2023-11-10T10:52:12.3721140Z Type = zip
2023-11-10T10:52:12.3726713Z Physical Size = 156915423
2023-11-10T10:52:12.3734890Z 
2023-11-10T10:52:12.3735624Z Everything is Ok
2023-11-10T10:52:12.3735913Z 
2023-11-10T10:52:12.3736236Z Folders: 56
2023-11-10T10:52:12.3736552Z Files: 766
2023-11-10T10:52:12.3736902Z Size:       258137973
2023-11-10T10:52:12.3737305Z Compressed: 156915423
2023-11-10T10:52:16.0390181Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\AppSettings.config
2023-11-10T10:52:16.0497849Z Processing substitution for xml node : appSettings
2023-11-10T10:52:16.0600958Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\AppSettings.config
2023-11-10T10:52:16.0602810Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Areas\HelpPage\Views\Web.config
2023-11-10T10:52:16.0604996Z Processing substitution for xml node : appSettings
2023-11-10T10:52:16.0606068Z Processing substitution for xml node : configSections
2023-11-10T10:52:16.0608117Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Areas\HelpPage\Views\Web.config
2023-11-10T10:52:16.0608999Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Properties\PublishItems\AppPoolClrConfig\EBES_NG_aspnetconfig.config
2023-11-10T10:52:16.0611299Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Properties\PublishItems\AppPoolClrConfig\EBES_NG_aspnetconfig.config
2023-11-10T10:52:16.0612211Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Scripts\core\web.config
2023-11-10T10:52:16.0616583Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Scripts\core\web.config
2023-11-10T10:52:16.0617461Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Scripts\ebesng\backup-web.config
2023-11-10T10:52:16.0667900Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Scripts\ebesng\backup-web.config
2023-11-10T10:52:16.0668710Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Views\Web.config
2023-11-10T10:52:16.0670082Z Processing substitution for xml node : appSettings
2023-11-10T10:52:16.0671040Z Processing substitution for xml node : configSections
2023-11-10T10:52:16.0673412Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Views\Web.config
2023-11-10T10:52:16.0674203Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Web.config
2023-11-10T10:52:16.1217411Z Processing substitution for xml node : appSettings
2023-11-10T10:52:16.1280369Z Processing substitution for xml node : connectionStrings
2023-11-10T10:52:16.1282212Z Processing substitution for xml node : configSections
2023-11-10T10:52:16.1284520Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\Web.config
2023-11-10T10:52:16.1285299Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\AppSettings.Dev2MocksDeploy.config
2023-11-10T10:52:16.1286706Z Processing substitution for xml node : appSettings
2023-11-10T10:52:16.1288287Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\AppSettings.Dev2MocksDeploy.config
2023-11-10T10:52:16.1290146Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\AppSettings.config
2023-11-10T10:52:16.1291127Z Processing substitution for xml node : appSettings
2023-11-10T10:52:16.1322931Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\AppSettings.config
2023-11-10T10:52:16.1323889Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Common.dll.config
2023-11-10T10:52:16.1325793Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Common.dll.config
2023-11-10T10:52:16.1327755Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Data.dll.config
2023-11-10T10:52:16.1330294Z Processing substitution for xml node : configSections
2023-11-10T10:52:16.1332712Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Data.dll.config
2023-11-10T10:52:16.1333552Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Domain.dll.config
2023-11-10T10:52:16.1334951Z Processing substitution for xml node : configSections
2023-11-10T10:52:16.1336415Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Domain.dll.config
2023-11-10T10:52:16.1337221Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Messaging.dll.config
2023-11-10T10:52:16.1339068Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Messaging.dll.config
2023-11-10T10:52:16.1339882Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Swagger.dll.config
2023-11-10T10:52:16.1341266Z Processing substitution for xml node : configSections
2023-11-10T10:52:16.1343649Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Swagger.dll.config
2023-11-10T10:52:16.1344455Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Systems.Dctm.dll.config
2023-11-10T10:52:16.1346280Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Systems.Dctm.dll.config
2023-11-10T10:52:16.1347873Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Systems.Sharepoint.dll.config
2023-11-10T10:52:16.1349762Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Systems.Sharepoint.dll.config
2023-11-10T10:52:16.1350572Z Initiated variable substitution in config file : C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Worker.dll.config
2023-11-10T10:52:16.1352009Z Processing substitution for xml node : configSections
2023-11-10T10:52:16.1353358Z Skipped Updating file: C:\vstsagent\A1\_work\_temp\temp_web_package_5858294650064004\Content\D_C\build\V1\_w\1\s\***.eBesNg.Api\***.eBesNg.Api\obj\Release\Package\PackageTmp\bin\***.eBesNg.Api.Worker.dll.config
2023-11-10T10:52:16.1353872Z XML variable substitution applied successfully.
2023-11-10T10:52:28.5052363Z [command]"C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\vstsagent\A1\_work\r3\a\temp_web_package_11882041661163134.zip' -dest:auto -setParam:name='IIS Web Application Name',value='ebesng-oauth' -enableRule:AppOffline -setParamFile=1699613548372_tempSetParameters.xml -setParam:kind=ProviderPath,scope=iisApp,value=ebesng-oauth -setParam:name='eBesNgDBContext-Web.config Connection String',value='Data Source=dcs0000338.leosrprod.sccloudres.net;Initial Catalog=EBESNG_INTERNAL;Persist Security Info=True;Integrated Security=SSPI;Trusted_Connection=true', -setParam:authentication:AssentisPassword=***, -setParam:api:EbesNgServiceRoot=https://ebesng-dev1.***.com:8443 -setParam:documentum:restServiceRoot=https://edms-rest-dev.***.com/services -setParam:aad:EbesNgClientId=1b3e871a-c99e-4024-9f75-c97cb46fed31 -setParam:aad:EbesNgClientSecret=*** -setParam:security:AesIv=*** -setParam:aad:EbesNgRedirectUri=https://ebesng-dev1.***.com:8443 -setParam:aad:DocumentumClientId=d38a6d05-8ec8-43eb-aef6-bc674eadd0b0 -setParam:'api:PdfTronSdkLic'='Swiss Re Management Ltd. (***.com):ENTERP:See Agreement::W+:AMS(20240923):47A5D4AD04E7F80A0320B13AC992237B20614F8B5C707AC2C56C3DDA8724B9A06AF431F5C7' -setParam:'api:PdfTronViewerLic'='Swiss Re Management Ltd. (***.com):ENTERP:See Agreement::B+:AMS(20240923):87A5AAAD04E7F80A0360B13AC982537B20614F8B5C707AC2C56C3DDA8724B9A06AF431F5C7' -setParam:name='DecryptionKey',value='D10A30A9AED8256DB8F225B964873312D5EF21BA2D13BE2E', -setParam:name='ValidationKey',value='763B109A08C58ACB5AB5EBBD348527EB0B31B7EF9107A35C52F40945CE8FA09305DDEFECBC4E6E3C7C65AE018420C8B04C13F096611FAF7B3BBFB3EA3B3885CF', -setParam:'messagebroker:RmqUserName'='tZtSh2pzxJmglvtq', -setParam:'messagebroker:RmqPassword'='***', -setParam:'messagebroker:RmqVirtualHost'='67d889ff-825f-4a64-973b-2a2c66ef6194', -setParam:name='eBesNgWorkerProcessDBContext-Web.config Connection String',value='Data Source=dcs0000338.leosrprod.sccloudres.net;Initial Catalog=EBESNG_INTERNAL_WORKER;Persist Security Info=True;Integrated Security=SSPI;Trusted_Connection=true'
2023-11-10T10:52:30.9275456Z Error: The process 'C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-10T10:52:30.9276737Z     at ExecState._setResult (C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-10T10:52:30.9278459Z     at ExecState.CheckComplete (C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-10T10:52:30.9279295Z     at ChildProcess.<anonymous> (C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-10T10:52:30.9279865Z     at ChildProcess.emit (events.js:198:13)
2023-11-10T10:52:30.9280192Z     at maybeClose (internal/child_process.js:982:16)
2023-11-10T10:52:30.9280550Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2023-11-10T10:52:30.9280850Z Retrying to deploy the package.
2023-11-10T10:52:30.9343465Z [command]"C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\vstsagent\A1\_work\r3\a\temp_web_package_11882041661163134.zip' -dest:auto -setParam:name='IIS Web Application Name',value='ebesng-oauth' -enableRule:AppOffline -setParamFile=1699613548372_tempSetParameters.xml -setParam:kind=ProviderPath,scope=iisApp,value=ebesng-oauth -setParam:name='eBesNgDBContext-Web.config Connection String',value='Data Source=dcs0000338.leosrprod.sccloudres.net;Initial Catalog=EBESNG_INTERNAL;Persist Security Info=True;Integrated Security=SSPI;Trusted_Connection=true', -setParam:authentication:AssentisPassword=***, -setParam:api:EbesNgServiceRoot=https://ebesng-dev1.***.com:8443 -setParam:documentum:restServiceRoot=https://edms-rest-dev.***.com/services -setParam:aad:EbesNgClientId=1b3e871a-c99e-4024-9f75-c97cb46fed31 -setParam:aad:EbesNgClientSecret=*** -setParam:security:AesIv=*** -setParam:aad:EbesNgRedirectUri=https://ebesng-dev1.***.com:8443 -setParam:aad:DocumentumClientId=d38a6d05-8ec8-43eb-aef6-bc674eadd0b0 -setParam:'api:PdfTronSdkLic'='Swiss Re Management Ltd. (***.com):ENTERP:See Agreement::W+:AMS(20240923):47A5D4AD04E7F80A0320B13AC992237B20614F8B5C707AC2C56C3DDA8724B9A06AF431F5C7' -setParam:'api:PdfTronViewerLic'='Swiss Re Management Ltd. (***.com):ENTERP:See Agreement::B+:AMS(20240923):87A5AAAD04E7F80A0360B13AC982537B20614F8B5C707AC2C56C3DDA8724B9A06AF431F5C7' -setParam:name='DecryptionKey',value='D10A30A9AED8256DB8F225B964873312D5EF21BA2D13BE2E', -setParam:name='ValidationKey',value='763B109A08C58ACB5AB5EBBD348527EB0B31B7EF9107A35C52F40945CE8FA09305DDEFECBC4E6E3C7C65AE018420C8B04C13F096611FAF7B3BBFB3EA3B3885CF', -setParam:'messagebroker:RmqUserName'='tZtSh2pzxJmglvtq', -setParam:'messagebroker:RmqPassword'='***', -setParam:'messagebroker:RmqVirtualHost'='67d889ff-825f-4a64-973b-2a2c66ef6194', -setParam:name='eBesNgWorkerProcessDBContext-Web.config Connection String',value='Data Source=dcs0000338.leosrprod.sccloudres.net;Initial Catalog=EBESNG_INTERNAL_WORKER;Persist Security Info=True;Integrated Security=SSPI;Trusted_Connection=true'
2023-11-10T10:52:33.2396321Z Error: The process 'C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-10T10:52:33.2397321Z     at ExecState._setResult (C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-10T10:52:33.2398222Z     at ExecState.CheckComplete (C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-10T10:52:33.2405217Z     at ChildProcess.<anonymous> (C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-10T10:52:33.2406852Z     at ChildProcess.emit (events.js:198:13)
2023-11-10T10:52:33.2407886Z     at maybeClose (internal/child_process.js:982:16)
2023-11-10T10:52:33.2408270Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2023-11-10T10:52:33.2409003Z Retrying to deploy the package.
2023-11-10T10:52:33.2530744Z [command]"C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\vstsagent\A1\_work\r3\a\temp_web_package_11882041661163134.zip' -dest:auto -setParam:name='IIS Web Application Name',value='ebesng-oauth' -enableRule:AppOffline -setParamFile=1699613548372_tempSetParameters.xml -setParam:kind=ProviderPath,scope=iisApp,value=ebesng-oauth -setParam:name='eBesNgDBContext-Web.config Connection String',value='Data Source=dcs0000338.leosrprod.sccloudres.net;Initial Catalog=EBESNG_INTERNAL;Persist Security Info=True;Integrated Security=SSPI;Trusted_Connection=true', -setParam:authentication:AssentisPassword=***, -setParam:api:EbesNgServiceRoot=https://ebesng-dev1.***.com:8443 -setParam:documentum:restServiceRoot=https://edms-rest-dev.***.com/services -setParam:aad:EbesNgClientId=1b3e871a-c99e-4024-9f75-c97cb46fed31 -setParam:aad:EbesNgClientSecret=*** -setParam:security:AesIv=*** -setParam:aad:EbesNgRedirectUri=https://ebesng-dev1.***.com:8443 -setParam:aad:DocumentumClientId=d38a6d05-8ec8-43eb-aef6-bc674eadd0b0 -setParam:'api:PdfTronSdkLic'='Swiss Re Management Ltd. (***.com):ENTERP:See Agreement::W+:AMS(20240923):47A5D4AD04E7F80A0320B13AC992237B20614F8B5C707AC2C56C3DDA8724B9A06AF431F5C7' -setParam:'api:PdfTronViewerLic'='Swiss Re Management Ltd. (***.com):ENTERP:See Agreement::B+:AMS(20240923):87A5AAAD04E7F80A0360B13AC982537B20614F8B5C707AC2C56C3DDA8724B9A06AF431F5C7' -setParam:name='DecryptionKey',value='D10A30A9AED8256DB8F225B964873312D5EF21BA2D13BE2E', -setParam:name='ValidationKey',value='763B109A08C58ACB5AB5EBBD348527EB0B31B7EF9107A35C52F40945CE8FA09305DDEFECBC4E6E3C7C65AE018420C8B04C13F096611FAF7B3BBFB3EA3B3885CF', -setParam:'messagebroker:RmqUserName'='tZtSh2pzxJmglvtq', -setParam:'messagebroker:RmqPassword'='***', -setParam:'messagebroker:RmqVirtualHost'='67d889ff-825f-4a64-973b-2a2c66ef6194', -setParam:name='eBesNgWorkerProcessDBContext-Web.config Connection String',value='Data Source=dcs0000338.leosrprod.sccloudres.net;Initial Catalog=EBESNG_INTERNAL_WORKER;Persist Security Info=True;Integrated Security=SSPI;Trusted_Connection=true'
2023-11-10T10:52:35.4194557Z ##[error]Failed to deploy web package to IIS website.
2023-11-10T10:52:35.4262411Z ##[error]'sjfdxuHes' is not recognized as an internal or external command,
operable program or batch file.

2023-11-10T10:52:35.4644829Z ##[error]Error: The process 'C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-10T10:52:35.4803486Z ##[section]Finishing: IIS Web App Deploy
```

### Relevant log output

```shell
2023-11-10T10:52:35.4194557Z ##[error]Failed to deploy web package to IIS website.
2023-11-10T10:52:35.4262411Z ##[error]'sjfdxuHes' is not recognized as an internal or external command,
operable program or batch file.

2023-11-10T10:52:35.4644829Z ##[error]Error: The process 'C:\vstsagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-10T10:52:35.4803486Z ##[section]Finishing: IIS Web App Deploy
```

### Aditional info

```shell
This pipeline was working fine with task version 0.227.0. There was no change in the configuration of the project.
```

**Comment by KristofKuli** [comment]
Tested the deployment with previous version "0.227.0" and it was successful, hence the issue is with the new version.

**Comment by JackTNeely** [comment]
I am seeing similar issues with the new task version 0.230.0. Notably, deployments have started failing for source packages if a special character exists in the file path. This issue did not occur with previous IISWebAppDeploymentOnMachineGroup@0 task versions.

2023-11-14T21:24:46.7536559Z ##[error]Failed to deploy web package to IIS website.
2023-11-14T21:24:46.7547686Z ##[debug]Processed: ##vso[task.issue type=error;]Failed to deploy web package to IIS website.
2023-11-14T21:24:46.7548834Z ##[debug]{}
2023-11-14T21:24:46.7549716Z ##[debug]System.DefaultWorkingDirectory=C:\azagent\A1\_work\r1\a
2023-11-14T21:24:46.7551433Z ##[error]Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
The system cannot find the path specified.

**Comment by v-mohithgc** [comment]
Hi @KristofKuli  , this task has been reverted back to 227, can you please run and confirm back here? thanks
