### ISSUE TITLE
IIS Web App Deploy started failing with Unrecognized App_Data

### ISSUE THREAD

**Issue by jmc18** [microsoft/azure-pipelines-tasks#19276]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task version

0.230.0

### Issue Description

I have tried to deploy and I get errors in IIS Web App Deploy, and it says:

- 'App_Data' is not recognized as an internal or external command, operable program or batch file.
- The process 'C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-86174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' ailed with exit code 255

I have tried to remove the folders from **C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup** and it didn't work

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2019

### Relevant log output

```shell
2023-11-14T23:47:51.2110779Z Error: The process 'C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 255
2023-11-14T23:47:51.2111354Z     at ExecState._setResult (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-14T23:47:51.2111841Z     at ExecState.CheckComplete (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-14T23:47:51.2112770Z     at ChildProcess.<anonymous> (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-14T23:47:51.2113062Z     at ChildProcess.emit (events.js:198:13)
2023-11-14T23:47:51.2113229Z     at maybeClose (internal/child_process.js:982:16)
2023-11-14T23:47:51.2113402Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2023-11-14T23:47:51.2113542Z Retrying to deploy the package.
2023-11-14T23:47:51.2177643Z [command]"C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A1\_work\r1\a\temp_web_package_7316042457830005.zip' -dest:auto -setParam:name='IIS Web Application Name',value='QAStore-Umbraco' -enableRule:AppOffline -setParamFile=1700005670735_tempSetParameters.xml -skip:skipaction='Delete',objectname='dirPath',absolutepath='\\([Mm]edia|App_Data|_temp|App_Plugins\\UmbracoForms\\Data|NEW|Webstore)$' -skip:objectName=setAcl
2023-11-14T23:47:51.2519106Z Error: The process 'C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 255
2023-11-14T23:47:51.2519653Z     at ExecState._setResult (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-14T23:47:51.2520156Z     at ExecState.CheckComplete (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-14T23:47:51.2520650Z     at ChildProcess.<anonymous> (C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-14T23:47:51.2520960Z     at ChildProcess.emit (events.js:198:13)
2023-11-14T23:47:51.2521109Z     at maybeClose (internal/child_process.js:982:16)
2023-11-14T23:47:51.2521276Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2023-11-14T23:47:51.2521421Z Retrying to deploy the package.
2023-11-14T23:47:51.2530660Z [command]"C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A1\_work\r1\a\temp_web_package_7316042457830005.zip' -dest:auto -setParam:name='IIS Web Application Name',value='QAStore-Umbraco' -enableRule:AppOffline -setParamFile=1700005670735_tempSetParameters.xml -skip:skipaction='Delete',objectname='dirPath',absolutepath='\\([Mm]edia|App_Data|_temp|App_Plugins\\UmbracoForms\\Data|NEW|Webstore)$' -skip:objectName=setAcl
2023-11-14T23:47:51.2859105Z ##[error]Failed to deploy web package to IIS website.
2023-11-14T23:47:51.2866209Z ##[error]'App_Data' is not recognized as an internal or external command,
operable program or batch file.

2023-11-14T23:47:51.3383561Z ##[error]Error: The process 'C:\azagent\A1\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 255
2023-11-14T23:47:51.3687513Z ##[section]Finishing: IIS Web App Deploy
```

**Comment by v-mohithgc** [comment]
Hi @jmc18 , this task has been reverted back to 227, can you please run and confirm back here? thanks

**Comment by jmc18** [comment]
Hi @v-mohithgc this is working now, we were able to deploy, thanks!
