### ISSUE TITLE
[Question]: How to pass NODE_OPTIONS=---openssl-legacy-provider in a public agent?

### ISSUE THREAD

**Issue by j4t1nd3r** [microsoft/azure-pipelines-tasks#19333]
### Task name

Gradle

### Task version

3

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Question

I am attempting to upgrade Node in the pipeline from 16 to 18.
Gradle fails with an error relating to SSL, the solution is apparently to pass NODE_OPTIONS=---openssl-legacy-provider as a variable in the pipeline. 
This variable is used locally by the devs to avoid the Gradle failure on local machines using Node18.

The Public Agent uses Node16 as a task runner, this is variable is not supported in Node16, it is Node17+ variable. 
I don't see a way to get around this limitation, installing Node18 and using task "useNode@1" specifying Node18 does not allow me to get around the task runner using Node16.

I am aware of the task NodeTaskRunnerInstaller@0, however this only lets me switch to Node 10 or 6. Suggestions? 

The initial error in the pipeline with Gradle@3 Task: 

```shell
> Task :react-native-mmkv:extractJNIFiles

Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:69:19)
at Object.createHash (node:crypto:133:10)
at stableHash (D:\a\1\s\node_modules\metro-cache\src\stableHash.js:19:8)
at Object.getCacheKey (D:\a\1\s\node_modules\metro-config\node_modules\metro-transform-worker\src\index.js:593:7)
at getTransformCacheKey (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:24:19)
at new Transformer (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\Transformer.js:48:9)
at D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\Bundler.js:22:29 {
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Cannot read properties of undefined (reading 'transformFile').
> Task :app:bundleDevReleaseJsAndAssets
TypeError: Cannot read properties of undefined (reading 'transformFile')
at Bundler.transformFile (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\Bundler.js:48:30)
at async Object.transform (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\lib\transformHelpers.js:101:12)
at async processModule (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\traverseDependencies.js:137:18)
at async traverseDependenciesForSingleFile (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\traverseDependencies.js:131:3)
at async Promise.all (index 0)
at async initialTraverseDependencies (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\traverseDependencies.js:114:3)
at async DeltaCalculator._getChangedDependencies (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:164:25)
at async DeltaCalculator.getDelta (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:94:16)
at async DeltaBundler.buildGraph (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler.js:50:5)
at async IncrementalBundler.buildGraphForEntries (D:\a\1\s\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\IncrementalBundler.js:80:19)
info Run CLI with --verbose flag for more details.

> Task :app:bundleDevReleaseJsAndAssets FAILED
> Task :react-native-mmkv:generateJsonModelDebug
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleDevReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

```

**Comment by aleksandrlevochkin** [comment]
Hi @j4t1nd3r thank you for the question, we'll take a look

**Comment by aleksandrlevochkin** [comment]
@j4t1nd3r you can use this variable to force the agent to use the Node 20 handler:

```
variables:
  AGENT_USE_NODE20_1: "true"
 ```

**Comment by j4t1nd3r** [comment]
> @j4t1nd3r you can use this variable to force the agent to use the Node 20 handler:
> 
> ```
> variables:
>   AGENT_USE_NODE20_1: "true"
> ```
> 
> Edit: If an older version of the agent is used, the variable may be called AGENT_USE_NODE20, so you can try that as well.

Thank you, this has resolved my issue! I did google to switch to a newer version of the node task runner but found nothing.
Where did you find this variable if you don't mind me asking?
