### ISSUE TITLE
[REGRESSION]: SSHv0 no longer working on self-hosted Windows 10 x64 agents

### ISSUE THREAD

**Issue by Metarract** [microsoft/azure-pipelines-tasks#19641]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

SSHv0

### Breaking task version

0.236.2

### Last working task version

0.231.3

### Regression Description

SSHv0 previously worked on self-hosted Windows 10 Agents, now does not as of most recent update - log explicitly states that whatever it's attempting to do is not available on Windows(x64). We have a workaround as we have some linux agents as well, but far fewer in number due to the nature of our company's products so i'd like to get these people off of the linux ones if possible.

Pretty sure it's not our agents as the most recent success was yesterday, on and agent that; on Attempt _1_ downloaded the newer version of the task, failed; then on Attempt _2_ downloaded the _older_ version of the task for some reason (or maybe it already had it? didn't have system.debug on for that one - not sure how this all happened lol) and succeeded (verified same agent / same machine both times).

I did see that the `ssh2` library was updated as part of the most recent update a couple weeks ago, though that should have been a minor change from what i can see - though the `sftp` lib was updated significantly but i would think that wouldn't matter here. 

Also seeing that the `node10` executor was removed in #19532, was this done early in error? I'm unaware of the current state of `node10` deprecation, [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=yaml%2Cbrowser#node-runner-versions) seems to still place `node10` as the default executor without mention of deprecation of it yet in favor of `node16` or `node20`. Would it be simple enough to update the agent (would that install the 16 executor it might be missing)? Or would something like a `NodeToolInstaller` task @ node 16 do the job?

Other things that might not matter but included for completion:
- Agent version 2.204.0
- Task was running an inline script
- Targeting bash on remote linux machine (not sure of OS but again probably doesn't matter)
- All other fields seemed set at defaults

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 10 (for self-hosted agent)

### Relevant log output

```shell
company info [omitted]

2024-03-13T12:12:37.2931033Z ##[section]Starting: [OMITTED]
2024-03-13T12:12:37.3932610Z ==============================================================================
2024-03-13T12:12:37.3933777Z Task         : SSH
2024-03-13T12:12:37.3934542Z Description  : Run shell commands or a script on a remote machine using SSH
2024-03-13T12:12:37.3934988Z Version      : 0.236.2
2024-03-13T12:12:37.3935996Z Author       : Microsoft Corporation
2024-03-13T12:12:37.3936822Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh
2024-03-13T12:12:37.3937459Z ==============================================================================
2024-03-13T12:12:37.5927557Z ##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.
2024-03-13T12:12:37.5948155Z ##[section]Finishing: [OMITTED]
```

### Full task logs with system.debug enabled

Do not have a successful run with system.debug on as newer runs (now, i guess) are downloading the newer task version, and the previous success had it off; but i've included that success regardless to illustrate the task version. The success is also the one that appeared out of order.

company info [omitted]

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre>
2024-03-14T13:28:55.4742748Z ##[debug]Evaluating condition for step: [OMITTED]
2024-03-14T13:28:55.4812566Z ##[debug]Evaluating: succeeded()
2024-03-14T13:28:55.4820437Z ##[debug]Evaluating succeeded:
2024-03-14T13:28:55.4879262Z ##[debug]=> True
2024-03-14T13:28:55.4893476Z ##[debug]Result: True
2024-03-14T13:28:55.4955422Z ##[section]Starting: [OMITTED]
2024-03-14T13:28:56.6013212Z ==============================================================================
2024-03-14T13:28:56.6014659Z Task         : SSH
2024-03-14T13:28:56.6015878Z Description  : Run shell commands or a script on a remote machine using SSH
2024-03-14T13:28:56.6019328Z Version      : 0.236.2
2024-03-14T13:28:56.6020545Z Author       : Microsoft Corporation
2024-03-14T13:28:56.6021876Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh
2024-03-14T13:28:56.6023048Z ==============================================================================
2024-03-14T13:28:56.6544760Z ##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.
2024-03-14T13:28:56.6568923Z ##[debug]System.InvalidOperationException: A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2024-03-14T13:28:56.6577176Z ##[section]Finishing: [OMITTED]
</pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre>
2024-03-13T12:13:57.5508201Z ##[section]Starting: [OMITTED]
2024-03-13T12:13:57.6514823Z ==============================================================================
2024-03-13T12:13:57.6515853Z Task         : SSH
2024-03-13T12:13:57.6516624Z Description  : Run shell commands or a script on a remote machine using SSH
2024-03-13T12:13:57.6517085Z Version      : 0.231.3
2024-03-13T12:13:57.6517719Z Author       : Microsoft Corporation
2024-03-13T12:13:57.6518550Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh
2024-03-13T12:13:57.6519277Z ==============================================================================
2024-03-13T12:13:59.6765585Z Trying to establish an SSH connection to [OMITTED]
2024-03-13T12:13:59.8829161Z Successfully connected.
[OMITTED]
2024-03-13T12:14:44.2068275Z Removing zip and package directory
2024-03-13T12:14:44.2069238Z 
2024-03-13T12:14:44.2069622Z Finished
2024-03-13T12:14:44.2069844Z 
2024-03-13T12:14:45.6250348Z ##[section]Finishing: [OMITTED] 
</pre>
</details>

### Repro steps

```yml
1. have Windows 10 x64 agent (presumably self-hosted, at version 2.204.x)
2. attempt to use SSHv0 task at version 0.236.x
3. task fails due to not having compat execution tool
```

**Comment by DmitriiBobreshev** [comment]
Hi @Metarract, thanks for the feedback. 
The node10 runner was removed because dependent packages [do not support](https://github.com/theophilusx/ssh2-sftp-client/blob/master/package.json#L21) node10.

We have a [task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/node-task-runner-installer-v0?view=azure-pipelines) when the runner is missing in the agent, but, unfortunately, it will not work with an old agent, because it works only for previous node versions (e.g. agent has node 16 handler and had node 10, the task could install node 10 for such agent). 

One of the options is that you can [pin](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-versions) the task version in the yml file (e.g. SSH@0.231.3) to use older version but it may contain some [bugs](https://github.com/microsoft/azure-pipelines-tasks/issues/19067), or update your agent(you need agent's version at least [2.206.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.206.1) where node16 runner was introduced). 
We apologise for the inconvenience

**Comment by Metarract** [comment]
fair enough, cheers; i assume it would make sense to bump the minimum agent version to 2.206.1 in the task json then? i see a pr out to fix it in the docs at the very least

**Comment by DmitriiBobreshev** [comment]
You're right, we'll bump minimumAgentVersion to 2.206.1, thank you!

**Comment by kirill-ivlev** [comment]
@Metarract, thank you reporting this!
I'd like to add that we highly recommend you upgrade you agent to more modern version, [v2.x is not supported], with each agent iteration we deliver important security fixes & improvements (https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v3-agent?view=azure-devops#can-i-stay-on-2x-agents-if-im-not-working-on-any-changes-in-my-project-anymore)

**Comment by Metarract** [comment]
@kirill-ivlev yeah previously we were just letting them update as-needed and didn't realize that they were so far behind as a result; went around updating them all for this reason but also since the team in question had several deployments waiting around.

---
Also i saw this got merged in last week and a new release was made just a couple days ago so i'm gonna just close this if that's fine; thank you very much everyone!
