### ISSUE TITLE
[BUG]: GoTool@0 doesn't support downloading Go 1.21 or above.

### ISSUE THREAD

**Issue by matthchr** [microsoft/azure-pipelines-tasks#19690]
### New issue checklist

- [ ] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

GoTool

### Task version

0

### Issue Description

GoTool tries to download all Golang releases from a path like: `https://storage.googleapis.com/golang/go1.22.linux-amd64.tar.gz`, but after Go 1.20 there are no longer published binaries at this path. Instead the URL `https://golang.org/dl/` should be used, as you can see on the official Golang site: https://go.dev/dl/

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu latest

### Relevant log output

```shell
Starting: Get Go 1.22
==============================================================================
Task         : Go tool installer
Description  : Find in cache or download a specific version of Go and add it to the PATH
Version      : 0.231.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/go-tool
==============================================================================
Downloading: https://storage.googleapis.com/golang/go1.22.linux-amd64.tar.gz
##[error]Failed to download version 1.22. Please verify that the version is valid and resolve any other issues. Error: Unexpected HTTP response: 404
    at Object.<anonymous> (/home/vsts/work/_tasks/GoTool_334727f4-9495-4f9d-a391-fc621d671474/0.231.0/node_modules/azure-pipelines-tool-lib/tool.js:216:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/_tasks/GoTool_334727f4-9495-4f9d-a391-fc621d671474/0.231.0/node_modules/azure-pipelines-tool-lib/tool.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  httpStatusCode: 404
}
Finishing: Get Go 1.22
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
- task: GoTool@0
      displayName: Get Go 1.22
      inputs:
        version: '1.22'
```

**Comment by TrevorChristman** [comment]
Hi, I'm having this problem also, and I'm unable to consume go 1.22.

Is there any workaround?  Is there any schedule for correcting the GoTool step?

**Comment by huliang-microsoft** [comment]
I have the same issue, will this be fixed?

**Comment by debben** [comment]
I'm having a similar issue but I'm wondering if for the fix here, the download URL could be configurable either as an input or overridden with an environment variable. In my case I have an artifactory instance acting as a proxying cache for requests to `https://storage.googleapis.com/golang/%s`. Also, is it possible to support wildcarded versions (1.22.*) similar to some of the dotnet tasks? I frequently re-bake runner images and the way that installer works is to grab the highest patch version
https://github.com/actions/runner-images/blob/584c7c0fef943495221b46033addefb6419ecb0f/images/ubuntu/toolsets/toolset-2204.json#L46C1-L48C25

**Comment by RichardChen820** [comment]
I'm stumbling by the same problem, any plan to fix or workaround?

**Comment by enzobrands** [comment]
Adding the patch version (1.22.3) to the version variable does work, if that helps anyone.

**Comment by sevenate** [comment]
It would be nice to have a "latest" as a valid input argument for `version` parameter for cases when you don't really care.

**Comment by nikolaigut** [comment]
I had the same problem. @enzobrands solution worked.

**Comment by TrevorChristman** [comment]
> This issue is stale because it has been open for 180 days with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days

Come on my dudes, we're better than this.

**Comment by thiagodemoura** [comment]
I have the same issue, will this be fixed?

**Comment by Googlom** [comment]
This small indie company don't have capacity to fix this.

**Comment by bicisteadm** [comment]
Same problem here, why don't you want to fix it? @viralpandya

**Comment by JiandongRuan** [comment]
Urgent fix is required since this now fails for all Go versions. `https://storage.googleapis.com` is no longer accessible to the public. It now returns 403 (instead of 404)

**Comment by bpm-alaska** [comment]
Looks like a fix is on the way: https://github.com/microsoft/azure-pipelines-tasks/pull/21389

**Comment by rm-dmiri** [comment]
This issue should have been resolved by the download URL change available starting with task version 0.264.0.
Please upgrade to that version. If the issue persists, feel free to open a new GitHub issue with updated details.
