### ISSUE TITLE
[BUG]: The term 'Invoke-VstsProcess' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by aelij** [microsoft/azure-pipelines-tasks#19832]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFileCopy

### Task version

6.238.11

### Issue Description

See log below

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Relevant log output

```shell
##[error]The term 'Invoke-VstsProcess' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[debug]Processed: ##vso[task.logissue type=error]The term 'Invoke-VstsProcess' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[debug]Leaving Initialize-AzModule.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]There was an error with the service principal used for the deployment.
##[debug]At D:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\6.238.11\ps_modules\VstsAzureHelpers_\InitializeAzModuleFunctions.ps1:296 char:13
##[debug]+             throw (New-Object System.Exception((Get-VstsLocString -Ke ...
##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : OperationStopped: (:) [], Exception
##[debug]    + FullyQualifiedErrorId : There was an error with the service principal used for the deployment.
##[debug] 
##[debug]Script stack trace:
##[debug]at Initialize-AzSubscription, D:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\6.238.11\ps_modules\VstsAzureHelpers_\InitializeAzModuleFunctions.ps1: line 296
##[debug]at Initialize-AzModule, D:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\6.238.11\ps_modules\VstsAzureHelpers_\InitializeAzModuleFunctions.ps1: line 91
##[debug]at <ScriptBlock>, D:\a\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\6.238.11\AzureFileCopy.ps1: line 66
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Exception: There was an error with the service principal used for the deployment. ---> System.Management.Automation.CommandNotFoundException: The term 'Invoke-VstsProcess' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
##[debug]   --- End of inner exception stack trace ---
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by daxianji007** [comment]
I meet the same issue. Please speed this up

**Comment by v-schhabra** [comment]
https://github.com/microsoft/azure-pipelines-tasks/pull/19827
