### ISSUE TITLE
[BUG]: build.gradle.kts not recognized when enabling code coverage

### ISSUE THREAD

**Issue by erosb** [microsoft/azure-pipelines-tasks#19937]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Gradle

### Task version

3

### Issue Description

My gradle build file is a kotlin file, `build.gradle.kts` , and not `build.gradle`. The `.kts` file isn't recognized when the task wants to enable code coverage. See the attached log output: it complains about missing `build.gradle` file and doesn't try to look for `build.gradle.kts`. At the first glance, it happens because the filename is hardcoded here: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/GradleV3/Modules/code-coverage.ts#L19

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Relevant log output

```shell
##[warning]Unable to append code coverage data: Error: File or folder doesn't exist: /home/vsts/work/1/s/build.gradle
    at Object.appendTextToFileSync (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-tasks-codecoverage-tools/utilities.js:80:15)
    at JacocoGradleCodeCoverageEnabler.enableCodeCoverage (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-tasks-codecoverage-tools/jacoco/jacoco.gradle.ccenabler.js:37:18)
    at Object.enableCodeCoverageAsync (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/Modules/code-coverage.js:34:32)
    at /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:92:43
    at Generator.next (<anonymous>)
    at /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:4:12)
    at run (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:27:12)
    at Object.<anonymous> (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:154:1)
##[warning]Failed to enable code coverage: Unable to append code coverage data: Error: File or folder doesn't exist: /home/vsts/work/1/s/build.gradle
    at Object.appendTextToFileSync (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-tasks-codecoverage-tools/utilities.js:80:15)
    at JacocoGradleCodeCoverageEnabler.enableCodeCoverage (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-tasks-codecoverage-tools/jacoco/jacoco.gradle.ccenabler.js:37:18)
    at Object.enableCodeCoverageAsync (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/Modules/code-coverage.js:34:32)
    at /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:92:43
    at Generator.next (<anonymous>)
    at /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:4:12)
    at run (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:27:12)
    at Object.<anonymous> (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/gradletask.js:154:1)
/home/vsts/work/1/s/gradlew clean build jacocoTestReport
```

**Comment by kirill-ivlev** [comment]
Hi @erosb, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by erosb** [comment]
Hello, can this be prioritized any time soon?

**Comment by JG9A** [comment]
this is still an issue in azure pipelines
