### ISSUE TITLE
[BUG]: Gradle task Code analysis failed if test task has failures

### ISSUE THREAD

**Issue by itkhanz** [microsoft/azure-pipelines-tasks#20052]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Gradle@3 - Gradle v3 task

### Task version

3

### Issue Description

I am running my java TestNG tests using Gradle task in Azure Pipelines. If gradle build is failed due to failed test cases, then it the gradle task throws following error that 

**_##[error]Code analysis failed. Gradle exit code: -1. Error: Error: The process '/__w/11/s/gradlew' failed with exit code 1_**

This issue is only happening within Azure Pipelines, and I do not get this error upon failing tests while running tests locally. I get this error after the test task is finished, and even though all the tests are executed (regardless of passing or failing), I do not get why this error is thrown when there is a failed test.

Here are the debug logs from Azure pipeline task:-

```
-----------------------------------------------------------------
|  Results: FAILURE (85 tests, 79 passed, 5 failed, 1 skipped)  |
-----------------------------------------------------------------

85 tests completed, 5 failed, 1 skipped

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests

* Try:
> Run with --scan to get full insights.

BUILD FAILED in 2h 3m 6s
Test report disabled, omitting generation of the HTML test report.
5 actionable tasks: 5 executed
Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.

##[debug]Exit code 1 received from tool '/__w/1/s/gradlew'
##[debug]STDIO streams have closed for tool '/__w/1/s/gradlew'
Error: The process '/__w/1/s/gradlew' failed with exit code 1
    at ExecState._setResult (/__w/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-task-lib/toolrunner.js:943:25)
    at ExecState.CheckComplete (/__w/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-task-lib/toolrunner.js:926:18)
    at ChildProcess.<anonymous> (/__w/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-task-lib/toolrunner.js:839:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
##[debug]taskRunner fail
##[debug]Processing code analysis results
##[debug]System.DefaultWorkingDirectory=/__w/1/s
##[debug]build.artifactStagingDirectory=/__w/1/a
........
##[debug]Entering ParseTestResultFiles
##[debug]runContext.ReleaseURI is null
##[debug]runContext.ReleaseEnvironmentUri is null
##[debug]Reading test results from file '/agent/_work/1/s/build/testng/junitreports/TEST-com.dcs.appium.testing.tests.DebugTest.xml'.
##[debug]Only single test suite found, parsing its information.
##[debug]Timestamp is not available for one or more testsuites. Total run duration is being calculated as the sum of time durations of detected testsuites.
##[debug]Total test results: 1.
##[debug]Leaving ParseTestResultFiles
##[debug]Processed: ##vso[results.publish type=JUnit;mergeResults=true;publishRunAttachments=true;resultFiles=/__w/1/s/build/testng/junitreports/TEST-com.appium.testing.tests.DebugTest.xml;testRunSystem=VSTS - gradle;]
##[debug]task result: Failed
##[debug]runContext.ReleaseURI is null
##[debug]runContext.ReleaseEnvironmentUri is null
##[debug]Entering PublishAllTestResultsToSingleTestRunAsync
##[error]Code analysis failed. Gradle exit code: -1. Error: Error: The process '/__w/1/s/gradlew' failed with exit code 1
##[debug]Uploading build level attachements individually
##[debug]Processed: ##vso[task.issue type=error;]Code analysis failed. Gradle exit code: -1. Error: Error: The process '/__w/1/s/gradlew' failed with exit code 1
##[debug]Processed: ##vso[task.complete result=Failed;]Code analysis failed. Gradle exit code: -1. Error: Error: The process '/__w/1/s/gradlew' failed with exit code 1
##[debug]Handler exit code: 0
```

Here is how my pipeline looks like:

```
- job: run_tests
  displayName: Run E2E Tests
  timeoutInMinutes: 180
  container:
    image: gradle:8-jdk17
  steps:
    - task: Gradle@3
    displayName: 'Execute gradle test'
    continueOnError: true
    inputs:
      gradleWrapperFile: 'gradlew'
      options: ${{ variables.gradleParameters }}
      tasks: test --info
```

My project is configured to run on JDK 17, and Gradle wrapper version 8.8. Here is how JDK is configured in `build.gradle`:
```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
```

If I run the same task with same configuration, and the test case passes, then i do not get above error. so this error is probably coming from gradle test task where it is unable to handle test failure presumably while executing `ParseTestResultFiles` or `PublishAllTestResultsToSingleTestRunAsync` as evident from logs.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Linux AMD64

### Relevant log output

```shell
2024-06-23T17:34:44.656+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2024-06-23T17:34:44.657+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
2024-06-23T17:34:44.657+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2024-06-23T17:34:44.657+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2024-06-23T17:34:44.657+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':test'.
2024-06-23T17:34:44.657+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > There were failing tests
2024-06-23T17:34:44.657+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2024-06-23T17:34:44.657+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2024-06-23T17:34:44.657+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --scan to get full insights.
2024-06-23T17:34:44.657+0000 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
2024-06-23T17:34:44.658+0000 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1m 42s
2024-06-23T17:34:44.659+0000 [LIFECYCLE] [org.gradle.internal.buildevents.TaskExecutionStatisticsReporter] 5 actionable tasks: 5 executed
2024-06-23T17:34:44.661+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Build finished for file system watching' started
2024-06-23T17:34:44.664+0000 [INFO] [org.gradle.internal.watch.registry.impl.WatchableHierarchies] Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.
2024-06-23T17:34:44.668+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Build finished for file system watching'
2024-06-23T17:34:44.668+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Build finished for file system watching' completed
............
2024-06-23T17:34:44.741+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
2024-06-23T17:34:44.820+0000 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@30d4a390
2024-06-23T17:34:44.820+0000 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 25: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
2024-06-23T17:34:44.821+0000 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Success[value=org.gradle.launcher.exec.BuildActionResult@971e903] from daemon DaemonInfo{pid=373, address=[gr34dgrg-1bbb-432f-a38c-887cffrëaae6 port:123456, addresses:[/127.0.0.1]], state=Busy, lastBusy=1719163987892, context=DefaultDaemonContext[uid=5139cd6e-9e7c-402b-a7f6-468547,javaHome=/opt/java/openjdk,javaVersion=17,daemonRegistryDir=/home/AzDevOps_azpcontainer/.gradle/daemon,pid=373,idleTimeout=10800000,priority=NORMAL,applyInstrumentationAgent=true,nativeServicesMode=ENABLED,daemonOpts=--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=384m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
2024-06-23T17:34:44.821+0000 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
2024-06-23T17:34:44.822+0000 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
2024-06-23T17:34:44.826+0000 [LIFECYCLE] [org.gradle.launcher.cli.DebugLoggerWarningAction] 
#############################################################################
   WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

   Debug level logging will leak security sensitive information!

   For more details, please refer to https://docs.gradle.org/8.8/userguide/logging.html#sec:debug_security in the Gradle documentation.
#############################################################################

##[debug]Exit code 1 received from tool '/__w/1/s/gradlew'
##[debug]STDIO streams have closed for tool '/__w/1/s/gradlew'
Error: The process '/__w/1/s/gradlew' failed with exit code 1
    at ExecState._setResult (/__w/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-task-lib/toolrunner.js:943:25)
    at ExecState.CheckComplete (/__w/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-task-lib/toolrunner.js:926:18)
    at ChildProcess.<anonymous> (/__w/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-task-lib/toolrunner.js:839:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

### Full task logs with system.debug enabled

<details>
  <pre> 
##[debug]Exit code 1 received from tool '/__w/1/s/gradlew'
##[debug]STDIO streams have closed for tool '/__w/1/s/gradlew'
Error: The process '/__w/1/s/gradlew' failed with exit code 1
    at ExecState._setResult (/__w/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-task-lib/toolrunner.js:943:25)
    at ExecState.CheckComplete (/__w/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-task-lib/toolrunner.js:926:18)
    at ChildProcess.<anonymous> (/__w/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/3.238.0/node_modules/azure-pipelines-task-lib/toolrunner.js:839:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
##[debug]taskRunner fail
##[debug]Processing code analysis results
##[debug]System.DefaultWorkingDirectory=/__w/1/s
##[debug]build.artifactStagingDirectory=/__w/1/a
........
##[debug]Entering ParseTestResultFiles
##[debug]runContext.ReleaseURI is null
##[debug]runContext.ReleaseEnvironmentUri is null
##[debug]Reading test results from file '/agent/_work/1/s/build/testng/junitreports/TEST-com.dcs.appium.testing.tests.DebugTest.xml'.
##[debug]Only single test suite found, parsing its information.
##[debug]Timestamp is not available for one or more testsuites. Total run duration is being calculated as the sum of time durations of detected testsuites.
##[debug]Total test results: 1.
##[debug]Leaving ParseTestResultFiles
##[debug]Processed: ##vso[results.publish type=JUnit;mergeResults=true;publishRunAttachments=true;resultFiles=/__w/1/s/build/testng/junitreports/TEST-com.appium.testing.tests.DebugTest.xml;testRunSystem=VSTS - gradle;]
##[debug]task result: Failed
##[debug]runContext.ReleaseURI is null
##[debug]runContext.ReleaseEnvironmentUri is null
##[debug]Entering PublishAllTestResultsToSingleTestRunAsync
##[error]Code analysis failed. Gradle exit code: -1. Error: Error: The process '/__w/1/s/gradlew' failed with exit code 1
##[debug]Uploading build level attachements individually
##[debug]Processed: ##vso[task.issue type=error;]Code analysis failed. Gradle exit code: -1. Error: Error: The process '/__w/1/s/gradlew' failed with exit code 1
##[debug]Processed: ##vso[task.complete result=Failed;]Code analysis failed. Gradle exit code: -1. Error: Error: The process '/__w/1/s/gradlew' failed with exit code 1
##[debug]Handler exit code: 0
  </pre>
</details>

### Repro steps

```yml
- job: run_tests
  displayName: Run E2E Tests
  timeoutInMinutes: 180
  container:
    image: gradle:8-jdk17
  steps:
    - task: Gradle@3
    displayName: 'Execute gradle test'
    continueOnError: true
    inputs:
      gradleWrapperFile: 'gradlew'
      options: ${{ variables.gradleParameters }}
      tasks: test --info
```

**Comment by ismayilov-ismayil** [comment]
Hi @itkhanz,  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by kool79** [comment]
Same issue on my site.
Just want to add that we have the next log line (see last line below) when execution started. Note that in my case I don't enable any code analysis: ll checkboxes in the 'Code analyses' section are empty.
```
2024-09-11T10:32:18.1795730Z ##[section]Starting: Test Execution
2024-09-11T10:32:18.1800934Z ==============================================================================
2024-09-11T10:32:18.1801058Z Task         : Gradle
2024-09-11T10:32:18.1801110Z Description  : Build using a Gradle wrapper script
2024-09-11T10:32:18.1801200Z Version      : 3.244.1
2024-09-11T10:32:18.1801253Z Author       : Microsoft Corporation
2024-09-11T10:32:18.1801461Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/gradle
2024-09-11T10:32:18.1801560Z ==============================================================================
2024-09-11T10:32:18.4093772Z ##[warning]Used 'chmod' method for gradlew file to make it executable.
2024-09-11T10:32:18.4195316Z Code analysis is disabled outside of the build environment. Could not find a value for: build.artifactStagingDirectory
```

**Comment by itkhanz** [comment]
This issue is still waiting for resolution!

**Comment by mishrarish** [comment]
@itkhanz Could you confirm what are command you are running locally which is giving build successful. did build pipeline succeeded with failing test cases?

**Comment by itkhanz** [comment]
> [@itkhanz](https://github.com/itkhanz) Could you confirm what are command you are running locally which is giving build successful. did build pipeline succeeded with failing test cases?

`./gradlew clean test`

I am using JDK 21 and Gradle 8.13
