### ISSUE TITLE
[REGRESSION]: Error when deploying to app service

### ISSUE THREAD

**Issue by evertonlsouza** [microsoft/azure-pipelines-tasks#20157]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Azure App Service Deploy

### Breaking task version

4.242.0

### Last working task version

 4.238.1

### Regression Description

I have a problem with two releases, both deploy to the same app service, however, in different virtual paths, I am using the Azure App Service Deploy task in version 4.

The first pipeline gives the following error:
Error: (7/16/2024 2:12:19 PM) An error occurred when the request was processed on the remote computer.

The second pipeline gives the following error:
##[error]Error: Malicious entry: xxxx\xxxxx\

Searching the community for all possible solutions, they say to use version 4 of the task that I'm already using.

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows server 2022

### Relevant log output

```shell
First pipe:
2024-07-16T17:24:36.2197164Z Info: Adding file (webapp-asp-plataforma-app-trusthub-dev/Relatorios\bin\xxxxx.Web.Autenticacao.Utils.Mvc.dll).
2024-07-16T17:24:36.2197950Z Info: Adding file (webapp-asp-xxxxx-dev/Relatorios\bin\Content\).
2024-07-16T17:24:36.2198639Z Info: Adding file (webapp-asp-xxxxx-dev/Relatorios\bin\Content\img\archive.png).
2024-07-16T17:24:38.2564223Z ##[error]Error: Error: (7/16/2024 2:24:36 PM) An error occurred when the request was processed on the remote computer.
Error: Could not find a part of the path 'C:\home\site\wwwroot\Relatorios\bin\Content\img\archive.png'.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileStreamEx.CreateInstance(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Nullable`1 fileLength)
   at Microsoft.Web.Deployment.FilePathProviderBase.Add(DeploymentObject source, Boolean whatIf)
   at Microsoft.Web.Deployment.DeploymentObject.AddChild(DeploymentObject source, Int32 position, DeploymentSyncContext syncContext)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAddChild(DeploymentObject destParent, DeploymentObject sourceObject, Int32 position)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData asyncData, Nullable`1 passId, String user, String siteName)


Second pipe:
024-07-16T17:31:15.4082278Z Folders: 16
2024-07-16T17:31:15.4082481Z Files: 935
2024-07-16T17:31:15.4082609Z Size:       109177767
2024-07-16T17:31:15.4082763Z Compressed: 31659160
2024-07-16T17:31:15.4250955Z ##[error]Error: Malicious entry: Areas\ControleAtividade\
```

### Full task logs with system.debug enabled

2024-07-16T17:57:11.6149887Z ##[debug]Agent running environment resource - Disk:D:\ Data available:31876.00MB out of 131053.00MB, Memory: used 31MB out of 16382MB, CPU: usage 2.43
2024-07-16T17:57:15.2983511Z ##[debug]Exit code 4294967295 received from tool 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2024-07-16T17:57:15.2984012Z ##[debug]Exit code 4294967295 received from tool 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2024-07-16T17:57:15.2984420Z ##[debug]STDIO streams have closed for tool 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2024-07-16T17:57:15.2984802Z ##[debug]STDIO streams have closed for tool 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2024-07-16T17:57:15.2988736Z ##[debug]{}
2024-07-16T17:57:15.2989102Z ##[debug]System.DefaultWorkingDirectory=D:\agents\xxxx\Pool-Default\agent-4\_work\r169\a
2024-07-16T17:57:15.3008404Z ##[debug]Deployment Failed with Error: Error: Error: (7/16/2024 2:57:11 PM) An error occurred when the request was processed on the remote computer.
Error: Could not find a part of the path 'C:\home\site\wwwroot\Relatorios\bin\Content\img\archive.png'.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileStreamEx.CreateInstance(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Nullable`1 fileLength)
   at Microsoft.Web.Deployment.FilePathProviderBase.Add(DeploymentObject source, Boolean whatIf)
   at Microsoft.Web.Deployment.DeploymentObject.AddChild(DeploymentObject source, Int32 position, DeploymentSyncContext syncContext)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAddChild(DeploymentObject destParent, DeploymentObject sourceObject, Int32 position)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData asyncData, Nullable`1 passId, String user, String siteName)
Error count: 1.

2024-07-16T17:57:15.3011253Z ##[debug]task result: Failed
2024-07-16T17:57:15.3050163Z ##[error]Error: Error: (7/16/2024 2:57:11 PM) An error occurred when the request was processed on the remote computer.
Error: Could not find a part of the path 'C:\home\site\wwwroot\Relatorios\bin\Content\img\archive.png'.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileStreamEx.CreateInstance(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Nullable`1 fileLength)
   at Microsoft.Web.Deployment.FilePathProviderBase.Add(DeploymentObject source, Boolean whatIf)
   at Microsoft.Web.Deployment.DeploymentObject.AddChild(DeploymentObject source, Int32 position, DeploymentSyncContext syncContext)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAddChild(DeploymentObject destParent, DeploymentObject sourceObject, Int32 position)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData asyncData, Nullable`1 passId, String user, String siteName)
Error count: 1.

2024-07-16T17:57:15.3054220Z ##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]Error: Error: (7/16/2024 2:57:11 PM) An error occurred when the request was processed on the remote computer.
Error: Could not find a part of the path 'C:\home\site\wwwroot\Relatorios\bin\Content\img\archive.png'.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileStreamEx.CreateInstance(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Nullable`1 fileLength)
   at Microsoft.Web.Deployment.FilePathProviderBase.Add(DeploymentObject source, Boolean whatIf)
   at Microsoft.Web.Deployment.DeploymentObject.AddChild(DeploymentObject source, Int32 position, DeploymentSyncContext syncContext)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAddChild(DeploymentObject destParent, DeploymentObject sourceObject, Int32 position)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData asyncData, Nullable`1 passId, String user, String siteName)
Error count: 1.

2024-07-16T17:57:15.3059786Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error: (7/16/2024 2:57:11 PM) An error occurred when the request was processed on the remote computer.
Error: Could not find a part of the path 'C:\home\site\wwwroot\Relatorios\bin\Content\img\archive.png'.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileStreamEx.CreateInstance(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Nullable`1 fileLength)
   at Microsoft.Web.Deployment.FilePathProviderBase.Add(DeploymentObject source, Boolean whatIf)
   at Microsoft.Web.Deployment.DeploymentObject.AddChild(DeploymentObject source, Int32 position, DeploymentSyncContext syncContext)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAddChild(DeploymentObject destParent, DeploymentObject sourceObject, Int32 position)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData asyncData, Nullable`1 passId, String user, String siteName)
Error count: 1.

2024-07-16T17:57:15.3062450Z ##[debug]Application Insights is not configured for the App Service. Skipping adding release annotation.
2024-07-16T17:57:15.3063069Z ##[debug]Azure_App_Service_Deploy_PackageArtifactAlias=_Web-xxxxx
2024-07-16T17:57:15.3063439Z ##[debug]release.releaseId=7383
2024-07-16T17:57:15.3063771Z ##[debug]release.releaseName=Web-xxxx-6
2024-07-16T17:57:15.3064329Z ##[debug]system.TeamFoundationCollectionUri=https://dev.azure.com/xxxxxx/
2024-07-16T17:57:15.3064723Z ##[debug]system.teamProjectId=9359a092-4209-458e-ac03-bb6e222c4641
2024-07-16T17:57:15.3065285Z ##[debug]release.requestedfor=xxxxxx
2024-07-16T17:57:15.3065938Z ##[debug]Artifact Source Alias is: _Web-xxxx
2024-07-16T17:57:15.3066463Z ##[debug]release.artifacts._Web-V5-Relatorios.sourceVersion=509894fefb91cf468a838dc03887f203a42db5fc
2024-07-16T17:57:15.3066843Z ##[debug]release.artifacts._Web-V5-Relatorios.repository.provider=TfsGit
2024-07-16T17:57:15.3067189Z ##[debug]release.artifacts._Web-V5-Relatorios.repository.name=Web-V5-Relatorios
2024-07-16T17:57:15.3067712Z ##[debug]release.artifacts._Web-V5-Relatorios.sourcebranchname=merge
2024-07-16T17:57:15.3068033Z ##[debug]release.artifacts._Web-V5-Relatorios.type=Build
2024-07-16T17:57:15.3068345Z ##[debug]release.artifacts._Web-V5-Relatorios.buildId=312059
2024-07-16T17:57:15.3068682Z ##[debug]release.artifacts._Web-V5-Relatorios.buildNumber=312059
2024-07-16T17:57:15.3069023Z ##[debug]release.artifacts._Web-V5-Relatorios.projectId=9359a092-4209-458e-ac03-bb6e222c4641
2024-07-16T17:57:15.3069382Z ##[debug]build.buildUri=vstfs:///Build/Build/312059
2024-07-16T17:57:15.3069689Z ##[debug]release.releaseUri=vstfs:///ReleaseManagement/Release/7383
2024-07-16T17:57:15.3069981Z ##[debug]build.buildId=312059
2024-07-16T17:57:15.3070267Z ##[debug]release.releaseId=7383
2024-07-16T17:57:15.3070539Z ##[debug]build.buildNumber=312059
2024-07-16T17:57:15.3070833Z ##[debug]release.releaseName=Web-V5xxxxx-6
2024-07-16T17:57:15.3071182Z ##[debug]system.TeamFoundationCollectionUri=https://dev.azure.com/xxxxxx/
2024-07-16T17:57:15.3071763Z ##[debug]system.teamProjectId=9359a092-4209-458e-ac03-bb6e222c4641
2024-07-16T17:57:15.3072280Z ##[debug]build.sourceVersion=509894fefb91cf468a838dc03887f203a42db5fc
2024-07-16T17:57:15.3072608Z ##[debug]build.repository.name=Web-V5-Relatorios
2024-07-16T17:57:15.3072908Z ##[debug]build.repository.provider=TfsGit
2024-07-16T17:57:15.3073220Z ##[debug]system.teamproject=xxxxxx
2024-07-16T17:57:15.3074014Z ##[debug]setting affinity cookie ["ARRAffinity=571ab93ebbf10a7b3be662f93adeca3108443e60964b44308283082086191b66;Path=/;HttpOnly;Secure;Domain=webapp-asp-plataforma-app-trusthub-dev.scm.azurewebsites.net","ARRAffinitySameSite=571ab93ebbf10a7b3be662f93adeca3108443e60964b44308283082086191b66;Path=/;HttpOnly;SameSite=None;Secure;Domain=xxxxxxxxxx-dev.scm.azurewebsites.net"]
2024-07-16T17:57:15.3074610Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-07-16T17:57:15.3075648Z ##[debug][PUT]https://$xxxxxxxxx-dev:***@xxxxxxxxxxx-dev.scm.azurewebsites.net/api/deployments/73831721152635292
2024-07-16T17:57:16.1759777Z ##[debug]updateDeployment. Data: {"statusCode":200,"statusMessage":"OK","headers":{"content-length":"1245","content-type":"application/json; charset=utf-8","date":"Tue, 16 Jul 2024 17:57:16 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","pragma":"no-cache","x-ms-request-id":"64456a9d-4e87-4968-952a-05572bfd1e5a","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"},"body":{"id":"73831721152635292","status":3,"status_text":null,"author_email":null,"author":"Everton Lima de Souza","deployer":"VSTS","message":"{\"type\":\"Deployment\",\"commitId\":\"509894fefb91cf468a838dc03887f203a42db5fc\",\"buildId\":\"312059\",\"releaseId\":\"7383\",\"buildNumber\":\"312059\",\"releaseName\":\"Web-V5-Relatorios - Copy-6\",\"repoProvider\":\"TfsGit\",\"repoName\":\"Web-V5-Relatorios\",\"collectionUrl\":\"https://dev.azure.com/xxxxxxx/\",\"teamProject\":\"9359a092-4209-458e-ac03-bb6e222c4641\",\"buildProjectUrl\":\"https://dev.azure.com/xxxxxx/9359a092-4209-458e-ac03-bb6e222c4641\",\"repositoryUrl\":\"\",\"branch\":\"merge\",\"teamProjectName\":\"xxxxxx\",\"slotName\":\"production\"}","progress":null,"received_time":"0001-01-01T00:00:00","start_time":"2024-07-16T17:57:15.935396Z","end_time":"2024-07-16T17:57:15.935396Z","last_success_end_time":null,"complete":false,"active":false,"is_temp":false,"is_readonly":false,"url":"https://xxxxx-dev.scm.azurewebsites.net/api/deployments/73831721152635292","log_url":"https://xxxxxxxx-dev.scm.azurewebsites.net/api/deployments/73831721152635292/log","site_name":null,"provisioningState":"Failed"}}
2024-07-16T17:57:16.1762232Z Successfully updated deployment History at https://xxxxxxxxx-dev.scm.azurewebsites.net/api/deployments/73831721152635292
2024-07-16T17:57:16.1762653Z ##[debug]Active DeploymentId :73831721152635292
2024-07-16T17:57:16.1786222Z App Service Application URL: https://xxxxxxx-dev.azurewebsites.net/Relatorios
2024-07-16T17:57:16.1786941Z ##[debug]set AppServiceApplicationUrl=https://xxxxxxxxx-dev.azurewebsites.net/Relatorios
2024-07-16T17:57:16.1788625Z ##[debug]Processed: ##vso[task.setvariable variable=AppServiceApplicationUrl;isOutput=false;issecret=false;]https://xxxxxxxx-dev.azurewebsites.net/Relatorios
2024-07-16T17:57:16.1792887Z ##[debug]Deployment failed

### Repro steps

```yml
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Trusthub'
  inputs:
    azureSubscription: 'xxxxx AZ DEV (EA)'
    WebAppName: 'xxxxxxx-dev'
    VirtualApplication: /Relatorios
    packageForLinux: '$(System.ArtifactsDirectory)\$(Release.PrimaryArtifactSourceAlias)\$(Build.BuildNumber)\*.zip'
    enableCustomDeployment: true
    RemoveAdditionalFilesFlag: true
```

**Comment by evertonlsouza** [comment]
Note. 
Before the deploy task, I have a powershell script that edits appsettings, when I disable this powershell task the deployment is done, but when I run the powershell script before deploying it, the error occurs. The powershell in line task is in version 2.4.2.1. It was running until 05/15/2024

Script:
```
$environment = "dev"
$application = "xxxxxx"

$workDir = -Join($Env:SYSTEM_DEFAULTWORKINGDIRECTORY, '\', $Env:RELEASE_PRIMARYARTIFACTSOURCEALIAS, '\', $Env:BUILD_BUILDNUMBER)

$artifact = -Join($workDir, '\*.zip')
$stage = -Join($workDir, '\stage')
$transformed = -Join($workDir, "\", $Env:BUILD_BUILDNUMBER, ".zip")

function Replace() {
	
	$configs = Get-ChildItem $workDir  -Recurse -Include "*.config", "appsettings.json", "appSettings.json", "ConnectedService.json" | foreach-object {$_.Fullname}

	foreach ($c in $configs) {
	   
		$isJson = ($c -Match 'appsettings.json')

		# le o conteudo do config
		$config = [System.IO.File]::ReadAllText($c)
		$newConfig = $config

		Write-Output "Lendo $c"
		
		if ($application -eq "xxxxxx") {

			if ($environment -eq "dev") {
				$newConfig = $newConfig -replace "https://app.dev.xxxxxx.com.br/v2/","https://xxxxxxdev.xxxxxx.com.br/"
                        	$newConfig = $newConfig -replace "https://appdev.xxxxxx.com.br/v2/","https://xxxxxxdev.xxxxxx.com.br/"
			} 
			elseif ($environment -eq "qa") {
				$newConfig = $newConfig -replace "https://app.qa.xxxxxx.com.br/v2/","https://xxxxxxqa.xxxxxx.com.br/"
                       		$newConfig = $newConfig -replace "https://appqa.xxxxxx.com.br/v2/","https://xxxxxxqa.xxxxxx.com.br/"
			} 
			elseif ($environment -eq "hml") {
				$newConfig = $newConfig -replace "https://homologacao.app.xxxxxx.com.br/v2/","https://xxxxxxhml.xxxxxx.com.br/"
                        	$newConfig = $newConfig -replace "https://apphml.xxxxxx.com.br/v2/","https://xxxxxxhml.xxxxxx.com.br/"
			} 
			elseif ($environment -eq "val") {
				$newConfig = $newConfig -replace "https://validacaoapp.xxxxxx.com.br/v2/","https://xxxxxxval.xxxxxx.com.br/"
			} 
			elseif ($environment -eq "prd") {
				$newConfig = $newConfig -replace "https://app.xxxxxx.com.br/v2/","https://xxxxxx.xxxxxx.com.br/"
			} 

		}
                elseif ($application -eq "app") {

                	if ($environment -eq "dev") {
				$newConfig = $newConfig -replace "https://app.dev.xxxxxx.com.br/v2/","https://appdev.xxxxxx.com.br/v2/"
                        	$newConfig = $newConfig -replace "https://xxxxxxdev.xxxxxx.com.br/","https://appdev.xxxxxx.com.br/v2/"
			} 
			elseif ($environment -eq "qa") {
				$newConfig = $newConfig -replace "https://app.qa.xxxxxx.com.br/v2/","https://appqa.xxxxxx.com.br/v2/"
                        	$newConfig = $newConfig -replace "https://xxxxxxqa.xxxxxx.com.br/","https://appqa.xxxxxx.com.br/v2/"
			} 
			elseif ($environment -eq "hml") {
				$newConfig = $newConfig -replace "https://homologacao.app.xxxxxx.com.br/v2/","https://apphml.xxxxxx.com.br/v2/"
                        	$newConfig = $newConfig -replace "https://xxxxxxhml.xxxxxx.com.br/","https://apphml.xxxxxx.com.br/v2/"
			} 
			elseif ($environment -eq "val") {
				$newConfig = $newConfig -replace "https://xxxxxxval.xxxxxx.com.br/","https://validacaoapp.xxxxxx.com.br/v2/"
			} 
			elseif ($environment -eq "prd") {
				$newConfig = $newConfig -replace "https://xxxxxx.xxxxxx.com.br/","https://app.xxxxxx.com.br/v2/"
			} 

		} 
		
		
		if ($newConfig -ne $config) {
			Write-Output "	Aplicando transformacao em $c"
			$newConfig | Out-File -Encoding "UTF8" $c
		}
    }
    
}

try {
	Expand-Archive -Path $artifact -DestinationPath $stage

	Remove-Item -r $artifact

	Replace

	Compress-Archive -Path  (-Join($stage, "\*")) -DestinationPath $transformed

	Remove-Item -r $stage -Force
}
catch {
	throw $_.Exception
}
```
