### ISSUE TITLE
[BUG]: AzureFunctionApp 2.242.1 Cannot find module @azure/msal-node

### ISSUE THREAD

**Issue by lw-imranmomin** [microsoft/azure-pipelines-tasks#20175]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFunctionApp

### Task version

2.242.1

### Issue Description

We are seeing error **Cannot find module '@azure/msal-node'**. The task worked correctly until **v2.238.1**

Our self-hosted agent 
Agent OS : Windows
Agent version: '2.200.2'

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2019

### Relevant log output

```shell
##[error]Unhandled: Cannot find module '@azure/msal-node'
##[error]Error: Cannot find module '@azure/msal-node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\agent\_work\_tasks\AzureFunctionApp_501dd25d-1785-43e4-b4e5-a5c78ccc0573\2.242.1\node_modules\azure-pipelines-tasks-azure-arm-rest\azure-arm-common.js:22:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Full task logs with system.debug enabled

<details>
  <pre>2024-07-18T15:32:26.5767628Z ##[debug]Evaluating condition for step: 'AzureFunctionApp'
2024-07-18T15:32:26.5770653Z ##[debug]Evaluating: SucceededNode()
2024-07-18T15:32:26.5771432Z ##[debug]Evaluating SucceededNode:
2024-07-18T15:32:26.5773082Z ##[debug]=> True
2024-07-18T15:32:26.5773924Z ##[debug]Result: True
2024-07-18T15:32:26.5774614Z ##[section]Starting: AzureFunctionApp
2024-07-18T15:32:26.5976014Z ==============================================================================
2024-07-18T15:32:26.5976543Z Task         : Azure Functions Deploy
2024-07-18T15:32:26.5977119Z Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
2024-07-18T15:32:26.5977654Z Version      : 2.242.1
2024-07-18T15:32:26.5977989Z Author       : Microsoft Corporation
2024-07-18T15:32:26.5979526Z Help         : https://aka.ms/azurefunctiontroubleshooting
2024-07-18T15:32:26.5980045Z ==============================================================================
2024-07-18T15:32:26.6150518Z ##[debug]Using node path: C:\agent\externals\node10\bin\node.exe
2024-07-18T15:32:26.7993572Z ##[debug]agent.TempDirectory=C:\agent\_work\_temp
2024-07-18T15:32:26.8019951Z ##[debug]loading inputs and endpoints
2024-07-18T15:32:26.8051113Z ##[debug]loading ENDPOINT_AUTH_148daa83-f6c0-479a-b8ff-d575d72cd111
2024-07-18T15:32:26.8065656Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_148daa83-f6c0-479a-b8ff-d575d72cd111_AUTHENTICATIONTYPE
2024-07-18T15:32:26.8069705Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_148daa83-f6c0-479a-b8ff-d575d72cd111_SERVICEPRINCIPALID
2024-07-18T15:32:26.8073263Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_148daa83-f6c0-479a-b8ff-d575d72cd111_SERVICEPRINCIPALKEY
2024-07-18T15:32:26.8075766Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_148daa83-f6c0-479a-b8ff-d575d72cd111_TENANTID
2024-07-18T15:32:26.8077967Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2024-07-18T15:32:26.8080019Z ##[debug]loading ENDPOINT_AUTH_SCHEME_148daa83-f6c0-479a-b8ff-d575d72cd111
2024-07-18T15:32:26.8082020Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2024-07-18T15:32:26.8084273Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2024-07-18T15:32:26.8086414Z ##[debug]loading INPUT_APPNAME
2024-07-18T15:32:26.8088822Z ##[debug]loading INPUT_APPSETTINGS
2024-07-18T15:32:26.8090662Z ##[debug]loading INPUT_APPTYPE
2024-07-18T15:32:26.8092369Z ##[debug]loading INPUT_AZURESUBSCRIPTION
2024-07-18T15:32:26.8094086Z ##[debug]loading INPUT_DEPLOYMENTMETHOD
2024-07-18T15:32:26.8095795Z ##[debug]loading INPUT_DEPLOYTOSLOTORASE
2024-07-18T15:32:26.8097833Z ##[debug]loading INPUT_PACKAGE
2024-07-18T15:32:26.8101099Z ##[debug]loading INPUT_SLOTNAME
2024-07-18T15:32:26.8104199Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2024-07-18T15:32:26.8110451Z ##[debug]loaded 18
2024-07-18T15:32:26.8115551Z ##[debug]Agent.ProxyUrl=undefined
2024-07-18T15:32:26.8117205Z ##[debug]Agent.CAInfo=undefined
2024-07-18T15:32:26.8118799Z ##[debug]Agent.ClientCert=undefined
2024-07-18T15:32:26.8120488Z ##[debug]Agent.SkipCertValidation=undefined
2024-07-18T15:32:26.8586695Z ##[debug]agent.proxyurl=undefined
2024-07-18T15:32:26.8588606Z ##[debug]VSTS_ARM_REST_IGNORE_SSL_ERRORS=undefined
2024-07-18T15:32:26.8590661Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_de81d2e3-6710-4933-b7c8-6ddddf7bc111_build_6279_0
2024-07-18T15:32:26.8885656Z ##[debug]task result: Failed
2024-07-18T15:32:26.8962595Z ##[error]Unhandled: Cannot find module '@azure/msal-node'
2024-07-18T15:32:26.8978409Z ##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]Unhandled: Cannot find module '@azure/msal-node'
2024-07-18T15:32:26.8981327Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Cannot find module '@azure/msal-node'
2024-07-18T15:32:26.8988808Z ##[error]Error: Cannot find module '@azure/msal-node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\agent\_work\_tasks\AzureFunctionApp_501dd25d-1785-43e4-b4e5-a5c78ccc0573\2.242.1\node_modules\azure-pipelines-tasks-azure-arm-rest\azure-arm-common.js:22:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2024-07-18T15:32:26.8998347Z ##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]Error: Cannot find module '@azure/msal-node'%0A    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)%0A    at Function.Module._load (internal/modules/cjs/loader.js:562:25)%0A    at Module.require (internal/modules/cjs/loader.js:692:17)%0A    at require (internal/modules/cjs/helpers.js:25:18)%0A    at Object.<anonymous> (C:\agent\_work\_tasks\AzureFunctionApp_501dd25d-1785-43e4-b4e5-a5c78ccc0573\2.242.1\node_modules\azure-pipelines-tasks-azure-arm-rest\azure-arm-common.js:22:14)%0A    at Module._compile (internal/modules/cjs/loader.js:778:30)%0A    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)%0A    at Module.load (internal/modules/cjs/loader.js:653:32)%0A    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)%0A    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2024-07-18T15:32:26.9008652Z ##[section]Finishing: AzureFunctionApp </pre>
</details>

**Comment by Raksha-CPU** [comment]
I am encountering the same issue today. It was working two days ago. Can anyone suggest a workaround?

**Comment by dragos-stoichita** [comment]
I have the same issue with the AzureRmWebAppDeployment task
![image](https://github.com/user-attachments/assets/5652eb85-ed9d-40f6-b3dc-dd770bd73329)

**Comment by lw-imranmomin** [comment]
for workaround, in the pipeline I'm using specific version of the task i.e. AzureFunctionApp@2.238.1

**Comment by lentyaishe** [comment]
> I have the same issue with the AzureRmWebAppDeployment task ![image](https://private-user-images.githubusercontent.com/176025899/350347311-5652eb85-ed9d-40f6-b3dc-dd770bd73329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NjA5OTMsIm5iZiI6MTcyMTU2MDY5MywicGF0aCI6Ii8xNzYwMjU4OTkvMzUwMzQ3MzExLTU2NTJlYjg1LWVkOWQtNDBmNi1iM2RjLWRkNzcwYmQ3MzMyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQxMTE4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYThmYjkzMmFmY2M4NTljODYwNjk3NTEyMTc0Y2Q4NjdlYTY1NmQ4NDkxMGM0OTIyOTMyMTZkMzcyOTY1NGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vC-ngViLydj9a1c0Zv1v6C4l0irJon6w1b1BW1W41F4)

I succeeded fixing this issue with upgrading the task version to version 4.* and defining the same set of properties as for the older task.

Unfortunately still having trouble with "Azure Functions Deploy" task (even an upgrade to the latest 2.* version continues to report an error of 'cannot find module '@azure/msal-node'')

**Comment by lentyaishe** [comment]
Well, solution found:
1. Upgrade your "Azure App Service Deploy" task to version 4.* and update the task run properties to your previous values. (or update the existing task from currently selected version to version 4.* and hope that all you properties will update configurations correctly).
2. For "Azure Functions Deploy" task upgrade it to version 2.* (all properties' values updated correctly for me).
3. Upgrade your build agent version to the latest one (in my case it's 3.241.0). See the picture to find where it's located and the [following post](https://stackoverflow.com/q/65087862/2471497) on how the upgrade is initiated.
![Capture](https://github.com/user-attachments/assets/a9448618-3848-4b7f-9671-e8ffc5ac70ce)

Afterwards build passed successfully for me.
Have fun :)

**Comment by v-schhabra** [comment]
Hi Everyone, 
Incase you are using self-hosted agents please upgrade your agent to the latest version and if you are using Ms-hosted agents please dont specify any variable in yaml pipeline:
 variables:
  - name: AGENT_USE_NODE10
    value: 'true'

**Comment by crowz4k** [comment]
Upgrade task to version 2.* 
Upgrade your build agent version to the latest one 3.241.0.

Did a trick for me

**Comment by tj-aew** [comment]
We were also running into this with `AzureRmWebAppDeployment`. Our build file had `AzureRmWebAppDeployment@4` so it was using the latest v4 which appears to be (as I write this) `@4.242.0`. I updated the YAML to use the last version we successfully deployed with (we've had an unusually quiet couple of months):

```yaml
    - task: AzureRmWebAppDeployment@4.234.2 
```

That worked around it for us.

**Comment by KEMBL** [comment]
> @lentyaishe
> 3. Update your build agent version to the latest one 3.241.0

that works, thx

**Comment by bordesujay** [comment]
So basically the solution is to not use the latest AzureRmWebAppDeployment version. Thank you Azure pipelines for keeping things simple.
