### ISSUE TITLE
[BUG]: Cache@2 fails if $TMPDIR is smaller than content to be uploaded

### ISSUE THREAD

**Issue by sandersaares** [microsoft/azure-pipelines-tasks#20253]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Cache

### Task version

2

### Issue Description

If the content to be uploaded to cache is larger than the size of the TMPDIR on Linux, the cache upload task fails.

In my case I have a 16G /tmp ramdisk but my cached files are more than 16G total.

The error is exemplified by:

> There is a cache miss.
> tar: 4e6417dda2374f438672b8c4d70943af_archive.tar: Wrote only 2048 of 10240 bytes
> tar: Error is not recoverable: exiting now

No additional relevant data shown in debug logs - it just starts tar and fails with this. Experimentally, I diagnosed it to meaning "out of disk space".

Expected behavior: cache task uses my working directory for any file management (huge amounts of disk space exactly for my 100G of build artifacts).

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [x] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Azure Linux

### Relevant log output

```shell
Starting: Cache target directory
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - target                        [string]
 - "1.79.0-ms-20240619.1"        [string]
 - "cargo_build_dev_linux"       [string]
 - "Linux"                       [string]
 - "X64"                         [string]
 - /mnt/vss/_work/1/s/Cargo.lock [file] --> C67001249BCC491EE01B2BD882E499CC216F5F00D0A518F870C1EADDA290E16C
Resolved to: target|"1.79.0-ms-20240619.1"|"cargo_build_dev_linux"|"Linux"|"X64"|2+YiHzGV8QL57W+Vs9DWAQgFVvQgSlLgUa4BgDA22pg=
Using default max parallelism.
Using default max parallelism.
Max dedup parallelism: 192
DomainId: 0
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 58cd4148-4688-43f0-8125-02c62e6893aa
Hashtype: Dedup64K
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `target|"1.79.0-ms-20240619.1"|"cargo_build_dev_linux"|"Linux"|"X64"|2+YiHzGV8QL57W+Vs9DWAQgFVvQgSlLgUa4BgDA22pg=`
There is a cache miss.
tar: 4e6417dda2374f438672b8c4d70943af_archive.tar: Wrote only 2048 of 10240 bytes
tar: Error is not recoverable: exiting now
ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session 58cd4148-4688-43f0-8125-02c62e6893aa
##[error]Process returned non-zero exit code: 2
Finishing: Cache target directory
```

### Full task logs with system.debug enabled

```
2024-08-05T08:53:29.7499438Z ##[debug]Evaluating condition for step: 'Cache target directory'
2024-08-05T08:53:29.7500357Z ##[debug]Evaluating: AlwaysNode()
2024-08-05T08:53:29.7500551Z ##[debug]Evaluating AlwaysNode:
2024-08-05T08:53:29.7501772Z ##[debug]=> True
2024-08-05T08:53:29.7502046Z ##[debug]Result: True
2024-08-05T08:53:29.7502236Z ##[section]Starting: Cache target directory
2024-08-05T08:53:29.7505103Z ==============================================================================
2024-08-05T08:53:29.7505191Z Task         : Cache
2024-08-05T08:53:29.7505226Z Description  : Cache files between runs
2024-08-05T08:53:29.7505270Z Version      : 2.198.0
2024-08-05T08:53:29.7505307Z Author       : Microsoft Corporation
2024-08-05T08:53:29.7505352Z Help         : https://aka.ms/pipeline-caching-docs
2024-08-05T08:53:29.7505407Z ==============================================================================
2024-08-05T08:53:30.7096931Z ##[debug]Resource Utilization warnings is disabled, switch "DISABLE_RESOURCE_UTILIZATION_WARNINGS" variable to "true" if you want to enable it
2024-08-05T08:53:30.9286984Z Resolving key:
2024-08-05T08:53:30.9411087Z  - target                        [string]
2024-08-05T08:53:30.9415967Z  - "1.79.0-ms-20240619.1"        [string]
2024-08-05T08:53:30.9416298Z  - "cargo_build_dev_linux"       [string]
2024-08-05T08:53:30.9416459Z  - "Linux"                       [string]
2024-08-05T08:53:30.9416625Z  - "X64"                         [string]
2024-08-05T08:53:30.9715113Z  - /mnt/vss/_work/1/s/Cargo.lock [file] --> C67001249BCC491EE01B2BD882E499CC216F5F00D0A518F870C1EADDA290E16C
2024-08-05T08:53:30.9750243Z Resolved to: target|"1.79.0-ms-20240619.1"|"cargo_build_dev_linux"|"Linux"|"X64"|2+YiHzGV8QL57W+Vs9DWAQgFVvQgSlLgUa4BgDA22pg=
2024-08-05T08:53:31.0094185Z Using default max parallelism.
2024-08-05T08:53:32.9275822Z ##[debug]Agent environment resources - Disk: / Available 464077.12 MB out of 515665.27 MB, Memory: Used 1096.00 MB out of 31838.00 MB, CPU: Usage 9.98%
2024-08-05T08:53:34.9594128Z Verbose, ArtifactHttpClientFactory.CreateVssHttpClient: ClientSettingsHttpClient with BaseUri: https://vsblobprodscussu5.vsblob.visualstudio.com/Ad1a8f71c-7f64-45ad-9c5c-19c2f469d620/, MaxRetries:5, SendTimeout:00:01:40
2024-08-05T08:53:35.0805859Z Using default max parallelism.
2024-08-05T08:53:35.0810315Z Max dedup parallelism: 192
2024-08-05T08:53:35.0811093Z DomainId: 0
2024-08-05T08:53:35.1015681Z Verbose, ArtifactHttpClientFactory.CreateVssHttpClient: DedupStoreHttpClient with BaseUri: https://vsblobprodscussu5.vsblob.visualstudio.com/Ad1a8f71c-7f64-45ad-9c5c-19c2f469d620/, MaxRetries:5, SendTimeout:00:01:40
2024-08-05T08:53:35.1974249Z Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session d6aadae3-33e3-4497-bda0-7e7c1e7eef72
2024-08-05T08:53:35.1974587Z Verbose, Started ITelemetrySender BlobStoreApplicationInsightsTelemetrySender.
2024-08-05T08:53:35.1988209Z Hashtype: Dedup64K
2024-08-05T08:53:36.2256430Z Getting a pipeline cache artifact with one of the following fingerprints:
2024-08-05T08:53:36.2257015Z Fingerprint: `target|"1.79.0-ms-20240619.1"|"cargo_build_dev_linux"|"Linux"|"X64"|2+YiHzGV8QL57W+Vs9DWAQgFVvQgSlLgUa4BgDA22pg=`
2024-08-05T08:53:36.3964142Z There is a cache miss.
2024-08-05T08:53:37.5263373Z ##[debug]Processed: ##vso[telemetry.publish area=AzurePipelinesAgent;feature=PipelineCache]{"FileCount":"0","PlanId":"bc064e61-4038-4109-ba9a-3cdeab778dda","JobId":"0869c88d-406b-5521-0e25-e73aca768d85","TaskInstanceId":"61738b86-8c2e-5412-98b6-ce3ba9dee3f4","CacheResult":"Miss","ActionDurationMs":"175","ActionName":"PipelineCache.RestoreCache","ActionResult":"Success","AttemptNumber":"1","ItemCount":"0","Level":"ThirdParty","CreatedUtcNow":"2024-08-05T08:53:36.2194882Z","SentUtcNow":"2024-08-05T08:53:36.3979209Z","BaseAddress":"https://vsblobprodscussu5.vsblob.visualstudio.com/Ad1a8f71c-7f64-45ad-9c5c-19c2f469d620/","X_TFS_Session":"d6aadae3-33e3-4497-bda0-7e7c1e7eef72","DeploymentEnvironment":"PRODUCTION","DeploymentEnvironmentIsProduction":"True","VSOAccount":"vsblobprodscussu5","OSName":"Linux","OSVersion":"2024","FrameworkDescription":".NET ","ProcessName":"Agent.PluginHost","DotNetReleaseDword":"-1","Version":"19.237.34720.0","ExceptionCount":"0"}
2024-08-05T08:53:37.5265363Z ##[debug]Starting 'tar' with arguments '-v -cf "e398e638292941de82ba5bba5aeae1bb_archive.tar" -C "/mnt/vss/_work/1/s/target" .'...
...
2024-08-05T08:53:55.3649226Z tar: e398e638292941de82ba5bba5aeae1bb_archive.tar: Wrote only 2048 of 10240 bytes
2024-08-05T08:53:55.3649427Z tar: Error is not recoverable: exiting now
2024-08-05T08:53:56.3043446Z Verbose, ApplicationInsightsTelemetrySender waiting for 0 of 1 TrackEvent operations to complete...
2024-08-05T08:53:56.3043781Z Verbose, ApplicationInsightsTelemetrySender operations completed in 0 ms
2024-08-05T08:53:56.3044465Z Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session d6aadae3-33e3-4497-bda0-7e7c1e7eef72
2024-08-05T08:53:56.3044752Z Verbose, Stopped ITelemetrySender BlobStoreApplicationInsightsTelemetrySender.
2024-08-05T08:53:56.3054321Z ##[error]Process returned non-zero exit code: 2
2024-08-05T08:53:56.3054737Z ##[debug]Processed: ##vso[task.logissue type=error;]Process returned non-zero exit code: 2
2024-08-05T08:53:56.3102547Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2024-08-05T08:53:56.3104639Z ##[debug]   at Agent.Plugins.PipelineCache.TarUtils.RunProcessAsync(AgentTaskPluginExecutionContext context, ProcessStartInfo processStartInfo, Func`3 additionalTaskToExecuteWhilstRunningProcess, Action actionOnFailure, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/src/Agent.Plugins/PipelineCache/TarUtils.cs:line 148
   at Agent.Plugins.PipelineCache.TarUtils.RunProcessAsync(AgentTaskPluginExecutionContext context, ProcessStartInfo processStartInfo, Func`3 additionalTaskToExecuteWhilstRunningProcess, Action actionOnFailure, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/src/Agent.Plugins/PipelineCache/TarUtils.cs:line 154
   at Agent.Plugins.PipelineCache.TarUtils.ArchiveFilesToTarAsync(AgentTaskPluginExecutionContext context, String inputPath, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/src/Agent.Plugins/PipelineCache/TarUtils.cs:line 50
   at Agent.Plugins.PipelineCache.PipelineCacheServer.GetUploadPathAsync(ContentFormat contentFormat, AgentTaskPluginExecutionContext context, String path, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs:line 287
   at Agent.Plugins.PipelineCache.PipelineCacheServer.UploadAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, String path, CancellationToken cancellationToken, ContentFormat contentFormat) in /mnt/vss/_work/1/s/src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs:line 72
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, Func`1 restoreKeysGenerator, String path, CancellationToken token) in /mnt/vss/_work/1/s/src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs:line 86
   at Agent.Plugins.PipelineCache.PipelineCacheTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token) in /mnt/vss/_work/1/s/src/Agent.Plugins/PipelineCache/PipelineCacheTaskPluginBase.cs:line 122
   at Agent.Plugins.PipelineCache.SavePipelineCacheV0.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token) in /mnt/vss/_work/1/s/src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs:line 55
   at Agent.PluginHost.Program.Main(String[] args) in /mnt/vss/_work/1/s/src/Agent.PluginHost/Program.cs:line 71
2024-08-05T08:53:56.3162868Z ##[section]Finishing: Cache target directory
```

**Comment by sandersaares** [comment]
The ability to at least override it with a custom path parameter would be desirable.

**Comment by sandersaares** [comment]
This remains as relevant as ever.

**Comment by psandana** [comment]
issue still relevant

**Comment by JeremyCamplin** [comment]
This is also an issue with Windows and the error has even less information.

> There is a cache miss.
> tar: Write error

This was trying to write a temp 5Gb cache file to `C:\windows\ServiceProfiles\NetworkService\AppData\Local\Temp` where the C drive had less than 5Gb available. The build agent is on another disk with plenty of space. I was only able to identify where it was trying to write by examining a successful run. I should be able to specify where it generates the temp file for the cache.

**Comment by spowser** [comment]
Ran into this today.  Setting the env var TMPDIR to a directory path on our attached disk seems to have resolved it.

**Comment by psandana** [comment]
> This issue is stale because it has been open for 180 days with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days

This is still an issue
