### ISSUE TITLE
[BUG]: Cannot find module '@azure/msal-node'

### ISSUE THREAD

**Issue by jcronanAgLoan** [microsoft/azure-pipelines-tasks#20256]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Azure App Service deploy

### Task version

4.240.3

### Issue Description

Getting the following when trying to deploy to an internal server on ADO Release Pipelines. Had to revert code on machine to version 4.240.2 to get working. 

2024-08-01T18:42:29.0438282Z ##[error]Unhandled: Cannot find module '@azure/msal-node'
2024-08-01T18:42:29.0452513Z ##[error]Error: Cannot find module '@azure/msal-node'

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2019 Standard

### Relevant log output

```shell
2024-08-01T18:42:29.0438282Z ##[error]Unhandled: Cannot find module '@azure/msal-node'
2024-08-01T18:42:29.0452513Z ##[error]Error: Cannot find module '@azure/msal-node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\vstsagent\A2\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\4.240.3\node_modules\azure-pipelines-tasks-azure-arm-rest\azure-arm-common.js:22:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Full task logs with system.debug enabled

<details>
  <pre> 2024-08-01T18:41:48.5090022Z ##[section]Starting: Release
2024-08-01T18:41:48.6879667Z ##[section]Starting: Initialize job
2024-08-01T18:41:48.6880906Z Agent name: 'QA-ENT-APP01-QATIMBERAPPS'
2024-08-01T18:41:48.6881229Z Agent machine name: 'QA-ENT-APP01'
2024-08-01T18:41:48.6881441Z Current agent version: '2.193.0'
2024-08-01T18:41:48.6906064Z Agent running as: 'QA-ENT-APP01$'
2024-08-01T18:41:48.6912197Z Prepare release directory.
2024-08-01T18:41:48.6916669Z ReleaseId=11374, TeamProjectId=fa5b7c2b-4670-4065-942c-a497fd420b03, ReleaseDefinitionName=OnlineBankingService
2024-08-01T18:41:48.6954665Z Release folder: C:\vstsagent\A2\_work\r2\a
2024-08-01T18:41:48.7027401Z Environment variables available are below.  Note that these environment variables can be referred to in the task (in the ReleaseDefinition) by replacing "_" with "." e.g. AGENT_NAME environment variable can be referenced using Agent.Name in the ReleaseDefinition: 
				[ADMINDNSROLES] --> [Application Production Support,S-QA-Team,IT Systems Development]
				[AGENT_DEPLOYMENTGROUPID] --> [147]
				[AGENT_DISABLELOGPLUGIN_TESTFILEPUBLISHERPLUGIN] --> [true]
				[AGENT_DISABLELOGPLUGIN_TESTRESULTLOGPLUGIN] --> [true]
				[AGENT_HOMEDIRECTORY] --> [C:\vstsagent\A2]
				[AGENT_ID] --> [153]
				[AGENT_JOBNAME] --> [Release]
				[AGENT_MACHINENAME] --> [QA-ENT-APP01]
				[AGENT_NAME] --> [QA-ENT-APP01-QATIMBERAPPS]
				[AGENT_OS] --> [Windows_NT]
				[AGENT_OSARCHITECTURE] --> [X64]
				[AGENT_RELEASEDIRECTORY] --> [C:\vstsagent\A2\_work\r2\a]
				[AGENT_RETAINDEFAULTENCODING] --> [false]
				[AGENT_ROOTDIRECTORY] --> [C:\vstsagent\A2\_work]
				[AGENT_SERVEROMDIRECTORY] --> [C:\vstsagent\A2\externals\vstsom]
				[AGENT_TASKRESTRICTIONSENFORCEMENTMODE] --> [Enabled]
				[AGENT_TEMPDIRECTORY] --> [C:\vstsagent\A2\_work\_temp]
				[AGENT_TOOLSDIRECTORY] --> [C:\vstsagent\A2\_work\_tool]
				[AGENT_VERSION] --> [2.193.0]
				[AGENT_WORKFOLDER] --> [C:\vstsagent\A2\_work]
				[APICONNECTION] --> [http://AzureEnv/OnlineBankingServices/]
				[APINAME] --> []
				[APPLICATIONSERVER] --> [AzureEnv]
				[AUTHORIZATION_CLIENTID] --> [3c7a3d3e-30f0-442c-a62e-25f978e8b672]
				[AUTHORIZATION_RESOURCE] --> [api://qa-timber-ods-internal]
				[AUTHORIZATIONFSCTOODSBRIDGE_CLIENTID] --> [7d8dfec0-a4c3-4f2e-a445-d9100c1225b0]
				[AUTHORIZATIONFSCTOODSBRIDGE_RESOURCE] --> [api://qa.timber.fsc.bridge.ods]
				[AUTHORIZATIONFSCTOODSBRIDGE_SUBSCRIPTIONKEY] --> [dd9c06d027934b70a36ad18d1c61d055]
				[AUTHORIZATIONSALESFORCE_AUTHORITY] --> [https://agloan--timber.sandbox.my.salesforce.com/services/oauth2/token]
				[AUTHORIZATIONSALESFORCE_CLIENTID] --> [3MVG9iBaHQRfreBmzVhejYNV5ju_2qeoebRQEIJPAFXDoyWGr0jIv6c4W1vBj4u6Vts3jtCfNB0fXEDuvIeg1]
				[AUTHORIZATIONSALESFORCE_USERNAME] --> [alkamisdk_orchestration@agloan.com.fsc.timber]
				[AZUREAPIMANAGEMENTNAME] --> [Agloan-APIM]
				[AZUREAPIMANAGEMENTRESOURCEGROUP] --> [RG-Agloan-AppSvc]
				[AZUREDEFAULTSITE] --> [appsdev2]
				[AZURE_HTTP_USER_AGENT] --> [VSTS_b77fd69c-44b8-4334-b257-d3ad642f97db_release_57_11374_46862_9]
				[BUILD_BUILDID] --> [33401]
				[BUILD_BUILDNUMBER] --> [20240520.2]
				[BUILD_BUILDURI] --> [vstfs:///Build/Build/33401]
				[BUILD_DEFINITIONID] --> [192]
				[BUILD_DEFINITIONNAME] --> [AAC.OnlineBanking.Services]
				[BUILD_PROJECTID] --> [fa5b7c2b-4670-4065-942c-a497fd420b03]
				[BUILD_PROJECTNAME] --> [Enterprise]
				[BUILD_REPOSITORY_ID] --> [8118de02-5acc-4bad-9751-74a6aab89948]
				[BUILD_REPOSITORY_NAME] --> [AAC.OnlineBanking.Services]
				[BUILD_REPOSITORY_PROVIDER] --> [TfsGit]
				[BUILD_REQUESTEDFOR] --> [Jason Rowe]
				[BUILD_REQUESTEDFORID] --> [e0b6d05c-1524-6213-a164-8621c8fe9202]
				[BUILD_SOURCEBRANCH] --> [refs/heads/master]
				[BUILD_SOURCEBRANCHNAME] --> [master]
				[BUILD_SOURCEVERSION] --> [d4cba08e808a2d9e887fa4ab49c79df5e7c2993c]
				[BUILD_TYPE] --> [Build]
				[DEFAULTPARENTWEBSITE] --> [Default Web Site]
				[DEVOPSRELEASELABEL] --> [AAC DevOps Version: Release-20240520.2]
				[DEVOPSRELEASELINK] --> [https://agloan.visualstudio.com/fa5b7c2b-4670-4065-942c-a497fd420b03/_release?releaseId=11374]
				[EMAIL_CUSTOMERSERVICETO_EMAIL] --> [bdt-customerdigitalexperienceplatform@agloan.com]
				[EMAIL_CUSTOMERSERVICETO_NAME] --> [bdt-customerdigitalexperienceplatform@agloan.com]
				[EMAIL_ENVSUBJECT] --> [QA-TIMBER]
				[EMAIL_TO_EMAIL] --> [bdt-customerdigitalexperienceplatform@agloan.com]
				[EMAIL_TO_NAME] --> [BDT - Customer Digital Experience Platform]
				[ENVIRONMENT] --> [Azure-Env]
				[GIT_TERMINAL_PROMPT] --> [0]
				[INETROOT] --> [D:\inetpub]
				[ISINTEGRATIONSENABLED] --> [true]
				[ISLOGERRORENABLED] --> [false]
				[MSDEPLOY_HTTP_USER_AGENT] --> [VSTS_b77fd69c-44b8-4334-b257-d3ad642f97db_release_57_11374_46862_9]
				[OAUTH_AUDIENCE] --> [https://qa-agloan-olb]
				[PIPELINEURL] --> [https://vsrm.dev.azure.com/AgLoan/b77fd69c-44b8-4334-b257-d3ad642f97db/_build?definitionId=$(System.DefinitionId)]
				[PROCESSFILESLOCATION] --> [D:\ProcessFiles]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_BUILDID] --> [33401]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_BUILDNUMBER] --> [20240520.2]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_BUILDURI] --> [vstfs:///Build/Build/33401]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_DEFINITIONID] --> [192]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_DEFINITIONNAME] --> [AAC.OnlineBanking.Services]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_PROJECTID] --> [fa5b7c2b-4670-4065-942c-a497fd420b03]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_PROJECTNAME] --> [Enterprise]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_REPOSITORY_ID] --> [8118de02-5acc-4bad-9751-74a6aab89948]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_REPOSITORY_NAME] --> [AAC.OnlineBanking.Services]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_REPOSITORY_PROVIDER] --> [TfsGit]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_REQUESTEDFOR] --> [Jason Rowe]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_REQUESTEDFORID] --> [e0b6d05c-1524-6213-a164-8621c8fe9202]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_SOURCEBRANCH] --> [refs/heads/master]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_SOURCEBRANCHNAME] --> [master]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_SOURCEVERSION] --> [d4cba08e808a2d9e887fa4ab49c79df5e7c2993c]
				[RELEASE_ARTIFACTS__AAC_ONLINEBANKING_SERVICES_TYPE] --> [Build]
				[RELEASE_ATTEMPTNUMBER] --> [9]
				[RELEASE_DEFINITIONENVIRONMENTID] --> [405]
				[RELEASE_DEFINITIONID] --> [57]
				[RELEASE_DEFINITIONNAME] --> [OnlineBankingService]
				[RELEASE_DEFINITIONSNAPSHOTREVISION] --> []
				[RELEASE_DEPLOYMENT_REQUESTEDFOR] --> [Admin Jeremy Cronan]
				[RELEASE_DEPLOYMENT_REQUESTEDFOREMAIL] --> [adminjcronan@agloan.com]
				[RELEASE_DEPLOYMENT_REQUESTEDFORID] --> [9452ab7a-5039-6565-af6d-9d7758f37398]
				[RELEASE_DEPLOYMENT_STARTTIME] --> [2024-08-01 18:39:51Z]
				[RELEASE_DEPLOYMENTID] --> [22558]
				[RELEASE_DEPLOYPHASEID] --> [49945]
				[RELEASE_ENVIRONMENTID] --> [46862]
				[RELEASE_ENVIRONMENTNAME] --> [QA-AZURE]
				[RELEASE_ENVIRONMENTPROTECTEDTENANTS] --> []
				[RELEASE_ENVIRONMENTS_DEV_2_STATUS] --> [NotStarted]
				[RELEASE_ENVIRONMENTS_DEV-AZURE_STATUS] --> [NotStarted]
				[RELEASE_ENVIRONMENTS_DEV_STATUS] --> [Succeeded]
				[RELEASE_ENVIRONMENTS_PROD-AZURE_STATUS] --> [Canceled]
				[RELEASE_ENVIRONMENTS_QA-AZURE_STATUS] --> [InProgress]
				[RELEASE_ENVIRONMENTURI] --> [vstfs:///ReleaseManagement/Environment/46862]
				[RELEASE_PRIMARYARTIFACTSOURCEALIAS] --> [_AAC.OnlineBanking.Services]
				[RELEASE_REASON] --> [ContinuousIntegration]
				[RELEASE_RELEASEDESCRIPTION] --> [Triggered by AAC.OnlineBanking.Services 20240520.2.]
				[RELEASE_RELEASEID] --> [11374]
				[RELEASE_RELEASENAME] --> [Release-20240520.2]
				[RELEASE_RELEASEURI] --> [vstfs:///ReleaseManagement/Release/11374]
				[RELEASE_RELEASEWEBURL] --> [https://dev.azure.com/AgLoan/fa5b7c2b-4670-4065-942c-a497fd420b03/_release?releaseId=11374&_a=release-summary]
				[RELEASE_REQUESTEDFOR] --> [Jason Rowe]
				[RELEASE_REQUESTEDFOREMAIL] --> [jrowe@agloan.com]
				[RELEASE_REQUESTEDFORID] --> [e0b6d05c-1524-6213-a164-8621c8fe9202]
				[RELEASE_SKIPARTIFACTSDOWNLOAD] --> [False]
				[RELEASE_TRIGGERINGARTIFACT_ALIAS] --> [_AAC.OnlineBanking.Services]
				[RELEASELABEL] --> [AAC DevOps Version]
				[RELEASEWEBCONFIGURL] --> [https://agloan.visualstudio.com/fa5b7c2b-4670-4065-942c-a497fd420b03/_release?releaseId=11374]
				[REQUESTEDFORID] --> [e0b6d05c-1524-6213-a164-8621c8fe9202]
				[SERVER] --> [dev-ent-app]
				[SERVICEADDRESSES_FSCBRIDGEODS] --> [https://api.agloan.com/timber/fscbridgeods/api/]
				[SERVICEADDRESSES_INTEGRATIONS] --> [https://api.agloan.com/timber/ods/api/]
				[SERVICEADDRESSES_MTA] --> [https://api.agloan.com/timber/mta/api/]
				[SERVICEADDRESSES_ODSINTEGRATIONSLOADDATE] --> [https://api.agloan.com/ods/api/]
				[SERVICEADDRESSES_SALESFORCE] --> [https://agloan--timber.sandbox.my.salesforce.com/services/apexrest/aacportalrest/]
				[SERVICEADDRESSES_SERVICENOW] --> [http://dev-ent-app/LoggingAPI/]
				[SWAGGER_TITLE] --> [QA AAC Online Banking Services Alkami Api]
				[SYSTEM] --> [deployment]
				[SYSTEM_ARTIFACTSDIRECTORY] --> [C:\vstsagent\A2\_work\r2\a]
				[SYSTEM_COLLECTIONID] --> [b77fd69c-44b8-4334-b257-d3ad642f97db]
				[SYSTEM_COLLECTIONURI] --> [https://vsrm.dev.azure.com/AgLoan/]
				[SYSTEM_CULTURE] --> [en-US]
				[SYSTEM_DEFAULTWORKINGDIRECTORY] --> [C:\vstsagent\A2\_work\r2\a]
				[SYSTEM_ENABLEACCESSTOKEN] --> [False]
				[SYSTEM_HOSTTYPE] --> [deployment]
				[SYSTEM_JOBID] --> [996116ac-af81-4de9-8f01-3f5605e8636a]
				[SYSTEM_JOBPARALLELISMTAG] --> [Private]
				[SYSTEM_OIDCREQUESTURI] --> [https://agloan.vsrm.visualstudio.com/fa5b7c2b-4670-4065-942c-a497fd420b03/_apis/distributedtask/hubs/deployment/plans/43d1edd1-cd20-4d58-a09d-f81a83fa708e/jobs/996116ac-af81-4de9-8f01-3f5605e8636a/oidctoken]
				[SYSTEM_PIPELINESTARTTIME] --> [2024-08-01 18:41:43+00:00]
				[SYSTEM_PLANID] --> [43d1edd1-cd20-4d58-a09d-f81a83fa708e]
				[SYSTEM_SERVERTYPE] --> [Hosted]
				[SYSTEM_TASKDEFINITIONSURI] --> [https://agloan.visualstudio.com/]
				[SYSTEM_TEAMFOUNDATIONCOLLECTIONURI] --> [https://agloan.visualstudio.com/]
				[SYSTEM_TEAMFOUNDATIONSERVERURI] --> [https://agloan.vsrm.visualstudio.com/]
				[SYSTEM_TEAMPROJECT] --> [Enterprise]
				[SYSTEM_TEAMPROJECTID] --> [fa5b7c2b-4670-4065-942c-a497fd420b03]
				[SYSTEM_TIMELINEID] --> [43d1edd1-cd20-4d58-a09d-f81a83fa708e]
				[SYSTEM_WORKFOLDER] --> [C:\vstsagent\A2\_work]
				[SYSTEMVENDOR_APPID] --> [SDK.1.0]
				[SYSTEMVENDOR_VENDORID] --> [Alkami]
				[TRIALDEPOSIT_ACCOUNTNUMBER] --> [2304001100]
				[WEBSITEROOT] --> [D:\Websites]
2024-08-01T18:41:48.9534787Z Creating artifacts directory: C:\vstsagent\A2\_work\r2\a
2024-08-01T18:41:48.9633667Z Created artifacts directory: C:\vstsagent\A2\_work\r2\a
2024-08-01T18:41:48.9679460Z Download all required tasks.
2024-08-01T18:41:48.9758021Z Downloading task: AzureRmWebAppDeployment (4.240.3)
2024-08-01T18:42:21.2454287Z Checking job knob settings.
2024-08-01T18:42:21.2461204Z Finished checking job knob settings.
2024-08-01T18:42:21.2717648Z Start tracking orphan processes.
2024-08-01T18:42:21.2781747Z ##[section]Finishing: Initialize job
2024-08-01T18:42:21.2990939Z ##[section]Starting: Download artifact - _AAC.OnlineBanking.Services - OnlineBankingApi
2024-08-01T18:42:21.3514872Z ==============================================================================
2024-08-01T18:42:21.3515286Z Task         : Download build artifacts
2024-08-01T18:42:21.3515620Z Description  : Download files that were saved as artifacts of a completed build
2024-08-01T18:42:21.3515851Z Version      : 0.242.0
2024-08-01T18:42:21.3516114Z Author       : Microsoft Corporation
2024-08-01T18:42:21.3516455Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts
2024-08-01T18:42:21.3516749Z ==============================================================================
2024-08-01T18:42:22.4014295Z Downloading artifacts for build: 33401
2024-08-01T18:42:22.4792912Z Downloading items from container resource #/5508982/OnlineBankingApi
2024-08-01T18:42:22.4793645Z Downloading artifact OnlineBankingApi from: https://agloan.visualstudio.com//_apis/resources/Containers/5508982?itemPath=OnlineBankingApi&isShallow=true&api-version=4.1-preview.4
2024-08-01T18:42:22.8190520Z Downloading OnlineBankingApi/AAC.OnlineBanking.Api.zip to C:\vstsagent\A2\_work\r2\a\_AAC.OnlineBanking.Services\OnlineBankingApi\AAC.OnlineBanking.Api.zip
2024-08-01T18:42:25.9447737Z Downloaded OnlineBankingApi/AAC.OnlineBanking.Api.zip to C:\vstsagent\A2\_work\r2\a\_AAC.OnlineBanking.Services\OnlineBankingApi\AAC.OnlineBanking.Api.zip
2024-08-01T18:42:26.4955541Z Total Files: 1, Processed: 1, Skipped: 0, Failed: 0, Download time: 4.015 secs, Download size: 26.237MB
2024-08-01T18:42:26.5109016Z Successfully downloaded artifacts to C:\vstsagent\A2\_work\r2\a\_AAC.OnlineBanking.Services\
2024-08-01T18:42:26.5127741Z ##[section]Finishing: Download artifact - _AAC.OnlineBanking.Services - OnlineBankingApi
2024-08-01T18:42:26.5172101Z ##[section]Starting: Azure App Service Deploy: QA-TIMBER-APPS
2024-08-01T18:42:26.5385010Z ==============================================================================
2024-08-01T18:42:26.5385274Z Task         : Azure App Service deploy
2024-08-01T18:42:26.5385567Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2024-08-01T18:42:26.5385842Z Version      : 4.240.3
2024-08-01T18:42:26.5386022Z Author       : Microsoft Corporation
2024-08-01T18:42:26.5386249Z Help         : https://aka.ms/azureappservicetroubleshooting
2024-08-01T18:42:26.5386483Z ==============================================================================
2024-08-01T18:42:29.0438561Z ##[error]Unhandled: Cannot find module '@azure/msal-node'
2024-08-01T18:42:29.0452850Z ##[error]Error: Cannot find module '@azure/msal-node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\vstsagent\A2\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\4.240.3\node_modules\azure-pipelines-tasks-azure-arm-rest\azure-arm-common.js:22:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2024-08-01T18:42:29.0567322Z ##[section]Finishing: Azure App Service Deploy: QA-TIMBER-APPS
2024-08-01T18:42:29.0620248Z ##[section]Starting: Finalize Job
2024-08-01T18:42:29.0643123Z Cleaning up task key
2024-08-01T18:42:29.0644505Z Start cleaning up orphan processes.
2024-08-01T18:42:29.0671929Z ##[section]Finishing: Finalize Job
2024-08-01T18:42:29.0705089Z ##[section]Finishing: Release
 </pre>
</details>

### Repro steps

```yml
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy'
  inputs:
    azureSubscription: 'API Subscription - PROD'
    WebAppName: 'XXXX'
    packageForLinux: '$(System.DefaultWorkingDirectory)/XXX/XXX.zip'
    enableXmlVariableSubstitution: true
    JSONFiles: '**/appsettings.json'
```

**Comment by jcronanAgLoan** [comment]
This is an old ADO Release Pipeline that suddenly stopped working. It is using the latest version of the task as it downloaded. I had to manually replace the files on the server from an older version to get it working.
![2024-08-06_14-43-22](https://github.com/user-attachments/assets/19e7439e-59f5-4720-9d87-7837873333ee)

**Comment by Tankatronic** [comment]
Experiencing the same issues as well, also in the classic release area. We confirmed that the last time the release worked, the version was 4.240.2, and once 4.240.3 hit the task would fail.

**Comment by v-schhabra** [comment]
Hi @Tankatronic @jcronanAgLoan 
Please share the complete debug logs by enabling system.debug to "true".
And please let us know which type of Service Connection you are using?

**Comment by Deekshitha981** [comment]
Hi @Tankatronic @jcronanAgLoan,
Can you please try updating your agent and see if the error still exists

**Comment by v-schhabra** [comment]
Hi @Tankatronic @jcronanAgLoan 
please share the latest updates if the issue is occurring or not?
