### ISSUE TITLE
[BUG]: Download build artifacts (1.220.0/2.198.0) is failing with error "System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.."

### ISSUE THREAD

**Issue by rajorin** [microsoft/azure-pipelines-tasks#20330]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DownloadPipelineArtifact

### Task version

1.220.0/2.198.0

### Issue Description

Task is able to download some portion of the artifact and then connection is getting closed. It retries download for 4 times and then task fails. 

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022 Datacenter 21H2

### Relevant log output

```shell
2024-08-21T08:55:01.3338925Z ##[debug]Evaluating condition for step: 'DownloadPipelineArtifact'
2024-08-21T08:55:01.3346480Z ##[debug]Evaluating: SucceededNode()
2024-08-21T08:55:01.3346796Z ##[debug]Evaluating SucceededNode:
2024-08-21T08:55:01.3356875Z ##[debug]=> True
2024-08-21T08:55:01.3362849Z ##[debug]Result: True
2024-08-21T08:55:01.3441556Z ##[section]Starting: DownloadPipelineArtifact
2024-08-21T08:55:01.3644069Z ==============================================================================
2024-08-21T08:55:01.3644551Z Task         : Download Pipeline Artifacts
2024-08-21T08:55:01.3644871Z Description  : Download build and pipeline artifacts
2024-08-21T08:55:01.3645005Z Version      : 2.198.0
2024-08-21T08:55:01.3645330Z Author       : Microsoft Corporation
2024-08-21T08:55:01.3645569Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
2024-08-21T08:55:01.3645765Z ==============================================================================
2024-08-21T08:55:02.6225140Z ##[debug]TargetPath: E:\ADO\Agents\Prod-1\_work\1/pc-pe-privatei-web-build-prod/Privatei.Web/Privatei.Web
2024-08-21T08:55:02.6226974Z ##[debug]ArtifactName: Privatei.Web
2024-08-21T08:55:02.6227919Z ##[debug]BuildResult: Succeeded
2024-08-21T08:55:02.6234185Z ##[debug]Run: Specific
2024-08-21T08:55:03.4100965Z ##[debug]ProjectId: 154004dd-3b35-44c3-9bee-9f7f3b60f914
2024-08-21T08:55:03.4109035Z ##[debug]PipelineVersionToDownload: latest
2024-08-21T08:55:03.4109466Z ##[debug]PipelineId from non-trigerringBuild: 5127782
2024-08-21T08:55:03.4109724Z Download from the specified build: #5127782
2024-08-21T08:55:03.4119631Z ##[debug]Processed: ##vso[task.setvariable variable=BuildNumber;issecret=False;]5127782
2024-08-21T08:55:03.4120291Z Download artifact to: E:\ADO\Agents\Prod-1\_work\1/pc-pe-privatei-web-build-prod/Privatei.Web/Privatei.Web
2024-08-21T08:55:03.4506756Z Pattern: **
2024-08-21T08:55:03.4521198Z Minimatch patterns: [**]
2024-08-21T08:55:03.4535244Z Applying include pattern against original list.
2024-08-21T08:55:03.4729942Z 2 matches
2024-08-21T08:55:03.4926623Z 2 final results
2024-08-21T08:55:03.5010612Z Start downloading FCS artifact- Privatei.Web
2024-08-21T08:55:03.5181989Z Downloading: E:\ADO\Agents\Prod-1\_work\1/pc-pe-privatei-web-build-prod/Privatei.Web/Privatei.Web\Privatei.Web.zip
2024-08-21T08:55:05.8723006Z ##[debug]Agent environment resources - Disk: E:\ Available 455258.00 MB out of 511982.00 MB, Memory: Used 5286.00 MB out of 16380.00 MB, CPU: Usage 40.65%
2024-08-21T08:55:10.9218563Z ##[debug]Agent environment resources - Disk: E:\ Available 455208.00 MB out of 511982.00 MB, Memory: Used 5302.00 MB out of 16380.00 MB, CPU: Usage 23.10%
2024-08-21T08:55:15.9943405Z ##[debug]Agent environment resources - Disk: E:\ Available 455152.00 MB out of 511982.00 MB, Memory: Used 5324.00 MB out of 16380.00 MB, CPU: Usage 16.12%
2024-08-21T08:55:21.0529975Z ##[debug]Agent environment resources - Disk: E:\ Available 455072.00 MB out of 511982.00 MB, Memory: Used 5342.00 MB out of 16380.00 MB, CPU: Usage 12.38%
2024-08-21T08:55:26.1208069Z ##[debug]Agent environment resources - Disk: E:\ Available 455068.00 MB out of 511982.00 MB, Memory: Used 5317.00 MB out of 16380.00 MB, CPU: Usage 10.05%
2024-08-21T08:55:26.2680194Z [] Try 1/4, retryable exception caught. Retrying in 00:00:01. System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:55:26.2681718Z  ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
2024-08-21T08:55:26.2684972Z    --- End of inner exception stack trace ---
2024-08-21T08:55:26.2685740Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-08-21T08:55:26.2686784Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
2024-08-21T08:55:26.2688362Z    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
2024-08-21T08:55:26.2688838Z    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2024-08-21T08:55:26.2689314Z    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2024-08-21T08:55:26.2689845Z    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
2024-08-21T08:55:26.2690417Z    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
2024-08-21T08:55:26.2691200Z    at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
2024-08-21T08:55:26.2691839Z    at Agent.Plugins.FileContainerProvider.<>c__DisplayClass7_1.<<DownloadFileContainerAsync>b__7>d.MoveNext() in D:\a\_work\1\s\src\Agent.Plugins\Artifact\FileContainerProvider.cs:line 220
2024-08-21T08:55:26.2692550Z --- End of stack trace from previous location ---
2024-08-21T08:55:26.2693006Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper.<>c__DisplayClass11_0.<<CreateTaskWrapper>b__0>d.MoveNext()
2024-08-21T08:55:26.2693525Z --- End of stack trace from previous location ---
2024-08-21T08:55:26.2693976Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2024-08-21T08:55:26.2694396Z Details:
2024-08-21T08:55:26.2694879Z No LastRequestResponse on exception IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:55:27.2832073Z Downloading: E:\ADO\Agents\Prod-1\_work\1/pc-pe-privatei-web-build-prod/Privatei.Web/Privatei.Web\Privatei.Web.zip
2024-08-21T08:55:31.1884560Z ##[debug]Agent environment resources - Disk: E:\ Available 455255.00 MB out of 511982.00 MB, Memory: Used 5282.00 MB out of 16380.00 MB, CPU: Usage 8.51%
2024-08-21T08:55:36.2545880Z ##[debug]Agent environment resources - Disk: E:\ Available 455205.00 MB out of 511982.00 MB, Memory: Used 5299.00 MB out of 16380.00 MB, CPU: Usage 7.43%
2024-08-21T08:55:41.3285966Z ##[debug]Agent environment resources - Disk: E:\ Available 455149.00 MB out of 511982.00 MB, Memory: Used 5318.00 MB out of 16380.00 MB, CPU: Usage 6.57%
2024-08-21T08:55:46.4008346Z ##[debug]Agent environment resources - Disk: E:\ Available 455081.00 MB out of 511982.00 MB, Memory: Used 5322.00 MB out of 16380.00 MB, CPU: Usage 5.90%
2024-08-21T08:55:51.4636831Z ##[debug]Agent environment resources - Disk: E:\ Available 455068.00 MB out of 511982.00 MB, Memory: Used 5310.00 MB out of 16380.00 MB, CPU: Usage 5.32%
2024-08-21T08:55:52.0335882Z [] Try 2/4, retryable exception caught. Retrying in 00:00:02.1552483. System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:55:52.0380902Z  ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
2024-08-21T08:55:52.0381600Z    --- End of inner exception stack trace ---
2024-08-21T08:55:52.0389361Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-08-21T08:55:52.0389887Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
2024-08-21T08:55:52.0390323Z    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
2024-08-21T08:55:52.0390713Z    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2024-08-21T08:55:52.0391068Z    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2024-08-21T08:55:52.0391481Z    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
2024-08-21T08:55:52.0392841Z    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
2024-08-21T08:55:52.0393246Z    at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
2024-08-21T08:55:52.0393721Z    at Agent.Plugins.FileContainerProvider.<>c__DisplayClass7_1.<<DownloadFileContainerAsync>b__7>d.MoveNext() in D:\a\_work\1\s\src\Agent.Plugins\Artifact\FileContainerProvider.cs:line 220
2024-08-21T08:55:52.0394269Z --- End of stack trace from previous location ---
2024-08-21T08:55:52.0395239Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper.<>c__DisplayClass11_0.<<CreateTaskWrapper>b__0>d.MoveNext()
2024-08-21T08:55:52.0395777Z --- End of stack trace from previous location ---
2024-08-21T08:55:52.0397767Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2024-08-21T08:55:52.0398159Z Details:
2024-08-21T08:55:52.0398540Z No LastRequestResponse on exception IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:55:54.2040731Z Downloading: E:\ADO\Agents\Prod-1\_work\1/pc-pe-privatei-web-build-prod/Privatei.Web/Privatei.Web\Privatei.Web.zip
2024-08-21T08:55:56.5198927Z ##[debug]Agent environment resources - Disk: E:\ Available 455258.00 MB out of 511982.00 MB, Memory: Used 5276.00 MB out of 16380.00 MB, CPU: Usage 4.91%
2024-08-21T08:56:01.5766697Z ##[debug]Agent environment resources - Disk: E:\ Available 455203.00 MB out of 511982.00 MB, Memory: Used 5294.00 MB out of 16380.00 MB, CPU: Usage 4.54%
2024-08-21T08:56:06.6609743Z ##[debug]Agent environment resources - Disk: E:\ Available 455133.00 MB out of 511982.00 MB, Memory: Used 5315.00 MB out of 16380.00 MB, CPU: Usage 4.24%
2024-08-21T08:56:11.7156934Z ##[debug]Agent environment resources - Disk: E:\ Available 455070.00 MB out of 511982.00 MB, Memory: Used 5333.00 MB out of 16380.00 MB, CPU: Usage 3.94%
2024-08-21T08:56:15.9404450Z [] Try 3/4, retryable exception caught. Retrying in 00:00:04.1127926. System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:56:15.9437350Z  ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
2024-08-21T08:56:15.9491171Z    --- End of inner exception stack trace ---
2024-08-21T08:56:15.9494980Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-08-21T08:56:15.9496839Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
2024-08-21T08:56:15.9497518Z    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
2024-08-21T08:56:15.9498018Z    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2024-08-21T08:56:15.9498498Z    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2024-08-21T08:56:15.9498929Z    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
2024-08-21T08:56:15.9499421Z    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
2024-08-21T08:56:15.9499852Z    at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
2024-08-21T08:56:15.9500345Z    at Agent.Plugins.FileContainerProvider.<>c__DisplayClass7_1.<<DownloadFileContainerAsync>b__7>d.MoveNext() in D:\a\_work\1\s\src\Agent.Plugins\Artifact\FileContainerProvider.cs:line 220
2024-08-21T08:56:15.9501027Z --- End of stack trace from previous location ---
2024-08-21T08:56:15.9501666Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper.<>c__DisplayClass11_0.<<CreateTaskWrapper>b__0>d.MoveNext()
2024-08-21T08:56:15.9502150Z --- End of stack trace from previous location ---
2024-08-21T08:56:15.9502552Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2024-08-21T08:56:15.9502785Z Details:
2024-08-21T08:56:15.9503039Z No LastRequestResponse on exception IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:56:16.7767868Z ##[debug]Agent environment resources - Disk: E:\ Available 455065.00 MB out of 511982.00 MB, Memory: Used 5290.00 MB out of 16380.00 MB, CPU: Usage 3.69%
2024-08-21T08:56:20.0440090Z Downloading: E:\ADO\Agents\Prod-1\_work\1/pc-pe-privatei-web-build-prod/Privatei.Web/Privatei.Web\Privatei.Web.zip
2024-08-21T08:56:21.8438621Z ##[debug]Agent environment resources - Disk: E:\ Available 455263.00 MB out of 511982.00 MB, Memory: Used 5254.00 MB out of 16380.00 MB, CPU: Usage 3.46%
2024-08-21T08:56:26.8977887Z ##[debug]Agent environment resources - Disk: E:\ Available 455211.00 MB out of 511982.00 MB, Memory: Used 5277.00 MB out of 16380.00 MB, CPU: Usage 3.26%
2024-08-21T08:56:31.9577517Z ##[debug]Agent environment resources - Disk: E:\ Available 455162.00 MB out of 511982.00 MB, Memory: Used 5288.00 MB out of 16380.00 MB, CPU: Usage 3.12%
2024-08-21T08:56:37.0334874Z ##[debug]Agent environment resources - Disk: E:\ Available 455090.00 MB out of 511982.00 MB, Memory: Used 5303.00 MB out of 16380.00 MB, CPU: Usage 2.96%
2024-08-21T08:56:42.1102562Z ##[debug]Agent environment resources - Disk: E:\ Available 455070.00 MB out of 511982.00 MB, Memory: Used 5284.00 MB out of 16380.00 MB, CPU: Usage 2.81%
2024-08-21T08:56:42.8296106Z [] Try 4/4, retryable exception caught. Retrying in 00:00:07.4144793. System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:56:42.8297761Z  ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
2024-08-21T08:56:42.8327586Z    --- End of inner exception stack trace ---
2024-08-21T08:56:42.8328200Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-08-21T08:56:42.8328704Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
2024-08-21T08:56:42.8329168Z    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
2024-08-21T08:56:42.8329580Z    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2024-08-21T08:56:42.8329965Z    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2024-08-21T08:56:42.8330397Z    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
2024-08-21T08:56:42.8330897Z    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
2024-08-21T08:56:42.8331332Z    at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
2024-08-21T08:56:42.8331835Z    at Agent.Plugins.FileContainerProvider.<>c__DisplayClass7_1.<<DownloadFileContainerAsync>b__7>d.MoveNext() in D:\a\_work\1\s\src\Agent.Plugins\Artifact\FileContainerProvider.cs:line 220
2024-08-21T08:56:42.8332436Z --- End of stack trace from previous location ---
2024-08-21T08:56:42.8332838Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper.<>c__DisplayClass11_0.<<CreateTaskWrapper>b__0>d.MoveNext()
2024-08-21T08:56:42.8333288Z --- End of stack trace from previous location ---
2024-08-21T08:56:42.8333674Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2024-08-21T08:56:42.8334193Z Details:
2024-08-21T08:56:42.8334669Z No LastRequestResponse on exception IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:56:47.1639928Z ##[debug]Agent environment resources - Disk: E:\ Available 455065.00 MB out of 511982.00 MB, Memory: Used 5273.00 MB out of 16380.00 MB, CPU: Usage 2.68%
2024-08-21T08:56:50.2330682Z Downloading: E:\ADO\Agents\Prod-1\_work\1/pc-pe-privatei-web-build-prod/Privatei.Web/Privatei.Web\Privatei.Web.zip
2024-08-21T08:56:52.2252411Z ##[debug]Agent environment resources - Disk: E:\ Available 455259.00 MB out of 511982.00 MB, Memory: Used 5257.00 MB out of 16380.00 MB, CPU: Usage 2.56%
2024-08-21T08:56:57.3147517Z ##[debug]Agent environment resources - Disk: E:\ Available 455212.00 MB out of 511982.00 MB, Memory: Used 5273.00 MB out of 16380.00 MB, CPU: Usage 2.45%
2024-08-21T08:57:02.3787535Z ##[debug]Agent environment resources - Disk: E:\ Available 455156.00 MB out of 511982.00 MB, Memory: Used 5303.00 MB out of 16380.00 MB, CPU: Usage 2.35%
2024-08-21T08:57:07.4512239Z ##[debug]Agent environment resources - Disk: E:\ Available 455082.00 MB out of 511982.00 MB, Memory: Used 5315.00 MB out of 16380.00 MB, CPU: Usage 2.25%
2024-08-21T08:57:12.8490650Z ##[debug]Agent environment resources - Disk: E:\ Available 455067.00 MB out of 511982.00 MB, Memory: Used 5301.00 MB out of 16380.00 MB, CPU: Usage 2.16%
2024-08-21T08:57:13.0579062Z [] Try 5/4, retryable exception caught, but retries have been exhausted. Throwing. System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:57:13.0661189Z  ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
2024-08-21T08:57:13.0682682Z    --- End of inner exception stack trace ---
2024-08-21T08:57:13.0687412Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-08-21T08:57:13.0698929Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
2024-08-21T08:57:13.0709283Z    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
2024-08-21T08:57:13.0722049Z    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2024-08-21T08:57:13.0723514Z    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2024-08-21T08:57:13.0724469Z    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
2024-08-21T08:57:13.0725045Z    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
2024-08-21T08:57:13.0725503Z    at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
2024-08-21T08:57:13.0726158Z    at Agent.Plugins.FileContainerProvider.<>c__DisplayClass7_1.<<DownloadFileContainerAsync>b__7>d.MoveNext() in D:\a\_work\1\s\src\Agent.Plugins\Artifact\FileContainerProvider.cs:line 220
2024-08-21T08:57:13.0726870Z --- End of stack trace from previous location ---
2024-08-21T08:57:13.0727316Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper.<>c__DisplayClass11_0.<<CreateTaskWrapper>b__0>d.MoveNext()
2024-08-21T08:57:13.0728072Z --- End of stack trace from previous location ---
2024-08-21T08:57:13.0728459Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2024-08-21T08:57:13.0728795Z Details:
2024-08-21T08:57:13.0729174Z No LastRequestResponse on exception IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:57:13.0768629Z ##[error]Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:57:13.0784604Z ##[debug]Processed: ##vso[task.logissue type=error;]Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-08-21T08:57:13.0793931Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2024-08-21T08:57:13.0798988Z ##[debug]   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
   at Agent.Plugins.FileContainerProvider.<>c__DisplayClass7_1.<<DownloadFileContainerAsync>b__7>d.MoveNext() in D:\a\_work\1\s\src\Agent.Plugins\Artifact\FileContainerProvider.cs:line 220
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper.<>c__DisplayClass11_0.<<CreateTaskWrapper>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.ExceptionExtensions.ReThrow(Exception ex)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Agent.Plugins.FileContainerProvider.<>c__DisplayClass7_0.<<DownloadFileContainerAsync>b__4>d.MoveNext() in D:\a\_work\1\s\src\Agent.Plugins\Artifact\FileContainerProvider.cs:line 206
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingActionBlock.<>c__DisplayClass5_0`1.<<CreateNonSwallowingFunc>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Services.Content.Common.TargetBlockExtensions.SendAllAndCompleteAsync[T1](ITargetBlock`1 targetBlock, IEnumerable`1 inputs, CancellationToken token)
   at Agent.Plugins.FileContainerProvider.DownloadFileContainerAsync(IEnumerable`1 items, ArtifactDownloadParameters downloadParameters, BuildArtifact artifact, String rootPath, AgentTaskPluginExecutionContext context, CancellationToken cancellationToken, Boolean isSingleArtifactDownload) in D:\a\_work\1\s\src\Agent.Plugins\Artifact\FileContainerProvider.cs:line 239
   at Agent.Plugins.FileContainerProvider.DownloadSingleArtifactAsync(ArtifactDownloadParameters downloadParameters, BuildArtifact buildArtifact, CancellationToken cancellationToken, AgentTaskPluginExecutionContext context) in D:\a\_work\1\s\src\Agent.Plugins\Artifact\FileContainerProvider.cs:line 62
   at Agent.Plugins.PipelineArtifactServer.DownloadAsyncV2(AgentTaskPluginExecutionContext context, ArtifactDownloadParameters downloadParameters, DownloadOptions downloadOptions, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Agent.Plugins\Artifact\PipelineArtifactServer.cs:line 310
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV2_0_0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token) in D:\a\_work\1\s\src\Agent.Plugins\PipelineArtifact\PipelineArtifactPluginV2.cs:line 301
   at Agent.PluginHost.Program.Main(String[] args) in D:\a\_work\1\s\src\Agent.PluginHost\Program.cs:line 71
2024-08-21T08:57:13.0849133Z ##[section]Finishing: DownloadPipelineArtifact
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by EshitaD** [comment]
Hi @rajorin, does this issue still persist? If so, could you let me know what you're trying to use in the artifact, so we can reproduce the issue?

**Comment by v-schhabra** [comment]
As DownloadPipelineArtifact is owned by Artifacts team so assigning it to them.

**Comment by rajorin** [comment]
Hi, This issue has been resolved after connecting with ADO support and whitelisting ADO IPs on org level firewall. Thank you all for your help.
