### ISSUE TITLE
[BUG]: PublishCodeCoverageResults@2 Error occured while parsing coverage files. System.InvalidOperationException: Nullable object must have a value.

### ISSUE THREAD

**Issue by Aerodynamite** [microsoft/azure-pipelines-tasks#20673]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

PublishCodeCoverageResults

### Task version

2.248.3

### Issue Description

Publishing code coverage stopped working in version 2.248.3 with error **Error occured while parsing coverage files. System.InvalidOperationException: Nullable object must have a value.** 

I have a build from a couple of days ago which worked and was using version 2.242.1 of the task. Running the pipeline from the exact same commit today fails with the only difference being the new task version.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Relevant log output

```shell
2024-11-19T13:59:02: Creating report 621/622 (Assembly: MyModule.Application, Class: MyModule.Application.MyModuleApplicationAssemblyMarker)
2024-11-19T13:59:02: Writing report file 'MyModule.Application_MyModuleApplicationAssemblyMarker.html'
2024-11-19T13:59:02: Creating report 622/622 (Assembly: MyModule.Application, Class: MyModule.Application.MyModuleMappingProfile)
2024-11-19T13:59:02: Writing report file 'MyModule.Application_MyModuleMappingProfile.html'
2024-11-19T13:59:02: Creating summary
2024-11-19T13:59:02: Writing report file '/home/vsts/work/_temp/5011078a-bc1a-4766-afe9-f0f7048b5a65/index.html'
##[error]Error occured while parsing coverage files. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Microsoft.Azure.Pipelines.CoveragePublisher.Parsers.ReportGeneratorTool.GetFileCoverageInfos() in D:\a\1\s\src\CoveragePublisher\Parsers\CoverageParserTools\ReportGeneratorTool.cs:line 63
   at Microsoft.Azure.Pipelines.CoveragePublisher.Parsers.Parser.GetFileCoverageInfos() in D:\a\1\s\src\CoveragePublisher\Parsers\Parser.cs:line 35
```

### Repro steps

```yml

```

**Comment by Aerodynamite** [comment]
I notice the Microsoft Hosted Agents have reverted the task version back to 2.248.1, which does not seem to have this issue.

**Comment by jdngray77** [comment]
We've seen the same issue today in production, and have also seen since that the task version has been reverted back to `2.248.1`, fixing our build.

I think this issue however can probably be closed, it looks like the fix for this went in 4 days ago in [!79](https://github.com/microsoft/azure-pipelines-coveragepublisher/pull/79/) in [this commit](https://github.com/microsoft/azure-pipelines-coveragepublisher/pull/79/commits/e104ac73e116f0df3feb9615a4d1cdfca692f2a4)

**Comment by vinayakmsft** [comment]
Task version is reverted to 2.248.1, which does not have the issue.
