### ISSUE TITLE
[BUG]: KubectlInstaller@0 does not support installing latest kubectl versions

### ISSUE THREAD

**Issue by TeodoraEinoryte** [microsoft/azure-pipelines-tasks#20702]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

KubectlInstaller@0

### Task version

0

### Issue Description

KubectlInstaller uses such URL https://storage.googleapis.com/kubernetes-release/release/v1.30.7/bin/linux/amd64/kubectl to download kubectl. However, latest versions are not available using such URL - from 1.30.5 to 1.31.3 (except for 1.30.0).  

When installing 1.30.7 using KubectlInstaller@0, I get error:
```
Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.30.7/bin/linux/amd64/kubectl
##[error]Error: Failed to download kubectl from location https://storage.googleapis.com/kubernetes-release/release/v1.30.7/bin/linux/amd64/kubectl. Error Error: Unexpected HTTP response: 404
    at Object.<anonymous> (/home/agent-admin/_work/_tasks/KubectlInstaller_8413c881-4959-43d5-8840-b4ea0ffc5cfd/0.247.1/node_modules/azure-pipelines-tasks-kubernetes-common/node_modules/azure-pipelines-tool-lib/tool.js:216:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/agent-admin/_work/_tasks/KubectlInstaller_8413c881-4959-43d5-8840-b4ea0ffc5cfd/0.247.1/node_modules/azure-pipelines-tasks-kubernetes-common/node_modules/azure-pipelines-tool-lib/tool.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  httpStatusCode: 404
}
```

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Relevant log output

```shell
Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.30.7/bin/linux/amd64/kubectl
##[error]Error: Failed to download kubectl from location https://storage.googleapis.com/kubernetes-release/release/v1.30.7/bin/linux/amd64/kubectl. Error Error: Unexpected HTTP response: 404
    at Object.<anonymous> (/home/agent-admin/_work/_tasks/KubectlInstaller_8413c881-4959-43d5-8840-b4ea0ffc5cfd/0.247.1/node_modules/azure-pipelines-tasks-kubernetes-common/node_modules/azure-pipelines-tool-lib/tool.js:216:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/agent-admin/_work/_tasks/KubectlInstaller_8413c881-4959-43d5-8840-b4ea0ffc5cfd/0.247.1/node_modules/azure-pipelines-tasks-kubernetes-common/node_modules/azure-pipelines-tool-lib/tool.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  httpStatusCode: 404
}
```

### Repro steps

```yml
jobs:
- job:

  steps:

  - task: KubectlInstaller@0
    inputs:
      kubectlVersion: 1.30.7
```

**Comment by peress** [comment]
https://github.com/Azure/azure-cli/pull/30130 This fixed the url and the new v2.66.0 of Azure Cli was released.
Yet, the KubectlInstaller v0.247.1 is still using the old url.

i'm also having the same issue.

**Comment by nnellanspdl** [comment]
Still seems to be an issue.  My pipelines are busted still.

**Comment by v-bkasu** [comment]
@peress , @nnellanspdl - The changes will be available in few more days. Will notify once the changes are available.

**Comment by Stephani0106** [comment]
Same issue here! We tried to install Kubernetes version 1.31.2 and received the same error. In version 1.30.3 it works.

**Comment by v-bkasu** [comment]
Hi All,

the changes have been deployed for KubectlInstaller@0. for Kubernetes@X, the changes deployment yet to be done and it can be tracked under this [Git ](https://github.com/microsoft/azure-pipelines-tasks/issues/20888)issue.
