### ISSUE TITLE
PowerShell on Target Machines task: Setting $ErrorActionPreference to "Continue" does not behave as expected

### ISSUE THREAD

**Issue by shaykalyan** [Microsoft/azure-pipelines-tasks#4130]
The default error action when using this task is `"Stop"`, which causes commands such as `Write-Error` to terminate the script execution. Setting the `$ErrorActionPreference` to `"Continue"` in the invoked script does not result in the execution to continue as expected per the docs ([about_Preference_Variables](https://technet.microsoft.com/en-us/library/dd347731.aspx)). 

E.g., running a .ps1 with the following
```
$ErrorActionPreference = "Continue"
Write-Output "Foo"
Write-Error "Bar"
Write-Output "Baz"
Exit 0
```
has the following output in the RM agent logs
<Details>
2017-04-25T23:45:44.8633391Z     Deployment started on target machine...

2017-04-25T23:45:44.8633391Z 

2017-04-25T23:45:44.8633391Z System.AggregateException: Failed to execute the powershell script. Consult the logs below for details of the error.

2017-04-25T23:45:44.8633391Z 

2017-04-25T23:45:44.8633391Z Bar

2017-04-25T23:45:44.8633391Z  +At line:1 char:1

2017-04-25T23:45:44.8633391Z + . "<path to script>\temp.ps1"

2017-04-25T23:45:44.8633391Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2017-04-25T23:45:44.8633391Z  CategoryInfo :NotSpecified: (:) [Write-Error], WriteErrorException

2017-04-25T23:45:44.8633391Z  FullyQualifiedErrorId :Microsoft.PowerShell.Commands.WriteErrorException,temp.ps1

2017-04-25T23:45:44.8633391Z  ---> Microsoft.PowerShell.Commands.WriteErrorException: Bar

2017-04-25T23:45:44.8633391Z    --- End of inner exception stack trace ---

2017-04-25T23:45:44.8633391Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String 
errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)

2017-04-25T23:45:44.8633391Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.ExecuteScript(IPowerShell 
powerShell, String script, String arguments, Boolean isScriptDotSourced, Boolean useHttp)

2017-04-25T23:45:44.8633391Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(
DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, 
String applicationPath, IPowerShell powerShellSession)

2017-04-25T23:45:44.8633391Z ---> (Inner Exception #0) Microsoft.PowerShell.Commands.WriteErrorException: Bar<---

2017-04-25T23:45:44.8633391Z 

2017-04-25T23:45:44.8633391Z 

2017-04-25T23:45:44.8633391Z Deployment status for machine '<hostname>:5985' : 'Failed'

2017-04-25T23:45:44.8789655Z 

2017-04-25T23:45:44.8789655Z 

2017-04-25T23:45:44.8945888Z ##[error]System.Management.Automation.RuntimeException: Bar ---> System.Management.Automation.RuntimeException: Bar

2017-04-25T23:45:44.8945888Z    --- End of inner exception stack trace ---

2017-04-25T23:45:44.8945888Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)

2017-04-25T23:45:44.8945888Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)

2017-04-25T23:45:44.8945888Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)

2017-04-25T23:45:44.8945888Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, 
PSDataCollection`1 output, PSInvocationSettings settings)

2017-04-25T23:45:44.8945888Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 
output, PSInvocationSettings settings)

2017-04-25T23:45:44.8945888Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)

2017-04-25T23:45:44.9102161Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

2017-04-25T23:45:44.9102161Z ##[section]Finishing: Run temp.ps1 on <hostname>

2017-04-25T23:45:44.9258399Z ##[section]Finishing: Release
</Details>
<br>

Compared to running via a local Powershell window:
```
Foo
\\path\to\script\temp.ps1 : Bar
At line:1 char:1
+ .\temp.ps1
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,temp.ps1
Baz
```

Thanks!

**Comment by Mobrockers** [comment]
We are experiencing the same issue when trying to perform an unattended upgrade to TFS2018 because of a warning about sharepoint sites and workitem migrations being returned by TfsConfig.
