### ISSUE TITLE
NuGet Command: Microsoft.VisualStudio.Services.Common.VssServiceException: TF400898

### ISSUE THREAD

**Issue by RaleS** [Microsoft/azure-pipelines-tasks#5318]
NuGet push (NuGetCommand 2.0.6) failes with internal error
Exception: Microsoft.VisualStudio.Services.Common.VssServiceException: TF400898
NuGet version: 4.3.0.4406

```
2017-09-13T21:06:50.3192183Z ##[section]Starting: NuGet push
2017-09-13T21:06:50.3192183Z ==============================================================================
2017-09-13T21:06:50.3202006Z Task         : NuGet
2017-09-13T21:06:50.3202006Z Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Package Management and MyGet.
2017-09-13T21:06:50.3202006Z Version      : 2.0.6
2017-09-13T21:06:50.3202006Z Author       : Microsoft Corporation
2017-09-13T21:06:50.3202006Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613747)
2017-09-13T21:06:50.3202006Z ==============================================================================
2017-09-13T21:06:51.1196757Z [command]C:\Windows\system32\chcp.com 65001
2017-09-13T21:06:51.1196757Z Active code page: 65001
2017-09-13T21:06:51.1974971Z SYSTEMVSSCONNECTION exists true
2017-09-13T21:06:51.2063592Z Detected NuGet version 4.3.0.4406 / 4.3.0
2017-09-13T21:06:51.5382997Z Saving NuGet.config to a temporary config file.
2017-09-13T21:06:51.5619399Z ##[warning]No package sources were found in the NuGet.config file at d:\a\1\Nuget\tempNuGet_533.config
2017-09-13T21:06:51.5668653Z [command]d:\a\_tasks\NuGetCommand_333b11bd-d341-40d9-afcf-b32d5ce6f23b\2.0.6\VstsNuGetPush\0.13.0\VstsNuGetPush.exe d:\a\1\s\src\utl\Tools\Tools\bin\release\Tools.1.1.0-unstable0131.nupkg -Source https://***.pkgs.visualstudio.com/_packaging/***/nuget/v3/index.json -AccessToken ******** -NonInteractive -Verbosity Detailed
2017-09-13T21:06:52.4634994Z Trying to authenticate with auth token.
2017-09-13T21:06:53.4090884Z Successfully authenticated.
2017-09-13T21:06:53.4090884Z Authentication and request took 00:00:01.6416400
2017-09-13T21:06:53.4120487Z Adding package Tools.1.1.0-unstable0131.nupkg to feed *** on https://***.pkgs.visualstudio.com/.
2017-09-13T21:06:53.4386908Z Trying to add package to feed without uploading.
2017-09-13T21:06:53.4396801Z Adding package to feed.
2017-09-13T21:06:54.7662870Z The package content is not already on the service.
2017-09-13T21:06:54.7672762Z Uploading package content.
2017-09-13T21:06:55.7557848Z Done uploading package content.
2017-09-13T21:06:55.7567730Z Adding package to feed.
2017-09-13T21:06:56.4285491Z Error:
2017-09-13T21:06:56.4443733Z Microsoft.VisualStudio.Services.Common.VssServiceException: TF400898: An Internal Error Occurred. Activity Id: af18d4ab-8e97-4fc2-8400-8b732305503e.
2017-09-13T21:06:56.4443733Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
2017-09-13T21:06:56.4443733Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47.MoveNext()
2017-09-13T21:06:56.4443733Z --- End of stack trace from previous location where exception was thrown ---
2017-09-13T21:06:56.4443733Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-09-13T21:06:56.4443733Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-13T21:06:56.4443733Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__29.MoveNext()
2017-09-13T21:06:56.4443733Z --- End of stack trace from previous location where exception was thrown ---
2017-09-13T21:06:56.4443733Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-09-13T21:06:56.4453838Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-13T21:06:56.4453838Z    at VstsNuGetPush.PackageAdder.AddPackageToFeed(String feedName, BlobIdentifierWithBlocks blobId)
2017-09-13T21:06:56.4453838Z    at VstsNuGetPush.VstsNuGetPushOperation.AddPackageToFeed(BlobIdentifierWithBlocks blobId)
2017-09-13T21:06:56.4453838Z    at VstsNuGetPush.VstsNuGetPushCommand.MainCore(ILogger logger)
2017-09-13T21:06:56.4453838Z    at VstsNuGetPush.VstsNuGetPushCommand.Main()
2017-09-13T21:06:56.5027397Z ##[error]Error: d:\a\_tasks\NuGetCommand_333b11bd-d341-40d9-afcf-b32d5ce6f23b\2.0.6\VstsNuGetPush\0.13.0\VstsNuGetPush.exe failed with return code: 1
2017-09-13T21:06:56.5027397Z ##[error]Packages failed to publish
2017-09-13T21:06:56.5159004Z ##[section]Finishing: NuGet push

```

**Comment by satbai** [comment]
@RaleS We are investigating this issue and will respond back once we have more information. Based on our logs this was a transient issue, but please let us know if you encounter this error again.

**Comment by shubham90** [comment]
@RaleS Are you still facing this issue? If yes, please paste the new logs so that I can check for any issues on the server side.

**Comment by RaleS** [comment]
@shubham90 The best logs I have is the one above. The latest available NuGetCommand 2.0.12 is also using VstsNuGetPush.exe 0.13.0. What version has the fix?

**Comment by shubham90** [comment]
@RaleS Sorry but I didn't get if this is working now or was it a transient issue for you. Could you please check if this is working now? This doesn't look like a client issue, so, not related to VstsNugetPush.exe version.

**Comment by RaleS** [comment]
@shubham90 The issue cannot be reproduced. It seems that the retry logic could solve it, but you write that the issue is not on the client side, so i assume that retry logic is already implemented. Hopefully there will be more logging next time it appears. Feel free to close the issue.

**Comment by PilotBob** [comment]
FYI: This just happened to me a few minutes ago.

**Comment by peetw** [comment]
I also just experienced this exact issue. Logs from the VSTS Nuget Push task are here: https://pastebin.com/FpkCMrdg

Definitely looks like a transient issue as re-running the build worked fine...

**Comment by coryvb123** [comment]
I get this error from time to time as well. Re-running the build works fine, though it's pretty annoying. Even if the NuGet Push task had a "Retry X times" option...

**Comment by AymericG** [comment]
I keep having this intermittent issue too. Same logs...

**Comment by phil-hodgson** [comment]
@AymericG Could you share the "ActivityId" entries from the logs of your latest repros?
e.g. "Microsoft.VisualStudio.Services.Common.VssServiceException: TF400898: An Internal Error Occurred. Activity Id: **7d225f18-6c6f-48f4-82b8-c294debbdc22**."

**Comment by sundar85** [comment]
I get the same error too.

Microsoft.VisualStudio.Services.Common.VssServiceException: TF400898: An Internal Error Occurred. Activity Id: 4c417f0b-fdc7-4a9e-bb0d-cfcddce77209.

**Comment by demyte** [comment]
Hi there,

I have this issue as well.

Activity Id: fec4a081-b2e5-4a94-bb5c-751159b24222

Debug log attached
[14.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2588011/14.txt)

**Comment by alexmullans** [comment]
Since we haven't recently seen this, closing as part of a triage pass. If you happen upon this issue/error in your builds, please report it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) so we can investigate.
