### ISSUE TITLE
[AppCenterTest Task] Cannot upload UITests (NUnit based)

### ISSUE THREAD

**Issue by rmarinho** [microsoft/azure-pipelines-tasks#6445]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS    
    - https://devdiv.visualstudio.com/DevDiv/Xamarin%20Forms/_apps/hub/ms.vss-releaseManagement-web.cd-workflow-hub?definitionId=567&_a=environments-editor-preview    
- Agent - Hosted: 
    
    - If using Hosted agent, provide agent queue name: Hosted or Hosted 2017

## Issue Description

Moving from the Xamarin Test Cloud task that was deprecated to AppCenter one, i have moved most of my properties and adjusted to AppCenter, when the script is runned i get error `System.Reflection.ReflectionTypeLoadException`

### Error logs

```
2018-02-15T15:05:43.2452232Z ##[section]Starting: Test with Visual Studio App Center
2018-02-15T15:05:43.2458698Z ==============================================================================
2018-02-15T15:05:43.2459419Z Task         : App Center Test
2018-02-15T15:05:43.2459969Z Description  : Test app packages with Visual Studio App Center.
2018-02-15T15:05:43.2460647Z Version      : 1.129.0
2018-02-15T15:05:43.2461344Z Author       : Microsoft Corporation
2018-02-15T15:05:43.2462020Z Help         : For help with this task, visit the Visual Studio App Center [support site](https://aka.ms/appcentersupport).
2018-02-15T15:05:43.2462757Z ==============================================================================
2018-02-15T15:05:43.8075347Z [command]C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.129.0\node_modules\.bin\appcenter.cmd test prepare uitest --artifacts-dir D:\a\r1\a\AppCenterTest --app-path D:/a/r1/a/build/OSXArtifacts/ios/XamarinFormsControlGalleryiOS.ipa --build-dir D:\a\r1\a\build\OSXArtifacts\ios --uitest-tools-dir D:\a\r1\a\build\OSXArtifacts\testcloud --debug --quiet"
2018-02-15T15:06:05.5927346Z Test chunking failed: Failed to execute: D:\a\_temp\uitest\a-B9B20274E1D5FFBC94ED0416C8F5121EAC0C3959\nunit2\Xamarin.UITest.Integration.NUnit2.exe "D:\a\r1\a\build\OSXArtifacts\ios\Xamarin.Forms.Core.iOS.UITests.dll" - exit code: -532462766
2018-02-15T15:06:05.5928452Z 
2018-02-15T15:06:05.5929270Z Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
2018-02-15T15:06:05.5930293Z    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2018-02-15T15:06:05.5930949Z    at System.Reflection.Assembly.GetTypes()
2018-02-15T15:06:05.5931661Z    at NUnit.Core.Builders.TestAssemblyBuilder.GetCandidateFixtureTypes(Assembly assembly, String ns)
2018-02-15T15:06:05.5932892Z    at NUnit.Core.Builders.TestAssemblyBuilder.GetFixtures(Assembly assembly, String ns)
2018-02-15T15:06:05.5933676Z    at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, Boolean autoSuites)
2018-02-15T15:06:05.5934673Z    at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, String testName, Boolean autoSuites)
2018-02-15T15:06:05.5935519Z    at NUnit.Core.TestSuiteBuilder.BuildSingleAssembly(TestPackage package)
2018-02-15T15:06:05.5940432Z    at NUnit.Core.TestSuiteBuilder.Build(TestPackage package)
2018-02-15T15:06:05.5941363Z    at Xamarin.UITest.Integration.NUnit2.NUnit2TestFinder.Find(String assemblyFile, String[] fixtures, String[] includedCategories, String[] excludedCategories)
2018-02-15T15:06:05.5942508Z    at Xamarin.UITest.Integration.NUnit2.Program.Main(String[] args)
2018-02-15T15:06:05.5942877Z 
2018-02-15T15:06:05.5982164Z Preparing tests... failed.
2018-02-15T15:06:05.5983370Z Error: Cannot prepare UI Test artifacts using command: D:\a\r1\a\build\OSXArtifacts\testcloud\test-cloud.exe prepare "D:/a/r1/a/build/OSXArtifacts/ios/XamarinFormsControlGalleryiOS.ipa" --assembly-dir "D:\a\r1\a\build\OSXArtifacts\ios" --artifacts-dir "D:\a\r1\a\AppCenterTest".
2018-02-15T15:06:05.5984181Z 
2018-02-15T15:06:05.5984870Z Test chunking failed, please try again. If you can't work out how to fix this issue, please contact support.
2018-02-15T15:06:05.6269758Z ##[error]Error: D:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.129.0\node_modules\.bin\appcenter.cmd failed with return code: 3
```

**Comment by owenniblock** [comment]
Thanks for the error report, we'll take a look and see what we can work out.

**Comment by owenniblock** [comment]
Hi @rmarinho 

I've been doing some digging this evening and I can successfully run the `prepare` command on my mac using the iOSXArtifacts/ios folder and it worked successfully.

I wonder if the VSTS Host Agent used is missing something (Standard Library stuff maybe?) that would cause this sort of error when it tried to access assemblies which don't exist on the target machine?

**Comment by rmarinho** [comment]
@owenniblock shouldn't that be a dependency of the the task?

**Comment by owenniblock** [comment]
I don't think so - you don't need to be using Standard Library to use App Center Test but if you've built your tests using Standard Library - it's possible that a dependency exists there? Same as if you'd built the tests using .Net 4.5.

It's just a hunch (I don't know your project that well) - alternatively - I think this is running on a Windows host - you could also try running it on a mac host and see if that makes a difference? (I guess it could also be missing some iOS deps which it expects for iOS tests?)

**Comment by owenniblock** [comment]
Just posting this here after some investigation from @rmarinho 

The App Center Test task works correctly on the [Mac Host Agent](https://devdiv.visualstudio.com/DevDiv/Xamarin%20Forms/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?releaseId=78737&definitionId=567&_a=release-logs)

Suspect that because the test DLL references iOS specific stuff - the Reflection required by the `prepare` command fails.

Solution is to run the tests using the the Mac agent. Suspect this issue won't occur with Android only tests or non UITest tests.

**Comment by owenniblock** [comment]
Reopened while @rmarinho and I discuss getting Android tests running on Windows (in case the same issue exists when running against the Android build).

**Comment by King-of-Spades** [comment]
While I'm necroing a bit by commenting on here, I have one observation to note that when testing on a local system, iOS test execution is *not supported* nor even possible by any means I'm aware of on Windows. 

While Xamarin.iOS does allow the building, debugging and running of an iOS app from Windows through the use of a paired Mac Build Host; this setup cannot be used with Xamarin.UITest. 

It's possible that whatever the integration is that refers to a Windows vs. Mac Host Agent here: https://github.com/Microsoft/azure-pipelines-tasks/issues/6445#issuecomment-366275699

Is effectively bound by the same sort of limitation.

**Comment by kingces95** [comment]
I also see `Error: Cannot prepare UI Test artifacts using command:`

```
X:\git\forms>appcenter test run uitest --app "xtc-Xamarin-Forms/AndroidControlGallery-1" --devices "xtc-Xamarin-Forms/api19" --app-path X:\git\forms\Xamarin.Forms.ControlGallery.Android\obj\Debug\90\android\bin\AndroidControlGallery.AndroidControlGallery.apk  --test-series "pull-5248" --locale "en_US" --build-dir X:\git\forms\Xamarin.Forms.ControlGallery.Android\obj\Debug\90\android\bin\ --uitest-tools-dir C:\git\forms\packages\Xamarin.UITest.2.2.4\tools\
/ Preparing tests... Invalid assembly path: X:\git\forms\Xamarin.Forms.ControlGallery.Android\obj\Debug\90\android\bin" --artifacts-dir C:\Users\Chris\AppData\Local\Temp\appcenter-upload119315-8864-8e6zzc.tysnb

Preparing tests... failed.
Error: Cannot prepare UI Test artifacts using command: C:\git\forms\packages\Xamarin.UITest.2.2.4\tools\test-cloud.exe prepare "X:\git\forms\Xamarin.Forms.ControlGallery.Android\obj\Debug\90\android\bin\AndroidControlGallery.AndroidControlGallery.apk" --assembly-dir "X:\git\forms\Xamarin.Forms.ControlGallery.Android\obj\Debug\90\android\bin\" --artifacts-dir "C:\Users\Chris\AppData\Local\Temp\appcenter-upload119315-8864-8e6zzc.tysnb".

The assembly directory was not found, please try again. If you can't work out how to fix this issue, please contact support.

Further error details: For help, please send both the reported error above and the following environment information to us by going to https://appcenter.ms/apps and starting a new conversation (using the icon in the bottom right corner of the screen)

    Environment: win32
    App Upload Id: xtc-Xamarin-Forms/AndroidControlGallery-1
    Timestamp: 1555389013294
    Operation: RunUITestsCommand
    Exit Code: 4
    User Email: kingces95@gmail.com
    User Name: Chris-King-sv7p25w8
    User Id: 374a723f-73b6-433d-a5e2-5d24077606a5
```

**Comment by owenniblock** [comment]
@kingces95 - that's a different error, looks like it can't locate (or access) the assembly path for some reason.

See if you can locate it in a command line? If not, please either reach out to us using the support in the App Center portal or create a new Issue here.

**Comment by prudx** [comment]
I also am seeing this error

`Cannot prepare UI Test artifacts using command: C:\Users\dnlma\.nuget\packages\xamarin.uitest\2.2.4\tools\test-cloud.exe prepare "C:\Users\dnlma\Desktop\com.prudx.grocerymate.apk" --assembly-dir "C:\Users\dnlma\Documents\Code\Project\GroceryMateApp\Product Lookup\App-UITests\bin\Debug" --artifacts-dir "C:\Users\dnlma\AppData\Local\Temp\appcenter-upload119328-4024-3ypjms.j8s4o".

There was an unknown error preparing test artifacts, please try again. If you can't work out how to fix this issue, please contact support.

Further error details: For help, please send both the reported error above and the following environment information to us by going to https://appcenter.ms/apps and starting a new conversation (using the icon in the bottom right corner of the screen)

    Environment: win32
    App Upload Id: prudx/GroceryMate
    Timestamp: 1556469870267
    Operation: RunUITestsCommand
    Exit Code: 1
    User Email: dnl.maguire@gmail.com
    User Name: prudx
    User Id: 7160c05c-f6c3-44df-a50a-7043d5947a39`

**Comment by owenniblock** [comment]
@prudx that's also a different error, please reach out to us using the support channels in the App Center portal and someone will help you.

I would also advise using the latest UITest nuget in case you've hit an issue which has already need resolved.

**Comment by leantk** [comment]
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days
