### ISSUE TITLE
VSTS Publish Test Results in Release Definition - Forbidden

### ISSUE THREAD

**Issue by WaelHamze** [Microsoft/azure-pipelines-tasks#7173]
Hi Team,

## Troubleshooting
I am facing any issue when publishing test results from a release definition. The test run is successful.

## Environment
The setup is VSTS with private on-premises agent behind proxy. Agent is configured to connect using the proxy.

I have updated the agent to latest version and using Visual Studio 2017 Enterprise 15.5.

## Issue Description
Note the same tests run successfully and are published from a build definition on the same agent with no issues.

## Error logs (after setting system.debug = true)

2018-05-10T12:23:01.5943183Z Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
2018-05-10T12:23:01.5943505Z Test Run Successful.
2018-05-10T12:23:01.5952848Z Test execution time: 8.9492 Seconds
2018-05-10T12:23:01.6149530Z Results File: D:\xxxxxx\_work\r9\a\TestResults\xxxxxx_2018-05-10_13_23_01.trx
2018-05-10T12:23:01.6414427Z ##[debug]rc:0
2018-05-10T12:23:01.6415308Z ##[debug]success:true
2018-05-10T12:23:01.6422401Z ##[debug]defaultRoot: 'D:\xxxxxx\_work\r9\a\TestResults'
2018-05-10T12:23:01.6422955Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2018-05-10T12:23:01.6423281Z ##[debug]findOptions.followSymbolicLinks: 'true'
2018-05-10T12:23:01.6423519Z ##[debug]matchOptions.debug: 'false'
2018-05-10T12:23:01.6423729Z ##[debug]matchOptions.nobrace: 'true'
2018-05-10T12:23:01.6424032Z ##[debug]matchOptions.noglobstar: 'false'
2018-05-10T12:23:01.6424255Z ##[debug]matchOptions.dot: 'true'
2018-05-10T12:23:01.6424465Z ##[debug]matchOptions.noext: 'false'
2018-05-10T12:23:01.6424656Z ##[debug]matchOptions.nocase: 'true'
2018-05-10T12:23:01.6424926Z ##[debug]matchOptions.nonull: 'false'
2018-05-10T12:23:01.6425117Z ##[debug]matchOptions.matchBase: 'false'
2018-05-10T12:23:01.6425341Z ##[debug]matchOptions.nocomment: 'false'
2018-05-10T12:23:01.6425560Z ##[debug]matchOptions.nonegate: 'false'
2018-05-10T12:23:01.6426031Z ##[debug]matchOptions.flipNegate: 'false'
2018-05-10T12:23:01.6426245Z ##[debug]pattern: 'D:\xxxxxx\_work\r9\a\TestResults\*.trx'
2018-05-10T12:23:01.6429936Z ##[debug]findPath: 'D:\xxxxxx\_work\r9\a\TestResults'
2018-05-10T12:23:01.6430262Z ##[debug]statOnly: 'false'
2018-05-10T12:23:01.6430490Z ##[debug]findPath: 'D:\xxxxxx\_work\r9\a\TestResults'
2018-05-10T12:23:01.6430705Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2018-05-10T12:23:01.6430933Z ##[debug]findOptions.followSymbolicLinks: 'true'
2018-05-10T12:23:01.6432932Z ##[debug]  D:\xxxxxx\_work\r9\a\TestResults (directory)
2018-05-10T12:23:01.6441870Z ##[debug]  D:\xxxxxx\_work\r9\a\TestResults\xxxxxx_2018-05-10_13_23_01.trx (file)
2018-05-10T12:23:01.6442187Z ##[debug]2 results
2018-05-10T12:23:01.6442360Z ##[debug]found 2 paths
2018-05-10T12:23:01.6442541Z ##[debug]applying include pattern
2018-05-10T12:23:01.6473107Z ##[debug]1 matches
2018-05-10T12:23:01.6473601Z ##[debug]1 final results
2018-05-10T12:23:02.4296450Z ##[error]Unable to process command '##vso[results.publish type=VSTest;mergeResults=false;publishRunAttachments=true;resultFiles=D:\xxxxxx\_work\r9\a\TestResults\xxxxxx_2018-05-10_13_23_01.trx;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2018-05-10T12:23:02.4308999Z ##[error]Forbidden
2018-05-10T12:23:02.4697951Z ##[debug]Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Forbidden
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.<CreateDataProviderAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.<ResolveLocationDataAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.<GetLocationDataAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.<GetClientInstanceAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.<GetClientServiceImplAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.<GetClientAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestResultsServer.InitializeServer(VssConnection connection)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestRunPublisher.InitializePublisher(IExecutionContext executionContext, VssConnection connection, String projectName, IResultReader resultReader)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.ResultsCommandExtension.ProcessPublishTestResultsCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
2018-05-10T12:23:02.4702961Z ##[debug]Processed: ##vso[results.publish type=VSTest;mergeResults=false;publishRunAttachments=true;resultFiles=D:\xxxxxx\_work\r9\a\TestResults\xxxxxx_2018-05-10_13_23_01.trx;]
2018-05-10T12:23:02.4703757Z ##[debug]File exists. Size: 40799 Bytes
2018-05-10T12:23:02.4733223Z ##[debug]Processed: ##vso[task.uploadfile]D:\xxxxxx\_work\_temp\db91c010-544c-11e8-8ffb-cde02d0d092a.txt
2018-05-10T12:23:02.4733563Z ##[debug]Agent.Version=2.133.3

**Comment by WaelHamze** [comment]
any thoughts or suggestions?

**Comment by GitHubSriramB** [comment]
@WaelHamze - the failure is happening most probably because "Project Collection Build Service (<account name>)" identity is not having sufficient permissions to publish test results.

@nigurr - could you confirm if this is the case? Also, could you mention the permission that is required?

**Comment by GitHubSriramB** [comment]
Given that the publishing of test results works within Build, it might not be a permission issue. 

I notice that the failure is happening when initializing connection to Test server:
Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Forbidden
at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
…
Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]() at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestResultsServer.InitializeServer(VssConnection connection) at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestRunPublisher.InitializePublisher(IExecutionContext executionContext, VssConnection connection, String projectName, IResultReader resultReader) at
…

@WaelHamze - is this failure happening consistently?

**Comment by WaelHamze** [comment]
@GitHubSriramB Yes this is happening consistently. Please provide email address so can share further details with you.

**Comment by GitHubSriramB** [comment]
Pl. send mail with account details to RM Customer Queries <RM_Customer_Queries@microsoft.com>

**Comment by WaelHamze** [comment]
@GitHubSriramB I am getting undeliverable from postmaster@microsoft.com Already tried twice. Please advise

**Comment by GitHubSriramB** [comment]
@WaelHamze - we received your mail. Will investigate further and give you and update.

**Comment by ShreyasRmsft** [comment]
@GitHubSriramB @WaelHamze what is the status here?

Is it a Release side issue or a test side issue? Is there anything actionable from the test team?

**Comment by ShreyasRmsft** [comment]
@GitHubSriramB  @WaelHamze any updates? It's currently lying in our area path. Please let us know if you need anything from us.

**Comment by bhojan** [comment]
@GitHubSriramB  Any updates for this issue ?

**Comment by GitHubSriramB** [comment]
It looks like an issue due to agent proxy configuration blocking access to URLs used in this flow. 

@SadagopanRajaram - could you pl. assign this issue to whoever is investigating this issue?

**Comment by navin22** [comment]
Observed this behavior in release definition, when using the tasks that interact with the TFS and proxy doesn't bypass certain required URLs. Please follow [this document](https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-windows?view=vsts#how-do-i-configure-the-agent-to-bypass-a-web-proxy-and-connect-to-vsts) for the list of URLs to be whitelisted.

**Comment by ajklotz** [comment]
I'm having this problem myself 

`2018-07-19T14:52:04.4227645Z ##[debug]Calling Publish-TestResults
2018-07-19T14:52:04.4540121Z Publishing Test Results...
2018-07-19T14:52:04.5946378Z ##[debug]Get - SecretService and EndpointService from TaskContext
2018-07-19T14:52:04.5946378Z ##[debug]Fetched Endpoint:SystemVssConnection
2018-07-19T14:52:04.5946378Z ##[debug]AuthorizationType : OAuth
2018-07-19T14:52:05.0210100Z ##[debug]Processed: ##vso[task.logissue type=error;TaskName=VSTest;code=Publish failed: The remote server returned an error: (403) Forbidden.]
2018-07-19T14:52:05.0210100Z ##[warning]Failed to publish test results: The remote server returned an error: (403) Forbidden.
2018-07-19T14:52:05.0210100Z ##[debug]Processed: ##vso[task.logissue type=warning]Failed to publish test results: The remote server returned an error: (403) Forbidden.
2018-07-19T14:52:05.0210100Z ##[debug]Leaving script PublishTestResults.ps1
2018-07-19T14:52:05.0366389Z ##[section]Finishing: Publish Test Results`

**Comment by jpsingleton** [comment]
If you are having trouble with the publish task not using the configured proxy then you can set a variable to bypass the external executable flow. Simply set `PublishTestResults.OverrideExeFlow` to `true` in your definition variables.

[This is the code that you need to trigger](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PublishTestResultsV2/publishtestresults.ts#L68) in the publish test results task. The [VS Test task doesn't use this external tool](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTestV2/vstest.ts#L647) so I have no idea why it's in there.

**Comment by SadagopanRajaram** [comment]
https://github.com/MicrosoftDocs/vsts-docs/issues/3992 has the required urls to whitelist for publish test results task to work. 
Please add "https://{organization_name}.vstmr.visualstudio.com"
