### ISSUE TITLE
Problems with quotes setting build.updatebuildnumber

### ISSUE THREAD

**Issue by RobertOwenJack** [Microsoft/azure-pipelines-tasks#7208]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS
       Account     https://horibatestautomation.visualstudio.com
       Project       StarsEnterpriseMobile-Production
       Build Definition  StarsEnterpriseMobile-M2-Production-Android-Build-Test
       Build Number    Build 1.0.4-545
- Agent - Hosted
      Hosted mac Preview
      Hosted  VS2017
   
## Issue Description

I am trying to set the buildnumber (build.buildnumber) from a task. I have successfully managed to do this with Powershell using the ##vso[build.updatebuildnumber]  logging construct. I have had to use a bash shell script however because I need to run on a hosted mac preview agent.  I have looked at the documentation which suggests:-
newversion="1.0.4-234"
echo "##vso[build.updatebuildnumber]$newversion"
This actually does update the build number but the task is reported to fail with the following message:-

2018-05-15T14:54:56.8235110Z ##[error]TF209010: The build number format $newbuildnumber" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
2018-05-15T14:54:56.8302680Z ##[debug]Microsoft.TeamFoundation.Build.WebApi.BuildNumberFormatException: TF209010: The build number format $newbuildnumber" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.

I have found that on a VS2017 host I can use:-

echo '##vso[build.updatebuildnumber]'$newversion

and this succeeds and gives no error. However on a macOS host it complains about the '. I believe the problem is the evaluation of the string.
If I used
echo ##vso[build.updatebuildnumber]$newversion

the command "succeeds" (gives no error) but I then have a build number of $newversion.   I have looked around but can't find any help on the error. I've also tried  reporting the problem on VSTS but haven't had much help there.

[logs_546.zip](https://github.com/Microsoft/vsts-tasks/files/2005502/logs_546.zip)

[Include task name(s), screenshots and any other relevant details]

### Error logs

[Insert error from the logs here]

**Comment by bryanmacfarlane** [comment]
have you tried this on mac?

```
echo "##vso[build.updatebuildnumber]$newversion"
```

on linux languages double quotes will apply variables but single quotes are literal.  I think this is an O.S. specific scripting detail

**Comment by RobertOwenJack** [comment]
Hi Brian


Re: echo "##vso[build.updatebuildnumber]$newversion"

yes,  I have tried this on a VSTS Hosted macOS preview, Linux preview and VS2017  system. The task completes I get the error reported with a problem in the build number, although the build number has been sucessfully set.  The error is:-

2018-05-18T07:29:27.5897138Z 1.0.4-606-a4303aeb4cf3182afd4e8bae19ad9a617c95a3de
2018-05-18T07:29:27.5973481Z ##[debug]Update build number for build: 606 to: 1.0.4-606-a4303aeb4cf3182afd4e8bae19ad9a617c95a3de at backend.
2018-05-18T07:29:27.6543716Z ##[debug]Processed: ##vso[build.updatebuildnumber]1.0.4-606-a4303aeb4cf3182afd4e8bae19ad9a617c95a3de
2018-05-18T07:29:27.6565445Z ##[debug]task result: Succeeded
2018-05-18T07:29:27.6597333Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]Code works.
2018-05-18T07:29:27.6686917Z ##[section]Async Command Start: Update Build Number
2018-05-18T07:29:27.7439110Z ##[section]Async Command End: Update Build Number
2018-05-18T07:29:27.8792571Z ##[error]TF209010: The build number format $newbuildnumber" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
2018-05-18T07:29:27.8859939Z ##[debug]Microsoft.TeamFoundation.Build.WebApi.BuildNumberFormatException: TF209010: The build number format $newbuildnumber" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.

If I use
echo  '##vso[build.updatebuildnumber]'$newbuildnumber

This works on a VS2017, macOS and linux hosts, with no error reported at all. I am slightly surprised, because I'm sure this on a macOS host without success, but at least it seems to working now and I so I am not sure if something has changed or whether I slipped up on my test.

Whilst this is a work around, it is a bit strange, particularly the documentation for bash shell scripts https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/_shared/set-variables-in-scripts?view=vsts&tabs=shellhttps://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/_shared/set-variables-in-scripts?view=vsts&tabs=shell  indicates that the original form of the command (ie double quotes around the whole command) should be used.

If you use  literals instead of double quotes for a version name there is of course no problem - the problem seems to come with the double quotes.

best regards

Robert


________________________________

**Comment by ericsciple** [comment]
try $(newversion) instead. that will macro replace the value in the task input, before the script is generated. I think the problem is the script contents are echoed before the script is run.

let me know if the workaround fixes the issue. if so it's a bug on the task (should not echo raw script contents when contains `##vso` instruction.

**Comment by bryanmacfarlane** [comment]
Did you try @ericsciple suggestiong of $(newversion) ?

**Comment by RobertOwenJack** [comment]
Hi Bryan

If I use

echo '##vso[build.updatebuildnumber]'$(newbuildnumber)
2018-05-22T07:55:32.3882740Z ##[error]Unable to process command '##vso[build.updatebuildnumber]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2018-05-22T07:55:32.3924870Z ##[error]Build number is required.
2018-05-22T07:55:32.4465930Z ##[debug]System.Exception: Build number is required.
at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildCommandExtension.ProcessBuildUpdateBuildNumberCommand(IExecutionContext context, String data)
at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
2018-05-22T07:55:32.4482650Z ##[debug]Processed: ##vso[build.updatebuildnumber]
2018-05-22T07:55:32.4503150Z ##[debug]task result: Succeeded
2018-05-22T07:55:32.4530740Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]Code works.
2018-05-22T07:55:32.4611660Z ##[section]Async Command Start: Update Build Number
2018-05-22T07:55:32.6036010Z Update build number to '$(newbuildnumber) for build 630

If I use

echo "##vso[build.updatebuildnumber]$(newbuildnumber)"
2018-05-22T07:56:46.6972020Z ##[error]Unable to process command '##vso[build.updatebuildnumber]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2018-05-22T07:56:46.7014770Z ##[error]Build number is required.
2018-05-22T07:56:46.7610790Z ##[debug]System.Exception: Build number is required.
at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildCommandExtension.ProcessBuildUpdateBuildNumberCommand(IExecutionContext context, String data)
at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
2018-05-22T07:56:46.7629660Z ##[debug]Processed: ##vso[build.updatebuildnumber]
2018-05-22T07:56:46.7658270Z ##[debug]task result: Succeeded
2018-05-22T07:56:46.7686860Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]Code works.
2018-05-22T07:56:46.7771300Z ##[section]Async Command Start: Update Build Number
2018-05-22T07:56:46.8263050Z ##[section]Async Command End: Update Build Number
2018-05-22T07:56:46.8384640Z ##[error]TF209010: The build number format $(newbuildnumber)" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
2018-05-22T07:56:46.8438410Z ##[debug]Microsoft.TeamFoundation.Build.WebApi.BuildNumberFormatException: TF209010: The build number format $(newbuildnumber)" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.

If I use however
echo '##vso[build.updatebuildnumber]'$newbuildnumber

18-05-22T08:15:30.4966010Z ##[section]Async Command Start: Update Build Number
2018-05-22T08:15:30.5551920Z Update build number to '$newbuildnumber for build 635
2018-05-22T08:15:30.5566180Z ##[section]Async Command End: Update Build Number
2018-05-22T08:15:30.5609090Z ##[section]Async Command Start: Update Build Number
2018-05-22T08:15:30.5630460Z Update build number to 1.0.4-635-a4303aeb4cf3182afd4e8bae19ad9a617c95a3de for build 635
2018-05-22T08:15:30.5646940Z ##[section]Async Command End: Update Build Number
2018-05-22T08:15:30.5686410Z ##[section]Finishing: shellexec

This works. It is a work around, but not what I would expect from the documentation. I don't think the issue I am
seeing is a OS related on as it behaves the same on macOS, linux and Windows


________________________________

**Comment by ericsciple** [comment]
I can't repro the original problem. Here is my definition:

```yaml
queue: Hosted macOS Preview
steps:
- bash: |
    newversion="1.0.4-234"
    echo "##vso[build.updatebuildnumber]$newversion"
```

**Comment by RobertOwenJack** [comment]
I have a build definition with a Shell Exec task with the following commands in:-
newversion=”1.0.4-234”
echo “##vso[build.updatebuildnumber]$newversion”

The command completes successfully setting the buildnumber to “1.0.4-234” but I get the following log indicating an error:-

2018-06-04T14:25:05.0032120Z ##[debug]Evaluating condition for step: 'shellexec '
2018-06-04T14:25:05.0061490Z ##[debug]Evaluating: succeeded()
2018-06-04T14:25:05.0088210Z ##[debug]Evaluating succeeded:
2018-06-04T14:25:05.0121760Z ##[debug]=> True
2018-06-04T14:25:05.0148930Z ##[debug]Result: True
2018-06-04T14:25:05.0169510Z ##[section]Starting: shellexec
2018-06-04T14:25:05.0504800Z ==============================================================================
2018-06-04T14:25:05.0518700Z Task         : Shell Exec
2018-06-04T14:25:05.0532490Z Description  : Execute shell commands without creating a shell file
2018-06-04T14:25:05.0545900Z Version      : 0.2.0
2018-06-04T14:25:05.0559270Z Author       : Tsuyoshi Ushio
2018-06-04T14:25:05.0572930Z Help         : Replace with markdown to show in help
2018-06-04T14:25:05.0586500Z ==============================================================================
2018-06-04T14:25:06.4100400Z ##[debug]agent.workFolder=/Users/vsts/agent/2.134.2/work
2018-06-04T14:25:06.4121930Z ##[debug]loading inputs and endpoints
2018-06-04T14:25:06.4142780Z ##[debug]loading INPUT_CODE
2018-06-04T14:25:06.4164710Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-06-04T14:25:06.4185560Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-06-04T14:25:06.4207190Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-06-04T14:25:06.4253090Z ##[debug]loaded 4
2018-06-04T14:25:06.4276260Z ##[debug]check path : /bin/bash
2018-06-04T14:25:06.4298160Z ##[debug]bash=/bin/bash
2018-06-04T14:25:06.4318960Z ##[debug]code=newversion="1.0.4-234"
2018-06-04T14:25:06.4558970Z ##[debug]Update build number for build: 706 to: $newversion" at backend.
2018-06-04T14:25:06.5734670Z ##[debug]Processed: echo  "##vso[build.updatebuildnumber]$newversion"
2018-06-04T14:25:06.5748260Z [command]/bin/bash ./.tempexecution.sh
2018-06-04T14:25:06.5789180Z ##[debug]Update build number for build: 706 to: 1.0.4-234 at backend.
2018-06-04T14:25:06.6164910Z ##[debug]Processed: ##vso[build.updatebuildnumber]1.0.4-234
2018-06-04T14:25:06.6185080Z ##[debug]task result: Succeeded
2018-06-04T14:25:06.6231300Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]Code works.
2018-06-04T14:25:06.6315360Z ##[section]Async Command Start: Update Build Number
2018-06-04T14:25:06.7321690Z ##[section]Async Command End: Update Build Number
2018-06-04T14:25:06.7976150Z ##[error]TF209010: The build number format $newversion" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
2018-06-04T14:25:06.8043490Z ##[debug]Microsoft.TeamFoundation.Build.WebApi.BuildNumberFormatException: TF209010: The build number format $newversion" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildServer.<UpdateBuildNumber>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildCommandExtension.<UpdateBuildNumberAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.AsyncCommandContext.<WaitAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2018-06-04T14:25:06.8081850Z ##[section]Async Command Start: Update Build Number
2018-06-04T14:25:06.8528460Z Update build number to 1.0.4-234 for build 706
2018-06-04T14:25:06.8542140Z ##[section]Async Command End: Update Build Number
2018-06-04T14:25:06.8576750Z ##[section]Finishing: shellexec

**Comment by ericsciple** [comment]
I'm not familiar with the internal details of that task (it is not one of the tasks in this repo). The attempted repro that I pasted, uses the "Shell Script" task (v3, choose inline option). There is a change rolling through the scale units that it will rename it in the tasks catalog as the "Bash" task. It would be good to know whether it repros using that task, or whether you can provide a repro using one of the tasks in this repository.

**Comment by RobertOwenJack** [comment]
I used the Shell Script task that you recommended and it works perfectly.  I used the market place shell script  https://marketplace.visualstudio.com/items?itemName=tsuyoshiushio.shell-exec   as the Shell Script task didn’t offer an inline option at the time and I wasn’t aware that this option existed until you mentioned it.   I’ll inform the author. Many thanks

**Comment by dbabineau-vr** [comment]
for those struggling with this across platforms the only thing that worked for me across Linux / Windows was the following without quotes but with a single leading '\':

```
    - script: echo \##vso[build.updatebuildnumber]${{ parameters.majorVersion }}.${{ parameters.minorVersion }}.r$(patch)
      displayName: 'Update Build Number'
```

anything else either failed the task, failed silently or inserted unwanted quotes in the build number in one platform or another, we shouldn't have to resort to platform conditionals for such a simple function

**Comment by prodigy1** [comment]
I stumbled upon this issue as I had a similar one while using PowerShell. It turned out that the `Set-PSDebug -Trace 2` for debugging my script produced the issue. It seems that the underlying pipeline seems to react to the debugging output as well and therefore produce the error output including the variable name.

Probably a similar issue with bash scripts when you enable debugging (set -x) or similar?
