### ISSUE TITLE
SSH: Unhandled: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by liri2006** [microsoft/azure-pipelines-tasks#7518]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS

- Agent - Hosted

- If using Hosted agent, provide agent queue name:
Hosted VS2017

## Issue Description
Task - SSH

I'm using SSH task to run command "git pull https://username:password@repo-url master" on the remote server and getting error Unhandled: Cannot read property 'on' of undefined. 
Basic commands like cd or ls work just fine.

### Error logs
2018-06-19T21:14:30.4331242Z ##[error]Unhandled: Cannot read property 'on' of undefined
2018-06-19T21:14:30.4384130Z ##[error]Command failed with errors on remote machine. Error: No response from server
2018-06-19T21:14:30.4384707Z     at Socket.<anonymous> (D:\a\_tasks\SSH_91443475-df55-4874-944b-39253b558790\0.135.0\node_modules\ssh2\lib\client.js:308:15)
2018-06-19T21:14:30.4384988Z     at emitOne (events.js:101:20)
2018-06-19T21:14:30.4385195Z     at Socket.emit (events.js:188:7)
2018-06-19T21:14:30.4385406Z     at TCP._handle.close [as _onclose] (net.js:497:12)
2018-06-19T21:14:30.4386116Z     at Socket.<anonymous> (D:\a\_tasks\SSH_91443475-df55-4874-944b-39253b558790\0.135.0\node_modules\ssh2\lib\client.js:308:15)
2018-06-19T21:14:30.4386829Z     at emitOne (events.js:101:20)
2018-06-19T21:14:30.4387208Z     at Socket.emit (events.js:188:7)
2018-06-19T21:14:30.4387496Z     at TCP._handle.close [as _onclose] (net.js:497:12)

[Insert error from the logs here]

**Comment by leantk** [comment]
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days

**Comment by Rwing** [comment]
Hi @liri2006,

I got same problem now. Is there any solution to solve it?
