### ISSUE TITLE
Build agent fails on Get sources tasks on Hosted VS2017 and Hosted build agents

### ISSUE THREAD

**Issue by nbuchert** [Microsoft/azure-pipelines-tasks#7990]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS
- Account: nticloud.visualstudio.com
- Team project: MDOCFM
- Build definition: MDOCFM-CI/#43

- Agent - Hosted
- Agent queue name: Hosted VS2017 (and Hosted on previous runs)

## Issue Description
I executed a build monday August 6th, which ran without any problems. Today I am unable to use either the Hosted or Hosted VS2017 build agents.

After switching to the Hosted Ubuntu 1604 build agent, the build completed successfully.

When looking at the below error, I see the following: "Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: c. Path 'repositories[0].properties.versionInfo.author', line 1, position 2659.". Could it be, that you have made some changes to the build agent, so it is unable to handle special characters like "ü", which is part of my surname?
I have never seen any error like this before, when building, and it also worked earlier this week, so I would conclude that this is because of some error on the Hosted build agents.

Best regards

Nicolas Büchert

### Update

The Ubunto 1604 Hosted build started failing later the same day, so I changed my surname when pushing changes to VSTS to not have any special characters, i.e. I changed the letter 'ü' to 'u'. This solved the issue, so I guess there might be an encoding change in your codes or something like that.
I am using SourceTree 2.7.6 on a Mac, if this info is useful to you.

Best regards

Nicolas Büchert

### Error logs

[Insert error from the logs here]
2018-08-09T13:00:32.0099051Z ##[section]Starting: Job
2018-08-09T13:00:32.0188839Z ##[debug]Cleaning agent temp folder: D:\a\_temp
2018-08-09T13:00:32.3962065Z ##[debug]Skipping overwrite %TEMP% environment variable
2018-08-09T13:00:33.1261812Z ##[section]Starting: Initialize job
2018-08-09T13:00:33.1262104Z Current agent version: '2.138.4'
2018-08-09T13:00:33.2290164Z ##[debug]Primary repository: MDOCFM. repository type: Git
2018-08-09T13:00:33.2754416Z Prepare build directory.
2018-08-09T13:00:33.3631363Z ##[debug]Creating build directory: 'D:\a\1'
2018-08-09T13:00:33.3634601Z ##[debug]Delete existing artifacts directory: 'D:\a\1\a'
2018-08-09T13:00:33.3641018Z ##[debug]Creating artifacts directory: 'D:\a\1\a'
2018-08-09T13:00:33.3643706Z ##[debug]Delete existing test results directory: 'D:\a\1\TestResults'
2018-08-09T13:00:33.3644834Z ##[debug]Creating test results directory: 'D:\a\1\TestResults'
2018-08-09T13:00:33.3647375Z ##[debug]Creating binaries directory: 'D:\a\1\b'
2018-08-09T13:00:33.3654222Z ##[debug]Creating source directory: 'D:\a\1\s'
2018-08-09T13:00:33.3655888Z Set build variables.
2018-08-09T13:00:33.3699904Z Download all required tasks.
2018-08-09T13:00:33.4071800Z Downloading task: ArchiveFiles
2018-08-09T13:00:33.7791972Z ##[debug]Task 'ArchiveFiles' has been downloaded into 'D:\a\_tasks\ArchiveFiles_d8b84976-e99a-4b86-b885-4849694435b0\2.127.0'.
2018-08-09T13:00:34.2618749Z Downloading task: CopyFiles
2018-08-09T13:00:34.4032431Z ##[debug]Task 'CopyFiles' has been downloaded into 'D:\a\_tasks\CopyFiles_5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c\2.117.0'.
2018-08-09T13:00:35.0953555Z Downloading task: PublishBuildArtifacts
2018-08-09T13:00:35.2771710Z ##[debug]Task 'PublishBuildArtifacts' has been downloaded into 'D:\a\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.135.0'.
2018-08-09T13:00:35.3013506Z ##[debug]Task 'Archive AppFrameFM WebApp' has following condition: 'succeeded()'.
2018-08-09T13:00:35.3068940Z ##[debug]Parsing expression: <succeeded()>
2018-08-09T13:00:35.3150266Z ##[debug]succeeded
2018-08-09T13:00:35.3165791Z ##[debug](
2018-08-09T13:00:35.3168834Z ##[debug])
2018-08-09T13:00:35.3187765Z ##[debug]Task 'Copy ARM Template files' has following condition: 'succeeded()'.
2018-08-09T13:00:35.3188654Z ##[debug]Parsing expression: <succeeded()>
2018-08-09T13:00:35.3188804Z ##[debug]succeeded
2018-08-09T13:00:35.3188917Z ##[debug](
2018-08-09T13:00:35.3189164Z ##[debug])
2018-08-09T13:00:35.3189337Z ##[debug]Task 'Copy Database bacpac file' has following condition: 'succeeded()'.
2018-08-09T13:00:35.3189655Z ##[debug]Parsing expression: <succeeded()>
2018-08-09T13:00:35.3189777Z ##[debug]succeeded
2018-08-09T13:00:35.3189883Z ##[debug](
2018-08-09T13:00:35.3189982Z ##[debug])
2018-08-09T13:00:35.3190096Z ##[debug]Task 'Copy Database Migration files' has following condition: 'succeeded()'.
2018-08-09T13:00:35.3190371Z ##[debug]Parsing expression: <succeeded()>
2018-08-09T13:00:35.3190662Z ##[debug]succeeded
2018-08-09T13:00:35.3191004Z ##[debug](
2018-08-09T13:00:35.3191343Z ##[debug])
2018-08-09T13:00:35.3191449Z ##[debug]Task 'Publish Artifact: drop' has following condition: 'succeeded()'.
2018-08-09T13:00:35.3191726Z ##[debug]Parsing expression: <succeeded()>
2018-08-09T13:00:35.3191847Z ##[debug]succeeded
2018-08-09T13:00:35.3192125Z ##[debug](
2018-08-09T13:00:35.3192224Z ##[debug])
2018-08-09T13:00:35.3500042Z ##[section]Finishing: Initialize job
2018-08-09T13:00:35.4391233Z ##[debug]Evaluating condition for step: 'Get sources'
2018-08-09T13:00:35.4496354Z ##[debug]Evaluating: SucceededNode()
2018-08-09T13:00:35.4507992Z ##[debug]Evaluating SucceededNode:
2018-08-09T13:00:35.4559041Z ##[debug]=> True
2018-08-09T13:00:35.4596198Z ##[debug]Result: True
2018-08-09T13:00:35.4671499Z ##[section]Starting: Get sources
2018-08-09T13:00:35.4944930Z ==============================================================================
2018-08-09T13:00:35.4945069Z Task         : Get sources
2018-08-09T13:00:35.4945166Z Description  : 
2018-08-09T13:00:35.4946778Z Version      : 1.0.0
2018-08-09T13:00:35.4946879Z Author       : Microsoft
2018-08-09T13:00:35.4946954Z Help         : 
2018-08-09T13:00:35.4947037Z ==============================================================================
2018-08-09T13:00:39.8218524Z Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: c. Path 'repositories[0].properties.versionInfo.author', line 1, position 2659.
2018-08-09T13:00:39.8218811Z    at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
2018-08-09T13:00:39.8218928Z    at Newtonsoft.Json.JsonTextReader.Read()
2018-08-09T13:00:39.8219051Z    at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
2018-08-09T13:00:39.8219180Z    at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
2018-08-09T13:00:39.8219321Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
2018-08-09T13:00:39.8219490Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
2018-08-09T13:00:39.8219688Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2018-08-09T13:00:39.8219875Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2018-08-09T13:00:39.8219998Z    at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
2018-08-09T13:00:39.8220154Z    at Microsoft.TeamFoundation.DistributedTask.Pipelines.ResourcePropertiesJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2018-08-09T13:00:39.8220326Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2018-08-09T13:00:39.8220983Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2018-08-09T13:00:39.8221345Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2018-08-09T13:00:39.8221521Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2018-08-09T13:00:39.8221709Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
2018-08-09T13:00:39.8221876Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
2018-08-09T13:00:39.8224561Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2018-08-09T13:00:39.8224862Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2018-08-09T13:00:39.8225417Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2018-08-09T13:00:39.8226460Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2018-08-09T13:00:39.8226639Z    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2018-08-09T13:00:39.8226797Z    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2018-08-09T13:00:39.8227119Z    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2018-08-09T13:00:39.8227417Z    at Agent.PluginHost.Program.Main(String[] args)
2018-08-09T13:00:40.2822027Z ##[error]Exit code 1 returned from process: file name 'C:\agents\2.138.4\bin\Agent.PluginHost.exe', arguments 'task "Agent.Plugins.Repository.CheckoutTask, Agent.Plugins"'.
2018-08-09T13:00:40.2856321Z ##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name 'C:\agents\2.138.4\bin\Agent.PluginHost.exe', arguments 'task "Agent.Plugins.Repository.CheckoutTask, Agent.Plugins"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.<ExecuteAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.AgentPluginManager.<RunPluginTaskAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.AgentPluginHandler.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2018-08-09T13:00:40.2862190Z ##[section]Finishing: Get sources
2018-08-09T13:00:40.2879171Z ##[debug]Evaluating condition for step: 'Archive AppFrameFM WebApp'
2018-08-09T13:00:40.2880026Z ##[debug]Evaluating: succeeded()
2018-08-09T13:00:40.2880198Z ##[debug]Evaluating succeeded:
2018-08-09T13:00:40.2880742Z ##[debug]=> False
2018-08-09T13:00:40.2881003Z ##[debug]Result: False
2018-08-09T13:00:40.2890795Z ##[debug]Evaluating condition for step: 'Copy ARM Template files'
2018-08-09T13:00:40.2891247Z ##[debug]Evaluating: succeeded()
2018-08-09T13:00:40.2891411Z ##[debug]Evaluating succeeded:
2018-08-09T13:00:40.2891626Z ##[debug]=> False
2018-08-09T13:00:40.2891865Z ##[debug]Result: False
2018-08-09T13:00:40.2901236Z ##[debug]Evaluating condition for step: 'Copy Database bacpac file'
2018-08-09T13:00:40.2901647Z ##[debug]Evaluating: succeeded()
2018-08-09T13:00:40.2901802Z ##[debug]Evaluating succeeded:
2018-08-09T13:00:40.2902002Z ##[debug]=> False
2018-08-09T13:00:40.2902315Z ##[debug]Result: False
2018-08-09T13:00:40.2913386Z ##[debug]Evaluating condition for step: 'Copy Database Migration files'
2018-08-09T13:00:40.2913974Z ##[debug]Evaluating: succeeded()
2018-08-09T13:00:40.2914146Z ##[debug]Evaluating succeeded:
2018-08-09T13:00:40.2914411Z ##[debug]=> False
2018-08-09T13:00:40.2914678Z ##[debug]Result: False
2018-08-09T13:00:40.2925257Z ##[debug]Evaluating condition for step: 'Publish Artifact: drop'
2018-08-09T13:00:40.2925828Z ##[debug]Evaluating: succeeded()
2018-08-09T13:00:40.2926001Z ##[debug]Evaluating succeeded:
2018-08-09T13:00:40.2926272Z ##[debug]=> False
2018-08-09T13:00:40.2926529Z ##[debug]Result: False
2018-08-09T13:00:40.2937673Z ##[debug]Evaluating condition for step: 'Get sources'
2018-08-09T13:00:40.2938516Z ##[debug]Evaluating: AlwaysNode()
2018-08-09T13:00:40.2938670Z ##[debug]Evaluating AlwaysNode:
2018-08-09T13:00:40.2939675Z ##[debug]=> True
2018-08-09T13:00:40.2939982Z ##[debug]Result: True
2018-08-09T13:00:40.2940534Z ##[section]Starting: Get sources
2018-08-09T13:00:40.2942516Z ==============================================================================
2018-08-09T13:00:40.2942602Z Task         : Get sources
2018-08-09T13:00:40.2942686Z Description  : 
2018-08-09T13:00:40.2942753Z Version      : 1.0.0
2018-08-09T13:00:40.2942819Z Author       : Microsoft
2018-08-09T13:00:40.2942886Z Help         : 
2018-08-09T13:00:40.2943522Z ==============================================================================
2018-08-09T13:00:40.8090990Z Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: c. Path 'repositories[0].properties.versionInfo.author', line 1, position 2659.
2018-08-09T13:00:40.8091277Z    at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
2018-08-09T13:00:40.8091520Z    at Newtonsoft.Json.JsonTextReader.Read()
2018-08-09T13:00:40.8091689Z    at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
2018-08-09T13:00:40.8091938Z    at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
2018-08-09T13:00:40.8092185Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
2018-08-09T13:00:40.8092382Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
2018-08-09T13:00:40.8092637Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2018-08-09T13:00:40.8092905Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2018-08-09T13:00:40.8093079Z    at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
2018-08-09T13:00:40.8093303Z    at Microsoft.TeamFoundation.DistributedTask.Pipelines.ResourcePropertiesJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2018-08-09T13:00:40.8093528Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2018-08-09T13:00:40.8093770Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2018-08-09T13:00:40.8094036Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2018-08-09T13:00:40.8094266Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2018-08-09T13:00:40.8094871Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
2018-08-09T13:00:40.8095077Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
2018-08-09T13:00:40.8151448Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2018-08-09T13:00:40.8151829Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2018-08-09T13:00:40.8152082Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2018-08-09T13:00:40.8152313Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2018-08-09T13:00:40.8152479Z    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2018-08-09T13:00:40.8152631Z    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2018-08-09T13:00:40.8152797Z    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2018-08-09T13:00:40.8153024Z    at Agent.PluginHost.Program.Main(String[] args)
2018-08-09T13:00:40.8342813Z ##[error]Exit code 1 returned from process: file name 'C:\agents\2.138.4\bin\Agent.PluginHost.exe', arguments 'task "Agent.Plugins.Repository.CleanupTask, Agent.Plugins"'.
2018-08-09T13:00:40.8511712Z ##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name 'C:\agents\2.138.4\bin\Agent.PluginHost.exe', arguments 'task "Agent.Plugins.Repository.CleanupTask, Agent.Plugins"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.<ExecuteAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.AgentPluginManager.<RunPluginTaskAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.AgentPluginHandler.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2018-08-09T13:00:40.8514270Z ##[section]Finishing: Get sources
2018-08-09T13:00:40.8783167Z ##[section]Finishing: Job

**Comment by bryanmacfarlane** [comment]
Is it still reproing?

**Comment by nbuchert** [comment]
Hi Bryan,

I haven’t tested if it is still a problem.
What I did to avoid the problem was to replace the special character in my surname.

I will test later today and see if it fails and let you know.

Best regards

Nicolas Büchert

**Comment by bryanmacfarlane** [comment]
I think we fixed an issue with encoding so good to know ...

**Comment by mpseidel** [comment]
We just ran into the same error message during Ceckout on a private agent on-prem. We updated the agent and the problem went away so I guess you can close this one.  Thanks for reporting this! Saved us a bunch of headaches :)

**Comment by ThePickNick** [comment]
We are getting same issue on agent that is build on ubuntu [error]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 127 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:https://test.visualstudio.com/" -jwt:*** -noprompt'.

**Comment by damccorm** [comment]
@ThePickNick is this still an issue for you?
