### ISSUE TITLE
Get sources fails when mapping a single file

### ISSUE THREAD

**Issue by mdschweda** [Microsoft/azure-pipelines-tasks#8041]
## Environment
On-premises 2017 Update 3

- Agent - Hosted or Private: 

Version 2.138.6 under CentOS Linux release 7.5.1804 (Core)

## Issue Description

Mapping a single file in task `Get sources`

![](https://i.imgur.com/XZGnBjm.png)

`java.io.FileNotFoundException: /.../_work/.../NuGet.config/.tf/8/d7301238-892d-4224-b15b-b960f38bcd29.gz (Not a directory)`

### Error logs

```
2018-08-15T11:54:14.2282055Z ##[debug]Evaluating condition for step: 'Get sources'
2018-08-15T11:54:14.2465978Z ##[debug]Evaluating: SucceededNode()
2018-08-15T11:54:14.2507557Z ##[debug]Evaluating SucceededNode:
2018-08-15T11:54:14.2617120Z ##[debug]=> True
2018-08-15T11:54:14.2691009Z ##[debug]Result: True
2018-08-15T11:54:14.2789427Z ##[section]Starten: Get sources
2018-08-15T11:54:14.3230081Z ==============================================================================
2018-08-15T11:54:14.3244592Z Task         : Get sources
2018-08-15T11:54:14.3258905Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2018-08-15T11:54:14.3273642Z Version      : 1.139.0
2018-08-15T11:54:14.3287769Z Author       : Microsoft
2018-08-15T11:54:14.3302028Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2018-08-15T11:54:14.3316542Z ==============================================================================
2018-08-15T11:54:15.1177297Z Prepending PATH environment variable with directory containing 'tf'.
2018-08-15T11:54:15.1250741Z ##[debug]Processed: ##vso[task.prependpath]/home/gs-build@GS-GMBH.local/tfs-agent/externals/tee
2018-08-15T11:54:15.1273581Z ##[debug]PATH: '/home/gs-build@GS-GMBH.local/tfs-agent/externals/tee:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/gs-build@GS-GMBH.local/.dotnet/tools:/home/gs-build@GS-GMBH.local/.local/bin:/home/gs-build@GS-GMBH.local/bin'
2018-08-15T11:54:15.1642995Z Querying workspace information.
2018-08-15T11:54:15.1855589Z ##[debug]tf workspaces -format:xml "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt
2018-08-15T11:54:15.1986564Z ##[debug]Starting process:
2018-08-15T11:54:15.2007971Z ##[debug]  File name: 'tf'
2018-08-15T11:54:15.2042186Z ##[debug]  Arguments: 'workspaces -format:xml "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt'
2018-08-15T11:54:15.2071664Z ##[debug]  Working directory: '/home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s'
2018-08-15T11:54:15.2094494Z ##[debug]  Require exit code zero: 'True'
2018-08-15T11:54:15.2120138Z ##[debug]  Encoding web name:  ; code page: ''
2018-08-15T11:54:15.2148073Z ##[debug]  Force kill process on cancellation: 'False'
2018-08-15T11:54:15.2169447Z ##[debug]  Lines to send through STDIN: '0'
2018-08-15T11:54:15.2194396Z ##[debug]Process started with process id 43745, waiting for process exit.
2018-08-15T11:54:17.7496209Z ##[debug]<?xml version="1.0" encoding="utf-8"?><workspaces>
2018-08-15T11:54:17.7518814Z ##[debug]  <workspace name="ws_1_5" owner="877be13b-bea8-476b-bc31-a0b33de29dbf" owner-display-name="Builddienst für Projektsammlung (TEAM FOUNDATION)" computer="gs-labor.gs-gmbh.local" comment="" server="https://gs-main:8081/tfs/defaultcollection/">
2018-08-15T11:54:17.7541593Z ##[debug]    <working-folder server-item="$/KaeferOnline/Kaboom" local-item="/home/gs-build@GS-GMBH.local/tfs-agent/_work/1/s" type="map" depth="full"/>
2018-08-15T11:54:17.7566400Z ##[debug]    <working-folder server-item="$/KaeferOnline/Kaboom/Drops" type="cloak" depth="full"/>
2018-08-15T11:54:17.7596202Z ##[debug]  </workspace>
2018-08-15T11:54:17.7618333Z ##[debug]  <workspace name="ws_2_5" owner="877be13b-bea8-476b-bc31-a0b33de29dbf" owner-display-name="Builddienst für Projektsammlung (TEAM FOUNDATION)" computer="gs-labor.gs-gmbh.local" comment="" server="https://gs-main:8081/tfs/defaultcollection/">
2018-08-15T11:54:17.7640917Z ##[debug]    <working-folder server-item="$/Gschwind/NuGet.config" local-item="/home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s/NuGet.config" type="map" depth="full"/>
2018-08-15T11:54:17.7662673Z ##[debug]  </workspace>
2018-08-15T11:54:17.7683957Z ##[debug]</workspaces>
2018-08-15T11:54:19.4406456Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:19.4431206Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:19.4819836Z ##[debug]Finished process 43745 with exit code 0, and elapsed time 00:00:04.2813848.
2018-08-15T11:54:19.5208974Z ##[debug]Processed: ##vso[task.setvariable variable=build.repository.tfvc.workspace;issecret=False;]ws_2_5
2018-08-15T11:54:19.5865492Z ##[command]tf workspace -delete ws_2_5%3B877be13b-bea8-476b-bc31-a0b33de29dbf "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt
2018-08-15T11:54:19.5901351Z ##[debug]Starting process:
2018-08-15T11:54:19.5931389Z ##[debug]  File name: 'tf'
2018-08-15T11:54:19.5985391Z ##[debug]  Arguments: 'workspace -delete ws_2_5;877be13b-bea8-476b-bc31-a0b33de29dbf "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt'
2018-08-15T11:54:19.6019443Z ##[debug]  Working directory: '/home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s'
2018-08-15T11:54:19.6052544Z ##[debug]  Require exit code zero: 'True'
2018-08-15T11:54:19.6093177Z ##[debug]  Encoding web name:  ; code page: ''
2018-08-15T11:54:19.6126734Z ##[debug]  Force kill process on cancellation: 'False'
2018-08-15T11:54:19.6160253Z ##[debug]  Lines to send through STDIN: '0'
2018-08-15T11:54:19.6201287Z ##[debug]Process started with process id 43870, waiting for process exit.
2018-08-15T11:54:22.0042631Z Workspace 'ws_2_5' deleted.
2018-08-15T11:54:23.8220020Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:23.8251977Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:23.8315683Z ##[debug]Finished process 43870 with exit code 0, and elapsed time 00:00:04.2436532.
2018-08-15T11:54:23.8368003Z ##[debug]tf workspaces ws_2_5 -computer:* -format:xml "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt
2018-08-15T11:54:23.8416379Z ##[debug]Starting process:
2018-08-15T11:54:23.8463335Z ##[debug]  File name: 'tf'
2018-08-15T11:54:23.8518206Z ##[debug]  Arguments: 'workspaces ws_2_5 -computer:* -format:xml "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt'
2018-08-15T11:54:23.8566809Z ##[debug]  Working directory: '/home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s'
2018-08-15T11:54:23.8611429Z ##[debug]  Require exit code zero: 'True'
2018-08-15T11:54:23.8651987Z ##[debug]  Encoding web name:  ; code page: ''
2018-08-15T11:54:23.8692903Z ##[debug]  Force kill process on cancellation: 'False'
2018-08-15T11:54:23.8733606Z ##[debug]  Lines to send through STDIN: '0'
2018-08-15T11:54:23.8772245Z ##[debug]Process started with process id 43979, waiting for process exit.
2018-08-15T11:54:26.4457947Z ##[debug]No workspace matching ws_2_5;Builddienst für Projektsammlung (TEAM FOUNDATION) on computer * found in Team Foundation Server https://gs-main:8081/tfs/DefaultCollection/.
2018-08-15T11:54:28.1214272Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:28.1237677Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:28.1811215Z ##[debug]Finished process 43979 with exit code 1, and elapsed time 00:00:04.3474250.
2018-08-15T11:54:28.1847583Z ##[debug]Deleting: '/home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s'.
2018-08-15T11:54:28.2351963Z ##[command]tf workspace -new -location:local -permission:Public ws_2_5 "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt
2018-08-15T11:54:28.2376464Z ##[debug]Starting process:
2018-08-15T11:54:28.2400530Z ##[debug]  File name: 'tf'
2018-08-15T11:54:28.2430545Z ##[debug]  Arguments: 'workspace -new -location:local -permission:Public ws_2_5 "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt'
2018-08-15T11:54:28.2455981Z ##[debug]  Working directory: '/home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s'
2018-08-15T11:54:28.2480969Z ##[debug]  Require exit code zero: 'True'
2018-08-15T11:54:28.2505816Z ##[debug]  Encoding web name:  ; code page: ''
2018-08-15T11:54:28.2533305Z ##[debug]  Force kill process on cancellation: 'False'
2018-08-15T11:54:28.2558265Z ##[debug]  Lines to send through STDIN: '0'
2018-08-15T11:54:28.2588548Z ##[debug]Process started with process id 44100, waiting for process exit.
2018-08-15T11:54:30.8493584Z Workspace 'ws_2_5' created.
2018-08-15T11:54:32.4326319Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:32.4352791Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:32.4824764Z ##[debug]Finished process 44100 with exit code 0, and elapsed time 00:00:04.2469631.
2018-08-15T11:54:32.4893444Z ##[command]tf workfold -map -workspace:ws_2_5 $/Gschwind/NuGet.config /home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s/./NuGet.config "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt
2018-08-15T11:54:32.4916627Z ##[debug]Starting process:
2018-08-15T11:54:32.4939531Z ##[debug]  File name: 'tf'
2018-08-15T11:54:32.4967271Z ##[debug]  Arguments: 'workfold -map -workspace:ws_2_5 $/Gschwind/NuGet.config /home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s/./NuGet.config "-collection:https://gs-main:8081/tfs/DefaultCollection/" -jwt:*** -noprompt'
2018-08-15T11:54:32.4994239Z ##[debug]  Working directory: '/home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s'
2018-08-15T11:54:32.5016733Z ##[debug]  Require exit code zero: 'True'
2018-08-15T11:54:32.5038936Z ##[debug]  Encoding web name:  ; code page: ''
2018-08-15T11:54:32.5061295Z ##[debug]  Force kill process on cancellation: 'False'
2018-08-15T11:54:32.5086830Z ##[debug]  Lines to send through STDIN: '0'
2018-08-15T11:54:32.5109326Z ##[debug]Process started with process id 44208, waiting for process exit.
2018-08-15T11:54:36.7161472Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:36.7206797Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:36.7393461Z ##[debug]Finished process 44208 with exit code 0, and elapsed time 00:00:04.2474399.
2018-08-15T11:54:36.7450363Z ##[command]tf get -version:2891 -recursive -overwrite /home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s/./NuGet.config -jwt:*** -noprompt
2018-08-15T11:54:36.7476199Z ##[debug]Starting process:
2018-08-15T11:54:36.7505077Z ##[debug]  File name: 'tf'
2018-08-15T11:54:36.7540156Z ##[debug]  Arguments: 'get -version:2891 -recursive -overwrite /home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s/./NuGet.config -jwt:*** -noprompt'
2018-08-15T11:54:36.7566858Z ##[debug]  Working directory: '/home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s'
2018-08-15T11:54:36.7596595Z ##[debug]  Require exit code zero: 'True'
2018-08-15T11:54:36.7625171Z ##[debug]  Encoding web name:  ; code page: ''
2018-08-15T11:54:36.7650080Z ##[debug]  Force kill process on cancellation: 'False'
2018-08-15T11:54:36.7675353Z ##[debug]  Lines to send through STDIN: '0'
2018-08-15T11:54:36.7700005Z ##[debug]Process started with process id 44316, waiting for process exit.
2018-08-15T11:54:39.2889415Z /home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s:
2018-08-15T11:54:39.2916669Z Getting NuGet.config
2018-08-15T11:54:39.3752254Z An error occurred: java.io.FileNotFoundException: /home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s/NuGet.config/.tf/8/d7301238-892d-4224-b15b-b960f38bcd29.gz (Not a directory)
2018-08-15T11:54:41.0166710Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:41.0212370Z ##[debug]STDOUT/STDERR stream read finished.
2018-08-15T11:54:41.0951872Z ##[debug]Finished process 44316 with exit code 100, and elapsed time 00:00:04.3485985.
2018-08-15T11:54:41.1537928Z ##[error]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 100 returned from process: file name 'tf', arguments 'get -version:2891 -recursive -overwrite /home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s/./NuGet.config -jwt:*** -noprompt'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.Plugins.Repository.TfsVCCliManager.<RunCommandAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.Plugins.Repository.TeeCliManager.<GetAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.Plugins.Repository.TfsVCSourceProvider.<GetSourceAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.Plugins.Repository.CheckoutTask.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.PluginHost.Program.Main(String[] args)
2018-08-15T11:54:41.1639515Z ##[debug]Processed: ##vso[task.logissue type=error;]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 100 returned from process: file name 'tf', arguments 'get -version:2891 -recursive -overwrite /home/gs-build@GS-GMBH.local/tfs-agent/_work/2/s/./NuGet.config -jwt:*** -noprompt'.%0A   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.<ExecuteAsync>d__26.MoveNext()%0A--- End of stack trace from previous location where exception was thrown ---%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0A   at Agent.Plugins.Repository.TfsVCCliManager.<RunCommandAsync>d__32.MoveNext()%0A--- End of stack trace from previous location where exception was thrown ---%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0A   at Agent.Plugins.Repository.TeeCliManager.<GetAsync>d__9.MoveNext()%0A--- End of stack trace from previous location where exception was thrown ---%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0A   at Agent.Plugins.Repository.TfsVCSourceProvider.<GetSourceAsync>d__0.MoveNext()%0A--- End of stack trace from previous location where exception was thrown ---%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0A   at Agent.Plugins.Repository.CheckoutTask.<RunAsync>d__2.MoveNext()%0A--- End of stack trace from previous location where exception was thrown ---%0A   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0A   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)%0A   at Agent.PluginHost.Program.Main(String[%5D args)
2018-08-15T11:54:41.1748365Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2018-08-15T11:54:41.1874075Z ##[section]Abschließen: Get sources

```

Works fine when using another build agent on Windows Server

**Comment by bryanmacfarlane** [comment]
might be an issue with the TEE tf (not the task) ...

**Comment by ArieHein** [comment]
well youre not supposed to map files, only folders to start with.
the .tf is the local workspace folder, the nuget.config file is set to be inside the  .gz file as the history of all commits.

Should probably include some sort of warning in the ui.

Note that its not complaining about the usage of a dot in a folder name , as you can have a folder with that name, its complaining about it being a file and not a folder which is what it was expecting.

**Comment by mdschweda** [comment]
> well youre not supposed to map files, only folders to start with.

Why would that be the case? I can't see any reason to disallow that. As a matter of fact, I can map a single file just fine on a Windows Server agent:

```
2018-09-14T08:12:56.5391178Z ##[section]Starting: Quellen abrufen (Get sources)
2018-09-14T08:12:56.6953798Z Prepending Path environment variable with directory containing 'tf.exe'.
2018-09-14T08:12:56.6953798Z Querying workspace information.
2018-09-14T08:12:57.6173256Z ##[command]tf vc workspace /delete ws_4_3;877be13b-bea8-476b-bc31-a0b33de29dbf /collection:http://gs-main:8080/tfs/DefaultCollection/ /loginType:OAuth /login:.,******** /noprompt
2018-09-14T08:12:58.4923935Z ##[command]tf vc workspace /new /location:local /permission:Public ws_4_3 /collection:http://gs-main:8080/tfs/DefaultCollection/ /loginType:OAuth /login:.,******** /noprompt
2018-09-14T08:12:59.0549369Z ##[command]tf vc workfold /unmap /workspace:ws_4_3 $/ /collection:http://gs-main:8080/tfs/DefaultCollection/ /loginType:OAuth /login:.,******** /noprompt
2018-09-14T08:12:59.6174803Z ##[command]tf vc workfold /map /workspace:ws_4_3 $/Gschwind/NuGet.config d:\agent\_work\4\s\NuGet.config /collection:http://gs-main:8080/tfs/DefaultCollection/ /loginType:OAuth /login:.,******** /noprompt
2018-09-14T08:13:00.1800241Z ##[command]tf vc get /version:2891 /recursive /overwrite d:\agent\_work\4\s /loginType:OAuth /login:.,******** /noprompt
2018-09-14T08:13:00.9613340Z d:\agent\_work\4\s:
2018-09-14T08:13:00.9613340Z Abrufen von NuGet.config
2018-09-14T08:13:01.0707174Z ##[section]Finishing: Quellen abrufen
```

**Comment by ArieHein** [comment]
Remove the ./NuGet.config leave only Nuget.config with nothing infront

**Comment by moswald** [comment]
@mdschweda I'm going to close this as it seems ArieHein has a valid fix. Please reopen if this is not correct.

**Comment by vinaysandela** [comment]
Facing Similar Issue. Attached is the Build Log. 
[1_Build.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2658895/1_Build.txt)

Build's Get Sources couldn't pull the code from the TFVC Repo
