### ISSUE TITLE
'Allow Remote Automation' option is not enabled in Safari on Hosted MacOS agents

### ISSUE THREAD

**Issue by oliwer94** [microsoft/azure-pipelines-tasks#8406]
## Issue Description

When I am trying to use the MacOS VSTS hosted agent to run Safari automated UI tests, I get a message that I should enable the 'Allow Remote Automation' option in Safari.
I have found that this issue came up end of last year and an update was released for the mac agents. #6155 

## Environment

VSTS
Team Project name: seleniumdemoproject
Build definition name: Test
Build number: 20180904.1
Release pipeline name: Selenium app
Release name: Release-16
Stage name: Safari Test
Task: dotnet test
Agent - Mac Hosted agent

### Error logs
```
2018-09-20T12:25:09.4069370Z Error Message:
2018-09-20T12:25:09.4084310Z  System.InvalidOperationException : Could not create a session: You must enable the 'Allow Remote Automation' option in Safari's Develop menu to control Safari via WebDriver. (SessionNotCreated)
2018-09-20T12:25:09.4098420Z Stack Trace:
2018-09-20T12:25:09.4111800Z    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
2018-09-20T12:25:09.4127540Z    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2018-09-20T12:25:09.4150330Z    at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
2018-09-20T12:25:09.4165000Z    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
```

**Comment by williamtsoi1** [comment]
I was the one who raised the original issue #6155 . I don't think this was ever fixed properly even though the issue had been closed. I was still facing the same issue even after the fix was put in, and so I've had to work around it by having a physical Mac sitting in the office.

**Comment by bryanmacfarlane** [comment]
You should probably move this to azure-pipelines-image-generation repo.

**Comment by leantk** [comment]
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days
