### ISSUE TITLE
Test task not completing the task when tests have finished

### ISSUE THREAD

**Issue by ADringer** [Microsoft/azure-pipelines-tasks#8484]
## Environment

- Agent - Hosted VS2017

## Issue Description

We have a test task that runs some selenium tests. This was working fine up until about a week ago but now doesn't complete the task. It appears to not be aware that the tasks have finished and so just waits until the 6 hour timeout. I've looked through the audit of the task and the history of the test project and can't see any changes. Below are the logs for when it was working and what happens now.

### Error logs

Working:

> 2018-09-28T14:30:40.3281431Z Results File: D:\a\r1\a\TestResults\VssAdministrator_factoryvm-az368_2018-09-28_14_16_03.trx
2018-09-28T14:30:40.3303116Z 
2018-09-28T14:30:40.3305567Z Total tests: 66. Passed: 0. Failed: 44. Skipped: 22.
2018-09-28T14:30:40.3317570Z Test Run Failed.
2018-09-28T14:30:40.3318135Z Test execution time: 15.7212 Minutes
2018-09-28T14:30:41.1692171Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2018-09-28T14:30:41.1896669Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
2018-09-28T14:30:41.8482695Z ##[error]VsTest task failed.
2018-09-28T14:30:41.8634567Z ##[section]Async Command Start: Publish test results
2018-09-28T14:30:42.2670887Z Publishing test results to test run '204'
2018-09-28T14:30:42.2671128Z Test results remaining: 65. Test run id: 204
2018-09-28T14:30:55.2916830Z Published Test Run : https://tfsprodscussu5.visualstudio.com/Adc32368b-ad15-4443-8b24-3aa6c87a6196/Donate%20Systems/_TestManagement/Runs#runId=204&_a=runCharts
2018-09-28T14:30:55.2917269Z ##[section]Async Command End: Publish test results
2018-09-28T14:30:55.2919230Z ##[section]Finishing: VsTest - testAssemblies

Current (not working):

> 2018-10-02T20:40:59.5818012Z Results File: D:\a\r1\a\TestResults\VssAdministrator_factoryvm-az368_2018-10-02_19_58_30.trx
2018-10-02T20:40:59.5843253Z 
2018-10-02T20:40:59.5846016Z Total tests: 66. Passed: 0. Failed: 44. Skipped: 22.
2018-10-02T20:40:59.5850253Z Test Run Failed.
2018-10-02T20:40:59.5859640Z Test execution time: 45.0899 Minutes
2018-10-02T20:47:36.8636472Z [1538513256.774][SEVERE]: Timed out receiving message from renderer: 600.000
2018-10-02T20:47:36.8637195Z [1538513256.774][WARNING]: screenshot failed, retrying
2018-10-02T20:57:36.8973930Z [1538513856.775][SEVERE]: Timed out receiving message from renderer: 600.000
2018-10-03T01:55:11.6287338Z ##[debug]Re-evaluate condition on job cancellation for step: 'VsTest - testAssemblies'.
2018-10-03T01:55:11.6287448Z ##[debug]Skip Re-evaluate condition on agent shutdown.
2018-10-03T01:55:11.9524382Z ##[error]The operation was canceled.
2018-10-03T01:55:11.9552158Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.<ExecuteAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.<RunAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2018-10-03T01:55:11.9555711Z ##[section]Finishing: VsTest - testAssemblies

**Comment by kaadhina** [comment]
Is this consistently failing with same error? Can you please attach full debug logs (set variable system.debug = true and share the collected logs zip file)
