### ISSUE TITLE
Error while deploying test agent 

### ISSUE THREAD

**Issue by soodputter** [Microsoft/azure-pipelines-tasks#8545]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - TFS on-premises
    
  Version 15.117.27414.0
  
- Agent - Private: 
    1.   Deploy Agent on 
      OS Name:                   Microsoft Windows 10 Enterprise 2016 LTSB
      OS Version:                10.0.14393 N/A Build 14393

    2. Configured agent to run build 
        OS Name:                   Microsoft Windows 7 Enterprise
        OS Version:                6.1.7601 Service Pack 1 Build 7601

## Issue Description

Error in Visual Studio Test Agent Deployment V2.0

### Error logs

2018-10-10T12:37:25.0012438Z ##[section]Starting: Build
2018-10-10T12:37:25.0012438Z Current agent version: '2.122.1'
2018-10-10T12:37:25.2976400Z ##[section]Starting: Initialize Job
2018-10-10T12:37:25.3132398Z Prepare build directory.
2018-10-10T12:37:25.3756390Z Set build variables.
2018-10-10T12:37:25.3756390Z Download all required tasks.
2018-10-10T12:37:25.4224384Z ##[section]Finishing: Initialize Job
2018-10-10T12:37:25.4536380Z ##[section]Starting: Get Sources
2018-10-10T12:37:25.5160372Z Prepending Path environment variable with directory containing 'tf.exe'.
2018-10-10T12:37:25.5316370Z Setting environment variable TFVC_BUILDAGENT_POLICYPATH
2018-10-10T12:37:25.5316370Z Querying workspace information.
2018-10-10T12:37:28.4331998Z ##[command]tf vc get /version:191272 /recursive /overwrite c:\_work\1\s /loginType:OAuth /login:.,******** /noprompt
2018-10-10T12:37:34.2363254Z All files are up to date.
2018-10-10T12:37:34.2675250Z ##[section]Finishing: Get Sources
2018-10-10T12:37:34.2675250Z ##[section]Starting: Deploy TestAgent on Server
2018-10-10T12:37:34.2831248Z ==============================================================================
2018-10-10T12:37:34.2831248Z Task         : Visual Studio Test Agent Deployment
2018-10-10T12:37:34.2831248Z Description  : Deploy and configure Test Agent to run tests on a set of machines
2018-10-10T12:37:34.2831248Z Version      : 2.1.8
2018-10-10T12:37:34.2831248Z Author       : Microsoft Corporation
2018-10-10T12:37:34.2831248Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=838890)
2018-10-10T12:37:34.2831248Z ==============================================================================
2018-10-10T12:37:35.6715070Z ****************************************************************
2018-10-10T12:37:35.6715070Z                     Task Input Information                      
2018-10-10T12:37:35.6715070Z ----------------------------------------------------------------
2018-10-10T12:37:35.6715070Z testMachineInput         = Server.Domain:6910
2018-10-10T12:37:35.6715070Z adminUserName            = Server\Administrator
2018-10-10T12:37:35.6715070Z winRmProtocal            = Https
2018-10-10T12:37:35.6715070Z testCertificate          = true
2018-10-10T12:37:35.6715070Z machineUserName          = TestAgentUserName
2018-10-10T12:37:35.6715070Z runAsProcess             = true
2018-10-10T12:37:35.6715070Z logonAutomatically       = true
2018-10-10T12:37:35.6715070Z disableScreenSaver       = true
2018-10-10T12:37:35.6715070Z isDataCollectionOnly     = false
2018-10-10T12:37:35.6715070Z testPlatform             = 15.0
2018-10-10T12:37:35.6715070Z agentLocation            = e:\TA\vstf_testagent.exe
2018-10-10T12:37:35.6715070Z updateTestAgent          = true
2018-10-10T12:37:35.6715070Z ****************************************************************
2018-10-10T12:37:35.9991028Z Starting to deploy and configure test agent on test machines.
2018-10-10T12:37:35.9991028Z Inputs provided are:
2018-10-10T12:37:35.9991028Z Use HTTP Port: False
2018-10-10T12:37:35.9991028Z Username: TestAgentUserName
2018-10-10T12:37:35.9991028Z Disable Screen saver: True
2018-10-10T12:37:35.9991028Z Login Automatically: True
2018-10-10T12:37:35.9991028Z Run as process: True
2018-10-10T12:37:35.9991028Z Agent location: e:\TA\vstf_testagent.exe
2018-10-10T12:37:35.9991028Z Update test agent: True
2018-10-10T12:37:35.9991028Z Run test agent as DataCollection only : False
2018-10-10T12:37:36.2175000Z Task 'VerifyTestAgentInstalled' on machine 'Server.Domain:6910' is being run
2018-10-10T12:37:39.0410638Z Task 'VerifyTestAgentInstalled' on machine 'Server.Domain:6910' completed.
2018-10-10T12:37:39.0410638Z ##[warning]Task 'VerifyTestAgentInstalled' for machine Server.Domain:6910's Error : System.AggregateException: 
2018-10-10T12:37:39.0410638Z Cannot create type. Only core types are supported in this language mode.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :CannotCreateTypeConstrainedLanguage
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z You cannot call a method on a null-valued expression.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :InvokeMethodOnNull
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z You cannot call a method on a null-valued expression.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :InvokeMethodOnNull
2018-10-10T12:37:39.0410638Z  ---> System.Management.Automation.RemoteException: Cannot create type. Only core types are supported in this language mode.
2018-10-10T12:37:39.0410638Z    --- End of inner exception stack trace ---
2018-10-10T12:37:39.0410638Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable) in E:\v2.0\A7\_work\2\s\DevTestLabs\Client\Deployment\Deployment\PowershellExecutor.cs:line 178
2018-10-10T12:37:39.0410638Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.AcquireMutexOwnerShip(String serviceName, String destinationPath, Int64 deploymentHeartbeatTimeoutSec) in E:\v2.0\A7\_work\2\s\DevTestLabs\Client\Deployment\Deployment\RemoteDeploymentHelper.cs:line 216
2018-10-10T12:37:39.0410638Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext() in E:\v2.0\A7\_work\2\s\DevTestLabs\Client\Deployment\Deployment\DeploymentClient.cs:line 326
2018-10-10T12:37:39.0410638Z ---> (Inner Exception #0) System.Management.Automation.RemoteException: Cannot create type. Only core types are supported in this language mode.<---
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z ---> (Inner Exception #1) System.Management.Automation.RemoteException: You cannot call a method on a null-valued expression.<---
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z ---> (Inner Exception #2) System.Management.Automation.RemoteException: You cannot call a method on a null-valued expression.<---
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z ##[warning]Task 'VerifyTestAgentInstalled' for machine Server.Domain:6910's Log : System.AggregateException: 
2018-10-10T12:37:39.0410638Z Cannot create type. Only core types are supported in this language mode.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :CannotCreateTypeConstrainedLanguage
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z You cannot call a method on a null-valued expression.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :InvokeMethodOnNull
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z You cannot call a method on a null-valued expression.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :InvokeMethodOnNull
2018-10-10T12:37:39.0410638Z  ---> System.Management.Automation.RemoteException: Cannot create type. Only core types are supported in this language mode.
2018-10-10T12:37:39.0410638Z    --- End of inner exception stack trace ---
2018-10-10T12:37:39.0410638Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable) in E:\v2.0\A7\_work\2\s\DevTestLabs\Client\Deployment\Deployment\PowershellExecutor.cs:line 178
2018-10-10T12:37:39.0410638Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.AcquireMutexOwnerShip(String serviceName, String destinationPath, Int64 deploymentHeartbeatTimeoutSec) in E:\v2.0\A7\_work\2\s\DevTestLabs\Client\Deployment\Deployment\RemoteDeploymentHelper.cs:line 216
2018-10-10T12:37:39.0410638Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext() in E:\v2.0\A7\_work\2\s\DevTestLabs\Client\Deployment\Deployment\DeploymentClient.cs:line 326
2018-10-10T12:37:39.0410638Z ---> (Inner Exception #0) System.Management.Automation.RemoteException: Cannot create type. Only core types are supported in this language mode.<---
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z ---> (Inner Exception #1) System.Management.Automation.RemoteException: You cannot call a method on a null-valued expression.<---
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z ---> (Inner Exception #2) System.Management.Automation.RemoteException: You cannot call a method on a null-valued expression.<---
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z ##[error]Error occured on 'Server.Domain:6910'. Details : '
2018-10-10T12:37:39.0410638Z Cannot create type. Only core types are supported in this language mode.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :CannotCreateTypeConstrainedLanguage
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z You cannot call a method on a null-valued expression.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :InvokeMethodOnNull
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z You cannot call a method on a null-valued expression.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :InvokeMethodOnNull
2018-10-10T12:37:39.0410638Z '. For troubleshooting, refer https://aka.ms/remotevstest.
2018-10-10T12:37:39.0410638Z Cannot create type. Only core types are supported in this language mode.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :CannotCreateTypeConstrainedLanguage
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z You cannot call a method on a null-valued expression.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :InvokeMethodOnNull
2018-10-10T12:37:39.0410638Z 
2018-10-10T12:37:39.0410638Z You cannot call a method on a null-valued expression.
2018-10-10T12:37:39.0410638Z  CategoryInfo :InvalidOperation: (:) [], RuntimeException
2018-10-10T12:37:39.0410638Z  FullyQualifiedErrorId :InvokeMethodOnNull
2018-10-10T12:37:39.0410638Z '. For troubleshooting, refer https://aka.ms/remotevstest.
2018-10-10T12:37:39.0410638Z Downloading test agent from https://testexecution.blob.core.windows.net/testexecution/3840309/TestExecution.zip to $env:SystemDrive\TestAgent\TestExecution.zip location on the test machines
2018-10-10T12:37:39.0566636Z Skipping 'DownloadTestAgent' task on machine 'Server.Domain:6910' due to errors. Check the logs for details and retry.
2018-10-10T12:37:39.0566636Z TaskList is empty
2018-10-10T12:37:39.0566636Z Downloading test agent from https://testexecution.blob.core.windows.net/testexecution/3840309/TestExecution.zip to $env:SystemDrive\TestAgent\TestExecution.zip location on the test machines
2018-10-10T12:37:39.0566636Z Skipping 'DownloadTestAgent' task on machine 'Server.Domain:6910' due to errors. Check the logs for details and retry.
2018-10-10T12:37:39.0566636Z TaskList is empty
2018-10-10T12:37:39.1034630Z ##[section]Finishing: Deploy TestAgent on Server
2018-10-10T12:37:39.1034630Z ##[section]Starting: Post Job Cleanup
2018-10-10T12:37:39.1190628Z ##[section]Finishing: Post Job Cleanup
2018-10-10T12:37:39.1190628Z ##[section]Finishing: Build

**Comment by kaadhina** [comment]
Hi, is this a consistent failure? Is this a setup that used to work and stopped working now?
Can you please see if you can run "powershell on target machines" task on the same machines?
Is winrm remoting enabled on the target machines?
Can you also please share verbose logs (set system.debug variable to true and share the build logs)

**Comment by soodputter** [comment]
Dear Kavipriya, it worked as expected. 

Best regards,
Varun
