### ISSUE TITLE
CondaEnvironment error

### ISSUE THREAD

**Issue by guolinke** [Microsoft/azure-pipelines-tasks#8698]
## Issue Description

CondaEnvironment shows strange error.

### Task logs

https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=721&view=logs

### Error logs

2018-10-25T05:15:34.4762420Z # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
2018-10-25T05:15:34.4762473Z 
2018-10-25T05:15:34.4762608Z     Traceback (most recent call last):
2018-10-25T05:15:34.4763753Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
2018-10-25T05:15:34.4764193Z         return func(*args, **kwargs)
2018-10-25T05:15:34.4764623Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/cli/main.py", line 78, in _main
2018-10-25T05:15:34.4764765Z         exit_code = do_call(args, p)
2018-10-25T05:15:34.4765379Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
2018-10-25T05:15:34.4766210Z         exit_code = getattr(module, func_name)(args, parser)
2018-10-25T05:15:34.4766650Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/cli/main_update.py", line 14, in execute
2018-10-25T05:15:34.4767018Z         install(args, parser, 'update')
2018-10-25T05:15:34.4767381Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/cli/install.py", line 253, in install
2018-10-25T05:15:34.4767544Z         handle_txn(unlink_link_transaction, prefix, args, newenv)
2018-10-25T05:15:34.4767887Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/cli/install.py", line 282, in handle_txn
2018-10-25T05:15:34.4768043Z         unlink_link_transaction.execute()
2018-10-25T05:15:34.4768411Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 223, in execute
2018-10-25T05:15:34.4768536Z         self.verify()
2018-10-25T05:15:34.4768831Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/common/io.py", line 46, in decorated
2018-10-25T05:15:34.4768921Z         return f(*args, **kwds)
2018-10-25T05:15:34.4769258Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 200, in verify
2018-10-25T05:15:34.4769547Z         self.prepare()
2018-10-25T05:15:34.4770435Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 192, in prepare
2018-10-25T05:15:34.4770569Z         stp.remove_specs, stp.update_specs)
2018-10-25T05:15:34.4771107Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 282, in _prepare
2018-10-25T05:15:34.4771351Z         mkdir_p(transaction_context['temp_dir'])
2018-10-25T05:15:34.4771945Z       File "/usr/share/miniconda/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 60, in mkdir_p
2018-10-25T05:15:34.4772078Z         makedirs(path)
2018-10-25T05:15:34.4774191Z       File "/usr/share/miniconda/lib/python3.7/os.py", line 221, in makedirs
2018-10-25T05:15:34.4774711Z         mkdir(name, mode)
2018-10-25T05:15:34.4776147Z     PermissionError: [Errno 13] Permission denied: '/usr/share/miniconda/.condatmp'
2018-10-25T05:15:34.4776374Z 
2018-10-25T05:15:34.4776676Z `$ /usr/bin/conda update --name base conda --yes`
2018-10-25T05:15:34.4776763Z 
2018-10-25T05:15:34.4777230Z   environment variables:
2018-10-25T05:15:34.4777419Z BUILD_REPOSITORY_LOCALPATH=/home/vsts/work/1/s
2018-10-25T05:15:34.4777510Z                  CIO_TEST=<not set>
2018-10-25T05:15:34.4777676Z                     CONDA=/usr/share/miniconda
2018-10-25T05:15:34.4778186Z                 CONDA_ENV=test-env
2018-10-25T05:15:34.4778329Z                CONDA_ROOT=/usr/share/miniconda
2018-10-25T05:15:34.4778405Z                      PATH=/usr/bin:"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2018-10-25T05:15:34.4778520Z                           :/usr/games:/usr/local/games"
2018-10-25T05:15:34.4778582Z            PYTHON_VERSION=3.6
2018-10-25T05:15:34.4778640Z        REQUESTS_CA_BUNDLE=<not set>
2018-10-25T05:15:34.4778750Z             SSL_CERT_FILE=<not set>
2018-10-25T05:15:34.4778790Z 
2018-10-25T05:15:34.4778843Z      active environment : None
2018-10-25T05:15:34.4779072Z        user config file : /home/vsts/.condarc
2018-10-25T05:15:34.4779134Z  populated config files : 
2018-10-25T05:15:34.4779231Z           conda version : 4.5.11
2018-10-25T05:15:34.4779471Z     conda-build version : not installed
2018-10-25T05:15:34.4779538Z          python version : 3.7.0.final.0
2018-10-25T05:15:34.4779649Z        base environment : /usr/share/miniconda  (read only)
2018-10-25T05:15:34.4779910Z            channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
2018-10-25T05:15:34.4780489Z                           https://repo.anaconda.com/pkgs/main/noarch
2018-10-25T05:15:34.4784465Z                           https://repo.anaconda.com/pkgs/free/linux-64
2018-10-25T05:15:34.4784754Z                           https://repo.anaconda.com/pkgs/free/noarch
2018-10-25T05:15:34.4785106Z                           https://repo.anaconda.com/pkgs/r/linux-64
2018-10-25T05:15:34.4785386Z                           https://repo.anaconda.com/pkgs/r/noarch
2018-10-25T05:15:34.4785984Z                           https://repo.anaconda.com/pkgs/pro/linux-64
2018-10-25T05:15:34.4786172Z                           https://repo.anaconda.com/pkgs/pro/noarch
2018-10-25T05:15:34.4786397Z           package cache : /usr/share/miniconda/pkgs
2018-10-25T05:15:34.4786541Z                           /home/vsts/.conda/pkgs
2018-10-25T05:15:34.4786613Z        envs directories : /home/vsts/.conda/envs
2018-10-25T05:15:34.4786738Z                           /usr/share/miniconda/envs
2018-10-25T05:15:34.4787136Z                platform : linux-64
2018-10-25T05:15:34.4787491Z              user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.15.0-1023-azure ubuntu/16.04 glibc/2.23
2018-10-25T05:15:34.4787648Z                 UID:GID : 1001:999
2018-10-25T05:15:34.4788045Z              netrc file : None
2018-10-25T05:15:34.4788123Z            offline mode : False
2018-10-25T05:15:34.4788266Z 
2018-10-25T05:15:34.4788305Z 
2018-10-25T05:15:34.4788366Z An unexpected error has occurred. Conda has prepared the above report.

**Comment by guolinke** [comment]
except for customed docker (first 5 builds), the remaining tasks, including ubuntu1604 and macos, suffer from this error.

**Comment by brcrista** [comment]
This should be fixed with #8667

To be clear, updating conda is best effort, so this error should not have caused the build to fail.
