### ISSUE TITLE
Powershell Execution on target machine issue still exists from Release pipeline of VSTS

### ISSUE THREAD

**Issue by johnqxu1** [Microsoft/azure-pipelines-tasks#8717]
If you still face such king of issue in future please get back to us with debug logs and your script

_Originally posted by @chshrikh in https://github.com/Microsoft/azure-pipelines-tasks/issues/8039#issuecomment-423880903_

I still facing this issue in VSTS release pipeline with Powershell execution on remote server while it executes an powershell script hosted in target server. The error I got is below: 
018-10-26T17:56:30.7624931Z ==============================================================================
2018-10-26T17:56:30.7625227Z Task         : PowerShell on Target Machines
2018-10-26T17:56:30.7625467Z Description  : Execute PowerShell scripts on remote machine(s)
2018-10-26T17:56:30.7625846Z Version      : 2.0.5
2018-10-26T17:56:30.7625976Z Author       : Microsoft Corporation
2018-10-26T17:56:30.7626110Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=627414)
2018-10-26T17:56:30.7626307Z ==============================================================================
2018-10-26T17:56:32.1537594Z ##[debug]VstsTaskSdk 0.8.2 commit 
2018-10-26T17:56:32.4006330Z ##[debug]Entering E:\BuildWorkFolders\Agent1\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\2.0.5\PowerShellOnTargetMachines.ps1.
2018-10-26T17:56:32.4427758Z ##[debug]INPUT_ENVIRONMENTNAME: 'MachineName'
2018-10-26T17:56:32.4461735Z ##[debug]INPUT_ADMINUSERNAME: XXXXXXXXX
2018-10-26T17:56:32.4496513Z ##[debug]INPUT_ADMINPASSWORD: 'xxxxxxxxxxxx
2018-10-26T17:56:32.4536109Z ##[debug]INPUT_PROTOCOL: 'Http'
2018-10-26T17:56:32.4569147Z ##[debug]INPUT_TESTCERTIFICATE: 'true'
2018-10-26T17:56:32.4622543Z ##[debug]INPUT_MACHINENAMES (empty)
2018-10-26T17:56:32.4770295Z ##[debug]INPUT_SCRIPTPATH: '\\MachineName\D$\temp\Scripts\BackUpWS_ByVersion.ps1'
2018-10-26T17:56:32.4812703Z ##[debug]INPUT_SCRIPTARGUMENTS (empty)
2018-10-26T17:56:32.4852688Z ##[debug]INPUT_INITIALIZATIONSCRIPTPATH (empty)
2018-10-26T17:56:32.4888696Z ##[debug]INPUT_RUNPOWERSHELLINPARALLEL: 'true'
2018-10-26T17:56:32.4929682Z ##[debug]INPUT_SESSIONVARIABLES: '$appname = InventoryManagement, $SourcePath = D:\Inetpub\websrvhub\InventoryManagement,$DLLs = D:\Inetpub\websrvhub\InventoryManagement\bin\InventoryManagement.dll'
2018-10-26T17:56:32.4969486Z ##[debug]Loading resource strings from: E:\BuildWorkFolders\Agent1\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\2.0.5/Task.json
2018-10-26T17:56:32.5356379Z ##[debug]Loaded 7 strings.
2018-10-26T17:56:32.5410449Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-10-26T17:56:32.5443483Z ##[debug]Loading resource strings from: E:\BuildWorkFolders\Agent1\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\2.0.5\Strings\resources.resjson\en-US\resources.resjson
2018-10-26T17:56:32.5808090Z ##[debug]Loaded 7 strings.
2018-10-26T17:56:32.6096124Z ##[debug]Loading module from path 'E:\BuildWorkFolders\Agent1\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\2.0.5\DeploymentUtilities\Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Internal.psm1'.
2018-10-26T17:56:32.6343106Z ##[debug]Exporting function 'Write-Telemetry'.
2018-10-26T17:56:32.6370852Z ##[debug]Exporting function 'Get-ResourceCredentials'.
2018-10-26T17:56:32.6397293Z ##[debug]Exporting function 'Get-ResourceOperationLogs'.
2018-10-26T17:56:32.6435085Z ##[debug]Exporting function 'Write-ResponseLogs'.
2018-10-26T17:56:32.6468612Z ##[debug]Exporting function 'Import-DevtestLabsCommomDll'.
2018-10-26T17:56:32.6496924Z ##[debug]Exporting function 'Get-ResourceHttpTagKey'.
2018-10-26T17:56:32.6525020Z ##[debug]Exporting function 'Get-ResourceHttpsTagKey'.
2018-10-26T17:56:32.6549894Z ##[debug]Exporting function 'Get-ResourceFQDNTagKey'.
2018-10-26T17:56:32.6575683Z ##[debug]Exporting function 'Get-SkipCACheckTagKey'.
2018-10-26T17:56:32.6601112Z ##[debug]Exporting function 'Get-OperationLogs'.
2018-10-26T17:56:32.6643378Z ##[debug]Exporting function 'Get-SqlPackageCommandArguments'.
2018-10-26T17:56:32.6681977Z ##[debug]Importing function 'Get-OperationLogs'.
2018-10-26T17:56:32.6711328Z ##[debug]Importing function 'Get-ResourceCredentials'.
2018-10-26T17:56:32.7788384Z ##[debug]Importing function 'Get-ResourceFQDNTagKey'.
2018-10-26T17:56:32.7829279Z ##[debug]Importing function 'Get-ResourceHttpsTagKey'.
2018-10-26T17:56:32.7860053Z ##[debug]Importing function 'Get-ResourceHttpTagKey'.
2018-10-26T17:56:32.7888834Z ##[debug]Importing function 'Get-ResourceOperationLogs'.
2018-10-26T17:56:32.7917139Z ##[debug]Importing function 'Get-SkipCACheckTagKey'.
2018-10-26T17:56:32.7963248Z ##[debug]Importing function 'Get-SqlPackageCommandArguments'.
2018-10-26T17:56:32.7998090Z ##[debug]Importing function 'Import-DevtestLabsCommomDll'.
2018-10-26T17:56:32.8043128Z ##[debug]Importing function 'Write-ResponseLogs'.
2018-10-26T17:56:32.8071473Z ##[debug]Importing function 'Write-Telemetry'.
2018-10-26T17:56:32.8114923Z ##[debug]Loading module from path 'E:\BuildWorkFolders\Agent1\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\2.0.5\DeploymentUtilities\Microsoft.TeamFoundation.DistributedTask.Task.Deployment.dll'.
2018-10-26T17:56:32.8429518Z ##[debug]Importing cmdlet 'Copy-FilesToAzureBlob'.
2018-10-26T17:56:32.8470551Z ##[debug]Importing cmdlet 'Copy-FilesToTargetMachine'.
2018-10-26T17:56:32.8500581Z ##[debug]Importing cmdlet 'Copy-ToAzureMachines'.
2018-10-26T17:56:32.8535183Z ##[debug]Importing cmdlet 'Get-EnvironmentProperty'.
2018-10-26T17:56:32.8564409Z ##[debug]Importing cmdlet 'Get-EnvironmentResources'.
2018-10-26T17:56:32.8592820Z ##[debug]Importing cmdlet 'Get-ParsedSessionVariables'.
2018-10-26T17:56:32.8621171Z ##[debug]Importing cmdlet 'Invoke-PsOnRemote'.
2018-10-26T17:56:32.8647321Z ##[debug]Importing cmdlet 'Register-Environment'.
2018-10-26T17:56:32.8690087Z ##[debug]Loading module from path 'E:\BuildWorkFolders\Agent1\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\2.0.5\ps_modules\TelemetryHelper\TelemetryHelper.psm1'.
2018-10-26T17:56:32.8902739Z ##[debug]Exporting function 'Write-Telemetry'.
2018-10-26T17:56:32.8933682Z ##[debug]Exporting function 'Get-ExceptionData'.
2018-10-26T17:56:32.8983687Z ##[debug]Exporting variable 'telemetryCodes'.
2018-10-26T17:56:32.9013823Z ##[debug]Importing function 'Get-ExceptionData'.
2018-10-26T17:56:32.9048988Z ##[debug]Importing function 'Write-Telemetry'.
2018-10-26T17:56:32.9085531Z ##[debug]Importing variable 'telemetryCodes'.
2018-10-26T17:56:32.9608040Z ##[debug]Starting Register-Environment cmdlet call for environment : MachineName with filter 
2018-10-26T17:56:32.9970300Z ##[debug]Begin Create-Environment cmdlet
2018-10-26T17:56:32.9970961Z ##[debug]UserName=XXXXXXXXXX
2018-10-26T17:56:32.9971261Z ##[debug]WinRmProtocol=HTTP
2018-10-26T17:56:32.9971532Z ##[debug]TestCertificate=True
2018-10-26T17:56:33.6833849Z ##[debug]Unable to create a environment object for given json - Unexpected character encountered while parsing value: P. Path '', line 0, position 0.
2018-10-26T17:56:33.6844065Z ##[debug]Instantiating new Environment with the provided EnvironmentSpecification
2018-10-26T17:56:33.6847519Z ##[debug]Using performedById=e96922bc-af77-440c-a330-2587fae57738
2018-10-26T17:56:33.6848878Z ##[debug]projectName=RISE_OMS
2018-10-26T17:56:33.6885629Z ##[debug]Setting TestCertificate to false as the WinRmProtocol is HTTP
2018-10-26T17:56:33.6909169Z ##[debug]Parsing EnvironmentSpecification MachineName
2018-10-26T17:56:33.6939529Z ##[debug]Updated HTTP port of resource MachineName to 5985
2018-10-26T17:56:33.7072982Z ##[debug]Added machine to environment MachineName
2018-10-26T17:56:33.7076570Z ##[debug]Finished instantiating new Environment with the provided EnvironmentSpecification
2018-10-26T17:56:33.7104212Z ##[debug]End Create-Environment cmdlet
2018-10-26T17:56:33.7152232Z ##[debug]Completed Register-Environment cmdlet call for environment : MachineName
2018-10-26T17:56:33.7179883Z ##[debug]Starting Get-EnvironmentResources cmdlet call on environment name: MachineName
2018-10-26T17:56:33.9462516Z ##[debug]Get-EnvironmentResources cmdlet started
2018-10-26T17:56:33.9463359Z ##[debug]Process Environment by object
2018-10-26T17:56:33.9479387Z ##[debug]Get-EnvironmentResources cmdlet ended
2018-10-26T17:56:33.9930558Z ##[debug]Starting Get-EnvironmentProperty cmdlet call on environment name: MachineName with key: Microsoft-Vslabs-MG-SkipCACheck
2018-10-26T17:56:33.9957917Z ##[debug]Get-EnvironmentResources cmdlet
2018-10-26T17:56:33.9958354Z ##[debug]Environment.Name=
2018-10-26T17:56:33.9994587Z ##[debug]Completed Get-EnvironmentProperty cmdlet call on environment name: MachineName with key: Microsoft-Vslabs-MG-SkipCACheck
2018-10-26T17:56:34.0116528Z ##[debug]Get Resource properties for MachineName (ResourceId = 1)
2018-10-26T17:56:34.0182002Z ##[debug]Starting Get-EnvironmentProperty cmdlet call on environment name: MachineName with resource id: 1(Name : MachineName) and key: Microsoft-Vslabs-MG-Resource-FQDN
2018-10-26T17:56:34.0193549Z ##[debug]Get-EnvironmentResources cmdlet
2018-10-26T17:56:34.0194250Z ##[debug]Environment.Name=MachineName
2018-10-26T17:56:34.0232845Z ##[debug]Completed Get-EnvironmentProperty cmdlet call on environment name: MachineName with resource id: 1(Name :MachineName) and key: Microsoft-Vslabs-MG-Resource-FQDN
2018-10-26T17:56:34.0553765Z ##[debug]Starting Get-EnvironmentProperty cmdlet call on environment name: MachineName with resource id: 1(Name : MachineName) and key: WinRM_Http
2018-10-26T17:56:34.0565603Z ##[debug]Get-EnvironmentResources cmdlet
2018-10-26T17:56:34.0566265Z ##[debug]Environment.Name=MachineName
2018-10-26T17:56:34.0628549Z ##[debug]Completed Get-EnvironmentProperty cmdlet call on environment name: MachineName with resource id: 1(Name : MachineName) and key: WinRM_Http
2018-10-26T17:56:34.0917746Z ##[debug]		 Resource Username - XXXXXXXX
2018-10-26T17:56:34.1357373Z Deployment started for machine: MachineName:5985'
2018-10-26T17:56:34.1585195Z ##[debug]Importing cmdlet 'Copy-FilesToAzureBlob'.
2018-10-26T17:56:34.1625184Z ##[debug]Importing cmdlet 'Copy-FilesToTargetMachine'.
2018-10-26T17:56:34.1657648Z ##[debug]Importing cmdlet 'Copy-ToAzureMachines'.
2018-10-26T17:56:34.1682881Z ##[debug]Importing cmdlet 'Get-EnvironmentProperty'.
2018-10-26T17:56:34.1926979Z ##[debug]Importing cmdlet 'Get-EnvironmentResources'.
2018-10-26T17:56:34.1949794Z ##[debug]Importing cmdlet 'Get-ParsedSessionVariables'.
2018-10-26T17:56:34.1988071Z ##[debug]Importing cmdlet 'Invoke-PsOnRemote'.
2018-10-26T17:56:34.2012354Z ##[debug]Importing cmdlet 'Register-Environment'.
2018-10-26T17:56:34.2040099Z ##[debug]fqdn = MachineName
2018-10-26T17:56:34.2064572Z ##[debug]scriptPath = \\MachineName\D$\temp\Scripts\BackUpWS_ByVersion.ps1
2018-10-26T17:56:34.2086803Z ##[debug]port = 5985
2018-10-26T17:56:34.2110355Z ##[debug]scriptArguments = 
2018-10-26T17:56:34.2132606Z ##[debug]initializationScriptPath = 
2018-10-26T17:56:34.2159190Z ##[debug]protocolOption = -UseHttp
2018-10-26T17:56:34.2182449Z ##[debug]skipCACheckOption = 
2018-10-26T17:56:34.2205114Z ##[debug]enableDetailedLogging = true
2018-10-26T17:56:34.2222883Z ##[debug]Get-ParsedSessionVariable cmdlet
2018-10-26T17:56:34.2223320Z ##[debug]InputSessionVariables=$appname = InventoryManagement, $SourcePath = D:\Inetpub\websrvhub\InventoryManagement,$DLLs = D:\Inetpub\websrvhub\InventoryManagement\bin\InventoryManagement.dll
2018-10-26T17:56:34.2654256Z ##[debug]Initiating deployment on MachineName
2018-10-26T17:56:34.3423018Z ##[debug]Begin Invoke-PsOnRemote
2018-10-26T17:56:34.3423908Z ##[debug]Input param MachineDnsName : MachineName
2018-10-26T17:56:34.3424223Z ##[debug]Input param ScriptPath : \\MachineName\D$\temp\Scripts\BackUpWS_ByVersion.ps1
2018-10-26T17:56:34.3424514Z ##[debug]Input param InitializationScriptPath : 
2018-10-26T17:56:34.3424778Z ##[debug]Input param User : XXXXXXXXXXX
2018-10-26T17:56:34.3425101Z ##[debug]Input param SkipCACheck : False
2018-10-26T17:56:34.3425357Z ##[debug]Input param UseHttp : True
2018-10-26T17:56:34.3425605Z ##[debug]Input param WinRMPort : 5985
2018-10-26T17:56:34.3425893Z ##[debug]Input param ScriptBlockContent : 
2018-10-26T17:56:41.9741662Z ##[debug]End Invoke-PsOnRemote
2018-10-26T17:56:41.9873524Z ##[debug]Finished Deployment operation on MachineName:5985
2018-10-26T17:56:41.9924237Z Deployment logs for Deployment operation on MachineName:5985 
2018-10-26T17:56:42.0083800Z 
2018-10-26T17:56:42.0084407Z 	 Deployment started on target machine...
2018-10-26T17:56:42.0084915Z 
2018-10-26T17:56:42.0085136Z System.AggregateException: Failed to execute the powershell script. Consult the logs below for details of the error.
2018-10-26T17:56:42.0086798Z AuthorizationManager check failed. ---> System.Management.Automation.PSSecurityException: AuthorizationManager check failed. ---> System.Management.Automation.Host.HostException: A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning message. Do you want to run \\MachineName\D$\temp\Scripts\BackUpWS_ByVersion.ps1?
2018-10-26T17:56:42.0087475Z    at System.Management.Automation.Internal.Host.InternalHostUserInterface.ThrowPromptNotInteractive(String promptMessage)
2018-10-26T17:56:42.0087779Z    at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
2018-10-26T17:56:42.0087995Z    at Microsoft.PowerShell.PSAuthorizationManager.RemoteFilePrompt(String path, PSHost host)
2018-10-26T17:56:42.0088236Z    at Microsoft.PowerShell.PSAuthorizationManager.CheckPolicy(ExternalScriptInfo script, PSHost host, Exception& reason)
2018-10-26T17:56:42.0088460Z    at Microsoft.PowerShell.PSAuthorizationManager.ShouldRun(CommandInfo commandInfo, CommandOrigin origin, PSHost host, Exception& reason)
2018-10-26T17:56:42.0088677Z    at System.Management.Automation.AuthorizationManager.ShouldRunInternal(CommandInfo commandInfo, CommandOrigin origin, PSHost host)
2018-10-26T17:56:42.0088893Z    --- End of inner exception stack trace ---
2018-10-26T17:56:42.0089078Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-10-26T17:56:42.0089299Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-10-26T17:56:42.0089535Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-10-26T17:56:42.0089756Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-10-26T17:56:42.0090488Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-10-26T17:56:42.0090721Z    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2018-10-26T17:56:42.0090949Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2018-10-26T17:56:42.0091437Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2018-10-26T17:56:42.0091815Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2018-10-26T17:56:42.0092064Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2018-10-26T17:56:42.0092320Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2018-10-26T17:56:42.0092591Z    --- End of inner exception stack trace ---
2018-10-26T17:56:42.0092824Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2018-10-26T17:56:42.0093123Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.ExecuteScript(IPowerShell powerShell, String script, String arguments, Boolean isScriptDotSourced, Boolean useHttp)
2018-10-26T17:56:42.0093434Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
2018-10-26T17:56:42.0094100Z ---> (Inner Exception #0) System.Management.Automation.PSSecurityException: AuthorizationManager check failed. ---> System.Management.Automation.Host.HostException: A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning message. Do you want to run \\MachineName\D$\temp\Scripts\BackUpWS_ByVersion.ps1?
2018-10-26T17:56:42.0094490Z    at System.Management.Automation.Internal.Host.InternalHostUserInterface.ThrowPromptNotInteractive(String promptMessage)
2018-10-26T17:56:42.0094816Z    at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
2018-10-26T17:56:42.0095049Z    at Microsoft.PowerShell.PSAuthorizationManager.RemoteFilePrompt(String path, PSHost host)
2018-10-26T17:56:42.0095261Z    at Microsoft.PowerShell.PSAuthorizationManager.CheckPolicy(ExternalScriptInfo script, PSHost host, Exception& reason)
2018-10-26T17:56:42.0095498Z    at Microsoft.PowerShell.PSAuthorizationManager.ShouldRun(CommandInfo commandInfo, CommandOrigin origin, PSHost host, Exception& reason)
2018-10-26T17:56:42.0095730Z    at System.Management.Automation.AuthorizationManager.ShouldRunInternal(CommandInfo commandInfo, CommandOrigin origin, PSHost host)
2018-10-26T17:56:42.0095939Z    --- End of inner exception stack trace ---
2018-10-26T17:56:42.0096293Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-10-26T17:56:42.0097049Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-10-26T17:56:42.0097580Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-10-26T17:56:42.0097844Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-10-26T17:56:42.0098073Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-10-26T17:56:42.0099739Z    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2018-10-26T17:56:42.0099983Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2018-10-26T17:56:42.0100227Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2018-10-26T17:56:42.0100455Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2018-10-26T17:56:42.0100664Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2018-10-26T17:56:42.0100932Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)<---
2018-10-26T17:56:42.0101086Z 
2018-10-26T17:56:42.0101192Z 
2018-10-26T17:56:42.0148409Z ##[debug]Service logs for Deployment operation on MachineName:5985 
2018-10-26T17:56:42.0184518Z ##[debug]RemoteDeployerSource Verbose: 10 : [RemoteDeployer][26:Oct:18:12:56:38:1312; 41228, 4](MachineName)Creating public key for communication

If executing the script "BackUpWS_ByVersion.ps1" in local server. No window promoted and is successful.  The powershell version is below in target server:
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 Any comment to resolve this issue?

**Comment by Ajay-MS** [comment]
@johnqxu1 

It seems that the script you are trying to execute needs some user interaction related operation and user interaction operations are not be supported in the automation. 

Can you please try to execute the script locally and make sure script doesn't demand any user interaction.

**Comment by johnqxu1** [comment]
Thanks Ajay for your investigation and support.
The script runs fine in local and no window promoted to waiting for user
input.

As a matter of fact, when Powershell execution on remote machine, the
window promoted that asking if it is safe to run script. That is not from
the script run in remote machine but but it is this execution script that
invoking the script in remote machine. My understanding, the interaction is
between Powershell execution  (From VSTS) and user account.It is not remote
script issue.

Any comments or solution?

Thanks

John
