### ISSUE TITLE
checkout task: need ability to disable submodule fetch initially / Server does not allow request for unadvertised object

### ISSUE THREAD

**Issue by voltagex** [Microsoft/azure-pipelines-tasks#8725]
*Edit:* I *think* this is still an issue, but might be better over in the yaml repository - I had shallow fetch set to 20 in the build definition UI, and also had fetch submodules turned on. There doesn't appear to be a way to turn off submodule fetch completely in the YAML.

## Environment
- Server - Azure Pipelines
   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: baxterworks-build.qemu (https://dev.azure.com/baxterworks-build/qemu/)

- Agent - Hosted
        - If using Hosted agent, provide agent queue name: baxterworks-build.qemu

YAML is:
```
pool:
  vmImage: 'win1803'

trigger:
  branches:
    include:
    - azure
    exclude: 
    - master

steps:
- checkout: self
  fetchDepth: 1
  submodules: false

#error happens before this line is run
- script: git submodule update #https://www.spinics.net/lists/git/msg323566.html
  
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: azure-helper.ps1
```

## Issue Description
I'm currently hitting this bug: https://www.spinics.net/lists/git/msg323566.html

![image](https://user-images.githubusercontent.com/159567/47612662-26e07900-dad3-11e8-9924-0831b28957df.png)

### Task logs
[Build 20181028.16-Job1 (1).zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2522515/Build.20181028.16-Job1.1.zip)

### Error logs
```
2018-10-28T05:56:35.6475794Z error: Server does not allow request for unadvertised object 22ead3e0bfdb87516656453336160e0a37b066bf
2018-10-28T05:56:35.7547107Z Fetched in submodule path 'capstone', but it did not contain 22ead3e0bfdb87516656453336160e0a37b066bf. Direct fetching of that commit failed.
2018-10-28T05:56:35.7959219Z ##[error]System.InvalidOperationException: Git submodule update failed with exit code: 1
```

```
System.InvalidOperationException: Git submodule update failed with exit code: 1
   at Agent.Plugins.Repository.GitSourceProvider.<GetSourceAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.Plugins.Repository.CheckoutTask.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.PluginHost.Program.Main(String[] args)
```

**Comment by voltagex** [comment]
and yeah, I know `false` isn't a valid value for `submodules` - perhaps it should be?

**Comment by bryanmacfarlane** [comment]
please move to azure-pipelines-yaml repo

**Comment by gkohen** [comment]
Has this been moved? I could not find it on the azure-pipelines-yaml repository and I'm experiencing this issue at the moment.
The submodule is relative under the same GitHub org, registered with HTTPS rather than git.

**Comment by lumaxis** [comment]
I just ran into this too. As a workaround, I did this:

```yaml
- checkout: self
  persistCredentials: true
- script: git submodule update --init
  displayName: Checkout submodules
```
