### ISSUE TITLE
Publish Pipeline Artifact (Preview): Cannot upload to a pipeline artifact from release environment.

### ISSUE THREAD

**Issue by rstabenow** [Microsoft/azure-pipelines-tasks#8812]
## Environment
Azure Pipelines Release
Agent Version: 2.141.1
OS: Hosted Ubuntu 1604 and Hosted VS2017

## Issue Description

Pipeline artifact cannot be uploaded from release pipeline.

From documentation: Use this task in a build **or release pipeline** to publish pipeline artifacts to Azure Pipelines.

I try to combine multiple build artifacts into a single pipeline artifact, that can be used by later stages. All files are copied into $(System.DefaultWorkingDirectory)/application, which is also set as "path to publish". I also tried other directories under $(Agent.WorkFolder), same result.

### Task logs

```
2018-11-09T12:58:37.0965386Z ==============================================================================
2018-11-09T12:58:37.0965460Z Task         : Publish Pipeline Artifact
2018-11-09T12:58:37.0965719Z Description  : Publish Pipeline Artifact
2018-11-09T12:58:37.0965769Z Version      : 0.139.0
2018-11-09T12:58:37.0965802Z Author       : Microsoft Corporation
2018-11-09T12:58:37.0966013Z Help         : Publish a local directory or file as a named artifact for the current pipeline.
2018-11-09T12:58:37.0966068Z ==============================================================================
2018-11-09T12:58:37.5744150Z ##[error]System.InvalidOperationException: Cannot upload to a pipeline artifact from release environment.
   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTask.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, String targetPath, String artifactName, CancellationToken token)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
```

**Comment by koreyba** [comment]
I encounter the same issue:
```
2018-11-22T10:49:53.1144549Z ##[section]Starting: Publish Pipeline Artifact
2018-11-22T10:49:53.1147343Z ==============================================================================
2018-11-22T10:49:53.1147400Z Task         : Publish Pipeline Artifact
2018-11-22T10:49:53.1147434Z Description  : Publish Pipeline Artifact
2018-11-22T10:49:53.1147486Z Version      : 0.139.0
2018-11-22T10:49:53.1147518Z Author       : Microsoft Corporation
2018-11-22T10:49:53.1147550Z Help         : Publish a local directory or file as a named artifact for the current pipeline.
2018-11-22T10:49:53.1147583Z ==============================================================================
2018-11-22T10:49:53.6900040Z ##[error]System.InvalidOperationException: Cannot upload to a pipeline artifact from release environment.
   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTask.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, String targetPath, String artifactName, CancellationToken token)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2018-11-22T10:49:53.6930046Z ##[section]Finishing: Publish Pipeline Artifact

```

**Comment by KenticoMartinS** [comment]
Hi @rstabenow, @koreyba,
if you check directly [code that is executed](https://github.com/Microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/PipelineArtifact/PipelineArtifactPlugin.cs#L60), then you can see the **Publish Pipeline Artifact** task works only for Build pipelines.

I was a bit sad after this discovery, as we are waiting for publish artifact from release pipeline for ages.

**Comment by angellaa** [comment]
I am also looking forward to seeing this happening. We have many customers who want to publish artifacts at release time.

**Comment by turimbar1** [comment]
I have a number of customers who want this functionality :/

**Comment by kaiza** [comment]
Why doesn't this work in a Release? The documentation here https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=vsts clearly states:

Use this task in a build **or release** pipeline to publish pipeline artifacts to Azure Pipelines.

**Comment by gregbenner** [comment]
It doesn't work with a release pipeline... at the top of the task log when running
"Publish a local directory or file as a named artifact for the current pipeline."

**Comment by mitchdenny** [comment]
Hi folks - we'll correct the documentation. We would also like to be able to associate artifacts with the release pipeline but it doesn't have the necessary APIs to associate artifacts (of any type).

**Comment by greigs** [comment]
Assuming this has not been resolved yet; the documentation on this page is also misleading: [https://github.com/Microsoft/azure-pipelines-tasks/issues/8812](https://github.com/Microsoft/azure-pipelines-tasks/issues/8812)

**Comment by fleed** [comment]
I thought that this was an improvement over the previous publish task..
Still not able to create artifacts from releases, which I need to create installers and setup scripts with specific configuration for environments.

**Comment by mitchdenny** [comment]
@fleed unfortunately Release pipelines don't have the ability to have artifacts associated with them in general (other than artifacts that you feed in as inputs to a pipeline).

**Comment by petenorth** [comment]
We need to be able publish functional test results from release pipelines, how do we go about doing that?

**Comment by Vossekop** [comment]
@petenorth if it is just a place to store your test results (given that you can't import them using the [Publish Test Results task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)), maybe the [##vso[task.uploadfile]](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md) command is something for you. More information in [this](https://stackoverflow.com/questions/38456303/how-do-you-publish-files-back-to-vsts-release-management-as-part-of-a-release) stackoverflow question.

**Comment by kiwidave72** [comment]
I dont get this... people clearly what the feature, and have asked for this and but no new ticket is created and the issue gets closed as the current feature is working by design (which its not).
I also need this feature but i cant see way this isnt a feature out of the box.

**Comment by marcelopontipedra** [comment]
I need this feature. I think everyone who knows CI will need this.

**Comment by nearwood** [comment]
Well I spent 30 mins making a new release pipeline in our Azure DevOps 2019 Server to package up all our various build artifacts into one zip file that we can release to our customer. Only to not be able to upload that zip file.

I need this in a *release* pipeline since I need all the artifacts from different build pipelines. As a workaround, I'm doing a file copy to our dev web server's drop folder, to which I then remote into and transfer back to my computer, so we can give our customer a release.

I suppose I could do a build pipeline and add "Download Pipeline Artifacts" task but that's more cumbersome and error-prone than what I'm doing now.

**Comment by joshsten** [comment]
We'd also like this.

**Comment by marcelopontipedra** [comment]
Just do your build and release in your Pipeline build. You can always download your artifacts after the build.

**Comment by thomasgalliker** [comment]
@marcelopontipedra but you're sure you understand the purpose of separating build and release pipelines? When I see that this feature does not exist, I'm not even sure if Microsoft/devops understands the need for it. Deploying software is not always just a matter of publishing something to azure...

**Comment by marcelopontipedra** [comment]
Hi Thomas
It was an alternative way to finish my tasks. It was helpful for me, which I was able to give report from a 3 to 4hrs of build.

**Comment by marcelopontipedra** [comment]
I understand the separation of build and release, but I need the reports. I only did it for only 3 months, then go back to "build and release". 
My tasked was done everyone was happy. :)

**Comment by cawoodm** [comment]
We run functional testss (cypress) after we deploy a release. These tests produce screenshots/videos of failed tests. How can we view/access these files if a release pipeline is not allowed to publish anything?

**Comment by marcelopontipedra** [comment]
Just do the same thing I've done. I hope Microsoft will allow this feature soon so we will do this alternative solution.

**Comment by cawoodm** [comment]
You mean releasing with a "build" pipeline? There are pros and cons to doing this. Personally I like a code (yaml) approach and dislike the drag&drop approach but releases are integrated into the whole DevOps experience and dropping them drops some interesting functionality.

**Comment by brentleslie** [comment]
As Microsoft manage what is built and published in some of their data apps (Data Factory/Synapse), we really need to be able to download non-build source control artifacts... nonsensical that this is closed as it is "by design".  If I build a car that breaks down when it hits a pothole because its suspension is too hard, I would make future ones with softer suspension. Not claim that it was originally designed to never hit potholes and use that a reason to never do anything about it. It's a belligerent and brittle attitude towards customers, basically telling them that they are wrong.

**Comment by alexs77** [comment]
I also have this need. As a workaround for copying artifact files from stage (1) to stage (2), I added Azure CLI tasks to my stages, running these "scripts":

    # Upload in stage (1):
    az storage blob upload -f $(Build.BuildNumber).file --container-name something --name $(Build.BuildNumber).file --account-name storageaccount

And in the later stage(s):

    # Download in stage (2):
    az storage blob download -f $(Build.BuildNumber).file --container-name something --name $(Build.BuildNumber).file --account-name storageaccount

**Comment by Luiz-Monad** [comment]
I had this problem.  "publish Universal Packages" to the "feed" works. just publish a folder as a package there.

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/4574729/741d5ce2-7b48-42fb-be96-aa3c484d06a1)

It seems they finally fixed it. 
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/4574729/ebf3eaa3-ad98-4f96-8163-4541a430d2aa)

(don't forget to add permission to `project Build Service (project-infra)` )

**Comment by SeidChr** [comment]
not being able to publish release-artifacts is just 🤯
