### ISSUE TITLE
DownloadSecureFileV1 Build/release pipeline issue

### ISSUE THREAD

**Issue by mrpolaris** [Microsoft/azure-pipelines-tasks#8815]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - TFS on-premises
    TFS 2017.3

- Agent - Private: 
Windows_NT  6.3.9600

Agent version 2.134.2 

    -
## Issue Description

DownloadSecureFileV1

When using this task in the build def after it downloads the file from the securefile it errors when setting the path to a vso variable.  I think there is an extra ";" in the string

### Task logs
018-11-09T21:30:35.0071792Z ##[debug]set secureFilePath=E:\BuildAgent\Agent1\_work\_temp\TICodeSigningCert_June7.pfx
2018-11-09T21:30:35.0175964Z ##[error]Unable to process command '##vso[task.setvariable variable=secureFilePath;issecret=false;]E:\BuildAgent\Agent1\_work\_temp\TICodeSigningCert_June7.pfx' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2018-11-09T21:30:35.0203251Z ##[error]Value cannot be null.
Parameter name: RefName
2018-11-09T21:30:35.0385986Z ##[debug]System.ArgumentNullException: Value cannot be null.
Parameter name: RefName
   at Microsoft.VisualStudio.Services.Agent.Worker.ExecutionContext.SetVariable(String name, String value, Boolean isSecret, Boolean isOutput)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension.ProcessTaskSetVariableCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
2018-11-09T21:30:35.0389207Z ##[debug]Processed: ##vso[task.setvariable variable=secureFilePath;issecret=false;]E:\BuildAgent\Agent1\_work\_temp\TICodeSigningCert_June7.pfx

**Comment by madhurig** [comment]
@mrpolaris - Are you still seeing this issue or have you resolved it? Any output variables on the tasks need to be provided a custom name like below. 
![image](https://user-images.githubusercontent.com/3269636/53436770-f26dc280-39c9-11e9-9bdd-dca128158c67.png)

Please check if that option is available in your TFS version. 

Thanks,
Madhuri

**Comment by mrpolaris** [comment]
Yes I did not make any code updates.  I found a third party task in the marketplace.  But would like to use this task and remove the third party.


Trent Bielejeski
Build Release Engineer
Work Hours : M-F 8:15am - 4:30pm office
W: (701) 353-7351

[Description: cid:image001.gif@01CA6C40.FA1B4B80]

**Comment by madhurig** [comment]
For support with the 3rd party task, you will need to contact the owner. We also built a "DownloadSecureFile" task in the product based on customer requests but that didn't ship in your TFS version. You can try compiling the task and uploading it to your TFS server using the [tfs-cli tool](https://github.com/Microsoft/tfs-cli)

Thanks,
Madhuri
