### ISSUE TITLE
VSTest hangs

### ISSUE THREAD

**Issue by grokys** [Microsoft/azure-pipelines-tasks#8838]
## Environment

Hosted; https://github-editor-tools.visualstudio.com/VisualStudio/_build?definitionId=4
    
## Issue Description

The `VSTest` task hangs after running all tests in about 1/3 builds.

### Task logs

Debug logs are as follows:

[logs_158.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2580471/logs_158.zip)

Note that I also enabled `diagnosticsEnabled: true` on the `VSTest` task but I don't seem to be able to get to the logs it produced and cannot upload them as artifacts because the build needs to be cancelled as it hangs, causing the publish artifacts step to be skipped. Hints on how to get hold of this log file would be appreciated.

### Error logs

Nothing really to see here. The relevant lines are:

```
2018-11-14T10:53:41.5003002Z Passed   RepoChangedHandlesNullRepository
2018-11-14T10:57:27.3560119Z ##[debug]Re-evaluate condition on job cancellation for step: 'VSTest'.
2018-11-14T10:57:27.3770467Z ##[section]Finishing: VSTest
```

You can see that the last test passed, then the agent hung for ~4 minutes until I cancelled it.

**Comment by karanjitsingh** [comment]
Hi @grokys, I don't seem to have access to your build definition.

To get the logs, what we can try is to set a timeout for the test sessions. Use a runsettings file with the content

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <TestSessionTimeout>10000</TestSessionTimeout>
  </RunConfiguration>
</RunSettings>
```

**Comment by grokys** [comment]
Hi @karanjitsingh, thanks for the reply. The build definition is on the `azure-pipelines` branch - you can see it at https://github.com/github/VisualStudio/blob/azure-pipelines/azure-pipelines.yml.

In the meantime, I will add the runsettings file with the timeout, thanks for the tip!

**Comment by grokys** [comment]
@karanjitsingh I added the runsettings file with a 10 second timeout as you suggested. This didn't give all the tests time to run, but it did publish a Test Run:

https://dev.azure.com/github-editor-tools/VisualStudio/_build/results?buildId=160&view=logs
```
2018-11-15T11:08:51.3415278Z Results File: D:\a\1\s\TestResults\VssAdministrator_factoryvm-az383_2018-11-15_11_08_43.trx
2018-11-15T11:08:51.3421188Z 
2018-11-15T11:08:51.3421617Z Total tests: Unknown. Passed: 280. Failed: 0. Skipped: 0.
2018-11-15T11:08:51.3421896Z Test Run Aborted.
2018-11-15T11:08:51.3422146Z Test execution time: 10.0321 Seconds
2018-11-15T11:09:01.4625755Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2018-11-15T11:09:01.4978938Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
2018-11-15T11:09:01.7766994Z ##[error]VsTest task failed.
2018-11-15T11:09:01.8197399Z ##[section]Async Command Start: Publish test results
2018-11-15T11:09:01.8243982Z Publishing test results to test run '43'
2018-11-15T11:09:01.8244166Z Test results remaining: 280. Test run id: 43
2018-11-15T11:09:02.3676057Z Published Test Run : https://github-editor-tools.visualstudio.com/VisualStudio/_TestManagement/Runs#runId=43&_a=runCharts
2018-11-15T11:09:02.3685402Z ##[section]Async Command End: Publish test results
2018-11-15T11:09:02.3686394Z ##[section]Finishing: VSTest
```

However, when I increased the timeout to allow the tests to hang, I see the following:

https://dev.azure.com/github-editor-tools/VisualStudio/_build/results?buildId=162&view=logs
```
2018-11-15T11:26:43.9772581Z Results File: D:\a\1\s\TestResults\VssAdministrator_factoryvm-az379_2018-11-15_11_24_46.trx
2018-11-15T11:26:43.9772777Z 
2018-11-15T11:26:43.9772906Z Total tests: Unknown. Passed: 944. Failed: 0. Skipped: 6.
2018-11-15T11:26:43.9773024Z Test execution time: 2.0007 Minutes
2018-11-15T11:26:43.9773142Z Test Run Aborted.
```

In this case, no Test Run is published and the `PublishBuildArtifacts` task doesn't run either.

I've made the project public so hopefully you can access it yourself now.

**Comment by Izzmo** [comment]
I'm currently running into this issue as well. Notice the time the test finishes (fails) and then the cancel is a difference of **21 minutes.** 

```
2018-11-15T18:11:16.5177405Z Results File: D:\a\_temp\TestResults\VssAdministrator_factoryvm-az362_2018-11-15_18_11_14.trx
2018-11-15T18:11:16.5195770Z 
2018-11-15T18:11:16.5198615Z Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
2018-11-15T18:11:16.5203977Z Test Run Failed.
2018-11-15T18:11:16.5211692Z Test execution time: 2.3095 Minutes
2018-11-15T18:32:35.7738674Z ##[debug]Re-evaluate condition on job cancellation for step: 'Run UI Tests'.
2018-11-15T18:32:35.8325699Z ##[error]The operation was canceled.
2018-11-15T18:32:35.8338345Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, IList`1 contentsToStandardIn, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, IList`1 contentsToStandardIn, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2018-11-15T18:32:35.8340847Z ##[section]Finishing: Run UI Tests
```

**Comment by karanjitsingh** [comment]
@grokys, Is it possible you're doing something similar?

https://github.com/Microsoft/azure-pipelines-tasks/issues/8733#issuecomment-439213502

**Comment by grokys** [comment]
@karanjitsingh I don't think so. We don't use selenium. We do actually fire up a Nancy server for a couple of tests, but I've tried removing those tests and was still able to reproduce the hang.

In fact, I'll re-disable those tests now to make sure.

**Comment by grokys** [comment]
@karanjitsingh I've just disabled those tests and you can see the tests are still hanging here: https://dev.azure.com/github-editor-tools/VisualStudio/_build/results?buildId=166&view=logs

**Comment by karanjitsingh** [comment]
@grokys, could you share a build that eventually expires and is not cancelled, with `system.debug=true`. When the build is cancelled the vstest diagnostic logs are not uploaded and I can't know what was going on inside vstest when the test hangs.

**Comment by grokys** [comment]
@karanjitsingh here you go: https://dev.azure.com/github-editor-tools/VisualStudio/_build/results?buildId=172&view=logs

Does that give you everything you needed?

**Comment by karanjitsingh** [comment]
@grokys, alright so I still can't access the vstest diagnostics logs because publish build artifacts is getting skipped.

![image](https://user-images.githubusercontent.com/4632805/48942520-cca5cd00-ef45-11e8-887c-8c01cc188db8.png)

Apologies for another ask and a build queue, here's what you need to do: update the Publish Build Artifact task to upload in all scenarios

![image](https://user-images.githubusercontent.com/4632805/48942579-0aa2f100-ef46-11e8-9a44-d53c4dc11817.png)

You can keep the test timeout so that you don't have to run the build for a long duration. We need the vstest diagnostic logs to identify which test is hanging and further diagnose why it's hanging.

**Comment by grokys** [comment]
I can enable that setting, but I'm not currently able to upload the VSTest diagnostics in that task anyway, because I don't know how to get hold of the file path:

```
Logging Vstest Diagnostics in file: D:\a\_temp\12622320-ef00-11e8-a778-d3f6aa8f9113.txt
```

How do i get hold of that path? I can't find any documentation on this, and looking through the `VSTest` task code didn't reveal much.

**Comment by karanjitsingh** [comment]
@grokys, one possible way is to run the build on a private agent

**Comment by grokys** [comment]
By "private agent" do you mean what the docs refer to as a "self-hosted agent"? https://docs.microsoft.com/en-gb/azure/devops/pipelines/agents/agents?view=vsts#install

**Comment by karanjitsingh** [comment]
Yes, private agent should help you get the logs.

**Comment by manu4rhyme** [comment]
Hi,

I have been facing the same issue, while trying to on board our product to continuous testing using Selenium. Locally all our Selenium tests are passing, however they are failing on AzDev Ops instead.

I’ve tried following this tutorial
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=vsts

But I’m facing few issues:

Unable to finish/terminate VSTest task (it keeps running indefinitely until I add timeout in control options)
Unable to collect video recordings of the test run https://docs.microsoft.com/en-us/azure/devops/test/collect-screenshots-and-video?view=vsts , so cannot debug failures on the pipeline
Clearly, if the VSTest task were to terminate gracefully, it should ideally publish test results including screenshots/video_recordings, so that we could debug why some test cases are failing on remote agent.

But the VSTest task is not closing, I've already tried multiple timeout values and hosted agent versions but still the same issue.

I've also mailed multiple instances of my logs during testing, to devops_tools@microsoft.com

Also I've tried browser.Quit() as well with no help.

**Comment by ShreyasRmsft** [comment]
@grokys hey are you still facing the issue? 

Also if you ran your tests using the VsTest task it should automatically upload all the log files generated like 

> Logging Vstest Diagnostics in file: D:\a\_temp\12622320-ef00-11e8-a778-d3f6aa8f9113.txt

as part of the build logs. I tried going through the links pasted in the thread but the build definition seems to have changed and the older builds seem to have expired. Do you have a recent failure for me to look at?

**Comment by vagisha-nidhi** [comment]
@grokys Any updates on this?

**Comment by grokys** [comment]
Apologies for the silence - I was on vacation for Christmas.

Yes we're still having a problem here. @ShreyasRmsft for the moment we've disabled running tests which is why you've not been able to find them. I will update the original PR and run the tests there again.

We've also had a few instances of the tests hanging on AppVeyor, which does suggest that the root of the problem is with our tests, however it happens on Azure Pipelines _much_ more often.

Having said that, I think there is still a problem with Azure Pipelines because when the tests _do_ fail, VSTest times out, but the build continues to hang until an hour passes. I'll look into getting a build to you which is failing in this way.

**Comment by grokys** [comment]
Ok, here is a test run that has failed:

https://github-editor-tools.visualstudio.com/VisualStudio/_build/results?buildId=608

You can see that VSTest timed out correctly after two minutes:

```
Total tests: Unknown. Passed: 960. Failed: 0. Skipped: 3.
Test Run Aborted.
Test execution time: 2.0004 Minutes
```

However the build continued to run (still running as I'm writing this) in a hung state.

**Comment by vagisha-nidhi** [comment]
@grokys 
This seems to be an issue with NUnit adapter and we have logged this with them as well.
We have analyzed this and it may be happening on Azure Pipelines much more often than AppVeyor because of hosted agents which are fairly slow machines (2 cores) and this could cause hang in events when NUnit adapter is stuck.
You can follow this [link](https://github.com/nunit/nunit/issues/3102) to the issue we logged with the Nunit folks. We have provided them with the dump we collected and that should be enough for them to take this further.

**Comment by hyobyun** [comment]
We are often seeing vstest.executionengine.x86 process hang on self hosted agents with console options "/Framework:Framework45 /inIsolation ". We are able to often induce this by cancelling builds while the tests are running. We end up having to terminate the process manually in order to restore functionality to the build servers.

**Comment by karanjitsingh** [comment]
@hyobyun, since this thread has a lot of mixed context I'd urge you to create a new issue referencing manu4rhyme's comment, this will help you get more traction.

**Comment by prawalagarwal** [comment]
Closing this issue. Please reopen if you are still facing this. @hyobyun please consider opening a new issue.
