### ISSUE TITLE
Visual Studio Test task failing on hosted agent

### ISSUE THREAD

**Issue by govanikunal** [Microsoft/azure-pipelines-tasks#9169]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

https://microsoftit.visualstudio.com/OneITVSO/_releaseProgress?_a=release-environment-logs&releaseId=526540&environmentId=1638346

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: **Hosted VS2017**

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
We are using the coded UI test running with help of selenium web drivers. It was working fine when we were using the self hosted agent. Now, we moved to hosted agent but it's failing for the below task. Please check screenshot & attached logs too:

Referring the Web Drivers using Environment.GetEnvironmentVariable("IEWebDriver") as per [article](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=vsts).

Task: Visual Studio Test

![image](https://user-images.githubusercontent.com/19185363/50413646-9904de00-0836-11e9-915d-976babf9a8b7.png)

### Task logs

2018-12-24T10:54:45.9510307Z TestContext Messages:
2018-12-24T10:54:45.9510453Z Browser Used: [OpenQA.Selenium.IE.InternetExplorerDriver]
2018-12-24T10:54:45.9510608Z  Chrome Browser Launched
2018-12-24T10:54:45.9510700Z  Chrome Browser Launched
2018-12-24T10:54:45.9510892Z  Excuting test scenarios for VariationType= 1 and VariationName:Create new deal and Complete Customer Contract and ReleaseVersion:Happy Path
2018-12-24T10:54:45.9511086Z  Found flag to create new deal. Creating new deal....
2018-12-24T10:54:45.9511234Z  Chrome Browser Launched
2018-12-24T10:54:45.9511502Z  Chrome Browser Launched
2018-12-24T10:54:45.9511626Z  VariationType:1 test case Failed with Error Reason:Timed out after 120 seconds
2018-12-24T10:54:45.9512212Z  Stack Trace:   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
2018-12-24T10:54:45.9512942Z     at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
2018-12-24T10:54:45.9513339Z     at CompassOneAutomation.Framework.Driver.Wait(By selector, Boolean invisible) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Framework\Driver.cs:line 477
2018-12-24T10:54:45.9513684Z     at CompassOneAutomation.Framework.Driver.Click(By by, TimeSpan waitTimeAfterClick, Boolean nondisplayable) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Framework\Driver.cs:line 372
2018-12-24T10:54:45.9514010Z     at CompassOneAutomation.Features.FeatureBase.CreateDealWithoutOpportunity(String geoId, String CustomerName) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Features\FeatureBase.cs:line 180
2018-12-24T10:54:45.9514319Z     at CompassOneAutomation.Features.FeatureBase.CreateNewDeal(DealInput dealInput) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Features\FeatureBase.cs:line 136
2018-12-24T10:54:45.9514650Z     at CompassOneAutomation.Features.FeatureBase.InitData(String variationTypeId, String FeatureFileName, DealInput dealInput) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Features\FeatureBase.cs:line 97
2018-12-24T10:54:45.9514927Z     at CompassOneTest.TestMethods.ExcelDataDriven.ExcelDataDriven_HPBasic()
2018-12-24T10:54:45.9515161Z   Inner Exception Error Reason:Unable to find element with xpath == .//div[@id='divLeftNav']/div/ul/li[2]
2018-12-24T10:54:45.9515479Z   Inner Exception StackTrace:   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
2018-12-24T10:54:45.9515751Z     at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2018-12-24T10:54:45.9515998Z     at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
2018-12-24T10:54:45.9516240Z     at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
2018-12-24T10:54:45.9516485Z     at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
2018-12-24T10:54:45.9516729Z     at OpenQA.Selenium.By.FindElement(ISearchContext context)
2018-12-24T10:54:45.9516909Z     at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
2018-12-24T10:54:45.9517150Z     at CompassOneAutomation.Framework.ExpectedConditions.<>c__DisplayClass0_0.<VisibleElementIsClickable>b__0(IWebDriver driver) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Framework\Driver.cs:line 884
2018-12-24T10:54:45.9517342Z     at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
2018-12-24T10:54:45.9517439Z 
### Error logs

Stack Trace:   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
2018-12-24T10:54:45.9512942Z     at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
2018-12-24T10:54:45.9513339Z     at CompassOneAutomation.Framework.Driver.Wait(By selector, Boolean invisible) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Framework\Driver.cs:line 477
2018-12-24T10:54:45.9513684Z     at CompassOneAutomation.Framework.Driver.Click(By by, TimeSpan waitTimeAfterClick, Boolean nondisplayable) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Framework\Driver.cs:line 372
2018-12-24T10:54:45.9514010Z     at CompassOneAutomation.Features.FeatureBase.CreateDealWithoutOpportunity(String geoId, String CustomerName) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Features\FeatureBase.cs:line 180
2018-12-24T10:54:45.9514319Z     at CompassOneAutomation.Features.FeatureBase.CreateNewDeal(DealInput dealInput) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Features\FeatureBase.cs:line 136
2018-12-24T10:54:45.9514650Z     at CompassOneAutomation.Features.FeatureBase.InitData(String variationTypeId, String FeatureFileName, DealInput dealInput) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Features\FeatureBase.cs:line 97
2018-12-24T10:54:45.9514927Z     at CompassOneTest.TestMethods.ExcelDataDriven.ExcelDataDriven_HPBasic()
2018-12-24T10:54:45.9515161Z   Inner Exception Error Reason:Unable to find element with xpath == .//div[@id='divLeftNav']/div/ul/li[2]
2018-12-24T10:54:45.9515479Z   Inner Exception StackTrace:   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
2018-12-24T10:54:45.9515751Z     at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2018-12-24T10:54:45.9515998Z     at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
2018-12-24T10:54:45.9516240Z     at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
2018-12-24T10:54:45.9516485Z     at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
2018-12-24T10:54:45.9516729Z     at OpenQA.Selenium.By.FindElement(ISearchContext context)
2018-12-24T10:54:45.9516909Z     at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
2018-12-24T10:54:45.9517150Z     at CompassOneAutomation.Framework.ExpectedConditions.<>c__DisplayClass0_0.<VisibleElementIsClickable>b__0(IWebDriver driver) in D:\a\1\s\CodedUITests\CompassOneAutomation\CompassOneAutomation\Framework\Driver.cs:line 884
2018-12-24T10:54:45.9517342Z     at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)

**Comment by ShreyasRmsft** [comment]
@govanikunal this scenario is not supported on hosted agents

**Comment by ShreyasRmsft** [comment]
@govanikunal we support only pure Selenium tests.

Coded UI tests are deprecated and we do not support running them on hosted agents.

**Comment by govanikunal** [comment]
Okay, what about the headless option. is that supported?

var option = new ChromeOptions();
option.AddArgument("--headless");
IWebDriver instance = new ChromeDriver(Environment.GetEnvironmentVariable("ChromeWebDriver"));

**Comment by ShreyasRmsft** [comment]
As long as it's a pure selenium test, we aren't doing anything special. If it runs locally with the same version of the webdriver and browser it ought to run on the hosted machines too.

Just double check if the feature is available for the version of chrome installed on the hosted machine along with the version of the driver that is present on the hosted machines.

**Comment by govanikunal** [comment]
Will verify those, Thanks for the clarifications.

**Comment by ShreyasRmsft** [comment]
@govanikunal closing this issue. Please re-open a new issue if this does not work for you to avoid mixing up/cluttering issues.

Thanks.
