### ISSUE TITLE
dotnet restore task suddenly started failing (The process cannot access the file)

### ISSUE THREAD

**Issue by andtii** [Microsoft/azure-pipelines-tasks#9205]
## Environment
Server - Azure Pipelines
Account
https://omnia-source.visualstudio.com/Omnia

Build 
Publish Preview Omnia Nuget And Npm Packages
Latest 

Agent - Hosted
agent queue name:
Hosted VS2017
Agent: Hosted Agent

## Issue Description

.net core task
dotnet restore

### Task logs

2018-12-30T10:50:54.3297669Z ==============================================================================
2018-12-30T10:50:54.3297771Z Task         : .NET Core
2018-12-30T10:50:54.3297892Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command. For package commands, supports NuGet.org and authenticated feeds like Package Management and MyGet.
2018-12-30T10:50:54.3298011Z Version      : 2.144.4
2018-12-30T10:50:54.3298078Z Author       : Microsoft Corporation
2018-12-30T10:50:54.3298182Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2018-12-30T10:50:54.3298290Z ==============================================================================
2018-12-30T10:50:54.9784178Z [command]C:\Windows\system32\chcp.com 65001
2018-12-30T10:50:55.0578813Z Active code page: 65001
2018-12-30T10:50:55.0612025Z SYSTEMVSSCONNECTION exists true
2018-12-30T10:50:55.2796336Z SYSTEMVSSCONNECTION exists true
2018-12-30T10:50:57.5663105Z SYSTEMVSSCONNECTION exists true
2018-12-30T10:50:57.5687960Z Saving NuGet.config to a temporary config file.
2018-12-30T10:50:57.5732997Z Saving NuGet.config to a temporary config file.
2018-12-30T10:50:57.5873302Z [command]"C:\Program Files\dotnet\dotnet.exe" restore D:\a\1\s\src\Omnia.Core.Models\Omnia.Core.Models.csproj --configfile D:\a\1\Nuget\tempNuGet_2236.config --verbosity Detailed
2018-12-30T10:50:59.8119150Z 
2018-12-30T10:50:59.8149658Z Welcome to .NET Core!
2018-12-30T10:50:59.8150218Z ---------------------
2018-12-30T10:50:59.8150631Z Learn more about .NET Core: https://aka.ms/dotnet-docs
2018-12-30T10:50:59.8151524Z Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
2018-12-30T10:50:59.8151755Z 
2018-12-30T10:50:59.8151974Z Telemetry
2018-12-30T10:50:59.8152169Z ---------
2018-12-30T10:50:59.8152454Z The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
2018-12-30T10:50:59.8154314Z 
2018-12-30T10:50:59.8154788Z Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
2018-12-30T10:50:59.8155064Z 
2018-12-30T10:50:59.8155269Z Configuring...
2018-12-30T10:50:59.8155345Z --------------
2018-12-30T10:50:59.8155469Z A command is running to populate your local package cache to improve restore speed and enable offline access. This command takes up to one minute to complete and only runs once.
2018-12-30T10:53:19.5783725Z Decompressing .......... 138789 ms
2018-12-30T10:54:31.3714910Z Expanding .........System.AggregateException: One or more errors occurred. (One or more errors occurred. (The process cannot access the file 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\tools\Microsoft.AspNetCore.Razor.Language.dll' because it is being used by another process.)) (The process cannot access the file 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\tools\Microsoft.AspNetCore.Razor.Language.dll' because it is being used by another process.) ---> System.IO.IOException: The process cannot access the file 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\tools\Microsoft.AspNetCore.Razor.Language.dll' because it is being used by another process.
2018-12-30T10:54:31.3716037Z    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
2018-12-30T10:54:31.3716334Z    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
2018-12-30T10:54:31.3716554Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2018-12-30T10:54:31.3716745Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
2018-12-30T10:54:31.3718535Z    at System.IO.File.Create(String path)
2018-12-30T10:54:31.3719133Z    at Microsoft.DotNet.Archive.IndexedArchive.CopyOperation.Execute()
2018-12-30T10:54:31.3719527Z    at Microsoft.DotNet.Archive.IndexedArchive.ExtractOperation.DoOperation()
2018-12-30T10:54:31.3719885Z    at Microsoft.DotNet.Archive.IndexedArchive.<>c__DisplayClass19_1.<Extract>b__0(ExtractOperation extractOperation)
2018-12-30T10:54:31.3720076Z    at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
2018-12-30T10:54:31.3720602Z    at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
2018-12-30T10:54:31.3721257Z    at System.Linq.Parallel.SpoolingTaskBase.Work()
2018-12-30T10:54:31.3721453Z    at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
2018-12-30T10:54:31.3722182Z    at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
2018-12-30T10:54:31.3722435Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-12-30T10:54:31.3722565Z --- End of stack trace from previous location where exception was thrown ---
2018-12-30T10:54:31.3722708Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-12-30T10:54:31.3722835Z    --- End of inner exception stack trace ---
2018-12-30T10:54:31.3722942Z    at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
2018-12-30T10:54:31.3723104Z    at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
2018-12-30T10:54:31.3723254Z    at System.Linq.Parallel.MergeExecutor`1.Execute()
2018-12-30T10:54:31.3723404Z    at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
2018-12-30T10:54:31.3723778Z    at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
2018-12-30T10:54:31.3723953Z    at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
2018-12-30T10:54:31.3724104Z    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
2018-12-30T10:54:31.3724414Z    at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
2018-12-30T10:54:31.3724902Z    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
2018-12-30T10:54:31.3725014Z    at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
2018-12-30T10:54:31.3725131Z    at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
2018-12-30T10:54:31.3725232Z    at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
2018-12-30T10:54:31.3725326Z    at Microsoft.DotNet.Archive.IndexedArchive.Extract(String compressedArchivePath, String outputDirectory, IProgress`1 progress)
2018-12-30T10:54:31.3725438Z    at Microsoft.DotNet.Configurer.NuGetPackagesArchiver.ExtractArchive(String archiveDestination)
2018-12-30T10:54:31.3725517Z    at Microsoft.DotNet.Configurer.NuGetCachePrimer.PrimeCache()
2018-12-30T10:54:31.3725616Z    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
2018-12-30T10:54:31.3725767Z    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, CliFolderPathCalculator cliFolderPathCalculator, Boolean hasSuperUserAccess)
2018-12-30T10:54:31.3726399Z    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
2018-12-30T10:54:31.3726478Z    at Microsoft.DotNet.Cli.Program.Main(String[] args)
2018-12-30T10:54:31.3726621Z ---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\tools\Microsoft.AspNetCore.Razor.Language.dll' because it is being used by another process.
2018-12-30T10:54:31.3726755Z    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
2018-12-30T10:54:31.3726839Z    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
2018-12-30T10:54:31.3726956Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2018-12-30T10:54:31.3727084Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
2018-12-30T10:54:31.3727161Z    at System.IO.File.Create(String path)
2018-12-30T10:54:31.3727255Z    at Microsoft.DotNet.Archive.IndexedArchive.CopyOperation.Execute()
2018-12-30T10:54:31.3727332Z    at Microsoft.DotNet.Archive.IndexedArchive.ExtractOperation.DoOperation()
2018-12-30T10:54:31.3727619Z    at Microsoft.DotNet.Archive.IndexedArchive.<>c__DisplayClass19_1.<Extract>b__0(ExtractOperation extractOperation)
2018-12-30T10:54:31.3727738Z    at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
2018-12-30T10:54:31.3727825Z    at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
2018-12-30T10:54:31.3728149Z    at System.Linq.Parallel.SpoolingTaskBase.Work()
2018-12-30T10:54:31.3728575Z    at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
2018-12-30T10:54:31.3728688Z    at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
2018-12-30T10:54:31.3728818Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-12-30T10:54:31.3728916Z --- End of stack trace from previous location where exception was thrown ---
2018-12-30T10:54:31.3729045Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---
2018-12-30T10:54:31.3729100Z

**Comment by tejasd1990** [comment]
Hi @andtii,
We are fixing this issue. Meanwhile, were you able to get the task working with the workaround suggested by hiyadav above?

**Comment by dikhakha** [comment]
Closing this issue as the fix has been merged. The fix should be available in few weeks.

**Comment by Aforkldj** [comment]
hello, does anyone have news on the issue? i'm having a hard time because of it :(

**Comment by hiyadav** [comment]
@Aforkldj
For helping us investigate, can you paste debug logs of the failing instance of the task.
