### ISSUE TITLE
Azure file copy tasks fails with error when trying to copy file using an on-premise agent to azure storage

### ISSUE THREAD

**Issue by shajusukumaran** [Microsoft/azure-pipelines-tasks#9219]
## Troubleshooting
Enable debug on the task and checked the logs, receiving the below error:'
`2018-12-14T17:38:43.1589619Z ##[debug]System.Exception: There was an error with the service principal used for the deployment. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.162.120.220:443`

## Environment
- Azure Pipelines

- Agent - Hosted or Private: 
Private agent: on-premise, behind corporate firewall
Agent Version: 2.144.0
Agent OS: Windows_NT
Agent OS Version: 10.0.14393

## Issue Description
Trying to copy file to a storage account using Azure File Copy task.

### Task logs

```
Error Stack Trace:
2018-12-14T17:37:39.3883591Z ##[command]Clear-AzureRmContext -Scope Process
2018-12-14T17:38:00.5323926Z ##[command]Clear-AzureRmContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
2018-12-14T17:38:21.6714136Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud
2018-12-14T17:38:43.0088025Z ##[error]An error occurred while sending the request.
2018-12-14T17:38:43.0094753Z ##[debug]Processed: ##vso[task.logissue type=error]An error occurred while sending the request.
2018-12-14T17:38:43.0490750Z ##[debug]Leaving Initialize-Azure.
2018-12-14T17:38:43.0627886Z ##[debug]Caught exception from task script.
2018-12-14T17:38:43.0657365Z ##[debug]Error record:
2018-12-14T17:38:43.1402226Z ##[debug]There was an error with the service principal used for the deployment.
2018-12-14T17:38:43.1411185Z ##[debug]At C:\vsts-agt-generic-01\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.144\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1:222 char:17
2018-12-14T17:38:43.1420002Z ##[debug]+ ...             throw (New-Object System.Exception((Get-VstsLocString -Ke ...
2018-12-14T17:38:43.1428906Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-12-14T17:38:43.1437938Z ##[debug]    + CategoryInfo          : OperationStopped: (:) [], Exception
2018-12-14T17:38:43.1446458Z ##[debug]    + FullyQualifiedErrorId : There was an error with the service principal used for the deployment.
2018-12-14T17:38:43.1455366Z ##[debug] 
2018-12-14T17:38:43.1468622Z ##[debug]Script stack trace:
2018-12-14T17:38:43.1493978Z ##[debug]at Initialize-AzureSubscription, C:\vsts-agt-generic-01\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.144\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1: line 222
2018-12-14T17:38:43.1502381Z ##[debug]at Initialize-Azure, C:\vsts-agt-generic-01\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.144\ps_modules\VstsAzureHelpers_\VstsAzureHelpers_.psm1: line 54
2018-12-14T17:38:43.1510686Z ##[debug]at <ScriptBlock>, C:\vsts-agt-generic-01\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.144\AzureFileCopy.ps1: line 55
2018-12-14T17:38:43.1519305Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-12-14T17:38:43.1528378Z ##[debug]at <ScriptBlock>, <No file>: line 22
2018-12-14T17:38:43.1536683Z ##[debug]at <ScriptBlock>, <No file>: line 18
2018-12-14T17:38:43.1549776Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-12-14T17:38:43.1558463Z ##[debug]Exception:
2018-12-14T17:38:43.1589619Z ##[debug]System.Exception: There was an error with the service principal used for the deployment. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.162.120.220:443
2018-12-14T17:38:43.1598482Z ##[debug]   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
2018-12-14T17:38:43.1607121Z ##[debug]   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
2018-12-14T17:38:43.1616213Z ##[debug]   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
2018-12-14T17:38:43.1624758Z ##[debug]   --- End of inner exception stack trace ---
2018-12-14T17:38:43.1633371Z ##[debug]   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2018-12-14T17:38:43.1641187Z ##[debug]   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
2018-12-14T17:38:43.1649798Z ##[debug]   --- End of inner exception stack trace ---
2018-12-14T17:38:43.1658230Z ##[debug]   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
2018-12-14T17:38:43.1666803Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-12-14T17:38:43.1675663Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-14T17:38:43.1684673Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-14T17:38:43.1693435Z ##[debug]   at Microsoft.Azure.Commands.Common.Authentication.Factories.CancelRetryHandler.<SendAsync>d__12.MoveNext()
2018-12-14T17:38:43.1701985Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-12-14T17:38:43.1710421Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-14T17:38:43.1718907Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-14T17:38:43.1727477Z ##[debug]   at Microsoft.Azure.Internal.Subscriptions.SubscriptionsOperations.<ListWithHttpMessagesAsync>d__7.MoveNext()
2018-12-14T17:38:43.1735971Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-12-14T17:38:43.1744721Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-14T17:38:43.1753170Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-14T17:38:43.1761467Z ##[debug]   at Microsoft.Azure.Internal.Subscriptions.SubscriptionsOperationsExtensions.<ListAsync>d__5.MoveNext()
2018-12-14T17:38:43.1770036Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-12-14T17:38:43.1778719Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-14T17:38:43.1787015Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-14T17:38:43.1795683Z ##[debug]   at Microsoft.Azure.Internal.Subscriptions.SubscriptionsOperationsExtensions.List(ISubscriptionsOperations operations)
2018-12-14T17:38:43.1804877Z ##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.Paging.GenericPageEnumerator`1..ctor(Func`1 list, Func`2 listNext, UInt64 first, UInt64 skip)
2018-12-14T17:38:43.1813350Z ##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.Paging.GenericPageEnumerable`1.GetEnumerator()
2018-12-14T17:38:43.1821718Z ##[debug]   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2018-12-14T17:38:43.1830238Z ##[debug]   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2018-12-14T17:38:43.1839171Z ##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.TryGetTenantSubscription(IAccessToken accessToken, IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, IAzureSubscription& subscription, IAzureTenant& tenant)
2018-12-14T17:38:43.2051725Z ##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
2018-12-14T17:38:43.2052239Z ##[debug]   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass87_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
2018-12-14T17:38:43.2052577Z ##[debug]   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
2018-12-14T17:38:43.2052858Z ##[debug]   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
2018-12-14T17:38:43.2053091Z ##[debug]   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
2018-12-14T17:38:43.2053447Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2018-12-14T17:38:43.2053805Z ##[debug]   --- End of inner exception stack trace ---
2018-12-14T17:38:43.2054982Z ##[error]There was an error with the service principal used for the deployment.
2018-12-14T17:38:43.2055386Z ##[debug]Processed: ##vso[task.logissue type=error]There was an error with the service principal used for the deployment.
2018-12-14T17:38:43.2056341Z ##[debug]Processed: ##vso[task.complete result=Failed]
2018-12-14T17:38:43.2322324Z ##[section]Finishing: AzureBlob File Copy : EDL custom script

```

**Comment by SumiranAgg** [comment]
@shajusukumaran Apologies for late reply. Are you still facing the issue? If yes please share complete debug logs for the task at RM_Customer_Queries@microsoft.com

**Comment by rajatagrawal-dev** [comment]
As discussed offline, this was a proxy issue.
We have added support for reading proxy passed while configuring agent in Azure File Copy V3 task. The updated task will be released to all accounts in 2-3 weeks.
