### ISSUE TITLE
Publish Pipeline Artifact fails with exception VssResourceNotFoundException

### ISSUE THREAD

**Issue by brianobr** [Microsoft/azure-pipelines-tasks#9245]
[7.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2727959/7.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - On-premises
    - Version: Azure Devops Server 2019 RC1 
- Agent - Private: 
        - OS of the machine running the agent and the agent version: Windows 10 Pro 10.0.17134
        - Agent version 2.141.1
## Issue Description
The task Publish Pipeline Artifact fails with exception VssResourceNotFoundException API resource location 53e6e1e0-7444-47ea-93cd-44e6ddf264e6 is not registered on _myServer_

![image](https://user-images.githubusercontent.com/5707009/50701725-44224e00-1014-11e9-86fa-bcd4422db5e1.png)

### Task logs
Attached

### Error logs
2019-01-04T17:18:55.1707757Z ##[error]Microsoft.VisualStudio.Services.WebApi.VssResourceNotFoundException: API resource location 53e6e1e0-7444-47ea-93cd-44e6ddf264e6 is not registered on https://myServer/DefaultCollection/.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.CreateRequestMessageAsync(HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, String mediaType)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.PutDedupAsync(Guid locationId, DedupIdentifier dedupId, DedupCompressedBuffer chunkBuffer, KeepUntilBlobReference keepUntil, SummaryKeepUntilReceipt receipt, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.PutNodeAndKeepUntilReferenceAsync(NodeDedupIdentifier dedupId, DedupCompressedBuffer chunkBuffer, KeepUntilBlobReference keepUntil, SummaryKeepUntilReceipt receipt, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UploadSession.UploadNodeAsyncInternal(NodeDedupIdentifier nodeId, DedupNode node, FileStream file, String path, Nullable`1 offset, String indent, KeepUntilReceipt[] receipts, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UploadSession.UploadNodeAsync(DedupNode node, String path, FileStream file, Nullable`1 offset, String indent, Boolean alreadyLocked, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.BuildDropManager.PublishAsync(String sourceDirectory, ArtifactPublishOptions artifactPublishOptions, String manifestFileOutputPath, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.UploadAsync(AgentTaskPluginExecutionContext context, Guid projectId, Int32 buildId, String name, String source, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTask.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, String targetPath, String artifactName, CancellationToken token)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2019-01-04T17:18:55.1724755Z ##[debug]Processed: ##vso[task.logissue type=error;]Microsoft.VisualStudio.Services.WebApi.VssResourceNotFoundException: API resource location 53e6e1e0-7444-47ea-93cd-44e6ddf264e6 is not registered on https://tfs.corepointhealth.net/DefaultCollection/.%0D%0A   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.CreateRequestMessageAsync(HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, String mediaType)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.PutDedupAsync(Guid locationId, DedupIdentifier dedupId, DedupCompressedBuffer chunkBuffer, KeepUntilBlobReference keepUntil, SummaryKeepUntilReceipt receipt, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.PutNodeAndKeepUntilReferenceAsync(NodeDedupIdentifier dedupId, DedupCompressedBuffer chunkBuffer, KeepUntilBlobReference keepUntil, SummaryKeepUntilReceipt receipt, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UploadSession.UploadNodeAsyncInternal(NodeDedupIdentifier nodeId, DedupNode node, FileStream file, String path, Nullable`1 offset, String indent, KeepUntilReceipt[%5D receipts, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UploadSession.UploadNodeAsync(DedupNode node, String path, FileStream file, Nullable`1 offset, String indent, Boolean alreadyLocked, CancellationToken cancellationToken)%0D%0A   at Microsoft.VisualStudio.Services.BlobStore.WebApi.BuildDropManager.PublishAsync(String sourceDirectory, ArtifactPublishOptions artifactPublishOptions, String manifestFileOutputPath, CancellationToken cancellationToken)%0D%0A   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.UploadAsync(AgentTaskPluginExecutionContext context, Guid projectId, Int32 buildId, String name, String source, CancellationToken cancellationToken)%0D%0A   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTask.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, String targetPath, String artifactName, CancellationToken token)%0D%0A   at Agent.Plugins.PipelineArtifact.PipelineArtifactTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)%0D%0A   at Agent.PluginHost.Program.Main(String[%5D args)
2019-01-04T17:18:55.1758168Z ##[debug]Processed: ##vso[task.complete result=Failed;]

**Comment by mitchdenny** [comment]
Hi Brian - unfortunately Pipeline Artifacts are not available in on-premises TFS.

**Comment by mitchdenny** [comment]
Re-opening because there is probably a bug here in that the task shouldn't have been available for use anyway.

**Comment by brianobr** [comment]
Ah.... that was self-inflicted. A colleague was working with the product group to enable a currently disabled feature we need, and that was enabled. Mystery solved... no need to spend time researching a bug that isn't there.

We had enabled VisualStudio.ReleaseManagement.CustomBuildArtifactsTasks, VisualStudio.ReleaseManagement.BuildArtifactsTasks, 
VisualStudio.ReleaseManagement.SelectiveArtifactsDownload

**Comment by mitchdenny** [comment]
That explains it! :)

**Comment by AJH16** [comment]
Is this still true?  I encountered a similar error with Azure Devops Server 2019 and don't believe we enabled the feature manually.

**Comment by shieldsjared** [comment]
Also seeing this on Azure Devops Server 2019, and we didnt enable anything manually (that we can recall).

**Comment by michaelkollmann** [comment]
So it's still not supported by Azure DevOps Server but available for use?

**Comment by Wo1fie** [comment]
Is this not supported by Azure DevOps Server 2019 1.0 or 1.1RC?  I appear to be experiencing this issue using 1.0 and after upgrading to 1.1RC.

**Comment by pcbt** [comment]
I am getting this error on my on-premise TFS. Is this still issue?
