### ISSUE TITLE
SSH File Copy - Handshake Timeout Issue

### ISSUE THREAD

**Issue by shajusukumaran** [microsoft/azure-pipelines-tasks#9300]
## Troubleshooting
Error occurs while connecting to remote RHEL server to perform SSH File Copy operation. I tried exploring the issue further by creating a sample code to connect to the remote server using ssh2. This is what i found:

Executing the below code, gave me the same handshake error:
```
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('uptime', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: '*.*.*.*',
  port: 22,
  username: '****',
  password: '****'
});
```
Error output:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at Timeout._onTimeout (C:\vsts-extensions\vsts-samples\node_modules\ssh2\lib\client.js:676:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```
But, when i tried with the below code (wherein i specified an increased readyTimeout value; the default readyTimeout value is 20s), it worked fine for me:
```
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('uptime', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: '*.*.*.*',
  port: 22,
  username: '****',
  password: '****',
  readyTimeout: 50000
});
```
Output:
```
Client :: ready
STDOUT:  19:37:49 up 98 days, 22:10,  2 users,  load average: 1.28, 1.31, 1.28

Stream :: close :: code: 0, signal: undefined
```

**So, it looks like in our network it takes more time to complete the handshake. Is there a way for me to pass the readyTimeout to the task?**

## Environment
- Server - Azure Pipelines
- Agent - Private: 
OS: RHEL 7.4
Agent Version: 2.140.0
Task Version: 0.142.2

## Issue Description
Timed out while waiting for handshake.

### Task logs
```
2019-01-10T18:46:35.4526265Z ##[debug]Evaluating condition for step: 'Run shell commands on remote machine'
2019-01-10T18:46:35.4555634Z ##[debug]Evaluating: succeeded()
2019-01-10T18:46:35.4581188Z ##[debug]Evaluating succeeded:
2019-01-10T18:46:35.4615925Z ##[debug]=> True
2019-01-10T18:46:35.4641085Z ##[debug]Result: True
2019-01-10T18:46:35.4660285Z ##[section]Starting: Run shell commands on remote machine
2019-01-10T18:46:35.4763606Z ==============================================================================
2019-01-10T18:46:35.4775210Z Task         : SSH
2019-01-10T18:46:35.4787028Z Description  : Run shell commands or a script on a remote machine using SSH
2019-01-10T18:46:35.4800299Z Version      : 0.142.2
2019-01-10T18:46:35.4811370Z Author       : Microsoft Corporation
2019-01-10T18:46:35.4822498Z Help         : [More Information](http://go.microsoft.com/fwlink/?LinkId=821892)
2019-01-10T18:46:35.4834553Z ==============================================================================
2019-01-10T18:46:35.7668865Z ##[debug]agent.workFolder=/home/****/vsts-agt-generic-01/_work
2019-01-10T18:46:35.7704346Z ##[debug]loading inputs and endpoints
2019-01-10T18:46:35.7738596Z ##[debug]loading INPUT_SSHENDPOINT
2019-01-10T18:46:35.7772880Z ##[debug]loading INPUT_RUNOPTIONS
2019-01-10T18:46:35.7807125Z ##[debug]loading INPUT_COMMANDS
2019-01-10T18:46:35.7842946Z ##[debug]loading INPUT_SCRIPTPATH
2019-01-10T18:46:35.7877766Z ##[debug]loading INPUT_FAILONSTDERR
2019-01-10T18:46:35.7912753Z ##[debug]loading ENDPOINT_AUTH_3f3f3649-7ba7-4b3f-ad0f-b0da16c0241f
2019-01-10T18:46:35.7934826Z ##[debug]loading ENDPOINT_AUTH_SCHEME_3f3f3649-7ba7-4b3f-ad0f-b0da16c0241f
2019-01-10T18:46:35.7957544Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_3f3f3649-7ba7-4b3f-ad0f-b0da16c0241f_USERNAME
2019-01-10T18:46:35.8054847Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_3f3f3649-7ba7-4b3f-ad0f-b0da16c0241f_PASSWORD
2019-01-10T18:46:35.8081098Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-01-10T18:46:35.8103235Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-01-10T18:46:35.8126989Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-01-10T18:46:35.8150396Z ##[debug]loading SECRET_AGENT_PROXYPASSWORD
2019-01-10T18:46:35.8172925Z ##[debug]loaded 13
2019-01-10T18:46:35.9402811Z ##[debug]check path : /home/****/vsts-agt-generic-01/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.142.2/task.json
2019-01-10T18:46:35.9427641Z ##[debug]set resource file to: /home/****/vsts-agt-generic-01/_work/_tasks/SSH_91443475-df55-4874-944b-39253b558790/0.142.2/task.json
2019-01-10T18:46:35.9452863Z ##[debug]system.culture=en-US
2019-01-10T18:46:35.9476116Z ##[debug]sshEndpoint=3f3f3649-7ba7-4b3f-ad0f-b0da16c0241f
2019-01-10T18:46:35.9497120Z ##[debug]3f3f3649-7ba7-4b3f-ad0f-b0da16c0241f auth param username = ***
2019-01-10T18:46:35.9520456Z ##[debug]3f3f3649-7ba7-4b3f-ad0f-b0da16c0241f auth param password = ***
2019-01-10T18:46:35.9542267Z ##[debug]3f3f3649-7ba7-4b3f-ad0f-b0da16c0241f data host = 10.185.203.14
2019-01-10T18:46:35.9567528Z ##[debug]3f3f3649-7ba7-4b3f-ad0f-b0da16c0241f data port = 22
2019-01-10T18:46:35.9589554Z ##[debug]Using username and password for ssh connection.
2019-01-10T18:46:35.9609618Z ##[debug]runOptions=commands
2019-01-10T18:46:35.9633196Z ##[debug]commands=sudo chmod 777 -R /home/***/***
2019-01-10T18:46:35.9653826Z ##[debug]failOnStdErr=true
2019-01-10T18:46:35.9669102Z Trying to establish an SSH connection to ***@*.*.*.*:22
2019-01-10T18:46:55.9780499Z ##[debug]task result: Failed
2019-01-10T18:46:55.9887559Z ##[error]Failed to connect to remote machine. Verify the SSH service connection details. Error: Error: Timed out while waiting for handshake.
2019-01-10T18:46:55.9920626Z ##[debug]Processed: ##vso[task.issue type=error;]Failed to connect to remote machine. Verify the SSH service connection details. Error: Error: Timed out while waiting for handshake.
2019-01-10T18:46:55.9949095Z ##[debug]Processed: ##vso[task.complete result=Failed;]Failed to connect to remote machine. Verify the SSH service connection details. Error: Error: Timed out while waiting for handshake.
2019-01-10T18:46:56.0826870Z ##[section]Finishing: Run shell commands on remote machine
```

**Comment by leantk** [comment]
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days
