### ISSUE TITLE
Unable to deploy Function App for Linux

### ISSUE THREAD

**Issue by altmnt** [microsoft/azure-pipelines-tasks#9445]
I am trying to deploy a Function App for Linux using Azure App Service Deploy Task Version 4.* in devops VSTS. App is using Consumption Plan.
Task fails with the message 
```
2019-01-29T12:20:42.5049909Z ##[error]Failed to deploy web package to App Service.
2019-01-29T12:20:42.5054448Z ##[error]Error: Error: Failed to deploy web package to App Service. Error: connect ECONNREFUSED 127.0.0.1:443
2019-01-29T12:20:44.5883936Z Successfully added release annotation to the Application Insight : <app>
2019-01-29T12:20:44.5947508Z ##[warning]Error: Failed to update deployment history. Error: Error: connect ECONNREFUSED 127.0.0.1:443
2019-01-29T12:20:44.9049004Z App Service Application URL: http://<app>.azurewebsites.net
2019-01-29T12:20:44.9183310Z ##[section]Finishing: Azure App Service Deploy: <app>
```
Is there anything I am missing? Project works well when I deploy via `func azure functionapp publish`

**Comment by SumiranAgg** [comment]
@altmnt Thanks for reporting this issue. The task currently doesnt support deployment to dunction app using consumption plan. The support should be added in next couple of sprints.

In the meanwhile you can use Azure CLI task as a workaround. Use below command:
az webapp config appsettings set -g MyResourceGroup -n MyUniqueApp --settings WEBSITE_RUN_FROM_PACKAGE=<SASUrl>

We will update this thread when the feature is available.

**Comment by altmnt** [comment]
Sounds good. Thanks.

**Comment by damienwebdev** [comment]
@SumiranAgg as a question about this task, if we wanted to do the following:

1. Provision a new Linux consumption app in a known resource group
2. Update the Linux consumption app from a build artifact

Would this be possible currently with the tasks, or would we need to orchestrate this with CLI commands?

**Comment by damienwebdev** [comment]
Just to add to this, as there's a preview task available #9901

**Comment by SumiranAgg** [comment]
@damienwebdev To provision a new linux consumption app in a known resource group you can use Azure resource group deployment task. Sample template can be found here https://github.com/Azure/azure-quickstart-templates/tree/f605b4b13a6d372d9f40142323e128b5e5e58440/101-function-app-create-dynamic.

To update the app with new build artifact you will have to use azure cli task. Where you will upload a package to a storage account. Create a SAS url for this uploaded package and use this generated URL in WEBSITE_RUN_FROM_PACKAGE app setting.

Also as mentioned in the bug you mentioned. The feature development is done and should be available in upcoming sprint.

**Comment by SumiranAgg** [comment]
The support for consumption plan for function apps has been added to Azure function app task.

**Comment by erfannariman** [comment]
I am getting the following error when deploying from GitHub actions, is this the same issue? Shouldn't be right since support for consumption plan for function apps is added:

```
Error: ECONNREFUSED
Error: Execution Exception (state: ValidateAzureResource) (step: Invocation)
Error:   When request Azure resource at ValidateAzureResource, Get Function App Settings : Failed to acquire app settings (SCM)
Error:     Failed to fetch Kudu App Settings.
Error: connect ECONNREFUSED 127.0.0.1:443
Error:       Error: Failed to fetch Kudu App Settings.
Error: connect ECONNREFUSED 127.0.0.1:443
    at Kudu.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:62:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
