### ISSUE TITLE
Azure App Service Deploy Task fails

### ISSUE THREAD

**Issue by PSausM** [Microsoft/azure-pipelines-tasks#9671]
Issue Description

The azure App Service Deploy task suddenly fails. I has worked for months now without any error. 
Now I get the following error. Any idea?

### Task logs

2019-02-22T17:52:53.6405729Z Retrying to deploy the package.
2019-02-22T17:52:53.6449936Z [command]"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp='D:\a\r1\a\Kundenportal CD Azure Test\release\Client\build' -dest:iisApp='blexon2dev',ComputerName='https://blexon2dev-blexon2dev-staging.scm.azurewebsites.net:443/msdeploy.axd?site=blexon2dev',UserName='$blexon2dev__blexon2dev-staging',Password='***',AuthType='Basic' -skip:Directory=App_Data -userAgent:VSTS_e6c8d448-098c-4863-a48a-f18fe3b0cdb6_release_1_342_342_1
2019-02-22T17:52:54.1640488Z Info: Using ID 'b83b6039-3ec3-49fd-8088-b0be843693ee' for connections to the remote server.
2019-02-22T17:52:54.9173681Z Info: Adding MSDeploy.iisApp (MSDeploy.iisApp).
2019-02-22T17:52:55.8766757Z ##[error]Failed to deploy web package to App Service.
2019-02-22T17:52:55.8778007Z ##[error]Error: (2/22/2019 5:52:54 PM) An error occurred when the request was processed on the remote computer.
Error: Retrieving the COM class factory for component with CLSID {2B72133B-3F5B-4602-8952-803546CE3344} failed due to the following error: 800703fa Illegal operation attempted on a registry key that has been marked for deletion. (Exception from HRESULT: 0x800703FA).
   at System.Runtime.Remoting.RemotingServices.AllocateUninitializedObject(RuntimeType objectType)
   at System.Runtime.Remoting.Activation.ActivationServices.CreateInstance(RuntimeType serverType)
   at System.Runtime.Remoting.Activation.ActivationServices.IsCurrentContextOK(RuntimeType serverType, Object[] props, Boolean bNewObj)
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at Microsoft.Web.Administration.ConfigurationManager.CreateAdminManager[TClass,TInterface](WebConfigurationMap webConfigMap, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.CreateWritableAdminManager(WebConfigurationMap webConfigMap, String configPathToEdit, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.CreateConfiguration(WebConfigurationMap configMap, String configPathToEdit, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.GetConfiguration(String rawConfigurationPath, String cacheKey, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.GetAdministrationConfiguration(WebConfigurationMap configMap, String configurationPath)
   at Microsoft.Web.Delegation.DeploymentAuthorization.GetAuthProviderFromAdminConfig()
   at Microsoft.Web.Delegation.DeploymentAuthorization.get_Provider()
   at Microsoft.Web.Deployment.DelegationHelper.ImpersonateForOperation(String deploymentAction, String deploymentProvider, String deploymentPath, DelegationContextCache cache)
   at Microsoft.Web.Deployment.DelegationHelper.ImpersonateForOperation(String deploymentAction, DeploymentObject deploymentObject)
   at Microsoft.Web.Deployment.DeploymentObject.Add(DeploymentObject source, DeploymentSyncContext syncContext)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAdd(DeploymentObject destObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData asyncData, Nullable`1 passId, String user, String siteName)
Error count: 1.

2019-02-22T17:52:55.8780247Z ##[error]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
2019-02-22T17:52:57.8055378Z Successfully updated deployment History at https://blexon2dev-blexon2dev-staging.scm.azurewebsites.net/api/deployments/3421550857977418
2019-02-22T17:52:57.8162157Z ##[section]Finishing: Azure App Service Deploy: blexon2dev

**Comment by SumiranAgg** [comment]
@PSausM I see a variety of errors here. Can you share complete debug logs at RM_Customer_Queries@microsoft.com? To get debug logs add variable "System.debug" with value "true" to your release and redeploy. Collect logs and share for further investigation.

Also is this a private / hosted agent? Which windows server are you using?

**Comment by PSausM** [comment]
This is a hosted agent.
I sent you the debug log via mail.

**Comment by PSausM** [comment]
I tried restart, but that didn't solve the problem. To use Version 4 helped. It works now. I still find it very strange, that this suddenly fails after so many months. Thanks for help.

**Comment by quigamdev** [comment]
I have the same issue. First I thought that it's some bug in my configuration. Then I thought it's the deployment task that is broken. Finally, we tried to push deployment via VS Publish and the result is the same. Restart did not work. Did you found out what causes this issue?

**Comment by infoTrainingym** [comment]
I have just run on this issue. 

It was working normally, but then it start fail. In my case, the project deploy correctly on others webapp.

We find out there was an app setting _MSDEPLOY_RENAME_LOCKED_FILES_ with value 1. After removed it, it works again.
