### ISSUE TITLE
Cannot download Github release using built-in task

### ISSUE THREAD

**Issue by BotellaA** [Microsoft/azure-pipelines-tasks#9742]
I am using Azure Pipelines with hosted Ubuntu and I cannot manage to download my Github release.
Here is the yml:
```
    - task: DownloadGitHubRelease@0
      inputs:
        connection: Geode-solutions_release
        userRepository: Geode-solutions/OpenGeode
        defaultVersionType: 'latest'
        itemPattern: '*Linux*'
```

And here is the link to the pasted log file [https://dev.azure.com/GeodeSolutions/Geode/_build/results?buildId=83&view=logs&jobId=3c1207c1-a75c-5bbe-bbb3-e7acf08a93c4](https://dev.azure.com/GeodeSolutions/Geode/_build/results?buildId=83&view=logs&jobId=3c1207c1-a75c-5bbe-bbb3-e7acf08a93c4):
```
##[debug]Evaluating condition for step: 'DownloadGitHubRelease'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: DownloadGitHubRelease
==============================================================================
Task         : Download GitHub Release
Description  : Downloads a GitHub Release from a repository.
Version      : 0.148.0
Author       : Microsoft Corporation
Help         : [More Information](https://aka.ms/AA3x715)
==============================================================================
##[debug]agent.TempDirectory=/home/vsts/work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_CONNECTION
##[debug]loading INPUT_USERREPOSITORY
##[debug]loading INPUT_DEFAULTVERSIONTYPE
##[debug]loading INPUT_ITEMPATTERN
##[debug]loading INPUT_DOWNLOADPATH
##[debug]loading ENDPOINT_AUTH_998ee3fa-c158-4667-992e-44e21c2cbe0b
##[debug]loading ENDPOINT_AUTH_SCHEME_998ee3fa-c158-4667-992e-44e21c2cbe0b
##[debug]loading ENDPOINT_AUTH_PARAMETER_998ee3fa-c158-4667-992e-44e21c2cbe0b_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loading SECRET_GITHUB-TOKEN
##[debug]loaded 13
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/lib.json
##[debug]adding resource file: /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/lib.json
##[debug]system.culture=en-US
##[debug]check path : /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/task.json
##[debug]adding resource file: /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/task.json
##[debug]system.culture=en-US
##[debug]connection=998ee3fa-c158-4667-992e-44e21c2cbe0b
##[debug]userRepository=Geode-solutions/OpenGeode
##[debug]defaultVersionType=latest
##[debug]itemPattern=*Linux*
##[debug]downloadPath=/home/vsts/work/1/a
##[debug]version=null
##[debug]998ee3fa-c158-4667-992e-44e21c2cbe0b auth param AccessToken = ***
##[debug]VSTS_HTTP_RETRY=undefined
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3600) Warning: Use Cipheriv for counter mode of aes-256-ctr
Downloading assets of release 15720616 from: https://api.github.com/repos/Geode-solutions/OpenGeode/releases/15720616/assets
##[debug]release.artifact.download.parallellimit=undefined
##[debug]System.Debug=true
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Enqueued 1 for processing.
##[debug]Nothing to process currently, respawing worker 1 after 1 sec.
##[debug]patternRoot: 'null'
##[debug]matchOptions.debug: 'false'
##[debug]matchOptions.nobrace: 'true'
##[debug]matchOptions.noglobstar: 'false'
##[debug]matchOptions.dot: 'true'
##[debug]matchOptions.noext: 'false'
##[debug]matchOptions.nocase: 'false'
##[debug]matchOptions.nonull: 'false'
##[debug]matchOptions.matchBase: 'false'
##[debug]matchOptions.nocomment: 'false'
##[debug]matchOptions.nonegate: 'false'
##[debug]matchOptions.flipNegate: 'false'
##[debug]pattern: '*Linux*'
##[debug]applying include pattern against original list
##[debug]1 matches
##[debug]1 final results
##[debug]Processing OpenGeode-v1.5.0-Linux.tar.gz
##[debug]Error getting file OpenGeode-v1.5.0-Linux.tar.gz: Error: Failed request: (statusCode) 404
Retrying download of OpenGeode-v1.5.0-Linux.tar.gz, retry count: 1
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Total Items: 2, Processed: 1, Processing: 1, Queued: 0, Skipped: 0, Failed: 0, Time elapsed: 5.002secs
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]patternRoot: 'null'
##[debug]matchOptions.debug: 'false'
##[debug]matchOptions.nobrace: 'true'
##[debug]matchOptions.noglobstar: 'false'
##[debug]matchOptions.dot: 'true'
##[debug]matchOptions.noext: 'false'
##[debug]matchOptions.nocase: 'false'
##[debug]matchOptions.nonull: 'false'
##[debug]matchOptions.matchBase: 'false'
##[debug]matchOptions.nocomment: 'false'
##[debug]matchOptions.nonegate: 'false'
##[debug]matchOptions.flipNegate: 'false'
##[debug]pattern: '*Linux*'
##[debug]applying include pattern against original list
##[debug]1 matches
##[debug]1 final results
##[debug]Processing OpenGeode-v1.5.0-Linux.tar.gz
##[debug]Error getting file OpenGeode-v1.5.0-Linux.tar.gz: Error: Failed request: (statusCode) 404
Retrying download of OpenGeode-v1.5.0-Linux.tar.gz, retry count: 2
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Total Items: 2, Processed: 1, Processing: 1, Queued: 0, Skipped: 0, Failed: 0, Time elapsed: 10.003secs
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]patternRoot: 'null'
##[debug]matchOptions.debug: 'false'
##[debug]matchOptions.nobrace: 'true'
##[debug]matchOptions.noglobstar: 'false'
##[debug]matchOptions.dot: 'true'
##[debug]matchOptions.noext: 'false'
##[debug]matchOptions.nocase: 'false'
##[debug]matchOptions.nonull: 'false'
##[debug]matchOptions.matchBase: 'false'
##[debug]matchOptions.nocomment: 'false'
##[debug]matchOptions.nonegate: 'false'
##[debug]matchOptions.flipNegate: 'false'
##[debug]pattern: '*Linux*'
##[debug]applying include pattern against original list
##[debug]1 matches
##[debug]1 final results
##[debug]Processing OpenGeode-v1.5.0-Linux.tar.gz
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Error getting file OpenGeode-v1.5.0-Linux.tar.gz: Error: Failed request: (statusCode) 404
Retrying download of OpenGeode-v1.5.0-Linux.tar.gz, retry count: 3
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Total Items: 2, Processed: 1, Processing: 1, Queued: 0, Skipped: 0, Failed: 0, Time elapsed: 15.005secs
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]patternRoot: 'null'
##[debug]matchOptions.debug: 'false'
##[debug]matchOptions.nobrace: 'true'
##[debug]matchOptions.noglobstar: 'false'
##[debug]matchOptions.dot: 'true'
##[debug]matchOptions.noext: 'false'
##[debug]matchOptions.nocase: 'false'
##[debug]matchOptions.nonull: 'false'
##[debug]matchOptions.matchBase: 'false'
##[debug]matchOptions.nocomment: 'false'
##[debug]matchOptions.nonegate: 'false'
##[debug]matchOptions.flipNegate: 'false'
##[debug]pattern: '*Linux*'
##[debug]applying include pattern against original list
##[debug]1 matches
##[debug]1 final results
##[debug]Processing OpenGeode-v1.5.0-Linux.tar.gz
##[debug]Error getting file OpenGeode-v1.5.0-Linux.tar.gz: Error: Failed request: (statusCode) 404
Retrying download of OpenGeode-v1.5.0-Linux.tar.gz, retry count: 4
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Total Items: 2, Processed: 1, Processing: 1, Queued: 0, Skipped: 0, Failed: 0, Time elapsed: 20.006secs
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]patternRoot: 'null'
##[debug]matchOptions.debug: 'false'
##[debug]matchOptions.nobrace: 'true'
##[debug]matchOptions.noglobstar: 'false'
##[debug]matchOptions.dot: 'true'
##[debug]matchOptions.noext: 'false'
##[debug]matchOptions.nocase: 'false'
##[debug]matchOptions.nonull: 'false'
##[debug]matchOptions.matchBase: 'false'
##[debug]matchOptions.nocomment: 'false'
##[debug]matchOptions.nonegate: 'false'
##[debug]matchOptions.flipNegate: 'false'
##[debug]pattern: '*Linux*'
##[debug]applying include pattern against original list
##[debug]1 matches
##[debug]1 final results
##[debug]Processing OpenGeode-v1.5.0-Linux.tar.gz
##[debug]Error getting file OpenGeode-v1.5.0-Linux.tar.gz: Error: Failed request: (statusCode) 404
##[debug]SYSTEM.HOSTTYPE=build
##[debug]BUILD.DEFINITIONNAME=Geode-solutions.OpenGeodeIO
##[debug]BUILD.BUILDID=83
##[debug]SYSTEM.TEAMFOUNDATIONSERVERURI=https://dev.azure.com/GeodeSolutions/
##[debug]SYSTEM.TEAMPROJECT=Geode
##[debug]BUILD.BUILDID=83
##[debug]TASK.DISPLAYNAME=DownloadGitHubRelease
##[debug]SYSTEM.JOBID=3c1207c1-a75c-5bbe-bbb3-e7acf08a93c4
##[debug]AGENT.VERSION=2.148.0
##[debug]AGENT.OS=Linux
##[debug]AGENT.NAME=Hosted Agent
##[debug]Processed: ##vso[telemetry.publish area=artifact-engine;feature=reliability]{"hostType":"build","definitionName":"[NonEmail:Geode-solutions.OpenGeodeIO]","processId":"83","processUrl":"https://dev.azure.com/GeodeSolutions/Geode/_build?buildId=83","taskDisplayName":"DownloadGitHubRelease","jobid":"3c1207c1-a75c-5bbe-bbb3-e7acf08a93c4","agentVersion":"2.148.0","agentOS":"Linux","agentName":"Hosted Agent","version":"0.1.26","issueType":"error","errorMessage":"{\"stack\":\"Error: Failed request: (statusCode) 404\\n    at WebClient.<anonymous> (/home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:41:23)\\n    at next (native)\\n    at /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:7:65\\n    at __awaiter (/home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:3:12)\\n    at WebClient.processResponse (/home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:35:16)\\n    at httpc.get.then (/home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:20:22)\\n    at process._tickCallback (internal/process/next_tick.js:109:7)\",\"message\":\"Failed request: (statusCode) 404\",\"statusCode\":404,\"result\":\"Not Found\"}"}
##[debug]SYSTEM.HOSTTYPE=build
##[debug]BUILD.DEFINITIONNAME=Geode-solutions.OpenGeodeIO
##[debug]BUILD.BUILDID=83
##[debug]SYSTEM.TEAMFOUNDATIONSERVERURI=https://dev.azure.com/GeodeSolutions/
##[debug]SYSTEM.TEAMPROJECT=Geode
##[debug]BUILD.BUILDID=83
##[debug]TASK.DISPLAYNAME=DownloadGitHubRelease
##[debug]SYSTEM.JOBID=3c1207c1-a75c-5bbe-bbb3-e7acf08a93c4
##[debug]AGENT.VERSION=2.148.0
##[debug]AGENT.OS=Linux
##[debug]AGENT.NAME=Hosted Agent
##[debug]Processed: ##vso[telemetry.publish area=DownloadGitHubRelease;feature=reliability]{"hostType":"build","definitionName":"[NonEmail:Geode-solutions.OpenGeodeIO]","processId":"83","processUrl":"https://dev.azure.com/GeodeSolutions/Geode/_build?buildId=83","taskDisplayName":"DownloadGitHubRelease","jobid":"3c1207c1-a75c-5bbe-bbb3-e7acf08a93c4","agentVersion":"2.148.0","agentOS":"Linux","agentName":"Hosted Agent","version":{"Major":0,"Minor":148,"Patch":0},"issueType":"error","errorMessage":"{\"stack\":\"Error: Failed request: (statusCode) 404\\n    at WebClient.<anonymous> (/home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:41:23)\\n    at next (native)\\n    at /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:7:65\\n    at __awaiter (/home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:3:12)\\n    at WebClient.processResponse (/home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:35:16)\\n    at httpc.get.then (/home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.148.0/node_modules/artifact-engine/Providers/webClient.js:20:22)\\n    at process._tickCallback (internal/process/next_tick.js:109:7)\",\"message\":\"Failed request: (statusCode) 404\",\"statusCode\":404,\"result\":\"Not Found\"}"}
##[debug]task result: Failed
##[error]Error: Failed request: (statusCode) 404
##[debug]Processed: ##vso[task.issue type=error;]Error: Failed request: (statusCode) 404
##[debug]Processed: ##vso[task.complete result=Failed;]Error: Failed request: (statusCode) 404
##[debug]Aborting respawning worker, as download failed for some file(s).
##[debug]Aborting respawning worker, as download failed for some file(s).
##[debug]Aborting respawning worker, as download failed for some file(s).
##[debug]Total Items: 2, Processed: 1, Processing: 0, Queued: 0, Skipped: 0, Failed: 1, Time elapsed: 25.007secs
##[section]Finishing: DownloadGitHubRelease
```
Thanks for your help

**Comment by gykuma** [comment]
@BotellaA, thanks for reporting the issue. We have found an issue with how we handle authentication while downloading private repo release assets. We are fixing the issue and it should be available to your account in few days.

**Comment by BotellaA** [comment]
@gykuma Thanks! How to know when you push a new release?

**Comment by gykuma** [comment]
@BotellaA I will update you here once it's available.

**Comment by andrelvahter** [comment]
Not sure if this ADO agent itself, but are there plans todo something with warnings 
(node:xxxx) Warning: Use Cipheriv for counter mode of aes-256-ctr ?

**Comment by gykuma** [comment]
It's not in agent but some modules that the task depends on. We already have it in our backlog and will be fixing it in couple of weeks.

**Comment by BotellaA** [comment]
@gykuma Any update?

**Comment by gykuma** [comment]
@BotellaA the fix should be available for your account. Please let us know if it works for you?

**Comment by BotellaA** [comment]
@gykuma Yes, it downloads the release. Thanks

**Comment by mbrancato** [comment]
I'm having this same issue with 0.148.2 where I cannot download private releases.

I get the following using 'latest' or 'specificTag', but nothing is actually downloaded. The task succeeds.

```Downloading assets of release 16187206 from: https://api.github.com/repos/xxxxxxxx/xxxxxxx/releases/16187206/assets
Total Files: 0, Processed: 0, Skipped: 0, Failed: 0, Download time: 1.01 secs, Download size: 0Bytes
```

If I use 'specificVersion' then the result is a 404 and the task hits an error.

**Comment by gykuma** [comment]
@mbrancato are you using this task in build or in release? Can you please re-run the build/release after adding `System.Debug` set to `true` in variables and then share the logs. Please share the account name as well.

You can share the logs and details here: RM_Customer_Queries@microsoft.com

**Comment by gykuma** [comment]
@mbrancato I'm closing the issue for now. Please feel free to reopen in case you are still facing this issue.
