### ISSUE TITLE
Conditionally update build number with PowerShell in container job

### ISSUE THREAD

**Issue by brent-robinson** [microsoft/azure-pipelines-tasks#9761]
## Environment
**Software:** Azure Pipelines
**Pool VM Image:** ubuntu-16.04
**Container:** mcr.microsoft.com/powershell

## Issue Description

When running a container job and executing a PowerShell task, if the build number is conditionally set in PowerShell it will fail. I can reproduce this with this definition.

```
name: 0.0.0-a

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: mcr.microsoft.com/powershell

steps:
- powershell: |
    if ($true) {
      Write-Output "##vso[build.updatebuildnumber]0.0.1-b"
    } else {
      Write-Output "##vso[build.updatebuildnumber]0.0.1-c"
    }
```

This problem also occurs if you use a PowerShell variable for the build number. It does not occur when running an agent job (instead of container job).

### Task logs

Please let me know if required.

### Error logs

```
##[section]Async Command Start: Update Build Number
##[section]Async Command End: Update Build Number
##[error]TF209010: The build number format 0.0.1-c" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
##[debug]Microsoft.TeamFoundation.Build.WebApi.BuildNumberFormatException: TF209010: The build number format 0.0.1-c" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildServer.UpdateBuildNumber(Int32 buildId, String buildNumber, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildCommandExtension.UpdateBuildNumberAsync(IAsyncCommandContext context, VssConnection connection, Guid projectId, Int32 buildId, String buildNumber, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.AsyncCommandContext.WaitAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[section]Async Command Start: Update Build Number
Update build number to 0.0.1-b for build 775
##[section]Async Command End: Update Build Number
```

**Comment by brent-robinson** [comment]
Redacted debug log for the task.

```
##[debug]Evaluating condition for step: 'PowerShell'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: PowerShell
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Windows, macOS, or Linux.
Version      : 2.140.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
==============================================================================
##[debug]Handler: /__a/externals/node/bin/node
##[debug]HandlerArg: /__w/_tasks/PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1/2.140.2/powershell.js
##[debug]HandlerWorkDir: /__w/1/s
##[debug]Set env: INPUT_TARGETTYPE=inline
##[debug]Set env: INPUT_FILEPATH=/__w/1/s
##[debug]Set env: INPUT_ARGUMENTS=
##[debug]Set env: INPUT_SCRIPT=if ($true) {
  Write-Output "##vso[build.updatebuildnumber]0.0.1-b"
} else {
##[debug]Update build number for build: 775 to: 0.0.1-c" at backend.
##[debug]Processed:   Write-Output "##vso[build.updatebuildnumber]0.0.1-c"
}
##[debug]Set env: INPUT_ERRORACTIONPREFERENCE=stop
##[debug]Set env: INPUT_FAILONSTDERR=false
##[debug]Set env: INPUT_IGNORELASTEXITCODE=false
##[debug]Set env: INPUT_PWSH=false
##[debug]Set env: INPUT_WORKINGDIRECTORY=/__w/1/s
##[debug]Set env: ENDPOINT_URL_SYSTEMVSSCONNECTION=https://***.visualstudio.com/
##[debug]Set env: ENDPOINT_AUTH_SYSTEMVSSCONNECTION={"parameters":{"AccessToken":***},"scheme":"OAuth"}
##[debug]Set env: ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION=OAuth
##[debug]Set env: ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN=***
##[debug]Set env: SYSTEM_TASKINSTANCEID=7dae026f-9e99-5d65-075e-3f7579577f94
##[debug]Set env: BUILD_DEFINITIONNAME=***
##[debug]Set env: AGENT_ROOTDIRECTORY=/__w
##[debug]Set env: BUILD_REQUESTEDFOR=***
##[debug]Set env: BUILD_REPOSITORY_GIT_SUBMODULECHECKOUT=False
##[debug]Set env: SYSTEM_HOSTTYPE=build
##[debug]Set env: SYSTEM=build
##[debug]Set env: BUILD_REQUESTEDFOREMAIL=****
##[debug]Set env: AGENT_CONTAINERID=7ba58d74acbf0664d932dd83111214e1e2d3cb68e866bd5aad3628c5590884f4
##[debug]Set env: agent.jobstatus=Succeeded
##[debug]Set env: AGENT_JOBSTATUS=Succeeded
##[debug]Set env: AGENT_OSARCHITECTURE=X64
##[debug]Set env: AGENT_HOMEDIRECTORY=/__a
##[debug]Set env: BUILD_STAGINGDIRECTORY=/__w/1/a
##[debug]Set env: SYSTEM_TIMELINEID=e95dd489-cd0e-4010-a1dd-6aa504be27fb
##[debug]Set env: SYSTEM_SERVERTYPE=Hosted
##[debug]Set env: AGENT_NAME=Hosted Agent
##[debug]Set env: SYSTEM_JOBID=12f1170f-54f2-53f3-20dd-22fc7dff55f9
##[debug]Set env: AGENT_TOOLSDIRECTORY=/__t
##[debug]Set env: BUILD_CONTAINERID=3153670
##[debug]Set env: BUILD_BUILDID=775
##[debug]Set env: AGENT_OS=Linux
##[debug]Set env: AGENT_RETAINDEFAULTENCODING=false
##[debug]Set env: SYSTEM_DEFINITIONNAME=***
##[debug]Set env: AGENT_CONTAINERNETWORK=vsts_network_97e485b37d854d0585eef7279445fa9f
##[debug]Set env: SYSTEM_DEBUG=true
##[debug]Set env: AGENT_WORKFOLDER=/__w
##[debug]Set env: SYSTEM_JOBPARALLELISMTAG=Private
##[debug]Set env: AGENT_JOBNAME=Job
##[debug]Set env: BUILD_REQUESTEDFORID=92958099-86e7-4f57-baeb-1735e216edf1
##[debug]Set env: SYSTEM_JOBIDENTIFIER=Job.__default
##[debug]Set env: BUILD_SOURCEVERSIONAUTHOR=***
##[debug]Set env: AGENT_ACCEPTTEEEULA=True
##[debug]Set env: AGENT_MACHINENAME=fv-az77
##[debug]Set env: AGENT_VERSION=2.147.1
##[debug]Set env: SYSTEM_TEAMFOUNDATIONSERVERURI=https://***.visualstudio.com/
##[debug]Set env: SYSTEM_TASKDISPLAYNAME=PowerShell
##[debug]Set env: BUILD_ARTIFACTSTAGINGDIRECTORY=/__w/1/a
##[debug]Set env: AGENT_TEMPDIRECTORY=/__w/_temp
##[debug]Set env: BUILD_SOURCEVERSIONMESSAGE=Added diag
##[debug]Set env: SYSTEM_JOBDISPLAYNAME=Job
##[debug]Set env: BUILD_BUILDNUMBER=0.0.0-a
##[debug]Set env: BUILD_REPOSITORY_NAME=***
##[debug]Set env: AGENT_DIAGNOSTIC=true
##[debug]Set env: SYSTEM_TASKDEFINITIONSURI=https://***.visualstudio.com/
##[debug]Set env: SYSTEM_PULLREQUEST_ISFORK=False
##[debug]Set env: SYSTEM_PIPELINESTARTTIME=2019-03-08 15:36:58+11:00
##[debug]Set env: COMMON_TESTRESULTSDIRECTORY=/__w/1/TestResults
##[debug]Set env: BUILD_SOURCEBRANCHNAME=mvp
##[debug]Set env: AGENT_ID=6
##[debug]Set env: BUILD_REPOSITORY_LOCALPATH=/__w/1/s
##[debug]Set env: SYSTEM_ENABLEACCESSTOKEN=SecretVariable
##[debug]Set env: BUILD_QUEUEDBY=***
##[debug]Set env: BUILD_REPOSITORY_ID=2cc42c0c-6c29-436c-81ca-80f51f200ee6
##[debug]Set env: SYSTEM_TASKINSTANCENAME=PowerShell
##[debug]Set env: SYSTEM_ISSCHEDULED=False
##[debug]Set env: VSTS_PROCESS_LOOKUP_ID=vsts_0c9e37c8-b451-441b-8c6b-ccace9f104a8
##[debug]Set env: SYSTEM_PHASENAME=Job
##[debug]Set env: SYSTEM_PLANID=e95dd489-cd0e-4010-a1dd-6aa504be27fb
##[debug]Set env: BUILD_REPOSITORY_PROVIDER=TfsGit
##[debug]Set env: SYSTEM_JOBNAME=__default
##[debug]Set env: BUILD_REPOSITORY_URI=https://***.visualstudio.com/***/_git/***
##[debug]Set env: SYSTEM_ARTIFACTSDIRECTORY=/__w/1/a
##[debug]Set env: SYSTEM_TEAMPROJECTID=53e3375b-336e-4450-9a95-68fd8502930f
##[debug]Set env: SYSTEM_COLLECTIONID=b6e9054b-f6c5-4160-8c65-b89df8b43579
##[debug]Set env: TASK_DISPLAYNAME=PowerShell
##[debug]Set env: BUILD_DEFINITIONVERSION=1
##[debug]Set env: AZURE_HTTP_USER_AGENT=VSTS_b6e9054b-f6c5-4160-8c65-b89df8b43579_build_27_0
##[debug]Set env: BUILD_REPOSITORY_CLEAN=False
##[debug]Set env: AGENT_BUILDDIRECTORY=/__w/1
##[debug]Set env: BUILD_SOURCESDIRECTORY=/__w/1/s
##[debug]Set env: SYSTEM_DEFAULTWORKINGDIRECTORY=/__w/1/s
##[debug]Set env: BUILD_SOURCEVERSION=ff8c2e7f09179bbc38c047c8432e7671709561c1
##[debug]Set env: AGENT_DISABLELOGPLUGIN_TESTRESULTLOGPLUGIN=true
##[debug]Set env: SYSTEM_COLLECTIONURI=https://***.visualstudio.com/
##[debug]Set env: SYSTEM_DEFINITIONID=27
##[debug]Set env: BUILD_REASON=Manual
##[debug]Set env: SYSTEM_PHASEID=3a3a2a60-14c7-570b-14a4-fa42ad92f52a
##[debug]Set env: BUILD_SOURCEBRANCH=refs/heads/feature/mvp
##[debug]Set env: SYSTEM_TEAMFOUNDATIONCOLLECTIONURI=https://***.visualstudio.com/
##[debug]Set env: SYSTEM_CULTURE=en-US
##[debug]Set env: MSDEPLOY_HTTP_USER_AGENT=VSTS_b6e9054b-f6c5-4160-8c65-b89df8b43579_build_27_0
##[debug]Set env: BUILD_BUILDURI=vstfs:///Build/Build/775
##[debug]Set env: SYSTEM_PHASEDISPLAYNAME=Job
##[debug]Set env: SYSTEM_WORKFOLDER=/__w
##[debug]Set env: SYSTEM_JOBATTEMPT=1
##[debug]Set env: SYSTEM_TEAMPROJECT=***
##[debug]Set env: BUILD_BINARIESDIRECTORY=/__w/1/b
##[debug]Set env: BUILD_QUEUEDBYID=92958099-86e7-4f57-baeb-1735e216edf1
##[debug]Set env: VSTS_PUBLIC_VARIABLES=["system.taskInstanceId","build.definitionName","agent.RootDirectory","build.requestedFor","build.repository.git.submodulecheckout","system.hosttype","system","build.requestedForEmail","agent.containerid","agent.jobstatus","agent.osarchitecture","agent.homedirectory","build.stagingdirectory","system.timelineId","system.servertype","agent.name","system.jobId","agent.ToolsDirectory","build.containerId","build.buildId","agent.os","agent.retainDefaultEncoding","system.definitionName","agent.containernetwork","system.debug","agent.workfolder","system.jobParallelismTag","agent.jobname","build.requestedForId","system.jobIdentifier","build.sourceVersionAuthor","agent.acceptteeeula","agent.machinename","agent.version","system.TeamFoundationServerUri","system.taskDisplayName","build.artifactstagingdirectory","agent.TempDirectory","build.sourceVersionMessage","system.jobDisplayName","build.buildNumber","build.Repository.name","agent.diagnostic","system.taskDefinitionsUri","system.pullRequest.isFork","system.pipelineStartTime","common.testresultsdirectory","build.sourceBranchName","agent.id","build.repository.localpath","system.enableAccessToken","build.queuedBy","build.repository.id","system.taskInstanceName","system.isScheduled","VSTS_PROCESS_LOOKUP_ID","system.phaseName","system.planId","build.repository.provider","system.jobName","build.repository.uri","system.artifactsdirectory","system.teamProjectId","system.collectionId","task.displayname","build.definitionVersion","AZURE_HTTP_USER_AGENT","build.repository.clean","agent.builddirectory","build.sourcesdirectory","system.defaultworkingdirectory","build.sourceVersion","agent.disablelogplugin.TestResultLogPlugin","system.collectionUri","system.definitionId","build.reason","system.phaseId","build.sourceBranch","system.teamFoundationCollectionUri","system.culture","MSDEPLOY_HTTP_USER_AGENT","build.buildUri","system.phaseDisplayName","system.workfolder","system.jobAttempt","system.teamProject","build.binariesdirectory","build.queuedById"]
##[debug]Set env: SECRET_SYSTEM_ACCESSTOKEN=***
##[debug]Set env: VSTS_SECRET_VARIABLES=["system.accessToken"]
##[debug]agent.TempDirectory=/__w/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_TARGETTYPE
##[debug]loading INPUT_FILEPATH
##[debug]loading INPUT_SCRIPT
##[debug]loading INPUT_ERRORACTIONPREFERENCE
##[debug]loading INPUT_FAILONSTDERR
##[debug]loading INPUT_IGNORELASTEXITCODE
##[debug]loading INPUT_PWSH
##[debug]loading INPUT_WORKINGDIRECTORY
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 12
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : /__w/_tasks/PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1/2.140.2/task.json
##[debug]adding resource file: /__w/_tasks/PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1/2.140.2/task.json
##[debug]system.culture=en-US
##[debug]errorActionPreference=stop
##[debug]failOnStderr=false
##[debug]ignoreLASTEXITCODE=false
##[debug]workingDirectory=/__w/1/s
##[debug]check path : /__w/1/s
##[debug]targetType=inline
##[debug]script=if ($true) {
  Write-Output "##vso[build.updatebuildnumber]0.0.1-b"
} else {
  Write-Output "##vso[build.updatebuildnumber]0.0.1-c"
}
Generating script.
##[debug]Agent.Version=2.147.1
##[debug]agent.tempDirectory=/__w/_temp
##[debug]check path : /__w/_temp
##[debug]which 'pwsh'
##[debug]found: '/usr/bin/pwsh'
##[debug]which '/usr/bin/pwsh'
##[debug]found: '/usr/bin/pwsh'
##[debug]which '/usr/bin/pwsh'
##[debug]found: '/usr/bin/pwsh'
##[debug]/usr/bin/pwsh arg: -NoLogo
##[debug]/usr/bin/pwsh arg: -NoProfile
##[debug]/usr/bin/pwsh arg: -NonInteractive
##[debug]/usr/bin/pwsh arg: -Command
##[debug]/usr/bin/pwsh arg: . '/__w/_temp/a16c5607-cb78-448c-9897-06c4f9be199c.ps1'
##[debug]exec tool: /usr/bin/pwsh
##[debug]arguments:
##[debug]   -NoLogo
##[debug]   -NoProfile
##[debug]   -NonInteractive
##[debug]   -Command
##[debug]   . '/__w/_temp/a16c5607-cb78-448c-9897-06c4f9be199c.ps1'
[command]/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/__w/_temp/a16c5607-cb78-448c-9897-06c4f9be199c.ps1'
##[debug]Update build number for build: 775 to: 0.0.1-b at backend.
##[debug]Processed: ##vso[build.updatebuildnumber]0.0.1-b
##[debug]$LASTEXITCODE is not set.
##[debug]rc:0
##[debug]success:true
##[debug]Handler exit code: 0
##[section]Async Command Start: Update Build Number
##[section]Async Command End: Update Build Number
##[error]TF209010: The build number format 0.0.1-c" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
##[debug]Microsoft.TeamFoundation.Build.WebApi.BuildNumberFormatException: TF209010: The build number format 0.0.1-c" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildServer.UpdateBuildNumber(Int32 buildId, String buildNumber, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildCommandExtension.UpdateBuildNumberAsync(IAsyncCommandContext context, VssConnection connection, Guid projectId, Int32 buildId, String buildNumber, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.AsyncCommandContext.WaitAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[section]Async Command Start: Update Build Number
Update build number to 0.0.1-b for build 775
##[section]Async Command End: Update Build Number
##[section]Finishing: PowerShell
```

**Comment by brent-robinson** [comment]
The real world scenario I'm trying to run is to reformat the build number depending on the branch.

```
name: 0.1.$(Build.BuildId)-$(Build.SourceBranchName)
# ... rest of file ...
steps:
- powershell: |
    if(@('master', 'develop').Contains($env:BuildSourceBranchName))
    {
      Write-Output "##vso[build.updatebuildnumber]$($env:BuildBuildNumber.Substring(0, $env:BuildBuildNumber.Length - $env:BuildSourceBranchName.Length - 1))"
    }
  displayName: Version
  env:
    BuildBuildNumber: $(Build.BuildNumber)
    BuildSourceBranchName: $(Build.SourceBranchName)
```

This fails with

```
##[error]TF209010: The build number format $($env:BuildBuildNumber.Substring(0, $env:BuildBuildNumber.Length - $env:BuildSourceBranchName.Length - 1))" contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
```

However breaking it up so `##vso` is never found in the source seems to workaround the issue.

```
name: 0.1.$(Build.BuildId)-$(Build.SourceBranchName)
# ... rest of file ...
steps:
- powershell: |
    if(@('master', 'develop').Contains($env:BuildSourceBranchName))
    {
      $command = "vso[build.updatebuildnumber]$($env:BuildBuildNumber.Substring(0, $env:BuildBuildNumber.Length - $env:BuildSourceBranchName.Length - 1))"
      Write-Output "##$command"
    }
  displayName: Version
  env:
    BuildBuildNumber: $(Build.BuildNumber)
    BuildSourceBranchName: $(Build.SourceBranchName)
```

This issue only occurs in container jobs.

**Comment by moswald** [comment]
I think the clue is here early in the log:

```
##[debug]Evaluating condition for step: 'PowerShell'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: PowerShell
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Windows, macOS, or Linux.
Version      : 2.140.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
==============================================================================
##[debug]Handler: /__a/externals/node/bin/node
##[debug]HandlerArg: /__w/_tasks/PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1/2.140.2/powershell.js
##[debug]HandlerWorkDir: /__w/1/s
##[debug]Set env: INPUT_TARGETTYPE=inline
##[debug]Set env: INPUT_FILEPATH=/__w/1/s
##[debug]Set env: INPUT_ARGUMENTS=
##[debug]Set env: INPUT_SCRIPT=if ($true) {
  Write-Output "##vso[build.updatebuildnumber]0.0.1-b"
} else {
##[debug]Update build number for build: 775 to: 0.0.1-c" at backend.
##[debug]Processed:   Write-Output "##vso[build.updatebuildnumber]0.0.1-c"
}
```
Notice how it suddenly tried to update the build number? The powershell task is being executed by a javascript file, which sees your input and tries to execute it, rather than pass it along as an input variable.

@bryanmacfarlane It looks like your team owns this task.

**Comment by Silvenga** [comment]
Thanks @moswald for the hint. This totally works as a work around for anyone impacted:

```
Write-Host ("##" + "vso[build.updatebuildnumber]$buildNumber")
```

**Comment by leantk** [comment]
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days

**Comment by sxlino** [comment]
Just started with this program and hadn’t had a computer to fix these
issues but will get to it as soon as possible. Give me a little more time.
