### ISSUE TITLE
PublishPipelineArtifact@0 Fails to upload artifact with error Service Unavailable

### ISSUE THREAD

**Issue by SinZ163** [Microsoft/azure-pipelines-tasks#9840]
## Environment
- Server - **Azure Pipelines**

- Agent - **Hosted Ubuntu 1604**

## Issue Description

When attempting to upload node project, getting error `Service Unavailable`

![image](https://user-images.githubusercontent.com/767456/54409301-2f5fe600-473a-11e9-8e84-e49d76de6aa9.png)

### Task logs
```
2019-03-15T04:49:00.7221552Z ##[debug]Evaluating condition for step: 'PublishPipelineArtifact'
2019-03-15T04:49:00.7222120Z ##[debug]Evaluating: SucceededNode()
2019-03-15T04:49:00.7222215Z ##[debug]Evaluating SucceededNode:
2019-03-15T04:49:00.7222413Z ##[debug]=> True
2019-03-15T04:49:00.7222631Z ##[debug]Result: True
2019-03-15T04:49:00.7222781Z ##[section]Starting: PublishPipelineArtifact
2019-03-15T04:49:00.7225142Z ==============================================================================
2019-03-15T04:49:00.7225196Z Task         : Publish Pipeline Artifact
2019-03-15T04:49:00.7225900Z Description  : Publish Pipeline Artifact
2019-03-15T04:49:00.7225946Z Version      : 0.139.0
2019-03-15T04:49:00.7225979Z Author       : Microsoft Corporation
2019-03-15T04:49:00.7226014Z Help         : Publish a local directory or file as a named artifact for the current pipeline.
2019-03-15T04:49:00.7226415Z ==============================================================================
2019-03-15T04:49:01.1476319Z Uploading pipeline artifact from /home/vsts/work/1/s for build #60
2019-03-15T04:49:42.9977266Z ##[error]Service Unavailable
2019-03-15T04:49:42.9987821Z ##[debug]Processed: ##vso[task.logissue type=error;]Service Unavailable
2019-03-15T04:49:42.9989163Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2019-03-15T04:49:43.0142320Z ##[debug]   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.CreateDataProviderAsync(String location, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.CreateBulidDropManager(AgentTaskPluginExecutionContext context, VssConnection connection)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.UploadAsync(AgentTaskPluginExecutionContext context, Guid projectId, Int32 buildId, String name, String source, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTask.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, String targetPath, String artifactName, CancellationToken token)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2019-03-15T04:49:43.0191957Z ##[section]Finishing: PublishPipelineArtifact
```
# Misc notes

This exact build pipeline was working earlier, but at some point the pipeline stopped working even when working on known working builds

**Comment by mitchdenny** [comment]
This error corresponds to a service incident that we had last night which has since been resolved. I'm closing this ticket for now (if you are still experiencing the problem let us know):

https://status.dev.azure.com/_event/109939066

**Comment by haflare** [comment]
I'm having the same issue.

**Server:** Azure Pipelines
**Agent:** Hosted Windows 2019 with VS2019
**Location:** Australia
**Last Successful Build:** Apr 3, 2020 at 6:55 PM GMT+11
**The First Failure After the Last Successful Buid:** Apr 6, 2020 at 11:59 AM GMT+10

Between the last successful and the first failure, we don't have any run, so I can't say when exactly it started happening.

**Comment by haflare** [comment]
It worked again after the 4th attempt...
