### ISSUE TITLE
Can't install dbus-python on Ubuntu-16.04 agents using python3.6

### ISSUE THREAD

**Issue by mattrunchey** [microsoft/azure-pipelines-tasks#9878]
## Environment
- Server - Azure Pipelines 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/iotile/arch_node_tasks/_build/results?buildId=155

- Agent -  Hosted Ubuntu 1604

## Issue Description

Seems that the python 3.6 environment is unable to install dbus. It isn't a dbus-python issue, because it installs just fine on a Docker image defined as such:
```
FROM python:3.6

RUN apt-get update && apt-get install -y \
  curl \
  pkg-config \
  libdbus-1-dev \
  libdbus-glib-1-dev

ENV C_FORCE_ROOT 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /var/app
WORKDIR  /var/app
RUN pip install -U pip wheel setuptools
RUN pip install dbus-python
```

### Task logs
You can easily replicate this with the following pipeline:
```jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      #Python37:
      #  python.version: '3.7'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: sudo apt-get update && sudo apt-get install -y curl pkg-config libdbus-1-dev libdbus-glib-1-dev
    displayName: 'Update packages'

  - script: |
      python -m pip install --upgrade pip && pip install -r requirements.txt
      python -m pip install dbus-python
    displayName: 'Install dependencies'
```
The 3.5 matrix job will pass, 3.6 will fail as below:

```
Installing collected packages: dbus-python
  Running setup.py install for dbus-python: started
    Running setup.py install for dbus-python: finished with status 'error'
    Complete output from command /opt/hostedtoolcache/Python/3.6.5/x64/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8djdg381/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_4rega16/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    creating /tmp/pip-install-8djdg381/dbus-python/build
    creating /tmp/pip-install-8djdg381/dbus-python/build/temp.linux-x86_64-3.6
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking minix/config.h usability... no
    checking minix/config.h presence... no
    checking for minix/config.h... no
    checking whether it is safe to define __EXTENSIONS__... yes
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking for style of include used by make... GNU
    checking whether UID '1001' is supported by ustar format... yes
    checking whether GID '999' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking dependency style of gcc... gcc3
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking for native Windows host... no
    checking how to print strings... printf
    checking for a sed that does not truncate output... /bin/sed
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for inline... inline
    checking for gawk... (cached) gawk
    checking for python3.6... /opt/hostedtoolcache/Python/3.6.5/x64/python
    checking for a version of Python >= '2.1.0'... yes
    checking for a version of Python >= '2.7'... yes
    checking for the distutils Python package... yes
    checking for Python include path... -I/opt/hostedtoolcache/Python/3.6.5/x64/include/python3.6m
    checking for Python library path... -L/usr/local/lib -lpython3.6m
    checking for Python site-packages path... /opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages
    checking python extra libraries... -lpthread -ldl  -lutil -lm
    checking python extra linking flags... -Xlinker -export-dynamic
    checking consistency of all components of python development environment... no
    configure: error: in `/tmp/pip-install-8djdg381/dbus-python/build/temp.linux-x86_64-3.6':
    configure: error:
      Could not link test program to Python. Maybe the main Python library has been
      installed in some non-standard library path. If so, pass it to configure,
      via the LIBS environment variable.
      Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
      ============================================================================
       ERROR!
       You probably have to install the development version of the Python package
       for your distribution.  The exact name of this package varies among them.
      ============================================================================
    
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8djdg381/dbus-python/setup.py", line 109, in <module>
        tests_require=['tap.py'],
      File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-8djdg381/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-8djdg381/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/opt/hostedtoolcache/Python/3.6.5/x64/python', '--prefix=/tmp/pip-install-8djdg381/dbus-python/build/temp.linux-x86_64-3.6/prefix']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/opt/hostedtoolcache/Python/3.6.5/x64/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8djdg381/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_4rega16/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-8djdg381/dbus-python/
##[error]Bash exited with code '1'.
```

**Comment by mattrunchey** [comment]
For reference, this is an issue with all versions of python that aren't 3.5 on the ubuntu 16.04 agent (3.4, 3.6, and 3.7)

**Comment by espoelstra** [comment]
This can also happen in an Ubuntu 18.04 container, the issue is that the system Python packages require a certain version which conflicts with the updated version. Your best bet is to use `pyenv` or a `virtualenv` when compiling a project that requires the dbus-python package.

**Comment by leantk** [comment]
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days
